### ISSUE TITLE
Add record: T'Sou-ke First Nation

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#1]
Summary: Add a new organization to ROR

Name of organization to be added | T'Sou-ke First Nation

Organization website | https://www.tsoukenation.com/

Wikipedia | https://en.wikipedia.org/wiki/T%27Sou-ke_Nation

Briefly explain why you are requesting a ROR ID for this organization and how the ROR ID will be used. | T'Sou-ke Nation is working with Ocean Networks Canada (ONC) on water quality testing. As a result, we will be collecting data that we would like T'Sou-ke Nation to always receive proper attribution and credit for. We would also like to use ROR ID for any future data that T'Sou-ke collects.

Provide DOI(s) or links for research associated with this organization, such as published articles that include the organization's name as an affiliation. If DOIs or links are not available, describe the research-related activities of this organization. | At this time the main data being collected is for water quality testing in the Sooke basin to collect evidence of pollution. We will use this data to come up with a plan to bring the water to acceptable levels so that we can fish our clam beds once again.

Other relevant metadata about the organization (e.g., name variants in other languages, related records in ROR, links to external records such as Wikidata) | http://www.tsoukenation.com/, Sooke, tsouke, t'souke, tsou-ke

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01v7jw115 in release v1.0.
