### ISSUE TITLE
Update Flight Research Institute named after M.M. Gromov https://ror.org/04sb28h93

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#10]
**Description**: Update alias

**Details**:
Organization: Flight Research Institute named after M.M. Gromov
ROR ID: https://ror.org/04sb28h93
Change to be made: Change alias from JSC "LII them MMGromova" to Gromov Flight Research Institute, GFRI

**Curator recommendation (AS):**
- Update primary name to Gromov Flight Research Institute
- Move current primary name (Flight Research Institute named after M.M. Gromov) to alias
- Remove current alias  'JSC "LII them MMGromova"' 
- Add GFRI to acronym
- Add Wikidata: Q282717
- Add Wikipedia: https://en.wikipedia.org/wiki/Gromov_Flight_Research_Institute

Update: change.name==Gromov Flight Research Institute; add.aliases==Flight Research Institute named after M.M. Gromov; delete.aliases==JSC "LII them MMGromova"; add.acronyms==GFRI; add.Wikidata==Q282717; add.wikipedia_url==https://en.wikipedia.org/wiki/Gromov_Flight_Research_Institute;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
