### ISSUE TITLE
Add a new organization to ROR: Finnish Social Science Data Archive (FSD)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#100]
Summary of request: Add a new organization to ROR

Name of organization: 
Name of organization: Finnish Social Science Data Archive (FSD)
Website: https://www.fsd.tuni.fi/en/
Link to publications: https://doi.org/10.1177/2158244016685136
https://doi.org/10.29173/iq936
https://doi.org/10.5281/zenodo.4020399
Wikipedia page: https://fi.wikipedia.org/wiki/Yhteiskuntatieteellinen_tietoarkisto
Wikidata ID: https://www.wikidata.org/wiki/Q11902697
ISNI ID: https://isni.org/isni/0000000474486517
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: FSD, Yhteiskuntatieteellinen tietoarkisto (FI), Finlands Samhällsvetenskapliga Dataarkiv
Acronym/abbreviation: 
Related organizations: https://ror.org/033003e23 (related)
City: City centre campus Virta, Åkerlundinkatu 5 B, FI-33014 Tampere University, FINLAND
Country: 
Other information about this request: urn:nbn:fi:research-infras-201607256 (https://research.fi/en/results/infrastructure/Yhteiskuntatieteellinen%20tietoarkisto)

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05wmhj005 in release v1.0.
