### ISSUE TITLE
Modify the information in an existing ROR record: 
 Leibniz Centre for Tropical Marine Research (ZMT) (https://ror.org/019w00969)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#101]
Summary of request: Modify the information in an existing ROR record

Name of organization:  Leibniz Centre for Tropical Marine Research (ZMT)
ROR ID: https://ror.org/019w00969

Description of change: Please change our name in the registry to :  Leibniz Centre for Tropical Marine Research (ZMT)

------
Reviewer assessment of change needed:
* Change main label to 'Leibniz Centre for Tropical Marine Research'
* Keep the old label as an alias
* Add German label 'Leibniz Zentrum für Marine Tropenforschung'

Update: delete.labels==Leibniz-Zentrum für Marine Tropenökologie; add.labels==Leibniz Zentrum für Marine Tropenforschung*German; add.aliases==Leibniz-Zentrum für Marine Tropenökologie;

**Comment by mariagould** [comment]
The main name has been updated in the September ROR/GRID update but we should keep this active to add in the old name as an alias ("Leibniz Center for Tropical Marine Ecology")

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
