### ISSUE TITLE
Project: Norwegian research institutions (pt. 2)

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1012]
As a follow-up to #661, Sikt - Norwegian Agency for Shared Services in Education and Research has suggested we add 5 more institutions to ROR. Metadata has been provided in the linked spreadsheet, beginning with the entry marked, "New as of 08/23."

https://docs.google.com/spreadsheets/d/1ubvpTLbBfZSRCEjMQO3atZ-EaPvtAjWDSwhK6fLbggM/edit#gid=0

**Comment by mariagould** [comment]
I concur the four organizations are in scope and should be added to ROR.

**Comment by adambuttrick** [comment]
Records added in rc-v1.5.

ROR ID | Organization name
-- | --
https://ror.org/020mpkg22 | University College of Norwegian Correctional Service
https://ror.org/01v408m73 | Norges Bank
https://ror.org/05vmk8z81 | Norwegian Railway Museum
https://ror.org/04vgq9s06 | Norwegian Centre for Organic Agriculture
