### ISSUE TITLE
Add a new organization to ROR: Institute of Mental Health and Neurosciences

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#102]
Summary of request: Add a new organization to ROR

Name of organization: Institute of Mental Health and Neurosciences
Website: http://imhans.ac.in/
Link to publications: 10.1093/schbul/sbab007, 10.1007/s40737-020-00201-9, 10.1007/s40615-021-00964-2
Wikipedia page: https://en.wikipedia.org/wiki/Institute_of_Mental_Health_and_Neurosciences
Wikidata ID: https://www.wikidata.org/wiki/Q98113942
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: IMHANS
Related organizations: 
City: Kozhikode, Kerala State
Country: India
Other information about this request: full address: Institute of Mental Health and Neurosciences (IMHANS) Government Medical College Campus, Kozhikode Kerala State, India, 673008

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/013aa2c03 in release v1.0.
