### ISSUE TITLE
Add a new organization to ROR:  Connecticut Geological Survey

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#103]
Summary of request: Add a new organization to ROR

Name of organization: Connecticut Geological Survey, DEEP
Website: https://www.ct.gov/deep/geology
Link to publications: https://scholar.google.com/citations?user=1F1t8AgAAAAJ&hl=en
Wikipedia page: 
Wikidata ID: 
ISNI ID: https://isni.org/isni/0000000097538333
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: CGNHS, CGS
Related organizations: https://ror.org/02hv6yw42 (parent)
City: 79 Elm Street, Hartford, CT, 06106 USA
Country: 
Other information about this request:

**Comment by mariagould** [comment]
Relationships:

https://ror.org/02hv6yw42, parent

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02ts2sn48 in release v1.0.
