### ISSUE TITLE
Add a new organization to ROR: Flatiron Institute

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1030]
Summary of request: Add a new organization to ROR

Name of organization: Flatiron Institute
Website: https://www.simonsfoundation.org/flatiron
Link to publications: 
Organization type: Nonprofit
Wikipedia page: https://en.wikipedia.org/wiki/Flatiron_Institute
Wikidata ID: Q30594395
ISNI ID: 0000 0004 7411 3681 
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/01cmst727 (parent)
City: NYC
Country: USA
Geonames ID: 5128581
Year established: 2016
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research arm of the Simons Foundation focused on computer science and mathematics research. Funds and employs researchers. Solid affiliation usage. Should be added to ROR.

Publication affiliation usage: https://doi.org/10.21468/scipostphys.10.4.091; https://doi.org/10.1167/jov.21.9.2654; https://doi.org/10.21203/rs.3.rs-385285/v1; https://doi.org/10.21468/scipostphyscodeb.4-r0.3; https://doi.org/10.7554/elife.74160.sa2; https://doi.org/10.21468/scipostphyscodeb.4

Google scholar affiliation usage: https://scholar.google.com/citations?user=KYpqau8AAAAJ; https://scholar.google.com/citations?user=hcmW-W0AAAAJ; https://scholar.google.com/citations?user=BtGwd3MAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0001-5442-8457 ; https://orcid.org/0000-0003-2631-4406 ; https://orcid.org/0000-0003-1540-7172
issue_references: None

**Comment by KellyStathis** [comment]
This looks good to me; agree this should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00sekdz59 in release v1.8.
