### ISSUE TITLE
Add a new organization to ROR: Hamburg Centre for Ultrafast Imaging

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1031]
Summary of request: Add a new organization to ROR

Name of organization: Hamburg Centre for Ultrafast Imaging
Website: https://www.cui.uni-hamburg.de
Link to publications: 
Organization type: Facility
Wikipedia page: https://en.wikipedia.org/wiki/Hamburg_Centre_for_Ultrafast_Imaging
Wikidata ID: Q20639175
ISNI ID:
GRID ID:
Crossref Funder ID: 501100019394
Other names for the organization: 
Acronym/abbreviation: CUI
Related organizations: https://ror.org/00g30e956 (parent)
City: Hamburg
Country: Germany
Geonames ID: 2911298
Year established: 2012
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Imaging facility and Cluster of Excellence hosted at the University of Hamburg. Funds and employs researchers. Solid affiliation usage. See discussion on #200 for other examples of these clusters in ROR.

Publication affiliation usage: https://doi.org/10.1002/ppsc.202100087; https://doi.org/10.29363/nanoge.nfm.2019.207; https://doi.org/10.7554/elife.48528.024; https://doi.org/10.1063/1.5091756; https://doi.org/10.29363/nanoge.nfm.2019.226; https://doi.org/10.1021/acs.jpclett.9b02622

Google Scholar affiliation usage: https://scholar.google.com/citations?user=cDukEXIAAAAJ; https://scholar.google.com/citations?user=q6Lw5jcAAAAJ; https://scholar.google.com/citations?user=puODHjYAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0003-0904-7254 ; https://orcid.org/0000-0001-6582-5984 ; https://orcid.org/0000-0002-7908-9778

**Comment by nlundvick** [comment]
Established, sufficiently independent organization that is clearly associated with research publications and activities.

- affiliation use: see examples provided by previous curator
- facility acknowledgements: https://doi.org/10.1002/9783527808465.EMC2016.5962; https://doi.org/10.1515/zna-2016-0326

In scope, add to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0149pv473 in release v1.8.
