### ISSUE TITLE
Add a new organization to ROR: Institute of Fluid Physics

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1032]
Summary of request: Add a new organization to ROR

Name of organization: Institute of Fluid Physics
Website: 
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID: Q39900689
ISNI ID: 0000 0004 1769 3616
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: IFP; CAEP IFP
Aliases: China Academy of Engineering Physics, Institute of Fluid Physics
Labels: 流体物理研究所*Chinese
Related organizations: https://ror.org/039vqpp67 (parent)
City: Mianyang
Country: China
Geonames ID: 1800627
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research institute and part of https://ror.org/039vqpp67. Funds and employs researchers. Solid affiliation usage. Should be added to ROR.

Publication affiliation usage: https://doi.org/10.2495/cmem130121; https://doi.org/10.1063/5.0064238; https://doi.org/10.4028/www.scientific.net/amm.477-478.1419; https://doi.org/10.1063/5.0089939; https://doi.org/10.1109/tps.2022.3168576; https://doi.org/10.1063/1.5047479

Google Scholar affiliation_usage: https://scholar.google.com/citations?user=UhbWrKkAAAAJ; https://scholar.google.com/citations?user=NgC-J10AAAAJ; https://scholar.google.com/citations?user=6qrYA84AAAAJ

ORCID affiliation usage: https://orcid.org/0000-0002-7440-2163 ; https://orcid.org/0000-0003-1029-7701 ; https://orcid.org/0000-0002-1562-2350

**Comment by nlundvick** [comment]
Other, similar CAEP child organizations in ROR (https://ror.org/00fzxtk71). Solid affiliation use (123 instances in AIP alone - https://aip.scitation.org/action/doSearch?field1=Affiliation&text1=Institute%20of%20Fluid%20Physics,%20CAEP&field2=AllField&text2=&Ppub=&Ppub=&AfterYear=&BeforeYear=&access=). Concur with first curator, add to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05rgwws51 in release v1.8.
