### ISSUE TITLE
Add a new organization to ROR: CROSS Neutron Science and Technology Center

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1034]
Summary of request: Add a new organization to ROR

Name of organization: CROSS Neutron Science and Technology Center
Website: https://neutron.cross.or.jp
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID: Q54914055
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Comprehensive Research Organization for Science and Society Neutron Science and Technology Center
Labels: CROSS中性子科学センター*Japanese
Acronym/abbreviation: CROSS NSTC
Related organizations: https://ror.org/03gb41d27 (parent)
City: Tokai
Country: Japan
Geonames ID: 2110767
Year established: 2016
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Neutron beam research facility that is part of https://ror.org/03gb41d27. Solid affiliation usage. Funds and employs researchers. In scope, per our facility tracking use case.

Publication affiliation usage: https://doi.org/10.7566/jpscp.33.011084; https://doi.org/10.5650/oleoscience.16.487; https://doi.org/10.4131/jshpreview.29.292

Google Scholar affiliation_usage: https://scholar.google.com/citations?user=Z8f2caEAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0001-5508-7092 ; https://orcid.org/0000-0002-0916-5333

**Comment by KellyStathis** [comment]
Agree this is in scope for ROR. I would add the full name to aliases: "Comprehensive Research Organization for Science and Society (CROSS) Neutron Science and Technology Center"

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05h0wd634 in release v1.8.
