### ISSUE TITLE
Add a new organization to ROR: Kansai Photon Science Institute

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1035]
Summary of request: Add a new organization to ROR

Name of organization: Kansai Photon Science Institute
Website: https://www.qst.go.jp/site/kansai
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID: Q39022389
ISNI ID: 0000 0004 7436 1394
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 関西光科学研究所*Japanese
Acronym/abbreviation:
Related organizations: https://ror.org/020rbyg91 (parent) 
City: Kizugawa
Country: Japan
Geonames ID: 1859202
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Light beam research facility and part of https://ror.org/020rbyg91. Funds and employs researchers. Solid affiliation usage. In scope for ROR by virtue of our facility tracking use case.

Publication affiliation usage: https://doi.org/10.2184/lsj.38.698; https://doi.org/10.1380/jsssj.29.413; https://doi.org/10.2184/lsj.42.2_160; https://doi.org/10.1063/1.4921854; https://doi.org/10.1117/12.2264966; https://doi.org/10.2184/lsj.46.3_134

Google Scholar affiliation_usage: https://scholar.google.com/citations?user=ntNc8ygAAAAJ; https://scholar.google.com/citations?user=xsQ2j7EAAAAJ; https://scholar.google.com/citations?user=rgmgwz4AAAAJ

ORCID affiliation usage: https://orcid.org/0000-0003-0508-4760 ; https://orcid.org/0000-0003-0420-3940

**Comment by nlundvick** [comment]
Established organization that is associated with research publications and activities. Affiliation use: [http://api.crossref.org/works/?query.affiliation=%22Kansai+Photon+Science+Institute%22](http://api.crossref.org/works/?query.affiliation=%22Kansai+Photon+Science+Institute%22). In scope under facility use case. Add to ROR.

**Comment by nlundvick** [comment]
@adambuttrick - I forgot to add that the website as entered does not resolve for me. Update to [https://www.qst.go.jp/site/kansai/](https://www.qst.go.jp/site/kansai/)?

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05mzhke23 in release v1.12.
