### ISSUE TITLE
Add a new organization to ROR: Soreq Nuclear Research Center

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1038]
Summary of request: Add a new organization to ROR

Name of organization: Soreq Nuclear Research Center
Website: https://www.gov.il/en/departments/nuclear-research-center
Link to publications: 
Organization type: Facility
Wikipedia page: https://en.wikipedia.org/wiki/Soreq_Nuclear_Research_Center
Wikidata ID: Q2092357
ISNI ID: 0000 0000 9067 5861
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels:  המרכז למחקר גרעיני שורק*Hebrew
Acronym/abbreviation:
Related organizations: https://ror.org/01bh2qr63 (parent)
City: Yavne
Country: Israel
Geonames ID: 293222
Year established: 1958
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Publication affiliation usage: https://doi.org/10.1117/12.951388; https://doi.org/10.1177/002199839002401102; https://doi.org/10.1117/12.968215; https://doi.org/10.2514/1.31868; https://doi.org/10.1177/073168449101000105; https://doi.org/10.2514/1.49532

Google Scholar affiliation usage: https://scholar.google.com/citations?user=Pa1djJcAAAAJ; https://scholar.google.com/citations?user=yohfVeAAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0003-2534-7732 ; https://orcid.org/0000-0003-2557-5129 ; https://orcid.org/0000-0001-8900-6297

**Comment by KellyStathis** [comment]
I agree this should be added to ROR. I am curious about the primary name in the ISNI record: https://isni.org/isni/0000000090675861 which comes from LCNAF: https://id.loc.gov/authorities/names/n80113181.html. However, I am not seeing use of this name widespread outside of ISNI and LC.

**Comment by adambuttrick** [comment]
@KellyStathis I'm not seeing it elsewhere either. Transliteration doesn't match the label I have on the record, but this Hebrew form is what is used by the goverment of Israel, e.g. https://www.gov.il/he/departments/nuclear-research-center/govil-landing-page

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/051rhng80 in release v1.8.
