### ISSUE TITLE
Add a new organization to ROR: European Laboratory for Non-Linear Spectroscopy

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1039]
Summary of request: Add a new organization to ROR

Name of organization: European Laboratory for Non-Linear Spectroscopy
Website: http://lens.unifi.it
Link to publications: 
Organization type: Facility
Wikipedia page: https://en.wikipedia.org/wiki/European_Laboratory_for_Non-Linear_Spectroscopy
Wikidata ID: Q3820241
ISNI ID: 0000 0000 9458 0261
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: Laboratorio europeo di spettroscopia non lineare*Italian
Acronym/abbreviation: LENS
Related organizations: https://ror.org/04jr1s763 (parent)
City: Sesto Fiorentino
Country: Italy
Geonames ID: 3166601
Year established: 1991
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Spectroscopy laboratory related to the University of Florence, but with European-wide funding and research utilization. Funds and employs researchers. Solid affiliation usage. Should be added to ROR.

Publication affiliation usage: https://doi.org/10.1021/ja200951f; https://doi.org/10.1002/9783527600441.oe1009; https://doi.org/10.1021/jp027194k; https://doi.org/10.1021/jp002677e; https://doi.org/10.1021/jp9082536; https://doi.org/10.1080/00268976.2013.782436

Google Scholar affiliation usage: https://scholar.google.com/citations?user=oF3DF24AAAAJ; https://scholar.google.com/citations?user=yL7SzwgAAAAJ; https://scholar.google.com/citations?user=T2xDw1wAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0002-6931-9234 ; https://orcid.org/0000-0002-9150-214X ; https://orcid.org/0000-0002-9799-9353

**Comment by nlundvick** [comment]
Established and sufficiently independent research facility with significant affiliation use. Concur, add to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04x48z588 in release v1.8.
