### ISSUE TITLE
Add a new organization to ROR: Barasat Government College

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1040]
Summary of request: Add a new organization to ROR

Name of organization: Barasat Government College
Website: http://www.bgc.org.in
Link to publications: 
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Barasat_Government_College
Wikidata ID: Q4858451
ISNI ID: 0000 0004 1772 5390
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City: Barasat
Country: India
Geonames ID: 1277065
Year established: 1950
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in India. Independent, top-level entity that funds and employs researchers. Solid affiliation usage. Should be added to ROR.

Publication affiliation usage: https://doi.org/10.1785/bssa0690030713; https://doi.org/10.1515/ring-2017-0004; https://doi.org/10.1142/s0217751x90000647; https://doi.org/10.1177/1420326x0101000104; https://doi.org/10.1142/s021827180901456x; https://doi.org/10.18052/www.scipress.com/ilns.33.37

Google Scholar affiliation usage: https://scholar.google.com/citations?user=2irR0MQAAAAJ; https://scholar.google.com/citations?user=tfR9_3IAAAAJ; https://scholar.google.com/citations?user=ixYrrk0AAAAJ

ORCID affiliation usage: https://orcid.org/0000-0002-2407-7729 ; https://orcid.org/0000-0001-7144-642X ; https://orcid.org/0000-0002-1016-475X

**Comment by nlundvick** [comment]
Established, top-level academic institution that is associated with research and has solid affiliation use (https://api.crossref.org/works/?query.affiliation="Barasat+Government+College"). Concur, add to ROR.

@adambuttrick - The website entered into the issue would not load for me. Should it be updated to https://bgc.ac.in/?

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02djvb753 in release v1.8.
