### ISSUE TITLE
Project: Several laboratories for University of Strasbourg - https://ror.org/00pg6eq24

### ISSUE THREAD

**Issue by HelloiseG** [ror-community/ror-updates#10489]
Attached is a list of research laboratories to be added in ror, in the column T we've add the RNSR id (French national Id for research structures). All the laboratories are linked to University of Strasbourg (parent) and sometimes with an other ror.
[new-ror-university_of_strabourg.xlsx](https://github.com/ror-community/ror-updates/files/14837695/new-ror-university_of_strabourg.xlsx)

**Comment by adambuttrick** [comment]
All corresponding record requests have been created and reviewed.

**Comment by adambuttrick** [comment]
All records added in release v1.45.
