### ISSUE TITLE
Modify the information in an existing ROR record: Superior School of Circus Arts https://ror.org/03khyar38

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#10480]
Summary of request: Modify the information in an existing ROR record

Name of organization: Superior School of Circus Arts
ROR ID: https://ror.org/03khyar38
Which part of the record needs to be changed? Name
Description of change: English translation of name should be changed to "College of Circus Arts". "École Supérieure" does not mean "Superior School".

Curator review: change name to Ecole Supérieure des Arts du Cirque*French. Add label Escuela Superior de Artes de Circo*Spanish. Replace link with https://www.esac.be. 

Update_v1: change.name==École Supérieure des Arts du Cirque; replace.labels==Escuela Superior de Artes de Circo*Spanish; replace.links==https://www.esac.be;$

Update_v2: ror_display.replace==École Supérieure des Arts du Cirque*French | label.replace==École Supérieure des Arts du Cirque*French; Escuela Superior de Artes de Circo*Spanish | website.replace==https://www.esac.be$

**Comment by adambuttrick** [comment]
Record updated in release v1.45.
