### ISSUE TITLE
Modify the information in an existing ROR record: National mining university of ukraine  (https://ror.org/05hkn5555)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#105]
Summary of request: Modify the information in an existing ROR record

Name of organization: National mining university of ukraine 
ROR ID: https://ror.org/05hkn5555
Which part of the record needs to be changed? 
Description of change: Change name to Dnipro University of Technology

Update: change.name==Dnipro University of Technology; add.aliases==National Mining University of Ukraine; delete.labels==Національний гірничий університет України; add.labels==Національний технічний університет «Дніпровська політехніка»*Ukrainian;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
