### ISSUE TITLE
Modify the information in an existing ROR record: 
Kyiv National University of Technologies and Design (https://ror.org/050vh8780)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#106]
Summary of request: Modify the information in an existing ROR record

Name of organization: Kyiv National University of Technologies and Design
ROR ID: https://ror.org/050vh8780

Description of change: University domain name has been changed. New domain name - https://knutd.edu.ua/

Update:delete.links==https://en.knutd.edu.ua/; add.links==https://knutd.edu.ua/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
