### ISSUE TITLE
Add a new organization to ROR: CI Compass

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#10641]
Summary of request: Add a new organization to ROR

Name of organization: CI Compass*English
Website: https://ci-compass.org
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: Q108615661
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: CI-Compass*English
Labels: 
Acronym/abbreviation: 
Related organizations: https://ror.org/03taz7m60 (parent) https://ror.org/01kg8sb98 (parent) https://ror.org/03r0ha626 (parent) https://ror.org/0405mnx93 (parent) https://ror.org/00mkhxb43 (parent) https://ror.org/01s91ey96 (parent) https://ror.org/04nh1dc89 (parent)
City: Los Angeles
Country: United States
Geonames ID: 5368361
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Part of ORCID funder integration.

**Comment by charlesvardeman** [comment]
The Wikidata ID for CI-Compass is Q108615661.

**Comment by adambuttrick** [comment]
@charlesvardeman Thanks! I've update the request to reflect.
