### ISSUE TITLE
Modify the information in an existing ROR record: Univerzitet Union Nikola Tesla - https://ror.org/02kgjn162

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#10866]
Summary of request: Modify the information in an existing ROR record

Name of organization: Univerzitet Union Nikola Tesla
ROR ID: https://ror.org/02kgjn162
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Other IDs for the organization
Description of change: Per their site (https://unt.edu.rs/en/), add English name: Union Nikola Tesla University
Add Serbian Cyrillic alias: Универзитет Унион Никола Тесла
Add abbreviation: UUNT
Add Wikidata: https://www.wikidata.org/wiki/Q104867336

Update: alias.label==Union Nikola Tesla University*English; Универзитет Унион Никола Тесла*Serbian | acronym.add==UUNT*Serbian | wikidata.all.add==Q104867336 | wikidata.preferred.replace==Q104867336 | website.replace==https://unt.edu.rs$

**Comment by adambuttrick** [comment]
Confirmed updates via the organization's site.
