### ISSUE TITLE
Add a new organization to ROR: Columban College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#10897]
Summary of request: Add a new organization to ROR

Name of organization: Columban College*English
Website: https://columban.edu.ph
Link to publications: http://api.crossref.org/works?query.affiliation=columban&select=DOI,author
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://en.wikipedia.org/wiki/Columban_College
Wikidata ID: Q5149544
ISNI ID: 0000 0004 0624 652X
GRID ID: 
Crossref Funder ID:
Other names for the organization: 
Aliases: Columban College, Inc.*English
Labels: Dalubhasaang Columban*tl
Acronym/abbreviation: 
Related organizations: 
City: Olongapo
Country: Philippines
Geonames ID: 1697175
Year established: 1961
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by adambuttrick** [comment]
College in the Philippines. Funds and employs researchers. Solid affiliation usage. Should be added.
