### ISSUE TITLE
Modify US Forest Service (https://ror.org/03zmjc935)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#109]
Summary of request: Modify the information in an existing ROR record

Name of organization: US Forest Service
ROR ID: https://ror.org/03zmjc935

Description of change: For the registered research organization US Forest Service at https://ror.org/03zmjc935 the official URL has been changed to https://www.fs.usda.gov/.
Update: delete.links==http://www.fs.fed.us/; add.links==https://www.fs.usda.gov/;

Related organizations: https://ror.org/issue9 (child)

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
