### ISSUE TITLE
Modify the information in an existing ROR record: Texas Heart Institute - https://ror.org/00r4vsg44

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#10913]
Summary of request: Modify the information in an existing ROR record

Name of organization: Texas Heart Institute
ROR ID: https://ror.org/00r4vsg44
Description of change: Record was marked as Withdrawn in 2022 update and I can find no documentation about why but based on the presence of the Successor Organization: [Texas Medical Center](https://ror.org/00dqsbj20) in the record, it was probably judged that the Institute was not a top-level entity but a constituent sub-unit of the TMC.

If this was indeed the reason the record was withdrawn then I think it may be worthy of being reinstated/made Active again. (If that was _not_ the reason it was withdrawn and I'm totally off-base about the rationale, apologies!)

The TMC is a mega-entity supporting [~50 different institutions](https://en.wikipedia.org/wiki/List_of_Texas_Medical_Center_institutions), but it does not appear to actually be a hierarchical parent-child relationship. TMC describes the groups it works with as "[members](https://www.tmc.edu/about-tmc/our-members/)" of its "[ecosystem](https://www.tmc.edu/ecosystem/)". Indeed, ROR has standalone records for a number of these:

- John Sealy Hospital (https://ror.org/02fxjt553)
- Houston Methodist (https://ror.org/027zt9171)
- Memorial Hermann–Texas Medical Center (https://ror.org/047225g28)
- Texas Children's Hospital (https://ror.org/05cz92x43)
- Michael E. DeBakey VA Medical Center (https://ror.org/052qqbc08)
(To name a few.)

The Texas Heart Institute (THI) describes itself as an [independent nonprofit](https://www.texasheart.org/the-institute/). It has [dedicated staff](https://www.texasheart.org/the-institute/our-people/professional-staff/), [ORCiD affiliations](https://orcid.org/orcid-search/search?searchQuery=%22texas%20heart%22), and [publication usage](http://api.crossref.org/works?query.affiliation=texas+heart&select=DOI,author).

If it's judged suitable for reactivation, I also suggest adding THI as an alias and 1962 as the establish date. It could also stay linked with TMC as a Related Organization. Thanks!

Update: status.replace==active | acronym.add==THI | established.replace==1962$

Related organizations: https://ror.org/00dqsbj20 (delete) https://ror.org/00dqsbj20 (related)

**Comment by adambuttrick** [comment]
The affiliation usage for this looks fine, so this can be re-instated. For additional context, @cknopp-schwyn, we inherited a set of deprecations from our predecessor service GRID, many of which were for medical centers like this, so this was unlikely to have been the result of anything we actively decided on.
