### ISSUE TITLE
Add a new organization to ROR: GLiCID

### ISSUE THREAD

**Issue by seignovert** [ror-community/ror-updates#10912]
Summary of request: Add a new organization to ROR

Name of organization: Groupement Ligérien pour le Calcul Intensif Distribué*French
Website: https://glicid.fr
Domains: glicid.fr
Link to publications: doi.org/10.26443/seismica.v3i1.1007
Organization type: Facility
Organization status: Active
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: GLiCID*French
Related organizations: https://ror.org/03gnr7b55 (parent) https://ror.org/04yrqp957 (parent) https://ror.org/01mtcc283 (parent) https://ror.org/03nh7d505 (parent)
City: Nantes
Country:France
Geonames ID: 2990969
Year established: 2022
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility
Other information about this request: No

**Comment by adambuttrick** [comment]
Research unit in France. Affiliation usage is limited, but there are many in-kind acknowledgements of this (e.g. [here](https://doi.org/10.1002/ange.202210419) and [here](https://doi.org/10.1002/ange.202311123)), so this is fine to add.
