### ISSUE TITLE
Modify the information in an existing ROR record: Kesmonds International University - https://ror.org/051194q96

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#10921]
Summary of request: Modify the information in an existing ROR record

Name of organization: Kesmonds International University
ROR ID: https://ror.org/051194q96
Which part of the record needs to be changed? 
Description of change: Add alt: KIU America
Add Wikidata: Q117405732
Add establish date: 2010

Update: alias.add==KIU America*English | wikidata.preferred.replace==Q117405732 | wikidata.all.add==Q117405732 | established.replace==2010$

**Comment by adambuttrick** [comment]
Confirmed use of alias and other details.
