### ISSUE TITLE
Add a new organization to ROR: Agusan del Sur State College of Agriculture and Technology

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#10968]
Summary of request: Add a new organization to ROR

Name of organization: Agusan del Sur State College of Agriculture and Technology*English
Website: https://asscat.edu.ph
Link to publications: http://api.crossref.org/works?query.affiliation=agusan+sur+agriculture&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Agusan_del_Sur_State_University
Wikidata ID: Q4694611
ISNI ID: 0000 0005 0234 1324
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Agusan del Sur State University*English
Labels:
Acronym/abbreviation: ASSCAT*English
City: Bunawan
Country: Philippines
Geonames ID: 1722731
Year established: 1908
How will a ROR ID for this organization be used? To identify researchers
Other information about this request:

**Comment by adambuttrick** [comment]
College in the Philippines. Funds and employs researchers. Solid affiliation usage. Should be added.
