### ISSUE TITLE
Add a new organization to ROR: American University of Iraq Baghdad

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#10969]
Summary of request: Add a new organization to ROR

Name of organization: American University of Iraq Baghdad*English
Website: https://auib.edu.iq
Domains: auib.edu.iq
Link to publications: http://api.crossref.org/works?query.affiliation=american+university+baghdad&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page:https://en.wikipedia.org/wiki/American_University_of_Iraq_-_Baghdad
Wikidata ID: Q107675529
ISNI ID: 0000 0004 8339 2723
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:  الجامعة الأمريكية في بغداد*ar
Acronym/abbreviation: AUIB*English
Related organizations: 
City: Baghdad
Country: Iraq
Geonames ID: 98182
Year established: 2018
How will a ROR ID for this organization be used? To identify researchers
Other information about this request:

**Comment by adambuttrick** [comment]
University in Iraw. Funds and employs researchers. Solid affiliation usage. Should be added.
