### ISSUE TITLE
Add a new organization to ROR: Institute of Nuclear Physics

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1099]
Summary of request: Add a new organization to ROR

Name of organization: Institute of Nuclear Physics
Website: https://inp.kz
Link to publications: 
Organization type: Government
Wikipedia page: https://ru.wikipedia.org/wiki/%D0%98%D0%BD%D1%81%D1%82%D0%B8%D1%82%D1%83%D1%82_%D1%8F%D0%B4%D0%B5%D1%80%D0%BD%D0%BE%D0%B9_%D1%84%D0%B8%D0%B7%D0%B8%D0%BA%D0%B8_%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B8_%D0%9A%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD
Wikidata ID: Q12572201
ISNI ID: 0000 0004 0606 0995
GRID ID:
Crossref Funder ID:
Aliases: Institute of Nuclear Physics of the Republic of Kazakhstan
Labels: Ядролық физика институты*Kazakh; Институт ядерной физики*Russian
Acronym/abbreviation:
Related organizations: 
City: Almaty
Country: Kazakhstan
Geonames ID: 1526384
Year established: 1957
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Nuclear physics research institute and part of Kazakhstan's Ministry of Energy. Independent, top-level entity with solid affiliation usage. Funds and employs researchers. Should be added to ROR.

Publication affiliation usage: https://doi.org/10.1142/s0218301318500428; https://doi.org/10.1142/s0218301317500185

ORCID affiliation usage: https://orcid.org/0000-0002-7001-6134

**Comment by nlundvick** [comment]
Established, top-level research organization with solid affiliation use (https://api.crossref.org/works/?query.affiliation=%22Institute+of+Nuclear+Physics+of+the+Republic+of+Kazakhstan%22). Similar organizations already in ROR (https://ror.org/01136x372). Concur - in scope, add to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02tpw8g37 in release v1.8.
