### ISSUE TITLE
Update Woods Hole Oceanographic Institute https://ror.org/03zbnzt98

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#11]
Description: Should we remove the French version of the name of Woods Hole Oceanographic Institute? This is a policy decision.

Name of organization: Woods Hole Oceanographic Institute
ROR ID: https://ror.org/03zbnzt98
Which part of the record needs to be changed? Primary name
Description of change: Remove French version of name to avoid confusion

Update: delete.labels==Institut océanographique de woods hole;$

**Comment by adambuttrick** [comment]
No reference to the French name anywhere on their site, so this should be removed.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
