### ISSUE TITLE
Modify Rocky Mountain Research Station (https://ror.org/04347cr60)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#110]
Summary: Modify an existing ROR record

Name of organization: Rocky Mountain Research Station
ROR ID: https://ror.org/04347cr60
Description of change: Replace this link (https://www.fs.fed.us/rmrs/) with this link (https://www.fs.usda.gov/rmrs/)
Update: delete.links==https://www.fs.fed.us/rmrs/; add.links==https://www.fs.usda.gov/rmrs/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
