### ISSUE TITLE
Add a new organization to ROR: Toshiba Nanoanalysis Corporation

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1100]
Summary of request: Add a new organization to ROR

Name of organization: Toshiba Nanoanalysis Corporation
Website: http://www.nanoanalysis.co.jp
Link to publications: 
Organization type: Company
Wikipedia page:
Wikidata ID: Q55829958
ISNI ID:
GRID ID:
Crossref Funder ID:
Aliases:
Labels: 東芝ナノアナリシス株式会社*Japanese
Acronym/abbreviation: 
Related organizations: https://ror.org/0326v3z14 (parent)
City: Kawasaki
Country: Japan
Geonames ID: 1859642
Year established: 2002
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Subsidiary corporation of https://ror.org/0326v3z14 focused on nanomaterials. Funds and employs researchers. Solid affiliation usage. Should be added to ROR.

Publication affiliation usage: https://doi.org/10.1380/vss.64.515; https://doi.org/10.31399/asm.cp.istfa2016p0609; https://doi.org/10.1103/PhysRevB.103.205113

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities and affiliation usage.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05p9h0d44 in release v1.8.
