### ISSUE TITLE
Add a new organization to ROR: Negev Nuclear Research Center

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1101]
Summary of request: Add a new organization to ROR

Name of organization: Shimon Peres Negev Nuclear Research Center
Website: http://nrcn.gov.il
Link to publications: 
Organization type: Facility
Wikipedia page: https://en.wikipedia.org/wiki/Shimon_Peres_Negev_Nuclear_Research_Center
Wikidata ID: Q1752912
ISNI ID: 0000 0004 0470 7206
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Negev Nuclear Research Center
Labels: קריה למחקר גרעיני – נגב ע"ש שמעון פרס*Hebrew
Acronym/abbreviation: NRCN
Related organizations: https://ror.org/01bh2qr63 (parent)
City: Negev Desert
Country: Israel
Geonames ID: 294886
Year established: 1958
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Nuclear research facility in Israel. Independent, top-level entity with solid affiliation usage. Fund and employs researchers. Should be added to ROR. 

Publication affiliation usage: https://doi.org/10.1145/2928275.2933276; https://doi.org/10.2495/wm140071; https://doi.org/10.1145/3427477.3429466

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities. I think it might be more appropriate to classify it as a facility rather than government, however.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/001swhm52 in release v1.8.
