### ISSUE TITLE
Add a new organization to ROR: Obninsk Institute for Nuclear Power Engineering

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1102]
Summary of request: Add a new organization to ROR

Name of organization: Obninsk Institute for Nuclear Power Engineering
Website: http://www.iate.obninsk.ru
Link to publications: 
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Obninsk_Institute_for_Nuclear_Power_Engineering
Wikidata ID: Q976613
ISNI ID: 0000 0001 0744 1907
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: ОБНИНСКИЙ ИНСТИТУТ АТОМНОЙ ЭНЕРГЕТИКИ*Russian
Acronym/abbreviation: OINPE; IATE NRNU MEPhI; IATE MEPHI
Related organizations: https://ror.org/04w8z7f34 (parent)
City: Obninsk
Country: Russia
Geonames ID: 516436
Year established: 1953
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Nuclear technology focused technical training university in Russia. Solid affiliation usage. Funds and employs researchers. Both site and Wikipedia entry list this as having been incorporated into https://ror.org/04w8z7f34 in 2009, but appears to still maintain degree-granting status. Would appreciate second review to verify relative independence.

**Comment by nlundvick** [comment]
Established research organization with strong affiliation use: [http://api.crossref.org/works/?query.affiliation=%22Obninsk+Institute+for+Nuclear+Power+Engineering%22](http://api.crossref.org/works/?query.affiliation=%22Obninsk+Institute+for+Nuclear+Power+Engineering%22). Given the standalone URL and [organizational structure](http://www.iate.obninsk.ru/node/24), this organization is in my opinion sufficiently independent and should be assigned it's own ROR ID.

@adambuttrick - Recommend adding "IATE NRNU MEPhI" and "IATE MEPHI" as acronyms. See [http://www.iate.obninsk.ru/node/25](http://www.iate.obninsk.ru/node/25).

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04kt5vk53 in release v1.12.
