### ISSUE TITLE
Add a new organization to ROR: QunaSys

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1103]
Summary of request: Add a new organization to ROR

Name of organization: QunaSys
Website: http://www.qunasys.com
Link to publications: 
Organization type: Company
Wikipedia page:
Wikidata ID: Q82071967
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Aliases: Quantum Native Systems
Labels:
Related organizations: 
City: Tokyo
Country: Japan
Geonames ID: 1850147
Year established: 2018
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Japanese quantum computing company. Independent, top-level entity that funds and employs researchers. Should be added to ROR.

Publication affiliation usage: https://doi.org/10.22331/q-2021-10-06-559; https://doi.org/10.1021/acsomega.2c01546

Google Scholar affiliation usage: https://scholar.google.com/citations?user=LyU8LXsAAAAJ; https://scholar.google.com/citations?user=wxg0I-sAAAAJ; https://scholar.google.com/citations?user=Ioyr43cAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0001-8534-7131 ; https://orcid.org/0000-0001-6191-4592 ; https://orcid.org/0000-0001-5555-1940

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities and affiliation usage.
