### ISSUE TITLE
Add a new organization to ROR: Constituyentes Atomic Center

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1104]
Summary of request: Add a new organization to ROR

Name of organization: Centro Atómico Constituyentes
Website: https://www.argentina.gob.ar/cnea/cac
Link to publications: http://www.tandar.cnea.gov.ar
Organization type: Facility
Wikipedia page: https://es.wikipedia.org/wiki/Centro_At%C3%B3mico_Constituyentes
Wikidata ID: Q8343571
ISNI ID: 0000 0001 2155 2304
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Constituyentes Atomic Center
Labels:
Acronym/abbreviation:
Related organizations: https://ror.org/01xz39a70 (parent) https://ror.org/05m802881 (related)
City: Buenos Aires
Country: Argentina
Geonames ID: 3435910
Year established: 1993
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Nuclear research facility in Argentina. Independent, top-level entity that funds and employs researchers. Solid affiliation usage. Should be added to ROR.

Publication affiliation usage: https://doi.org/10.4028/www.scientific.net/ddf.224-225.59; https://doi.org/10.4028/www.scientific.net/ddf.272.51; https://doi.org/10.4028/www.scientific.net/ddf.194-199.1375; https://doi.org/10.4028/www.scientific.net/kem.391.109; https://doi.org/10.1021/ma8015757; https://doi.org/10.4028/www.scientific.net/msf.15-18.863; https://doi.org/10.4028/www.scientific.net/ddf.213-215.31

ORCID affiliation usage: https://orcid.org/0000-0003-4300-3706 ; https://orcid.org/0000-0002-3513-1495 ; https://orcid.org/0000-0001-7740-882X

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities and affiliation usage. It is analogous to the existing entry for the Bariloche Atomic Centre (https://ror.org/05m802881). It is the site of the first nuclear reactor in Latin America and also serves as the operating hub for the digital repository for Argentina's atomic energy commission. 

A few metadata suggestions:

- In primary name, add accent to change "Atomico" to "Atómico"
- Add website: https://www.argentina.gob.ar/cnea/cac
- Add related org: https://ror.org/05m802881

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04nrcyx09 in release v1.8.
