### ISSUE TITLE
Add a new organization to ROR: National Institute of Education

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1105]
Summary of request: Add a new organization to ROR

Name of organization: National Institute of Education
Website: https://www.nie.edu.sg
Link to publications: 
Organization type: Education
Wikipedia page:
Wikidata ID: Q6973642
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/02e7b5302 (parent)
City: Jurong West
Country: Singapore
Geonames ID: 1881955
Year established: 1950
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
National-level teacher training institute in Singapore. Solid affiliation usage. Website lists it as a joint project between Singapore's Ministry of Education and https://ror.org/02e7b5302. Wikidata has as part of https://ror.org/02e7b5302. Would appreciate additional curator review for determination of independence.

Publication affiliation usage: https://doi.org/10.14221/ajte.2008v33n3.6; https://doi.org/10.1002/rev3.3002

Google scholar affiliation usage: https://scholar.google.com/citations?user=Lo34NicAAAAJ; https://scholar.google.com/citations?user=dvo-5UAAAAAJ; https://scholar.google.com/citations?user=nh3jgF0AAAAJ

**Comment by arthurpsmith** [comment]
According to the History section here: https://www.nie.edu.sg/about-us/corporate-information
it was founded in its present state in 1991 by the merger of two pre-existing institutes, the "Institute of Education" (IE) and the "College of Physical Education" (CPE), and at the same time became part of NTU at that point in time. "NIE was also established as an institute of the Nanyang Technological University (NTU) when it was reconstituted from the former Nanyang Technological Institute on the same day". If they are arguing for an inception date of 1950, that seems to be for a predecessor institution, "Teachers' Training College", which was for a period of time associated with the University of Singapore (and eventually became the IE).

So I think the independent history combined with the separate internet domain and that affiliation usage seems to be clearly "NIE" only, not mentioning NTU, does indicate this should have its own ROR id.

**Comment by adambuttrick** [comment]
@arthurpsmith I will reach out to the requester and see if we can determine.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02fhgbp51 in release v1.8.
