### ISSUE TITLE
Add a new organization to ROR: Takasaki Advanced Radiation Research Institute

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1107]
Summary of request: Add a new organization to ROR

Name of organization: Takasaki Advanced Radiation Research Institute
Website: https://www.qst.go.jp/site/taka
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID: Q39652817
ISNI ID: 0000 0000 9045 9544
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: 高崎量子応用研究所*Japanese
Acronym/abbreviation: TARRI
Related organizations: https://ror.org/020rbyg91 (parent)
City: Takasaki
Country: Japan
Geonames ID: 1851002
Year established: 2005
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Nuclear research facility in Japan. Funds and employs researchers. Solid affiliation usage. Should be added to ROR.

Publication affiliation usage: https://doi.org/10.1585/pfr.9.4406106; https://doi.org/10.1142/s0129083512400025

Google Scholar affiliation usage: https://scholar.google.com/citations?user=s9wd194AAAAJ; https://scholar.google.com/citations?user=y1dmeZAAAAAJ

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities and affiliation usage. 

The English version of the organization name is a little confusing to sort out. The website above links to "Takasaki Applied Quantum Research Institute" and I can't find any reference to the name "Takasaki Advanced Radiation Research Institute." Running a Google search on the name returns usage on this page: https://www.qst.go.jp/site/taka-english/. But I think both sites ultimately lead to the same content (e.g., https://www.qst.go.jp/site/taka/2084.html under "institute overview"). Should "Takasaki Applied Quantum Research Institute" be added as an alias even if affiliation usage tends to use the other name?

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04399kt07 in release v1.8.
