### ISSUE TITLE
Add a new organization to ROR: Ho Chi Minh City Institute of Physics

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1108]
Summary of request: Add a new organization to ROR

Name of organization: Ho Chi Minh City Institute of Physics
Website: http://hcmip.ac.vn
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID: Q10832782
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Aliases:
Labels: Trung tâm Vật lý tại Thành phố Hồ Chí Minh*Vietnamese
Related organizations: https://ror.org/02wsd5p50 (parent)
City: Ho Chi Minh City
Country: Vietnam
Geonames ID: 1566083
Year established: 1993
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Physics research center in Vietnam. Funds and employs researchers. Solid affiliation usage. Child institutes of https://ror.org/02wsd5p50 already exist in ROR. Should be added.

Publication affiliation usage: https://doi.org/10.1002/pssb.201451442; https://doi.org/10.1021/acs.jpcc.8b04073; https://doi.org/10.1063/1.5034404

Google Scholar affiliation usage: https://scholar.google.com/citations?user=ZIE08qAAAAAJ; https://scholar.google.com/citations?user=EecHVyQAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0003-1457-3128 ; https://orcid.org/0000-0002-8150-2445 ; https://orcid.org/0000-0002-8816-4450

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities, affiliation usage, and similar entities already in ROR. 

NB: Website does not appear to be working at present.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04g43ky75 in release v1.8.
