### ISSUE TITLE
Modify Pacific Northwest Research Station (https://ror.org/02s42ys89)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#111]
Summary: Modify an existing ROR record
Name of organization: Pacific Northwest Research Station
ROR ID: https://ror.org/02s42ys89
Description of change: Replace this link (https://www.fs.fed.us/pnw/) with this link (https://www.fs.usda.gov/pnw/)
Update: delete.links==https://www.fs.fed.us/pnw/; add.links==https://www.fs.usda.gov/pnw/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
