### ISSUE TITLE
Add a new organization to ROR: 1QBit

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1110]
Summary of request: Add a new organization to ROR

Name of organization: 1QBit
Website: http://www.1QBit.com
Link to publications: 
Organization type: Company
Wikipedia page: https://en.wikipedia.org/wiki/1QBit
Wikidata ID: Q17507626
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: 1QB Information Technologies
Labels:
Acronym/abbreviation:
Related organizations: 
City: Vancouver
Country: Canada
Geonames ID: 6173331
Year established: 2012
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Canadian quantum computing company. Independent, top-level entity with solid affiliation usage. Should be added to ROR.

Publication affiliation usage: https://doi.org/10.7566/jpsj.88.061006; https://doi.org/10.1002/9783527693245.ch4; https://doi.org/10.1145/2830556.2830563; https://doi.org/10.1063/5.0054647

Google Scholar affiliation usage: https://scholar.google.com/citations?user=YZf-SyAAAAAJ; https://scholar.google.com/citations?user=R_zkWkwAAAAJ; https://scholar.google.com/citations?user=J-7MAM4AAAAJ

ORCID affiliation usage: https://orcid.org/0000-0003-3820-7851 ; https://orcid.org/0000-0001-7324-3204 ; https://orcid.org/0000-0002-6966-752X

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities and affiliation usage.

Metadata note: add "1QB Information Technologies" as alias? This appears to be used in some affiliations.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04eswfz98 in release v1.8.
