### ISSUE TITLE
Add a new organization to ROR: G. Venkataswamy Naidu College, Kovilpatti

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11137]
Summary of request: Add a new organization to ROR

Name of organization: G. Venkataswamy Naidu College*en
Website: https://www.gvncollege.org
Domains: gvncollege.edu.in
Link to publications: http://api.crossref.org/works?query.affiliation=Venkataswamy&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/G.Venkataswamy_Naidu_College,_Kovilpatti
Wikidata ID: Q48725521
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: GVN College*en; G.Venkataswamy Naidu College (Autonomous)*en
Labels: ஜி. வெங்கடசாமி நாயுடு கல்லூரி*ta
Acronym/abbreviation: GVNC*en
Related organizations: https://ror.org/02qgw5c67 (related)
City: Kovilpatti
Country: India
Geonames ID:  1265891
Year established: 1966
How will a ROR ID for this organization be used? To identify researchers
Other information about this request:

**Comment by adambuttrick** [comment]
College in India. Funds and employs researchers. Solid affiliation usage. Should be added.
