### ISSUE TITLE
Add a new organization to ROR: Janaki Medical College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11133]
Summary of request: Add a new organization to ROR

Name of organization: Janaki Medical College*English
Website: https://janakimedicalcollege.edu.np
Link to publications: http://api.crossref.org/works?query.affiliation=janaki+medical&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Janaki_Medical_College
Wikidata ID: Q19672701
ISNI ID: 0000 0004 5998 7313
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Janaki Medical College and Teaching Hospital*English
Labels: जानकी मेडिकल कलेज*ne
Acronym/abbreviation: JMC*English
Related organizations: https://ror.org/02rg1r889 (related)
City: Janakpur
Country: Nepal
Geonames ID: 1283318
Year established: 2003
How will a ROR ID for this organization be used? To identify researchers
Other information about this request:

**Comment by adambuttrick** [comment]
@cknopp-schwyn For additional context, the relationship here is a form of accreditation or degree granting status derived from the referenced institution. In ROR, we use the "related" relationship type for this.

**Comment by adambuttrick** [comment]
Medical college in Nepal. Funds and employs researchers. Solid affiliation usage. Should be added.
