### ISSUE TITLE
Modify the information in an existing ROR record:  Lviv State University of Physical Culture - https://ror.org/04z6kfz30

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11149]
Summary of request: Modify the information in an existing ROR record

Name of organization: Lviv State University of Physical Culture
ROR ID: https://ror.org/04z6kfz30
Which part of the record needs to be changed? Alt names
Description of change: Add alt names: LDUFK; Ivan Bobersky Lviv State University of Physical Culture; Львівський державний університет фізичної культури імені Івана Боберського (uk); ЛДУФК (uk); Львоўскі дзяржаўны ўніверсітэт фізічнай культуры імя Івана Бабэрскага (bel)

Update: alias.add==Ivan Bobersky Lviv State University of Physical Culture*English | label.add==Львівський державний університет фізичної культури імені Івана Боберського*uk | acronym.replace==LDUFK*en; ЛДУФК*uk$

**Comment by adambuttrick** [comment]
Additional aliases, aside from the Belarusian form, have affiliation usage and so can be added.
