### ISSUE TITLE
Modify the information in an existing ROR record: Arizona College of Emergency Physicians - https://ror.org/0521sww17

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11155]
Summary of request: Modify the information in an existing ROR record

Name of organization: Arizona College of Emergency Physicians
ROR ID: https://ror.org/0521sww17
Which part of the record needs to be changed? Alt name, External ID
Description of change: Add acronym ACEP. Add Wikidata Q43896337. Add establish date 1972

Update: acronym.add==ACEP | wikidata.all.add==Q43896337 | wikidata.preferred.replace==Q43896337 | established.replace==1972$

**Comment by adambuttrick** [comment]
Wikidata ID and acronym are that for the organization.
