### ISSUE TITLE
Modify the information in an existing ROR record: Banking University of Ho Chi Minh City

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11152]
Summary of request: Modify the information in an existing ROR record

Name of organization: Banking University of Ho Chi Minh City
ROR ID: https://ror.org/03fsckq75
Which part of the record needs to be changed? Main name, Alt names, Website
Description of change: Update main name to Ho Chi Minh University of Banking. Add alt names Đại học Ngân hàng TP.HCM (vi). Add acronym HUB. Update URL to https://hub.edu.vn

Update: ror_display.replace==Ho Chi Minh University of Banking*English | label.replace==Ho Chi Minh University of Banking*English; Trường Đại học Ngân hàng Thành phố Hồ Chí Minh*vi | alias.replace==Banking University of Ho Chi Minh City*English; Đại học Ngân hàng TP.HCM*vi | acronym.add==HUB*en| website.replace==https://hub.edu.vn$

**Comment by adambuttrick** [comment]
Name change corresponds to the organization's site and branding.
