### ISSUE TITLE
Modify the information in an existing ROR record:  Universidad Evangelica de El Salvador - https://ror.org/01xs7ed64

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11166]
Summary of request: Modify the information in an existing ROR record

Name of organization: Universidad Evangelica de El Salvador
ROR ID: https://ror.org/01xs7ed64
Which part of the record needs to be changed? Alt name, External ID
Description of change: Add English alt: Evangelical University of El Salvador. Add Wikidata: Q29002771

Update: alias.add==Evangelical University of El Salvador*English | wikidata.all.add==Q29002771 | wikidata.preferred.replace==Q29002771$

**Comment by adambuttrick** [comment]
Confirmed Wikidata ID and affiliation usage for this alias.
