### ISSUE TITLE
Add a new organization to ROR: Abetifi Presbyterian College of Education 

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11205]
Summary of request: Add a new organization to ROR

Name of organization: Abetifi Presbyterian College of Education*English
Website: https://abeticoe.edu.gh
Domains:
Link to publications: http://api.crossref.org/works?query.affiliation=Abetifi&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Abetifi_Presbyterian_College_of_Education
Wikidata ID: Q46996953
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: Abetifi Presby College of Education*English; Abetifi Training College*English
Aliases:
Labels:
Acronym/abbreviation: ABETICO*English
Related organizations: https://ror.org/0492nfe34 (related)
City: Abetifi
Country: Ghana
Geonames ID: 2306390
Year established: 1952
How will a ROR ID for this organization be used? To identify researchers
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
