### ISSUE TITLE
Add a new organization to ROR: Solomon Islands National University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11206]
Summary of request: Add a new organization to ROR

Name of organization: Solomon Islands National University*English
Website: https://www.sinu.edu.sb
Domains: sinu.edu.sb
Link to publications: http://api.crossref.org/works?query.affiliation=Solomon+Islands+National+University&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Solomon_Islands_National_University
Wikidata ID: Q110442979
ISNI ID: 0000 0001 2106 6445
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Solomon Islands College of Higher Education*English
Labels:
Acronym/abbreviation: SINU*English; SICHE*English
Related organizations: 
City: Honiara
Country: Solomon Islands
Geonames ID: 2108502
Year established: 2013
How will a ROR ID for this organization be used? To identify researchers
Other information about this request:

**Comment by adambuttrick** [comment]
University in the Solomon Islands. Funds and employs researchers. Solid affiliation usage. Should be added.
