### ISSUE TITLE
Modify the information in an existing ROR record:  Presbyterian University College - https://ror.org/02369cb65

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11204]
Summary of request: Modify the information in an existing ROR record

Name of organization: Presbyterian University College
ROR ID: https://ror.org/02369cb65
Which part of the record needs to be changed? Main name
Description of change: Name changed to Presbyterian University, Ghana per [here](https://www.presbyuniversity.edu.gh/site/). Add acronym: PUG

Update: ror_display.replace==Presbyterian University, Ghana*English | label.replace==Presbyterian University, Ghana*English | alias.replace==Presbyterian University College*English | acronym.replace==PUG*English; PUCG*English$

**Comment by adambuttrick** [comment]
Confirmed name change via the organization's site.
