### ISSUE TITLE
Add a new organization to ROR: Saint Michael College of Caraga

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11202]
Summary of request: Add a new organization to ROR

Name of organization: Saint Michael College of Caraga*English
Website: https://smccnasipit.edu.ph
Domains: smccnasipit.edu.ph
Link to publications: [here](https://www.researchgate.net/profile/Felix-Arcilla-Jr/publication/344374652_Readiness_for_Flexible_Learning_amidst_COVID-19_Pandemic_of_Saint_Michael_College_of_Caraga_Philippines/links/5f6d97d392851c14bc94a24d/Readiness-for-Flexible-Learning-amidst-COVID-19-Pandemic-of-Saint-Michael-College-of-Caraga-Philippines.pdf), [here](https://d1wqtxts1xzle7.cloudfront.net/71820142/sherj6j.06.010119-libre.pdf?1634081714=&response-content-disposition=inline%3B+filename%3DCollection_Evaluation_of_Saint_Michael_C.pdf&Expires=1715022675&Signature=H-tcC6UBwXWnYgn8m5MYfTpyp5Bbd53ITxqPF0kjzOmiikKhXYgMsCk~4ieAOx5Gin0hzUGj2d6PxUMS9HlviGPvAJW1hBmpl3glgtBHTJWxjrNEzlA6FbUJDlwEQeT-t6YhYqgSid2PtGowM6hDaJ8wKu-WVT5dInRqTuqKYdh3TuukoBBvG27dbhQhFjNPninfmFONNQBCUWL9h3vJ227iQmHwGo6SsPRO8GCdYpRzmwyBA1KUB2J3w5CiBEzUYxDENc8k7Z2pR3tuuoGkfvRSWSH6eujf4OmAiacUSFsAfRUePctb9EpRcABb3KqI8yMSTvdZTOezEazx4Kqr2Q__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA), [here](https://web.archive.org/web/20200208211929id_/http://sherj.smccnasipit.edu.ph/articles/Vol6/Madelyn.pdf)
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Saint_Michael_College_of_Caraga
Wikidata ID: Q7401915
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: St. Michael College of Caraga*English; Saint Michael's Institute*English
Labels: Dalubhasaang San Miguel ng Caraga*tl
Acronym/abbreviation: SMCC
Related organizations: 
City: Nasipit
Country: Philiipines
Geonames ID: 1698063
Year established: 1948
How will a ROR ID for this organization be used? To identify researchers
Other information about this request:

**Comment by adambuttrick** [comment]
College in the Philippines. Funds and employs researchers. Solid affiliation usage. Should be added.
