### ISSUE TITLE
Modify National Technical University of Ukraine “Igor Sikorsky Kyiv Polytechnic Institute” (https://ror.org/00syn5v21)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#113]
Summary: Modify an existing ROR record

Name of organization: National Technical University of Ukraine “Igor Sikorsky Kyiv Polytechnic Institute”
ROR ID: https://ror.org/00syn5v21

Description of change:
We would like to correct the name of our University since it was modified in 2016: https://kpi.ua/en  

We ask you to correct the name of the University in different languages as follows:

- In English: Igor Sikorsky Kyiv Polytechnic Institute

- In Ukrainian: Національний технічний університет України ""Київський політехнічний інститут імені Ігоря Сікорського""

- In Russian: Национальный технический университет Украины ""Киевский политехнический институт имени Игоря Сикорского""
- In Polish: Igor Sikorsky Kijowski Instytut Politechniczny

In English and Polish we would like to see the short title because we ask our scientists use this variant when publish their works (see, e.g., University's profile in WoS: http://wcs.webofknowledge.com/RA/analyze.do?product=WOS&SID=C4WDvIZh1CX2IioEyKN&field=TASCA_JCRCategories_JCRCategories_en&yearSort=false)

Update: change.name==Igor Sikorsky Kyiv Polytechnic Institute; add.labels==Національний технічний університет України ""Київський політехнічний інститут імені Ігоря Сікорського""*Ukrainian; add.labels==Национальный технический университет Украины ""Киевский политехнический институт имени Игоря Сикорского""*Russian; add.labels==Igor Sikorsky Kijowski Instytut Politechniczny*Polish; add.aliases==NTUU “Igor Sikorsky Kyiv Polytechnic Institute”; add.aliases==Kyiv Polytechnic Institute; add.acronyms==NTUU KPI; add.acronyms==KPI;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
