### ISSUE TITLE
Add a new organization to ROR: Bagadhar Brahma Kishan College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11318]
Summary of request: Add a new organization to ROR

Name of organization: Bagadhar Brahma Kishan College*en
Website: https://bbkishancollege.ac.in
Domains:
Link to publications: https://doi.org/10.1039/d4ob00281d; https://doi.org/10.1021/acs.joc.3c02479
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Bagadhar_Brahma_Kishan_College
Wikidata ID: Q4841390
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: B. B. Kishan College*en
Aliases: বগাধৰ ব্ৰহ্ম কিষান মহাবিদ্যালয়*as; बगाधर ब्रह्म किसान फरायसालिमा*hi
Labels: 
Acronym/abbreviation: BBKC*en
Related organizations: https://ror.org/01ppj9r51 (related)
City: Jalah
Country: India
Geonames ID: 1276937
Year established: 1978
How will a ROR ID for this organization be used? To identify researchers
Other information about this request:

**Comment by adambuttrick** [comment]
College in India. Funds and employs researchers. Solid affiliation usage. Should be added.
