### ISSUE TITLE
Add a new organization to ROR: Nowgong Girls' College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11316]
Summary of request: Add a new organization to ROR

Name of organization: Nowgong Girls' College*en
Website: https://nowgonggirlscollege.edu.in
Domains: nowgonggirlscollege.edu.in
Link to publications: http://api.crossref.org/works?query.affiliation=nowgong+girls&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Nowgong_Girls%27_College
Wikidata ID: Q39050015
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: নগাঁও ছোৱালী কলেজ*as
Labels:
Acronym/abbreviation:
Related organizations: https://ror.org/01ppj9r51 (related)
City: Nagaon
Country: India
Geonames ID: 12684924
Year established: 1962
How will a ROR ID for this organization be used? To identify researchers
Other information about this request:

**Comment by adambuttrick** [comment]
College in India. Funds and employs researchers. Solid affiliation usage. Should be added.
