### ISSUE TITLE
Add a new organization to ROR: Idlib University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11347]
Summary of request: Add a new organization to ROR

Name of organization: Idlib University*en
Website: https://idlib.university
Domains:
Link to publications: http://api.crossref.org/works?query.affiliation=idlib&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Idlib_University
Wikidata ID: Q30314718
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: جامعة إدلب*ar
Acronym/abbreviation:
Related organizations: 
City: Idlib
Country: Syria
Geonames ID: 169389
Year established: 2015
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Syria. Funds and employs researchers. Solid affiliation usage. Should be added.
