### ISSUE TITLE
Add a new organization to ROR: BGMEA University of Fashion & Technology

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11346]
Summary of request: Add a new organization to ROR

Name of organization: BGMEA University of Fashion & Technology*en
Website: https://buft.edu.bd
Domains: buft.edu.bd
Link to publications: http://api.crossref.org/works?query.affiliation=bgmea&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/BGMEA_University_of_Fashion_%26_Technology
Wikidata ID: Q4835554
ISNI ID: 0000 0004 4682 9041
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: BGMEA University of Fashion and Technology*en; Bangladesh Garment Manufacturers and Exporters Association University of Fashion and Technology*en
Labels :বাংলাদেশ পোশাক প্রস্তুতকারক ও রপ্তানিকারক সমিতি*bn
Acronym/abbreviation: BUFT*en; বিইউএফটি*bn
Related organizations: 
City: Dhaka
Country: Bangladesh
Geonames ID: 1185241
Year established: 1999
How will a ROR ID for this organization be used?
Other information about this request:

**Comment by adambuttrick** [comment]
University in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
