### ISSUE TITLE
Add a new organization to ROR: ADx NeuroSciences

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1136]
Summary of request: Add a new organization to ROR

Name of organization: ADx NeuroSciences
Website: https://adxneurosciences.com
Link to publications: 
Organization type: Company
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City: Ghent
Country: Belgium
Geonames ID: 2797656
Year established: 2011
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Publication affiliation usage: https://doi.org/10.2217/bmm.12.46; https://doi.org/10.1016/j.biopsych.2020.02.001; https://doi.org/10.1001/jamaneurol.2015.1285; https://doi.org/10.3389/fneur.2015.00179; https://doi.org/10.1016/j.jalz.2015.05.012; https://doi.org/10.1016/j.jalz.2016.09.014

Google Scholar affiliation usage: https://scholar.google.com/citations?user=5rmwih8AAAAJ

ORCID affiliation usage: https://orcid.org/0000-0002-2147-3961 ; https://orcid.org/0000-0002-4062-8711 ; https://orcid.org/0000-0002-8200-5336

**Comment by carlyrobinson** [comment]
Agree, should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/016c76a68 in release v1.8.
