### ISSUE TITLE
Add a new organization to ROR: Woman Online University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11381]
Summary of request: Add a new organization to ROR

Name of organization: Woman Online University*en
Website: https://womenonlineuniversity.com
Domains: womenonlineuniversity.com
Link to publications: http://rcsdevelopment.org/index.php/rcsd/article/view/325 https://doi.org/10.59653/jemls.v2i02.650 https://doi.org/10.56778/jdlde.v2i11.234 https://doi.org/10.32996/smic.2023.1.1.3x
Organization type: Education
Organization status: Active
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: Zan Online University*en; Woman's Online University*en; Women Online University*en; Women's Online University*en; Woman Online Academy*en; Online Women University*en
Aliases: دانشگاه آنلاین زن*fa
Labels:
Acronym/abbreviation: 
Related organizations: 
City: Northwood
Country: UK
Geonames ID: 7291791
Year established: 2023
How will a ROR ID for this organization be used? To identify researchers
Other information about this request: An online-only university primarily for Afghan women unable to attend in-person university [due to government regulations](https://8am.media/eng/woman-online-university-can-online-education-replace-in-person-learning/). Such as there is a physical location, the entity is [registered in the UK](https://find-and-update.company-information.service.gov.uk/company/14726171), though most affiliations for this org (logically) mention Afghanistan as the location.

**Comment by adambuttrick** [comment]
Affiliation usage is somewhat limited, but otherwise looks fine, so this can be added.
