### ISSUE TITLE
Add a new organization to ROR: Austrian BioImaging/CMI

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1138]
Summary of request: Add a new organization to ROR

Name of organization: Austrian BioImaging/CMI
Website: https://www.bioimaging-austria.at
Link to publications:
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Austrian BioImaging Correlated Multimodal Imaging (CMI)
Labels:
Acronym/abbreviation:
Related organizations: https://ror.org/01w64ht88 (parent) https://ror.org/05n3x4p02 (parent) https://ror.org/05d78xc36 (related)
City: Vienna
Country: Austria
Geonames ID: 2761369
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Distributed bioimaging infrastructure, submitted as part of Euro-Bioimaging nodes project on #778. Funds and employs researchers. Solid affiliation usage. In scope for ROR by virtue of our facility acknowledgement use case.

See additional curation team comments here:
https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing

Publication affiliation usage: https://doi.org/10.1039/d0an02373f

ORCID affiliation usage: https://orcid.org/0000-0002-5141-3177 ; https://orcid.org/0000-0002-7368-7523

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities, affiliation usage, and similar entities already in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/028696h48 in release v1.8.
