### ISSUE TITLE
Modify the information in an existing ROR record: Ahmed Draia University -  https://ror.org/01k476402

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11397]
Summary of request: Modify the information in an existing ROR record

Name of organization: Ahmed Draia University
ROR ID: https://ror.org/01k476402
Which part of the record needs to be changed? Alt names
Description of change: Add alt names: University of Adrar*en; University of Adrar-Algiers*en; The African University Ahmed Draïa of Adrar*en; Université D'adrar*fr; UADRAR*en

Update: alias.add==University of Adrar*en; University of Adrar-Algiers*en; The African University Ahmed Draïa of Adrar*en; African University Ahmed Draïa of Adrar*en; Université d'Adrar*fr | acronyms.add==UADRAR*en$

**Comment by adambuttrick** [comment]
Aliases appear to mostly have affiliation usage in ORCID  (vs. on publications), but otherwise look fine, so these can be added.
