### ISSUE TITLE
Add a new organization to ROR: Samangan University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11398]
Summary of request: Add a new organization to ROR

Name of organization: Samangan Higher Education Institute*en
Website: https://www.smgu.edu.af
Domains: smgu.edu.af
Link to publications: https://doi.org/10.1177/00194662211036097 https://doi.org/10.52241/TJDS.2023.0061 https://doi.org/10.1080/14786451.2023.2246081 https://doi.org/10.1080/10106049.2023.2248082
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Samangan_University
Wikidata ID: Q18914717
ISNI ID: 0000 0005 1317 594X
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Samangan University*en
Labels: پوهنتون سمنگان*fa
Acronym/abbreviation:
Related organizations: 
City: Aibak
Country: Afghanistan
Geonames ID: 1127768
Year established: 1964
How will a ROR ID for this organization be used? To identify researchers
Other information about this request:

**Comment by adambuttrick** [comment]
Higher educational institute in Afghanistan. Funds and employs researchers. Solid affiliation usage. Should be added.
