### ISSUE TITLE
Add a new organization to ROR: Center for Advanced Preclinical Imaging

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1139]
Summary of request: Add a new organization to ROR

Name of organization: Center for Advanced Preclinical Imaging
Website: https://capi.lf1.cuni.cz
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: Centrum pokročilého preklinického zobrazování*Czech
Acronym/abbreviation: CAPI
Related organizations: https://ror.org/024d6js02 (parent) https://ror.org/05d78xc36 (related)
City: Prague
Country: Czech Republic
Geonames ID: 3067696
Year established: 2016
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Imaging facility hosted at https://ror.org/024d6js02. Part of Euro-Bioimaging and Czech Bioimaging consortiums. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. Solid affiliation usage. In scope for ROR by virtue of our facility acknowledgement use case

Publication affiliation usage: https://doi.org/10.1088/1748-0221/11/12/c12065; https://doi.org/10.3389/fphy.2020.00047; https://doi.org/10.1021/acs.biomac.9b01748; https://doi.org/10.1016/j.carbon.2019.05.061; https://doi.org/10.1039/c7nr05456d

Google Scholar affiliation usage: https://scholar.google.com/citations?user=LJHA7PUAAAAJ

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities, affiliation usage, and similar entities in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0094hc805 in release v1.8.
