### ISSUE TITLE
Modify European Academy of Bozen (https://ror.org/01xt1w755)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#114]
Summary: Modify an existing record in ROR

Name of organization: European Academy of Bozen
ROR ID: https://ror.org/01xt1w755
Description of change:

I would like to request corrections to our organization’s ROR record. The organization short name is wrong as is its categorization as a governmental organization.

We are a non-profit research-performing organization.

Our legal name is:

- Europäische Akademie Bozen
- Accademia Europea di Bolzano
- European Academy of Bozen-Bolzano
- Short name: EURAC Research

Update: change.name==European Academy of Bozen-Bolzano; delete.types==Government; add.types==Nonprofit; delete.aliases==Academia Europeica de Bulsan; add.aliases==EURAC Research; add.labels==Academia Europeica de Bulsan*Romansh;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
