### ISSUE TITLE
Add a new organization to ROR: Finnish Advanced Light Microscopy Node

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1140]
Summary of request: Add a new organization to ROR

Name of organization: Finnish Advanced Light Microscopy Node
Website: https://eurobioimaging.fi/FiALM
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: FiALM; EBI FiALM
Related organizations: https://ror.org/05d78xc36 (related)
City: Turku
Country: Finland
Geonames ID: 633679
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Imaging facility and part of Euro-Bioimaging. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. Solid affiliation usage. In scope for ROR by virtue of our facility acknowledgement use case.

See additional curation team comments here:
https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing

Facility acknowledgements: https://doi.org/10.3390/nano11010014; https://doi.org/10.1681/ASN.2018121218

**Comment by KellyStathis** [comment]
See comments on #1141 - looks good, suggest adding Euro-BioImaging Finland as parent org.

**Comment by adambuttrick** [comment]
@KellyStathis Euro-BioImaging Finland is something of an alias (although not entirely) for the Euro-BioImaging project altogether, which is based in Turku, Finland. There are instances of facility acknowledgement for this node but none for the suggested parent. I'll create a record for Euro-BioImaging Finland and stick it in "Hold for Later" to see if this changes over time.

**Comment by KellyStathis** [comment]
@adambuttrick Makes perfect sense, thank you!

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/023f5cj14 in release v1.8.
