### ISSUE TITLE
Add a new organization to ROR: Finnish Biomedical Imaging Node

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1141]
Summary of request: Add a new organization to ROR

Name of organization: Finnish Biomedical Imaging Node
Website: https://eurobioimaging.fi/FiBI
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: FiBi
Related organizations: https://ror.org/05d78xc36 (related)
City: Turku
Country: Finland
Geonames ID: 633679
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Imaging facility and part of Euro-Bioimaging. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. In scope for ROR by virtue of our facility acknowledgement use case.

See additional curation team comments here:
https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing

Facility acknowledgement: https://doi.org/10.3389/fnins.2022.944432

**Comment by KellyStathis** [comment]
Agree this is in scope for ROR. Curation team comments mentioned that this node/facility is part of of Euro-Bioimaging Finland, along with https://github.com/ror-community/ror-updates/issues/1140. Suggest adding Euro-Bioimaging Finland to ROR also.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03xh8px24 in release v1.8.
