### ISSUE TITLE
Add a new organization to ROR: France-BioImaging

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1142]
Summary of request: Add a new organization to ROR

Name of organization: France-BioImaging
Website: https://france-bioimaging.org
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: FBI
Related organizations: https://ror.org/05d78xc36 (related)
City: Montpellier
Country: France
Geonames ID: 2992166
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
French national research infrastructure for biomedical imaging and EuroBioimaging node. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. In scope for ROR by virtue of our facility acknowledgement use case.

Publication affiliation usage: https://doi.org/10.3389/fnmol.2021.624265

Facility acknowledgement: https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008047; https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8226399/

**Comment by KellyStathis** [comment]
Agree this is in scope for ROR. I searched for a French name but they appear to operate primarily in English, so I think the proposed name/acronym works.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01y7vt929 in release v1.8.
