### ISSUE TITLE
Add a new organization to ROR: Advanced Light Microscopy Italian Node

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1143]
Summary of request: Add a new organization to ROR

Name of organization: Advanced Light Microscopy Italian Node
Website: https://www.eurobioimaging.eu/nodes/advanced-light-microscopy-italian-node
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/05d78xc36 (related)
City: Naples
Country: Italy
Geonames ID: 3172394 
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Distributed Italian infrastructure for biomedical imaging and EuroBioimaging node. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. In scope for ROR by virtue of our facility acknowledgement use case.

See additional curation team comments here:
https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing

Facility acknowledgement: https://doi.org/10.1117/1.JBO.24.10.106504; https://doi.org/10.1038/s41598-021-86092-7; https://www.biorxiv.org/content/10.1101/2020.07.28.225011v1.full.pdf

**Comment by mariagould** [comment]
Agree this is in scope given research activity, facility acknowledgments, and similar entities in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00h3qhh74 in release v1.12.
