### ISSUE TITLE
Add a new organization to ROR: Multi-Modal Molecular Imaging Italian Node

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1144]
Summary of request: Add a new organization to ROR

Name of organization: Multi-Modal Molecular Imaging Italian Node
Website: http://www.mmmi.unito.it
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: MMMI
Related organizations: https://ror.org/048tbm396 (parent) https://ror.org/05d78xc36 (related) https://ror.org/01kdj2848 (related) https://ror.org/03rqtqb02 (related)
City: Turin
Country: Italy
Geonames ID: 3165524
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Imaging facility and EuroBioimaging node, hosted at https://ror.org/048tbm396. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. In scope for ROR by virtue of our facility acknowledgement use case.

See additional curation team comments here:
https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing

Facility acknowledgement: https://doi.org/10.1002/nbm.4602; https://doi.org/10.1007/s11307-021-01637-6; https://link.springer.com/article/10.1007/s10278-022-00612-z

**Comment by KellyStathis** [comment]
Agree this is is in scope for ROR. 

Main contact info lists University of Turin: http://www.mmmi.unito.it/it/content/contact-us, however there are multiple node sites in other locations: http://www.mmmi.unito.it/it/node/4. Should these be added as related? Full list here on the Euro-Bioimaging site: https://www.eurobioimaging.eu/nodes/molecular-imaging-italian-node

**Comment by adambuttrick** [comment]
@KellyStathis I think the case for this being in scope would be as a distributed infrastructure comprising these nodes. With that framing, the sub-entities would effectively be departments of the Multi-Modal Molecular Imaging Italian Node and thus out of scope.

**Comment by KellyStathis** [comment]
@adambuttrick I phrased my question poorly! I meant to ask if the other associated _institutions_ (e.g. University of Pisa) should be added in addition to University of Turin, not the sub-entities of MMMI.

**Comment by adambuttrick** [comment]
@KellyStathis Apologies for the confusion! I've added all we have in ROR as related. Need to look at possibly creating records for CNR Institute of Clinical Physiology, CNR Institute of Biostructures and BioImages, and IRCCS SDN.

**Comment by adambuttrick** [comment]
The Institute of Clinical Physiology is in ROR under its Italian name (created Issue to add English label), Institute of Biostructures and BioImages is https://ror.org/03rqtqb02, IRCCS SDN is a sub-entity of https://ror.org/04tfzc498 and likely not in scope.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0573ty638 in release v1.8.
