### ISSUE TITLE
Add a new organization to ROR: Italian Phase Contrast Imaging Flagship Node

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1145]
Summary of request: Add a new organization to ROR

Name of organization: Italian Phase Contrast Imaging Flagship Node
Website: https://www.eurobioimaging.eu/nodes/phase-contrast-imaging-flagship-node-trieste	
Link to publications: 
Organization type: 
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/05d78xc36 (related)
City: Trieste
Country: Italy
Geonames ID: 3165185
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Italian imaging facility and EuroBioimaging node. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. In scope for ROR by virtue of our facility acknowledgement use case.

See additional curation team comments here:
https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing

Facility acknowledgements: https://doi.org/10.1002/mp.15084; https://doi.org/10.1016/j.physo.2020.100050;

**Comment by nlundvick** [comment]
Hi @adambuttrick - Sounds good to me.
