### ISSUE TITLE
Add a new organization to ROR: Erasmus Optical Imaging Centre

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1146]
Summary of request: Add a new organization to ROR

Name of organization: Erasmus Optical Imaging Centre
Website: https://erasmusoic.nl
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Aliases: Erasmus Optical Imaging Center; Erasmus OIC
Labels:
Related organizations: https://ror.org/018906e22 (parent) https://ror.org/05d78xc36 (related)
City: Rotterdam
Country: Netherlands
Geonames ID: 2747891
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Imaging center that is part of https://ror.org/018906e22. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. In scope for ROR by virtue of our facility acknowledgement use case.

See additional curation team comments here:
https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing

Publication affiliation usage: https://doi.org/10.1038/ncomms14388; https://doi.org/10.1016/j.ccell.2019.01.008; https://doi.org/10.1016/j.jacc.2015.01.040; https://doi.org/10.3390/bioengineering6010007; https://doi.org/10.1038/nmeth.3891; https://doi.org/10.1093/cercor/bhx203

**Comment by mariagould** [comment]
Agree this is in scope given evidence of research activity and affiliation usage.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00hjpwn75 in release v1.12.
