### ISSUE TITLE
Add a new organization to ROR: BIMM University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11479]
Summary of request: Add a new organization to ROR

Name of organization: BIMM University*en
Website: https://www.bimm.university
Domains: bimm.university
Link to publications: https://api.crossref.org/works?query.affiliation=bimm&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/BIMM_University
Wikidata ID: Q4967681
ISNI ID: 0000 0004 0485 3078
GRID ID:
Crossref Funder ID:
Other names for the organization: BIMM University Ltd*en; BIMM Institute*en; Brighton Institute of Modern Music*en; British and Irish Modern Music Institute*en
Aliases:
Labels:
Acronym/abbreviation:
Related organizations: 
City: Brighton
Country: UK
Geonames ID: 2654710
Year established: 2001
How will a ROR ID for this organization be used? To identify researchers
Other information about this request:

**Comment by adambuttrick** [comment]
Private university in the UK. Funds and employs researchers. Solid affiliation usage. Should be added.
