### ISSUE TITLE
Add a new organization to ROR: Van Leeuwenhoek Centre for Advanced Microscopy

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1148]
Summary of request: Add a new organization to ROR

Name of organization: Van Leeuwenhoek Centre for Advanced Microscopy
Website: http://www.lcam.nl
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: LCAM
Related organizations: https://ror.org/04dkp9463 (parent) https://ror.org/03xqtf034 (parent) https://ror.org/05d78xc36 (related)
City: Amsterdam
Country: Netherlands
Geonames ID: 2759794
Year established: 2011
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Shared microscopy infrastructure hosted by https://ror.org/04dkp9463 and https://ror.org/03xqtf034. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. In scope for ROR by virtue of our facility acknowledgement use case.

See additional curation team comments here:
https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing

Publication affiliation usage: https://doi.org/10.1038/nmeth.4074; https://doi.org/10.1038/ncomms1738
Facility acknowledgements: https://doi.org/10.1091/mbc.E14-08-1296; https://doi.org/10.1007/s11060-013-1235-y

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activity and affiliation usage.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/013rctf62 in release v1.12.
