### ISSUE TITLE
Add a new organization to ROR: Brain Imaging Network

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1149]
Summary of request: Add a new organization to ROR

Name of organization: Brain Imaging Network
Website: https://www.uc.pt/en/brainimaging
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/04z8k9a98 (parent) https://ror.org/05d78xc36 (related)
City: Coimbra
Country: Portugal
Geonames ID: 2740637
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Multimodal medical imaging center based out of https://ror.org/04z8k9a98. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. In scope for ROR by virtue of our facility acknowledgement use case.

See additional curation team comments here:
https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing

Publication affiliation usage: https://doi.org/10.1371/journal.pone.0086213; https://doi.org/10.1093/brain/aww160; https://doi.org/10.1016/j.nicl.2016.12.013; https://doi.org/10.1002/hbm.23266; https://doi.org/10.1088/1741-2560/12/2/026008

ORCID affiliation usage: https://orcid.org/0000-0001-7315-0550

**Comment by mariagould** [comment]
I think this is in scope given evidence of research activities, affiliation usage, and facility acknowledgments.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01d3r6z34 in release v1.12.
