### ISSUE TITLE
Modify the information in an existing ROR record: 
IK4-AZTERLAN (https://ror.org/009mwwv16)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#115]
Summary of request: Modify the information in an existing ROR record

Name of organization: IK4-AZTERLAN
ROR ID: https://ror.org/009mwwv16

Description of change: The commercial name of our organization has changed.Our current name is: AZTERLAN Metallurgy Research Centre

Update: change.name==AZTERLAN; add.aliases==AZTERLAN Metallurgy Research Centre; add.aliases==Fundación AZTERLAN; add.aliases==IK4-Azterlan; add.labels==AZTERLAN Metalurgia Ikerketa Zentroa*Basque; add.labels==AZTERLAN Centro de Investigación Metalúrgica*es;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
