### ISSUE TITLE
Add a new organization to ROR: Rift Valley Technical Training Institute

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11502]
Summary of request: Add a new organization to ROR

Name of organization: Rift Valley Technical Training Institute*en
Website: https://rvti.ac.ke
Domains: rvti.ac.ke
Link to publications: http://afritvetjournal.org/index.php/Afritvet/article/view/85 https://www.afritvet.org/index.php/Afritvet/article/view/151 http://www.afritvetjournal.org/index.php/Afritvet/article/view/57
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Rift_Valley_Technical_Training_Institute
Wikidata ID: Q28223339
ISNI ID: 0000 0004 9410 2963
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Rift Valley Technical and Trade High School*en; Taasisi ya Mafunzo ya Ufundi ya Bonde la Ufa*sw
Labels:
Acronym/abbreviation: RVTTI*en
Related organizations: 
City: Eldoret
Country: Kenya
Geonames ID: 198629
Year established: 1962
How will a ROR ID for this organization be used? To ID researchers
Other information about this request:

**Comment by adambuttrick** [comment]
Higher educational institute in Kenya. Funds and employs researchers. Solid affiliation usage. Should be added.
