### ISSUE TITLE
Add a new organization to ROR: Portuguese Platform of BioImaging

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1150]
Summary of request: Add a new organization to ROR

Name of organization: Portuguese Platform of BioImaging
Website: https://www.ppbi.pt
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0005 0634 7029
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/05d78xc36 (related)
City: Lisbon
Country: Portugal
Geonames ID: 2267057
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Consortium of top research universities and institutes in Portugal providing a shared platform for advanced microscopy and processing/analysis of life science images. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. In scope for ROR by virtue of our facility acknowledgement use case.

See additional curation team comments here:
https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing

Facility acknowledgement: https://doi.org/10.1016/j.fsigss.2019.10.091; https://doi.org/10.4103/1673-5374.324827

**Comment by mariagould** [comment]
I agree this in scope given evidence of research activities and facility acknowledgments.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0479zfq62 in release v1.12.
