### ISSUE TITLE
Add a new organization to ROR: National Microscopy Infrastructure

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1151]
Summary of request: Add a new organization to ROR

Name of organization: National Microscopy Infrastructure
Website: https://www.nmisweden.se
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: NMI
Related organizations: https://ror.org/026vcq606 (related) https://ror.org/05f0yaq80 (related) https://ror.org/05kb8h459 (related) https://ror.org/01tm6cn81 (related) https://ror.org/048a87296 (related) https://ror.org/05d78xc36 (related)
City: Stockholm
Country: Sweden
Geonames ID: 2673730
Year established: 2016
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Consortium of Swedish universities providing a shared platform for advanced microscopy and processing/analysis of life science images. Submitted as part of Euro-Bioimaging nodes project on https://github.com/ror-community/ror-updates/issues/778. Funds and employs researchers. In scope for ROR by virtue of our facility acknowledgement use case.

See additional curation team comments here:
https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing

Facility acknowledgments: https://doi.org/10.1364/BOE.8.004135; https://doi.org/10.1186/s13287-018-1017-8
ORCID affiliation usage: https://orcid.org/0000-0003-2216-2900

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities and facility acknowledgments (and similar entities in ROR).

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01mq2eh43 in release v1.12.
