### ISSUE TITLE
Add a new organization to ROR: Kibi Presbyterian College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11532]
Summary of request: Add a new organization to ROR

Name of organization: Kibi Presbyterian College of Education*en
Website: https://kpce.edu.gh
Domains: kpce.edu.gh
Link to publications: http://api.crossref.org/works?query.affiliation=kibi+Presbyterian&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Kibi_Presbyterian_College_of_Education
Wikidata ID: Q46996973
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: Kibi Presbyterian CoE*en
Aliases:
Labels:
Acronym/abbreviation: KPCE*en
Related organizations: https://ror.org/0492nfe34 (related)
City: Kibi
Country: Ghana
Geonames ID: 2299636
Year established: 1963
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
