### ISSUE TITLE
Add a new organization to ROR: Mount Mary College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11535]
Summary of request: Add a new organization to ROR

Name of organization: Mount Mary College of Education*en
Website: http://mmce.edu.gh
Domains: mmce.edu.gh
Link to publications: https://royalliteglobal.com/jlfl/article/view/446 https://royalliteglobal.com/ijoras/article/view/440 https://sinomicsjournal.com/index.php/SJ/article/view/7
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Mount_Mary_College_of_Education
Wikidata ID: Q46996976
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: Mt. Mary College of Education*en
Aliases: École normale supérieure Mount Mary*fr
Labels:
Acronym/abbreviation: MMCE*en; MOMACOE*en
Related organizations: https://ror.org/01r22mr83 (related)
City: Somanya
Country: Ghana
Geonames ID: 2295236
Year established: 1947
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
