### ISSUE TITLE
Add a new organization to ROR: Presbyterian Women's College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11553]
Summary of request: Add a new organization to ROR

Name of organization: Presbyterian Women's College of Education*en
Website: https://pwce.edu.gh
Domains: pwce.edu.gh
Link to publications: [here](https://www.researchgate.net/profile/Saviour-Adjibolosoo/publication/364279122_EXPLORING_SOURCES_OF_PLASTIC_WASTE_IN_THE_COLLEGES_OF_EDUCATION_IN_GHANA_THE_CASE_OF_PRESBYTERIAN_WOMEN'S_COLLEGE_OF_EDUCATION-GHANA/links/6342b250ff870c55ce1292ff/EXPLORING-SOURCES-OF-PLASTIC-WASTE-IN-THE-COLLEGES-OF-EDUCATION-IN-GHANA-THE-CASE-OF-PRESBYTERIAN-WOMENS-COLLEGE-OF-EDUCATION-GHANA.pdf) [here](https://d1wqtxts1xzle7.cloudfront.net/49659273/ASSISTING_BASIC_SIX.-libre.pdf?1476698706=&response-content-disposition=inline%3B+filename%3DAssisting_Basic_Six_Pupils_of_Presbyteri.pdf&Expires=1716480508&Signature=TL3sv4EpjB47-lwV6vMDVp6FplAZLjJwHi9bFKnKErmlt9oqUv~44mHaWozCzAVLuVxcQYXdrPU84qbQ8bwP28EDNXY~gDe2ZTdrrFuYR5F-az1sLIQbDcTFz0RB2tFC7bN~vf40y3AyZjHy5ga2zEVVwLMtsjVge0binwaScbkdoJsnHJuj2VxrULSAYldFvO28VFXhuf9TxFvgedCIQGXPWk0OkYpwNOg~zENn2AzzZVKrmx3QdHBiVbPbjaU7Jin794HBHJ45f3ugyuQ7oehwv17RIH6Rj~YCcALWvDjPxmZr2TDw5KuG0HqMf-s8mLssg-O1MA5pRbTY5FMQOw__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA) [here](https://www.ajhssr.com/wp-content/uploads/2019/08/C19382136.pdf)
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Presbyterian_Women%27s_College_of_Education
Wikidata ID: Q28840538
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: Aburi Women's Teacher Training College*en
Aliases:
Labels:
Acronym/abbreviation: PWCE*en
Related organizations: 
City: Aburi
Country: Ghana
Geonames ID: 2306119
Year established: 1928
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
