### ISSUE TITLE
Add a new organization to ROR: Our Lady of Apostles College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11555]
Summary of request: Add a new organization to ROR

Name of organization: Our Lady of Apostles College of Education*en
Website: http://www.olacoe.edu.gh
Domains: olacoe.edu.gh
Link to publications: https://doi.org/10.31586/ojer.2022.190 https://doi.org/10.31586/ujssh.2021.095 https://doi.org/10.1080/2331186X.2024.2334686
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Our_Lady_of_Apostles_College_of_Education
Wikidata ID: Q25208128
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: OLA College of Education*en; OLA Training College*en
Aliases:
Labels:
Acronym/abbreviation: OLACoE*en
Related organizations: https://ror.org/0492nfe34 (related)
City: Cape Coast
Country: Ghana
Geonames ID: 2302357
Year established: 1924
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
