### ISSUE TITLE
Add a new organization to ROR: Presbyterian College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11552]
Summary of request: Add a new organization to ROR

Name of organization: Presbyterian College of Education*en
Website: https://pce.edu.gh
Domains: pce.edu.gh
Link to publications: https://doi.org/10.58421/misro.v3i2.183 [here](https://d1wqtxts1xzle7.cloudfront.net/94352508/EJ1042469-libre.pdf?1668624492=&response-content-disposition=inline%3B+filename%3DProviding_Information_Communication_Tech.pdf&Expires=1716479955&Signature=N23sCxwPTDfcINdrdzd7mzdM3TUSMocMG5SzYU0tww1PGidStgXfJkJP-a2FEoAERow0LJ-j7alWDvtYQQwLdipHXmGFnJF5nmdkXRtNMee58CkzuWDOnkDdnV7aJuAGFX7Sdav~V-ItufyNkGPiSAq~EYCIAOK7OvsWLrGhlVhi2cFdKFkH6NPh7~ffyl5UUC8jGyb2paxi1Q~QmIv5nTIQxVYAVG5228KH4iHmEGuYmVeGnZaordE3Csj~dwcA~SKYJkwTjjTOWxtgX7Lvwz944gpx-uziWIKJtOCjjcz-ZZNOujP-uyVRkfgWb8jjWgtShtlxROYHJ9s6GJmT4Q__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA) https://www.fnasjournals.com/index.php/FNAS-JMSE/article/view/332
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Presbyterian_College_of_Education,_Akropong
Wikidata ID: Q48800046
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: Presbyterian College of Education, Akropong*en; Presbyterian College of Education, Akropong-Akuapem*en; Akropong College of Education*en; Presbyterian Training College, Akropong*en; Scottish Mission Teacher Training College*en; Basel Mission Seminary, Akropong*en; PCE Akropong*en
Aliases:
Labels:
Acronym/abbreviation: PCE*en
Related organizations: https://ror.org/00y1ekh28 (related)
City: Akropong
Country: Ghana
Geonames ID: 2305027
Year established: 1848
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
