### ISSUE TITLE
Add a new organization to ROR: Komenda College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11556]
Summary of request: Add a new organization to ROR

Name of organization: Komenda College of Education*en
Website: https://komendacollege.edu.gh
Domains: komendacollege.edu.gh
Link to publications: http://api.crossref.org/works?query.affiliation=komenda&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Komenda_College_of_Education
Wikidata ID: Q46996974
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation:
Related organizations: https://ror.org/00y1ekh28 (related)
City: Komenda
Country: Ghana
Geonames ID: 2299392
Year established: 1948
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. :find
