### ISSUE TITLE
Add a new organization to ROR: Al-Qalam University College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11558]
Summary of request: Add a new organization to ROR

Name of organization: Al-Qalam University College*en
Website: https://alqalam.edu.iq
Domains: alqalam.edu.iq
Link to publications: https://doi.org/10.52866/ijcsm.2021.02.01.001 https://doi.org/10.1158/1538-7445.AM2019-3932 https://doi.org/10.1097/ms9.0000000000000810
Organization type: Education
Organization status: Active
Wikipedia page:
Wikidata ID: Q126075532
ISNI ID: 0000 0005 1316 2655
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: 
Labels: كلية القلم الجامعة*ar
Acronym/abbreviation:
Related organizations: 
City: Kirkuk
Country: Iraq
Geonames ID: 94787 
Year established: 2009
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Iraq. Funds and employs researchers. Solid affiliation usage. Should be added.
