### ISSUE TITLE
Add a new organization to ROR: Foso College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11562]
Summary of request: Add a new organization to ROR

Name of organization: Foso College of Education*en
Website: https://fosco.edu.gh
Domains: fosco.edu.gh
Link to publications: https://doi.org/10.55529/jlls.31.20.30 https://doi.org/10.1080/2331186X.2024.2334686 
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Foso_College_of_Education
Wikidata ID: Q46996967
ISNI ID: 
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: FOSCO*en
Related organizations: https://ror.org/0492nfe34 (related)
City: Foso
Country: Ghana
Geonames ID: 2300883
Year established: 1965
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
