### ISSUE TITLE
Add a new organization to ROR: Accra College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11563]
Summary of request: Add a new organization to ROR

Name of organization: Accra College of Education*en
Website: https://acce.edu.gh
Domains: acce.edu.gh
Link to publications: https://doi.org/10.1080/2331186X.2023.2175515 https://www.scipublications.com/journal/index.php/ojer/article/view/924 http://publications.uew.edu.gh/2015/sites/default/files/78-85%20Dontoh.pdf
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Accra_College_of_Education
Wikidata ID: Q46996954
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Accra Teacher Training College*en
Labels:
Acronym/abbreviation: AcCE*en; ATTRACO*en
Related organizations: https://ror.org/01r22mr83 (related)
City: Accra
Country: Ghana
Geonames ID: 2306104
Year established: 1909
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
