### ISSUE TITLE
Add a new organization to ROR: Research Bridge Publisher

### ISSUE THREAD

**Issue by admin-muo** [ror-community/ror-updates#11566]
Summary of request: Add a new organization to ROR

Name of organization: Research Bridge Publisher
Website: https://researchbridgepublisher.com
Domains: researchbridgepublisher.com
Link to publications: https://researchbridgepublisher.com/index.php/ijsshr
Organization type: Publisher
Organization status: Public
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation:
Related organizations: 
City: 
Country:
Geonames ID: 
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
ROR requires a location for the organization to create records and there does not appear to be any publicly facing attestation on this organization's site. Describes itself as publishing three journals, one of which asserts external indexing while not appearing to have any issues, https://researchbridgepublisher.com/index.php/ijhs. This does not appear to be consistent with our [publisher guidelines](https://github.com/ror-community/ror-updates/wiki/Curator-Evaluation-Workflow:-New-Records#guidance-for-evaluating-publishers), so declining as out of scope.
