### ISSUE TITLE
Add a new organization to ROR: Ada College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11597]
Summary of request: Add a new organization to ROR

Name of organization: Ada College of Education*en
Website: https://adacoe.edu.gh
Domains: adacoe.edu.gh
Link to publications: https://doi.org/10.2478/atd-2024-0004 https://doi.org/10.38159/ehass.2022381 https://qabasjournals.com/index.php/ejlll/article/view/179/173
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Ada_College_of_Education
Wikidata ID: Q46996955
ISNI ID: 0000 0005 0262 624X
GRID ID:
Crossref Funder ID:
Other names for the organization: Ada Teacher Training College*en
Aliases: 
Labels:
Acronym/abbreviation: AdaCoE*en; AdaCo*en
Related organizations: 
City: Ada Foah
Country: Ghana
Geonames ID: 2306019
Year established: 1965
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
