### ISSUE TITLE
Add a new organization to ROR: St. John Bosco College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11602]
Summary of request: Add a new organization to ROR

Name of organization: St. John Bosco College of Education*en
Website: https://bosco.edu.gh
Domains: bosco.edu.gh
Link to publications: https://doi.org/10.58425/jetm.v2i2.178  https://doi.org/10.1016/j.foodcont.2019.106841 https://doi.org/10.1111/jfs.12792
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/St._John_Bosco%27s_College_of_Education
Wikidata ID: Q46996985
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: St. John Bosco's College of Education*en; Bosco's College of Education*en; Saint John Bosco College of Education*en
Aliases:
Labels:
Acronym/abbreviation: 
Related organizations: 
City: Navrongo
Country: Ghana
Geonames ID: 2297505
Year established: 1946
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
