### ISSUE TITLE
Add a new organization to ROR: Tumu College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11610]
Summary of request: Add a new organization to ROR

Name of organization: Tumu College of Education*en
Website: https://tuce.edu.gh
Domains: tuce.edu.gh
Link to publications: https://doi.org/10.21083/ajote.v13i1.7535 https://core.ac.uk/download/pdf/234641805.pdf https://embarpublishers.com/assets/articles/1665674246.pdf
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Tumu_College_of_Education
Wikidata ID: Q46996990
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels:
Acronym/abbreviation: TuCE*en
Related organizations: 
City: Tumu
Country: Ghana
Geonames ID: 2294342
Year established: 1984
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
