### ISSUE TITLE
Add a new organization to ROR: Nusrat Jahan Ahmadiyya College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11611]
Summary of request: Add a new organization to ROR

Name of organization: Nusrat Jahan Ahmadiyya College of Education*en
Website: https://www.njace.edu.gh
Domains: njace.edu.gh
Link to publications: https://doi.org/10.11648/j.tecs.20230802.17 https://aspjournals.org/ajahss/index.php/ajahss/article/view/22 https://doi.org/10.54536/ajiri.v2i3.1925 
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Nusrat_Jahan_Ahmadiyya_College_of_Education
Wikidata ID: Q46996978
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: N. J. Ahmadiyya College of Education*en; NJA College of Education*en
Aliases:
Labels:
Acronym/abbreviation: NJACoE*en
Related organizations: 
City: Wa
Country: Ghana
Geonames ID: 2294206
Year established: 1982
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
