### ISSUE TITLE
Modify the information in an existing ROR record:  Nakhchivan University - https://ror.org/01dqrx648

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11668]
Summary of request: Modify the information in an existing ROR record

Name of organization: Nakhchivan University
ROR ID: https://ror.org/01dqrx648
Which part of the record needs to be changed? Wikidata
Description of change: + Q6002003

Update: wikidata.all.add==Q6002003 | wikidata.preferred.replace==Q6002003 | isni.all.add==0000 0005 1433 0884
 | isni.preferred.replace==0000 0005 1433 0884 | website.replace==https://nu.edu.az | domains.add==nu.edu.az$

**Comment by adambuttrick** [comment]
ID provided is that for the organization.
