### ISSUE TITLE
Modify the information in an existing ROR record: 
University of Bergen (https://ror.org/03zga2b32)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#117]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Bergen
ROR ID: https://ror.org/03zga2b32

Description of change: Remove finish name, add new names and update web reference

Names:
University of Bergen
Universitetet i Bergen
Universitas Bergensis
Bergen University

website: http://www.uib.no/en

I don't know what "Crossref Funder ID 501100005036" should be, but the link doesn't work
Update: delete.aliases==Universitetet i Bergen; add.labels==Universitetet i Bergen*Norwegian; add.labels==Universitas Bergensis*Latin; delete.links==http://www.uib.no/en/node/36362; add.links==http://www.uib.no/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
