### ISSUE TITLE
Add a new organization to ROR: Modern Business School

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11718]
Summary of request: Add a new organization to ROR

Name of organization: Modern Business School*en
Website: https://mbs.edu.rs
Domains: mbs.edu.rs
Link to publications: https://doi.org/10.1515/ethemes-2017-0023 https://doi.org/10.5937/nabepo27-34803 https://doi.org/10.58898/ijmt.v2i1.64-70 
Organization type: Education
Organization status: Active
Wikipedia page: 
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: Visoka škola modernog biznisa*sr
Acronym/abbreviation: MBS*en
Related organizations: 
City: Belgrade
Country: Serbia
Geonames ID: 792680
Year established: 2008
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Higher educational institute Serbia. Funds and employs researchers. Solid affiliation usage. Should be added.
