### ISSUE TITLE
Add a new organization to ROR: MoreBrains Cooperative

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#11715]
Summary of request: Add a new organization to ROR

Name of organization: MoreBrains Cooperative (United Kingdom)*en
Website: https://www.morebrains.coop
Domains: morebrains.coop
Link to publications: https://zenodo.org/communities/morebrains_cooperative/records?q=&l=list&p=1&s=10&sort=newest 
Organization type: Company
Organization status: Active
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: MoreBrains Consulting*en
Labels: MoreBrains Cooperative*en
Acronym/abbreviation:
Related organizations: 
City: Chichester
Country: UK
Geonames ID: 2653192
Year established: 
How will a ROR ID for this organization be used? For author affiliations 
Other information about this request: Happened to chat with Alice Meadows at SSP and she mentioned that she's been meaning to request a ROR ID for MoreBrains, so I said I'd request one for her

**Comment by adambuttrick** [comment]
Research consultancy in the UK. Affiliation usage looks fine, has multiple staff, so this can be added.
