### ISSUE TITLE
Add a new organization to ROR: Seventh-day Adventist College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11765]
Summary of request: Add a new organization to ROR

Name of organization: Seventh-day Adventist College of Education*en
Website: https://sedacoe.edu.gh
Domains: sedacoe.edu.gh
Link to publications: https://doi.org/10.18860/ijtlm.v5i1.13212 https://doi.org/10.53696/27753719.3174 https://doi.org/10.31586/ujll.2022.570
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Adventist_College_of_Education
Wikidata ID: Q46996982
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Adventist College of Education, Asokore-Koforidua*en; S. D. A. College of Education*en; SDA College of Education, Asokore-Koforidua*en 
Labels:
Acronym/abbreviation: SEDACOE*en
Related organizations: 
City: Koforidua
Country: Ghana
Geonames ID: 2299522
Year established: 1962
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
