### ISSUE TITLE
Add a new organization to ROR: Galala University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11767]
Summary of request: Add a new organization to ROR

Name of organization: Galala University*en
Website: https://www.gu.edu.eg
Domains: gu.edu.eg
Link to publications: http://api.crossref.org/works?query.affiliation=galala&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Galala_University
Wikidata ID: Q96757061
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: Al-Galala University*en
Aliases:
Labels: جامعة الجلالة*ar
Acronym/abbreviation: GU*en
Related organizations: 
City: Suez
Country: Egypt
Geonames ID: 359796
Year established: 2020
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Egypt. Funds and employs researchers. Solid affiliation usage. Should be added.
