### ISSUE TITLE
Modify the information in an existing ROR record: Tavria State Agrotechnological University - https://ror.org/01v2hty12

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11770]
Summary of request: Modify the information in an existing ROR record

Name of organization: Tavria State Agrotechnological University
ROR ID: https://ror.org/01v2hty12
Which part of the record needs to be changed? +Alt name
Description of change: Add alt: Dmytro Motornyi Tavria State Agrotechnological University*en

Update: aliases.add==Dmytro Motornyi Tavria State Agrotechnological University*en | domains.add==tsatu.edu.ua$

**Comment by adambuttrick** [comment]
Affiliation usage exists with this form, so this is fine to add.
