### ISSUE TITLE
YER xSP

### ISSUE THREAD

**Issue by alievinfo** [ror-community/ror-updates#11780]
Summary of request: Add a new organization to ROR

Name of organization: YER xSP
Website: https://yer.az
Domains: yer.az; yer.cloud
Link to publications: 
Organization type: Hosting Provider
Organization status: Active
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: yeraz
Labels:
Acronym/abbreviation:
Related organizations: 
City: Baku
Country: Azerbaijan
Geonames ID: 
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
No evidence of affiliation usage or funding activities I can find, nor were any provided in the request. ROR requires these to be added to the registry, so declining as out of scope.
