### ISSUE TITLE
Add a new organization to ROR: Enchi College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11798]
Summary of request: Add a new organization to ROR

Name of organization: Enchi College of Education*en
Website: https://www.enchicoe.edu.gh
Domains: enchicoe.edu.gh
Link to publications: http://api.crossref.org/works?query.affiliation=enchi&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Enchi_College_of_Education
Wikidata ID: Q46996964
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: ENCHICOE*en
Related organizations: https://ror.org/01r22mr83 (related)
City: Enchi
Country: Ghana
Geonames ID: 2301174
Year established: 1965
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
