### ISSUE TITLE
Add a new organization to ROR: Osol Aldeen University College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11809]
Summary of request: Add a new organization to ROR

Name of organization: Osol Aldeen University College*en
Website: https://ouc.edu.iq
Domains: ouc.edu.iq
Link to publications: http://api.crossref.org/works?query.affiliation=osol&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://ar.wikipedia.org/wiki/%D9%83%D9%84%D9%8A%D8%A9_%D8%A3%D8%B5%D9%88%D9%84_%D8%A7%D9%84%D8%AF%D9%8A%D9%86_%D8%A7%D9%84%D8%AC%D8%A7%D9%85%D8%B9%D8%A9
Wikidata ID: Q25450390
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Osol Aldeen Private University College*en; Osol Al-Deen University College*en
Labels: كلية أصول الدين الجامعة*ar
Acronym/abbreviation: OAC*en
Related organizations: 
City: Baghdad
Country: Iraq
Geonames ID: 98182
Year established: 2011
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Iraq. Funds and employs researchers. Solid affiliation usage. Should be added.
