### ISSUE TITLE
Modify the information in an existing ROR record:

### ISSUE THREAD

**Issue by garshol** [ror-community/ror-updates#11804]
Summary of request: Modify the information in an existing ROR record

Name of organization: Norwegian Institute of Public Health
ROR ID: https://ror.org/046nvst19
Which part of the record needs to be changed? a part of-case 
Description of change: Merge of to institutions
https://ror.org/03sm1ej59 is now a part of https://ror.org/046nvst19

**Comment by adambuttrick** [comment]
Instead of merging, we would identify https://ror.org/046nvst19 as the parent on https://ror.org/03sm1ej59. https://ror.org/03sm1ej59 needs additional updates, so I'll process this change there.
