### ISSUE TITLE
Add a new organization to ROR: Alfalah University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11811]
Summary of request: Add a new organization to ROR

Name of organization: Alfalah University*en
Website: https://alfalah.edu.af
Domains: alfalah.edu.af
Link to publications: http://api.crossref.org/works?query.affiliation=Alfalah&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Alfalah_University,_Jalalabad
Wikidata ID: Q48798646
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: الفلاح پوهنتون*ps; Alfalah universiteti*uz
Acronym/abbreviation:
Related organizations: 
City: Jalalabad
Country: Afghanistan
Geonames ID: 1139715
Year established: 2011
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Afghanistan. Funds and employs researchers. Solid affiliation usage. Should be added.
