### ISSUE TITLE
Add a new organization to ROR: Police Staff College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11852]
Summary of request: Add a new organization to ROR

Name of organization: Police Staff College*en
Website: https://psc.gov.bd
Domains: psc.gov.bd
Link to publications: https://doi.org/10.31014/aior.1991.07.01.462 https://doi.org/10.22259/2638-4787.0701001 https://doi.org/10.26717/BJSTR.2023.52.008264 
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Police_Staff_College,_Bangladesh
Wikidata ID: Q7209508
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Police Staff College Bangladesh*en
Labels: পুলিশ স্টাফ কলেজ*bn
Acronym/abbreviation: PSC*en
Related organizations: 
City: Dhaka
Country: Bangladesh
Geonames ID: 1185241
Year established: 2000
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
