### ISSUE TITLE
Modify the information in an existing ROR record: Jessore University of Science and Technology - https://ror.org/04eqvyq94

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11851]
Summary of request: Modify the information in an existing ROR record

Name of organization: Jessore University of Science and Technology
ROR ID: https://ror.org/04eqvyq94
Which part of the record needs to be changed? Primary name
Description of change: Name changed in 2018. Update primary name to Jashore University of Science and Technology*en
Retain Jessore Science and Technology University*en as an alt name.

Update: ror_display.replace==Jashore University of Science and Technology*en | label.replace==Jashore University of Science and Technology*en;  যশোর বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়*bn | alias.add==Jessore University of Science and Technology*en | domains.add==just.edu.bd$

**Comment by adambuttrick** [comment]
Confirmed name change via the organization's site.
