### ISSUE TITLE
Add a new organization to ROR: Wiawso College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11944]
Summary of request: Add a new organization to ROR

Name of organization: Wiawso College of Education*en
Website: https://www.wce.edu.gh
Domains: wce.edu.gh
Link to publications: http://api.crossref.org/works?query.affiliation=wiawso&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Wiawso_College_of_Education
Wikidata ID: Q25051576
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Sefwi Wiawso College of Education*en; Wiawso Anglican Training College*en; Wiawso Body Corporate Training College*en
Labels:
Acronym/abbreviation: WCE*en; WATICO*en
Related organizations: https://ror.org/00y1ekh28 (related)
City: Sefwi Wiawso
Country: Ghana
Geonames ID: 2294056
Year established: 1952
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
