### ISSUE TITLE
Add a new organization to ROR: Holy Child College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#11943]
Summary of request: Add a new organization to ROR

Name of organization: Holy Child College of Education*en
Website: https://hcce.edu.gh
Domains: hcce.edu.gh
Link to publications: https://doi.org/10.5281/zenodo.1438457 https://files.eric.ed.gov/fulltext/EJ1083499.pdf https://doi.org/10.24018/ejsocial.2022.2.2.246
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Holy_Child_College_of_Education
Wikidata ID: Q46996971
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Holicoe*en
Labels:
Acronym/abbreviation: HCCE*en
Related organizations: https://ror.org/0492nfe34 (related)
City: Takoradi
Country: Ghana
Geonames ID: 2294915
Year established: 1946
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
