### ISSUE TITLE
Add a new organization to ROR: PLA Navy Submarine Academy

### ISSUE THREAD

**Issue by Hagooddemon** [ror-community/ror-updates#1195]
Summary of request: Add a new organization to ROR 

Name of organization: PLA Navy Submarine Academy
Website: https://www.qtxy.mil.cn
Link to publications: 
Organization type: Education
Wikipedia page: https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%9B%BD%E4%BA%BA%E6%B0%91%E8%A7%A3%E6%94%BE%E5%86%9B%E6%B5%B7%E5%86%9B%E6%BD%9C%E8%89%87%E5%AD%A6%E9%99%A2
Wikidata ID: Q10873002
ISNI ID: 0000 0004 1761 1449
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: NSA; PLA NSA
Aliases: People's Liberation Army Navy Submarine Academy
Labels: 海军潜艇学院*Chinese
Related organizations: https://ror.org/05tf9r976 (parent)
City: Qingdao
Country: China
Geonames ID: 1797929
Year established:1953
How will a ROR ID for this organization be used? 
Other information about this request:To identify affiliations for research publications

**Comment by arthurpsmith** [comment]
Looks good, yes should be in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0585bz443 in release v1.12.
