### ISSUE TITLE
Add a new organization to ROR: Qingdao Institude of collaborative innovation

### ISSUE THREAD

**Issue by Hagooddemon** [ror-community/ror-updates#1196]
Summary of request: Add a new organization to ROR: Qingdao Institude of collaborative innovation

Name of organization: Qingdao Institute of Collaborative Innovation
Website: 
Link to publications: 
Organization type: 
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: QICI
Related organizations: 
City: Qingdao
Country:China
Geonames ID: 
Year established: 2022
How will a ROR ID for this organization be used? 
Other information about this request: To identify affiliations for research publications. QICI is new research institution located at Qingdao. It has none website by now.

**Comment by adambuttrick** [comment]
Evidence of research outputs are required for review and to be added to the registry. Request can be re-submitted once these are available.
