### ISSUE TITLE
Update Acupuncture and Massage College https://ror.org/00gej0269

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#12]
**Description**: Update organization website

**Details**:
Organization name: Acupuncture and Massage College
ROR ID: https://ror.org/00gej0269
Current URL: http://www.amcollege.edu/
New URL: https://www.amcollege.edu/

Update: delete.links==http://www.amcollege.edu/; add.links==https://www.amcollege.edu/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
