### ISSUE TITLE
Add a new organization to ROR: Scientific Foundation SPIROSKI

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#120]
Summary of request: Add a new organization to ROR

Name of organization: Scientific Foundation SPIROSKI
Website: https://foundationspiroski.eu
Link to publications: 
Organization type: Nonprofit
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 8516 6789
GRID ID:
Crossref Funder ID:
Other names for the organization:
Labels: Научна фондација СПИРОСКИ*Macedonian
Acronym/abbreviation:
Related organizations: 
City: Skopje
Country: Republic of Macedonia (North Macedonia)
Geonames ID: 785842
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by nlundvick** [comment]
I am also not finding affiliation use for this organization. I did find an instance of this organization funding research (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6684436/). Other than affiliation use the organization seems to be in scope. One other note – I am not finding any information on who runs the organization on their website. Most of the links lead to empty web pages. I agree with Arthur that this is on the margins. Moving to Needs discussion.

**Comment by adambuttrick** [comment]
Situation is largely unchanged, so I think we need to decide yes or no on this. As a publisher of an open access medical journal with consistent outputs, I'd lean toward including them.

**Comment by mariagould** [comment]
I agree the website information is lacking but given its role as a publisher and evidence of funding research I think it makes sense to include this in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03xzm3p02 in release v1.3.
