### ISSUE TITLE
Deprecate an existing ROR record: Gediz University https://ror.org/0251p9z15

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#1200]
Summary of request: Deprecate an existing ROR record

Name of organization: Gediz University
ROR ID: https://ror.org/0251p9z15
Which part of the record needs to be changed? Deprecate record
Description of change: In the course of investigating #1172 I learned that Gediz University (https://ror.org/0251p9z15) has been shut down (https://en.wikipedia.org/wiki/Gediz_University). The status should be changed in ROR when functionality is in place. According to Wikipedia, there was consideration at one point of Bakırçay University (the organization referenced in #1172) as the successor to Gediz, but it appears that this did not ultimately happen, so there should be no successor indicated when we make the Gediz record inactive.
Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
Updated in release v.1.17.
