### ISSUE TITLE
Add a new organization to ROR: Akatsi College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12158]
Summary of request: Add a new organization to ROR

Name of organization: Akatsi College of Education*en
Website: http://akatsico.edu.gh
Domains: akatsico.edu.gh
Link to publications: https://doi.org/10.47963/jedp.v7i.973 http://dx.doi.org/10.46827/ejes.v10i2.4665 https://doi.org/10.29333/mathsciteacher/13133
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Akatsi_College_of_Education
Wikidata ID: Q16733330
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: AKATSICO*en
Related organizations: 
City: Akatsi
Country: Ghana
Geonames ID: 2305191
Year established: 1963
How will a ROR ID for this organization be used? 
Other information about this request: Link is currently offline

**Comment by adambuttrick** [comment]
University in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
