### ISSUE TITLE
Add a new organization to ROR: Dambai College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12161]
Summary of request: Add a new organization to ROR

Name of organization: Dambai College of Education*en
Website: https://www.dace.edu.gh
Domains: dace.edu.gh
Link to publications: https://doi.org/10.1007/s11769-021-1222-8 https://doi.org/10.47963/jem.v12i1.1003 https://doi.org/10.31586/ujssh.2022.363
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Dambai_College_of_Education
Wikidata ID: Q46996962
ISNI ID: 0000 0004 0598 6366
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Dambai Training College*en
Labels:
Acronym/abbreviation: DACE*en
Related organizations: 
City: Dambai
Country: Ghana
Geonames ID: 2301424
Year established: 1974
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
