### ISSUE TITLE
Add a new organization to ROR: Evangelical Presbyterian College of Education, Amedzofe

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12167]
Summary of request: Add a new organization to ROR

Name of organization: Evangelical Presbyterian College of Education, Amedzofe*en 
Website: 
Domains:
Link to publications: https://doi.org/10.47604/ajep.1686 https://doi.org/10.47941/jep.746 https://doi.org/10.7575/aiac.alls.v.11n.2p.74
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Evangelical_Presbyterian_College_of_Education,_Amedzofe
Wikidata ID: Q46996965
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: E. P. College of Education, Amedzofe*en; Evangelical Presbyterian College of Education in Amedzofe*en
Labels: Kwalejin Ilimi ta Presbyterian na Bishara, Amedzofe*ha
Acronym/abbreviation: AMECO*en
Related organizations: https://ror.org/01r22mr83 (related)
City: Amedzofe
Country: Ghana
Geonames ID: 2304791
Year established: 1946
How will a ROR ID for this organization be used? 
Other information about this request: There is another college of a very similar name not yet in ROR (Evangelical Presbyterian College of Education, Bimbilla) hence the need for the city in the name. See #12169

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
