### ISSUE TITLE
Add a new organization to ROR: Evangelical Presbyterian College of Education, Bimbilla

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12169]
Summary of request: Add a new organization to ROR

Name of organization: Evangelical Presbyterian College of Education, Bimbilla*en
Website: https://epcoebimbilla.edu.gh
Domains: epcoebimbilla.edu.gh
Link to publications: https://doi.org/10.2174/9789815238785124010002 https://doi.org/10.4018/978-1-6684-7649-9.ch011 https://doi.org/10.9734/arjom/2020/v16i1130246
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Evangelical_Presbyterian_College_of_Education,_Bimbilla
Wikidata ID: Q46996966
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: E. P. College of Education, Bimbilla*en; Evangelical Presbyterian College of Education in Bimbilla*en
Aliases: 
Labels: Kwalejin Ilimi ta Presbyterian, Bimbilla*ha
Acronym/abbreviation: EPCE*en; BIMBICO*en
Related organizations: 
City: Bimbilla
Country: Ghana
Geonames ID: 2303026
Year established: 1962
How will a ROR ID for this organization be used? 
Other information about this request: Distinct from the similarly named Evangelical Presbyterian College of Education, Amedzofe (#12167)

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
