### ISSUE TITLE
Add a new organization to ROR: Jasikan College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12170]
Summary of request: Add a new organization to ROR

Name of organization: Jasikan College of Education*en
Website: 
Domains:
Link to publications: https://doi.org/10.46606/eajess2023v04i03.0280 https://www.ajol.info/index.php/eajess/article/view/252759 https://doi.org/10.4314/gjg.v15i2.3
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Jasikan_College_of_Education
Wikidata ID: Q46996972
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 
Acronym/abbreviation: JCoE*en; JASICO*en
Related organizations: 
City: Jasikan
Country: Ghana
Geonames ID: 2300178
Year established: 1952
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
