### ISSUE TITLE
Add a new organization to ROR: Leipzig Research Centre Global Dynamics (ReCentGlobe)

### ISSUE THREAD

**Issue by ffoerster** [ror-community/ror-updates#12215]
Summary of request: Add a new organization to ROR

Name of organization: Leipzig Research Centre Global Dynamics*en
Website: https://recentglobe.uni-leipzig.de
Domains:
Link to publications: https://doi.org/10.4324/9780429438233, https://doi.org/10.1515/9783110690132
Organization type: Education
Organization status:
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: ReCentGlobe*en
Labels:
Acronym/abbreviation: 
Related organizations: Leipzig University
City: Leipzig
Country: Germany
Geonames ID: 2879139
Year established: 2020
How will a ROR ID for this organization be used? Integration into a new research webportal and to identify affiliations with research publications

Other information about this request:
The Leipzig Research Centre Global Dynamics is a central institution of Leipzig University. ReCentGlobe is a broad interdisciplinary cooperation dedicated to the study of globalisation projects in the past and present. More than 200 staff members work at the centre.

**Comment by adambuttrick** [comment]
Research center in Germany. Funds and employs researchers. Solid affiliation usage. Should be added.
