### ISSUE TITLE
Add a new organization to ROR: St. Teresa's College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12227]
Summary of request: Add a new organization to ROR

Name of organization: St. Teresa's College of Education*en
Website: https://teresco.edu.gh/
Domains: teresco.edu.gh
Link to publications: https://doi.org/10.55544/jrasb.2.1.16 https://doi.org/10.29333/mathsciteacher/12188 https://doi.org/10.58256/rjah.v1i3.164
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/St._Teresa%27s_College_of_Education
Wikidata ID: Q46996988
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Saint Teresa's College of Education*en
Labels: Kwalejin Ilimi ta St. Teresa*ha
Acronym/abbreviation: TERESCO*en; WOTRACO*en
Related organizations: 
City: Hohoe
Country: Ghana
Geonames ID: 2300372
Year established: 1961
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
