### ISSUE TITLE
Add a new organization to ROR: St. Francis College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12225]
Summary of request: Add a new organization to ROR

Name of organization: St. Francis College of Education*en
Website: https://franco.edu.gh
Domains: franco.edu.gh
Link to publications: https://doi.org/10.12691/education-7-6-1 https://doi.org/10.22271/allresearch.2022.v8.i2d.9440 https://doi.org/10.59324/ejceel.2023.1(2).05
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/St._Francis_College_of_Education
Wikidata ID: Q46996984
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Saint Francis College of Education*en; St. Francis' College of Education*en; St. Francis COE*en
Labels: Kwalejin Ilimi ta St. Francis*ha
Acronym/abbreviation: FRANCO*en
Related organizations: 
City: Hohoe
Country: Ghana
Geonames ID: 2300372
Year established: 1947
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
