### ISSUE TITLE
Add a new organization to ROR: McCoy College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12228]
Summary of request: Add a new organization to ROR

Name of organization: McCoy College of Education*en
Website: https://mccoycoe.edu.gh
Domains: mccoycoe.edu.gh
Link to publications: https://doi.org/10.9734/ajess/2022/v34i1720 https://doi.org/10.9734/ajess/2024/v50i21259 https://doi.org/10.55544/ijrah.2.6.3
Organization type: Education
Organization status: Active
Wikipedia page:
Wikidata ID: Q126911819
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: McCoy COE*en
Labels:
Acronym/abbreviation:
Related organizations: 
City: Nadowli
Country: Ghana
Geonames ID: 7647177
Year established: 2014
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
