### ISSUE TITLE
Add a new organization to ROR: Gbewaa College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12232]
Summary of request: Add a new organization to ROR

Name of organization: Gbewaa College of Education*en
Website: http://gbce.edu.gh
Domains: gbce.edu.gh
Link to publications: https://doi.org/10.11648/j.her.20220702.15 https://doi.org/10.37256/ser.3320221567 https://doi.org/10.4236/jss.2022.109020
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Gbewaa_College_of_Education
Wikidata ID: Q46996970
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Government Training College Pusiga*en
Labels:
Acronym/abbreviation: GBCE*en
Related organizations: https://ror.org/01r22mr83 (related)
City: Pusiga
Country: Ghana
Geonames ID: 12105116
Year established: 1963
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
