### ISSUE TITLE
Add a new organization to ROR: Gambaga College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12231]
Summary of request: Add a new organization to ROR

Name of organization: Gambaga College of Education*en
Website: https://gacoe.edu.gh
Domains: gacoe.edu.gh
Link to publications: http://api.crossref.org/works?query.affiliation=gambaga&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Gambaga_College_of_Education
Wikidata ID: Q46996969
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: GaCoE*en
Related organizations: https://ror.org/052nhnq73 (related)
City: Gambaga
Country: Ghana
Geonames ID: 2300776
Year established: 2013
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
