### ISSUE TITLE
Add a new organization to ROR: Bagabaga College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12230]
Summary of request: Add a new organization to ROR

Name of organization: Bagabaga College of Education*en
Website: http://bagabaga.edu.gh
Domains: bagabaga.edu.gh
Link to publications: http://api.crossref.org/works?query.affiliation=bagabaga&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Bagabaga_College_of_Education
Wikidata ID: Q46996960
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: BACE*en; BATCO*en
Related organizations: https://ror.org/00y1ekh28 (related)
City: Tamale
Country: Ghana
Geonames ID: 2294877
Year established: 1944
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
