### ISSUE TITLE
Modify the information in an existing ROR record: Minnesota Children's Museum - https://ror.org/031zpdg16

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12257]
Summary of request: Modify the information in an existing ROR record

Name of organization: Minnesota Children's Museum
ROR ID: https://ror.org/031zpdg16
Which part of the record needs to be changed? +Wikidata ID
Description of change: +Q6868186

Update: wikidata.all.add==Q6868186 | wikidata.preferred.replace==Q6868186$

**Comment by adambuttrick** [comment]
ID provided is that for the organization.
