### ISSUE TITLE
Add a new organization to ROR: Tamale College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12253]
Summary of request: Add a new organization to ROR

Name of organization: Tamale College of Education*en
Website: https://tace.edu.gh
Domains: tace.edu.gh
Link to publications: https://doi.org/10.38159/jelt.2021212 https://doi.org/10.15520/sslej.v3i4.2123 http://doi.org/10.46827/ejes.v10i2.4665
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Tamale_College_of_Education
Wikidata ID: Q46996989
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: TACE*en
Related organizations: 
City: Tamale
Country: Ghana
Geonames ID: 2294877
Year established: 1958
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
