### ISSUE TITLE
Add a new organization to ROR: Atebubu College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12255]
Summary of request: Add a new organization to ROR

Name of organization: Atebubu College of Education*en
Website: https://atecoe.edu.gh
Domains: atecoe.edu.gh
Link to publications: http://api.crossref.org/works?query.affiliation=atebubu&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Atebubu_College_of_Education
Wikidata ID: Q46996958
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: ATECOE*en
Related organizations: 
City: Atebubu
Country: Ghana
Geonames ID: 2303878
Year established: 1965
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
