### ISSUE TITLE
Add a new organization to ROR: Berekum College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12256]
Summary of request: Add a new organization to ROR

Name of organization: Berekum College of Education*en
Website: https://becoled.edu.gh
Domains: becoled.edu.gh
Link to publications: http://api.crossref.org/works?query.affiliation=berekum&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Berekum_College_of_Education
Wikidata ID: Q46996961
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels:
Acronym/abbreviation: BECOLED*en
Related organizations: 
City: Berekum
Country: Ghana
Geonames ID: 2303125
Year established: 1953
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
