### ISSUE TITLE
Add a new organization to ROR: St. Ambrose College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12272]
Summary of request: Add a new organization to ROR

Name of organization: St. Ambrose College of Education*en
Website: https://sace.edu.gh
Domains: sace.edu.gh
Link to publications: https://doi.org/10.38159/jelt.2023441 https://doi.org/10.54536/ajet.v3i2.2891 https://doi.org/10.11648/j.ijecs.20240902.14
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/St._Ambrose_College_of_Education
Wikidata ID: Q46996983
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Saint Ambrose College of Education*en
Labels: Kwalejin Ilimi ta St. Ambrose*ha
Acronym/abbreviation: SACE*en
Related organizations: https://ror.org/0492nfe34 (related)
City: Dormaa Akwamu 
Country: Ghana
Geonames ID: 7648973
Year established: 2009
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
