### ISSUE TITLE
Add a new organization to ROR: St. Louis College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12289]
Summary of request: Add a new organization to ROR

Name of organization: St. Louis College of Education*en
Website: https://slce.edu.gh
Domains: slce.edu.gh
Link to publications: https://doi.org/10.9734/ajess/2020/v10i330270 https://doi.org/10.4236/jss.2020.810016 http://dx.doi.org/10.46827/ejes.v8i5.3756
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/St._Louis_College_of_Education
Wikidata ID: Q46996987
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Saint Louis College of Education*en
Labels: Kwalejin Ilimi ta St. Louis*ha
Acronym/abbreviation: SLCE*en
Related organizations: https://ror.org/00y1ekh28 (related)
City: Kumasi
Country: Ghana
Geonames ID: 2298890
Year established: 1960
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
