### ISSUE TITLE
Modify the information in an existing ROR record:

### ISSUE THREAD

**Issue by kmccurley** [ror-community/ror-updates#12280]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of California, Los Angeles
ROR ID: [046rm7j60](https://ror.org/046rm7j60)
Which part of the record needs to be changed? geonames ID
Description of change: The geonames ID is currently listed as 5368361 but it should be [5404884](https://www.geonames.org/5404884/university-of-california-los-angeles.html) with associated latitude and longitude of 34.07062, -118.44455

There are quite a few locations I've found that simply have the wrong geonames ID associated with them. Another one is Macquarie University in Australia, which should be 8175215 instead of 2147714

**Comment by adambuttrick** [comment]
ROR uses the Geonames ID for the city in which the organization is located vs. the value for the place itself. There was some discussion about switching to the place name entries as part of our last round of schema revisions, but we decided against this because all organizations do not have such entries in Geonames.

**Comment by kmccurley** [comment]
In that case you should remove the geonames ID, latitude and longitude, since they bear very little relation to the actual location of the institution.  They are certainly meaningless for any geo applications, but you're showing six digits of accuracy in the latitude and longitude, AND giving the wrong geonames ID. I found examples like [04tavf782](https://ror.org/04tavf782) that are off by 30 miles.
