### ISSUE TITLE
Add a new organization to ROR: Mampong Technical College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12287]
Summary of request: Add a new organization to ROR

Name of organization: Mampong Technical College of Education*en
Website: https://mtce.edu.gh
Domains: mtce.edu.gh
Link to publications: https://doi.org/10.11591/edulearn.v15i4.20293 https://doi.org/10.54536/ajet.v2i3.1888 https://doi.org/10.24940/ijird/2021/v10/i4/159356-391055-1-SM
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Mampong_Technical_College_of_Education
Wikidata ID: Q46996975
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Mampong Technical Teachers College of Education*en
Labels:
Acronym/abbreviation: MTCE*en; MAMTECH*en
Related organizations: 
City: Mampong
Country: Ghana
Geonames ID: 2298264
Year established: 1967
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
