### ISSUE TITLE
Add a new organization to ROR: Offinso College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12288]
Summary of request: Add a new organization to ROR

Name of organization: Offinso College of Education*en
Website: https://www.ofce.edu.gh
Domains: ofce.edu.gh
Link to publications: https://doi.org/10.31586/ujll.2024.965 https://doi.org/10.37745/bje.2013/vol10n16122 https://doi.org/10.4236/ce.2023.143034
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Offinso_College_of_Education
Wikidata ID: Q46996979
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: OFCE*en; OFFINCO*en
Related organizations: https://ror.org/0492nfe34 (related)
City: Offinso
Country: Ghana
Geonames ID: 2296441
Year established: 1955
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
