### ISSUE TITLE
Add a new organization to ROR: Akrokerri College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12286]
Summary of request: Add a new organization to ROR

Name of organization: Akrokerri College of Education*en
Website: http://www.akrotco.edu.gh
Domains: akrotco.edu.gh
Link to publications: http://api.crossref.org/works?query.affiliation=Akrokerri&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Akrokerri_College_of_Education
Wikidata ID: Q46996957
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Adansi University*en; Akrokerri Training College*en; Akrokerri Teacher Training College*en
Labels:
Acronym/abbreviation: AKROTCOE*en
Related organizations: https://ror.org/00cb23x68 (related)
City: Akrokerri
Country: Ghana
Geonames ID: 11812998
Year established: 1962
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
