### ISSUE TITLE
Add a new organization to ROR: Agogo Presbyterian Women's College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12285]
Summary of request: Add a new organization to ROR

Name of organization: Agogo Presbyterian Women's College of Education*en
Website: https://apwce.edu.gh
Domains: apwce.edu.gh
Link to publications: https://doi.org/10.1111/jfpp.15994 https://doi.org/10.9734/jsrr/2021/v27i1130467 
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Agogo_Presbyterian_College_of_Education
Wikidata ID: Q46996956
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Agogo Presbyterian College of Education*en; Agogo Presby College of Education*en
Labels:
Acronym/abbreviation: APWCE*en
Related organizations: https://ror.org/00y1ekh28 (related)
City: Agogo
Country: Ghana
Geonames ID: 2305537
Year established: 1931
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
