### ISSUE TITLE
Add a new organization to ROR: St. Monica's College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12294]
Summary of request: Add a new organization to ROR

Name of organization: St. Monica's College of Education*en
Website: http://monico.edu.gh
Domains: monico.edu.gh
Link to publications: https://doi.org/10.9734/arjass/2023/v19i3430 https://doi.org/10.37256/ser.222021914 https://doi.org/10.3389/fpubh.2021.752195
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/St._Monica%27s_College_of_Education
Wikidata ID: Q48780701
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Saint Monica's College of Education*en; St. Monica College of Education*en
Labels:
Acronym/abbreviation: MONICO*en
Related organizations: https://ror.org/0492nfe34 (related)
City: Mampong
Country: Ghana
Geonames ID: 2298264
Year established: 1930
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
