### ISSUE TITLE
Add a new organization to ROR: Bia Lamplighter College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12292]
Summary of request: Add a new organization to ROR

Name of organization: Bia Lamplighter College of Education*en
Website: https://blce.edu.gh/
Domains: blce.edu.gh
Link to publications: http://api.crossref.org/works?query.affiliation=lamplighter&select=DOI,author
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Bia_Lamplighter_College_of_Education
Wikidata ID: Q85746900
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: BLCE*en
Related organizations: https://ror.org/00y1ekh28 (related)
City: Debiso
Country: Ghana
Geonames ID: 2301891
Year established: 2004
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
