### ISSUE TITLE
Add a new organization to ROR: Al-Faruq College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12291]
Summary of request: Add a new organization to ROR

Name of organization: Al-Faruq College of Education*en
Website: https://afcoe.edu.gh
Domains: afcoe.edu.gh
Link to publications: https://doi.org/10.4314/ajesms.v15i1.8 http://dx.doi.org/10.46827/ejals.v6i2.438 https://doi.org/10.47772/IJRISS.2023.70505
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Al-Faruq_College_of_Education
Wikidata ID: Q77924246
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: Al-Faruq taʼlim kolleji*uz; كلية الفاروق للتربية*ar
Acronym/abbreviation: AFCOE*en
Related organizations: https://ror.org/052nhnq73 (related)
City: Wenchi
Country: Ghana
Geonames ID: 2294086
Year established: 1991
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
