### ISSUE TITLE
Add a new organization to ROR: St. Vincent College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12295]
Summary of request: Add a new organization to ROR

Name of organization: St. Vincent College of Education*en
Website: https://www.stvinceyendi.edu.gh
Domains: stvinceyendi.edu.gh
Link to publications: https://doi.org/10.31586/ojer.2022.265 https://doi.org/10.30935/conmaths/14638 https://doi.org/10.33422/jelr.v2i2.463
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/St._Vincent_College_of_Education
Wikidata ID: Q85847309
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Saint Vincent College of Education*en
Labels: Kwalejin Ilimi ta St. Vincent*ha
Acronym/abbreviation: 
Related organizations: https://ror.org/052nhnq73 (related)
City: Yendi
Country: Ghana
Geonames ID: 2293801
Year established: 2016
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
