### ISSUE TITLE
Add a new organization to ROR: Jackson University College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12296]
Summary of request: Add a new organization to ROR

Name of organization: Jackson University College*en
Website: https://jackson.edu.gh
Domains: jackson.edu.gh
Link to publications: https://doi.org/10.5281/zenodo.8167688 https://www.researchgate.net/profile/Harry-Essel/publication/324496261_Effects_of_Student_Support_Services_on_Distance_Learners_in_Selected_Centres_of_Jackson_College_of_Education/links/5ad060c00f7e9b18965cf03d/Effects-of-Student-Support-Services-on-Distance-Learners-in-Selected-Centres-of-Jackson-College-of-Education.pdf 
Organization type: Education
Organization status: Active
Wikipedia page: 
Wikidata ID: Q126949646
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Jackson Educational Complex*en; Jackson College of Education*en
Labels:
Acronym/abbreviation: JUC*en; JEC*en
Related organizations: 
City: Kumasi
Country: Ghana
Geonames ID: 2298890
Year established: 2009
How will a ROR ID for this organization be used? 
Other information about this request: All of [Ghana's colleges of education](https://en.wikipedia.org/wiki/List_of_colleges_of_education_in_Ghana) should now be in ROR with this addition!

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
