### ISSUE TITLE
Add a new organization to ROR: Methodist College of Education

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12293]
Summary of request: Add a new organization to ROR

Name of organization: Methodist College of Education*en
Website: https://metcoe.edu.gh
Domains: metcoe.edu.gh
Link to publications: https://doi.org/10.24018/ejpolitics.2023.2.3.88 http://dx.doi.org/10.46827/ejlll.v5i2.277 https://doi.org/10.53378/352902
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Methodist_College_of_Education_(Ghana)
Wikidata ID: Q65073483
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels:
Acronym/abbreviation: METCOE*en
Related organizations: https://ror.org/00y1ekh28 (related)
City: Akim Oda
Country: Ghana
Geonames ID: 2296564
Year established: 2012
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
