### ISSUE TITLE
Modify the information in an existing ROR record: 
Kharkiv National Academy of Municipal Economy (https://ror.org/05ws31q32)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#123]
Summary of request: Modify the information in an existing ROR record

Name of organization: Kharkiv National Academy of Municipal Economy
ROR ID: https://ror.org/05ws31q32
Which part of the record needs to be changed? 
Description of change: name of the University (new name O.M.Beketov National University of Urban Economy in Kharkiv)

Update: change.name==O.M. Beketov National University of Urban Economy in Kharkiv; add.aliases==O.M. Beketov Kharkiv National University of Municipal Economy; add.aliases==Kharkiv National Academy of Municipal Economy; delete.labels==Харківський національний університет міського господарства; add.labels==Харківський національний університет міського господарства імені О. М. Бекетова*Ukrainian;

**Comment by arthurpsmith** [comment]
What Kelly proposes here makes sense to me. I think we should add the full Ukrainian name, either replacing the existing one or as an alternate label in that language - they seem to emphasize the Beketov (Бекетов) part of the name on the website now.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
