### ISSUE TITLE
Modify the information in an existing ROR record: 
Odessa State Environmental University (https://ror.org/04s92tb21)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#124]
Summary of request: Modify the information in an existing ROR record

Name of organization: Odessa State Environmental University
ROR ID: https://ror.org/04s92tb21
Which part of the record needs to be changed? 
Description of change: Institute Links need to be changed - the correct organization website is https://odeku.edu.ua/ and the Wikipedia link is to be added

Update: delete.links==http://www.odeku.edu.ua/en; add.links==https://odeku.edu.ua/; add.Wikidata==Q4331448; add.wikipedia_url==https://en.wikipedia.org/wiki/Odessa_State_Environmental_University; add.ISNI==0000 0004 5945 3653;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
