### ISSUE TITLE
Add a new organization to ROR: University of Fada N'gourma

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12418]
Summary of request: Add a new organization to ROR

Name of organization: University of Fada N'gourma*en
Website: 
Domains:
Link to publications: https://doi.org/10.4236/ae.2024.122006 https://doi.org/10.9734/cjast/2022/v41i1431717 https://doi.org/10.1002/jmv.27821
Organization type: Education
Organization status: Active
Wikipedia page: 
Wikidata ID: Q126960902
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: University de Fada*en
Labels: Université de Fada N'gourma*fr; Université de Fada-Ngourma*fr
Acronym/abbreviation: UDFG*fr
Related organizations: 
City: Fada N'Gourma
Country: Burkina Faso
Geonames ID: 2360886
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Burkina Faso. Funds and employs researchers. Solid affiliation usage. Should be added.
