### ISSUE TITLE
Add a new organization to ROR: Korn Ferry

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12428]
Summary of request: Add a new organization to ROR

Name of organization: Korn Ferry (United States)*en
Website: https://www.kornferry.com
Domains: kornferry.com
Link to publications: http://api.crossref.org/works?query.affiliation=korn+ferry&select=DOI,author
Organization type: Company
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Korn_Ferry
Wikidata ID: Q1728446
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Korn/Ferry International*en; Korn Ferry Hay Group*en; Korn Ferry Institute*en
Labels: Korn Ferry*en
Acronym/abbreviation:
Related organizations: 
City: Los Angeles
Country: United States
Geonames ID: 5368361
Year established: 1969
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Consulting firm in the US. Funds and employs researchers. Solid affiliation usage. Should be added.
