### ISSUE TITLE
Modify the information in an existing ROR record: East West College of Natural Medicine - https://ror.org/00embpk79

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12431]
Summary of request: Modify the information in an existing ROR record

Name of organization: East West College of Natural Medicine
ROR ID: https://ror.org/00embpk79
Which part of the record needs to be changed? +Wikidata
Description of change: Q16934156

Update: wikidata.preferred.replace==Q16934156 | wikidata.all.add==Q16934156$

**Comment by adambuttrick** [comment]
Confirmed Wikidata ID.
