### ISSUE TITLE
Modify the information in an existing ROR record:  Judson College - https://ror.org/04z066j96

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12439]
Summary of request: Modify the information in an existing ROR record

Name of organization: Judson College
ROR ID: https://ror.org/04z066j96
Which part of the record needs to be changed? Make inactive
Description of change: College ended operations in July 2021 per [here](https://www.judson.edu/2021/08/judson-college-board-of-trustees-vote-to-close-183-year-old-institution/). Not seeing any new research outputs in Google Scholar so hopefully any residual outputs have been published.

Update: status.replace==inactive$

**Comment by adambuttrick** [comment]
Confirmed inactive.
