### ISSUE TITLE
Modify the information in an existing ROR record: Saint Katherine College - https://ror.org/05f1eky95

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12470]
Summary of request: Modify the information in an existing ROR record

Name of organization: Saint Katherine College
ROR ID: https://ror.org/05f1eky95
Which part of the record needs to be changed? Org name, website
Description of change: Update main name to University of Saint Katherine*en, add USK*en as acronym; update website to https://www.usk.edu/

Also, they'll be closing next month but can probably be kept active a little while longer

Update: ror_display.replace==University of Saint Katherine*en | label.replace==University of Saint Katherine*en | alias.add==Saint Katherine College*en | acronym.add==USK*en | website.replace==https://www.usk.edu | domains.add==usk.edu | status.replace==inactive$

**Comment by adambuttrick** [comment]
Confirmed name change. Updating status in anticipation of closure at the end of the month.
