### ISSUE TITLE
Add a new organization to ROR: Lesbian Herstory Archives

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12473]
Summary of request: Add a new organization to ROR

Name of organization: Lesbian Herstory Archives*en
Website: https://lesbianherstoryarchives.org
Domains: lesbianherstoryarchives.org
Link to publications: https://doi.org/10.1080/10894160.2015.1083827 https://doi.org/10.1057/fr.1990.12 https://doi.org/10.5250/fronjwomestud.34.2.0261
Organization type: Archive
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Lesbian_Herstory_Archives
Wikidata ID: Q6530249
ISNI ID: 0000 0000 9499 0412
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: LHA*en
Related organizations: 
City: Brooklyn
Country: United States
Geonames ID: 5110302
Year established: 1974
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Archive in the US. Funds and employs researchers. Solid affiliation usage. Should be added.
