### ISSUE TITLE
Modify the information in an existing ROR record: Mills College - https://ror.org/01ynb8e46

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12472]
Summary of request: Modify the information in an existing ROR record

Name of organization: Mills College
ROR ID: https://ror.org/01ynb8e46
Which part of the record needs to be changed? Name, relationships, URL
Description of change: Bought by Northeastern University [in 2022](https://en.wikipedia.org/wiki/Mills_College_at_Northeastern_University). Change primary name to Mills College at Northeastern University*en. Add https://ror.org/04t5xt781 (parent). Update URL to https://mills.northeastern.edu/

pdate: ror_display.replace==Mills College at Northeastern University*en | label.replace==Mills College at Northeastern University*en | alias.add==Mills College*en | website.replace==https://mills.northeastern.edu | domains.add==mills.northeastern.edu$

Related organizations: https://ror.org/04t5xt781 (parent)

**Comment by adambuttrick** [comment]
Confirmed name change/acquisition.
