### ISSUE TITLE
Add a new organization to ROR: Microsoft Research New England (United States)

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12471]
Summary of request: Add a new organization to ROR

Name of organization: Microsoft Research New England (United States)*en
Website: https://www.microsoft.com/en-us/research/lab/microsoft-research-new-england/
Domains:
Link to publications: https://doi.org/10.1002/pro.4401 https://doi.org/10.1145/2939672.2945357 https://doi.org/10.1145/3652918
Organization type: Company
Organization status: Active
Wikipedia page: 
Wikidata ID: 
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: Microsoft Research New England*en
Acronym/abbreviation: MSR-NE*en
Related organizations: https://ror.org/00d0nc645 (parent)
City: Cambridge
Country: United States
Geonames ID: 4931972
Year established: 2008
How will a ROR ID for this organization be used? 
Other information about this request: One of several [Microsoft Research labs](https://www.microsoft.com/en-us/research/labs-locations/), of which two are already in ROR and the rest aren't (yet)

**Comment by adambuttrick** [comment]
Corporate research lab in the US. Funds and employs researchers. Solid affiliation usage. Should be added.
