### ISSUE TITLE
Add a new organization to ROR: Zhebei Mingzhou Hospital

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1249]
Summary of request: Add a new organization to ROR

Name of organization: Zhebei Mingzhou Hospital
Website: 
Link to publications: 
Organization type: Healthcare
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Aliases:
Labels:
Related organizations: 
City: Huzhou
Country: Zhejiang
Geonames ID: 1806535
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Submitted as part of a support request relating to a publication submission rejection from Hindawi (lack of a ROR ID). As far as I can tell, has no web presence beyond a reference to the hospital on the [parent company's website](http://www.sanxingelectric.com/medical.php). Affiliation usage is, however, solid, so I think this is fine to add.

Publication affiliation usage: https://doi.org/10.1016/j.yexcr.2018.04.002; https://doi.org/10.2147/cmar.s202543; https://doi.org/10.1186/s13014-020-01555-x; https://doi.org/10.1016/j.yexcr.2019.111652; https://doi.org/10.1200/jco.2019.37.4_suppl.51; https://doi.org/10.3877/cma.j.issn.1674-6880.2018.01.007; https://doi.org/10.1016/j.yexcr.2019.06.032; https://doi.org/10.1159/000491005

ORCID affiliation usage: https://orcid.org/0000-0002-9972-8821

**Comment by mariagould** [comment]
I agree this is in scope given evidence of affiliation usage.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05r7bye26 in release v1.12.
