### ISSUE TITLE
Modify the information in an existing ROR record: University of Illinois at Peoria - https://ror.org/02qrdc062

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1251]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Illinois at Peoria
ROR ID: https://ror.org/02qrdc062
Which part of the record needs to be changed? Name, relationships
Description of change: There is no U of I at Peoria. There is a Peoria campus of the University of Illinois Chicago

Update: change.name==Peoria campus of the University of Illinois System; add.aliases==University of Illinois at Peoria; delete.relationships==https://ror.org/05e94g991; delete.ISNI==0000 0001 0741 4132; replace.links==https://www.uillinois.edu;$

Related organizations: https://ror.org/02mpq6x41 (parent)

**Comment by adambuttrick** [comment]
See https://github.com/ror-community/ror-updates/issues/1234 for original context. There doesn't appear to be a standard form for this campus' name. All its colleges use differing forms. See links to colleges here](https://www.uillinois.edu/cms/One.aspx?portalId=1324&pageId=348087) for details. Even more confusing than #1250, as most colleges are University of Illinois Chicago affiliated, but one is University of Illinois system affiliated. Open to how ideas on how to best represent.

Existing name has affiliation usage (e.g. https://doi.org/10.1111/ane.12036), so preserving as an alias.

**Comment by arthurpsmith** [comment]
Definitely confusing. Again it seems like it would have been better if we didn't have this ID in the first place. However, given the two parent organizations (UIC and UIS) there may be some point in retaining this ID with some sort of suitable name to retain a record of both relationships. The website link is broken and the ISNI is for the "University of Illinois College of Medicine" of which this contains only a part, so I would remove both of those. Can we call it "Peoria campus of the University of Illinois System" with both UIC and UIS as parents?
The only other good option I see is creating a bunch of separate ID's for the various colleges which seems to be the actual structure that UI recognizes here.

**Comment by adambuttrick** [comment]
Record updated in release v1.17.
