### ISSUE TITLE
Modify the information in an existing ROR record: CEA Saclay - https://ror.org/03n15ch10

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#12594]
Summary of request: Modify the information in an existing ROR record

Name of organization: CEA Saclay
ROR ID: https://ror.org/03n15ch10
Which part of the record needs to be changed? Name
Description of change: Part of DTIC reconciliation. CEA Saclay is now called CEA Paris-Saclay. This change occurred following a reorganization in 2017, and the center now consists of multiple sites, including the CEA Saclay site (formerly a “center”), the Fontenay-aux-Roses site, and the sites of Paris, Évry, Orsay, and Caen. The CEA Paris-Saclay center is one of nine centers belonging to the French Alternative Energies and Atomic Energy Commission (CEA). https://en.wikipedia.org/wiki/CEA_Paris-Saclay. http://www-centre-saclay.cea.fr/fr redirects to the new website at:  https://www.cea.fr/paris-saclay

Update: ror_display.replace==CEA Paris-Saclay*fr | label.replace==CEA Paris-Saclay*fr | website.replace==https://www.cea.fr/paris-saclay$

Related organizatons: https://ror.org/00jjx8s55 (parent) https://ror.org/03cwzta72 (delete)

**Comment by adambuttrick** [comment]
In some French sources, CEA Saclay persists as its own unit, either underneath CEA Paris-Saclay or CEA itself. Below is an example from the authority file for their state repository service, HAL:

https://aurehal.archives-ouvertes.fr/structure/read/id/20287

So we may need to create a new record for CEA Paris-Saclay instead and put https://ror.org/03n15ch10 underneath it.

**Comment by ABES-cmc** [comment]
Hello, 
The parent record is https://ror.org/00jjx8s55 .
Inside the CEA, there are indeed 9 centers, including "Centre CEA Paris-Saclay" https://www.cea.fr/Pages/le-cea/les-centres-cea/paris-saclay.aspx . 
There are currently 2 record https://ror.org/03n15ch10 and https://ror.org/01fv25t22 both named CEA Saclay.
In my opinion, https://ror.org/03n15ch10 should be renamed as requested "CEA Paris-Saclay" and considered as child of https://ror.org/00jjx8s55 . 
Record https://ror.org/01fv25t22 should be considered as "CEA Paris-Saclay - Etablissement de Saclay" (one of the 2 children sites of CEA Paris-Saclay, the other one being "CEA Paris-Saclay - Etablissement de Fontenay-aux-roses.", which is https://ror.org/010j2gw05.

**Comment by adambuttrick** [comment]
Updating this and additional records tagged here, relative to curator review.
