### ISSUE TITLE
Add a new organization to ROR: Hématopoïèse et immunologie

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12619]
Summary of request: Add a new organization to ROR

Name of organization: Hématopoïèse et immunologie*fr
Website: https://hematim.u-picardie.fr
Domains:
Link to publications: https://u-picardie.hal.science/HEMATIM
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID: Q51779928
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 
Acronym/abbreviation: HEMATIM*fr
Related organizations: https://ror.org/01gyxrk03 (parent)
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2012
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
