### ISSUE TITLE
Add a new organization to ROR: Simplification des soins chez les patients complexes

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12615]
Summary of request: Add a new organization to ROR

Name of organization: Simplification des soins chez les patients complexes*fr
Website: https://sspc.u-picardie.fr
Domains:
Link to publications: https://u-picardie.hal.science/SSPC
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 
Acronym/abbreviation: SSPC*fr
Related organizations: https://ror.org/01gyxrk03 (parent)
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2018
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
