### ISSUE TITLE
Add a new organization to ROR: Adaptation physiologiques à l'exercice et réadaptation à l'effort

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12618]
Summary of request: Add a new organization to ROR

Name of organization: Adaptation physiologiques à l'exercice et réadaptation à l'effort*fr
Website: https://apere.u-picardie.fr
Domains:
Link to publications: https://u-picardie.hal.science/APERE
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID: Q51783509
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 
Acronym/abbreviation: APERE*fr
Related organizations: https://ror.org/01gyxrk03 (parent)
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2000
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
