### ISSUE TITLE
Add a new organization to ROR: Mécanismes physiopathologiques et conséquences des calcifications cardiovasculaires

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12614]
Summary of request: Add a new organization to ROR

Name of organization: Mécanismes physiopathologiques et conséquences des calcifications cardiovasculaires*fr
Website: https://mp3cv.u-picardie.fr
Domains:
Link to publications: 
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID: Q51784514
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: Mécanismes physiopathologiques et conséquences des calcifications cardiovasculaires*fr
Aliases:
Labels: 
Acronym/abbreviation: MP3CV
Related organizations: https://ror.org/01gyxrk03 (parent)
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2005
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
