### ISSUE TITLE
Add a new organization to ROR: Laboratoire de neurosciences fonctionnelles et pathologies

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12616]
Summary of request: Add a new organization to ROR

Name of organization: Laboratoire de neurosciences fonctionnelles et pathologies*fr
Website: https://lnfp.u-picardie.fr
Domains:
Link to publications: https://u-picardie.hal.science/LNFP
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID: Q51784106
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 
Acronym/abbreviation: LNFP*fr
Related organizations: https://ror.org/01gyxrk03
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2012
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
