### ISSUE TITLE
Add a new organization to ROR: Laboratoire de physique de la matière condensée

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12620]
Summary of request: Add a new organization to ROR

Name of organization: Laboratoire de physique de la matière condensée*fr
Website: https://lpmc.u-picardie.fr
Domains:
Link to publications: https://u-picardie.hal.science/LPMC-UPJV
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID: Q51786249
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 
Acronym/abbreviation: LPMC*fr
Related organizations: https://ror.org/01gyxrk03 (parent)
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2000
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added. Verified discrete from https://ror.org/04zaaa143.

**Comment by adambuttrick** [comment]
Assigned https://ror.org/05brss208 in release v1.50.
