### ISSUE TITLE
Add a new organization to ROR: Centre de droit privé et de sciences criminelles d'Amiens

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12625]
Summary of request: Add a new organization to ROR

Name of organization: Centre de droit privé et de sciences criminelles d'Amiens*fr
Website: http://www.ceprisca.fr
Domains:
Link to publications: https://u-picardie.hal.science/CEPRISCA
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID: Q51783091
ISNI ID: 0000 0001 0244 085X
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Centre on Private Law and Criminal Science*en
Labels: 
Acronym/abbreviation: CEPRISCA*fr
Related organizations: https://ror.org/01gyxrk03 (parent)
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2004
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
