### ISSUE TITLE
Add a new organization to ROR: Centre de recherche sur les institutions, l'industrie et les systèmes économiques d'Amiens

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12626]
Summary of request: Add a new organization to ROR

Name of organization: Centre de recherche sur les institutions, l'industrie et les systèmes économiques d'Amiens*fr
Website: https://criisea.u-picardie.fr
Domains:
Link to publications: https://u-picardie.hal.science/CRIISEA
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID: Q51780170
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: 
Acronym/abbreviation: CRIISEA*fr
Related organizations: https://ror.org/01gyxrk03 (parent)
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2004
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
