### ISSUE TITLE
Add a new organization to ROR: Centre d'Etudes Hispaniques d'Amiens

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12630]
Summary of request: Add a new organization to ROR

Name of organization: Centre d'Etudes Hispaniques d'Amiens*fr
Website: https://ceha.u-picardie.fr
Domains:
Link to publications: https://u-picardie.hal.science/CEHA
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0001 2337 0731
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 
Acronym/abbreviation: CEHA*fr
Related organizations: https://ror.org/01gyxrk03 (parent)
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2018
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
