### ISSUE TITLE
Add a new organization to ROR: Conflits, représentations et dialogues dans l'univers anglosaxon

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12632]
Summary of request: Add a new organization to ROR

Name of organization: Conflits, représentations et dialogues dans l'univers anglo-saxon*fr
Website: https://corpus.u-picardie.fr
Domains:
Link to publications: https://u-picardie.hal.science/CORPUS-UPJV
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 
Acronym/abbreviation: CORPUS*fr
Related organizations: https://ror.org/01gyxrk03 (parent)
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2008
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
