### ISSUE TITLE
Add a new organization to ROR: Centre d'histoire des sociétés, des sciences et des conflits

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12633]
Summary of request: Add a new organization to ROR

Name of organization: Centre d'histoire des sociétés, des sciences et des conflits*fr
Website: https://chssc.u-picardie.fr
Domains:
Link to publications: https://u-picardie.hal.science/CHSSC
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID: Q51784205
ISNI ID: 0000 0001 2097 4644
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 
Acronym/abbreviation: CHSSC*fr
Related organizations: https://ror.org/01gyxrk03 (parent)
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2008
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
