### ISSUE TITLE
Add a new organization to ROR: Habiter le monde

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12635]
Summary of request: Add a new organization to ROR

Name of organization: Habiter le monde*fr
Website: https://www.u-picardie.fr/habiterlemonde/
Domains:
Link to publications: 
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID: Q51780431
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 
Acronym/abbreviation:
Related organizations: https://ror.org/01gyxrk03 (parent)
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2008
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
