### ISSUE TITLE
Add a new organization to ROR: Centre de recherches en arts et esthétique

### ISSUE THREAD

**Issue by louisedessaivre** [ror-community/ror-updates#12634]
Summary of request: Add a new organization to ROR

Name of organization: Centre de recherches en arts et esthétique*fr
Website: https://www.u-picardie.fr/crae/
Domains:
Link to publications: 
Organization type: Facility
Organization status:
Wikipedia page:
Wikidata ID: Q51785614
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 
Acronym/abbreviation: CRAE*fr
Related organizations: https://ror.org/01gyxrk03
City: Amiens
Country: France
Geonames ID: 3037854
Year established: 2008
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
