### ISSUE TITLE
Modify the information in an existing ROR record: 
Dnipropetrovsk National University of Railway Transport named after Academician V. Lazaryan (https://ror.org/04b5zca04)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#127]
Summary of request: Modify the information in an existing ROR record

Name of organization: Dnipropetrovsk National University of Railway Transport named after Academician V. Lazaryan
ROR ID: https://ror.org/04b5zca04
Which part of the record needs to be changed? 
Description of change: Values of the following fields have to be changed:

1. Primary Name
Correct value [1, 2]: Dnipro National University of Railway Transport named after Academician V. Lazaryan

2. Other names or name versions listed in the record
Correct value [1, 2]: Dnipropetrovsk Institute of Railway Transport Engineers; DIIT; Дніпровський національний університет залізничного транспорту імені академіка В. Лазаряна; ДНУЗТ; Днепровский национальный университет железнодорожного транспорта имени академика В. Лазаряна; ДНУЖТ

Organization type [2]: 
Correct value: Education; Science

The reason for the change: the name and name versions are obsolete, incomplete and do not comply with the statute of the DNURT [2]

References: 

1. Official web site of the DNURT: 
http://diit.edu.ua/

2. The statute of the DNURT
http://diit.edu.ua/upload/files/shares/statute.pdf

Reviewer note: we should also add DNURT as an acronym

Update: change.name==Dnipro National University of Railway Transport named after Academician V. Lazaryan; add.acronyms==DNURT; add.acronyms==ДНУЗТ; add.acronyms==ДНУЖТ; delete.aliases==Institute of Railway Transport Engineers; add.aliases==Dnipropetrovsk Institute of Railway Transport Engineers; delete.labels==Дніпропетровський національний університет залізничного транспорту імені В. Лазаряна; add.labels==Дніпровський національний університет залізничного транспорту імені академіка В. Лазаряна*Ukrainian; delete.labels==Днепропетровский национальный университет железнодорожного транспорта; add.labels==Днепровский национальный университет железнодорожного транспорта имени академика В. Лазаряна*Russian;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
