### ISSUE TITLE
Project: Bulk updates from Ludwig-Maximilians-Universität München - https://ror.org/05591te55

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#12738]
https://ror.org/05591te55 has submitted a list of updated they would like applied to the registry. These should be reviewed and added, where appropriate.

Child organizations for https://ror.org/05591te55:

- https://ror.org/02jet3w32
- https://ror.org/02qqvpd39
- https://ror.org/025z3z560
- https://ror.org/010wkny21
- https://ror.org/04xrcta15
- https://ror.org/01mvrj242
- https://ror.org/032hzb643
- https://ror.org/002epp671
- https://ror.org/04j4kfb22
- https://ror.org/01h2vtb84

Related organizations for https://ror.org/05591te55:

- https://ror.org/02jjvb954
- https://ror.org/045495t75

Child organizations for https://ror.org/02jet3w32:

- https://ror.org/05fw3y429
- https://ror.org/03j546b66
- https://ror.org/01trny179
- https://ror.org/02794jc95

Child organization for https://ror.org/02qqvpd39:

- https://ror.org/02am8se85

Child organization for https://ror.org/010wkny21:

- https://ror.org/01996tc28

Name change for https://ror.org/04jc43x05:

Change name to Klinikum rechts der Isar.

**Comment by MSpenger** [comment]
Looks complete and good from my side: 

For related organizations for https://ror.org/05591te55 there is a digit missing from https://ror.org/045495t7 -> it should be https://ror.org/045495t75

**Comment by adambuttrick** [comment]
@MSpenger Thanks, I've created the new issue tagged above to correct.

**Comment by adambuttrick** [comment]
Addressed with release v1.51.

**Comment by MSpenger** [comment]
@adambuttrick: Thanks for adding the changes below. Unfortunately one relation too much was deleted for each entry. 

https://ror.org/02jet3w32 was listed as both "Child Organization" and "Related Organization". Only the "Related Organization" needed to be delted. Is it possible to add https://ror.org/02jet3w32 again as a child to https://ror.org/05591te55 (preferably as the first entry under "Child Organizations".

The same goes for  https://ror.org/045495t75 which was under both relation categories. It only needed to be deleted under "Child Organization/Parent Organization". So if possible, this should be relisted as a "Related Organization" for https://ror.org/05591te55 

Many thanks in advance and sorry for the inconvenience. But after those two changes, all relations are correct.

> @adambuttrick: Thanks for the updates regarding https://ror.org/05591te55
> 
> just a small addition:
> 
> * the relationship "Child Organization/Parent Organization" needs to be deleted for https://ror.org/045495t75
> * the relationship "Related Organization" needs to be deleted for https://ror.org/02jet3w32
> 
> Many thanks in advance.

**Comment by adambuttrick** [comment]
@MSpenger Thanks for flagging this. I've corrected with https://github.com/ror-community/ror-updates/issues/14118. If you could please review and verify that this is correct, it would be much appreciated.
