### ISSUE TITLE
Add a new organization to ROR: University Business Academy in Novi Sad

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12764]
Summary of request: Add a new organization to ROR

Name of organization: Univerzitet Privredna akademija u Novom Sadu*sh
Website: https://www.privrednaakademija.edu.rs
Domains: privrednaakademija.edu.rs
Link to publications: https://doi.org/10.7595/management.fon.2022.0009 https://doi.org/10.1108/JPMD-04-2020-0033 https://doi.org/10.3390/su12218911
Organization type: Education
Organization status: Active
Wikipedia page: https://sr.wikipedia.org/wiki/%D0%A3%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D0%B7%D0%B8%D1%82%D0%B5%D1%82_%D0%9F%D1%80%D0%B8%D0%B2%D1%80%D0%B5%D0%B4%D0%BD%D0%B0_%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%98%D0%B0
Wikidata ID: Q118185578
ISNI ID: 0000 0004 4660 7609 
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: University of Economics Academy Novi Sad*en
Labels: University Business Academy in Novi Sad*en; Sveučilište Privredna akademija*hr; Универзитет Привредна академија*sr
Acronym/abbreviation:
Related organizations: 
City: Novi Sad
Country: Serbia
Geonames ID: 3194360
Year established: 2000
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Serbia. Funds and employs researchers. Solid affiliation usage. Should be added.
