### ISSUE TITLE
Add a new organization to ROR: Lusail University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12774]
Summary of request: Add a new organization to ROR

Name of organization: Lusail University*en
Website: https://www.lu.edu.qa
Domains: lu.edu.qa
Link to publications: https://doi.org/10.17507/jltr.1206.10 https://doi.org/10.3390/fractalfract6120724 https://doi.org/10.1109/ICFDA58234.2023.10153324
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Lusail_University
Wikidata ID: Q108293481
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: جَامِعَة لُوسَيْل*ar
Acronym/abbreviation: LU*en
Related organizations: 
City: Lusail
Country: Qatar
Geonames ID: 289910
Year established: 2020
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Qatar. Funds and employs researchers. Solid affiliation usage. Should be added.
