### ISSUE TITLE
Modify the information in an existing ROR record: Dietrich Bonhoeffer Klinikum - https://ror.org/04qa46285

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#12775]
Summary of request: Modify the information in an existing ROR record

Name of organization: Dietrich Bonhoeffer Klinikum
ROR ID: https://ror.org/04qa46285
Which part of the record needs to be changed? Website, relationships
Description of change: Replace website with https://dbknb.de. Add domain dbknb.de. 

Update: website.replace==https://dbknb.de | domains.add==dbknb.de$

Related organizatons: https://ror.org/00r1edq15 (delete) https://ror.org/025vngs54 (related)

**Comment by MSpenger** [comment]
@adambuttrick: Regarding this entry, I was contacted by a colleague from Universität Greifswald. For this entry https://ror.org/025vngs54 the relation to https://ror.org/04qa46285 needs to be deleted. The main website (https://dbknb.de/) does not list the relation and the connection is not in accordance with the final takeaways from this blog entry: https://ror.org/blog/2023-02-27-parents-children-and-other-relationships-in-ror/  "ROR’s support for relationships and hierarchies is specifically informed by our core use case of connecting research organizations to research outputs"

Feel free to contact me, if there are any further questions regarding this.

**Comment by adambuttrick** [comment]
@MSpenger Thanks for flagging. I've addressed with the issue tagged here.
