### ISSUE TITLE
Add a new organization to ROR: Australian Antarctic Program Partnership

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#12785]
Summary of request: Add a new organization to ROR

Name of organization: Australian Antarctic Program Partnership
Website: https://aappartnership.org.au
Domains: aappartnership.org.au
Link to publications: 
Organization type: Other
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: 
Labels: 
Acronym/abbreviation: 
Related organizations: https://ror.org/01nfmeh72 (parent)
City:  Hobart
Country: Australia
Geonames ID: 2163355
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: Dryad request

**Comment by adambuttrick** [comment]
Affiliation usage for this looks fine, but its status as an organization is somewhat nebulous. Appears to be more of a multiparent initiative of universities and government organizations in Australia.

**Comment by mpfl** [comment]
@adambuttrick you've hit the nail on the head - a pretty typical partnership between Australian organisations - a "virtual" organisation that has its own branding and leadership, but doesn't _legally_ exist. Its staff are actually employed by the parent organisations.

**Comment by adambuttrick** [comment]
Declining per above review.
