### ISSUE TITLE
Solicito la actualización ROR de la Universidad  San Francisco de Asís  a Universidad Privada San Francisco de Así 

### ISSUE THREAD

**Issue by Universidad-Usfa** [ror-community/ror-updates#12802]
Buenas tades 
Solicito, por favor, la actualización en el ROR de la universidad donde soy actualmente el Director del instituto de Investigación e Interacción Social 

- Nombre ROR actual: Universidad San Francisco de Asís 
- Nombre ROR Actualizado: Universidad Privada San Francisco de Asís 

gracias

**Comment by adambuttrick** [comment]
Duplicate of https://github.com/ror-community/ror-updates/issues/12801.
