### ISSUE TITLE
Modify the information in an existing ROR record: Shota Rustaveli National Science Foundation - https://ror.org/00xc87681

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12812]
Summary of request: Modify the information in an existing ROR record

Name of organization: Shota Rustaveli National Science Foundation
ROR ID: https://ror.org/00xc87681
Which part of the record needs to be changed? Wikidata, ISNI
Description of change: ISNI: 0000 0004 4907 8888
Wikidata: Q16377946
Wikipedia: https://ka.wikipedia.org/wiki/%E1%83%A8%E1%83%9D%E1%83%97%E1%83%90_%E1%83%A0%E1%83%A3%E1%83%A1%E1%83%97%E1%83%90%E1%83%95%E1%83%94%E1%83%9A%E1%83%98%E1%83%A1_%E1%83%A1%E1%83%90%E1%83%A5%E1%83%90%E1%83%A0%E1%83%97%E1%83%95%E1%83%94%E1%83%9A%E1%83%9D%E1%83%A1_%E1%83%94%E1%83%A0%E1%83%9D%E1%83%95%E1%83%9C%E1%83%A3%E1%83%9A%E1%83%98_%E1%83%A1%E1%83%90%E1%83%9B%E1%83%94%E1%83%AA%E1%83%9C%E1%83%98%E1%83%94%E1%83%A0%E1%83%9D_%E1%83%A4%E1%83%9D%E1%83%9C%E1%83%93%E1%83%98

Update: isni.all.add==0000 0004 4907 8888 | isni.preferred.replace==0000 0004 4907 8888 | wikidata.all.add==Q16377946 | wikidata.preferred.replace==Q16377946 | website.replace==https://www.rustaveli.org.ge | domains.add==rustaveli.org.ge | wikipedia.replace==https://ka.wikipedia.org/wiki/%E1%83%A8%E1%83%9D%E1%83%97%E1%83%90_%E1%83%A0%E1%83%A3%E1%83%A1%E1%83%97%E1%83%90%E1%83%95%E1%83%94%E1%83%9A%E1%83%98%E1%83%A1_%E1%83%A1%E1%83%90%E1%83%A5%E1%83%90%E1%83%A0%E1%83%97%E1%83%95%E1%83%94%E1%83%9A%E1%83%9D%E1%83%A1_%E1%83%94%E1%83%A0%E1%83%9D%E1%83%95%E1%83%9C%E1%83%A3%E1%83%9A%E1%83%98_%E1%83%A1%E1%83%90%E1%83%9B%E1%83%94%E1%83%AA%E1%83%9C%E1%83%98%E1%83%94%E1%83%A0%E1%83%9D_%E1%83%A4%E1%83%9D%E1%83%9C%E1%83%93%E1%83%98$

**Comment by adambuttrick** [comment]
Confirmed IDs and Wikipedia entry.
