### ISSUE TITLE
Modify the information in an existing ROR record:  Aktobe Regional State University named after K.Zhubanov - https://ror.org/01mgaqp12

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12811]
Summary of request: Modify the information in an existing ROR record

Name of organization: Aktobe Regional State University named after K.Zhubanov
ROR ID: https://ror.org/01mgaqp12
Which part of the record needs to be changed? Name, website
Description of change: Add alt name Zhubanov University*en (as is used e.g. [here](https://doi.org/10.3847/1538-4357/ad3e7b))
Update website to http://zhubanov.edu.kz

Update: alias.add==Zhubanov University*en | website.replace==http://zhubanov.edu.kz | domains.add==zhubanov.edu.kz$

**Comment by adambuttrick** [comment]
Confirmed alias and link.
