### ISSUE TITLE
Modify the information in an existing ROR record: Volga Region State University of Service - https://ror.org/041g3z125

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12874]
Summary of request: Modify the information in an existing ROR record

Name of organization: Volga Region State University of Service
ROR ID: https://ror.org/041g3z125
Which part of the record needs to be changed? +Wikidata
Description of change: Q4366451

Update: wikidata.all.add==Q4366451 | wikidata.preferred.replace==Q4366451$

**Comment by adambuttrick** [comment]
Confirmed Wikidata ID.
