### ISSUE TITLE
Modify the information in an existing ROR record: Modern Business School - https://ror.org/05he7vj96

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12871]
Summary of request: Modify the information in an existing ROR record

Name of organization: Modern Business School
ROR ID: https://ror.org/05he7vj96
Which part of the record needs to be changed? +Wikidata
Description of change: Q126839542

Update: wikidata.all.add==Q126839542 | wikidata.preferred.replace==Q126839542$

**Comment by adambuttrick** [comment]
Confirmed Wikidata ID.
