### ISSUE TITLE
Modify the information in an existing ROR record: Kotebe Metropolitan University - https://ror.org/01n8adr31

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12870]
Summary of request: Modify the information in an existing ROR record

Name of organization: Kotebe Metropolitan University
ROR ID: https://ror.org/01n8adr31
Which part of the record needs to be changed? Name, +Wikidata, URL
Description of change: +Q50039998
Name changed to Kotebe University of Education*en
URL updated to https://www.kue.edu.et/

Update: ror_display.replace==Kotebe University of Education*en | label.replace==Kotebe University of Education*en | alias.add==Kotebe Metropolitan University*en | website.replace==https://www.kue.edu.et | domains.replace==kue.edu.et | wikidata.preferred.replace==Q50039998 | wikidata.all.add==Q50039998$

**Comment by adambuttrick** [comment]
Confirmed name and site change.
