### ISSUE TITLE
Modify the information in an existing ROR record: University College of Allameh Helli - https://ror.org/0015z8z93

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12895]
Summary of request: Modify the information in an existing ROR record

Name of organization: University College of Allameh Helli
ROR ID: https://ror.org/0015z8z93
Which part of the record needs to be changed? URL, Wikidata
Description of change: URL: http://www.ahelli-cha-ihe.ac.ir/
Wikidata: Q30263972

Update: website.replace==http://www.ahelli-cha-ihe.ac.ir | domains.replace==ahelli-cha-ihe.ac.ir | wikidata.all.add==Q30263972 | wikidata.preferred.replace==Q30263972$

**Comment by adambuttrick** [comment]
Confirmed updates.
