### ISSUE TITLE
Modify the information in an existing ROR record: University of Business and Entrepreneurship in Ostrowiec Świętokrzyski - https://ror.org/03dfz9238

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12914]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Business and Entrepreneurship in Ostrowiec Świętokrzyski
ROR ID: https://ror.org/03dfz9238
Which part of the record needs to be changed? Names, URL
Description of change: Per organization's [Facebook page](https://www.facebook.com/ansgoluchowski/?locale=sw_KE), "Decyzją MEiN Wyższa Szkoła Biznesu i Przedsiębiorczości w Ostrowcu Świętokrzyskim nadano status Akademii Nauk Stosowanych im. Józefa Gołuchowskiego" = "By the decision of MEiN, the University of Business and Entrepreneurship in Ostrowiec Świętokrzyski was granted the status of the Academy of Applied Sciences. Józef Gołuchowski."
Update main name to either Jozef Goluchowski University of Applied Sciences*en or Akademia Nauk Stosowanych im. Józefa Gołuchowskiego*pl with the other as an alias
Add acronym ANSG*pl
Update URL: https://goluchowski.edu.pl/

Update: ror_display.replace==Akademii Nauk Stosowanych im. Józefa Gołuchowskiego*pl  | label.replace==Akademii Nauk Stosowanych im. Józefa Gołuchowskiego*pl  | alias.add==ANSG w Ostrowcu Świętokrzyskim*pl; Jozef Goluchowski University of Applied Sciences*en; University of Business and Entrepreneurship in Ostrowiec Świętokrzyski*en | acronym.add==ANSG*pl | website.replace==https://goluchowski.edu.pl | domains.add==goluchowski.edu.pl$

**Comment by adambuttrick** [comment]
Confirmed name change via the organization's site.
