### ISSUE TITLE
Modify the information in an existing ROR record: State Education Development Agency - https://ror.org/055t1w920

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12913]
Summary of request: Modify the information in an existing ROR record

Name of organization: State Education Development Agency
ROR ID: https://ror.org/055t1w920
Which part of the record needs to be changed? Wikidata
Description of change: Q30260918

Update: wikidata.all.add==Q30260918 | wikidata.preferred.replace==Q30260918 | labels.replace==State Education Development Agency*en; Valsts izglītības attīstības aģentūra*lv | website.replace==https://www.viaa.gov.lv | domains.add==viaa.gov.lv$

**Comment by adambuttrick** [comment]
Confirmed Wikidata ID.
