### ISSUE TITLE
Modify the information in an existing ROR record: Rural Education and Development - https://ror.org/02arxvh93

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12912]
Summary of request: Modify the information in an existing ROR record

Name of organization: Rural Education and Development
ROR ID: https://ror.org/02arxvh93
Which part of the record needs to be changed? Wikidata, name
Description of change: Seems like the Primary name should be READ Global per [website](https://www.readglobal.org/)
+Q17086739

Update: ror_display.replace==READ Global*en | label.replace==READ Global*en | alias.add==Rural Education and Development (READ) Global*en; Rural Education and Development Global*en | wikidata.all.add==Q17086739 | wikidata.preferred.replace==Q17086739$

**Comment by adambuttrick** [comment]
Confirmed name change.
