### ISSUE TITLE
Modify the information in an existing ROR record: Brooklyn Historical Society - https://ror.org/03xvvtc63

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12953]
Summary of request: Modify the information in an existing ROR record

Name of organization: Brooklyn Historical Society
ROR ID: https://ror.org/03xvvtc63
Which part of the record needs to be changed? Name, relationships, URL, Wikidata, Wikipedia
Description of change: [Folded](https://www.bklynlibrary.org/center-for-brooklyn-history) under the Brooklyn Public Library in 2020. 
Update name to Center for Brooklyn History*en, add acronym CBH*en; maintain BHS/Brooklyn Historical Society as alt names.
Add relationship https://ror.org/051kejp81 (parent)
Update URL: https://www.bklynlibrary.org/center-for-brooklyn-history
Add Wikidata: Q4974851
Update Wikipedia: https://en.wikipedia.org/wiki/Center_for_Brooklyn_History

Update: ror_display.replace==Center for Brooklyn History*en | label.replace==Center for Brooklyn History*en |  alias.add==Brooklyn Historical Society*en | acronym.add==CBH*en | website.replace==https://www.bklynlibrary.org/center-for-brooklyn-history | wikidata.all.add==Q4974851 | wikidata.preferred.replace==Q4974851 | wikipedia.replace==https://en.wikipedia.org/wiki/Center_for_Brooklyn_History |

**Comment by adambuttrick** [comment]
Confirmed updates.
