### ISSUE TITLE
Modify the information in an existing ROR record: Centre scientifique et technique du bâtiment

### ISSUE THREAD

**Issue by kongfundamentals** [ror-community/ror-updates#12958]
Summary of request: Modify the information in an existing ROR record

Name of organization: Centre scientifique et technique du bâtiment
ROR ID: https://ror.org/02fsd1928
Which part of the record needs to be changed?
Description of change: Some letters need to be capitalized: should be [Centre Scientifique et Technique du Bâtiment]

Thank you!

Update: ror_display.replace==Centre Scientifique et Technique du Bâtiment*fr | label.replace==Centre Scientifique et Technique du Bâtiment*fr; Scientific and Technical Center for Building*en | website.replace==https://www.cstb.fr | domains.add==cstb.fr$

**Comment by adambuttrick** [comment]
Confirmed name change via the organization's site.
