### ISSUE TITLE
Modify the information in an existing ROR record: Bridging Access to Care - https://ror.org/057fagq12

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12954]
Summary of request: Modify the information in an existing ROR record

Name of organization: Bridging Access to Care
ROR ID: https://ror.org/057fagq12
Which part of the record needs to be changed? Wikidata 
Description of change: +Q30255287

Update: wikidata.all.add==Q30255287 | wikidata.preferred.replace==Q30255287$

**Comment by adambuttrick** [comment]
Confirmed Wikidata ID.
