### ISSUE TITLE
Modify the information in an existing ROR record: Brooklyn ImmunoTherapeutics (United States) - https://ror.org/01gg39979

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12955]
Summary of request: Modify the information in an existing ROR record

Name of organization: Brooklyn ImmunoTherapeutics (United States)
ROR ID: https://ror.org/01gg39979
Which part of the record needs to be changed? Name, URL, Wikidata
Description of change: Name [updated](https://www.globenewswire.com/news-release/2022/10/11/2531832/0/en/Brooklyn-ImmunoTherapeutics-Announces-Name-Change-to-Eterna-Therapeutics-and-Provides-Corporate-Updates.html) 2022.
Update name to Eterna Therapeutics*en
Update URL: https://www.eternatx.com/
Add Wikidata: Q104480793

Update: ror_display.replace==Eterna Therapeutics (United States)*en | label.replace==Eterna Therapeutics*en | alias.add==Brooklyn ImmunoTherapeutics*en | website.replace==https://www.eternatx.com | domains.add==eternatx.com | wikidata.all.add==Q104480793 | wikidata.preferred.replace==Q104480793$

**Comment by adambuttrick** [comment]
Confirmed name change.
