### ISSUE TITLE
Add a new organization to ROR: Business Finland

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1297]
Summary of request: Add a new organization to ROR

Name of organization: Business Finland
Website: https://www.businessfinland.fi
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Business_Finland
Wikidata ID: Q42056829
ISNI ID:
GRID ID:
Crossref Funder ID: 501100014438
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City: Helsinki
Country: Finland
Geonames ID: 658225
Year established: 1983
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Successor organization to https://ror.org/02ag8cq23, established in 2018 through it and the merger of Finpro. Top-level government entity with solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1111/jcc4.12063; https://doi.org/10.1016/j.chb.2015.01.053; https://doi.org/10.1002/hrm.21525; https://doi.org/10.1016/j.jbankfin.2014.05.007; https://doi.org/10.1016/0160-7383(86)90055-1; https://doi.org/10.1016/j.ibusrev.2013.02.006; https://doi.org/10.1016/j.ejor.2013.02.001; https://doi.org/10.1177/0018726713491772; https://doi.org/10.1080/0267257x.2013.813577

ORCID affiliation usage: https://orcid.org/0000-0002-2000-6552 ; https://orcid.org/0000-0003-3230-7958

**Comment by mariagould** [comment]
I'm not seeing affiliation usage in the links above (it looks like the triage tool might have pulled erroneous results?) but I think this would be in scope as the successor to Tekes and given its role as a supporter/funder of research.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05bgf9v38 in release v1.12.
