### ISSUE TITLE
Modify the information in an existing ROR record: Brooklyn Navy Yard - https://ror.org/01vhsdf43

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12988]
Summary of request: Modify the information in an existing ROR record

Name of organization: Brooklyn Navy Yard
ROR ID: https://ror.org/01vhsdf43
Which part of the record needs to be changed? +Wikidata
Description of change: Q524435

Update: wikidata.all.add==Q524435 | wikidata.preferred.replace==Q524435$

**Comment by adambuttrick** [comment]
Confirmed Wikidata ID.
