### ISSUE TITLE
Modify the information in an existing ROR record: Brooklyn Children's Museum - https://ror.org/016bk3j80

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#12987]
Summary of request: Modify the information in an existing ROR record

Name of organization: Brooklyn Children's Museum
ROR ID: https://ror.org/016bk3j80
Which part of the record needs to be changed? Wikidata, acronym
Description of change: Q4974780
Add BCM*en

Update: wikidata.all.add==Q4974780 | wikidata.preferred.replace==Q4974780 | acronym.add==BCM*en$

**Comment by adambuttrick** [comment]
Confirmed updates
