### ISSUE TITLE
Modify the information in an existing ROR record: 
 University  of Paderborn  (https://ror.org/058kzsd48)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#130]
Summary of request: Modify the information in an existing ROR record

Name of organization:  University  of Paderborn 
ROR ID: https://ror.org/058kzsd48
Which part of the record needs to be changed? Primary name
Description of change: Please change the primary name from University of Paderborn to Paderborn University. According to the new Guidelines on stating affiliations in scientific publications at the Paderborn University (dated: 16.April 2021) the official form of the name is Universität Paderborn and Paderborn University. Please have a look to: https://doi.org/10.17619/UNIPB/1-1123

Update: change.name==Paderborn University;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
