### ISSUE TITLE
Add a new organization to ROR: Microsoft Research New York City (United States)

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13003]
Summary of request: Add a new organization to ROR

Name of organization: Microsoft Research New York City (United States)*en
Website: https://www.microsoft.com/en-us/research/lab/microsoft-research-new-york/
Domains:
Link to publications: https://doi.org/10.1145/3366424.3383417 https://doi.org/10.3758/s13428-021-01694-3 https://doi.org/10.1016/j.jtho.2019.08.583
Organization type: Company
Organization status: Active
Wikipedia page:
Wikidata ID: 
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Microsoft Research New York*en
Labels: Microsoft Research New York City*en
Acronym/abbreviation: MSR-NYC*en
Related organizations: https://ror.org/00d0nc645 (parent)
City: New York City
Country: United States
Geonames ID: 5128581
Year established: 2012
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research lab in the US. Funds and employs researchers. Solid affiliation usage. Should be added.
