### ISSUE TITLE
Add a new organization to ROR: Rai University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13002]
Summary of request: Add a new organization to ROR

Name of organization: Rai University*en
Website: https://www.raiuniversity.edu
Domains: raiuniversity.edu
Link to publications: https://doi.org/10.1149/10701.2191ecst https://doi.org/10.1016/j.protcy.2016.03.046 https://doi.org/10.1063/5.0168196
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Rai_University
Wikidata ID: Q7283682
ISNI ID: 0000 0004 0499 5674
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: RU*en
Related organizations: 
City: Ahmedabad
Country: India
Geonames ID: 1279233
Year established: 2012
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in India. Funds and employs researchers. Solid affiliation usage. Should be added.
