### ISSUE TITLE
Modify the information in an existing ROR record: Koje College - https://ror.org/044xay220

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13014]
Summary of request: Modify the information in an existing ROR record

Name of organization: Koje College
ROR ID: https://ror.org/044xay220
Which part of the record needs to be changed? Name, URL, Wikidata, Wikipedia
Description of change: Geoje University*en appears to be the preferred name per [their site](https://www.koje.ac.kr/www); swap it and Koje College*en
Update URL to https://www.koje.ac.kr/
Add Wikidata: Q12583329
Add Wikipedia: https://ko.wikipedia.org/wiki/%EA%B1%B0%EC%A0%9C%EB%8C%80%ED%95%99%EA%B5%90

pdate: ror_display.replace==Geoje University*en | label.replace==Geoje University*en; 거제대학교*ko | alias.add==Koje College; 거제대학*ko | website.replace==https://www.koje.ac.kr | wikidata.preferred.replace==Q12583329 | wikidata.all.add==Q12583329 | wikipedia.replace==https://ko.wikipedia.org/wiki/%EA%B1%B0%EC%A0%9C%EB%8C%80%ED%95%99%EA%B5%90$

**Comment by adambuttrick** [comment]
Confirmed name change.
