### ISSUE TITLE
Add a new organization to ROR: Collegium Intermarium

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13027]
Summary of request: Add a new organization to ROR

Name of organization: Collegium Intermarium*la
Website: https://collegiumintermarium.org
Domains: collegiumintermarium.org
Link to publications: https://doi.org/10.37873/legal.2022.5.90 https://doi.org/10.15633/lie.61105 https://doi.org/10.5604/01.3001.0053.8990
Organization type: Education
Organization status: Active
Wikipedia page: https://pl.wikipedia.org/wiki/Uczelnia_Collegium_Intermarium
Wikidata ID: Q107202968
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: Uczelnia Collegium Intermarium*pl
Acronym/abbreviation:
Related organizations: 
City: Warsaw
Country: Poland
Geonames ID: 756135
Year established: 2021
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Higher educational institution in Poland. Funds and employs researchers. Solid affiliation usage. Should be added.
