### ISSUE TITLE
Add a new organization to ROR:Universitas Nahdlatul Ulama Purwokerto, Indonesia

### ISSUE THREAD

**Issue by asepbudiman-design** [ror-community/ror-updates#13037]
Summary of request: Add a new organization to ROR

Name of organization:
Website: 
Domains:
Link to publications: 
Organization type: 
Organization status:
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation:
Related organizations: 
City: 
Country:
Geonames ID: 
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Merging into https://github.com/ror-community/ror-updates/issues/13039.
