### ISSUE TITLE
Add a new organization to ROR: Universitas Nahdlatul Ulama Purwokerto, Indonesia

### ISSUE THREAD

**Issue by asepbudiman-design** [ror-community/ror-updates#13039]
Summary of request: Add a new organization to ROR

Name of organization: Universitas Nahdlatul Ulama Purwokerto*id
Website: https://unupurwokerto.ac.id
Domains: unupurwokerto.ac.id
Link to publications: 
Organization type: Education
Organization status: Education
Wikipedia page: https://id.wikipedia.org/wiki/Universitas_Nahdlatul_Ulama_Purwokerto
Wikidata ID: Q85995029
ISNI ID:
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: UNU Purwokerto*id; University of Nahdlatul Ulama Purwokerto*en
Labels: 
Acronym/abbreviation: 
Related organizations: 
City: Purwokerto
Country: Indonesia
Geonames ID: 1630328
Year established: 2013
How will a ROR ID for this organization be used? to enrich the metadata of the published paper
Other information about this request:

**Comment by adambuttrick** [comment]
University in Indonesia. Funds and employs researchers. Solid affiliation usage. Should be added.
