### ISSUE TITLE
Modify the information in an existing ROR record: Nobel International Business School - https://ror.org/00dv28z40

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13049]
Summary of request: Modify the information in an existing ROR record

Name of organization: Nobel International Business School
ROR ID: https://ror.org/00dv28z40
Which part of the record needs to be changed? +Wikidata
Description of change: Q125761957

Update: wikidata.all.add==Q125761957 | wikidata.preferred.replace==Q125761957$

**Comment by adambuttrick** [comment]
Confirmed update
