### ISSUE TITLE
Add a new organization to ROR: Florida Global University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13044]
Summary of request: Add a new organization to ROR

Name of organization: Florida Global University*en
Website: https://floridaglobal.university
Domains: floridaglobal.university
Link to publications: https://doi.org/10.54517/st.v2i2.1704 https://doi.org/10.31207/rch.v13i2.354 https://doi.org/10.21500/23825014.4955
Organization type: Education
Organization status: Active
Wikipedia page: 
Wikidata ID: Q128123383
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: Universidad Global de Florida*es
Acronym/abbreviation: FGU*en
Related organizations: 
City: Doral
Country: United States
Geonames ID: 4153471
Year established: 2004
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Florida. Funds and employs researchers. Solid affiliation usage. Should be added.
