### ISSUE TITLE
Modify the information in an existing ROR record: Hennepin Healthcare Research Institute - https://ror.org/05v1amx46

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13050]
Summary of request: Modify the information in an existing ROR record

Name of organization: Hennepin Healthcare Research Institute
ROR ID: https://ror.org/05v1amx46
Which part of the record needs to be changed? +Wikidata
Description of change: Q108737452

Update: wikidata.all.add==Q108737452 | wikidata.preferred.replace==Q108737452$

**Comment by adambuttrick** [comment]
Confirmed update. @cknopp-schwyn Just an FYI, in the next month or so we will be doing a dataset-wide update to reconcile Wikidata IDs for ROR, so you shouldn't need to submit these as one-offs for anything aside from new records, subsequent to that.
