### ISSUE TITLE
Add a new organization to ROR: Delhi Skill and Entrepreneurship University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13208]
Summary of request: Add a new organization to ROR

Name of organization: Delhi Skill and Entrepreneurship University*en
Website: https://dseu.ac.in
Domains: dseu.ac.in
Link to publications: https://doi.org/10.37383/SBJ200102 https://doi.org/10.1155/2022/4457973 https://doi.org/10.1002/widm.1509
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Delhi_Skill_and_Entrepreneurship_University
Wikidata ID: Q108673567
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: DSEU*en
Related organizations: 
City: New Delhi
Country: India
Geonames ID: 1261481 
Year established: 2020
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in India. Funds and employs researchers. Solid affiliation usage. Should be added.
