### ISSUE TITLE
Add a new organization to ROR: MIT Art, Design and Technology University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13222]
Summary of request: Add a new organization to ROR

Name of organization: MIT Art, Design and Technology University*en
Website: https://mituniversity.ac.in
Domains: mituniversity.ac.in
Link to publications: https://doi.org/10.34218/IJM.11.12.2020.197 https://doi.org/10.1007/978-981-19-7481-6_8 https://doi.org/10.1111/jfpe.13270
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/MIT_Art,_Design_and_Technology_University
Wikidata ID: Q116960702
ISNI ID: 0000 0004 8339 4120
GRID ID:
Crossref Funder ID:
Other names for the organization: MIT Institute of Design*en; MIT ADT University*en
Aliases: एमआयटी_कला,_डिझाईन_आणि_तंत्रज्ञान_विद्यापीठ*mr 
Labels: 
Acronym/abbreviation: MIT-ADT*en
Related organizations: 
City: Pune
Country: India
Geonames ID: 1259229
Year established: 2015
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Private university in INdia. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by adambuttrick** [comment]
Already exists in ROR - https://ror.org/05b69xa56.
