### ISSUE TITLE
Add a new organization to ROR: Ramon Magsaysay Memorial Colleges

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13369]
Summary of request: Add a new organization to ROR

Name of organization: Ramon Magsaysay Memorial Colleges*en
Website: https://rmmc.edu.ph
Domains: rmmc.edu.ph
Link to publications: https://doi.org/10.51629/ijeamal.v2i2.25 https://doi.org/10.5281/zenodo.7083128 http://dx.doi.org/10.46827/ejes.v11i8.5437
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Ramon_Magsaysay_Memorial_Colleges
Wikidata ID: Q7289847
ISNI ID: 0000 0004 0474 5472
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: RMMC*en
Related organizations: 
City: General Santos
Country: Philippines
Geonames ID: 1713022
Year established: 1957
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Private college in the Philippines. Funds and employs researchers. Solid affiliation usage. Should be added.
