### ISSUE TITLE
Add a new organization to ROR: Los Altos History Museum

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13387]
Summary of request: Add a new organization to ROR

Name of organization: Los Altos History Museum*en
Website: https://www.losaltoshistory.org
Domains: losaltoshistory.org
Link to publications: https://doi.org/10.1179/msi.2007.2.2.243 https://www.proquest.com/docview/2307391294?pq-origsite=gscholar&fromopenview=true&sourcetype=Scholarly%20Journals https://doi.org/10.1353/soh.2021.0129
Organization type: Archive
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Los_Altos_History_Museum
Wikidata ID: Q6681898
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: LAHM*en
Related organizations: 
City: Los Altos
Country: United States
Geonames ID: 5368335
Year established: 2001
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Museum in the US. Funds and employs researchers. Solid affiliation usage. Should be added.
