### ISSUE TITLE
Modify the information in an existing ROR record: Brooklyn Historical Society - https://ror.org/03xvvtc63

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13394]
Summary of request: Modify the information in an existing ROR record

Name of organization: Brooklyn Historical Society
ROR ID: https://ror.org/03xvvtc63
Which part of the record needs to be changed? Name, URL, Wikidata
Description of change: Name [changed](https://www.bklynlibrary.org/center-for-brooklyn-history) in 2020 to Center for Brooklyn History*en
Add abbr. CBH*en
URL updated to https://www.bklynlibrary.org/center-for-brooklyn-history
+Wikidata Q4974851

Update: ror_display.replace==Center for Brooklyn History*en | label.replace==Center for Brooklyn History*en | alias.add==Brooklyn Historical Society*en | acronym.add==CBH*en | website.replace==https://www.bklynlibrary.org/center-for-brooklyn-history | wikidata.all.add==Q4974851 | wikidata.preferred.replace==Q4974851 | wikipedia.replace==https://en.wikipedia.org/wiki/Center_for_Brooklyn_History$

**Comment by adambuttrick** [comment]
Encoding on https://github.com/ror-community/ror-updates/issues/12953 was invalid, which prevented update in release v1.50.
