### ISSUE TITLE
Modify the information in an existing ROR record: Brooklyn Philharmonic - https://ror.org/04z73qb28

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13393]
Summary of request: Modify the information in an existing ROR record

Name of organization: Brooklyn Philharmonic
ROR ID: https://ror.org/04z73qb28
Which part of the record needs to be changed? Make inactive
Description of change: [Defunct](https://en.wikipedia.org/wiki/Brooklyn_Philharmonic) as of 2012. Thanks!

Update: status.replace==inactive$

**Comment by adambuttrick** [comment]
Errant encoding (failure to tag status change) on https://github.com/ror-community/ror-updates/issues/12986
