### ISSUE TITLE
Add a new organization to ROR: Lakeside University College Ghana

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13401]
Summary of request: Add a new organization to ROR

Name of organization: Lakeside University College Ghana*en
Website: https://lucg.edu.gh
Domains: lucg.edu.gh
Link to publications: https://doi.org/10.1108/JHTT-04-2020-0074 https://doi.org/10.1080/23311975.2024.2307640 https://doi.org/10.1080/23311983.2023.2286736
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Lakeside_University_College
Wikidata ID: Q55648280
ISNI ID: 0000 0004 7417 3879
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Lakeside University College*en; Madina Institute of Science and Technology*en; LUC Ghana*en
Labels: 
Acronym/abbreviation: LUCG*en; MIST*en
Related organizations: https://ror.org/00cb23x68 (related); https://ror.org/052nhnq73 (related)
City: Accra
Country: Ghana
Geonames ID: 2306104
Year established: 2013
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Ghana. Funds and employs researchers. Solid affiliation usage. Should be added.
