### ISSUE TITLE
Modify the information in an existing ROR record: Université de Parakou

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13400]
Summary of request: Modify the information in an existing ROR record

Name of organization: Université de Parakou
ROR ID: https://ror.org/025wndx93
Which part of the record needs to be changed? Add label
Description of change: Add English label: University of Parakou*en (used [here](https://doi.org/10.1016/j.jeph.2024.202525) for example)

Update: label.add==University of Parakou*en$

**Comment by adambuttrick** [comment]
Confirmed use by the organization.
