### ISSUE TITLE
Add a new organization to ROR:  University of the South Pacific - Emalus Campus

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13429]
Summary of request: Add a new organization to ROR

Name of organization: University of the South Pacific - Emalus Campus*en
Website: https://www.usp.ac.fj/emalus
Domains:
Link to publications: https://doi.org/10.1080/14760400508522899 https://doi.org/10.1080/14781158.2011.540097 https://doi.org/10.1108/GKMC-05-2018-0049
Organization type: Education
Organization status: Active
Wikipedia page:
Wikidata ID: Q99286041
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: USP Emalus Campus*en; University of the South Pacific Vanuatu*en
Labels:
Acronym/abbreviation:
Related organizations: https://ror.org/008stv805 (parent)
City: Port Vila
Country: Vanuatu
Geonames ID: 2135171
Year established: 1968
How will a ROR ID for this organization be used? 
Other information about this request: Relates to #12584

**Comment by rileymmarsh** [comment]
South Pacific university campus, other affiliated campuses already in ROR. Funds and employs researchers. Solid affiliation usage. Should be added.
