### ISSUE TITLE
Add a new organization to ROR: BioIVT (United States)

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#13445]
Summary of request: Add a new organization to ROR

Name of organization: BioIVT (United States)
Website: https://bioivt.com
Domains: bioivt.com
Link to publications: 
Organization type: Company
Wikipedia page: 
Wikidata ID: Q124545356
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: BioreclamationIVT
Labels: BioIVT
Acronym/abbreviation: 
Related organizations: https://ror.org/04hjzsd20 (child)
City: Westbury
Country: United States
Geonames ID: 5144040
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Adding parent for [XenoTech](https://ror.org/04hjzsd20). Research company with solid affiliation usage. Funds and employs researchers. Should be added.
