### ISSUE TITLE
Add a new organization to ROR: Telefónica Innovación Digital

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#13446]
Summary of request: Add a new organization to ROR

Name of organization: Telefónica Innovación Digital (Spain)*es
Website: https://telefonicainnovaciondigital.com
Domains: telefonicainnovaciondigital.com
Link to publications: 
Organization type: Company
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: 
Labels: Telefónica Digital Innovation*en; Telefónica Innovación Digital S.L.U.*es
Acronym/abbreviation: 
Related organizations: https://ror.org/03qgzzb04 (predecessor)
City: Madrid
Country: Spain
Geonames ID: 3117735
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: Follows from https://github.com/ror-community/ror-updates/issues/13427.

**Comment by rileymmarsh** [comment]
Company with predecessor in ROR. Funds and employs researchers. Solid affiliation usage. Should be added.
