### ISSUE TITLE
Modify the information in an existing ROR record: Impaq International (United States) https://ror.org/04kb0nk47

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#13454]
Summary of request: Modify the information in an existing ROR record

Name of organization: Impaq International (United States)
ROR ID: https://ror.org/04kb0nk47
Which part of the record needs to be changed? Relationships
Description of change: AIR (https://ror.org/00490n048) acquired IMPAQ in 2020 and therefore a relationship should be created with IMPAQ record https://ror.org/04kb0nk47, either Parent - Child or Predecessor / Successor. See press release https://www.air.org/news/press-release/american-institutes-research-completes-acquisition-impaq-llc

Update: status.replace==inactive$

Related organizations: https://ror.org/00490n048 (successor-np)

**Comment by adambuttrick** [comment]
Update would be applied to Impaq International (United States) https://ror.org/04kb0nk47, so updating request to reflect. Confirmed merger.
