### ISSUE TITLE
Add a new organization to ROR: Air Force Sustainment Center

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#13475]
Summary of request: Add a new organization to ROR

Name of organization: Air Force Sustainment Center*en
Website: https://www.afsc.af.mil
Domains: 
Link to publications: 
Organization type: Government; Facility
Wikipedia page: https://it.wikipedia.org/wiki/Air_Force_Sustainment_Center
Wikidata ID: Q56322523
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: US Air Force Sustainment Center*en; United States Air Force Sustainment Center*en
Labels: 
Acronym/abbreviation: AFSC*en
Related organizations: https://ror.org/02m4c1x70 (parent)
City: Tinker Air Force Base
Country: USA
Geonames ID: 4553114
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: DTIC request

**Comment by rileymmarsh** [comment]
US military research center. Funds and employs researchers. Solid affiliation usage. Should be added.
