### ISSUE TITLE
Add a new organization to ROR: IMRA (United States)

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#13477]
Summary of request: Add a new organization to ROR

Name of organization: IMRA America (United States)
Website: https://www.imra.com
Domains: imra.com
Link to publications: 
Organization type: Company
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: Institut Minoru de Recherche Avancé America*fr
Labels: IMRA America; IMRA America, Inc.
Acronym/abbreviation: 
Related organizations: https://ror.org/00vtxwp63 (parent) https://ror.org/054d78x30 (related)
City: Ann Arbor
Country: USA
Geonames ID: 4984247
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: DTIC request.

**Comment by rileymmarsh** [comment]
Might be worth it to add Institut Minoru de Recherche Avancé*fr to related https://ror.org/054d78x30.

**Comment by rileymmarsh** [comment]
Research and engineering company with French equivalent already in ROR. Funds and employs researchers. Solid affiliation usage. Should be added.
