### ISSUE TITLE
Add a new organization to ROR: Microsoft Research Montréal (Canada)

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13499]
Summary of request: Add a new organization to ROR

Name of organization: Microsoft Research Montréal (Canada)*en
Website: https://www.microsoft.com/en-us/research/lab/microsoft-research-montreal/
Domains:
Link to publications: https://doi.org/10.1145/3544549.3583178 https://doi.org/10.1145/3531146.3533234 https://doi.org/10.1109/ICASSP40776.2020.9053599
Organization type: Company
Organization status: Active
Wikipedia page: 
Wikidata ID: 
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Microsoft Research Montreal*en; Microsoft Research Lab – Montréal*en; MSR Montréal*en
Labels:
Acronym/abbreviation:
Related organizations: https://ror.org/00d0nc645 (parent)
City: Montréal
Country: Canada
Geonames ID: 6077243
Year established: 2017
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
One of Microsoft's research labs. Funds and employs researchers. Solid affiliation usage. Should be added.
