### ISSUE TITLE
Add a new organization to ROR: Bangabandhu Sheikh Mujibur Rahman Maritime University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13498]
Summary of request: Add a new organization to ROR

Name of organization: Bangabandhu Sheikh Mujibur Rahman Maritime University*en
Website: https://www.bsmrmu.edu.bd
Domains: bsmrmu.edu.bd
Link to publications: https://doi.org/10.1007/s43545-021-00188-5 https://doi.org/10.1016/j.marpol.2020.104041 https://doi.org/10.3329/brc.v9i1.63604
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Bangabandhu_Sheikh_Mujibur_Rahman_Maritime_University
Wikidata ID: Q30591100
ISNI ID: 0000 0004 4683 9661
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: বঙ্গবন্ধু শেখ মুজিবুর রহমান মেরিটাইম বিশ্ববিদ্যালয়*bn; बंगबन्धु शेख मुजीबुर रहमान समुद्री विश्वविद्यालय*hi
Acronym/abbreviation: BSMRMU*en
Related organizations: 
City: Dhaka
Country: Bangladesh
Geonames ID: 1185241
Year established: 2013
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Bangladeshi university. Funds and employs researchers. Solid affiliation usage. Should be added.
