### ISSUE TITLE
Modify the information in an existing ROR record: National Center for Post Traumatic Stress Disorder - https://ror.org/04xv0vq46

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#13493]
Summary of request: Modify the information in an existing ROR record

Name of organization: National Center for Post Traumatic Stress Disorder
ROR ID: https://ror.org/04xv0vq46
Which part of the record needs to be changed? Site, relationships
Description of change: Replace site with https://www.ptsd.va.gov. Delete relationship to https://ror.org/030j39b93. 

Update: website.replace==https://www.ptsd.va.gov$

Related organizations: https://ror.org/02hd1sz82 (parent) https://ror.org/030j39b93 (delete)

**Comment by carlyrobinson** [comment]
- It looks like the site is correct for https://ror.org/04xv0vq46 (https://www.ptsd.va.gov/). 
- Agree that the parent relationship to https://ror.org/030j39b93 should be removed. Should also remove the child relationship from https://ror.org/030j39b93. 
- Agree with addition of https://ror.org/02hd1sz82 as parent of https://ror.org/04xv0vq46. On https://www.mirecc.va.gov/ homepage, it lists National Center for PTSD as a VA MIRECC.
