### ISSUE TITLE
Merge duplicate records for Qamcom Research & Technology (Sweden)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#135]
ROR has duplicate records for Qamcom Research & Technology (Sweden). These need to be merged.

Duplicate records:
1. https://ror.org/0162qn279
2. https://ror.org/01jkn7h76

Record 2 has less metadata so it should be redirected to Record 1.

**Comment by adambuttrick** [comment]
Part of GRID removed records and thus will address there.
