### ISSUE TITLE
Modify the information in an existing ROR record: Phonak (Switzerland) - https://ror.org/027rr8795

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#13505]
Summary of request: Modify the information in an existing ROR record

Name of organization: Phonak (Switzerland)
ROR ID: https://ror.org/027rr8795
Which part of the record needs to be changed? Name, aliases, site, domain, relationships
Description of change: Change name to Sonova (Switzerland). Add alias Phonak AG; Phonak Holding AG. Replace website with https://www.sonova.com. Add domain sonova.com. Related organizations: https://ror.org/05k0hd440 (child)

Update: ror_display.replace==Sonova (Switzerland) | label.replace==Sonova (Switzerland) | alias.add==Phonak Switzerland; Phonak AG; Phonak Holding AG*en | website.replace==https://www.sonova.com | domains.add==sonova.com$

Related organizations: https://ror.org/05k0hd440 (child)

**Comment by rileymmarsh** [comment]
According to [Sonova's website](https://www.sonova.com/en/phonak) and the [Phonak website](https://www.phonak.com/en-us/about-us), Phonak still exists as a part of Sonova. Corrected updates reflect this relationship.
