### ISSUE TITLE
Add a new organization to ROR: Centre for Reproductive & Genetic Health

### ISSUE THREAD

**Issue by RichardJActon** [ror-community/ror-updates#13515]
Summary of request: Add a new organization to ROR

Name of organization: The Centre for Reproductive & Genetic Health*en
Website: https://crgh.co.uk
Domains: crgh.co.uk
Link to publications: 10.1016/j.rbmo.2013.12.010
Organization type: Healthcare (A medical care facility such as hospital or clinic. Excludes medical schools, which should be categorized as “Education”)
Organization status:
Wikipedia page:
Wikidata ID: Q102867797
ISNI ID: 0000 0004 4666 2413
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Centre for Reproductive and Genetic Health*en
Labels:
Acronym/abbreviation: CRGH*en
Related organizations: 
City: London
Country: UK
Geonames ID: 2643743
Year established: 1990
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by rileymmarsh** [comment]
Fertility clinic in London. Funds and employs researchers. Solid affiliation usage. Should be added.
