### ISSUE TITLE
Add a new organization to ROR: Xavier Institute of Management and Entrepreneurship

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13575]
Summary of request: Add a new organization to ROR

Name of organization: Xavier Institute of Management and Entrepreneurship*en
Website: http://www.xime.org
Domains: xime.org
Link to publications: https://doi.org/10.1109/TEM.2024.3437427 http://dx.doi.org/10.5958/0974-1852.2020.00008.5 https://doi.org//10.32628/IJSRST2295191
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Xavier_Institute_of_Management_and_Entrepreneurship
Wikidata ID: Q8043260
ISNI ID: 0000 0004 1770 0521
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: XIME*en
Related organizations: 
City: Bangalore
Country: India
Geonames ID: 1277333
Year established: 1993
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Business school in Bangalore. Funds and employs researchers. Solid affiliation usage. Should be added.
