### ISSUE TITLE
Project: Updated records from NSW government orgs

### ISSUE THREAD

**Issue by rileymmarsh** [ror-community/ror-updates#13659]
Following #13513, organizations under the Government of New South Wales should have NSW added to their names as needed to prevent confusion over the NSW government and Australian government.

[Department of Communities and Justice](https://ror.org/05dmpdy49)
[Forestry Corporation](https://ror.org/029r1ks56)
[Roads and Maritime Services](https://ror.org/01j72sa23)
with special consideration to [Office for Learning and Teaching](https://ror.org/000dfsq72) under the [Department of Education](https://ror.org/05nne8c43) which links to the Australian OLT (link is also broken) and not the NWS OLT.

**Comment by adambuttrick** [comment]
All issues processed in release v1.52.
