### ISSUE TITLE
Modify the information in an existing ROR record: Office for Learning and Teaching

### ISSUE THREAD

**Issue by rileymmarsh** [ror-community/ror-updates#13665]
Summary of request: Modify the information in an existing ROR record

Name of organization: Office for Learning and Teaching
ROR ID: https://ror.org/000dfsq72
Which part of the record needs to be changed?
Description of change: [Office for Learning and Teaching](https://ror.org/000dfsq72) under the [Department of Education](https://ror.org/05nne8c43) links to the Australian OLT and not the NWS OLT. Either link to Australian Department of Education as parent or change name and link to NSW versions. Part of #13659. 

Update: website.replace==https://www.education.gov.au/learning-and-teaching$

Related organizations: https://ror.org/05nne8c43 (delete) https://ror.org/03z942k20 (parent)

**Comment by adambuttrick** [comment]
Confirmed record is federal government entity. Should create new record request for NSW office - https://education.nsw.gov.au/teaching-and-learning.
