### ISSUE TITLE
Modify the information in an existing ROR record: Instituto Colombiano del Petróleo - https://ror.org/010bvr713

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#13669]
Summary of request: Modify the information in an existing ROR record

Name of organization: Instituto Colombiano del Petróleo
ROR ID: https://ror.org/010bvr713
Which part of the record needs to be changed? Acronym, relationships
Description of change: Delete acronym ECOPETROL*es. Add parent https://ror.org/05gsrh908.

Update: ror_display.replace==Instituto Colombiano del Petróleo y Energías de la Transición - Icpet*es  | label.replace==Instituto Colombiano del Petróleo y Energías de la Transición - Icpet*es | alias.add==Instituto Colombiano del Petróleo*es; Instituto Colombiano del Petróleo y Energías de la Transición*es | acronym.replace== ICPET*es; ICP*es$

Related organizations: https://ror.org/05gsrh908 (parent)

**Comment by rileymmarsh** [comment]
Might be considered inactive or renamed: https://www.ecopetrol.com.co/wps/portal/Home/es/noticias/detalle/nuevo-icpet-impulsara-el-futuro-de-la-transicion-energetica-de-colombia
