### ISSUE TITLE
Add a new organization to ROR: Bangabandhu Sheikh Mujibur Rahman Digital University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13670]
Summary of request: Add a new organization to ROR

Name of organization: Bangabandhu Sheikh Mujibur Rahman Digital University*en
Website: https://bdu.ac.bd
Domains: bdu.ac.bd
Link to publications: https://doi.org/10.11591/eei.v13i4.6763 https://doi.org/10.1080/02680513.2022.2162870 https://doi.org/10.1109/SWC57546.2023.10448820 https://doi.org/10.3390/educsci12120857
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Bangabandhu_Sheikh_Mujibur_Rahman_Digital_University
Wikidata ID: Q60463842
ISNI ID: 0000 0004 8004 3050
GRID ID:
Crossref Funder ID:
Other names for the organization: Bangabandhu Digital University*en
Aliases:
Labels: বঙ্গবন্ধু শেখ মুজিবুর রহমান ডিজিটাল ইউনিভার্সিটি, বাংলাদেশ*bn
Acronym/abbreviation: BDU*en
Related organizations: 
City: Gazipur
Country: Bangladesh
Geonames ID: 1200109
Year established: 2018
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Digital university in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
