### ISSUE TITLE
Add a new organization to ROR: Severe Weather Institute - Radar & Lightning Laboratory

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#13679]
Summary of request: Add a new organization to ROR

Name of organization: Severe Weather Institute - Radar & Lightning Laboratory*en
Website: https://www.nsstc.uah.edu/swirll/main
Domains: 
Link to publications: https://doi.org/10.1175/MWR-D-18-0300.1 
Organization type: Facility
Organization status: Active
Wikipedia page: 
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Severe Weather Institute and Radar & Lightning Laboratories*en; Severe Weather Institute–Radar and Lightning Laboratories*en
Labels:
Acronym/abbreviation: SWIRLL*en; UAH SWIRLL*en
Related organizations: https://ror.org/02zsxwr40 (parent)
City: Huntsville 
Country: US
Geonames ID: 4068590
Year established: 2014
How will a ROR ID for this organization be used? To link publications to a research facility 
Other information about this request: https://www.uah.edu/facilities-and-operations/news/6332-7-million-severe-weather-research-lab-building-coming-to-uah-campus

**Comment by rileymmarsh** [comment]
Research and teaching facility attached to UAH. Funds and employs researchers. Solid affiliation usage. Should be added.
