### ISSUE TITLE
Add a new organization to ROR: Sheikh Hasina Medical University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13673]
Summary of request: Add a new organization to ROR

Name of organization: Sheikh Hasina Medical University*en
Website: https://shmu.ac.bd
Domains: shmu.ac.bd
Link to publications: https://doi.org/10.1109/EICT61409.2023.10427577 https://doi.org/10.3329/jom.v23i2.60626 https://doi.org/10.1097/01.hs9.0000975908.55937.36
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Sheikh_Hasina_Medical_University,_Khulna
Wikidata ID: Q83837104
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: Sheikh Hasina Medical University, Khulna*en; Khulna Medical University*en
Aliases:
Labels: শেখ হাসিনা মেডিকেল বিশ্ববিদ্যালয়, খুলনা*bn
Acronym/abbreviation: SHMU*en
Related organizations: 
City: Khulna
Country: Bangladesh 
Geonames ID: 1337211
Year established: 2020
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Medical school in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
