### ISSUE TITLE
Add a new organization to ROR: Mildred Elley College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13684]
Summary of request: Add a new organization to ROR

Name of organization: Mildred Elley College*en
Website: https://www.mildred-elley.edu
Domains: mildred-elley.edu
Link to publications: https://scholarsarchive.library.albany.edu/cgi/viewcontent.cgi?article=1063&context=ulib_fac_scholar https://infonomics-society.org/wp-content/uploads/iji/published-papers/volume-11-2018/One-Classroom-Two-Cultures.pdf https://doi.org/10.7759/cureus.26805
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Mildred_Elley
Wikidata ID: Q6850968
ISNI ID: 0000 0004 0526 0928
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Mildred Elley Business School*en; Mildred Elley*en
Labels:
Acronym/abbreviation:
Related organizations: 
City: Albany
Country: United States
Geonames ID: 5106834
Year established: 1917
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
For-profit college in New York with sparse research output. Still, funds and employs researchers. Adequate affiliation usage. Should be added.
