### ISSUE TITLE
Add a new organization to ROR: Bangabandhu Sheikh Mujibur Rahman University, Kishoreganj

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13681]
Summary of request: Add a new organization to ROR

Name of organization: Bangabandhu Sheikh Mujibur Rahman University, Kishoreganj*en
Website: https://bsmru.ac.bd
Domains: bsmru.ac.bd
Link to publications: https://doi.org/10.1109/ACCESS.2023.3304332 https://doi.org/10.1142/S0217984924504815 http://doi.org/10.12928/telkomnika.v22i4.25812
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Bangabandhu_Sheikh_Mujibur_Rahman_University,_Kishoreganj
Wikidata ID: Q86502559
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: BSMRU, Kishoreganj*en; বঙ্গবন্ধু শেখ মুজিবুর রহমান বিশ্ববিদ্যালয়*bn
Labels: বঙ্গবন্ধু শেখ মুজিবুর রহমান বিশ্ববিদ্যালয়, কিশোরগঞ্জ*bn
Acronym/abbreviation: BSMRU*en
Related organizations: 
City: Kishoreganj
Country: Bangladesh
Geonames ID: 1337249
Year established: 2020
How will a ROR ID for this organization be used? 
Other information about this request: City name in org title is to disambiguate from the newly formed (2023) Bangabandhu Sheikh Mujibur Rahman University, Naogaon, which isn't yet ROR-eligible but likely will be in the next year or two.

**Comment by rileymmarsh** [comment]
Public university in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
