### ISSUE TITLE
Add a new organization to ROR: FSU Coastal & Marine Laboratory

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#13680]
Summary of request: Add a new organization to ROR

Name of organization: FSU Coastal and Marine Laboratory*en
Website: https://marinelab.fsu.edu
Domains: marinelab.fsu.edu
Link to publications: https://doi.org/10.1139/cjfas-2019-0202, https://marinelab.fsu.edu/research/publications/ 
Organization type: Facility
Organization status: Active
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Florida State University Coastal and Marine Laboratory*en; Florida State University Marine Laboratory*en; FSU Oceanographic Institute*en; FSU Oceanic Institute*en; FSU Edward Ball Marine Laboratory*en; FSU Coastal & Marine Laboratory*en; FSU Marine Lab*en; FSU Coastal & Marine Lab*en; FSU Coastal Marine Lab*en
Labels:
Acronym/abbreviation: FSUCML*en; CML*en
Related organizations: https://ror.org/05g3dte14 (parent)
City: Saint Teresa
Country: US
Geonames ID: 4171613
Year established: 1949
How will a ROR ID for this organization be used? To link research publications to a research facility
Other information about this request:

**Comment by rileymmarsh** [comment]
Marine laboratory at FSU. Funds and employs researchers. Solid affiliation usage. Should be added.
