### ISSUE TITLE
Add a new organization to ROR: Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13683]
Summary of request: Add a new organization to ROR

Name of organization: Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University*en
Website: http://bsfmstu.ac.bd
Domains: bsfmstu.ac.bd
Link to publications: https://doi.org/10.1111/jai.14163 https://doi.org/10.1049/pel2.12577 https://doi.org/10.1002/bte2.20220018
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Bangamata_Sheikh_Fojilatunnesa_Mujib_Science_and_Technology_University
Wikidata ID: Q29016368
ISNI ID: 0000 0005 0720 1670
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Bangamata Sheikh Fojilatunnesa Mujib Science & Technology University*en; Bongomata Sheikh Fazilatunnesa Mujib University of Science and Technology*en; Jamalpur Science and Technology University*en
Labels: বঙ্গমাতা শেখ ফজিলাতুন্নেছা মুজিব বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়*bn
Acronym/abbreviation: BSFMSTU*en; JSTU*en
Related organizations: 
City: Melandaha Upazila
Country: Bangladesh
Geonames ID: 7647189
Year established: 2017
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Science and technology university in Bangladesh. Name changed to Jamalpur Science and Technology University in Google Maps. Funds and employs researchers. Solid affiliation usage. Should be added.
