### ISSUE TITLE
Add a new organization to ROR: Crystal Bridges Museum of American Art

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13696]
Summary of request: Add a new organization to ROR

Name of organization: Crystal Bridges Museum of American Art*en
Website: https://crystalbridges.org
Domains: crystalbridges.org
Link to publications: https://doi.org/10.17077/0003-4827.12212 https://doi.org/10.1093/jdh/epac022 https://doi.org/10.1086/669991
Organization type: Archive
Organization status: Active
Wikipedia page: 
Wikidata ID: Q1142334
ISNI ID: 0000 0000 8689 2089
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Crystal Bridges*en
Labels:
Acronym/abbreviation: CBMAA*en
Related organizations: 
City: Bentonville
Country: United States
Geonames ID: 4101260
Year established: 2011
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Art museum in Arkansas. Funds and employs researchers. Solid affiliation usage. Should be added.
