### ISSUE TITLE
Add a new organization to ROR: Hugging Face

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1369]
Summary of request: Add a new organization to ROR

Name of organization: Hugging Face
Website: https://huggingface.co
Link to publications: https://doi.org/10.48550/arxiv.2011.14203; https://doi.org/10.1145/3466752.3480095
Organization type: Company
Wikipedia page: https://en.wikipedia.org/wiki/Hugging_Face
Wikidata ID: Q108943604
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City: New York, New York
Country: USA
Geonames ID: 5128581
Year established: 2016
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
AI software company based in New York. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1609/aaai.v33i01.33016949; https://openalex.org/W2900533563; https://openalex.org/W3126493605; https://openalex.org/W3110511794; https://doi.org/10.48550/arxiv.2011.14203; https://doi.org/10.1145/3466752.3480095; https://openalex.org/W4281862740

ORCID affiliation usage: https://orcid.org/0000-0002-1552-999X ; https://orcid.org/0000-0002-7997-1170

**Comment by carlyrobinson** [comment]
Agree, should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02grspc61 in release v1.12.
