### ISSUE TITLE
Modify the information in an existing ROR record: Macao University of Tourism

### ISSUE THREAD

**Issue by rileymmarsh** [ror-community/ror-updates#13709]
Summary of request: Modify the information in an existing ROR record

Name of organization: Institute for Tourism Studies
ROR ID: https://ror.org/00nx0vn86
Which part of the record needs to be changed? Names; Website; Identifiers
Description of change: Change name to Macao University of Tourism*en. Add label 澳門旅遊大學*zh; Universidade de Turismo de Macau*pt. Replace website with https://www.utm.edu.mo. Add utm.edu.mo to domains. Add isni 0000 0004 0605 0308. Add wikidata id Q9289400. Add acronym UTMpt; IFTM. Following #13533

Update: ror_display.replace==Macao University of Tourism*en | label.replace==Macao University of Tourism*en; Universidade de Turismo de Macau*pt; 澳門旅遊大學*zh | alias.add==Institute for Tourism Studies*en; Instituto de Formação Turística*pt; 旅遊學院*zh | website.replace==https://www.utm.edu.mo | domains.add==utm.edu.mo | isni.all.add==0000 0004 0605 0308 | isni.preferred.replace==0000 0004 0605 0308 | wikidata.all.add==Q9289400 | wikidata.preferred.replace==Q9289400 | acronym.replace==UTM*pt; IFTM*en; IFT*en$

**Comment by adambuttrick** [comment]
@rileymmarsh Here we would use replace for labels and need to include the new display name name, in addition to the new labels. We would also use replace for the acronyms to assign languages to the existing. UTM acronym was also combined with its language code vs. added to it with the asterisk syntax.
