### ISSUE TITLE
Add a new organization to ROR: Kaggle

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1370]
Summary of request: Add a new organization to ROR

Name of organization: Kaggle
Website: http://www.kaggle.com
Link to publications: https://doi.org/10.1145/2517288.2517299; https://doi.org/10.1038/s41591-021-01620-2
Organization type: Company
Wikipedia page: https://en.wikipedia.org/wiki/Kaggle
Wikidata ID: Q10996045
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City: San Francisco
Country: USA
Geonames ID: 5391959
Year established: 2010
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by carlyrobinson** [comment]
Agree, should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/050tqnp89 in release v1.12.
