### ISSUE TITLE
Modify the information in an existing ROR record: Centro Studi e Laboratori Telecomunicazioni - https://ror.org/01rt74q71

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#13716]
Summary of request: Modify the information in an existing ROR record

Name of organization: Centro Studi e Laboratori Telecomunicazioni
ROR ID: https://ror.org/01rt74q71
Which part of the record needs to be changed? Name, alias, acronym
Description of change: Change name to Telecom Italia Lab. Add alias Telecom Italia Lab S.p.A.. Add acronym TILAB.

Update: ror_display.replace==Telecom Italia Lab*it | label.replace==Telecom Italia Lab*it | alias.add==Centro Studi e Laboratori Telecomunicazioni*it; Telecom Italia Lab S.p.A.*it;  TILab*it$

**Comment by rileymmarsh** [comment]
Possibly inactive - affiliated websites no longer load, and there have been acquisitions involving the lab.
