### ISSUE TITLE
Modify the information in an existing ROR record: Centre de Recherche de Biochimie Macromoléculaire - https://ror.org/01xpc6869

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#13741]
Summary of request: Modify the information in an existing ROR record

Name of organization: Centre de Recherche de Biochimie Macromoléculaire
ROR ID: https://ror.org/01xpc6869
Which part of the record needs to be changed? Name, alias, site
Description of change: Change name to Centre de Recherche de Biochimie Montpellier. Add alias UMR 5237. Replace site with https://www.crbm.cnrs.fr.

Update: ror_display.replace==Centre de Recherche de Biochimie Montpellier*fr | label.add==Centre de Recherche de Biochimie Montpellier*fr | alias.add==UMR 5237 | website.replace==https://www.crbm.cnrs.fr$

**Comment by adambuttrick** [comment]
Centre de Recherche de Biochimie Macromoléculaire and Centre de Recherche de Biochimie Montpellier are equivalent labels.

**Comment by rileymmarsh** [comment]
Duplicate of #13724
