### ISSUE TITLE
Merge National Yang Ming University and National Chiao Tung University

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#138]
Summary of request: Merge two or more ROR records

National Yang Ming University (https://ror.org/009h5ks85)
National Chiao Tung University (https://ror.org/00se2k293)

Institutions have merged into National Yang Ming Chiao Tung University as of February 2021 - see https://www.nycu.edu.tw/about-nycu/about-nycu/

**Comment by adambuttrick** [comment]
Merger is part of GRID removed records, so will address in that update.
