### ISSUE TITLE
Add a new organization to ROR: Islamic Arabic University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13882]
Summary of request: Add a new organization to ROR

Name of organization: Islamic Arabic University*en
Website: http://iau.edu.bd/
Domains: iau.edu.bd
Link to publications: https://doi.org/10.3126/sjah.v4i2.47423 https://doi.org/10.31893/multirev.2024137 https://doi.org/10.23917/mier.v1i1.2674
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Islamic_Arabic_University
Wikidata ID: Q23043282
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: ইসলামি আরবি বিশ্ববিদ্যালয়*bn; الجامعة الإسلامية العربية*ar
Acronym/abbreviation: IAU*en
Related organizations: 
City: Dhaka
Country: Bangladesh
Geonames ID: 1185241
Year established: 2013
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Bangaldesh. Funds and employs researchers. Solid affiliation usage. Should be added.
