### ISSUE TITLE
Add a new organization to ROR: Rajshahi Medical University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13881]
Summary of request: Add a new organization to ROR

Name of organization: Rajshahi Medical University*en
Website: https://www.rmu.edu.bd
Domains: rmu.edu.bd
Link to publications: https://doi.org/10.3329/jcamr.v10i1.69418 https://doi.org/10.9734/ajess/2023/v48i11047 https://doi.org/10.3390/plants10061135
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Rajshahi_Medical_University
Wikidata ID: Q56816080
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: রাজশাহী মেডিকেল বিশ্ববিদ্যালয়*bn
Acronym/abbreviation: RMU*en
Related organizations: 
City: Rajshahi
Country: Bangladesh
Geonames ID: 1185128
Year established: 2017
How will a ROR ID for this organization be used? 
Other information about this request: ≠ https://ror.org/02k4h0b10

**Comment by adambuttrick** [comment]
University in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
