### ISSUE TITLE
Add a new organization to ROR: Habiganj Agricultural University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13880]
Summary of request: Add a new organization to ROR

Name of organization: Habiganj Agricultural University*en
Website: https://hau.ac.bd
Domains: hau.ac.bd
Link to publications: https://doi.org/10.47440/JAFE.2024.5209 https://doi.org/10.4236/as.2024.152014 https://doi.org/10.3390/agronomy12092128
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Habiganj_Agricultural_University
Wikidata ID: Q65318701
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: হবিগঞ্জ কৃষি বিশ্ববিদ্যালয়*bn
Acronym/abbreviation: HAU*en
Related organizations: 
City: Habiganj
Country: Bangladesh
Geonames ID: 1185209
Year established: 2020
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University on Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
