### ISSUE TITLE
Add a new organization to ROR: Chandpur Science and Technology University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13896]
Summary of request: Add a new organization to ROR

Name of organization: Chandpur Science and Technology University*en
Website: https://www.cstu.ac.bd
Domains: cstu.ac.bd
Link to publications: https://doi.org/10.1109/STI59863.2023.10464900 https://doi.org/10.3390/math11163504 https://doi.org/10.1109/STI59863.2023.10465048
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Chandpur_Science_and_Technology_University
Wikidata ID: Q83839243
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Chandpur Science & Technology University*en
Labels: চাঁদপুর বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়*bn
Acronym/abbreviation: CSTU*en
Related organizations: 
City: Chandpur
Country: Bangladesh
Geonames ID: 1337194
Year established: 2021
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
