### ISSUE TITLE
Add a new organization to ROR: Chittagong Medical University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13914]
Summary of request: Add a new organization to ROR

Name of organization: Chittagong Medical University*en
Website: https://cmu.edu.bd
Domains: cmu.edu.bd
Link to publications: https://doi.org/10.1097/JD9.0000000000000133 https://doi.org/10.3329/iahsmj.v4i1.59135 https://doi.org/10.1111/dth.13486
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Chittagong_Medical_University
Wikidata ID: Q19891182
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: চট্টগ্রাম মেডিকেল বিশ্ববিদ্যালয়*bn; சிட்டகாங் மருத்துவப் பல்கலைக்கழகம்*ta
Acronym/abbreviation: CMU*en
Related organizations: 
City: Chittagong
Country: Bangladesh
Geonames ID: 1205733
Year established: 2016
How will a ROR ID for this organization be used? 
Other information about this request: ≠ https://ror.org/01y8zn427

**Comment by adambuttrick** [comment]
University in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
