### ISSUE TITLE
Add a new organization to ROR: Khulna Agricultural University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#13915]
Summary of request: Add a new organization to ROR

Name of organization: Khulna Agricultural University*en
Website: https://kau.ac.bd
Domains: kau.ac.bd
Link to publications: https://doi.org/10.5455/faa.71289 https://doi.org/10.52168/bjf.2021.33.11 https://doi.org/10.54319/jjbs/170202
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Khulna_Agricultural_University
Wikidata ID: Q61365816
ISNI ID: 0000 0005 1665 484X
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: খুলনা কৃষি বিশ্ববিদ্যালয়*bn
Acronym/abbreviation: KAU*en
Related organizations: 
City: Khulna
Country: Bangladesh
Geonames ID: 1336135
Year established: 2015
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
