### ISSUE TITLE
Add a new organization to ROR: Washington State Department of Transportation

### ISSUE THREAD

**Issue by ptvrdy** [ror-community/ror-updates#13910]
Summary of request: Add a new organization to ROR

Name of organization: Washington State Department of Transportation*en
Website: https://wsdot.wa.gov
Domains: wsdot.wa.gov
Link to publications: https://cdm16977.contentdm.oclc.org/digital/#:~:text=This%20collection%20contains%20city%20and%20county%20road%20maps%20of%20Washington
Organization type: Government
Organization status:
Wikipedia page: https://en.wikipedia.org/wiki/Washington_State_Department_of_Transportation
Wikidata ID: Q834834
ISNI ID: 0000 0004 0422 7456
GRID ID:
Crossref Funder ID: 100014789
Other names for the organization: 
Aliases: Washington State DOT*en
Labels:
Acronym/abbreviation: WSDOT*en
Related organizations: 
City: Olympia
Country: Washington, United States of America
Geonames ID: 5805687
Year established: 1905
How will a ROR ID for this organization be used?: To associate publications with their WSDOT funding
Other information about this request:

**Comment by rileymmarsh** [comment]
Department of transportation for Washington State. Funds and employs researchers. Solid affiliation usage. Should be added.
