### ISSUE TITLE
Add a new organization to ROR: Benefit-sharing Fund

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#13972]
Summary of request: Add a new organization to ROR

Name of organization: Benefit-sharing Fund of the International Treaty on Plant Genetic Resources for Food and Agriculture*en
Website: https://www.fao.org/plant-treaty/areas-of-work/benefit-sharing-fund/
Domains: 
Link to publications: 
Organization type: Funder
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: International Treaty on Plant Genetic Resources for Food and Agriculture Benefit-sharing Fund*en; ITPGRFA Benefit-sharing Fund*en
Labels: 
Acronym/abbreviation: BSF*en
Related organizations: https://ror.org/00pe0tf51 (parent)
City: Rome
Country: Italy
Geonames ID: 3169070
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by marcomarsella** [comment]
Hi Adma, thank you for your assistance. I would prefer the name to be

Benefit-sharing Fund of the International Treaty on Plant Genetic Resources for Food and Agriculture

Do you need me to submit a request thorugh ror.org or you can proceed with the above?

**Comment by adambuttrick** [comment]
@marcomarsella I've updated. Nothing further needed and thank you for flagging!

**Comment by marcomarsella** [comment]
@adambuttrick Thank you for following up on this. When can I expect to find the new Organization defined in ROR?

**Comment by adambuttrick** [comment]
Funder under https://ror.org/00pe0tf51. Extensive funding references, so this is fine to add.
