### ISSUE TITLE
Add a new organization to ROR: Laboratoire d'Ingénierie pour les Systèmes Complexes

### ISSUE THREAD

**Issue by NicolasDumoulin** [ror-community/ror-updates#13983]
Summary of request: Add a new organization to ROR

Name of organization: Laboratoire d'Ingénierie pour les Systèmes Complexes*fr
Website: https://lisc.inrae.fr
Domains: 
Link to publications: https://hal.science/search/index?q=inrae+lisc 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: 
Labels:
Acronym/abbreviation: LISC*fr; UR LISC*fr
Related organizations: https://ror.org/04aqtsh50 (parent)
City: Aubière
Country: France
Geonames ID: 3036364
Year established: 1997
How will a ROR ID for this organization be used? For creating and registering an open Data Management Plan
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit in France. Funds and employs researchers. Solid affiliation usage. Should be added.
