### ISSUE TITLE
Add a new organization to ROR: Yellowstone National Park

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#14]
Summary of request: Add a new organization to ROR

Name of organization: Yellowstone National Park
Website: https://www.nps.gov/yell/
Link to publications: https://www.nps.gov/yell/learn/scienceresearch.htm
Organization type: Archive
Wikipedia page: https://en.wikipedia.org/wiki/Yellowstone_National_Park
Wikidata ID: https://www.wikidata.org/wiki/Q351
ISNI ID: https://isni.org/isni/0000000121667865
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/044zqqy65 (parent)
City: Yellowstone National Park, Wyoming
Country: United States
Geonames ID: 5843642
Year established: 1872
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by mariagould** [comment]
This is a legacy request from 2020. The request came from Dryad for the purpose of identifying datasets created by Yellowstone-affiliated researchers. ROR submitted it to GRID for inclusion but it was not approved by GRID at the time. I am reinstating the request now so that we can create the entry in ROR. Per our criteria for inclusion, ROR includes national parks that are involved in research and used as an affiliation. I recommend that Yellowstone National Park be added.

**Comment by carlyrobinson** [comment]
Within scope, recommend adding to registry.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04rw5yk74 in release v1.1.
