### ISSUE TITLE
Add a new organization to ROR:  The Navigation Fund

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#14004]
Summary of request: Add a new organization to ROR

Name of organization: The Navigation Fund*en
Website: https://navigation.org
Domains: navigation.org
Link to publications: 
Organization type: Nonprofit; Funder
Organization status: active
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation:
Related organizations: 
City: Berkeley
Country: United States
Geonames ID: 5327684
Year established: 2023
How will a ROR ID for this organization be used? Identify funders in awards and research outputs 
Other information about this request:

**Comment by adambuttrick** [comment]
New funder. Adding as part of award registration scheme.
