### ISSUE TITLE
Modify the information in an existing ROR record: Al Ain University of Science and Technology - https://ror.org/023abrt21

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14002]
Summary of request: Modify the information in an existing ROR record

Name of organization: Al Ain University of Science and Technology
ROR ID: https://ror.org/023abrt21
Which part of the record needs to be changed? Name
Description of change: Update name to Al Ain University*en
(Name [changed](https://en.wikipedia.org/wiki/Al_Ain_University) 2019)

Update: ror_display.replace==Al Ain University*en | label.replace==Al Ain University*en;  جامعة العين للعلوم والتكنولوجيا*ar | alias.add==Al Ain University of Science and Technology*en$

**Comment by adambuttrick** [comment]
Confirmed update.
