### ISSUE TITLE
Add a new organization to ROR: Palau Community College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14026]
Summary of request: Add a new organization to ROR

Name of organization: Palau Community College*en
Website: https://pcc.palau.edu
Domains: pcc.palau.edu
Link to publications: https://doi.org/10.1080/21500894.2020.1725103 https://doi.org/10.4269/ajtmh.24-0129 https://doi.org/10.1002/wer.10923
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Palau_Community_College
Wikidata ID: Q15060585
ISNI ID: 0000 0001 2163 3673
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Micronesian Occupational College*en
Labels:
Acronym/abbreviation: PCC*en
Related organizations: 
City: Koror
Country: Palau
Geonames ID: 1559446
Year established: 1969
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Palau. Funds and employs researchers. Solid affiliation usage. Should be added.
