### ISSUE TITLE
Add a new organization to ROR: Teknologi Pendidikan ID

### ISSUE THREAD

**Issue by vzrenggamani** [ror-community/ror-updates#14020]
Summary of request: Add a new organization to ROR

Name of organization: Teknologi Pendidikan ID (Indonesia)*id
Website: https://teknologipendidikan.or.id
Domains: teknologipendidikan.or.id; teknologipendidikan.sch.id
Link to publications: 
- https://jurnal.mediaakademik.com/index.php/jma/article/view/720 (Publications)
- https://scholar.google.com/citations?user=qZFqIZwAAAAJ&hl=id (Profile)
- https://scholar.google.com/citations?user=PLXxL8wAAAAJ&hl=id (Profile)
- https://repository.teknologipendidikan.or.id/publications/583622/pengembangan-learning-management-system-dengan-pendekatan-gamifikasi-untuk-pembe (Repository)
- https://issn.brin.go.id/terbit/detail/20230729171148525 (Managed Journal)
- https://www.scilit.net/publishers/97359 (Managed Publication)

Organization type: Company
Wikipedia page: 
Wikidata ID: Q114913113
ISNI ID: 0000 0005 0942 0893
GRID ID: 
Crossref Funder ID: 
Other names for the organization: PT Inovasi Teknologi Pembelajaran*id; EDTECH-ID Institute; EDTECH-ID
Aliases: 
Labels: 
Acronym/abbreviation: 
Related organizations: 
City: Sidoarjo
Country: Indonesia
Geonames ID: 1627253
Year established: 2023
How will a ROR ID for this organization be used?
1. The RoR ID are mandatory for registering the affiliation with Indonesia Research Center System managed by Badan Riset dan Inovasi Nasional (BRIN).
2. Ministry of Education and Higher Education are asking to have ROR ID to acknowledge the published paper that comes from our researchers in OJS system.
3. We are providing funding for publication research paper that conducted by undergraduate.

Other information about this request:
1. We are still asking elsevier for adding our affiliation to the Funder Registry.

**Comment by vzrenggamani** [comment]
https://doi.org/10.37859/jpumri.v8i2.7455

**Comment by adambuttrick** [comment]
Educational services and technology consultancy in Indonesia. Affiliation usage is somewhat limited, but has multiple authors using and otherwise looks fine. @vzrenggamani ROR advises against organizations requiring ROR IDs as not all organizations that might need to be supported by the integrator's services are in scope for ROR. Could you point us at any documentation where BRIN is making this mandatory so we can get in touch with them?
