### ISSUE TITLE
Add a new organization to ROR: Utah Agricultural Experiment Station

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#14047]
Summary of request: Add a new organization to ROR

Name of organization: Utah Agricultural Experiment Station*en
Website: https://caas.usu.edu/uaes/
Domains: 
Link to publications: https://doi.org/10.26078/4FBT-0K57 
Organization type: Facility; Funder
Organization status: Active
Wikipedia page: 
Wikidata ID: 
ISNI ID: 0000 0004 5906 8413 
GRID ID:
Crossref Funder ID: 100007199
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: UAES*en
Related organizations: https://ror.org/00h6set76 (parent)
City: Logan
Country: US
Geonames ID: 5777544
Year established:
How will a ROR ID for this organization be used? To track research activities connected to / funded by a facility
Other information about this request: Other U.S. state agricultural experimental stations are already in ROR, e.g., https://ror.org/01cc25b87

**Comment by adambuttrick** [comment]
Research station in the US. Funds and employs researchers. Solid affiliation usage. Should be added.
