### ISSUE TITLE
Modify the information in an existing ROR record: Federal Highway Administration

### ISSUE THREAD

**Issue by ptvrdy** [ror-community/ror-updates#14053]
Summary of request: Modify the information in an existing ROR record

Name of organization: Federal Highway Administration
ROR ID: https://ror.org/0473rr271
Which part of the record needs to be changed?: Old names that the organization used to be known as
Description of change: The Bureau of Public Roads (BPR) underwent several transformations over the years. Initially established in the Department of Agriculture in 1893, it was later renamed the Office of Public Roads and Rural Engineering. [In 1918, it became the Bureau of Public Roads](https://www.archives.gov/research/guide-fed-records/groups/030.html)[1](https://www.archives.gov/research/guide-fed-records/groups/030.html).

In 1939, the BPR was transferred to the Federal Works Agency and renamed the Public Roads Administration. [Eventually, it became part of the Federal Highway Administration (FHWA) in 1966](https://www.archives.gov/research/guide-fed-records/groups/030.html)[1](https://www.archives.gov/research/guide-fed-records/groups/030.html)[2](https://www.britannica.com/topic/Bureau-of-Public-Roads).

FHWA should also have the "used to be known or have" Bureau of Public Roads? Complicated issue since it used to be under Dept. of Agriculture.

**Comment by adambuttrick** [comment]
We would not process these as alias updates on https://ror.org/0473rr271, but instead with a new inactive record to represent the Bureau of Public Roads that was replaced by/subsumed within the FHA, indicating FHA as its successor. I'll create the corresponding new record request to reflect.
