### ISSUE TITLE
Modify the information in an existing ROR record: National Highway Traffic Safety Administration

### ISSUE THREAD

**Issue by ptvrdy** [ror-community/ror-updates#14051]
Summary of request: Modify the information in an existing ROR record

Name of organization: National Highway Traffic Safety Administration
ROR ID: https://ror.org/04gcfqs37
Which part of the record needs to be changed?: Other names/old names
Description of change: National Highway Traffic Safety Administration used to be known as the National Highway Safety Bureau when it was first established.

Update: alias.add==National Highway Safety Bureau*en | website.replace==https://www.nhtsa.gov | domains.add==nhtsa.gov$

**Comment by adambuttrick** [comment]
Appears to be sufficient continuity to class this as an alias vs. predecessor organization.
