### ISSUE TITLE
Add a new organization to ROR: Kansas Geological Survey

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14073]
Summary of request: Add a new organization to ROR

Name of organization: Kansas Geological Survey*en
Website: https://kgs.ku.edu
Domains: kgs.ku.edu
Link to publications: https://doi.org/10.17161/mg.v4i.20851 https://doi.org/10.2118/38825-MS https://doi.org/10.1190/segam2019-3216657.1
Organization type: Facility
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Kansas_Geological_Survey
Wikidata ID: Q6364985
ISNI ID: 0000 0004 0495 1989
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: KGS*en
Related organizations: https://ror.org/001tmjg57 (parent)
City: Lawrence
Country: United States
Geonames ID: 4941720
Year established: 1889
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Geological survey in the US. Funds and employs researchers. Solid affiliation usage. Should be added.
