### ISSUE TITLE
Merge Open Geospatial Consortium records (https://ror.org/00fsdxs93 and https://ror.org/00nz0j151)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#141]
We have two records in ROR for the Open Geospatial Consortium:

1. https://ror.org/00fsdxs93 is a US location
2. https://ror.org/00nz0j151 is UK location

The website https://www.ogc.org/ lists the location as Massachusetts USA. 

Recommendation: We should merge the two records and redirect the UK record to the US one. The website in the US record needs to be updated from http://www.opengeospatial.org/ to https://www.ogc.org/

Name of organization: Open Geospatial Consortium
ROR ID: https://ror.org/00nz0j151
Related organizations: https://ror.org/00fsdxs93 (successor-np)
Update: change.status==withdrawn;$

**Comment by adambuttrick** [comment]
Per their [contact page](https://www.ogc.org/contacts), OGS has registered entities in the US, UK, and Belgium.

**Comment by mariagould** [comment]
This situation concerns duplicate records for the same organization. It looks like the organization's headquarters are in the US (based on the information in their website footer) so I would recommend retaining the US record as primary and then marking it as a successor of the UK record. 

Therefore: change status of https://ror.org/00nz0j151 to `withdrawn` and add https://ror.org/00fsdxs93 as a successor. 

The metadata in the primary record needs to be updated so I will create a separate issue for that.

**Comment by adambuttrick** [comment]
Record updated in release v1.17.
