### ISSUE TITLE
Add a new organization to ROR: Modern University College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14188]
Summary of request: Add a new organization to ROR

Name of organization: Modern University College*en
Website: http://www.muc.edu.ps
Domains: muc.edu.ps
Link to publications: https://doi.org/10.33193/JALHSS.104.2024.1091 https://doi.org/10.11648/j.ajns.20211006.15 https://doi.org/10.1016/j.heliyon.2023.e21680
Organization type: Education
Organization status: Active
Wikipedia page: https://ar.wikipedia.org/wiki/%D8%A7%D9%84%D9%83%D9%84%D9%8A%D8%A9_%D8%A7%D9%84%D8%B9%D8%B5%D8%B1%D9%8A%D8%A9
Wikidata ID: Q12191842
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: كلية المجتمع العصرية*ar; الكلية العصرية*ar
Aliases:
Labels: الـكلـيـة الـعـصـريـة الـجــامعـيـــة*ar
Acronym/abbreviation: MUC*en
Related organizations: 
City: Ramallah
Country: Palestine
Geonames ID:  282239
Year established: 1983
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
University in Palestine. Funds and employs researchers. Solid affiliation usage. Should be added.
