### ISSUE TITLE
Modify National Institute of Oceanography and Experimental Geophysics (https://ror.org/04y4t7k95)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#142]
Summary: Modify an existing record in ROR
ROR ID: https://ror.org/04y4t7k95

Description of change: 

we want to inform you that the record should show:

National Institute of Oceanography and Applied Geophysics - OGS
Istituto Nazionale di Oceanografia e di Geofisica Sperimentale - OGS
WEBSITE  http://www.inogs.it/

instead of:
National Institute of Oceanography and Experimental Geophysics
OGS, ISTITUTO NAZIONALE DI OCEANOGRAFIA E GEOFISICA SPERIMENTALE
WEBSITE  http://www.ogs.trieste.it/

as these are the official names.
Update: change.name==National Institute of Oceanography and Applied Geophysics; add.labels==Istituto Nazionale di Oceanografia e di Geofisica Sperimentale*Italian;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
