### ISSUE TITLE
Add a new organization to ROR: Centre de Recherche sur les Risques et les Crises

### ISSUE THREAD

**Issue by Hdubray** [ror-community/ror-updates#14260]
Summary of request: Add a new organization to ROR

Name of organization: Centre de Recherche sur les Risques et les Crises*fr
Website: https://www.crc.mines-paristech.fr
Domains: crc.mines-paristech.fr
Link to publications: https://minesparis-psl.hal.science/ENSMP_CRC/search/index/?q=*
Organization type: Facility
Organization status: Active
Wikipedia page: https://fr.wikipedia.org/wiki/Centre_de_recherche_sur_les_risques_et_les_crises
Wikidata ID: Q56318261
ISNI ID: 0000 0000 9642 2734
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: CRC Mines Paris Tech*fr
Labels: Centre for Research on Risks and Crises*en
Acronym/abbreviation: CRC*fr
Related organizations: https://ror.org/04y8cs423 (parent)
City: Sophia Antipolis
Country: France 
Geonames ID: 6640252
Year established: 2008
How will a ROR ID for this organization be used? 
The goal of a recording for this organization is to promote the Centre for Research on Risks and Crises, according to the new curated signature chart, validated by our research director. 
Other information about this request:
You will find the signature charter attached to this request.

Thank you very much ! 

Best regards, 

Héloïse Dubray 
[10963-2024-08-20_Note_Signatures_publications-1.pdf](https://github.com/user-attachments/files/17015620/10963-2024-08-20_Note_Signatures_publications-1.pdf)

**Comment by rileymmarsh** [comment]
Research center in France. Funds and employs researchers. Solid affiliation usage. Should be added.
