### ISSUE TITLE
Add a new organization to ROR: Ministry of Defense

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1427]
Summary of request: Add a new organization to ROR

Name of organization: Ministry of Defense
Website: https://www.moda.gov.sa
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Ministry_of_Defense_(Saudi_Arabia)
Wikidata ID: Q6866094
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Aliases:
Labels: وزارة الدفاع*Arabic
Related organizations: 
City: Riyadh
Country: Saudi Arabia
Geonames ID: 108410
Year established: 1943
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Saudi Arabia's Ministry of Defense. Identified as a parent organization for #1425. Funds and employs researchers. Solid affiliation usage. We also already have other of their ministries (e.g. https://ror.org/036dczj04 and https://ror.org/030atj633), so this should be added.

Publication affiliation usage: https://doi.org/10.9734/jpri/2021/v33i60b34755; https://doi.org/10.9734/jpri/2021/v33i59b34432; https://doi.org/10.1145/1167253.1167305

**Comment by nlundvick** [comment]
Established, top-level organization that is associated with research publications and other activities. As noted by previous curator, other Saudi ministries are already included in the registry. Affiliation use: [https://api.crossref.org/works/?query.affiliation=%22Saudi+Ministry+of+Defense%22](https://api.crossref.org/works/?query.affiliation=%22Saudi+Ministry+of+Defense%22). In scope, add to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03dtp6w69 in release v1.14.
