### ISSUE TITLE
Retire or merge Conexant (https://ror.org/05rx1xe20)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#143]
Conexant (https://ror.org/05rx1xe20) is no longer active.

https://en.wikipedia.org/wiki/Conexant contains information about this organization's history

Either the ROR ID should be deprecated, or we should redirect it to its parent company, Synaptics (https://ror.org/031tq8403)

Name of organization: Conexant
ROR ID: https://ror.org/05rx1xe20
Related organizations: https://ror.org/031tq8403 (successor-np)
Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
Record updated in release v1.15.
