### ISSUE TITLE
Add a new organization to ROR: Rabindra University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14330]
Summary of request: Add a new organization to ROR

Name of organization: Rabindra University*en
Website: https://www.rub.ac.bd
Domains: rub.ac.bd
Link to publications: https://doi.org/10.1504/IJECRM.2024.138649 https://doi.org/10.1002/pits.23069 https://doi.org/10.34293/education.v9i3.3732
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Rabindra_University,_Bangladesh
Wikidata ID: Q20613210
ISNI ID: 0000 0004 8501 6641
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Rabindra University, Bangladesh*en; রবীন্দ্র বিশ্ববিদ্যালয়, বাংলাদেশ*bn
Labels: রবীন্দ্র বিশ্ববিদ্যালয়*bn
Acronym/abbreviation: RUB*en
Related organizations: 
City: Sirajganj
Country: Bangladesh
Geonames ID: 1337168
Year established: 2017
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
University in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
