### ISSUE TITLE
Modify the information in an existing ROR record: 04s11ea33

### ISSUE THREAD

**Issue by stmichaelis** [ror-community/ror-updates#14376]
Summary of request: Modify the information in an existing ROR record

Name of organization: Lamarr Institute
ROR ID: https://ror.org/04s11ea33
Which part of the record needs to be changed?
Record should be updated with more precise and additional information. Fields not mentioned here should be kept "as is".

Description of change:

UPDATE: Name: Lamarr Institute for Machine Learning and Artificial Intelligence

ADD: Location: Dortmund, GeoNamesID: 2935517, Germany

ADD: Location: Bonn, GeoNamesID: 11856166, Germany

UPDATE: Name (de): Lamarr-Institut für Maschinelles Lernen und Künstliche Intelligenz

DELETE: Name, Acronym: ML2R

ADD: Link to publications: https://lamarr-institute.org/publications/

UPDATE: Organization type: Facility

ADD: Year established: 2022

ADD: Relationship, Parent Organization: TU Dortmund University, https://ror.org/01k97gp34

ADD: Relationship, Parent Organization: University of Bonn, https://ror.org/041nas322

ADD: Relationship, Parent Organization: Fraunhofer Institute for Intelligent Analysis and Information Systems, https://ror.org/04nc32781

ADD: Relationship, Parent Organization: Fraunhofer Institute for Material Flow and Logistics: https://ror.org/00z7dje19

Update: ror_display.replace==Lamarr Institute for Machine Learning and Artificial Intelligence*en | label.replace==Lamarr Institute for Machine Learning and Artificial Intelligence*en; Lamarr-Institut für Maschinelles Lernen und Künstliche Intelligenz*de | alias.replace==Lamarr Institute*en; Lamarr-Institut*de; Kompetenzzentrum Maschinelles Lernen Rhein-Ruhr*de | types.replace==Facility | geonames.add==2935517; 11856166 | established.replace==2022$

Related organizations: https://ror.org/01k97gp34 (parent) https:// https://ror.org/041nas322 (parent) https://ror.org/04nc32781 (parent) https://ror.org/00z7dje19 (parent)

**Comment by adambuttrick** [comment]
Confirmed updates. We would not delete ML2R, as this was at one time a valid acronym. ROR preserves historic name forms on its records to facilitate matching. For more details about this approach to names, please see here: https://ror.org/blog/2022-08-31-name-metadata-in-ror/

**Comment by stmichaelis** [comment]
Fine to me, thanks. Was not aware of the importance of keeping the history, but then this is absolutely correct.
