### ISSUE TITLE
Add a new organization to ROR: Center for Community Progress

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14390]
Summary of request: Add a new organization to ROR

Name of organization: Center for Community Progress*en
Website: https://communityprogress.org
Domains: communityprogress.org
Link to publications: https://doi.org/10.1080/10511482.2024.2321226 https://doi.org/10.1093/cdj/bsv052 https://doi.org/10.1016/j.cities.2017.01.008
Organization type: Nonprofit
Organization status: Active
Wikipedia page: 
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID: 100030187
Other names for the organization: National Vacant Properties Campaign*en
Aliases:
Labels:
Acronym/abbreviation: CCP*en
Related organizations: 
City: Flint
Country: United States
Geonames ID: 4992982
Year established: 2010
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Nonprofit in the US. Funds and employs researchers. Solid affiliation usage. Should be added.
