### ISSUE TITLE
Redirect Instituto Superior de Contabilidade e Administracao do Porto (https://ror.org/00wg3s094)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#144]
Summary: Redirect a subsidiary unit to its parent organization

Name of organization: Instituto Superior de Contabilidade e Administracao do Porto 
ROR ID: https://ror.org/00wg3s094
Description of change: The Polytechnic Institute of Porto (https://ror.org/04988re48) has eight schools. Someone in one of the Schools (ISCAP) also decide to create a ROR, that is not correct because the top organisation is the Polytechnic Institut of Porto, they are just one of our eight schools, as anyone can see in the URL: www.iscap.ipp.pt. They exist since 1886, but by the Law nº70/88, from 3 of March of 1988 they were integrated in Polytechnic Institut of Porto (https://dre.pt/web/guest/pesquisa/-/search/287592/details/normal?q=decreto-lei+n%C2%BA70%2F88+de+3+de+mar%C3%A7o)

Update: change.status==withdrawn;$
Related organizations: https://ror.org/04988re48 (successor-np)

**Comment by mariagould** [comment]
This request concerns the fact that the sub-institutes forming part of the Polytechnic Institute of Porto (https://ror.org/04988re48) are considered part of the primary institution and therefore should not have separate ROR IDs. It looks like only one of the eight schools has an existing ROR record (https://ror.org/00wg3s094). My suggestion, following the information from the requestor, would be to change the status of https://ror.org/00wg3s094 to `withdrawn` and indicate the primary institution `https://ror.org/04988re48` as a successor.

**Comment by adambuttrick** [comment]
Updated in release v1.17.
