### ISSUE TITLE
Modify the information in an existing ROR record:

### ISSUE THREAD

**Issue by ShirazMED** [ror-community/ror-updates#14408]
Summary of request: Modify the information in an existing ROR record

Name of organization: Shiraz University of Medical Sciences
ROR ID: https://ror.org/01n3s4692
Which part of the record needs to be changed? Some links need to be updated (University's Website + 1 Child Organization + 2 Related Organizations)
Description of change:
We would like to request the following updates to the links of the University and its organizations:

University's Website: **https://sums.ac.ir** (Old Link: http://gsia.sums.ac.ir/en)
Stem Cell Technology Research Center: **https://sctrc.sums.ac.ir** (Old Link: http://sctrc.sums.ac.ir/en/)
Faghihi Hospital: **https://faghihi.sums.ac.ir** (Old Link: http://faghihi.sums.ac.ir/bakhshe_english)
Amir-Al-Momenin Hospital: **https://amiralmomeninhospital.sums.ac.ir** (Old Link: https://amiralmomeninbh.sums.ac.ir)

Thank you in advance,

Update: website.replace==https://sums.ac.ir$

**Comment by adambuttrick** [comment]
Created separate update issues for other records mentioned. Website is otherwise fine to update.

**Comment by ShirazMED** [comment]
Dear Adam,
Thank you for your follow-up. We keep checking for updates on the links.
Could you please provide the latest status of our request? I appreciate your time and assistance.
Looking forward to hearing from you soon

**Comment by adambuttrick** [comment]
@ShirazMED These requests have been approved and will be published in our next release, which is currently scheduled for next week. The issue will be updated once the changes have been published, so please continue to follow to be notified.
