### ISSUE TITLE
Add a new organization to ROR: Pan African University

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1441]
Summary of request: Add a new organization to ROR

Name of organization: Pan-African University
Website: https://pau-au.africa
Link to publications: 
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Pan-African_University
Wikidata ID: Q7129473
ISNI ID: 0000 0004 9332 9605
GRID ID:
Crossref Funder ID: 501100022253
Other names for the organization: 
Acronym/abbreviation: PAU
Related organizations: 
City: Yaounde
Country: Cameroon
Geonames ID: 2220957
Year established: 2011
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by mariagould** [comment]
I concur this is in scope as an educational institution and a university system parent entity.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04r9gvy43 in release v1.14.
