### ISSUE TITLE
Add a new organization to ROR: Pan African University Institute for Governance, Humanities and Social Sciences

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1442]
Summary of request: Add a new organization to ROR

Name of organization: Pan African University Institute for Governance, Humanities and Social Sciences
Website: 
Link to publications: 
Organization type: Education
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: PAU Institute for Governance, Humanities and Social Sciences
Acronym/abbreviation: PAUGHSS
Related organizations: https://ror.org/04r9gvy43 (parent)
City: Yaoundé
Country: Cameroon
Geonames ID: 2220957
Year established: 2002
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
As first identified in #1432, child institute of the Pan African University hosted at https://ror.org/041kdhz15. Funds and employs researchers. Solid affiliation usage. Should be added.

publication affiliation usage: https://doi.org/10.1007/s13132-022-00891-5; https://doi.org/10.1080/23311932.2021.1933745; https://openalex.org/W4225693624; https://doi.org/10.1111/1467-8268.12445; https://openalex.org/W4291225020; https://doi.org/10.1080/20421338.2020.1799545; https://doi.org/10.1080/20421338.2020.1796051; https://openalex.org/W4287749284; https://openalex.org/W4297727828

ORCID affiliation usage: https://orcid.org/0000-0002-7738-5004 ; https://orcid.org/0000-0002-7849-0156 ; https://orcid.org/0000-0001-9418-4282

**Comment by arthurpsmith** [comment]
Hi - this seems fine to add, however, all the affiliation usage that I saw said the location is Yaoundé, and not Buea. Where did you get Buea as a location? Is there a website reference on this at all?

**Comment by adambuttrick** [comment]
@arthurpsmith Mistake on my part. Thank you for catching!

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02ysyhv70 in release v1.14.
