### ISSUE TITLE
Modify the information in an existing ROR record: Concordia University https://ror.org/04dwckp88

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#14421]
Summary of request: Modify the information in an existing ROR record

Name of organization: Concordia University
ROR ID: https://ror.org/04dwckp88
Which part of the record needs to be changed? Status, Website
Description of change: The website for Concordia University in Portland no longer resolves, apparently because the organization closed in 2020 https://en.wikipedia.org/wiki/Concordia_University_(Oregon) 

Update: status.replace==inactive$

**Comment by adambuttrick** [comment]
Confirmed inactive.
