### ISSUE TITLE
Add a new organization to ROR: Pan African University Institute of Life and Earth Sciences 

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1444]
Summary of request: Add a new organization to ROR

Name of organization: Pan African University Institute of Life and Earth Sciences 
Website: https://pau-au.africa/institues/paulesi
Link to publications: 
Organization type: Education
Wikipedia page: 
Wikidata ID:
ISNI ID: 0000 0005 0260 8543
GRID ID:
Crossref Funder ID: 501100022496
Other names for the organization: 
Acronym/abbreviation: PAULESI
Aliases: PAU Institute of Life and Earth Sciences 
Labels: 
Related organizations: https://ror.org/03wx2rr30 (parent) https://ror.org/04r9gvy43 (parent)
City: Ibadan
Country: Nigeria
Geonames ID: 2339354
Year established: 2009
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
As first identified in https://github.com/ror-community/ror-updates/issues/1432, child institute of the Pan African University hosted at https://ror.org/041kdhz15. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.4103/npmj.npmj_16_17; https://doi.org/10.1080/21645515.2021.1963600; https://doi.org/10.1016/j.ejrh.2019.100654; https://doi.org/10.2166/wcc.2019.258; https://doi.org/10.1007/s40808-018-0479-0; https://doi.org/10.18203/2320-1770.ijrcog20171378; https://doi.org/10.1007/s12041-020-01216-8

ORCID affiliation usage: https://orcid.org/0000-0002-5423-7914 ; https://orcid.org/0000-0003-4575-7667 ; https://orcid.org/0000-0003-1962-0683

**Comment by arthurpsmith** [comment]
I added the ISNI - though that seems to have an incorrect city and country so maybe it's not the correct one? It has the same acronym PAULESI though. I would note that a lot of the affiliation usage includes "University of Ibadan" but I guess the fact that it has two parents qualifies it here. Anyway, this should be in ROR for the various reasons listed.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03r5zvp34 in release v1.14.
