### ISSUE TITLE
Modify the information in an existing ROR record: University of Ahl al-Bayt - https://ror.org/01h3hm524

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14452]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Ahl al-Bayt
ROR ID: https://ror.org/01h3hm524
Which part of the record needs to be changed? Names
Description of change: Name used by [org itself](http://www.abu.edu.iq/en) in English appears to be Ahl Al Bayt University*en
Also transliterated (e.g., [here](https://www.iasj.net/iasj/download/43a44b266becf669)) as Ahlulbait University*en
Add labels: جامعة أهل البيت*ar; دانشگاه اهل‌البیت*fa

Update: ror_display.replace==Ahl Al Bayt University*en | label.replace==Ahl Al Bayt University*en;  جامعة أهل البيت*ar; دانشگاه اهل‌البیت*fa | alias.add==University of Ahl al-Bayt*en; Ahlulbait University*en$

**Comment by adambuttrick** [comment]
Confirmed updates.
