### ISSUE TITLE
Modify the information in an existing ROR record: Hanoi Academy of Theater and Cinema - https://ror.org/02gswea15

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14451]
Summary of request: Modify the information in an existing ROR record

Name of organization: Hanoi Academy of Theater and Cinema
ROR ID: https://ror.org/02gswea15
Which part of the record needs to be changed? Alt names
Description of change: Existing label is missing two letters at the end, should be Trường Đại học Sân khấu và Điện ảnh Hà Nội*vi
Name is also rendered with a dash rather than "và" as in the affiliation in [this article](https://tapchiskda.vn/skda/article/view/71/42). Add Trường Đại học Sân khấu – Điện ảnh Hà Nội*vi

Update: label.replace==Hanoi Academy of Theater and Cinema*en; Trường Đại học Sân khấu và Điện ảnh Hà Nội*vi$

**Comment by adambuttrick** [comment]
Confirmed update.
