### ISSUE TITLE
Add a new organization to ROR: Pan African University Institute of Water and Energy Science

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1445]
Summary of request: Add a new organization to ROR

Name of organization: Pan African University Institute of Water and Energy Science
Website: https://pau-au.africa/institutes/pauwes
Link to publications: 
Organization type: Education
Wikipedia page:
Wikidata ID: Q18026629
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: PAU Institute of Water and Energy Science
Labels:
Acronym/abbreviation: PAUWES
Related organizations: https://ror.org/00jsjm362 (parent) https://ror.org/04r9gvy43 (parent)
City: Tlemcen
Country: Algeria
Geonames ID: 2475687
Year established: 2014
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by arthurpsmith** [comment]
Yes, clearly should be in ROR!

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04qe65e37 in release v1.14.
