### ISSUE TITLE
Add a new organization to ROR: Centre de Robotique

### ISSUE THREAD

**Issue by Hdubray** [ror-community/ror-updates#14487]
Summary of request: Add a new organization to ROR

Name of organization: Centre de Robotique*fr
Website: https://www.caor.minesparis.psl.eu
Domains: caor.minesparis.psl.eu
Link to publications: https://minesparis-psl.hal.science/ENSMP_CAOR/search/index/?q=*
Organization type: Facility; Education
Organization status: Active
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Centre for Robotics*en
Labels:  Mines Paris, Université PSL, Centre de Robotique (CAOR)*fr; Mines Paris, PSL University, Centre for Robotics (CAOR)*en
Acronym/abbreviation: CAOR*fr
Related organizations:  https://ror.org/04y8cs423 (parent)
City: Paris 
Country: France 
Geonames ID: 2988507
Year established: 1989
How will a ROR ID for this organization be used? 
The goal of a recording for this organization is to promote the Center for Robotic research, according to the new curated signature chart.
Other information about this request: You will find our signature charter attached to this request.

Thank you for your help !

Best regards,
[10963-2024-08-20_Note_Signatures_publications-2.pdf](https://github.com/user-attachments/files/17150267/10963-2024-08-20_Note_Signatures_publications-2.pdf)

Héloïse Dubray

**Comment by adambuttrick** [comment]
Research center in France. Funds and employs researchers. Solid affiliation usage. Should be added.
