### ISSUE TITLE
Add a new organization to ROR: Khyber Girls Medical College

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14494]
Summary of request: Add a new organization to ROR

Name of organization: Khyber Girls Medical College*en
Website: https://www.kgmc.edu.pk
Domains: kgmc.edu.pk
Link to publications: https://doi.org/10.53730/ijhs.v7nS1.14272 https://doi.org/10.1002/ccr3.9295 https://doi.org/10.52206/jsmc.2023.13.4.799
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Khyber_Girls_Medical_College
Wikidata ID: Q18388103
ISNI ID: 0000 0004 0522 6287
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: خیبر خواتین طبی کالج*ur; د خیبر ښځو طب پوهنځی*ps
Acronym/abbreviation: KGMC*en
Related organizations: 
City: Peshawar
Country: Pakistan
Geonames ID: 1168197
Year established: 2004
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Higher educational institution in Pakistan. Funds and employs researchers. Solid affiliation usage. Should be added.
