### ISSUE TITLE
Add a new organization to ROR: Daqing Oilfield Company Ltd Exploration and Development Research Institute

### ISSUE THREAD

**Issue by chougui0408** [ror-community/ror-updates#1453]
Summary of request: Add a new organization to ROR

Name of organization: Daqing Oilfield Company Exploration and Development Research Institute
Website: http://dqyt.cnpc.com.cn/dq/
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 1755 3226
GRID ID:
Crossref Funder ID:
Other names for the organization:
Acronym/abbreviation:
Aliases:
Labels: 大庆油田有限责任公司勘探开发研究院*Chinese
Related organizations:
City: Daqing
Country:China
Geonames ID: 2037860
Year established:1963
How will a ROR ID for this organization be used? Publish articles
Other information about this request:

**Comment by adambuttrick** [comment]
Research institute associated with Chinese petroleum company, Daqing Oilfield of CNPC. More extensive affiliation usage exists for the parent company using the English form "Daqing Oilfield Company" (e.g. : https://doi.org/10.1306/08031817416; https://doi.org/10.1016/j.marpetgeo.2008.01.008; https://doi.org/10.1016/j.bios.2015.06.020; https://doi.org/10.1016/j.earscirev.2016.05.004; https://doi.org/10.1111/j.1365-2117.2009.00445.x; https://doi.org/10.2118/121460-pa). 

Despite solid affiliation usage, I'm having difficulty verifying that this research institute exists separately from the company itself. Would appreciate other's thoughts here, although whatever the determination, we would still likely need to create the parent record.

Publication affiliation usage: https://doi.org/10.7623/syxb201501011; https://doi.org/10.1360/zd-2011-41-7-1000; https://doi.org/10.2118/186276-MS; https://doi.org/10.2118/200443-MS
; http://en.cnki.com.cn/Article_en/CJFDTOTAL-SYHH201103025.htm

**Comment by adambuttrick** [comment]
Per requestor comment on #1454, the research institute is a sub-entity of the company. Closing this and creating a ROR ID for the parent entity.
