### ISSUE TITLE
Add a new organization to ROR: Daqing Oilfield of CNPC

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1454]
Summary of request: Add a new organization to ROR

Name of organization: Daqing Oilfield of CNPC
Website: http://dqyt.cnpc.com.cn
Link to publications: 
Organization type: Company
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Aliases: Daqing Oilfield Company; Daqing Oilfield of China National Petroleum Corporation
Labels: 中国石油大庆油田*Chinese
Related organizations: https://ror.org/05269d038 (parent)
City: Daqing
Country: China
Geonames ID: 2037860
Year established: 1959
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Publication affiliation usage: https://doi.org/10.4028/www.scientific.net/amm.733.144; https://doi.org/10.1190/igc2018-419; https://doi.org/10.1111/jpg.12582; https://doi.org/10.3390/ijerph17093017; https://doi.org/10.2118/149082-ms; https://doi.org/10.1016/s1001-6058(16)60775-8; https://doi.org/10.1098/rsos.181634; https://doi.org/10.4028/www.scientific.net/amm.733.43; https://doi.org/10.1016/j.petrol.2019.106484; https://doi.org/10.4028/www.scientific.net/amm.733.784

**Comment by chougui0408** [comment]
Thank you very much! Exploration and Development Research Institute is belong to Daqing Oilfield of CNPC,  research institute is not exists separately from the company itsel. Excuse me, when can I find this organization on the Research Organization Registry https://ror.org.

**Comment by mariagould** [comment]
I concur that adding an entry for Daqing Oilfield of CNPC would be in scope given evidence of research activities and affiliation usage. 

As the above comment mentions and as @adambuttrick notes in #1453, the Exploration and Development Research Institute (captured in #1453) appears to be a subsidiary unit within Daqing Oilfield of CNPC so we should not create a separate entry.

**Comment by adambuttrick** [comment]
@chougui0408 No record yet exists for Daqing Oilfield of CNPC. We will publish a new record for it this week, so please follow this issue to be notified when it has been assigned a ROR ID.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03shhrx95 in release v1.12.
