### ISSUE TITLE
Modify the information in an existing ROR record: Oregon Department of Transportation

### ISSUE THREAD

**Issue by ptvrdy** [ror-community/ror-updates#14643]
Summary of request: Modify the information in an existing ROR record: Ohio DOT info is included in Oregon DOT API Response

Name of organization: Oregon Department of Transportation
ROR ID: https://ror.org/028tfkh72
Which part of the record needs to be changed?: Returns Ohio Department of Transportation ROR name and ID
Description of change: When searching the ROR API, the metadata return for "chosen": true is incorrect, includes Ohio and some Texas DOT info in other parts. You can see at the bottom that the chosen result returns Ohio DOT info (starts line 1447). The input search text is: "Oregon Department of Transportation"

[Oregeon DOT ROR API Response.json](https://github.com/user-attachments/files/17196375/Oregeon.DOT.ROR.API.Response.json)

**Comment by adambuttrick** [comment]
@ptvrdy Please report issues with ROR services in the [ror-roadmap repository](https://github.com/ror-community/ror-roadmap), including the exact details of the query. I'm not able to reproduce using our affiliation matching for the substring in the JSON:

https://api.ror.org/v2/organizations?affiliation="Oregon Department of Transportation"

https://api.ror.org/v2/organizations?affiliation=Oregon Department of Transportation
