### ISSUE TITLE
Add a new organization to ROR: Nordre Øyeren Bird Observatory

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#147]
Summary of request: Add a new organization to ROR

Name of organization: Nordre Øyeren Bird Observatory
Website: http://www.noef.no
Link to publications: http://www.noef.no/noefrapporter.php
Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/Q106653361
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: Nordre Øyeren Fuglestasjon
Acronym/abbreviation: NØF
Related organizations: 
City: Rælingen
Country: Norway
Other information about this request:

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04t667177 in release v1.0.
