### ISSUE TITLE
Project: Withdraw NFDI Consortia Records from v1.52

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#14719]
Relative to some internal concerns, the NFDI consortia have asked to withdraw the records added for them in v1.52 until such time as these issues can be resolved. A full list to be withdrawn is attached.
[20241001_NFDI_withdraw.csv](https://github.com/user-attachments/files/17217226/20241001_NFDI_withdraw.csv)

**Comment by adambuttrick** [comment]
Updated in release v1.53.

**Comment by cthoyt** [comment]
oh boy... this is a needle in the haystack situation.  with me luck

**Comment by cthoyt** [comment]
@adambuttrick I am still looking for the exact person, but I got the following sentiment:

> consortia are not legal entities and should not try to appear as such (due to tax reasons)

I don't think this is consistent with how ROR does curation, correct? Not all ROR IDs correspond to organizations that are distinct legal entities (and we can give many examples). Do you agree with this statement?

Honestly, it's pretty hard to understand from https://ror.org/about/faqs/#is-my-organization-in-scope-for-ror if this is correct or not, but https://ror.org/registry/#scope-and-criteria-for-inclusion gives a more relaxed definition which I think the NFDI consortia themselves should pass
