### ISSUE TITLE
Add a new organization to ROR: Ivy Enber Christian University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14715]
Summary of request: Add a new organization to ROR

Name of organization: Ivy Enber Christian University*en
Website: https://enberuniversity.com
Domains: enberuniversity.com
Link to publications: https://doi.org/10.55905/oelv22n9-127 https://doi.org/10.56238/sevened2024.006-012 https://doi.org/10.54033/cadpedv21n9-156
Organization type: Education
Organization status: Active
Wikipedia page: 
Wikidata ID:
ISNI ID: 0000 0004 9337 2304
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Enber*en; Enber University*en; Ivy Enber University*en
Labels:
Acronym/abbreviation:
Related organizations: 
City: Orlando
Country: United States
Geonames ID: 4167147
Year established: 2019
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
University in Orlando, Florida. Funds and employs researchers. Solid affiliation usage. Should be added.
