### ISSUE TITLE
Add a new organization to ROR: Faculty of Medicine of Tunis

### ISSUE THREAD

**Issue by BessemAamira** [ror-community/ror-updates#14734]
Summary of request: Add a new organization to ROR

Name of organization: Faculté de médecine de Tunis*fr
Website: https://fmt.rnu.tn
Domains: fmt.utm.tn
Link to publications: 
Organization type: Education
Organization status:
Wikipedia page: https://en.wikipedia.org/wiki/Medicine_School_of_Tunis
Wikidata ID: Q3064283
ISNI ID: 0000 0004 0401 0548
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Medicine School of Tunis*en
Labels: كلية الطب بتونس*ar; Faculty of Medicine of Tunis*en
Acronym/abbreviation: FMT
Related organizations: https://ror.org/029cgt552 (parent)
City: Tunis
Country: Tunisia
Geonames ID: 2464470
Year established: 1964
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by rileymmarsh** [comment]
Medical school in Tunisia. Funds and employs researchers. Solid affiliation usage. Should be added.
