### ISSUE TITLE
Add a new organization to ROR: Instituto Superior de Educación Normal del Estado de Colima, Profr. Gregorio Torres Quintero (ISENCO)

### ISSUE THREAD

**Issue by Christian-santos7** [ror-community/ror-updates#14746]
Summary of request: Add a new organization to ROR

Name of organization: Instituto Superior de Educación Normal del Estado de Colima "Profr. Gregorio Torres Quintero"*es
Website: http://www.isencolima.edu.mx
Domains: isencolima.edu.mx
Link to publications: 
Organization type: Education
Organization status:
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: ISENCO*es
Related organizations: 
City: Colima
Country: México
Geonames ID: 4013513
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Funds and employs researchers. Solid affiliation usage. Should be added.
