### ISSUE TITLE
Add a new organization to ROR: Engineering Biology Research Consortium

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14741]
Summary of request: Add a new organization to ROR

Name of organization: Engineering Biology Research Consortium*en
Website: https://ebrc.org
Domains: ebrc.org
Link to publications: https://doi.org/10.1002/bbb.2586 https://doi.org/10.1038/s44168-023-00089-8 https://doi.org/10.1021/acssynbio.1c00129
Organization type: Nonprofit
Organization status: Active
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation: EBRC*en
Related organizations: 
City: Emeryville
Country: United States
Geonames ID: 5346462
Year established: 2016
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Nonprofit in California. Funds and employs researchers. Solid affiliation usage. Should be added.
