### ISSUE TITLE
Add a new organization to ROR: Veni Creator Christian University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14759]
Summary of request: Add a new organization to ROR

Name of organization: Veni Creator Christian University*en
Website: https://ead.veniuniversity.com
Domains: veniuniversity.com
Link to publications: https://doi.org/10.1177/00219096231171540 https://doi.org/10.55905/cuadv16n8-033 https://doi.org/10.54033/cadpedv21n9-175
Organization type: Education
Organization status: Active
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Veni University*en
Labels:
Acronym/abbreviation: VCCU*en
Related organizations: 
City: Orlando
Country: United States
Geonames ID: 4167147
Year established: 2019
How will a ROR ID for this organization be used? 
Other information about this request: Also appears to be an online Brazilian uni based in Florida.

**Comment by adambuttrick** [comment]
Funds and employs researchers. Solid affiliation usage. Should be added.
