### ISSUE TITLE
Add a new organization to ROR: Al Fajr College of Science and Technology

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14764]
Summary of request: Add a new organization to ROR

Name of organization: Al Fajr College of Science and Technology*en
Website: https://fajr.edu.sd
Domains: fajr.edu.sd
Link to publications: https://doi.org/10.1002/brb3.2495 http://doi.org/10.5530/097483261402 https://doi.org/10.51847/Ce9m7Yp4rC
Organization type: Education
Organization status: Active
Wikipedia page:
Wikidata ID: Q130408985
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Alfajr College for Sciences & Technology*en; Fajr College*en; Al-Fajr College*en
Labels: كلية الفجر للعلوم والتكنولوجيا*ar
Acronym/abbreviation:
Related organizations: 
City: Khartoum
Country: Sudan
Geonames ID: 379252
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Funds and employs researchers. Solid affiliation usage. Should be added.
