### ISSUE TITLE
Modify the information in an existing ROR record: 
Institute of Plant Genetics and Crop Plant Research (https://ror.org/02skbsp27)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#148]
Summary of request: Modify the information in an existing ROR record

Name of organization: Institute of Plant Genetics and Crop Plant Research
ROR ID: https://ror.org/02skbsp27
Which part of the record needs to be changed? Primary name
Description of change: Please change the organisation name to: Leibniz Institute of Plant Genetics and Crop Plant Research (IPK)

Reviewer recommendation:
1) Change primary name to Leibniz Institute of Plant Genetics and Crop Plant Research
2) Add the current name (without Leibniz) as an alias
Note that we already have IPK as acronym so nothing needs to be done regarding that part of the name.

Update: change.name==Leibniz Institute of Plant Genetics and Crop Plant Research; add.aliases==Institute of Plant Genetics and Crop Plant Research;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
