### ISSUE TITLE
Add a new organization to ROR: Faculté des Lettres et des Sciences Humaines de Sfax

### ISSUE THREAD

**Issue by BessemAamira** [ror-community/ror-updates#14860]
Summary of request: Add a new organization to ROR

Name of organization: Faculté des Lettres et des Sciences Humaines de Sfax*fr
Website: https://flshs.rnu.tn
Domains: flshs.rnu.tn
Link to publications: [10.4236/jss.2019.710018](https://doi.org/10.4236/jss.2019.710018), [10.4236/ce.2015.612134](http://dx.doi.org/10.4236/ce.2015.612134), [10.4236/psych.2015.68091](http://dx.doi.org/10.4236/psych.2015.68091), [10.4236/ce.2015.612136](http://dx.doi.org/10.4236/ce.2015.612136)
Organization type: Education
Organization status:
Wikipedia page: https://ar.wikipedia.org/wiki/%D9%83%D9%84%D9%8A%D8%A9_%D8%A7%D9%84%D8%A2%D8%AF%D8%A7%D8%A8_%D9%88%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85_%D8%A7%D9%84%D8%A5%D9%86%D8%B3%D8%A7%D9%86%D9%8A%D8%A9_%D8%A8%D8%B5%D9%81%D8%A7%D9%82%D8%B3
Wikidata ID: Q12235867
ISNI ID: 0000 0001 0668 5715
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: University of Arts and Human Sciences of Sfax*en; Faculty of Letters and Humanities of Sfax*en; Université de Sfax Faculté des Lettres et des Sciences humaine*fr; Faculty of Human Sciences of Sfax*en
Labels: كلية الآداب والعلوم الإنسانية بصفاقس*ar
Acronym/abbreviation: FLSHS*en
Related organizations: https://ror.org/04d4sd432 (parent)
City: Sfax
Country: Tunisia
Geonames ID: 2467454
Year established: 1978
How will a ROR ID for this organization be used? 
Other information about this request: To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
Structure of https://ror.org/04d4sd432 is somewhat confusing, as some of its constituent units are discrete organization (e.g. its engineering school and medical faculty), but it is not clear to what extent this is true for all. Would appreciate a second review here or if the requestor could clarify as well, preferably with official documentation that enumerates if this is a discrete legal or accredited entity.

**Comment by ABES-cmc** [comment]
Had a look at legal documentation provided in French ( https://www.pist.tn/jort/1987/1987F/Jo06987.pdf is the official publication for legal bodies in Tunisia, very similar to the Journal Officiel in France). 
To my understanding, the "établissements" participating in a university in Tunisia are legally distinct. They can be called "faculté", "école" or "insitut supérieur". The Faculté de médecine de Sfax for example has been created in 1974, and the Université de Sfax has been created afterwards in 1986 (https://uss.rnu.tn/page/presentation_universite). Public universities in Tunisia look rather like a formal unit that gathers several autonomous institutions, mostly on a geographical basis. 
Would recommand the creation of distinct records, with a relation of University of Sfax (https://ror.org/04d4sd432) as parent.
