### ISSUE TITLE
Modify the information in an existing ROR record: 
Répertoire International des Sources Musicales (https://ror.org/01kk1vy78)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#149]
Summary of request: Modify the information in an existing ROR record

Name of organization: Répertoire International des Sources Musicales
ROR ID: https://ror.org/01kk1vy78
Which part of the record needs to be changed? Primary name, Organization website, Other IDs for the organization

Description of change: Since 2021, our organization has a new name and a new website. 

- Primary name: "RISM Digital Center"
- Organization website: "https://rism.digital/"
- Please delete the ISNI number 0000000404558378, because it refers to a different organization (the RISM Editorial Center in Frankfurt, Germany).

Reviewer note: we can also add Wikidata ID: Q33121097

**Comment by carlyrobinson** [comment]
Agree with the recommended updates.
