### ISSUE TITLE
Modify the information in an existing ROR record: Berkeley Brewing Science - https://ror.org/0341q1641

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#14991]
Summary of request: Modify the information in an existing ROR record

Name of organization: Berkeley Brewing Science
ROR ID: https://ror.org/0341q1641
Which part of the record needs to be changed? Name, URL, Wikidata
Description of change: Org name [changed](https://ipira.berkeley.edu/berkeley-yeast) at some point in the last several years. 
Update name to Berkeley Yeast*en
Add alias Berkeley Brewing Science*en
Update URL to https://berkeleyyeast.com/
Add domain berkeleyyeast.com
Add Wikidata Q43895610

Update: ror_display.replace==Berkeley Yeast*en | label.replace==Berkeley Yeast*en | alias.replace==Berkeley Brewing Science*en | website.replace==https://berkeleyyeast.com | domains.add==berkeleyyeast.com | wikidata.preferred.replace==Q43895610 | wikidata.all.add==Q43895610$

**Comment by adambuttrick** [comment]
Confirmed update.
