### ISSUE TITLE
Modify Wigner Research Centre for Physics (https://ror.org/035dsb084)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#150]
Summary: Modify an existing organization in ROR

Name of organization: Wigner Research Centre for Physics
ROR ID: https://ror.org/035dsb084
Description of change: We realized that the entry has an incorrect link to the Wikidata. The appropriate one is Q1161072.
Update: delete.Wikidata==Q1161068; add.Wikidata==Q1161072;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
