### ISSUE TITLE
Modify the information in an existing ROR record:  Slovenian Institute for Hop Growing and the Brewing https://ror.org/00vywdr32

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#15013]
Summary of request: Modify the information in an existing ROR record

Name of organization: Slovenian Institute for Hop Growing and the Brewing
ROR ID: https://ror.org/00vywdr32
Which part of the record needs to be changed? Names ror-display, Types
Description of change: The English (ror-display) name should be "Slovenian Institute for Hop Growing and Brewing." Also the type of organization should be reviewed: is it a facility?

Update: ror_display.replace==Slovenian Institute of Hop Research and Brewing*en | label.replace==Slovenian Institute of Hop Research and Brewing*en; Inštitut za hmeljarstvo in pivovarstvo Slovenije*sk | alias.add==Slovenian Institute for Hop Growing and Brewing*en; Slowenisches Insttut fur Hopfenbau und Brauereiwesen*de | website.replace==https://www.ihps.si | acronyms.add==IHPS*sk | domains.add==ihps.si | isni.preferred.replace==0000 0004 0459 1549 | isni.all.add==0000 0004 0459 1549 | wikidata.preferred.replace==Q30299318 | wikidata.all.add==Q30299318$

**Comment by adambuttrick** [comment]
English form on site uses "of" (vs. for), so updating to reflect and remove the errant "the." Almost all institutes in ROR are tagged as facilities, so the type is fine as is.

**Comment by adambuttrick** [comment]
Record updated in in release v1.55.
