### ISSUE TITLE
Add a new organization to ROR: National Institute of Textile Engineering and Research

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15017]
Summary of request: Add a new organization to ROR

Name of organization: National Institute of Textile Engineering and Research*en
Website: https://niter.edu.bd
Domains: niter.edu.bd
Link to publications: https://doi.org/10.1109/ICCCNT54827.2022.9984443 https://doi.org/10.4236/jtst.2021.74014 https://doi.org/10.1007/s42452-021-04582-9
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/National_Institute_of_Textile_Engineering_and_Research
Wikidata ID: Q16895693
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: Textile Industry Development Centre*en; National Institute of Textile Training Research and Design*en
Aliases:
Labels: জাতীয় বস্ত্র প্রকৌশল ও গবেষণা ইনস্টিটিউট*bn
Acronym/abbreviation: NITER*en; TIDC*en; NITTRAD*en
Related organizations: https://ror.org/05wv2vq37 (related)
City: Savar
Country: Bangladesh
Geonames ID: 1349452
Year established: 1979
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
State research institute in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
