### ISSUE TITLE
Add a new organization to ROR: Sheikh Hasina University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15015]
Summary of request: Add a new organization to ROR

Name of organization: Sheikh Hasina University*en
Website: https://www.shu.edu.bd
Domains: shu.edu.bd
Link to publications: https://doi.org/10.1109/ICCCNT54827.2022.9984443 https://doi.org/10.3389/fpsyt.2022.804162 https://doi.org/10.3390/math11081921
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Sheikh_Hasina_University
Wikidata ID: Q29015031
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Sheikh Hasina University, Netrokona*en
Labels: শেখ হাসিনা বিশ্ববিদ্যালয়*bn
Acronym/abbreviation: SHU*en
Related organizations: 
City: Netrokona
Country: Bangladesh
Geonames ID: 1185116
Year established: 2018
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
