### ISSUE TITLE
Modify the information in an existing ROR record: IE University - https://ror.org/02jjdwm75

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15046]
Summary of request: Modify the information in an existing ROR record

Name of organization: IE University
ROR ID: https://ror.org/02jjdwm75
Which part of the record needs to be changed? Labels, alias
Description of change: per [Wikipedia](https://en.wikipedia.org/wiki/IE_University), add label IE Universidad*es
Add alias Universidad Instituto de Empresa*es

Update: label.add==IE Universidad*es | alias.add==Universidad Instituto de Empresa*es$

**Comment by adambuttrick** [comment]
Confirmed updates.
