### ISSUE TITLE
Add a new organization to ROR: Topfaith University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15082]
Summary of request: Add a new organization to ROR

Name of organization: Topfaith University*en
Website: https://topfaith.edu.ng/
Domains: topfaith.edu.ng
Link to publications: https://doi.org/10.4018/979-8-3693-1347-3.ch004 https://doi.org/10.9734/ajopacs/2023/v11i2200 https://doi.org/10.4236/jss.2024.127027
Organization type: Education
Organization status: Active
Wikipedia page:
Wikidata ID: Q115869757
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels:
Acronym/abbreviation:
Related organizations: 
City: Mkpatak
Country: Nigeria
Geonames ID: 2330057
Year established: 2021
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Nigeria. Funds and employs researchers. Solid affiliation usage. Should be added.
