### ISSUE TITLE
Add a new organization to ROR: INFN Amministrazione Centrale

### ISSUE THREAD

**Issue by rileymmarsh** [ror-community/ror-updates#15124]
Summary of request: Add a new organization to ROR

Name of organization: Istituto Nazionale di Fisica Nucleare, Amministrazione Centrale*it
Website: https://www.ac.infn.it
Domains: ac.infn.it
Link to publications: 
Organization type: Government
Organization status:
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: INFN Amministrazione Centrale*it
Labels:
Acronym/abbreviation: INFN-AC*it
Related organizations: https://ror.org/005ta0471 (parent)
City: Frascati
Country: Italy
Geonames ID: 3176589
Year established:
How will a ROR ID for this organization be used? 
Other information about this request: Part of project https://github.com/ror-community/ror-updates/issues/14219

**Comment by rileymmarsh** [comment]
Administrative division that does not deal with research. Unsure if this is within scope for ROR.

**Comment by adambuttrick** [comment]
This is fine to add as an Italian state organization that coordinates the other units research activities.
