### ISSUE TITLE
Add a new organization to ROR: St. Aloysius (Deemed to Be University)

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15130]
Summary of request: Add a new organization to ROR

Name of organization: St. Aloysius (Deemed to Be University)*en
Website: https://staloysius.edu.in
Domains: staloysius.edu.in
Link to publications: https://doi.org/10.1007/s13197-024-05965-7 https://doi.org/10.1109/ICAIT61638.2024.10690387 https://doi.org/10.53555/kuey.v30i5.4635
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/St._Aloysius,_Mangalore
Wikidata ID: Q16899555
ISNI ID: 0000 0001 2289 6643
GRID ID:
Crossref Funder ID:
Other names for the organization: St. Aloysius College*en
Aliases: St. Aloysius, Mangalore*en; Saint Aloysius*en
Labels:
Acronym/abbreviation:
Related organizations: 
City: Mangalore
Country: India
Geonames ID: 1263780
Year established: 1880
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Funds and employs researchers. Solid affiliation usage. Should be added.
