### ISSUE TITLE
Modify the information in an existing ROR record: Osh Technological University - https://ror.org/009vyzb24

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15199]
Summary of request: Modify the information in an existing ROR record

Name of organization: Osh Technological University
ROR ID: https://ror.org/009vyzb24
Which part of the record needs to be changed? Alt names
Description of change: Per https://doi.org/10.1063/5.0145469 and https://doi.org/10.5281/zenodo.10047921: Add aliases:
Osh Technological University named after M.M. Adysheva*en
Osh Technological University named after acad. MM. Adysheva*en

Update: alias.add==Osh Technological University named after M.M. Adysheva*en; Osh Technological University named after acad. MM. Adysheva*en$

**Comment by adambuttrick** [comment]
Confirmed updates.
