### ISSUE TITLE
Modify Institute of Non-Ferrous Metals (https://ror.org/025ghn770)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#152]
Summary: Modify the information in an existing ROR record
Name of organization: Instytut Metali Nieżelaznych (Institute of Non-Ferrous Metals) 
ROR ID: https://ror.org/025ghn770
Description of change: Instytut Metali Nieżelaznych (Institute of Non-Ferrous Metals) in Gliwice has been transformed into an Institute of the Network operating under the name „Sieć Badawcza Łukasiewicz – Instytut Metali Nieżelaznych"

--
Curator recommendation (MG):

- Change primary name from `Institute of Non-Ferrous Metals` to `Łukasiewicz Research Network - Institute of Non-Ferrous Metals`
- Move alias to language label field with Polish code `pl` and update Polish name to `Sieć Badawcza Łukasiewicz – Instytut Metali Nieżelaznych`

Update: change.name==Łukasiewicz Research Network - Institute of Non-Ferrous Metals; delete.aliases==Instytut Metali Nieżelaznych w Gliwicach; add.labels==Sieć Badawcza Łukasiewicz – Instytut Metali Nieżelaznych*Polish; add.Wikidata==Q11713121; add.wikipedia_url==https://pl.wikipedia.org/wiki/Instytut_Metali_Nieżelaznych;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
