### ISSUE TITLE
Add a new organization to ROR: Toplica Academy of Applied Studies

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15275]
Summary of request: Add a new organization to ROR

Name of organization: Toplica Academy of Applied Studies*en
Website: https://toplicka.edu.rs
Domains: toplicka.edu.rs
Link to publications: https://doi.org/10.46793/ICEMIT23.017P https://doi.org/10.3390/su15064780 https://doi.org/10.5937/str2201027L
Organization type: Education
Organization status: Active
Wikipedia page: 
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Toplica Academy Professional Studies*en; Toplica Academy of Vocational Studies*en; Toplička akademija strukovnih studija*sr
Labels: Топличка академија струковних студија*sr
Acronym/abbreviation: TAAS*en
Related organizations: 
City: Prokuplje
Country: Serbia
Geonames ID: 786690
Year established: 2022
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Publication affiliation usage: Toplica Academy of Applied Studies: https://doi.org/10.46793/icemit23.129d, https://doi.org/10.5281/zenodo.7479788, https://doi.org/10.2298/apt2354301r, https://doi.org/10.1109/icetran62308.2024.10645091, https://doi.org/10.5937/bizinfo2301077g, https://doi.org/10.5937/bizinfo2302121a, https://doi.org/10.1007/s10462-023-10436-0, https://doi.org/10.46793/icemit23.189d, https://doi.org/10.5937/bizinfo2302047d, https://doi.org/10.5937/pomc19-41863 | Toplica Academy Professional Studies: https://doi.org/10.3390/su151310501, https://doi.org/10.55302/jafes22767036v, https://doi.org/10.3390/su15064780 | Toplica Academy of Vocational Studies: https://doi.org/10.55302/jafes22764071s, https://doi.org/10.5937/str2201027l, https://doi.org/10.15308/finiz-2022-32-38, https://doi.org/10.5937/zrpfn1-40481, https://doi.org/10.5937/ekonomika2302013m, https://doi.org/10.5937/str2302042l, https://doi.org/10.55302/jafes22767041r, https://doi.org/10.18485/ecologica.2023.30.109.17 | Toplička akademija strukovnih studija: https://doi.org/10.7251/blczr0623309d, https://doi.org/10.5937/medrec2301016s, https://doi.org/10.5937/trendpos2301007j, https://doi.org/10.5937/tehnika2302215d, https://doi.org/10.56362/rev23102025m, https://doi.org/10.5937/medrec2203072z, https://doi.org/10.5937/medrec2203083s, https://doi.org/10.5937/pomc20-44841, https://doi.org/10.18485/ecologica.2023.30.109.17, https://doi.org/10.5937/medrec2203076a
Potential aliases: Toplica Academy of Applied Studies; Toplica Academy Professional Studies; Toplica Academy of Vocational Studies; Toplička akademija strukovnih studija
ORCID affiliation usage: https://orcid.org/0009-0008-8145-7542; https://orcid.org/0009-0007-1352-8962; https://orcid.org/0000-0002-9345-2422; https://orcid.org/0009-0008-4431-3689; https://orcid.org/0000-0002-0069-2516
Previous requests: https://github.com/ror-community/ror-updates/issues/15275
Geonames match: Prokuplje | Geonames ID: [ 786690](https://www.geonames.org/786690)

**Comment by rileymmarsh** [comment]
Vocational school in Serbia. Funds and employs researchers. Solid affiliation usage. Should be added.
