### ISSUE TITLE
Modify Industrial Institute of Agricultural Engineering (https://ror.org/05qczcd66)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#153]
Summary: Modify the information in an existing ROR record
ROR ID: https://ror.org/05qczcd66
Description of change:
Change of the name of the organization. 
Website: pimr.lukasiewicz.gov.pl

--
Curator recommendation (MG):
- Change primary name to `Łukasiewicz Research Network - Industrial Institute of Agricultural Engineering`
- Move alias to language label field with Polish code `pl` and update Polish name to `Sieć Badawcza Łukasiewicz - Przemysłowy Instytut Maszyn Rolniczych`
- Change website to https://pimr.lukasiewicz.gov.pl 

Update: change.name==Łukasiewicz Research Network - Industrial Institute of Agricultural Engineering; add.labels==Sieć Badawcza Łukasiewicz - Przemysłowy Instytut Maszyn Rolniczych*Polish; delete.aliases==Przemysłowy Instytut Maszyn Rolniczych; delete.links==http://www.pimr.poznan.pl/; add.links==https://pimr.lukasiewicz.gov.pl; add.Wikidata==Q30261196;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
