### ISSUE TITLE
Modify the information in an existing ROR record: 02a0fwv66 American Institute of Mathematics

### ISSUE THREAD

**Issue by kmccurley** [ror-community/ror-updates#15317]
Summary of request: Modify the information in an existing ROR record

Name of organization: American Institute of Mathematics
ROR ID: https://ror.org/02a0fwv66
Which part of the record needs to be changed? `locations`
Description of change:
The institute has moved twice since their location was original recorded in Palo Alto. They are now located on the campus of Caltech University in Pasadena, California. The geonames ID for this location can be found here: https://www.geonames.org/6331816/california-institute-of-technology.html so I believe the correct entry would have
```
"locations" : [
  {
     "geonames_id": 6331816,
     "geonames_details": {
         "country_code": "US",
         "country_name": "United States",
         "lat": 34.13794,
         "lng": -118.12574,
         "name": "California Institute of Technology"
  }
]
```
Everything else is unchanged. You can verify the location from their [website](https://aimath.org/).

Update: geonames.replace==5381396$

**Comment by rileymmarsh** [comment]
Update: geonames.replace==6331816$

**Comment by adambuttrick** [comment]
For locations, the most granular level of location we encode that of the city in which the organization is located. For the sake of consistency, we unfortunately can't make use of organization-specific location records, as they are of unknown provenance in Geonames and not all records have these values. So, we can update to use Pasadena (Geonames ID: 5381396).
