### ISSUE TITLE
Add a new organization to ROR: Universitas Ibnu Sina

### ISSUE THREAD

**Issue by ropianto** [ror-community/ror-updates#15321]
Summary of request: Add a new organization to ROR

Name of organization: Universitas Ibnu Sina*id
Website: http://uis.ac.id
Domains: uis.ac.id
Link to publications: 
Organization type: Education; Funder
Organization status: 
Wikipedia page: https://id.wikipedia.org/wiki/UNIVERSITAS_IBNU_SINA
Wikidata ID: Q109913120
ISNI ID: 0000 0005 1089 9037
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: Ibnu Sina University*en
Acronym/abbreviation: UIS*id
Related organizations: 
City: Kota Batam
Country: Indonesia
Geonames ID: 9849917
Year established: 2019
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by ropianto** [comment]
Summary of request: Add a new organization to ROR

Name of organization: Universitas Ibnu Sina
Website: http://uis.ac.id/
Domains: uis.ac.id
Link to publications:
Organization type: Education, Funder
Organization status:
Wikipedia page: https://id.wikipedia.org/wiki/UNIVERSITAS_IBNU_SINA
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: Universitas Ibnu Sina (uis)
Acronym/abbreviation: UIS
Related organizations:
City: Batam
Country: Indonesia
Geonames ID:
Year established:
How will a ROR ID for this organization be used?
Other information about this request:

**Comment by rileymmarsh** [comment]
University in Indonesia. Funds and employs researchers. Solid affiliation usage. Should be added.
