### ISSUE TITLE
Modify the information in an existing ROR record: Happy Plating (Austria) - https://ror.org/05cxx5e41

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15333]
Summary of request: Modify the information in an existing ROR record

Name of organization: Happy Plating (Austria)
ROR ID: https://ror.org/05cxx5e41
Which part of the record needs to be changed? Names, URL, relationships, location.
Description of change: Changed name to Hirtenberger Engineered Surfaces GmbH around 2015, then was bought and rebranded by RENA in 2020.
Update name: RENA Technologies Austria*en
Add aliases: RENA Technologies GmbH Austria*en; Hirtenberger Engineered Surfaces GmbH*en; Happy Plating GmbH*en
URL: https://www.rena.com/en/company/rena-austria
Relationship: https://ror.org/00j5nrv77 (parent)
City: Wiener Neustadt
Geonames: 2761353

Update: ror_display.replace==RENA Technologies Austria GmbH (Austria)*en | label.replace==RENA Technologies Austria GmbH (Austria)*en; RENA Technologies Austria GmbH*en | alias.add==RENA Technologies Austria*en; RENA Austria*en; Hirtenberger Engineered Surfaces GmbH*en; Happy Plating GmbH*en | website.replace==https://www.rena.com/en/company/rena-austria | geonames.replace==2761353$

Related organizations: https://ror.org/00j5nrv77 (parent)

**Comment by rileymmarsh** [comment]
Update: ror_display.replace==RENA Technologies Austria | label.replace==RENA Technologies Austria | alias.add==Hirtenberger Engineered Surfaces GmbH; Happy Plating GmbH | website.replace==https://www.rena.com/en/company/rena-austria | geonames.replace==2761353$
