### ISSUE TITLE
Add a new organization to ROR: Sunamganj Science and Technology University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15346]
Summary of request: Add a new organization to ROR

Name of organization: Sunamganj Science and Technology University*en
Website: https://sstu.ac.bd
Domains: sstu.ac.bd
Link to publications: https://doi.org/10.1007/s11082-024-07172-2 https://doi.org/10.4236/msa.2024.159021 https://doi.org/10.1155/2024/6420467
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Sunamganj_Science_and_Technology_University
Wikidata ID: Q83831881
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: সুনামগঞ্জ বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়*bn
Acronym/abbreviation: SSTU*en
Related organizations: 
City: Sunamganj
Country: Bangladesh
Geonames ID: 1185105
Year established: 2020
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Wikidata Name: Sunamganj Science and Technology University
Wikidata ID: Q83831881
Wikidata name match ratio: 100
wikipedia_url: https://en.wikipedia.org/wiki/Sunamganj_Science_and_Technology_University
Wikidata Established: 2020
Wikidata Country: Bangladesh
Publication affiliation usage: Sunamganj Science and Technology University: https://doi.org/10.1016/j.padiff.2024.100765, https://doi.org/10.1016/j.padiff.2024.100615, https://doi.org/10.1016/j.ibmed.2024.100149, https://doi.org/10.1007/s11082-024-07172-2, https://doi.org/10.1016/j.rinp.2022.106095
Potential aliases: Sunamganj Science and Technology University
ORCID affiliation usage: https://orcid.org/0009-0009-5587-8359
Previous requests: https://github.com/ror-community/ror-updates/issues/15346
Geonames match: Sunamganj | Geonames ID: [ 1337188](https://www.geonames.org/1337188)

**Comment by rileymmarsh** [comment]
University in Bangladesh. Funds and employs researchers. Solid affiliation usage. Should be added.
