### ISSUE TITLE
Add a new organization to ROR: Centre de Mathématiques Appliquées 

### ISSUE THREAD

**Issue by Hdubray** [ror-community/ror-updates#15364]
Summary of request: Add a new organization to ROR

Name of organization: Centre de Mathématiques Appliquées - CMA*fr
Website: https://www.cma.mines-paristech.fr
Domains: cma.mines-paristech.fr
Link to publications: https://minesparis-psl.hal.science/ENSMP_CMA/search/index/?q=*
Organization type: Facility; Education
Organization status: Active
Wikipedia page: 
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Centre de Mathématiques Appliquées*fr; Centre for Applied Mathematics*en; Center for Applied Mathematics*en
Labels: Centre for Applied Mathematics - CMA*en; Mines Paris, Université PSL, Centre de Mathématiques Appliquées (CMA)*fr; Mines Paris, PSL University, Centre for Applied Mathematics (CMA)*en
Acronym/abbreviation: CMA*fr
Related organizations: 
City: Sophia Antipolis
Country: France 
Geonames ID: 6640252
Year established: 1976
How will a ROR ID for this organization be used? 
The goal of a recording for this organization is to promote the Center for Applied Mathematics, according to the new curated signature chart, validated by our research director. 
Other information about this request:
You will find the signature chart attached to this request. 
[10963-2024-08-20_Note_Signatures_publications-4.pdf](https://github.com/user-attachments/files/17649959/10963-2024-08-20_Note_Signatures_publications-4.pdf)

**Comment by Hdubray** [comment]
Hello,
A quick note to inform you that I edited my request : It is not necessary to add https://ror.org/04y8cs423 (Université PSL) as a parent organisation.
Best regards.
Héloïse Dubray

**Comment by rileymmarsh** [comment]
Hello @Hdubray. I have a question regarding the names in your requests (https://github.com/ror-community/ror-updates/issues/15482; https://github.com/ror-community/ror-updates/issues/15374; https://github.com/ror-community/ror-updates/issues/15373; https://github.com/ror-community/ror-updates/issues/15372; https://github.com/ror-community/ror-updates/issues/15364). Labels represent official names for the organization. Would the full name you've provided be the official name (label) for the organization, i.e. "Mines Paris, Université PSL, Centre de Mathématiques Appliquées (CMA)"? Or is it just an additional/alternate name (alias)? In this request, I have these long forms of the name as aliases, but if they are official, legal names, I can add the French and English versions to labels. I am unable to open the link in https://github.com/ror-community/ror-updates/issues/15356 to confirm as it appears to be an internal document.

**Comment by Hdubray** [comment]
Hello,
Thank you for reaching out, I misunderstood the difference between both cathegories of names. If possible, you can put all the names provided as official names (labels). 
I attached to this comment the signature charter of our school (the internal document linked in #15356)

Best regards, 

Héloïse Dubray
[10963-2024-08-20_Note_Signatures_publications-3.pdf](https://github.com/user-attachments/files/17831083/10963-2024-08-20_Note_Signatures_publications-3.pdf)

**Comment by rileymmarsh** [comment]
Thank you for the clarification!

**Comment by rileymmarsh** [comment]
Research center in France. Funds and employs researchers. Solid affiliation usage. Should be added.
