### ISSUE TITLE
Add a new organization to ROR: Centre d'Economie Industrielle

### ISSUE THREAD

**Issue by Hdubray** [ror-community/ror-updates#15374]
Summary of request: Add a new organization to ROR

Name of organization: Centre d’Economie Industrielle - CERNA*fr
Website: https://www.cerna.minesparis.psl.eu
Domains: cerna.minesparis.psl.eu
Link to publications: https://minesparis-psl.hal.science/ENSMP_CERNA/search/index/?q=*
Organization type: Facility; Education
Organization status: Active
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Centre d'Economie Industrielle*fr; Centre for industrial economics*en; Center for industrial economics*en; UMR 9217; i3 UMR CNRS 9217; Centre d'économie industrielle i3*fr
Labels: Centre for industrial economics - CERNA*en; Mines Paris, Université PSL, Centre d’Economie Industrielle (CERNA), i3 UMR9217 CNRS*fr; Mines Paris, PSL University, Centre for industrial economics (CERNA), i3 UMR9217 CNRS*en
Acronym/abbreviation: CERNA*fr; CERNA i3*fr
Related organizations: https://ror.org/04y8cs423 (parent) https://ror.org/01naq7912 (parent) https://ror.org/05hy3tk52 (parent) https://ror.org/02feahw73 (parent)
City: Paris
Country: France 
Geonames ID: 2988507
Year established: 2009
How will a ROR ID for this organization be used? 
The goal of a recording for this organization is to promote the CERNA, according to the new curated signature chart, validated by our research director. 
Other information about this request:
You will find attached to this request the signature chart of our school. 
[10963-2024-08-20_Note_Signatures_publications-4.pdf](https://github.com/user-attachments/files/17662964/10963-2024-08-20_Note_Signatures_publications-4.pdf)

**Comment by rileymmarsh** [comment]
Research center in France. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by Hdubray** [comment]
Hello, 
I edited the label line : a letter was missing "Centre for industrial economics - CERNA*en" and not "CERN".

Have a nice day !

Héloïse Dubray
