### ISSUE TITLE
Modify the information in an existing ROR record: Debapriya Mukhopadhyay Vision Research Institute and Foundation

### ISSUE THREAD

**Issue by imdebapriya** [ror-community/ror-updates#15377]
Summary of request: Modify the information in an existing ROR record

Name of organization: Debapriya Mukhopadhyay Vision Research Institute and Foundation
ROR ID: https://ror.org/04yg9zd47
Which part of the record needs to be changed?
Description of change: Need to add 
WIKIDATA ID:  [Q131010034](https://www.wikidata.org/wiki/Q131010034)
Ringgold ID: 704205
<img width="1074" alt="Screenshot 2024-11-07 at 9 06 21 PM" src="https://github.com/user-attachments/assets/03fd7aea-7178-4abc-961e-f9ec5e3d39be">
<img width="1426" alt="Screenshot 2024-11-07 at 9 16 51 PM" src="https://github.com/user-attachments/assets/251ca290-ae3e-47e1-97b0-b99bb3a7e5cf">

Following comment on #15090

Update: wikidata.add.all==Q131010034 | wikidata.preferred.replace==Q131010034$

**Comment by rileymmarsh** [comment]
Added Wikidata ID, but we do not support Ringgold ID.
