### ISSUE TITLE
Modify the information in an existing ROR record: https://ror.org/0329ynx05

### ISSUE THREAD

**Issue by tilfischer** [ror-community/ror-updates#15371]
Summary of request: Modify the information in an existing ROR record

Update record: 
Name of organization: German Federal Environment Agency
ROR ID: https://ror.org/0329ynx05
Which part of the record needs to be changed? English name of organization.
Description of change: ``Federal`` needs to be removed from the name, see [UBA web page on Corporate Design](https://www.umweltbundesamt.de/dokument/corporate-design-des-umweltbundesamtes) and the [PDF](https://www.umweltbundesamt.de/sites/default/files/medien/1410/dokumente/2019_uba_manual_screen.pdf) linked on that page  on page 18, which states ``German Environment Agency``

JSON snippet of updated record would look like this:

```
{
    ...
    "names": [
        {
            "lang": "en",
            "types": [
                "ror_display",
                "label"
            ],
            "value": "German Environment Agency"
        },
    ],
...
}
```
Best

Update: ror_display.replace==German Environment Agency*en | label.replace==German Environment Agency*en; Umweltbundesamt*de | alias.add==German Federal Environment Agency*en | website.replace==https://www.umweltbundesamt.de | domains.add==umweltbundesamt.de$

**Comment by tilfischer** [comment]
@rileymmarsh : Thank you for your reply. I have seen your edit of my post

``
Update: ror_display.replace==German Environment Agencyen | label.replace==German Environment Agencyen; Umweltbundesamtde | alias.add==German Federal Environment Agencyen | website.replace==https://www.umweltbundesamt.de/ | domains.add==umweltbundesamt.de$
``

Is ``Agencyen`` a typo? The English name of the organisation is ``German Environment Agency``. The German name of the organisation is ``Umweltbundesamt``.

Best

**Comment by rileymmarsh** [comment]
Hello @tilfischer the "en" at the end of "German Environment Agency" is a language tag for English and "de" at the end of "Umweltbundesamt" is the language tag for German.
