### ISSUE TITLE
Add a new organization to ROR: Institut Supérieur d’Ingéniérie et de Gestion de l’Environnement 

### ISSUE THREAD

**Issue by Hdubray** [ror-community/ror-updates#15373]
Summary of request: Add a new organization to ROR

Name of organization: Institut Supérieur d'Ingénierie et Gestion de l'Environnement - ISIGE*fr
Website: https://www.isige.minesparis.psl.eu
Domains: isige.minesparis.psl.eu
Link to publications: https://minesparis-psl.hal.science/ENSMP_ISIGE/search/index/?q=*
Organization type: Facility; Education
Organization status: Active
Wikipedia page: https://fr.wikipedia.org/wiki/Institut_sup%C3%A9rieur_d%27ing%C3%A9nierie_et_de_gestion_de_l%27environnement
Wikidata ID: Q3152544
ISNI ID: 0000 0001 2159 0642
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Institut Supérieur d'Ingénierie et Gestion de l'Environnement*fr; Higher institute for environmental engineering and management*en; ISIGE-Mines Paris PSL*fr
Labels: Higher institute for environmental engineering and management - ISIGE*en; Mines Paris, Université PSL, Institut Supérieur d’Ingénierie et Gestion de l'Environnement (ISIGE)*fr; Mines Paris, PSL University, Higher institute for environmental engineering and management (ISIGE)*en
Acronym/abbreviation: ISIGE*fr
Related organizations: 
City: Fontainebleau
Country: France 
Geonames ID: 3018074
Year established: 1992
How will a ROR ID for this organization be used? 
The goal of a recording for this organization is to promote the ISIGE, according to the new curated signature chart, validated by our research director. 
Other information about this request:
Other information about this request: You will find the signature chart of Mines Paris-PSL attached to this request.
[10963-2024-08-20_Note_Signatures_publications-4.pdf](https://github.com/user-attachments/files/17662204/10963-2024-08-20_Note_Signatures_publications-4.pdf)

**Comment by Hdubray** [comment]
Hello,
A quick note to inform you that I edited my request : It is not necessary to add https://ror.org/04y8cs423 (Université PSL) as a parent organisation.
Best regards.
Héloïse Dubray

**Comment by rileymmarsh** [comment]
Research center in France. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by Hdubray** [comment]
Hello, 

Thank you for your help in creating those records. 

I write you to signal a mistake I made on the following tickets : #15372, #15373, #15364. I asked to suppress a parent organization, but I picked the wrong identifier. 

Here are the records concerned : 
-https://ror.org/05yd19040
-https://ror.org/00dxbgs74
-https://ror.org/0579t4s85
For each three of these organizations, could you please add the following parent organization : https://ror.org/04y8cs423

Thank you again. 
If you need further information on my part, please let me know.

Best regards, 

Héloïse Dubray

**Comment by rileymmarsh** [comment]
Hello @Hdubray ! I've created three new issues for these corrections: #16462, #16463, #16464.
