### ISSUE TITLE
Add a new organization to ROR: Community Action Tenants Union

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15378]
Summary of request: Add a new organization to ROR

Name of organization: Community Action Tenants Union*en
Website: https://catuireland.org
Domains: catuireland.org
Link to publications: https://doi.org/10.54825/ESFP3948 https://doi.org/10.1386/ajms_00150_1
Organization type: Other
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Community_Action_Tenants_Union
Wikidata ID: Q120208949
ISNI ID: 
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: CATU Ireland*en; CATU Limerick*en
Labels:
Acronym/abbreviation: CATU*en
Related organizations: 
City: Dublin
Country: Ireland
Geonames ID: 2964574
Year established: 2019
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Tenants Union in Ireland. Two instances of affiliation usage and many secondary references. Not strictly a research organization. May be fine to add but could use a second review.

**Comment by adambuttrick** [comment]
Multiple authors using, so this is fine to add.
