### ISSUE TITLE
Modify Industrial Research Institute for Automation and Measurements (https://ror.org/04b9a1925)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#154]
Summary: Modify the information in an existing ROR record
Name of organization: Industrial Research Institute for Automation and Measurements
ROR ID: https://ror.org/04b9a1925
Description of change: We kindly inform you that according to the ŁUKASIEWICZ Research Network Act dated on February 21st, 2019 (Dz.U. 2019, poz. 534), starting from the 1 of April 2019, the Industrial Research Institute for Automation and Measurements PIAP became part of the ŁUKASIEWICZ Research Network and uses the name: Sieć Badawcza ŁUKASIEWICZ – Przemysłowy Instytut Automatyki i Pomiarów PIAP.

--
Curator recommendation (MG):
- Change name to `Łukasiewicz Research Network - Industrial Research Institute for Automation and Measurements`
- Move alias to language label field with Polish code `pl` and update Polish name to `Sieć Badawcza Łukasiewicz – Przemysłowy Instytut Automatyki i Pomiarów` 
- Change organization type to "Facility" to be consistent with other Łukasiewicz Research Network records

Update: change.name==Łukasiewicz Research Network - Industrial Research Institute for Automation and Measurements; delete.aliases==Przemysłowy Instytut Automatyki i Pomiarów; add.labels==Sieć Badawcza Łukasiewicz – Przemysłowy Instytut Automatyki i Pomiarów*Polish; delete.types==Company; add.types==Facility;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
