### ISSUE TITLE
Add a new organization to ROR: Provincie Gelderland

### ISSUE THREAD

**Issue by pvgenuchten** [ror-community/ror-updates#15401]
Summary of request: Add a new organization to ROR

Name of organization: Provincie Gelderland*nl
Website: https://www.gelderland.nl
Domains: gelderland.nl
Link to publications: doi: 10.1016/j.clwas.2024.100178, doi: 10.1016/j.resconrec.2024.107595, doi: 10.1016/j.ecolind.2024.111897, doi: 10.3390/ijerph15112550
Organization type: Government
Organization status:
Wikipedia page: https://en.wikipedia.org/wiki/Gelderland
Wikidata ID: Q775
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Province of Gelderland*en
Labels:
Acronym/abbreviation:
Related organizations: 
City: Arnhem
Country: Netherlands
Geonames ID: 2759661
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Funds and employs researchers. Solid affiliation usage. Should be added.
