### ISSUE TITLE
Add a new organization to ROR: Academy of Public Administration under the President of the Republic of Kazakhstan

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15413]
Summary of request: Add a new organization to ROR

Name of organization: Academy of Public Administration under the President of the Republic of Kazakhstan*en
Website: https://www.apa.kz
Domains: apa.kz
Link to publications: https://doi.org/10.46303/jcsr.2024.11 https://doi.org/10.2478/nispa-2018-0018 https://doi.org/10.21511/ppm.22(2).2024.52
Organization type: Education
Organization status: Active
Wikipedia page: https://ru.wikipedia.org/wiki/%D0%90%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%8F_%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F_%D0%BF%D1%80%D0%B8_%D0%9F%D1%80%D0%B5%D0%B7%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%B5_%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B8_%D0%9A%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD
Wikidata ID: Q12553646
ISNI ID: 0000 0004 0547 503X
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Мемлекеттік Қызмет Академиясы*kk; Казахстанская академия государственной службы*ru; Академия госуправления*ru
Labels: Академия государственного управления при Президенте Республики Казахстан*ru; Қазақстан Республикасы Президентінің жанындағы Мемлекеттік басқару академиясы*kk
Acronym/abbreviation: APA*en;  АГУ*ru
Related organizations: 
City: Astana
Country: Kazakhstan
Geonames ID: 1526273
Year established: 1994
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Academy to train for civil service in Kazakhstan. Funds and employs researchers. Solid affiliation usage. Should be added.
