### ISSUE TITLE
Add a new organization to ROR: Q University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15412]
Summary of request: Add a new organization to ROR

Name of organization: Q University*en
Website: https://q-university.kz
Domains: q-university.kz
Link to publications: https://doi.org/10.3390/bs14080648 https://doi.org/10.47703/ejebs.v1i67.267 https://doi.org/10.3390/su16166752
Organization type: Education
Organization status: Active
Wikipedia page: 
Wikidata ID: Q43147119
ISNI ID: 0000 0000 9486 9081
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Академии «QAINAR»*ru; Qainar Academy*en; Kainar University*en; Kainar Academy*en; Qainar University*en; Kainar College*en
Labels: колледжа «Кайнар»*ru; Қайнар Академиясы*kk 
Acronym/abbreviation:
Related organizations: 
City: Almaty
Country: Kazakhstan
Geonames ID: 1526384
Year established: 1991
How will a ROR ID for this organization be used? 
Other information about this request: Name [changed](https://q-university.kz/en/5430-istorija_universiteta.html) to "Q University" earlier this year.

**Comment by rileymmarsh** [comment]
Private university in Kazakhstan. Funds and employs researchers. Solid affiliation usage. Should be added.
