### ISSUE TITLE
Add a new organization to ROR: International Image Sensor Society

### ISSUE THREAD

**Issue by rileymmarsh** [ror-community/ror-updates#15415]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: International Image Sensor Society*en
Website: https://imagesensors.org
Domains: imagesensors.org
Link to publications: 
Organization type: Other
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Aliases: 
Acronym/abbreviation: IISS*en
Labels: 
Related organizations: 
City: Crieff
Country: United Kingdom
Geonames ID: 2651983
Year established: 
Other information about this request: Part of project  #15274

**Comment by adambuttrick** [comment]
In scope for ROR by virtuie of its conference activities and publications. Numerous service affiliations as well (e.g. https://ieeexplore.ieee.org/abstract/document/9780860)
