### ISSUE TITLE
Add a new organization to ROR: Faculty of Sciences of Sfax

### ISSUE THREAD

**Issue by BessemAamira** [ror-community/ror-updates#15433]
Summary of request: Add a new organization to ROR

Name of organization: Faculty of Sciences of Sfax*en
Website: https://fss.rnu.tn
Domains: fss.rnu.tn
Link to publications: 
Organization type: Education
Organization status: https://www.pist.tn/jort/1987/1987F/Jo06987.pdf
Wikipedia page:
Wikidata ID: Q91611455
ISNI ID: 0000 0004 0475 6155
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: Faculté des Sciences de Sfax*fr; كلية العلوم بصفاقس*ar
Acronym/abbreviation: FSS*en
Related organizations: https://ror.org/029cgt552 (parent)
City: Sfax
Country: Tunisia
Geonames ID: 2467454
Year established: 1987
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

**Comment by adambuttrick** [comment]
Funds and employs researchers. Solid affiliation usage. Should be added.
