### ISSUE TITLE
Add a new organization to ROR: Força Aérea Brasileira

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15465]
Summary of request: Add a new organization to ROR

Name of organization: Força Aérea Brasileira*pt
Website: https://www.fab.mil.br
Domains: fab.mil.br
Link to publications: https://doi.org/10.59254/sbpo-2019-106779 https://doi.org/10.1590/S0365-05962011000200035 https://doi.org/10.1055/s-0038-1676060
Organization type: Government
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Brazilian_Air_Force
Wikidata ID: Q634542
ISNI ID: 0000 0000 9407 7033
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: 
Labels: Brazilian Air Force*en; Fuerza Aérea Brasileña*es; Force aérienne brésilienne*fr
Acronym/abbreviation: FAB*pt
Related organizations: https://ror.org/00nya5t35 (child); https://ror.org/01mke9645 (parent)
City: Brasília
Country: Brazil
Geonames ID: 3469058
Year established: 1941
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Publication affiliation usage: Força Aérea Brasileira: https://doi.org/10.5102/rbpp.v12i3.8044, https://openalex.org/W1856840189, https://doi.org/10.5935/cmm.a045, https://doi.org/10.52781/cmm.e014, https://doi.org/10.59254/sbpo-2019-106779, https://doi.org/10.1590/1517-86922015210101898, https://doi.org/10.21071/az.v59i226.4730, https://doi.org/10.17851/1983-3652.11.1.60-81, https://doi.org/10.1590/s0365-05962010000100004, https://doi.org/10.52781/cmm.a045
Potential aliases: Força Aérea Brasileira
ORCID affiliation usage: https://orcid.org/0000-0001-9738-4618; https://orcid.org/0000-0001-6518-6465; https://orcid.org/0000-0002-9577-4804; https://orcid.org/0000-0002-2000-2041; https://orcid.org/0000-0003-2394-009X
Possible ROR matches: alias: https://ror.org/00nya5t35 - Fôrça Aérea Brasileira
Previous requests: https://github.com/ror-community/ror-updates/issues/15465
Geonames match: Brazil | Geonames ID: [ 3469034](https://www.geonames.org/3469034)

**Comment by rileymmarsh** [comment]
Air force in Brazil. Funds and employs researchers. Solid affiliation usage. Should be added.
