### ISSUE TITLE
Add a new organization to ROR: Xavier Institute of Social Service

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15463]
Summary of request: Add a new organization to ROR

Name of organization: Xavier Institute of Social Service*en
Website: https://www.xiss.ac.in
Domains: xiss.ac.in
Link to publications: https://doi.org/10.1080/10911359.2012.646851 https://doi.org/10.1111/camh.12398 https://doi.org/10.1177/0970846419750104
Organization type: Education
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Xavier_Institute_of_Social_Service
Wikidata ID: Q8043261
ISNI ID: 0000 0004 0497 5980
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: जेवियर समाज सेवा संस्थान*hi
Acronym/abbreviation: XISS*en
Related organizations: 
City: Ranchi
Country: India
Geonames ID: 1258526 
Year established: 1955
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Wikidata Name: Xavier Institute of Social Service
Wikidata ID: Q8043261
Wikidata name match ratio: 100
wikipedia_url: https://en.wikipedia.org/wiki/Xavier_Institute_of_Social_Service
Wikidata Admin territory name: Ranchi
Wikidata Admin territory Geonames ID: 1258526
Wikidata Country: India
Wikidata links: http://www.xiss.ac.in
Wikidata ISNI ID: 0000000404975980
ISNI: Xavier Institute of Social Service - 0000000404975980; Karve Institute of Social Service - 0000000103639529
Publication affiliation usage: Xavier Institute of Social Service: https://doi.org/10.1016/j.stlm.2021.100013, https://doi.org/10.1108/ijicc-07-2016-0025, https://doi.org/10.1080/19371918.2010.525136, https://doi.org/10.2139/ssrn.1349894, https://doi.org/10.1504/ijiei.2020.109094, https://doi.org/10.1109/icccs49678.2020.9277482, https://openalex.org/W3122984361, https://doi.org/10.1016/j.puhip.2020.100009, https://doi.org/10.1080/10911359.2012.646851, https://doi.org/10.1080/15433714.2014.997097
Potential aliases: Xavier Institute of Social Service
ORCID affiliation usage: https://orcid.org/0000-0002-3203-4702; https://orcid.org/0000-0001-6132-5157; https://orcid.org/0000-0003-1810-6439; https://orcid.org/0000-0002-5639-2600; https://orcid.org/0000-0002-9939-0955
Possible ROR matches: ror_display: https://ror.org/01cw3ja29 - Higher Institute of Social Service
Previous requests: https://github.com/ror-community/ror-updates/issues/15463
Geonames match: Ranchi | Geonames ID: [ 1258526](https://www.geonames.org/1258526)

**Comment by rileymmarsh** [comment]
Business school in India. Funds and employs researchers. Solid affiliation usage. Should be added.
