### ISSUE TITLE
Add a new organization to ROR: Nuvance Health

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15478]
Summary of request: Add a new organization to ROR

Name of organization: Nuvance Health*en
Website: https://www.nuvancehealth.org
Domains: nuvancehealth.org
Link to publications: https://doi.org/10.1212/WNL.0000000000204396 https://doi.org/10.1200/JCO.2023.41.16_suppl.12015 https://doi.org/10.1212/WNL.0000000000204837
Organization type: Healthcare
Organization status: Active
Wikipedia page: https://en.wikipedia.org/wiki/Nuvance_Health
Wikidata ID: Q85846824
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Nuvance Health Systems*en
Labels:
Acronym/abbreviation:
Related organizations: https://ror.org/03vcded87 (predecessor) https://ror.org/02bxt4m23 (parent) https://ror.org/05g023586 (child) https://ror.org/04t2rv460 (child) https://ror.org/005xhc966 (child)
City: Danbury
Country: United States
Geonames ID: 4832353
Year established: 2019
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment]
Hospital system in Connecticut. Funds and employs researchers. Solid affiliation usage. Should be added.
