### ISSUE TITLE
Add a new organization to ROR: Institut des Hautes Études pour l’Innovation et l’Entreprenariat 

### ISSUE THREAD

**Issue by Hdubray** [ror-community/ror-updates#15482]
Summary of request: Add a new organization to ROR

Name of organization: Institut des Hautes Études pour l’Innovation et l’Entreprenariat - IHEIE*fr 
Website: https://iheie.minesparis.psl.eu
Domains: iheie.minesparis.psl.eu
Link to publications: https://minesparis-psl.hal.science/ENSMP_IHEIE/
Organization type: Facility; Education
Organization status: Active
Wikipedia page:
Wikidata ID:
ISNI ID: 
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Institut des Hautes Études pour l’Innovation et l’Entreprenariat*fr; Institute of Higher Education for Innovation and Entrepreneurship*en; Mines Paris - PSL, Institut des Hautes Études pour l’Innovation et l’Entreprenariat (IHEIE)*fr
Labels: Institute of Higher Education for Innovation and Entrepreneurship - IHEIE*en; Mines Paris, PSL University, Institute of Higher Education for Innovation and Entrepreneurship (IHEIE)*en; Mines Paris, Université PSL, Institut des Hautes Études pour l’Innovation et l’Entreprenariat (IHEIE)*fr
Acronym/abbreviation: IHEIE
Related organizations: https://ror.org/04y8cs423 (parent)
City: Paris
Country: France 
Geonames ID: 2988507
Year established: 2016
How will a ROR ID for this organization be used? 
The goal of a recording for this organization is to promote the IHEIE, according to the new curated signature chart, validated by our research director.
Other information about this request:
Other information about this request: You will find the signature chart of Mines Paris-PSL attached to this request.
[10963-2024-08-20_Note_Signatures_publications-4.pdf](https://github.com/user-attachments/files/17736010/10963-2024-08-20_Note_Signatures_publications-4.pdf)

**Comment by rileymmarsh** [comment]
Research center in France. Funds and employs researchers. Solid affiliation usage. Should be added.
