### ISSUE TITLE
Add a new organization to ROR: National Research and Innovation Agency

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1551]
Summary of request: Add a new organization to ROR

Name of organization: National Research and Innovation Agency
Website: https://www.brin.go.id
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/National_Research_and_Innovation_Agency
Wikidata ID: Q97200300
ISNI ID:
GRID ID:
Crossref Funder ID: 501100020638
Other names for the organization: 
Labels: Badan Riset dan Inovasi Nasional*Indonesian
Acronym/abbreviation:
Related organizations: 
City: Jakarta
Country: Indonesoa
Geonames ID: 1642911
Year established: 2021
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
As first identified in #1548, Jakarta has closed many of their government research institutes and folded them into this single organization. See [Wikipedia entry](https://en.wikipedia.org/wiki/National_Research_and_Innovation_Agency) for further details. Funds and employs researchers. Solid affiliation usage. Should be added to be identified as successor.

Publication affiliation usage: https://doi.org/10.3390/met12010099; https://doi.org/10.1016/j.ijdrr.2021.102771; https://doi.org/10.3390/v14040778

ORCID affiliation usage: https://orcid.org/0000-0002-7515-574X ; https://orcid.org/0000-0002-1043-1600 ; https://orcid.org/0000-0002-0336-4702

**Comment by nlundvick** [comment]
Established, top-level organization associated with research publications and activities. Affiliation use: [https://api.crossref.org/works/?query.affiliation=%22National+Research+and+Innovation+Agency%22](https://api.crossref.org/works/?query.affiliation=%22National+Research+and+Innovation+Agency%22). In scope, add to ROR. Identify as successor as noted by previous curator and in related issues.
