### ISSUE TITLE
Add a new organization to ROR: The Bedford College Group

### ISSUE THREAD

**Issue by rileymmarsh** [ror-community/ror-updates#15523]
Summary of request: Add a new organization to ROR

Name of organization: The Bedford College Group*en
Website: https://bedfordcollegegroup.ac.uk
Domains: bedfordcollegegroup.ac.uk
Link to publications: 
Organization type: Education
Organization status:
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0005 0465 6813
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Bedford College Group*en
Labels:
Acronym/abbreviation:
Related organizations: https://ror.org/01aa0nz04 (child)
City: Bedford
Country: United Kingdom
Geonames ID: 2656046
Year established: 2017
How will a ROR ID for this organization be used? 
Other information about this request: Following #15363

**Comment by adambuttrick** [comment]
Funds and employs researchers. Solid affiliation usage. Should be added.
