### ISSUE TITLE
Add a new organization to ROR: Harte Research Institute for Gulf of Mexico Studies

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1557]
Summary of request: Add a new organization to ROR

Name of organization: Harte Research Institute for Gulf of Mexico Studies
Website: https://www.harteresearch.org
Link to publications: 
Organization type: Facility
Wikipedia page: https://en.wikipedia.org/wiki/Harte_Research_Institute_for_Gulf_of_Mexico_Studies
Wikidata ID: Q5674340
ISNI ID: 0000 0000 8958 062X 
GRID ID:
Crossref Funder ID:
Other names for the organization: Harte Research Institute
Aliases:
Labels:
Acronym/abbreviation:
Related organizations: https://ror.org/01mrfdz82 (parent)
City: Corpus Christi, Texas
Country: USA
Geonames ID: 4683416
Year established: 2000
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by mariagould** [comment]
I think this appears to be sufficiently independent from Texas A&M (including separate identity, website, copyright statement) that we would consider it to be in scope.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04rpe5h19 in release v1.14.
