### ISSUE TITLE
Add a new organization to ROR: Sri Ramakrishna Engineering College

### ISSUE THREAD

**Issue by saranyaKise** [ror-community/ror-updates#1559]
Summary of request: Add a new organization to ROR

Name of organization: Sri Ramakrishna Engineering College
Website: https://www.srec.ac.in
Link to publications: 10.1007/978-981-15-0184-5_14
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Sri_Ramakrishna_Engineering_College
Wikidata ID: Q7586207
ISNI ID: 0000 0004 1767 7042
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: SREC
Related organizations: https://ror.org/01qhf1r47 (related)
City: Coimbatore
Country:India
Geonames ID: 1273865
Year established:1994
How will a ROR ID for this organization be used? 
Other information about this request:For research publication purpose

**Comment by adambuttrick** [comment]
Engineering college affiliated to https://ror.org/01qhf1r47. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1016/j.electacta.2011.02.036; https://doi.org/10.1039/c7nj02664a; https://doi.org/10.1016/j.scitotenv.2020.139021; https://doi.org/10.1109/tencon.2016.7848162; https://doi.org/10.1109/tie.2013.2290776; https://doi.org/10.1016/j.jpdc.2013.10.009; https://doi.org/10.1016/j.ijheatmasstransfer.2014.11.034

ORCID affiliation usage: https://orcid.org/0000-0001-9572-1844 ; https://orcid.org/0000-0002-1294-0476 ; https://orcid.org/0000-0002-8491-5675

**Comment by nlundvick** [comment]
Established, top-level organization associated with research publications and activities. Affiliation use: [https://api.crossref.org/works/?query.affiliation=%22Sri+Ramakrishna+Engineering+College%22](https://api.crossref.org/works/?query.affiliation=%22Sri+Ramakrishna+Engineering+College%22). In scope, add to ROR.

**Comment by saranyaKise** [comment]
Sir,
Kindly tell me when the details will be updated because this is mandatory for verifying the affiliation in hindawi publication and due to this my publication is getting delayed.Kindly let me know if any data needed from my end.

**Comment by amandafrench** [comment]
@saranyaKise Our communications with Hindawi have indicated that the "requirement" for a ROR ID before publication is a mistake -- the lack of a ROR ID for your organization should not be holding up publication. Please communicate with Hindawi staff to resolve this. Meanwhile, your requests will undergo review for addition to the ROR registry.
