### ISSUE TITLE
Modify Institute of Heavy Organic Synthesis "Blachownia" (https://ror.org/035hkbq39)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#156]
Summary: Modify the information in an existing ROR record
Name of organization: Heavy Organic Synthesis "Blachownia"
ROR ID: https://ror.org/035hkbq39
Description of change: I'm writing you on the behalf of former Institute of Heavy Organic Synthesis "Blachownia" (https://ror.org/035hkbq39). Last year we changed our name to Łukasiewicz Research Network - Institute of Heavy Organic Synthesis "Blachownia". Is it possible to update our name on your website?

--
Curator recommendation (MG):
- Change name to `Łukasiewicz Research Network - Institute of Heavy Organic Synthesis "Blachownia"`
- Move alias to language label field with Polish code `pl` and update Polish name to `Sieć Badawcza Łukasiewicz -
Instytut Ciężkiej Syntezy Organicznej "Blachownia"`

Update: change.name==Łukasiewicz Research Network - Institute of Heavy Organic Synthesis "Blachownia"; add.labels==Sieć Badawcza Łukasiewicz - Instytut Ciężkiej Syntezy Organicznej "Blachownia"*Polish; delete.aliases==Instytut Ciężkiej Syntezy Organicznej "Blachownia"; add.Wikidata==Q11712982;add.wikipedia_url==https://pl.wikipedia.org/wiki/Sieć_Badawcza_Łukasiewicz_–_Instytut_Ciężkiej_Syntezy_Organicznej_„Blachownia”;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
