### ISSUE TITLE
Add a new organization to ROR: Universidade da Força Aérea

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15603]
Summary of request: Add a new organization to ROR

Name of organization: Universidade da Força Aérea*pt
Website: https://www2.fab.mil.br/unifa/
Domains:
Link to publications: https://doi.org/10.34117/bjdv8n5-514 https://doi.org/10.18359/ries.4300 https://doi.org/10.21826/01021788326606
Organization type: Education
Organization status: Active
Wikipedia page: 
Wikidata ID:
ISNI ID: 0000 0004 4648 0134
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: Brazilian Air Force University*en
Acronym/abbreviation: UNIFA*pt
Related organizations: https://ror.org/00gz6rx61 (parent)
City: Rio de Janeiro
Country: Brazil
Geonames ID: 6322060
Year established: 1983
How will a ROR ID for this organization be used? 
Other information about this request: ≠ https://ror.org/00nya5t35

**Comment by rileymmarsh** [comment]
University of the Air force in Brazil, separated from the Academia da Força Aérea in 1971. Funds and employs researchers. Solid affiliation usage. Should be added.
