### ISSUE TITLE
Modify the information in an existing ROR record: University of Turku - https://ror.org/05vghhr25

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#1561]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Turku
ROR ID: https://ror.org/05vghhr25
Which part of the record needs to be changed? aliases
Description of change: The Swedish and Finnish translations of "University of Turku" are already stored in labels and can be removed from aliases, where they are duplicated. 

Update: delete.aliases==Turun yliopisto; delete.aliases==Åbo universitet;$

**Comment by amandafrench** [comment]
cf ror-community/ror-schema#9

**Comment by adambuttrick** [comment]
Record updated in release v1.14.
