### ISSUE TITLE
Modify the information in an existing ROR record: Minneapolis Public Library - https://ror.org/032tz4q83

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15626]
Summary of request: Modify the information in an existing ROR record

Name of organization: Minneapolis Public Library
ROR ID: https://ror.org/032tz4q83
Which part of the record needs to be changed? Status, relationship
Description of change: MPL [merged](https://en.wikipedia.org/wiki/Minneapolis_Public_Library) into Hennepin County Library (https://ror.org/05gjbhz21) in 2008.
Change status to inactive
Maybe make https://ror.org/032tz4q83 a predecessor to https://ror.org/05gjbhz21

Update: alias.add==Minneapolis Central Library*en$

**Comment by rileymmarsh** [comment]
The Minneapolis Public Library still exists in name, if not as an entire system. Add the alias Minneapolis Central Library to prevent confusion but keep the name active for new affiliation usage.
