### ISSUE TITLE
Add a new organization to ROR: State Scientific Institution "Institute of Information, Security and Law of the National Academy of Legal Sciences of Ukraine"

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1572]
Summary of request: Add a new organization to ROR

Name of organization: State Scientific Institution "Institute of Information, Security and Law of the National Academy of Legal Sciences of Ukraine"
Website: http://ippi.org.ua
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Institute of Information, Security and Law of the NALS of Ukraine
Labels: Державна наукова установа “Інститут інформації, безпеки і права Національної академії правових наук України”*Ukrainian
Acronym/abbreviation:
Related organizations: https://ror.org/02wnejx52 (parent)
City: Kyiv
Country: Ukraine
Geonames ID: 703448
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Publication affiliation usage: https://doi.org/10.30525/978-9934-26-197-8-1; https://doi.org/10.46398/cuestpol.4074.12; https://doi.org/10.24144/2788-6018.2022.01.33; https://doi.org/10.37635/jnalsu.28(2).2021.66-75

ORCID affiliation usage: https://orcid.org/0000-0003-0446-5975 ; https://orcid.org/0000-0002-0571-0437

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities and affiliation usage.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05at5an04 in release v1.14.
