### ISSUE TITLE
Modify Wood Technology Institute (https://ror.org/052svzr34)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#158]
Summary: Modify the information in an existing ROR record
Name of organization: Wood Technology Institute
ROR ID: https://ror.org/052svzr34
Description of change: Last year the Wood Technology Institute in Poznan was transformed into the Łukasiewicz Research Network - Wood Technology Institute (Polish: Sieć Badawcza Łukasiewicz - Instytut Technologii Drewna) 

-- 
Curator recommendation (MG, AS):
- Change name to `Łukasiewicz Research Network - Wood Technology Institute`
- Move alias to Polish name label with code `pl` and change Polish name to `Sieć Badawcza Łukasiewicz - Instytut Technologii Drewna`
- Fix acronym - should be ITD, not IPD
- Website should be https now: https://www.itd.poznan.pl/
- Wikidata ID: https://www.wikidata.org/wiki/Q30290057
- Wikipedia page (Polish): https://pl.wikipedia.org/wiki/Instytut_Technologii_Drewna

Update: change.name==Łukasiewicz Research Network - Wood Technology Institute; delete.aliases==Instytut Technologii Drewna; add.labels==Sieć Badawcza Łukasiewicz - Instytut Technologii Drewna*Polish; delete.acronyms==IPD; add.acronyms==ITD; delete.links==http://www.itd.poznan.pl/en/; add.links==https://www.itd.poznan.pl/; add.Wikidata==Q30290057; add.wikipedia_url==https://pl.wikipedia.org/wiki/Instytut_Technologii_Drewna;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
