### ISSUE TITLE
Modify the information in an existing ROR record: Crossref - https://ror.org/02twcfp32

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#1583]
Summary of request: Modify the information in an existing ROR record

Name of organization: Crossref
ROR ID: https://ror.org/02twcfp32
Which part of the record needs to be changed? aliases, acronyms
Description of change: Add "Publishers International Linking Organization" as an alias and "PILA" as an acronym per https://www.crossref.org/board-and-governance/ 

Update: add.aliases==Publishers International Linking Organization; add.acronyms==PILA;$

**Comment by adambuttrick** [comment]
Addition of names corresponds to organization's website/documentation.

**Comment by adambuttrick** [comment]
Record updated in release v1.14.
