### ISSUE TITLE
Add a new organization to ROR: Salymbekov University

### ISSUE THREAD

**Issue by cknopp-schwyn** [ror-community/ror-updates#15988]
Summary of request: Add a new organization to ROR

Name of organization: Salymbekov University*en
Website: https://salymbekov.com
Domains: salymbekov.com
Link to publications: https://doi.org/10.24969/hvt.2024.488 https://doi.org/10.1002/ccr3.9318 https://doi.org/10.32768/abc.2024114418-422
Organization type: Education
Organization status: Active
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: Салымбеков университет*ky
Acronym/abbreviation:
Related organizations: 
City: Bishkek
Country: Kyrgyzstan
Geonames ID: 1528334
Year established: 2019
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Funds and employs researchers. Solid affiliation usage. Should be added.
