### ISSUE TITLE
Redirect Instytut Biotechnologii i Antybiotyków (https://ror.org/024za3n32)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#160]
Instytut Biotechnologii i Antybiotyków (https://ror.org/024za3n32) has been incorporated into  Łukasiewicz Research Network – Industrial Chemistry Institute (https://ror.org/00jhf1r34) per https://ichp.pl/en/.

Therefore, the records should be merged and the ID for Instytut Biotechnologii i Antybiotyków should be redirected to https://ror.org/00jhf1r34. 

Name of organization: Instytut Biotechnologii i Antybiotyków
ROR ID: https://ror.org/024za3n32
Related organizations: https://ror.org/00jhf1r34 (successor-np)
Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
Updated in release v1.15.
