### ISSUE TITLE
Modify Industrial Chemistry Institute (https://ror.org/00jhf1r34)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#161]
Summary: Modify the information in an existing ROR record
Name of organization: Industrial Chemistry Institute
ROR ID: https://ror.org/00jhf1r34

Description of change:
- Previous name: Industrial Chemistry Research Institute
- Present name: Łukasiewicz Research Network - Industrial Chemistry Institute

--
Curator recommendation (MG, AS):
- Change name of organization to `Łukasiewicz Research Network - Industrial Chemistry Institute`
- Move alias to Polish name label with code `pl` and change Polish name to `Sieć Badawcza Łukasiewicz - Instytut Chemii Przemysłowej`
- Change website to https://ichp.pl/
- Wikidata ID: https://www.wikidata.org/wiki/Q11712979
- Wikipedia page (Polish): https://pl.wikipedia.org/wiki/Instytut_Chemii_Przemysłowej

Update: change.name==Łukasiewicz Research Network - Industrial Chemistry Institute; delete.aliases==Instytut Chemii Przemysłowej; add.labels==Sieć Badawcza Łukasiewicz - Instytut Chemii Przemysłowej*Polish; delete.links==http://en.www.ichp.pl/; add.links==https://ichp.pl/; add.Wikidata==Q11712979; add.wikipedia_url ==https://pl.wikipedia.org/wiki/Instytut_Chemii_Przemysłowej;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
