### ISSUE TITLE
Add a new organization to ROR: LA Referencia

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#1610]
Summary of request: Add a new organization to ROR

Name of organization: LA Referencia
Website: https://www.lareferencia.info
Link to publications: https://www.lareferencia.info/es/recursos/ciencia-abierta-documentos-externos; https://scholar.google.com/citations?user=z4cVWPGTmKsC&hl=en&oi=ao
Organization type: Archive
Wikipedia page:
Wikidata ID: Q65557864
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: La Red Federada de Repositorios Institucionales de Publicaciones Científicas; Federated Network of Institutional Repositories of Scientific Publications
Labels:
Acronym/abbreviation:
Related organizations: https://ror.org/02h21fh05 (related)
City: Santiago
Country: Chile
Geonames ID: 3871336
Year established: 2012
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Latin American network of open access repositories. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.5281/zenodo.7097514; https://doi.org/10.21747/21836671/pagnespc4; https://doi.org/10.5281/zenodo.7263151; https://openalex.org/W3014068810; https://openalex.org/W2982203802

ORCID affiliation usage: https://orcid.org/0000-0002-4703-8992

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/024pbfj84 in release v1.14.
