### ISSUE TITLE
Modify Instytut Inżynierii Materiałów Polimerowych i Barwników (https://ror.org/05556pa07)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#162]
Summary: Modify an existing organization in ROR
Name of organization: Instytut Inżynierii Materiałów Polimerowych i Barwników
ROR ID: https://ror.org/05556pa07
Description of change: 
The organization contacted ROR to add a new record for this organization. It turns out that this organization is already in ROR. The name information in the metadata should be updated to make the record more discoverable and to conform to the organization's current name. 

Curator recommendation (MG, AS): 
- Change primary name to `Łukasiewicz Research Network - Institute for Engineering of Polymer Materials and Dyes`
- Create Polish name field with code `pl` and Polish name `Sieć Badawcza Łukasiewicz –
Instytut Inżynierii Materiałów Polimerowych i Barwników` 
- Wikidata ID: Q30261007
- Wikipedia page: https://pl.wikipedia.org/wiki/Instytut_Inżynierii_Materiałów_Polimerowych_i_Barwników_w_Toruniu

Update: change.name==Łukasiewicz Research Network - Institute for Engineering of Polymer Materials and Dyes; add.labels==Sieć Badawcza Łukasiewicz –Instytut Inżynierii Materiałów Polimerowych i Barwników*Polish; add.Wikidata==Q30261007; add.wikipedia_url==https://pl.wikipedia.org/wiki/Instytut_Inżynierii_Materiałów_Polimerowych_i_Barwników_w_Toruniu;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
