### ISSUE TITLE
Modify Polish Center for Technology Development (https://ror.org/03rvn3n08)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#163]
Summary: Modify an existing organization in ROR
Name of organization: Polish Center for Technology Development
ROR ID: https://ror.org/03rvn3n08

Description of change:
The organization contacted ROR to add a new record for this organization. It turns out that this organization is already in ROR. The name information in the metadata should be updated to make the record more discoverable and to conform to the organization's current name.

Curator recommendation (MG, AS):
- Change name to `Łukasiewicz Research Network – PORT Polish Center for Technology Development`
- Move alias to Polish name label with code `pl` and change Polish name to `Sieć Badawcza Łukasiewicz – PORT Polski Ośrodek Rozwoju Technologii`
- Wikidata ID: https://www.wikidata.org/wiki/Q97371596
- Wikipedia page (Polish): https://pl.wikipedia.org/wiki/Sieć_Badawcza_Łukasiewicz_–_PORT_Polski_Ośrodek_Rozwoju_Technologii

Update: change.name==Łukasiewicz Research Network – PORT Polish Center for Technology Development; delete.labels==Polski Ośrodek Rozwoju Technologii; add.labels==Sieć Badawcza Łukasiewicz – PORT Polski Ośrodek Rozwoju Technologii*Polish; add.Wikidata==Q97371596; add.wikipedia_url==https://pl.wikipedia.org/wiki/Sieć_Badawcza_Łukasiewicz_–_PORT_Polski_Ośrodek_Rozwoju_Technologii;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
