### ISSUE TITLE
Modify Textile Research Institute (https://ror.org/01zwfkr30)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#164]
Summary: Modify the information in an existing ROR record 

Name of organization: Textile Research Institute
ROR ID: https://ror.org/01zwfkr30
Description of change: The name of our Institute was changed in 2019 from "Textile Research Institute" to "Łukasiewicz - Textile Research Institute".

Curator recommendation (MG, AS):
- Change name to `Łukasiewicz Research Network - Textile Research Institute`
- Alternate name alias (English) "Łukasiewicz - Textile Research Institute"
- Alternate name alias (Polish) "Łukasiewicz - Instytut Włókiennictwa"
- Wikidata ID: https://www.wikidata.org/wiki/Q11713259
- Wikipedia page (Poilish): https://pl.wikipedia.org/wiki/Instytut_Włókiennictwa
- Move alias to Polish name label with code `pl` and change Polish name to `Sieć Badawczą Łukasiewicz - Instytut Włókiennictwa`
- Change website to https://iw.lukasiewicz.gov.pl/

Update: change.name==Łukasiewicz Research Network - Textile Research Institute; add.aliases==Łukasiewicz - Textile Research Institute; add.aliases==Łukasiewicz - Instytut Włókiennictwa; delete.aliases==Instytut Włókiennictwa; add.labels==Sieć Badawczą Łukasiewicz - Instytut Włókiennictwa*Polish; add.wikipedia_url==https://pl.wikipedia.org/wiki/Instytut_Włókiennictwa; add.Wikidata==Q11713259; delete.links==http://www.iw.lodz.pl/eng/; add.links==https://iw.lukasiewicz.gov.pl/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
