### ISSUE TITLE
Modify the information in an existing ROR record: Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica - https://ror.org/05c7j7r25

### ISSUE THREAD

**Issue by abeldelcarpio** [ror-community/ror-updates#1643]
Summary of request: Modify the information in an existing ROR record

Name of organization: Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica
ROR ID: https://ror.org/05c7j7r25
Which part of the record needs to be changed?
Description of change:
WEBSITE: https://www.gob.pe/concytec
location GeoNames: GeoNames 6330746

Update: replace.links==https://www.gob.pe/concytec; change.Geonames==3936456;$

**Comment by adambuttrick** [comment]
Current link in ROR redirects to the provided. [Address is listed as being in Lima](https://www.gob.pe/institucion/concytec/contacto-y-numeros-de-emergencias), thus using Geonames ID for that location

https://www.geonames.org/3936456/lima.html

**Comment by adambuttrick** [comment]
Record updated in release v1.14.
