### ISSUE TITLE
Modify the information in an existing ROR record: Louisiana Technical College https://ror.org/05qc49402

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#1649]
Summary of request: Modify the information in an existing ROR record

Name of organization: Louisiana Technical College
ROR ID: https://ror.org/05qc49402
Which part of the record needs to be changed? Name, URL
Description of change: In the process of investigating #1589 I noticed that the entry in ROR for this branch of the Louisiana community college system should be updated to reflect the current name and URL. Current name appears to be Central Louisiana Community College. The URL in the metadata should also be shortened to the canonical form: https://www.cltcc.edu/

Update: change.name==Central Louisiana Community College; add.aliases==Louisiana Technical College; replace.links==https://www.cltcc.edu;$

**Comment by adambuttrick** [comment]
Record updated in release v1.17.
