### ISSUE TITLE
Modify Tabor (Poland) (https://ror.org/02px88477)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#165]
Summary: Modify the information in an existing ROR record
Name of organization: Tabor (Poland)
ROR ID: https://ror.org/02px88477
Description of change: IPS "TABOR" was incorporated into the Łukasiewicz Research Network (https://lukasiewicz.gov.pl/en/). Please adjust the organization name to reflect this affiliation as: Lukasiewicz Research Network - Rail Vehicles Institute "TABOR"

Curator recommendation (MG, AS):
- Change name to `Łukasiewicz Research Network - Rail Vehicles Institute`
- Add Polish name label with code `pl` and Polish name `Sieć Badawczą Łukasiewicz - Instytut Pojazdów Szynowych "TABOR”`
- Change website to https://www.tabor.lukasiewicz.gov.pl/
- Add Wikidata ID: https://www.wikidata.org/wiki/Q16560152
- Add Wikipedia page (Polish): https://pl.wikipedia.org/wiki/Instytut_Pojazdów_Szynowych_„Tabor”
- Change organization type to "Facility" per other Łukasiewicz entries

Update: change.name==Łukasiewicz Research Network - Rail Vehicles Institute; add.labels==Sieć Badawczą Łukasiewicz - Instytut Pojazdów Szynowych "TABOR”*Polish; delete.links==http://www.tabor.com.pl; add.links==https://www.tabor.lukasiewicz.gov.pl/; add.Wikidata==Q16560152; add.wikipedia_url==https://pl.wikipedia.org/wiki/Instytut_Pojazdów_Szynowych_„Tabor”; delete.types==Company; add.types==Facility;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
