### ISSUE TITLE
Add Research Centre of the Slovenian Academy of Sciences and Arts

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#166]
Summary: Add a new organization to ROR
Name of organization: Research Centre of the Slovenian Academy of Sciences and Arts
Name in Slovenian:  Znanstvenoraziskovalni center Slovenske akademije znanosti in umetnosti (ZRC SAZU) 
Website: https://www.zrc-sazu.si/
Wikipedia URL (Slovenian): https://sl.wikipedia.org/wiki/Znanstvenoraziskovalni_center_Slovenske_akademije_znanosti_in_umetnosti
Wikidata ID: Q15977604
ISNI: https://isni.org/isni/0000000121765262
Related organizations: https://ror.org/04evj0n95 (related)

Information about this request: 
We are upgrading our repository for research data, incorporating new standards and technologies. New repository will be based on Open Linked Data philosophy, so we need to describe important objects – like Agents entities – with Internationalized Resource Identifier (IRI). 

we are aware that the Slovenian Academy of Sciences and Arts (https://ror.org/04evj0n95) is already registered in ROR. However, our Research Centre of the Slovenian Academy of Sciences and Arts is an autonomous legal entity with different mission and scope. Therefore we kindly ask you to enter the Research Centre of the Slovenian Academy of Sciences and Arts into the ROR as well.

**Comment by carlyrobinson** [comment]
Agree, it should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04zvj8c18 in release v1.0.
