### ISSUE TITLE
Modify Metal Forming Institute (https://ror.org/03pw76589)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#167]
Summary: Modify the information in an existing ROR record
Name of organization: Metal Forming Institute
ROR ID: https://ror.org/03pw76589

Description of change: 
Name: Lukasiewicz Research Network - Metal Forming Institute
Alternate name (Polish): Sieć Badawcza Łukasiewicz – Instytut Obróbki Plastycznej
Abbreviations: 
Lukasiewicz - Metal Forming Institute 
Lukasiewicz - INOP
L-INOP
Type: Facility (R&D institute)
Also, we have wikipedia url: https://pl.wikipedia.org/wiki/Sie%C4%87_Badawcza_%C5%81ukasiewicz_%E2%80%93_Instytut_Obr%C3%B3bki_Plastycznej
but at this moment it is only in Polish (we are still working on the English version)

Curator recommendations (MG, AS):
- Change name to `Łukasiewicz Research Network - Metal Forming Institute`
- Add Polish name label `Sieć Badawcza Łukasiewicz – Instytut Obróbki Plastycznej`
- Add aliases `Lukasiewicz - Metal Forming Institute`,  `Lukasiewicz - INOP`, `L-INOP`
- Add [Wikipedia URL](https://pl.wikipedia.org/wiki/Sie%C4%87_Badawcza_%C5%81ukasiewicz_%E2%80%93_Instytut_Obr%C3%B3bki_Plastycznej)
- Add Wikidata ID: https://www.wikidata.org/wiki/Q30290049
- Change organization type to "Facility" per other Łukasiewicz entries

Update: change.name==Łukasiewicz Research Network - Metal Forming Institute; add.labels==Sieć Badawcza Łukasiewicz – Instytut Obróbki Plastycznej*Polish; add.aliases==Lukasiewicz - Metal Forming Institute; add.aliases==Lukasiewicz - INOP; add.acronyms==L-INOP; add.wikipedia_url==https://pl.wikipedia.org/wiki/Sieć_Badawcza_Łukasiewicz_–_Instytut_Obróbki_Plastycznej; add.Wikidata==Q30290049; delete.types==Education; add.types==Facility;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
