### ISSUE TITLE
Modify Institute for Sustainable Technologies (https://ror.org/03yntf296)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#168]
Summary: Modify the information in an existing ROR record
Name of organization: Institute for Sustainable Technologies
ROR ID: https://ror.org/03yntf296
Description of change: The name of the organisation: Sieć Badawcza Łukasiewicz - Instytut Technologii Eksploatacji, link to the website: www.itee.radom.pl 

Curator recommendation (MG, AS):
- Change name to `Łukasiewicz - Institute for Sustainable Technologies`
- Move alias to Polish name label and change Polish name to `Sieć Badawcza Łukasiewicz - Instytut Technologii Eksploatacji`
- Change website to http://www.itee.radom.pl/
- Add Wikidata ID: https://www.wikidata.org/wiki/Q11713230
- Add Wikipedia page (Polish): https://pl.wikipedia.org/wiki/Sieć_Badawcza_Łukasiewicz_–_Instytut_Technologii_Eksploatacji

Update: change.name==Łukasiewicz - Institute for Sustainable Technologies; add.labels==Sieć Badawcza Łukasiewicz - Instytut Technologii Eksploatacji*Polish; delete.aliases==Instytut Technologii Eksploatacji; delete.links==http://www.itee.radom.pl/lang/index.php; add.links==http://www.itee.radom.pl/; add.Wikidata==Q11713230; add.wikipedia_url==https://pl.wikipedia.org/wiki/Sieć_Badawcza_Łukasiewicz_–_Instytut_Technologii_Eksploatacji;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
