### ISSUE TITLE
Add a new organization to ROR: FitzPatrick Institute of African Ornithology

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#17]
Summary of request: Add a new organization to ROR

Name of organization: FitzPatrick Institute of African Ornithology
Website: http://www.fitzpatrick.uct.ac.za/
Link to publications: http://www.fitzpatrick.uct.ac.za/fitz/publications
Organization type: Nonprofit
Wikipedia page: https://en.wikipedia.org/wiki/Percy_FitzPatrick_Institute_of_African_Ornithology
Wikidata ID: https://www.wikidata.org/wiki/Q2070244
ISNI ID: https://isni.org/isni/0000000110174395
GRID ID:
Crossref Funder ID: 501100020133
Other names for the organization: Percy FitzPatrick Institute of African Ornithology
Acronym/abbreviation:
Related organizations: https://ror.org/03p74gp79 (related)
City: Cape Town
Country: South Africa
Geonames ID: 3369157
Year established: 1960
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by mariagould** [comment]
This is a legacy issue from 2020 that came to ROR via Dryad. ROR suggested it to GRID but the addition was not approved. I am reopening the request so we can reconsider it for inclusion in ROR. This research institute is affiliated with the University of Cape Town but it was established as a nonprofit and appears to have independent staff and research activities. I would recommend we consider it for inclusion in ROR.

**Comment by carlyrobinson** [comment]
Within scope, recommend adding to registry.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05rgme147 in release v1.0.
