### ISSUE TITLE
Add a new organization to ROR: Association for Science

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#170]
Summary of request: Add a new organization to ROR

Name of organization: Association for Science
Website: http://www.4science.ge
Link to publications: https://journals.4science.ge/, https://doi.org/10.52340/sp1.1
Organization type: Other
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID:  
Other names for the organization:
Labels: ასოციაცია მეცნიერებისათვის*Georgian
Acronym/abbreviation: AFS
Related organizations: 
City: Tbilisi
Country: Georgia
Geonames ID: 611717
Other information about this request:

**Comment by adambuttrick** [comment]
I'm seeing fairly regular issue publication for most of their journals now in 2022:

https://journals.4science.ge/

What they appear to be doing is running an OJS platform for a number of Georgian e-journals, which may not be exactly the same thing as publishing them (most have origins at Georgian universities). We should discuss further whether this use case is in scope for ROR.

**Comment by adambuttrick** [comment]
In scope per discussion on June 7th 2022. Crossref membership, DOI distribution indicated on site.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00wvavs63 in release v1.3.
