### ISSUE TITLE
Add a new organization to ROR: Black Country Healthcare NHS Foundation Trust

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1723]
Summary of request: Add a new organization to ROR

Name of organization: Black Country Healthcare NHS Foundation Trust
Website: https://www.blackcountryhealthcare.nhs.uk
Link to publications: 
Organization type: Healthcare
Wikipedia page: https://en.wikipedia.org/wiki/Black_Country_Healthcare_NHS_Foundation_Trust
Wikidata ID: Q16842671
ISNI ID: 0000 0004 0498 6647
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City: Dudley
Country: UK
Geonames ID: 2650839
Year established: 2020
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Successor organization resulting from the merger of https://ror.org/04kk6v249 and https://ror.org/0013ks972, as identified in https://github.com/ror-community/ror-updates/issues/272. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1007/s00702-020-02292-x; https://doi.org/10.1017/dmp.2020.368; https://doi.org/10.1055/s-0041-1726618; https://doi.org/10.31729/jnma.6747; https://doi.org/10.1177/0253717620958380; https://doi.org/10.1177/00207640211011191; https://doi.org/10.4103/jfmpc.jfmpc_2124_20; https://doi.org/10.1016/j.psychres.2022.114439; https://doi.org/10.1016/j.psychres.2020.113598; https://doi.org/10.1016/j.jhin.2022.01.006

ORCID affiliation usage: https://orcid.org/0000-0001-8544-4484 ; https://orcid.org/0000-0001-5440-0905 ; https://orcid.org/0000-0001-7932-5585

**Comment by carlyrobinson** [comment]
Agreed. Recommend adding to ROR.

**Comment by adambuttrick** [comment]
Assigning to myself to create updates for inactive records, identifying this as the successor org, once the record has been created.
