### ISSUE TITLE
Add a new organization to ROR: Ukrainian Research Institute of Design and Ergonomics of the National Aviation University

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#173]
Summary of request: Add a new organization to ROR

Name of organization: Ukrainian Research Institute of Design and Ergonomics of the National Aviation University
Website: http://ndi-design.nau.edu.ua
Link to publications: http://ndi-design.nau.edu.ua/?page_id=132
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: УкрНДІ ДЕ НАУ
Acronym/abbreviation: UkrRIED NAU
Related organizations: National Aviation University https://ror.org/01f74x078 (parent)
City: Kyiv
Country: Ukraine
Established: 1966
Other information about this request:

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04pd1hv08 in release v1.0.
