### ISSUE TITLE
Modify the information in an existing ROR record: 
Kherson State Maritime Academy (https://ror.org/00dfbfw84)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#175]
Summary of request: Modify the information in an existing ROR record

Name of organization: Kherson State Maritime Academy
ROR ID: https://ror.org/00dfbfw84
Which part of the record needs to be changed? Organization website
Description of change: new website is ksma.ks.ua

Update: delete.links==http://ksmatest.net.ua/; add.links==https://ksma.ks.ua/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
