### ISSUE TITLE
Add a new organization to ROR: CARTOGRÁFICA DE CANARIAS

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#176]
Summary of request: Add a new organization to ROR

Name of organization: Cartográfica de Canarias
Website: https://www.grafcan.es
Link to publications: https://www.grafcan.es/quienes_somos
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: Cartográfica de Canarias, S. A.
Acronym/abbreviation: GRAFCAN
Related organizations: Parent: Gobierno de Canarias - https://ror.org/0172fj584
City: Santa Cruz de Tenerife
Country: SPAIN
Other information about this request:

**Comment by nlundvick** [comment]
I concur. Organization publishes research data/datasets and is in scope. Add to ROR

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/030wzvf80 in release v1.0.
