### ISSUE TITLE
Add a new organization to ROR: Institute of Information Technologies and Learning Tools of the NAES of Ukraine

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#179]
Summary of request: Add a new organization to ROR

Name of organization: Institute of Information Technologies and Learning Tools of the NAES of Ukraine
Website: https://iitlt.gov.ua/eng/
Link to publications: https://lib.iitta.gov.ua/view/divisions/inf=5Ftech=5Flear=5Ftool/
Wikipedia page: https://uk.wikipedia.org/wiki/Інститут_інформаційних_технологій_і_засобів_навчання_НАПН_України
Wikidata ID: Q12074710
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: Інститут інформаційних технологій і засобів навчання НАПН України
Acronym/abbreviation: IITLT NAES of Ukraine
Related organizations: National Academy of Educational Sciences of Ukraine - https://ror.org/05h1pdj54 (parent)
City: Kyiv
Country: Ukraine
Other information about this request:

**Comment by nlundvick** [comment]
I concur, organization is in scope. Add to ROR

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02qqjk369 in release v1.0.
