### ISSUE TITLE
Add a new organization to ROR: Internet Initiative Japan

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1797]
Summary of request: Add a new organization to ROR

Name of organization: Internet Initiative Japan
Website: http://www.iij.ad.jp
Link to publications: 
Organization type: Company
Wikipedia page: https://en.wikipedia.org/wiki/Internet_Initiative_Japan
Wikidata ID: Q1667971
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases:
Labels: インターネットイニシアティブ*Japanese
Acronym/abbreviation: IIJ
Related organizations: https://ror.org/05e0dm506 (parent)
City: Tokyo
Country: Japan
Geonames ID: 1850147
Year established: 1992
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Japanese ISP. Identified as parent on https://github.com/ror-community/ror-updates/issues/1433. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1145/2018436.2018473; https://doi.org/10.1145/1658978.1658990; https://doi.org/10.1145/1151659.1159956; https://doi.org/10.1145/948205.948207; https://doi.org/10.1109/jsac.2010.101002; https://doi.org/10.1145/1352664.1352675; https://doi.org/10.1145/1402946.1402996; https://doi.org/10.1109/infcom.2009.5061979; https://doi.org/10.1145/637201.637231; https://doi.org/10.1145/1644893.1644923

ORCID affiliation usage: https://orcid.org/0000-0002-4349-4691 ; https://orcid.org/0000-0001-9457-554X ; https://orcid.org/0000-0001-9098-6659

**Comment by mariagould** [comment]
I agree this is in scope given evidence of research activities and affiliation usage.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05c4bsk60 in release v1.17.
