### ISSUE TITLE
Modify the information in an existing ROR record: 
Ternopil State Medical University (https://ror.org/04gcpjy47)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#180]
Summary of request: Modify the information in an existing ROR record

Name of organization: Ternopil State Medical University
ROR ID: https://ror.org/04gcpjy47
Which part of the record needs to be changed? Primary name
Description of change: in 2019 University was awarded National  https://www.tdmu.edu.ua/en/2019/09/06/ternopil-medical-university-received-the-status-of-a-national-2/

We ask to change the name to I.Horbachevsky Ternopil National Medical University 

Update: change.name==I.Horbachevsky Ternopil National Medical University; change.wikipedia_url==https://en.wikipedia.org/wiki/Ternopil_National_Medical_University;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
