### ISSUE TITLE
Modify the information in an existing ROR record: Ministerio de Educación del Perú https://ror.org/00zd77s10

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#1802]
Summary of request: Modify the information in an existing ROR record

Name of organization: Ministerio de Educación del Perú
ROR ID: https://ror.org/00zd77s10
Which part of the record needs to be changed? website, labels, acronyms, wikipedia, wikidata
Description of change:
- Update website to https://www.gob.pe/minedu
- Add acronyms MINEDU, MED Perú
- Add English label Ministry of Education of Peru
- Add Wikipedia link https://es.wikipedia.org/wiki/Ministerio_de_Educaci%C3%B3n_(Per%C3%BA)
- Add Wikidata https://www.wikidata.org/wiki/Q3315247

Update: replace.links==https://www.gob.pe/minedu; add.acronyms==MINEDU; add.acronyms==MED Perú; add.labels==Ministry of Education of Peru*English; add.wikipedia_url==https://es.wikipedia.org/wiki/Ministerio_de_Educaci%C3%B3n_(Per%C3%BA);$

**Comment by adambuttrick** [comment]
Record updated in release v1.17.
