### ISSUE TITLE
Modify the information in an existing ROR record: University of California, San Francisco https://ror.org/043mz5j54

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#1805]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of California, San Francisco 
ROR ID: https://ror.org/043mz5j54
Which part of the record needs to be changed? alias
Description of change: add alias "UC San Francisco" to optimize discovery in searches and typeahead lookups

Update: add.aliases==UC San Francisco;$

**Comment by adambuttrick** [comment]
Record updated in release v1.17.
