### ISSUE TITLE
Modify the information in an existing ROR record: 
Broward County Public Schools https://ror.org/04m21fy21


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#182]
Summary of request: Modify the information in an existing ROR record

Name of organization: Broward County Public Schools
ROR ID: https://ror.org/04m21fy21
Which part of the record needs to be changed? Something else
Description of change: The displayed info on the record in the regular UI is correct, but the API record at https://api.ror.org/organizations/04m21fy21 provides an incorrect geo-location. Actually the latitude and longitude are correct as far as I can see, but the geonames info is wrong - this is a school district based in Fort Lauderdale, Florida, not in Madison, North Carolina as the geonames data indicates.

**Comment by KellyStathis** [comment]
I agree that this should be changed as described. The original metadata in GRID appears to be correct, so we could pull GeoNames IDs from there: https://www.grid.ac/institutes/grid.428307.a
