### ISSUE TITLE
Modify the information in an existing ROR record: 
ECI Telecom (Israel) and ECI Telecom (United States) https://ror.org/00pfa9y72


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#183]
Summary of request: Modify the information in an existing ROR record

Name of organization: ECI Telecom (Israel) and ECI Telecom (United States)
ROR ID: https://ror.org/00pfa9y72
Which part of the record needs to be changed? Primary name, Organization website
Description of change: (Change also applies for https://ror.org/01jdgyj97) ECI has merged with Ribbon - see https://info.rbbn.com/eci-now-ribbon/. We don't have a ROR for Ribbon so it might be ok to just change the name on the ECI records. On the other hand the parent entity is now the US (where Ribbon HQ is) so that might confuse things. So maybe new id(s) for Ribbon and redirect the existing ones? There's a Wikidata ID for Ribbon here: Q54871457, Wikipedia page https://en.wikipedia.org/wiki/Ribbon_Communications, main website is https://ribboncommunications.com/ now.

**Comment by nlundvick** [comment]
Ribbon acquired ECI in November 2019 (https://en.wikipedia.org/wiki/ECI_Telecom). Recommend redirecting ROR records for ECI to Ribbon record (see ticket #186), or merging with Ribbon record.

**Comment by mariagould** [comment]
Update: 

Prior GRID for ECI Telecom (US) redirects to Ribbon (US):  https://ror.org/01jdgyj97 | grid.479738.6
GRID record for Ribbon (US) maps to ROR ID for Genband: https://ror.org/02mzerg05

Prior GRID for ECI Telecom (Israel) redirects to Ribbon (Israel): https://ror.org/00pfa9y72 | grid.434142.4
GRID record for Ribbon (Israel) maps to this ROR ID: https://ror.org/00pfa9y72

Ribbon (US) is parent of Ribbon (Israel) in GRID

**Comment by mariagould** [comment]
This has been addressed via #207. However, the original ID for ECI Telecom https://ror.org/01jdgyj97 no longer resolves because ROR does not yet support redirect functionality. We will plan to enable a redirect in future. 

When we do wholesale work across the registry to handle records that were made inactive by GRID, we can address the question of how to represent historical relationships and historical names in the metadata. 

For now this issue can be closed.
