### ISSUE TITLE
Modify the information in an existing ROR record: 
Laser Laboratorium Gottingen https://ror.org/00ecchs44


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#184]
Summary of request: Modify the information in an existing ROR record

Name of organization: Laser Laboratorium Gottingen
ROR ID: https://ror.org/00ecchs44
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website
Description of change: Name is now 'Institut für Nanophotonik', acronym IFNANO, new website is https://www.ifnano.de/ - see the old website http://www.llg-ev.de/ for info on the change.

**Comment by carlyrobinson** [comment]
Agree with @MSpenger recommendation.
