### ISSUE TITLE
Modify the information in an existing ROR record: 
Genband (United States) https://ror.org/02mzerg05


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#186]
Summary of request: Modify the information in an existing ROR record

Name of organization: Genband (United States)
ROR ID: https://ror.org/02mzerg05
Which part of the record needs to be changed? Primary name, Organization website, Other IDs for the organization
Description of change: If you follow the current website link, it goes to Ribbon Communications (see previous update request for ECI Telecom - https://ror.org/00pfa9y72). From the wikipedia page it appears this merged to form Ribbon in 2017. Since this is already based in the US if we are not creating a new ROR record for Ribbon then it might be best to rename this record as Ribbon (and update the website etc.) Otherwise this would be another one to redirect/merge when we can do that.

**Comment by nlundvick** [comment]
GENBAND and Sonus Networks merged in 2017 to form Ribbon Communications. Recommend updating metadata of ROR record for GENBAND to Ribbon. Ticket #183 - Ribbon acquired ECI in November 2019 (https://en.wikipedia.org/wiki/ECI_Telecom). Recommend redirecting ROR records for ECI to Ribbon record, or merging with Ribbon record.

**Comment by mariagould** [comment]
Update:

Prior GRID for ECI Telecom (US) redirects to Ribbon (US): https://ror.org/01jdgyj97 | grid.479738.6
GRID record for Ribbon (US) maps to ROR ID for Genband: https://ror.org/02mzerg05

Prior GRID for ECI Telecom (Israel) redirects to Ribbon (Israel): https://ror.org/00pfa9y72 | grid.434142.4
GRID record for Ribbon (Israel) maps to this ROR ID: https://ror.org/00pfa9y72

Ribbon (US) is parent of Ribbon (Israel) in GRID

**Comment by mariagould** [comment]
This has been addressed via #207
