### ISSUE TITLE
Project: Portuguese Primary Names for Brazilian Organizations

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1876]
Staff from the Universidade do Estado de Santa Catarina have submitted a list of organizations where they have requested the primary name be in Portuguese instead of English. We should consult with our regional contacts in Brazil and determine whether these changes are appropriate, since they were submitted by a third party.

[20221220_Brazil_bulk_name_change_request.xlsx](https://github.com/ror-community/ror-updates/files/10272638/20221220_Brazil_bulk_name_change_request.xlsx)

**Comment by mariagould** [comment]
Tasks:

- [ ] Review entries in submitted spreadsheet
- [ ] Check if the provided Portuguese names are correct
- [ ] Check existing ROR record to see if a Portuguese name is already present and if it matches what was submitted
- [ ] Determine what the correct Portuguese name should be
- [ ] Determine which name(s) need to be captured in the `alias` field versus `labels`
- [ ] Check other metadata in ROR to see if other changes are needed: organization website and external IDs, 
- [ ] Add comments in the spreadsheet about which changes need to be made. Use explicit instructions like "change", "add", "replace", "delete"
