### ISSUE TITLE
Add a new organization to ROR: 
 
Paveprime Ltd

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#188]
Summary of request: Add a new organization to ROR

Name of organization: Paveprime Ltd
Website: http://www.paveprime.com
Link to publications: http://www.paveprime.com/research.html
Organization type: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: None
Acronym/abbreviation: PPL
Related organizations: 
City: Purley
Country: United Kingdom
Other information about this request:

**Comment by KellyStathis** [comment]
Paveprime appears to primarily be involved in research on the "CIDOC object-oriented Conceptual Reference Model" (CRM). For example, the most recent publication on the list linked above: http://www.cidoc-crm.org/Version/version-7.1. Stephen Stead, the director of Paveprime, is a co-author on this. He also lists his affiliation on the page for the SIG for CIDOC CRM here: http://www.cidoc-crm.org/sig-members-list

However, I am not sure if the organization is run by more than one person, which is one criterion for inclusion. Stephen Stead is listed as the director. Do we have any further information on additional staff?

**Comment by mariagould** [comment]
Per curation group discussion, it was determined that we should proceed to create a ROR ID for this organization on the basis of its documented research activities.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05bgydj64 in release v1.0.
