### ISSUE TITLE
Modify the information in an existing ROR record: National Kaohsiung Normal University https://ror.org/04tsc8g87

### ISSUE THREAD

**Issue by zambujo** [ror-community/ror-updates#1889]
Summary of request: Modify the information in an existing ROR record

Name of organization: National Kaohsiung Normal University
ROR ID: https://ror.org/04tsc8g87
Which part of the record needs to be changed? Organization website
Description of change: The organization website in the ROR record is an invalid IP-like address http://140.127.40.68/files/90-1000-40.php - Wikidata points to https://w3.nknu.edu.tw which is the correct website URL for this organization.

Update: replace.links==https://w3.nknu.edu.tw;$

**Comment by adambuttrick** [comment]
Current link in ROR does not resolve while the provided is for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
