### ISSUE TITLE
Modify the information in an existing ROR record: Liaoning University of International Business and Economics https://ror.org/03m6hya42

### ISSUE THREAD

**Issue by zambujo** [ror-community/ror-updates#1890]
Summary of request: Modify the information in an existing ROR record

Name of organization:  Liaoning University of International Business and Economics
ROR ID:  https://ror.org/03m6hya42
Which part of the record needs to be changed?  Organization website
Description of change:
The organization website in the ROR record is an invalid IP-like address http://219.216.225.20/yy/index.asp - Wikidata points to https://www.luibe.edu.cn/ which is the correct website URL for this organization.

Update: replace.links==https://www.luibe.edu.cn;$

**Comment by adambuttrick** [comment]
Current link in ROR does not resolve while the provided does.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
