### ISSUE TITLE
Modify the information in an existing ROR record: Weihai Maternal and Child Health https://ror.org/0384ea937Hospital 

### ISSUE THREAD

**Issue by zambujo** [ror-community/ror-updates#1891]
Summary of request: Modify the information in an existing ROR record

Name of organization: Weihai Maternal and Child Health Hospital
ROR ID: https://ror.org/0384ea937
Which part of the record needs to be changed? Organization website
Description of change: Replace http://180.76.178.48:9999/whfy/ with http://www.whhospital.com.cn

Update: replace.links==http://www.whhospital.com.cn;$

**Comment by adambuttrick** [comment]
Current link in ROR does not resolve while the provided does.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
