### ISSUE TITLE
Modify the information in an existing ROR record: Rajasthan University of Health Sciences https://ror.org/04f5g2442

### ISSUE THREAD

**Issue by zambujo** [ror-community/ror-updates#1892]
Summary of request: Modify the information in an existing ROR record

Name of organization: Rajasthan University of Health Sciences
ROR ID: https://ror.org/04f5g2442
Which part of the record needs to be changed? Organization website
Description of change: Replace http://216.55.163.156:90/RUHS/index with https://www.ruhsraj.org

Update: replace.links==https://www.ruhsraj.org;$

**Comment by adambuttrick** [comment]
Current link in ROR does not resolve while the provided does.
