### ISSUE TITLE
Add a new organization to ROR: Yale Peabody Museum

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#19]
Summary of request: Add a new organization to ROR

Name of organization: Yale Peabody Museum
Website: https://peabody.yale.edu/
Link to publications: https://peabody.yale.edu/explore/publications
Organization type: Archive
Wikipedia page: https://en.wikipedia.org/wiki/Peabody_Museum_of_Natural_History
Wikidata ID: https://www.wikidata.org/wiki/Q122945
ISNI ID: https://isni.org/isni/0000000121679241
GRID ID:
Crossref Funder ID:
Other names for the organization: Peabody Museum of Natural History
Acronym/abbreviation:
Related organizations: https://ror.org/03v76x132 (parent)
City: New Haven, CT
Country: United States
Geonames ID: 4839366
Year established: 1866
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by mariagould** [comment]
This is a legacy request from 2020. The request came from Dryad for the purpose of identifying datasets created by Peabody-affiliated researchers. ROR submitted it to GRID for inclusion but it was not approved by GRID at the time. I am reinstating the request now so that we can create the entry in ROR. The museum is affiliated with Yale University but per our criteria for inclusion regarding museums affiliated with universities, I think we should proceed with creating a separate ID.

**Comment by carlyrobinson** [comment]
Within scope, recommend adding to registry.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03db5ay71 in release v1.1.
