### ISSUE TITLE
Add a new organization to ROR: The Academic College Levinsky-Wingate

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1909]
Summary of request: Add a new organization to ROR

Name of organization: Levinsky-Wingate Academic College
Website: https://www.l-w.ac.il
Link to publications: 
Organization type: Education
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Academic College Levinsky-Wingate; Levinsky-Wingate Academic Center
Labels: המרכז האקדמי לוינסקי-וינגייט*Hebrew
Acronym/abbreviation:
Related organizations: https://ror.org/000be6g31 (predecessor) https://ror.org/00nydej67 (predecessor)
City: Tel Aviv
Country: Israel
Geonames ID: 293397
Year established: 2022
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University resulting from the merger of https://ror.org/000be6g31 and https://ror.org/00nydej67, as described in https://github.com/ror-community/ror-updates/issues/1903. Would be in scope by being the successor organizations for these records. Does not appear to have a single website or location, so we will have to choose one or another until we add functionality to support multiple addresses.

**Comment by adambuttrick** [comment]
Requestor provided new website and identified Tel Aviv as the primary address.

**Comment by mariagould** [comment]
I agree this should be added. I'm not clear as to which version of the English name to use, as the website and affiliation usage seems to indicate "Levinsky-Wingate Academic Center"

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00hayyk04 in release v1.18.
