### ISSUE TITLE
Modify the information in an existing ROR record: 
Azərbaycan Respublikasının Təhsil Institutu https://ror.org/01ytcra85


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#191]
Summary of request: Modify the information in an existing ROR record

Name of organization: Azərbaycan Respublikasının Təhsil Institutu
ROR ID: https://ror.org/01ytcra85
Which part of the record needs to be changed? Primary name
Description of change: Name should be stated in English like this: Institute of Education of the Republic of Azerbaijan 

The reason for this change is that we try to use one unique name in all the platforms making it easier for our researchers and employees to find their affiliated institution. 

Update: change.name==Institute of Education of the Republic of Azerbaijan; delete.links==https://www.arti.edu.az/az/#; add.links==https://www.arti.edu.az/az/; add.Wikidata==Q25536880; change.wikipedia_url==https://az.wikipedia.org/wiki/Azərbaycan_Respublikasının_Təhsil_İnstitutu;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
