### ISSUE TITLE
Modify University of the French West Indies and Guiana (https://ror.org/02ryfmr77)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#192]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of the French West Indies and Guiana
ROR ID: https://ror.org/02ryfmr77
Which part of the record needs to be changed?
Description of change: University of the French West Indies and Guiana no longer exists since 2015. Following a split, two universities were created:

- University of the French West Indies
- University of Guiana

**Comment by arthurpsmith** [comment]
I agree with Maria on what the new name should be (what is missing from ROR right now). As this is a split it seems like we should somehow deprecate this record and create a new one with the new name? But maybe just changing the name as proposed here is ok.
