### ISSUE TITLE
Modify the information in an existing ROR record: Solutions for Tomorrow https://ror.org/00mxv3x47

### ISSUE THREAD

**Issue by zambujo** [ror-community/ror-updates#1921]
Summary of request: Modify the information in an existing ROR record

Name of organization: Solutions for Tomorrow
ROR ID:  https://ror.org/00mxv3x47
Which part of the record needs to be changed? Organization website
Description of change: Replace http://www.solutionsfortomorrow.se/1.0.1.0/3/1/ with http://www.solutionsfortomorrow.se/

Update: replace.links==http://www.solutionsfortomorrow.se;$

**Comment by adambuttrick** [comment]
Top-level domain for existing link on the record.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
