### ISSUE TITLE
Modify the information in an existing ROR record: Institute of Nuclear Energy Research https://ror.org/052jx3443

### ISSUE THREAD

**Issue by zambujo** [ror-community/ror-updates#1922]
Summary of request: Modify the information in an existing ROR record

Name of organization: Institute of Nuclear Energy Research
ROR ID: https://ror.org/052jx3443
Which part of the record needs to be changed? Organization website
Description of change: Replace http://192.192.22.67/siteiner/wSite/mp?mp=INER_e with https://www.iner.gov.tw/

Update: replace.links==https://www.iner.gov.tw;$

**Comment by adambuttrick** [comment]
Confirmed link is that for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
