### ISSUE TITLE
Modify the information in an existing ROR record: Orthopterists' Society https://ror.org/03nm7c278

### ISSUE THREAD

**Issue by zambujo** [ror-community/ror-updates#1923]
Summary of request: Modify the information in an existing ROR record

Name of organization: Orthopterists' Society
ROR ID: https://ror.org/03nm7c278
Which part of the record needs to be changed? Organization website
Description of change: Replace http://140.247.96.247/orthsoc/ with https://orthsoc.org/

Update: replace.links==https://orthsoc.org;$

**Comment by adambuttrick** [comment]
Confirmed link is that for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
