### ISSUE TITLE
Modify the information in an existing ROR record: International Network for Bamboo and Rattan https://ror.org/02h5sfg65

### ISSUE THREAD

**Issue by zambujo** [ror-community/ror-updates#1926]
Summary of request: Modify the information in an existing ROR record

Name of organization: International Network for Bamboo and Rattan
ROR ID: https://ror.org/02h5sfg65
Which part of the record needs to be changed? Organization website and name
Description of change: Replace http://118.26.187.104/Index.shtml with https://www.inbar.int/ and *International Network for Bamboo and Rattan* with *International Bamboo and Rattan Organisation*

Update: change.name==International Bamboo and Rattan Organization; add.aliases==International Bamboo and Rattan Organisation; add.aliases==International Network for Bamboo and Rattan; replace.links==https://www.inbar.int;$

**Comment by adambuttrick** [comment]
Name change corresponds to organization's website and branding.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
