### ISSUE TITLE
Modify the information in an existing ROR record: Arbeitsgemeinschaft Gynäkologische Onkologie Studiengruppe https://ror.org/01kjfnp05

### ISSUE THREAD

**Issue by zambujo** [ror-community/ror-updates#1927]
Summary of request: Modify the information in an existing ROR record

Name of organization: Arbeitsgemeinschaft Gynäkologische Onkologie Studiengruppe
ROR ID: https://ror.org/01kjfnp05
Which part of the record needs to be changed? Organization website
Description of change: Replace http://85.158.4.112/ago-ovar.de/en/profile-3.html with https://ago-ovar.de/

Update: replace.links==https://ago-ovar.de; add.aliases==AGO Studiengruppe;$

**Comment by adambuttrick** [comment]
Confirmed link is that for organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
