### ISSUE TITLE
Modify the information in an existing ROR record: Instituto Tecnológico de Puebla https://ror.org/02jsxsw65

### ISSUE THREAD

**Issue by zambujo** [ror-community/ror-updates#1928]
Summary of request: Modify the information in an existing ROR record

Name of organization: Instituto Tecnológico de Puebla
ROR ID: https://ror.org/02jsxsw65
Which part of the record needs to be changed? Organization website
Description of change: Replace http://148.208.231.5/portalitp/ with http://www.itpuebla.edu.mx/

Update: replace.links==http://www.itpuebla.edu.mx;$

**Comment by adambuttrick** [comment]
Confirmed link is that for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
