### ISSUE TITLE
Add a new organization to ROR: Instituto de Física Gleb Wataghin

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1933]
Summary of request: Add a new organization to ROR

Name of organization: Instituto de Física Gleb Wataghin
Website: https://portal.ifi.unicamp.br
Link to publications: 
Organization type: Facility
Wikipedia page: https://pt.wikipedia.org/wiki/Instituto_de_F%C3%ADsica_Gleb_Wataghin
Wikidata ID: Q10302851
ISNI ID: 0000 0000 9739 9759
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: IFI; IFI GW
Aliases: Instituto de Física "Gleb Wataghin"; Gleb Wataghin Institute of Physics
Related organizations: https://ror.org/04wffgt70 (parent)
City: Campinas
Country: Brazil
Geonames ID: 3467865
Year established: 1967
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Submitted as part of https://github.com/ror-community/ror-updates/issues/1932, physics research institute at https://ror.org/04wffgt70. Funds and employs researchers. Solid affiliation usage. Should be added. 

Publication affiliation usage: https://doi.org/10.1103/physreva.80.024103; https://doi.org/10.1016/j.physletb.2018.06.019; https://doi.org/10.1103/physreva.81.052107; https://doi.org/10.1103/physrevlett.90.055504; https://doi.org/10.1016/0378-4371(83)90013-4; https://doi.org/10.1016/j.jmmm.2009.06.086; https://doi.org/10.1038/nature10461; https://doi.org/10.1103/physrevlett.85.4124

ORCID affiliation usage: https://orcid.org/0000-0002-2134-3876 ; https://orcid.org/0000-0001-6764-1839 ; https://orcid.org/0000-0003-3200-5693

**Comment by arthurpsmith** [comment]
Hmm, I thought we'd handled these sort of university institutes generally as part of the university and not eligible for ROR. The curation policy document says "Add to ROR if: publishing & using that affiliation, have separate funding source(s), dedicated staff, and have standalone (separate from university) website and branding." 
Yes, they have a good history of publishing and using that affiliation (but always along with UNICAMP). I don't see separate funding sources, and their staff all appear to be at the university, not associated with the institute independent of the university. The website domain is under unicamp.br and UNICAMP is mentioned on their web pages. Adding this might be a good idea, but I think adding it also opens up a lot of similar entities that we might not want to tackle...

**Comment by adambuttrick** [comment]
Out of scope, per curation team discussion. Institute has never existed separate from the university.
