### ISSUE TITLE
Add a new organization to ROR: Universidad Técnica Nacional (UTN)

### ISSUE THREAD

**Issue by jorgelpolanco** [ror-community/ror-updates#1941]
Summary of request: Add a new organization to ROR

Name of organization: Universidad Técnica Nacional
Website: https://www.utn.ac.cr
Link to publications: 10.22458/caes.v12i2.3854 , 10.4067/S0718-19572016000300007 , 10.18475/cjos.v51i2.a4, 10.11606/issn.2316-9079.v20i2p203-207, 10.15517/revedu.v44i2.39787
Organization type: Education
Wikipedia page: https://es.wikipedia.org/wiki/Universidad_T%C3%A9cnica_Nacional_(Costa_Rica)
Wikidata ID: Q9091616
ISNI ID: 0000 0004 0512 8855
GRID ID:
Crossref Funder ID:
Other names for the organization:
Acronym/abbreviation: UTN
Related organizations: 
City: Alajuela
Country: Costa Rica
Geonames ID: 3624955
Year established: 2008
How will a ROR ID for this organization be used?  for publications
Other information about this request:

**Comment by adambuttrick** [comment]
Public university in Costa Rica. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.15517/am.v24i1.9790; https://doi.org/10.1007/s10499-021-00751-0; https://doi.org/10.30909/vol.04.s1.viixxxiii; https://doi.org/10.1016/j.toxicon.2015.10.001; https://doi.org/10.5713/ajas.16.0821; https://doi.org/10.4067/s0718-19572016000300007; https://doi.org/10.1016/j.livsci.2016.09.008; https://doi.org/10.15517/rbt.v58i4.5423

ORCID affiliation usage: https://orcid.org/0000-0002-4430-9486 ; https://orcid.org/0000-0002-7614-9392 ; https://orcid.org/0000-0002-0211-3477

**Comment by arthurpsmith** [comment]
Looks good to me. Note that the suggested Wikidata ID was wrong (it is for a disambiguation item listing universities with the same name). I added the correct ID above.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01s9pbd40 in release v1.18.
