### ISSUE TITLE
Add a new organization to ROR: Japan Society of Civil Engineers

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1958]
Summary of request: Add a new organization to ROR

Name of organization: Japan Society of Civil Engineers
Website: https://www.jsce-int.org
Link to publications: 
Organization type: Nonprofit
Wikipedia page: https://en.wikipedia.org/wiki/Japan_Society_of_Civil_Engineers
Wikidata ID: Q11423671
ISNI ID: 0000 0004 1757 1555
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: JSCE
Aliases: どぼくがっかい; ドボクガッカイ
Labels: 公益社団法人土木学会*Japanese; 
Related organizations: 
City: Tokyo
Country: Japan
Geonames ID: 1850147
Year established: 1914
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Japanese professional society for civil engineers. Funds and employs researchers. Solid affiliation usage. We have similar organizations in ROR (e.g. https://ror.org/05tmv0d13 and https://ror.org/02apbz725). Should be added.

Publication affiliation usage: https://doi.org/10.2208/jscej.1986.372_167; https://doi.org/10.2208/jscej1969.1982.325_61; https://doi.org/10.2208/jscej.1986.376_221

ORCID affiliation usage: https://orcid.org/0000-0002-2810-8801 ; https://orcid.org/0000-0003-1197-302X ; https://orcid.org/0000-0003-3492-7421

**Comment by mariagould** [comment]
I agree this is in scope as given evidence of research activities and affiliation usage, and similar organizations in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05c8wa765 in release v1.18.
