### ISSUE TITLE
Modify the information in an existing ROR record: 
University of Colorado Anschutz Medical Campus https://ror.org/03wmf1y16


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#196]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Colorado Anschutz Medical Campus
ROR ID: https://ror.org/03wmf1y16
Which part of the record needs to be changed? Other IDs for the organization
Description of change: The entry for CU Anschutz doesn't have the Crossref Funder ID. Can that be added?

--
Curator recommendation (MG):
(1) Add two new Funder IDs:
100014450 (Anschutz Medical Campus, University of Colorado) (preferred)
100016193 (University of Colorado School of Medicine, Anschutz Medical Campus)

(2) Update URL:
https://www.cuanschutz.edu/

Update: add.FundRef==100016193; add.FundRef==100014450; delete.links==http://www.ucdenver.edu/anschutz/Pages/landing.aspx; add.links==https://www.cuanschutz.edu/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
