### ISSUE TITLE
Add a new organization to ROR: 
 
Long Term Ecological Research Network

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#197]
Summary of request: Add a new organization to ROR

Name of organization: Long Term Ecological Research Network
Website: https://lternet.edu
Link to publications: https://lternet.edu/bibliography/
Organization type: Other
Wikipedia page: https://en.wikipedia.org/wiki/Long_Term_Ecological_Research_Network
Wikidata ID: Q6673290
ISNI ID: 0000 0000 8820 3822
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Long-Term Ecological Research Network, LTERN, LTER Network
Acronym/abbreviation: LTER
Related organizations: Part of (child) institutions:
Andrews Forest (AND)
Arctic LTER (ARC)
Baltimore Ecosystem Study (BES)
Beaufort Lagoon Ecosystem (BLE)
Bonanza Creek LTER (BNZ)
Central Arizona - Phoenix (CAP)
Central Plains Experimental Range
California Current Ecosystem (CCE)
Cedar Creek Ecosystem Science Reserve (CDR)
Coweeta LTER (CWT)
Florida Coastal Everglades (FCE)
Georgia Coastal Ecosystems (GCE)
Harvard Forest (HFR)
Hubbard Brook Experimental Forest LTER (HBR)
Jornada Basin LTER (JRN)
Kellogg Biological Station (KBS)
Konza Prairie (KNZ)
Luquillo Experimental Forest (LUQ)
McMurdo Dry Valleys (MCM)
Minneapolis St. Paul LTER (MSP)
Mo'orea Coral Reef (MCR)
Niwot Ridge LTER (NWT)
North Temperate Lakes (NTL)
Northeast U.S. Shelf LTER (NES)
Northern Gulf of Alaska LTER (NGA)
Palmer Station Antarctica (PAL)
Plum Island Ecosystem (PIE)
Santa Barbara Coastal (SBC)
Sevilleta National Wildlife Refuge (SEV)
Shortgrass Steppe LTER (SGS)
Virginia Coast Reserve Long-Term Ecological Research (VCR)
City: Santa Barbara, CA
Country: United States
Other information about this request: Some of these answers are tentative and may require discussion. We will want to align for all of the LTER sites.

**Comment by arthurpsmith** [comment]
I updated with the Wikidata ID and ISNI ID. We already approved the child org in request #32 - I think it's clear this should have a ROR id also.

**Comment by KellyStathis** [comment]
I agree this organization should have a ROR ID.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/039kwqk96 in release v1.0.
