### ISSUE TITLE
Modify the information in an existing ROR record: 
DataONE https://ror.org/00hr5y405


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#198]
Summary of request: Modify the information in an existing ROR record

Name of organization: DataONE
ROR ID: https://ror.org/00hr5y405
Which part of the record needs to be changed? Something else
Description of change: The primary address for DataONE has changed from UNM to UCSB. An accurate geonames.org entry for our address would be https://www.geonames.org/5404893/ We are an off-campus facility affiliated with UCSB, with some components on campus (at the data center). You can see our address on our web site here: https://www.dataone.org/contact/

Other information about this request: DataONE was originally administered from 2009-2019 through the University of New Mexico with UCSB and University of Tennessee as a partner. In 2019, administration transferred to UCSB. Project management transition details can be found here: https://old.dataone.org/news/dataone-begins-transition-new-leadership

Update: change.Geonames==5392952;

**Comment by mariagould** [comment]
Let's use the Geonames for the city of Santa Barbara instead, as we are going to focus on city-level geolocation: 5392952

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
