### ISSUE TITLE
Add a new organization to ROR: Real Sociedad Española de Química

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1986]
Summary of request: Add a new organization to ROR

Name of organization: Real Sociedad Española de Química
Website: https://rseq.org
Link to publications: https://rseq.org/publicaciones/
Organization type: Other
Wikipedia page: https://es.wikipedia.org/wiki/Real_Sociedad_Espa%C3%B1ola_de_Qu%C3%ADmica
Wikidata ID: Q9067104
ISNI ID: 0000 0001 0667 1479
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: RSEQ
Aliases: Spanish Royal Society of Chemistry; 
Labels:
Related organizations: https://ror.org/01m0pag22 (related)
City: Madrid
Country: Spain
Geonames ID: 3117735
Year established: 1903
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Spanish academic society, first identified in https://github.com/ror-community/ror-updates/issues/1982. Limited affiliation usage - only one instance I can find. But publishes [three journals](https://rseq.org/publicaciones/) and thus would be in scope for our publisher use case. 

Publication affiliation usage: https://doi.org/10.1038/nchem.1014

ORCID affiliation usage: https://orcid.org/0000-0001-8325-2032 ; https://orcid.org/0000-0001-8241-3463 ; https://orcid.org/0000-0002-4892-7775

**Comment by mariagould** [comment]
I agree this is in scope as an academic society and given evidence of research activities and affiliation usage. 

I made a small edit to the Spanish name (add accent over the first "i" in "Química")

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02x4dn920 in release v1.18.
