### ISSUE TITLE
Modify the information in an existing ROR record: 
Bundesanstalt für Wasserbau https://ror.org/03z6hnk02


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#199]
Summary of request: Modify the information in an existing ROR record

Name of organization: Bundesanstalt für Wasserbau
ROR ID: https://ror.org/03z6hnk02
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website, Other IDs for the organization
Description of change: 1.) Please change the primary name to: Bundesanstalt für Wasserbau
English name (only secondary!): Federal Waterways Engineering and Research Institute

2.) Please add - already existing IDs:
ISNI: 0000 0001 0057 9452
grid.493870.1
Ringold: 130420

3.) Please, change our website: 
http://www.baw.de

4.) Please add:
https://de.wikipedia.org/wiki/Bundesanstalt_für_Wasserbau

5.) Please add:
https://orcid.org/members/0010f00002GWMgjAAH-bundesanstalt-fuer-wasserbau

**Comment by MSpenger** [comment]
Looks good to me. 

Maybe the WikiData-ID could also be added: https://www.wikidata.org/wiki/Q1005545

Interesting aspect of including the ORCID Member-ID.

**Comment by arthurpsmith** [comment]
Looks fine to me also (and doesn't need a second review here I think). The main change they are requesting is to make the German name and website the primary ones, which I think is fine. Can we actually add Ringgold and ORCID Member Id's? Probably a good idea if it's possible.

**Comment by mariagould** [comment]
Just a note that we can't add Ringgold and ORCID Member IDs currently but this is something to explore in future.
