### ISSUE TITLE
Add a new organization to ROR: Tokai University Tokyo Hospital

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#1998]
Summary of request: Add a new organization to ROR

Name of organization: Tokai University Tokyo Hospital
Website: https://www.tokyo-hosp.tokai.ac.jp
Link to publications: 
Organization type: Healthcare
Wikipedia page: https://ja.wikipedia.org/wiki/%E6%9D%B1%E6%B5%B7%E5%A4%A7%E5%AD%A6%E5%8C%BB%E5%AD%A6%E9%83%A8%E4%BB%98%E5%B1%9E%E6%9D%B1%E4%BA%AC%E7%97%85%E9%99%A2
Wikidata ID: Q11527839
ISNI ID: 0000 0004 1764 0303
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Aliases: とうかいだいがくいがくぶふぞくとうきょうびょういん; トウカイダイガクイガクブフゾクトウキョウビョウイン
Labels: 東海大学医学部付属東京病院 *Japanese
Related organizations: https://ror.org/01p7qe739 (related)
City: Tokyo
Country: Japan
Geonames ID: 1850147
Year established: 1983
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by mariagould** [comment]
This is fine to add. We already have the university's other hospitals represented in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/034kd8j82 in release v1.18.
