### ISSUE TITLE
Update Finnish Food Authority https://ror.org/01zmp8b44

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#2]
ROR ID: https://ror.org/01zmp8b44
Summary of changes to be made: update website, name, and ISNI

Website: www.foodauthority.fi
Name: Finnish Food Authority
ISNI: https://isni.org/isni/0000000492902959

Update: replace.links==www.foodauthority.fi/;$

**Comment by adambuttrick** [comment]
Changes (aside from link), appear to have already been applied to the record, I'm guessing as part of a GRID update. @mariagould could you reassess whether this update is still needed?

**Comment by mariagould** [comment]
This is a successor organization to the Finnish Food Safety Authority Evira, which was associated with grid.425556.5 and https://ror.org/01zmp8b44. 

GRID created a new record for the successor org, Finnish Food Authority, which corresponds to https://ror.org/00dpnza76 and https://grid.ac/institutes/grid.509946.7. 

The change to the website that was originally requested was to update the URL to [www.foodauthority.fi](http://www.foodauthority.fi/). This redirects to https://www.ruokavirasto.fi/, which is the URL we have in our metadata.

Therefore, the metadata that we currently have for the Finnish Food Authority (https://ror.org/00dpnza76) appears to be correct so this issue can be closed. I will update the ID in the issue title for clarity. When we do a comprehensive review of ROR IDs that need to be redirected as per merging performed by GRID, the prior ID https://ror.org/01zmp8b44 will be redirected.
