### ISSUE TITLE
Modify the information in an existing ROR record: 
Library college https://ror.org/044radm67


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#201]
Summary of request: Modify the information in an existing ROR record

Name of organization: Library college
ROR ID: https://ror.org/044radm67
Which part of the record needs to be changed? Organization website
Description of change: This organization is a historical one. This college was discontinued in 1980. So, this record should not have a website...

Curator comments (MG/AS):
- Change name to Junior College Library Association
- Change Japanese name to 私立短期大学図書館協議会
- Remove Wikidata ID

Update: change.name==Junior College Library Association; delete.labels==図書館短期大学; add.labels==私立短期大学図書館協議会*Japanese; delete.Wikidata==Q10926283;

**Comment by mariagould** [comment]
The requestor (not affiliated with the organization) notes that the college has been discontinued, but the website does not seem to indicate that this is the case. However, it does seem as though the name in the record should be updated to "Private Junior College Library Council".

**Comment by arthurpsmith** [comment]
Agreed, from the website it appears to be something different than the current name indicates. However, the English name on the website is "Junior College Library Association", so we should probably prefer that name for the main label/English name?
The Japanese name we have also appears to be incorrect - from the website the name in Japanese I believe should be:
私立短期大学図書館協議会
(which is "Private Junior College Library Council" from Google Translate - is that where you got that English name?)
The Wikidata ID in any case is what points to the library college that came to an end in 1980, which is presumably where the person suggesting the problem discovered this, so we should remove that Wikidata ID also.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
