### ISSUE TITLE
Add a new organization to ROR: Institute of Informatics & Telecommunications

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2012]
Summary of request: Add a new organization to ROR

Name of organization: Institute of Informatics & Telecommunications
Website: https://www.iit.demokritos.gr
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Aliases: Institute of Informatics and Telecommunications
Labels: Ινστιτούτο Πληροφορικής & Τηλεπικοινωνιών*Greek
Related organizations: https://ror.org/038jp4m40 (parent)
City: Aghia Paraskevi
Country: Greece
Geonames ID: 6692232
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Originally submitted as part of https://github.com/ror-community/ror-updates/issues/2008, technology research center in Greece and child of https://ror.org/038jp4m40. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1049/iet-com.2009.0107; https://doi.org/10.1109/aqtr.2008.4588768; https://doi.org/10.1145/2382434.2382436; https://doi.org/10.1016/j.giq.2015.07.003; https://doi.org/10.1117/12.850098

**Comment by mariagould** [comment]
I think this is fine to add. The institutes of the national research center are independently administered and we already have one represented in ROR (https://ror.org/03znpfq81)

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0396t6k89 in release v1.18.
