### ISSUE TITLE
Add a new organization to ROR: Institute of Nanoscience and Nanotechnology

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2015]
Summary of request: Add a new organization to ROR

Name of organization: Institute of Nanoscience and Nanotechnology
Website: https://inn.demokritos.gr
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: INN
Related organizations: https://ror.org/038jp4m40 (parent)
City: Aghia Paraskevi
Country: Greece
Geonames ID: 6692232
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Originally submitted as part of https://github.com/ror-community/ror-updates/issues/2008, nanotechnology research center in Greece and child of https://ror.org/038jp4m40. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1117/12.2306509; https://doi.org/10.1117/1.jmm.17.4.041009; https://doi.org/10.1117/12.2297264; https://doi.org/10.1117/1.jmm.16.2.024001; https://doi.org/10.1117/12.2294617; https://doi.org/10.1117/12.2294060

**Comment by mariagould** [comment]
I think this is fine to add. The institutes of the national research center are independently administered and we already have one represented in ROR (https://ror.org/03znpfq81)

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/022j9ve58 in release v1.18.
