### ISSUE TITLE
Add a new organization to ROR: Institute of Nuclear & Radiological Sciences and Technology, Energy & Safety

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2016]
Summary of request: Add a new organization to ROR

Name of organization: Institute of Nuclear & Radiological Sciences and Technology, Energy & Safety
Website: https://inrastes.demokritos.gr
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: INRASTES
Aliases:
Labels: Ινστιτούτο Πυρηνικών & Ραδιολογικών Επιστημών & Τεχνολογίας, Ενέργειας & Ασφάλειας*Greek
Related organizations: https://ror.org/038jp4m40 (parent)
City: Aghia Paraskevi
Country: Greece
Geonames ID: 6692232
Year established: 2012
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Originally submitted as part of https://github.com/ror-community/ror-updates/issues/2008, nanotechnology research center in Greece and child of https://ror.org/038jp4m40. Funds and employs researchers. Should be added.

Publication affiliation usage: https://doi.org/10.1021/acsphotonics.9b00235; https://doi.org/10.1073/pnas.1912070116; https://doi.org/10.1002/zaac.202000291

**Comment by mariagould** [comment]
I think this is fine to add. The institutes of the national research center are independently administered and we already have one represented in ROR (https://ror.org/03znpfq81)

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00tq5n859 in release v1.18.
