### ISSUE TITLE
Modify the information in an existing ROR record: 
RIKEN Center for Integrative Medical Sciences  https://ror.org/04mb6s476


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#202]
Summary of request: Modify the information in an existing ROR record

Name of organization: RIKEN Center for Integrative Medical Sciences
ROR ID:  https://ror.org/04mb6s476
Which part of the record needs to be changed? Primary name
Description of change: It would be corrected from "IMS, 理化学研究所 生命医科学研究センタ" to "国立研究開発法人　理化学研究所　生命医科学研究センター".

Update: delete.labels==理化学研究所 生命医科学研究センタ; add.labels==国立研究開発法人　理化学研究所　生命医科学研究センター*Japanese;

**Comment by arthurpsmith** [comment]
The request seems to have some confusion about our display/use of names - IMS is an acronym in our data, even though it's displayed along with the Japanese name. I'm assuming what they really want is to modify the Japanese name, and the requested change there would be to add the string "国立研究開発法人" (Google translates this as "Japanese National Research and Development Agency") at the front, and slightly modify the last part "生命医科学研究センタ" to "生命医科学研究センター" (Google translates both as "Biomedical Science Research Center"). If we just change the name in Japanese along these lines I think that's fine, it does appear to be the more complete official name.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
