### ISSUE TITLE
Modify the information in an existing ROR record: Don Law Institute

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2028]
Summary of request: Modify the information in an existing ROR record

Name of organization: Don Law Institute
ROR ID: https://ror.org/010swb518
Which part of the record needs to be changed? Status
Description of change: This org looks to be permanently closed

Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
Confirmed organization has closed.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
