### ISSUE TITLE
Modify the information in an existing ROR record: Wyższa Szkoła Ekonomiczno-Humanistyczna im.prof. Szczepana A. Pieniążka

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2029]
Summary of request: Modify the information in an existing ROR record

Name of organization: Wyższa Szkoła Ekonomiczno-Humanistyczna im.prof. Szczepana A. Pieniążka
ROR ID: https://ror.org/0050bke46
Which part of the record needs to be changed? Status
Description of change: This org looks to be permanently closed

Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
Confirmed organization has closed.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
