### ISSUE TITLE
Modify the information in an existing ROR record: Formedia, https://ror.org/056an2h19

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2030]
Summary of request: Modify the information in an existing ROR record

Name of organization: Formedia 
ROR ID: https://ror.org/056an2h19
Which part of the record needs to be changed? Status
Description of change: This org looks like it is permanently closed

Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
Confirmed organization has closed.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
