### ISSUE TITLE
Modify the information in an existing ROR record: California Postsecondary Education Commission, https://ror.org/01gxxpv20

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2031]
Summary of request: Modify the information in an existing ROR record

Name of organization: California Postsecondary Education Commission
ROR ID: https://ror.org/01gxxpv20
Which part of the record needs to be changed? Status
Description of change: This org closed in 2011, https://en.wikipedia.org/wiki/California_Postsecondary_Education_Commission

Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
Confirmed organization has closed.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
