### ISSUE TITLE
Modify the information in an existing ROR record: V-Continent Beijing Parkview Wuzhou Hotel, https://ror.org/03aaa6v42

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2033]
Summary of request: Modify the information in an existing ROR record

Name of organization:  V-Continent Beijing Parkview Wuzhou Hotel
ROR ID: https://ror.org/03aaa6v42
Which part of the record needs to be changed? Status
Description of change: This appears to be a hotel, presumably created in error

Update: change.status==withdrawn;$

**Comment by adambuttrick** [comment]
Has no affiliation usage and is not a research organization, thus withdrawing.

**Comment by adambuttrick** [comment]
Record updated in release v1.18.
