### ISSUE TITLE
Add a new organization to ROR: 
 
Institut Papst Benedikt XVI.

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#205]
Summary of request: Add a new organization to ROR

Name of organization: Pope Benedict XVI Institute
Website: http://www.institut-papst-benedikt.de/
Link to publications: http://www.institut-papst-benedikt.de/joseph-ratzinger-gesammelteschriften-jrgs.html
Organization type: Nonprofit
Wikipedia page: https://de.wikipedia.org/wiki/Institut_Papst_Benedikt_XVI.
Wikidata ID: https://www.wikidata.org/wiki/Q1664747
ISNI ID: https://isni.org/isni/0000000107418336
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Institut Papst Benedikt XVI.
Labels: Institut Papst Benedikt XVI (German)
Acronym/abbreviation: IPB
Related organizations: 
City: Regensburg
Country: Germany
Other information about this request:

**Comment by MSpenger** [comment]
Looks good to me. 

Title should include the final "dot" at "XVI." (like in the ISNI entry) . Also the URL to Wikipedia needs that detail at the end.

**Comment by MSpenger** [comment]
"Other name" could be "Pope Benedict XVI Institute" (according to website: http://www.institut-papst-benedikt.de/englisch.html)

**Comment by mariagould** [comment]
Following our policy on primary name languages, we should use the English version of the name in the primary name field:

`Pope Benedict XVI Institute` 

Then we should include the German name in the language label field (ISO tag: `de`):

`Institut Papst Benedikt XVI.`

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00wv18f77 in release v1.0.
