### ISSUE TITLE
Add a new organization to ROR: 
 
Invixium

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#206]
Summary of request: Add a new organization to ROR

Name of organization: Invixium
Website: https://www.invixium.com
Link to publications: https://www.invixium.com/blog/
Organization type: 
Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/Q107222290
ISNI ID: https://isni.org/isni/0000000502692757
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Invixium Inc.
Acronym/abbreviation: IXM
Related organizations: 
City: Toronto
Country: Canada
Other information about this request: At Invixium, We do research on biometric technology and touchless access control to prevent un authentic access.

**Comment by nlundvick** [comment]
This is a biometric hardware and software company. Link to publications is a corporate blog. No affiliation use found in scholarly literature (Google Scholar, Web of Science). Determination: Not in scope

**Comment by arthurpsmith** [comment]
I've looked a bit also, I agree with nlundvick, not in scope. I did find an ISNI id for them.
