### ISSUE TITLE
Add a new organization to ROR: Ministry of Science, Technology and Research

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2074]
Summary of request: Add a new organization to ROR

Name of organization: Ministry of Science, Technology and Research
Website: https://www.mostr.gov.lk
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Ministry_of_Technology_(Sri_Lanka)
Wikidata ID: Q4294474
ISNI ID: 0000 0004 0373 9230
GRID ID:
Crossref Funder ID: 501100008981
Other names for the organization: 
Acronym/abbreviation:
Aliases: Ministry of Technology; Ministry of Technology and Research
Labels: විද්‍යා, තාක්ෂණ හා පර්යේෂණ අමාත්‍යාංශය*si
Related organizations: 
City: Colombo
Country: Sri Lanka
Geonames ID: 1248991
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
State scientific agency in Sri Lanka. No affiliation usage I can find, but is an extensive funder of research (13797 citations) exposed in our Funder Registry reconciliation and thus would be in scope for ROR.

Funding acknowledgements: https://api.crossref.org/funders/10.13039/501100008981/works

**Comment by arthurpsmith** [comment]
Sure, we have lots of similar government ministries already.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00nqjr204 in release v1.18.
