### ISSUE TITLE
Add a new organization to ROR: Fonds de recherche du Québec

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2078]
Summary of request: Add a new organization to ROR

Name of organization: Fonds de recherche du Québec
Website: https://frq.gouv.qc.ca
Link to publications: 
Organization type: Government
Wikipedia page:
Wikidata ID: Q111530697
ISNI ID: 0000 0004 8076 5870; 0000 0005 0383 7436
GRID ID:
Crossref Funder ID: 501100020951
Other names for the organization: 
Aliases: Quebec Research Fund
Labels: 
Acronym/abbreviation:
Related organizations: https://ror.org/02eqrsj93 (child) https://ror.org/00b9f9778 (child) https://ror.org/00shpc021 (child) https://ror.org/05waa5295 (parent)
City: Quebec
Country: Canada
Geonames ID: 6325494
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Parent body for https://ror.org/02eqrsj93, https://ror.org/00b9f9778, https://ror.org/00shpc021 exposed in Funder Registry reconciliation. Since the children are in scope I believe this would be as well.

Funding acknowledgements: https://api.crossref.org/funders/10.13039/501100020951/works

**Comment by arthurpsmith** [comment]
Huh- I saw the name and thought - "I'm sure we already have this"! But I must have remembered one of the child agencies. Yes, should be in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00w3qhf76 in release v1.18.
