### ISSUE TITLE
Modify the information in an existing ROR record: 
Anglia Ruskin University https://ror.org/0009t4v78


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#208]
Summary of request: Modify the information in an existing ROR record

Name of organization: Anglia Ruskin University
ROR ID: https://ror.org/0009t4v78
Which part of the record needs to be changed? Other names or name versions listed in the record, Organization website
Description of change: ARU - Anglia Ruskin University - was known as Anglia Polytechnic University (APU) from its formation in 1992 to 2005. Our website is at www.aru.ac.uk.

Curator comments (MG):
- Add alias: `Anglia Polytechnic University`
- Update website to https://www.aru.ac.uk

Update: add.aliases==Anglia Polytechnic University; delete.links==http://www.anglia.ac.uk/; add.links==https://www.aru.ac.uk;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
