### ISSUE TITLE
Add a new organization to ROR: 
 
Maison des Sciences de l'Homme Mondes

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#209]
Summary of request: Add a new organization to ROR

Name of organization: Maison des Sciences de l'Homme Mondes
Website: https://www.mshmondes.cnrs.fr/
Link to publications: https://www.mshmondes.cnrs.fr/
Organization type: 
Wikipedia page: https://fr.wikipedia.org/wiki/Maison_des_Sciences_de_l%E2%80%99homme_Mondes
Wikidata ID: https://www.wikidata.org/wiki/Q3278957
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Maison Archéologie & Ethnologie
Acronym/abbreviation: MSH Mondes
Related organizations: Centre national de la recherche scientifique, France. https://ror.org/02feahw73
Université Paris Nanterre, France. https://ror.org/013bkhk48
Université Paris 1 Panthéon Sorbonne. https://ror.org/002t25c44
City: Nanterre
Country: France
Other information about this request:

**Comment by arthurpsmith** [comment]
It seems to be also known as "Maison René-Ginouvès" or "Maison René Ginouvès d'archéologie et d'ethnologie", or "Maison de l'Archéologie et de l'Ethnologie René-Ginouvès", or just "MAE", looking at affiliation listings from 2016 and earlier. This is a facility located within the University of Paris-Nanterre, but it does seem to be considered a top-level research institute on its own, in archeology/anthropology/ethnology etc.  I do think it should have an id in ROR.

**Comment by carlyrobinson** [comment]
Seems to be a research organization and seems to be used as an affiliation - https://halshs.archives-ouvertes.fr/halshs-03270407/,  https://journals.openedition.org/traces/10643. I agree it should be have a ROR ID.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00wx1mx58 in release v1.0.
