### ISSUE TITLE
Add Federal Office of Topography swisstopo

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#21]
Summary of request: Add a new organization to ROR

Name of organization: Federal Office of Topography swisstopo
Website: https://www.swisstopo.admin.ch
Link to publications: https://doi.org/10.1016/j.asr.2020.04.038
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Swisstopo
Wikidata ID: Q685592
ISNI ID: 0000 0001 2265 2235
GRID ID:
Crossref Funder ID: 501100013406
Other names for the organization:
Acronym/abbreviation:
Aliases: 
Labels: Bundesamt für Landestopografie swisstopo*German; Office fédéral de topographie swisstopo*French; Ufficio federale di topografia swisstopo*Italian
Related organizations:
City: Wabern
Country: Switzerland
Geonames ID: 2658084
Year established: 1838
How will a ROR ID for this organization be used?
Other information about this request:

**Comment by mariagould** [comment]
This was a legacy request submitted by the Swiss National Science Foundation. There are similar federal agencies from Switzerland already in ROR, e.g., https://ror.org/03wbkx358. The organization is used as an affiliation and is also a research funder. I would recommend including in ROR.

**Comment by arthurpsmith** [comment]
Seems a clear case to me, should be in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02cvys591 in release v1.0.
