### ISSUE TITLE
Modify the information in an existing ROR record: 
Lappeenranta University of Technology https://ror.org/0208vgz68


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#210]
Summary of request: Modify the information in an existing ROR record

Name of organization: Lappeenranta University of Technology
ROR ID: https://ror.org/0208vgz68
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: Our Uni is now (since Jan. 2020) Lappeenranta-Lahti University of Technology. Could you please update the information, thank you! In Finnish it would be Lappeenrannan-Lahden teknillinen yliopisto. Most used name is LUT University, in Finnish LUT-yliopisto; those should be added to the name versions too. (Please, check: https://www.lut.fi/web/en/ and https://www.lut.fi/)

MG Note:
Change name: Lappeenranta-Lahti University of Technology
Add aliases: LUT University; LUT-yliopisto; Lappeenranta University of Technology
Replace label: Lappeenrannan-Lahden teknillinen yliopisto (fi)
Change links: https://www.lut.fi/

Update: change.name==Lappeenranta-Lahti University of Technology; add.aliases==UT University; add.aliases==LUT-yliopisto; add.aliases==Lappeenranta University of Technology; replace.labels==Lappeenrannan-Lahden teknillinen yliopisto*fi; replace.links==https://www.lut.fi/;

**Comment by nlundvick** [comment]
Name changed in 2017 to "Lappeenranta-Lahti University of Technology LUT" (https://www.lut.fi/web/en/news/-/asset_publisher/lGh4SAywhcPu/content/lut-s-future-name-lut-university). Update main name in ROR record. Add aliases "LUT University", "Lappeenrannan-Lahden teknillinen yliopisto LUT", "LUT-yliopisto"

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
