### ISSUE TITLE
Add a new organization to ROR: 
 
International Platform on Mental Health

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#212]
Summary of request: Add a new organization to ROR

Name of organization: International Platform on Mental Health
Website: https://mhgc21.org/en/about
Link to publications: https://mhgc21.org/en/mhgc21/events/October-2021-Report/About-October-2021-Conference
Organization type: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: MHGC21.ORG
Acronym/abbreviation: MHGC21.ORG
Related organizations: 
City: Kyiv
Country: Ukraine
Other information about this request: The International Platform on Mental Health “Mental Health: global challenges” (www.mhgc21.org ) is the platform for Social Initiatives, for dissemination of leading ideas and experience, for support of building academic and professional networks, developing future collaborations between researchers and professionals across the different regions of the world. The Platform is doing the attempt to rise the social awareness, to facilitate social changes, to support Governmental initiatives, to develop qualitative skills of professionals. The Platform helps researchers, social activists and all interested parties from all over the world to improve multidisciplinary aspects of Mental Health Care system
Since 2017 we are organizing annual International Conference “Mental Health; global challenges of XXI century”. We try to commute all main actors in the field of Mental Health. Thus, Governmental, International, Religious, Academic, Research, Educational and Civil Institutions, Volunteer Movements took part in the Conference activities. 
Among our Honorable Guests, Partners and Speakers were:    
•	World Federation of Mental Health (Dr. Ana de Sousa Baptista, Director of the Board and Chair of the Mental Health Policy Section of the World Federation of Mental Health)                                                           
•	WHO
•	International Medical Corps
•	Red Cross Society
•	Interdisciplinary Council on Development and Learning
•	Médecins Sans Frontières 
•	EMDR Europe Association
•	National Institute of Health (Italy)
•	Balkan Universities Association
•	Mental Health Reform, National Coalition for Mental Health in Ireland
The main Platform’s results are: social awareness-rising campaign, geographical diversification, research contributions, partnership building.
social awareness-rising campaign. The Platform organizes activities between these annual Conferences. Thus, in 2018 we organized several seminars and workshops in Ukraine. In January 2019 we organized National Round table meeting on rehabilitation of ex-combatants and their families. In May 2019 – International Public-Scientific Initiative” Community: health, human potential, socio-economic innovations”. For example, our audience for Event was more than 2 600 participants. In October 2020 – Mental Health Literacy Event (devoted to WMHD). Within this Event we organized activities in North (Chernigiv, Human Rights House), Central (Kyiv, National Academy of Management), South-West (Khmelnytsky, City Hospital), South-East (Zaporozhye, Caritas). Our audience (more than 600 persons) – family doctors, educators, social workers (persons who can “deliver” this knowledge to wide Ukrainian society)
geographical diversification. There were participants from Algeria, Austria, Belgium, Canada, Cyprus, Finland, Greece, Italy, Israel, Latvia, Lithuania, Netherlands, Portugal, Spain, South Africa, Taiwan, Ukraine, United Kingdom, USA on our Conference
research contributions. The MHGC Proceedings and Journal “Mental Health: global challenges” (ISSN 2612-2138) were established. The MHGC Proceedings is also placed in National Library of Ukraine (www.nbuv.gov.ua )
The International Journal “Mental Health: global challenges” (ISSN 2612-2138) (www.mhgcj.org ) is already indexed in DOAJI, ERIHPlus, Crossref, BASE, CORE, Index Copernicus, ResearchBib, … The Journal is also available on Publons (Clarivate Analytics), National Library of Australia, HINARY (WHO). The Journal considers with special attention the manuscripts which can be of interest for policy makers and practioners
partnership building. We are doing the attempt to establish cooperation regarding MHC globally. Among our participants were Governmental Institutions, Directors and Presidents, Vice-Directors, Vice-Rectors, Deans of the Faculties, Heads of the Departments, Professors and Specialists

**Comment by nlundvick** [comment]
This is a Ukrainian organization established in 2017/2018 that organizes and publishes the proceedings for an annual conference on mental health. They also publish a peer reviewed open access journal. No affiliation use found. Organization seems to be run by one person, Dr. Viktor Vus. I don't think this organization is in scope, second reviewer may want to move to Needs Discussion. If adding, will also need to discuss metadata. Org name in the request was "International Platform on Mental Health", but the name throughout org's website is "Mental Health: Global Challenges of XXI Century."

**Comment by KellyStathis** [comment]
I agree that this organization does not appear to be in scope, for the reasons described above. I checked that Dr. Victor Vus uses a different affiliation when publishing, which is already in ROR (https://ror.org/01ezcv773)--see https://www.impactio.com/publication/2551944358. I am moving this to declined requests.
