### ISSUE TITLE
Add a new organization to ROR: 
 
Disabled Women in Africa

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#213]
Summary of request: Add a new organization to ROR

Name of organization: Disabled Women in Africa
Website: www.diwaafrica.org
Link to publications: https://www.makingitwork-crpd.org/sites/default/files/2019-07/DIWA%20Access%20Audit%20report%20Final%202016.pdf
Organization type: 
Wikipedia page: N/A
Wikidata ID: N/A
ISNI ID: N/A
GRID ID: N/A
Crossref Funder ID: N/A
Other names for the organization: not applicable
Acronym/abbreviation: DIWA
Related organizations: N/A
City: Lilongwe
Country: Malawi
Other information about this request: None

**Comment by arthurpsmith** [comment]
From curation meeting, this is being held for later/more info.

**Comment by adambuttrick** [comment]
Situation is unchanged. Need to make a yes or no determination on this.
