### ISSUE TITLE
Modify the information in an existing ROR record: Iberoamerican University of Science and Technology  - https://ror.org/005g07p37

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#2139]
Summary of request: Modify the information in an existing ROR record

Name of organization: Iberoamerican University of Science and Technology
ROR ID: https://ror.org/005g07p37
Which part of the record needs to be changed? aliases
Description of change: The organization's website http://www.uiberoamericana.cl/ is incorrectly stored in aliases

Update: delete.aliases==http://www.uiberoamericana.cl;$

**Comment by adambuttrick** [comment]
Updated in release v1.19.
