### ISSUE TITLE
Modify the information in an existing ROR record: Karnataka State Open University - https://ror.org/00ecztp88

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#2140]
Summary of request: Modify the information in an existing ROR record

Name of organization: Karnataka State Open University
ROR ID: https://ror.org/00ecztp88
Which part of the record needs to be changed? aliases
Description of change: The organization's website http://ksoumysore.karnataka.gov.in/ is incorrectly stored in aliases

Update: delete.aliases==http://ksoumysore.karnataka.gov.in/;$

**Comment by adambuttrick** [comment]
Updated in release v1.19.
