### ISSUE TITLE
Modify the information in an existing ROR record: 
Musée National d'Histoire Naturelle https://ror.org/05natt857


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#215]
Summary of request: Modify the information in an existing ROR record

Name of organization: Musée National d'Histoire Naturelle
ROR ID: https://ror.org/05natt857
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: Change of the Primary name from the ambiguous French version "Musée National d'Histoire Naturelle" to "National Museum of Natural History, Luxembourg". Adding the versions "Musée national d'histoire naturelle du Luxembourg" (Fr), "Naturmusée" (Lb) and "Nationalmuseum für Naturgeschichte Luxemburg" (de) as alternative names.

Update: delete.labels==Nationalmuseum für Naturgeschichte; add.labels==Musée national d'histoire naturelle du Luxembourg*French; add.labels==Naturmusée*lb; add.labels==Nationalmuseum für Naturgeschichte Luxemburg*German;

**Comment by KellyStathis** [comment]
This change makes sense to reduce ambiguity.  We currently have these two labels:

```
"labels": [
{
"label": "Nationalmusée fir Naturgeschicht",
"iso639": "lb"
},
{
"label": "Nationalmuseum für Naturgeschichte",
"iso639": "de"
}
```

I would recommend changing this to:
```
"labels": [
{
"label": Musée national d'histoire naturelle du Luxembourg",
"iso639": "fr"
},
{
"label": "Naturmusée",
"iso639": "lb"
},
{
"label": "Nationalmusée fir Naturgeschicht",
"iso639": "lb"
},
{
"label": "Nationalmuseum für Naturgeschichte Luxemburg",
"iso639": "de"
}
]
```

See https://lb.wikipedia.org/wiki/Nationalmus%C3%A9e_fir_Naturgeschicht for the source of the ""Nationalmusée fir Naturgeschicht" name.

**Comment by MSpenger** [comment]
I agree with the recommended changes.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
