### ISSUE TITLE
Add a new organization to ROR: AmeriCorps

### ISSUE THREAD

**Issue by rogerwood-infoed** [ror-community/ror-updates#2153]
Summary of request: Add a new organization to ROR

Name of organization: AmeriCorps
Website: https://americorps.gov
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/AmeriCorps
Wikidata ID: Q511243
ISNI ID: 0000 0004 0438 3301
GRID ID:
Crossref Funder ID: 100018691
Other names for the organization:
Aliases: Corporation for National and Community Service
Labels:
Acronym/abbreviation: CNCS
Related organizations: 
City: Washington, DC
Country: United States
Geonames ID: 4140963
Year established: 1993
How will a ROR ID for this organization be used? Linking grant programs and funding to sponsor
Other information about this request:

**Comment by adambuttrick** [comment]
American government agency. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1016/j.jbusres.2015.11.009; https://doi.org/10.1080/01488376.2013.799112; https://doi.org/10.1080/09583157.2012.681627; https://doi.org/10.1046/j.1570-7458.1999.00539.x; https://doi.org/10.3200/tchs.82.1.35-39; https://doi.org/10.1016/j.bse.2007.03.007; https://doi.org/10.1080/03637751.2016.1214871; https://doi.org/10.1653/024.099.0103; https://doi.org/10.1111/1471-0528.15176

ORCID affiliation usage: https://orcid.org/0000-0002-1746-1925 ; https://orcid.org/0000-0001-7434-6483 ; https://orcid.org/0000-0001-9632-9721

**Comment by arthurpsmith** [comment]
Yes, affiliation usage plus they are a funder. Should be in ROR.

**Comment by adambuttrick** [comment]
Exists in ROR under CNCS alias - https://ror.org/00p8rjs69. Will create update to reflect.

**Comment by arthurpsmith** [comment]
Huh - good catch!

**Comment by rogerwood-infoed** [comment]
Thanks. Should there be an alias reference somewhere then because when you load that website address… it redirects to: https://www.americorps.gov.

Just trying to understand how I would uncover this?

Thanks
Roger Wood

From: Arthur Smith ***@***.***>
Date: Friday, February 10, 2023 at 2:58 PM
To: ror-community/ror-updates ***@***.***>
Cc: Wood, Roger ***@***.***>, Author ***@***.***>
Subject: Re: [ror-community/ror-updates] Add a new organization to ROR: AmeriCorps (Issue #2153)

Huh - good catch!

**Comment by adambuttrick** [comment]
@rogerwood-infoed It's just outdated metadata on our end. We will correct to reflect the Americorps name and link in our next release. Apologies for the confusion.

**Comment by rogerwood-infoed** [comment]
Perfect Thanks!

This was just me randomly picking one we didn’t find a match for to get a sense of the process. 😊

From: adambuttrick ***@***.***>
Date: Friday, February 10, 2023 at 4:05 PM
To: ror-community/ror-updates ***@***.***>
Cc: Wood, Roger ***@***.***>, Mention ***@***.***>
Subject: Re: [ror-community/ror-updates] Add a new organization to ROR: AmeriCorps (Issue #2153)

@rogerwood-infoed<https://github.com/rogerwood-infoed> It's just outdated metadata on our end. We will correct to reflect the Americorps name and link in our next release. Apologies for the confusion.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01ny57s80 in release v1.19.
