### ISSUE TITLE
Add a new organization to ROR: 
 
Polyneme LLC

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#217]
Summary of request: Add a new organization to ROR

Name of organization: Polyneme LLC
Website: https://polyneme.xyz/
Link to publications: https://polyneme.xyz/publications
Organization type: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: N/A
Acronym/abbreviation: N/A
Related organizations: 
City: New York, NY
Country: USA
Other information about this request:

**Comment by carlyrobinson** [comment]
Single person and not being used as affiliation on that person's publications. Out of scope.
