### ISSUE TITLE
Modify the information in an existing ROR record: 
Tecnologico de Monterrey https://ror.org/03ayjn504


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#218]
Summary of request: Modify the information in an existing ROR record

Name of organization: Tecnologico de Monterrey
ROR ID: https://ror.org/03ayjn504
Which part of the record needs to be changed? Primary name, Organization website
Description of change: Our correct institutional name is “Tecnológico de Monterrey”, this is our institutional name used for academic and research papers and publications (it is in Spanish). We prefer not to use translations to our university institutional name.

Our correct web site in English is: www.tec.mx/en

Other information about this request: Our correct name is “Tecnológico de Monterrey”, this is our institutional name used for academic and research papers and publications (it is in Spanish). We prefer not to use translations to our university institutional name.
Our correct web site in English is: www.tec.mx/en

Update: change.name==Tecnológico de Monterrey; delete.aliases==Tecnológico de Monterrey; delete.links==http://www.itesm.mx/; add.links==https://www.tec.mx/;

**Comment by carlyrobinson** [comment]
Recommend updating the name to: Tecnológico de Monterrey. This is used as affiliation by faculty https://pubs.acs.org/doi/10.1021/jf200944y.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
