### ISSUE TITLE
Add a new organization to ROR: Uniting

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#22]
Summary of request: Add a new organization to ROR

Name of organization: Uniting
Website: https://www.uniting.org
Link to publications: https://www.uniting.org/community-impact/research-and-innovation, https://doi.org/10.1016/j.drugalcdep.2020.107909, https://doi.org/10.1016/j.drugpo.2019.01.026
Organization type: Nonprofit
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City: Sydney
Country: Australia
Geonames ID: 2147714
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by mariagould** [comment]
This is a legacy issue from 2020. The organization was suggested by the Swiss National Science Foundation to identify affiliations in SNSF-funded research. ROR recommended the addition to GRID but the addition was not approved at the time so the request has been on hold since then. I am now reinstating it so we can consider it for inclusion in ROR. 

The organization is a nonprofit affiliated with the Uniting Church in Australia. It appears that most of the organization's research publications are associated with the Uniting Medically Supervised Injection Centre (Uniting MSIC). We should consider whether to create a ROR ID for Uniting or for Uniting MSIC.

**Comment by arthurpsmith** [comment]
Yes, I think we should have something for this. How about creating a ROR id for the overall church (Uniting Church in Australia)? We do have https://ror.org/04m5qh397 for the Church of England, for example and a number of others (https://ror.org/03vpkt967, https://ror.org/012hhd379, etc.)

Uniting MSIC seems to be one service provided in Sydney (https://www.uniting.org/community-impact/uniting-medically-supervised-injecting-centre--msic) - I guess it is used as an affiliation the way some hospitals and clinics would be, and we have plenty of those, so I suppose a ROR id for that would be ok too.

However, "Uniting" as a whole seems to be responsible for a lot more services than just this MSIC, particularly care for the aged and mental health care. It's a little hard to search for research from them as "Uniting" is hardly a unique string to search on. Their "Research and Innovation" page here: https://www.uniting.org/community-impact/research-and-innovation lists a wide variety of research projects they are involved with, with relations with about two dozen universities. So it seems to me that this organization in itself should qualify for a ROR id as a research-involved nonprofit/medical care organization.

So my recommendation is to add a ROR id for Uniting as requested in this issue, and then consider additional ROR id's for a parent (Uniting Church in Australia) and child (Uniting MSIC, Sydney).

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01qx0e979 in release v1.1.
