### ISSUE TITLE
Add a new organization to ROR: 
 
Instituto Superior Tecnológico Bolivariano de Tecnología

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#220]
Summary of request: Add a new organization to ROR

Name of organization: Instituto Superior Tecnológico Bolivariano de Tecnología
Website: https://itb.edu.ec/
Link to publications:  https://doi.org/10.37611/ib25506749
Organization type: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: https://isni.org/isni/0000000405860042
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Instituto Superior Tecnológico Bolivariano de Tecnología
Acronym/abbreviation: ITB
Related organizations: 
City: Guayaquil
Country: Ecuador
Other information about this request:

**Comment by carlyrobinson** [comment]
Agreed that they should be given a ROR ID - university doing research, publishing a journal, faculty are publishing.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0171n2m64 in release v1.0.
