### ISSUE TITLE
Add a new organization to ROR: 
 
Colectica

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#221]
Summary of request: Add a new organization to ROR

Name of organization: Colectica
Website: https://www.colectica.com
Link to publications: https://www.icpsr.umich.edu/web/pages/NACDA/colectica-portal.html https://www.ssc.wisc.edu/naddi2015/webready/NADDI2015_Iverson_Radler.pdf https://doi.org/10.5281/zenodo.3228385
Organization type: Company
Wikipedia page: https://en.wikipedia.org/wiki/Colectica
Wikidata ID: https://www.wikidata.org/wiki/Q105299208
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Algenta Technologies
Acronym/abbreviation: Colectica
Related organizations: 
City: Minneapolis
Country: United States
Other information about this request:

**Comment by nlundvick** [comment]
This is a company that provides software for data management. First link to publications is to the National Archive of Computerized Data on Aging data repository, which is based on a Colectica platform. Other affiliation uses found in informal publications/slide presentations, almost all by the company's founder. Recommendation: Not in scope as a research organization

**Comment by arthurpsmith** [comment]
So their software clearly is used for research purposes, but ROR isn't an identifier for software. The company itself seems very small and as Nick points out is not really used as an affiliation except for mostly promotional materials. I agree this is not in scope.
