### ISSUE TITLE
Add a new organization to ROR: 
 
Brown Dog Consulting

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#222]
Summary of request: Add a new organization to ROR

Name of organization: Brown Dog Consulting
Website: www.browndogllc.com
Link to publications: https://unesdoc.unesco.org/ark:/48223/pf0000378061?posInSet=1&queryId=66d5f7f9-94e2-4253-9cc9-eba3d7b7ee8a
Organization type: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: none
Acronym/abbreviation: BDC
Related organizations: Lotus Circle
City: Seattle
Country: United States
Other information about this request: I would like to register both Brown Dog Consulting LLC (a for-profit corporation) and Lotus Circle (a nonprofit corporation).  I am the founder of both organizations and am affiliated with the University of Washington in Seattle, WA as a Senior Fellow in the Disability Inclusive Development Initiative and, effective January 2022, Affiliate Assistant Professor in the Law, Societies and Justice Department.  Both BDC and LC are vehicles to bridge the gap between academic research and its practical applications.  I use both to facilitate contracting with external organizations such as UNESCO and Humanity & Inclusion for research particularly into the rights of persons with disabilities.  We are anticipating applying for grants from organizations like SVRI and others and expanding our research profile, for which a ROR ID would be helpful.  Many thanks in advance for your consideration.

**Comment by carlyrobinson** [comment]
No indication that there is more than one person, so out of scope.
