### ISSUE TITLE
Modify the information in an existing ROR record: 
Centro de Investigaciones Biológicas https://ror.org/04advdf21


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#223]
Summary of request: Modify the information in an existing ROR record

Name of organization: Centro de Investigaciones Biológicas
ROR ID: https://ror.org/04advdf21
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website
Description of change: The center added to its title the name of a recently deceased Spanish Molecular Biology pioneer, Margarita Salas. Therefore, the name of the institution should be "Centro de Investigaciones Biológicas Margarita Salas" or, in English, "Margarita Salas Center for Biological Research". Also, the link to the institution leads to a non-exixting page, it should be just "https://www.cib.csic.es".

Update: change.name==Centro de Investigaciones Biológicas Margarita Salas; delete.labels==Center for Biological Research; add.labels==Margarita Salas Center for Biological Research*English; delete.links==http://www.cib.csic.es/en/; add.links==https://www.cib.csic.es/;

**Comment by carlyrobinson** [comment]
Recommend updating the URL to: https://www.cib.csic.es/. Recommend changing the name to: Centro de Investigaciones Biológicas Margarita Salas. It's being used as an affiliation (doi.org/10.3390/cells9040988 and https://www.mdpi.com/2079-4991/11/3/671)

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
