### ISSUE TITLE
Add a new organization to ROR: 
 
St. Lawrence Global Observatory

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#224]
Summary of request: Add a new organization to ROR

Name of organization: St. Lawrence Global Observatory
Website: https://ogsl.ca/en/home-slgo/
Link to publications: https://doi.org/10.3389/fmars.2019.00431, https://internal-journal.frontiersin.org/articles/10.3389/fmars.2020.00383/full
Organization type: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Observatoire Global du Saint-Laurent (OGSL)
Acronym/abbreviation: SLGO
Related organizations: DFO - ROR: 02qa1x782 (related institution: OBSERVER MEMBERS), UQAR - ROR: 049jtt335 (related institution: ACTIVE MEMBERS), TMQ - ROR: 01ncvjw08 (related institution: ASSOCIATE MEMBERS), CRBM - ROR: 01aa78f69 (related institution: ASSOCIATE MEMBERS), MUN - ROR: 04haebc03 (related institution: ACTIVE MEMBERS), UQTR - ROR: 02xrw9r68 (related institution: ACTIVE MEMBERS), Shipping Federation of Canada - ROR: 0515hsf31 (related institution: ASSOCIATE MEMBERS), WWF Canada - ROR: 020tdv696 (ASSOCIATE MEMBERS)
https://ror.org/02qa1x782 (related)
https://ror.org/049jtt335 (related)
https://ror.org/01ncvjw08 (related)
https://ror.org/01aa78f69 (related)
https://ror.org/04haebc03 (related)
https://ror.org/02xrw9r68 (related)
https://ror.org/0515hsf31 (related)
https://ror.org/020tdv696 (related)
City: Rimouski
Country: Canada
Other information about this request:

**Comment by KellyStathis** [comment]
This organization supports and conducts oceans research, and hosts a repository for oceans data. It is not already in ROR, and it is used as an affiliation (see links in submission).

It is also a top-level organization. SLGO is part of the [Canadian Integrated Oceans Observing System (CIOOS)](https://cioos.ca/), along with CIOOS Atlantic and CIOOS Pacific: https://ogsl.ca/en/cioos/. However, SLGO is an independent organization from CIOOS and predates CIOOS. I checked with a colleague and we are not sure if [CIOOS Atlantic](https://cioosatlantic.ca/) and [CIOOS Pacific](https://cioospacific.ca/) are equally independent, but SLGO definitely is.

In addition to adding SLGO, I would also recommend adding CIOOS (the national organization) to ROR. We may still indicate a "parent" relationship here, in that SLGO is one of the three partner "regional associations" that together form the national CIOOS. See the governance structure here - https://www.cioos.ca/governance/.

A few metadata notes:

- For the related organizations submitted, I am not sure if it makes sense to list all of these members here. There are many more members listed on this page: https://ogsl.ca/en/members-list/. This seems like it would be difficult to maintain. 
- For the labels: I would not capitalize "global" in "Observatoire global du Saint-Laurent".

I recommend adding SLGO to ROR.

**Comment by arthurpsmith** [comment]
I agree with Kelly here - SLGO/OGSL is an independent research organization that should be in ROR. I did not find any Wikidata/Wikipedia or ISNI entries for it; however several people (data scientists) list it as their employer in LinkedIn.  I also agree that it would make sense to add an entry for CIOOS.

**Comment by pauline-chauvet** [comment]
Hi,
I am working for SLGO as a scientific adviser. If ever you need some other info, I'll be happy to provide it. 
Thanks very much for your work. 
Pauline Chauvet
chauvetp@ogsl.ca

**Comment by adambuttrick** [comment]
@pauline-chauvet Thank you so much for your offer of assistance! This request has been approved and will be included in our next release. Please continue to follow this issue so you can be notified when it has been assigned its ROR ID. We will also reach out if we have any further questions.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03wfagk22 in release v1.0.
