### ISSUE TITLE
Add a new organization to ROR: Department of Agriculture, Fisheries and Forestry

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2241]
Summary of request: Add a new organization to ROR

Name of organization: Department of Agriculture, Fisheries and Forestry
Website: https://www.agriculture.gov.au
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Department_of_Agriculture,_Fisheries_and_Forestry_(Australia)
Wikidata ID: Q113826568
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: DAFF
Related organizations: https://ror.org/030c92375 (predecessor) https://ror.org/0314h5y94 (parent)
City: Canberra
Country: Australia
Geonames ID: 2172517
Year established: 2022
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Australian government department and successor organization to https://ror.org/030c92375, as identified in https://github.com/ror-community/ror-updates/issues/2240. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1111/j.1365-2664.2006.01136.x; https://doi.org/10.1111/1755-0998.12157; https://doi.org/10.1038/ncomms3320; https://doi.org/10.1016/j.envsoft.2014.07.009

ORCID affiliation usage: https://orcid.org/0000-0002-0169-4070 ; https://orcid.org/0000-0002-8559-7808 ; https://orcid.org/0000-0001-8533-0006

**Comment by adambuttrick** [comment]
@mpfl Can you review and sign off on this one?

**Comment by mpfl** [comment]
The degree to which successive governments mess around with departments in Australia is quite frustrating.

Is it possible to have two successor organisations? There is also the Department of Climate Change, Energy, the Environment and Water https://www.dcceew.gov.au/

**Comment by adambuttrick** [comment]
@mpfl Yes, multiple successors are permitted. I created https://github.com/ror-community/ror-updates/issues/2256 to reflect.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00jks2h96 in release v1.19.
