### ISSUE TITLE
Add a new organization to ROR: Institutul National de Cercetari Economice "Costin C. Kiritescu"

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2243]
Summary of request: Add a new organization to ROR

Name of organization: Institutul National de Cercetari Economice "Costin C. Kiritescu"
Website: http://www.ince.ro
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 4908 0152; 0000 0000 9523 8396 
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: National Institute of Economic Research "Costin C. Kiritescu"
Labels: 
Acronym/abbreviation: 
Related organizations: https://ror.org/0561n6946 (parent) https://ror.org/021hxpr45 (child)
City: Bucharest
Country: Romania
Geonames ID: 683506
Year established: 1918
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Research institute in Romania, identified in https://github.com/ror-community/ror-updates/issues/2108#issuecomment-1419815480. Funds and employs researchers. Solid affiliation usage. Should be added. 

Publication affiliation usage: http://www.ince.ro/Publicatii/publicatii.html; https://doi.org/10.1051/shsconf/20219701027

ORCID affiliation usage: https://orcid.org/0000-0002-8339-795X ; https://orcid.org/0000-0001-6868-2907 ; https://orcid.org/0000-0002-0269-2886

**Comment by arthurpsmith** [comment]
Thanks - looks great to me!

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04kddtt70 in release v1.19.
