### ISSUE TITLE
Modify the information in an existing ROR record:  Minerals and Energy Research Institute of Western Australia - https://ror.org/02txrtk05

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2259]
Summary of request: Modify the information in an existing ROR record

Name of organization: Minerals and Energy Research Institute of Western Australia
ROR ID: https://ror.org/02txrtk05
Which part of the record needs to be changed? Status
Description of change: This appears to have been restructured in some fashion back in 2013 to become the Minerals Research Institute of Western Australia, but not certain whether it is a new organization or continuation of the prior under a new name. There are discrete funder entries for the two forms [501100009108](https://api.crossref.org/funders/501100009108) and [501100000962](https://api.crossref.org/funders/501100000962), so need to determine how to represent and associate these values. Tried checking the Libraries Australia authority records, but they appear to have put these behind a login.

Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
@mpfl Can you advise?

**Comment by mpfl** [comment]
MRIWA is a statutory body of the government of Western Australia, defined by an Act of state parliament (_Minerals Research Institute of WA Act 2013_). It looks like the 2013 Act repealed the _Minerals and Energy Research Act 1987_, which caused the abolition of the Minerals and Energy Research Institute of Western Australia. The MERIWA's assets were transferred to the new MRIWA.

The 2013 Act deliberately uses the phrase "abolished Institute" to refer to MERIWA. To abolish means to destroy (Wordnik suggests "Abolish is a strong word, and signifies a complete removal, generally but not always by a summary act.")

Legally, MERIWA ceased to exist. They are not the same organisation, even if MRIWA replaced MERIWA and has continued some of its work.

**Comment by adambuttrick** [comment]
@mpfl Thanks for this clarification. I will update https://ror.org/02txrtk05 to be inactive and create a new record for MRIWA.

**Comment by adambuttrick** [comment]
Record updated in release v1.19.
