### ISSUE TITLE
Modify the information in an existing ROR record: 
Technische Universität Darmstadt https://ror.org/05n911h24


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#227]
Summary of request: Modify the information in an existing ROR record

Name of organization: Technische Universität Darmstadt
ROR ID: https://ror.org/05n911h24
Which part of the record needs to be changed? Other names or name versions listed in the record
Description of change: 2019 the presidium of TU Darmstadt decided, that „Technical University of Darmstadt“ should be the only official englisch name. Other versions are no longer allowed.

MG Note:
Change name: Technical University of Darmstadt
Replace alias: TU Darmstadt

Update: change.name==Technical University of Darmstadt; replace.aliases==TU Darmstadt;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
