### ISSUE TITLE
Add a new organization to ROR: Editora JRG

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2276]
Summary of request: Add a new organization to ROR

Name of organization: Editora JRG
Website: http://www.editorajrg.com
Link to publications: 
Organization type: Other
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City: Brasília
Country: Brazil
Geonames ID: 3469058
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Small academic publisher, first identified in https://github.com/ror-community/ror-updates/issues/2274. Publishes journal  Revista JRG de Estudos Acadêmicos, as well as [several open access eBooks](http://revistajrg.com/index.php/portaljrg/index). Would be in scope for ROR by virtue of our publisher use case. Has a single instance of affiliation usage as well. 

Publication affiliation usage: https://api.openalex.org/W3104864514

**Comment by mariagould** [comment]
I agree this is in scope as a small publisher.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02gexj360 in release v1.20.
