### ISSUE TITLE
Add a new organization to ROR: Fundo Nacional de Desenvolvimento da Educação

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2277]
Summary of request: Add a new organization to ROR

Name of organization: Fundo Nacional de Desenvolvimento da Educação
Website: https://www.fnde.gov.br
Link to publications: 
Organization type: Government
Wikipedia page: https://pt.wikipedia.org/wiki/Fundo_Nacional_de_Desenvolvimento_da_Educa%C3%A7%C3%A3o
Wikidata ID: Q10286468
ISNI ID: 0000 0004 6027 3836
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: FNDE
Related organizations: https://ror.org/04d0xx942 (parent)
City: Brasília
Country: Brasil
Geonames ID: 3469058
Year established: 1968
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Brazilian state strategic development fund under https://ror.org/04d0xx942. Funds and employs researchers, solid affiliation usage. Serves as publisher for academic journals, as identified in https://github.com/ror-community/ror-updates/issues/2275. Should be added.

Publication affiliation usage: https://doi.org/10.1590/0102-311x00206816; https://doi.org/10.24109/2176-6681.rbep.92i231.532; https://doi.org/10.1590/s1413-81232013000400002; https://openalex.org/W2292203994; https://openalex.org/W2150417384; https://openalex.org/W2086441651; https://doi.org/10.26633/rpsp.2020.32; https://doi.org/10.1590/s1413-81232013000400003; https://doi.org/10.5007/1983-4535.2017v10n1p79

ORCID affiliation usage: https://orcid.org/0000-0002-9456-8371 ; https://orcid.org/0000-0002-9858-597X ; https://orcid.org/0000-0001-5500-4437

**Comment by mariagould** [comment]
I agree this is in scope as given evidence of research activity and affiliation usage.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03w24fg09 in release v1.20.
