### ISSUE TITLE
Modify the information in an existing ROR record: 
Universidad Central (Chile) https://ror.org/0577avk88


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#228]
Summary of request: Modify the information in an existing ROR record

Name of organization: Universidad Central (Chile)
ROR ID: https://ror.org/0577avk88
Which part of the record needs to be changed? Organization website
Description of change: Could you change our URL website please? the correct website is; www.ucentral.cl  

Other information about this request: The URL you show does not exist (Error 404)

MG Note:
Replace links: https://www.ucentral.cl

Update: replace.links==https://www.ucentral.cl/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
