### ISSUE TITLE
Add a new organization to ROR: 
 
German Institute for Development Evaluation (DEval)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#231]
Summary of request: Add a new organization to ROR

Name of organization: German Institute for Development Evaluation (DEval)
Website: https://www.deval.org/
Link to publications: https://elibrary.utb.de/doi/abs/10.31244/zfe.2013.02.06
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: DEval
Acronym/abbreviation: DEval
Related organizations: 
City: Bonn
Country: Germany
How will a ROR ID be used: To identify affiliations for research publications
To acknowledge a research facility
Other information about this request:

**Comment by MSpenger** [comment]
Looks good to me. In addition to the information above I would add the following:

- aliases: Deutsches Evaluierungsinstitut der Entwicklungszusammenarbeit
- ISNI ID: https://isni.org/isni/0000000463627353
- Wikipedia page: https://de.wikipedia.org/wiki/Deutsches_Evaluierungsinstitut_der_Entwicklungszusammenarbeit
- Wikidata ID: https://www.wikidata.org/wiki/Q41791404

Publications can be found here: https://www.deval.org/en/publications?tx_lfpublications_list%5Boffset%5D=0&cHash=52aa7e3c7d05e8796224b253fe6b315c

**Comment by arthurpsmith** [comment]
Looks good to me - thanks Martin for the additional id's etc. If we're adding inception dates I believe this one was started in 2012, and it might be better classified as a nonprofit organization?
Refs (in German): https://www.deval.org/de/ueber-uns/das-institut/struktur-und-finanzierung and https://www.deval.org/de/ueber-uns/das-institut/aufgaben-und-ziele

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04tmban63 in release v1.0.
