### ISSUE TITLE
Project: Peruvian institutions

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#233]
Review [list of institutions](https://docs.google.com/spreadsheets/d/1Y9LRl7MkUpvGANhZylRdVOXA56qBOL4x/edit#gid=2135351962) (with metadata) provided by CONCYTEC/PeruCRIS

**Comment by arthurpsmith** [comment]
Note I've worked on the first bunch in the list. It's pretty quick to go through them.

**Comment by arthurpsmith** [comment]
I guess I should update - I finished the list. There was one case that I think needed further discussion.

**Comment by adambuttrick** [comment]
One institution in this list is a duplicate request by the organization. Keeping that issue - #253 - open, so the organization can track.

**Comment by adambuttrick** [comment]
Assigned ROR IDs in release v1.0:

https://ror.org/043ncc240 - Escuela de Postgrado Gerens
https://ror.org/02dbp3m50 - Escuela Postgrado Neumann Business School
https://ror.org/00bqrh472 - Universidad Autónoma de Ica
https://ror.org/05dxn4584 - Universidad Autónoma del Perú
https://ror.org/01fefmh69 - Universidad Jaime Bausate y Meza
https://ror.org/02201g510 - Universidad Le Cordon Bleu
https://ror.org/031dyqa07 - Universidad María Auxiliadora
https://ror.org/00gt23c81 - Universidad Nacional Autónoma Altoandina de Tarma
https://ror.org/0180xa122 - Universidad Nacional Autónoma de Alto Amazonas
https://ror.org/02r5q9a81 - Universidad Nacional Autónoma de Chota
https://ror.org/023ycer62 - Universidad Nacional Autónoma de Huanta
https://ror.org/03yef2k78 - Universidad Nacional Autónoma de Tayacaja Daniel Hernández Morillo
https://ror.org/01y280z29 - Universidad Nacional de Barranca
https://ror.org/053drm788 - Universidad Nacional de Cañete
https://ror.org/017bd4h68 - Universidad Nacional de Frontera
https://ror.org/051zgrs14 - Universidad Nacional de Jaén
https://ror.org/01897f782 - Universidad Nacional de Juliaca
https://ror.org/04df9ks57 - Universidad Nacional Intercultural "Fabiola Salazar LeguÍa" de Bagua
https://ror.org/026ewty38 - Universidad Nacional Intercultural de la Selva Central Juan Santos Atahualpa
https://ror.org/04wmpkv79 - Universidad Nacional Intercultural de Quillabamba
https://ror.org/036ttgc90 - Universidad Privada de Huancayo "Franklin Roosevelt"
https://ror.org/00meyfe69 - Universidad Privada Peruano Alemana
https://ror.org/039vhkg84 - Comisión Nacional de Investigación y Desarrollo Aeroespacial
https://ror.org/01kq4t285 - Instituto Geográfico Nacional
https://ror.org/00hmkqz52 - Instituto Nacional de Ciencias Neurológicas
https://ror.org/03t9kaa43 - Instituto Nacional de Defensa de la Competencia y de la Protección de la Propiedad Intelectual
https://ror.org/02e838q34 - Instituto Nacional de Estadística e Informática
https://ror.org/004qcrr52 - Instituto Nacional de Innovación Agraria
https://ror.org/05t25a229 - Instituto Nacional de Oftalmología "Dr. Francisco Contreras Campos"
https://ror.org/02c3p9381 - Instituto Nacional de Rehabilitación de "Dra. Adriana Rebaza Flores" Amistad Perú-Japón
https://ror.org/03yhwzd24 - Instituto Nacional de Salud del Niño-San Borja
https://ror.org/00s582952 - Instituto Nacional de Salud Mental "Honorio Delgado - Hideyo Noguchi"
https://ror.org/04bk2qw80 - Instituto Peruano de Energía Nuclear
https://ror.org/003z0hw02 - Instituto Tecnológico de la Producción
https://ror.org/00tfqpy41 - Servicio Nacional de Sanidad Agraria
https://ror.org/00rs6s651 - Museo de Historia Natural

**Comment by GianmarcoGC** [comment]
Muy buena iniciativa para organizaciones e instituciones públicas donde todos los nombres se uniformicen en bases de datos como scopus y web of science atreves de **ROR**
