### ISSUE TITLE
Add a new organization to ROR: 
 
Kültür ve Turizm Bakanlığı

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#234]
Summary of request: Add a new organization to ROR

Name of organization: Kültür ve Turizm Bakanlığı
Website: https://www.ktb.gov.tr
Link to publications: 10.37879/belleten.2021.1 10.37879/belleten.2020.503
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://tr.wikipedia.org/wiki/T%C3%BCrkiye_Cumhuriyeti_K%C3%BClt%C3%BCr_ve_Turizm_Bakanl%C4%B1%C4%9F%C4%B1
Wikidata ID: https://www.wikidata.org/wiki/Q3136957
ISNI ID: https://isni.org/isni/0000000117815781
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Türkiye Cumhuriyeti Kültür ve Turizm Bakanlığı, T.C. Kültür ve Turizm Bakanlığı, Ministry of Culture and Tourism
Acronym/abbreviation: KTB
Related organizations: 
City: Ankara
Country: Turkey
Year established: 2018
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets
Other information about this request:

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04zsc3j83 in release v1.0.
