### ISSUE TITLE
Modify the information in an existing ROR record: 
Kosuyolu Yuksek Ihtisas Egitim ve Arastirma Hastanesi https://ror.org/054q9np86


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#235]
Summary of request: Modify the information in an existing ROR record

Name of organization: Kosuyolu Yuksek Ihtisas Egitim ve Arastirma Hastanesi
ROR ID: https://ror.org/054q9np86
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website
Description of change: Organization name and url has been changed. Wikidata record holds valid "Turkish name" field but url information still holds the old one. (https://www.wikidata.org/wiki/Q30280319) New name: Kartal Koşuyolu Yüksek İhtisas Eğitim ve Araştırma Hastanesi New url: https://kosuyolueah.saglik.gov.tr Alternative names: İstanbul Kartal Koşuyolu Yüksek İhtisas Eğitim ve Araştırma Hastanesi, Koşuyolu Yüksek İhtisas Eğitim ve Araştırma Hastanesi, Kartal Koşuyolu High Specialization Training and Research Hospital, Kartal Kosuyolu High Specialization Training and Research Hospital

MG Note:
Change name: Kartal Koşuyolu High Specialization Training and Research Hospital
Add aliases: İstanbul Kartal Koşuyolu Yüksek İhtisas Eğitim ve Araştırma Hastanesi
Add label: Kartal Koşuyolu Yüksek İhtisas Eğitim ve Araştırma Hastanesi (Turkish)
Replace links: https://kosuyolueah.saglik.gov.tr

Update: change.name==Kartal Koşuyolu High Specialization Training and Research Hospital; add.aliases==İstanbul Kartal Koşuyolu Yüksek İhtisas Eğitim ve Araştırma Hastanesi; add.labels==Kartal Koşuyolu Yüksek İhtisas Eğitim ve Araştırma Hastanesi*Turkish; replace.links==https://kosuyolueah.saglik.gov.tr/;

**Comment by arthurpsmith** [comment]
This seems straightforward. However, we perhaps want to make the main name the English one they provide, "Kartal Kosuyolu High Specialization Training and Research Hospital", and keep their suggested name along with some of the alternatives as language labels (Turkish).

The old website URL does not appear to be responding, so we definitely should update that as well.

**Comment by carlyrobinson** [comment]
Agree with @arthurpsmith

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
