### ISSUE TITLE
Add a new organization to ROR: Colegio Nacional de Monserrat

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2354]
Summary of request: Add a new organization to ROR

Name of organization: Colegio Nacional de Monserrat
Website: https://monserrat.unc.edu.ar
Link to publications: 
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Colegio_Nacional_de_Monserrat
Wikidata ID: Q5142862
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/056tb7j80 (parent)
City: Córdoba
Country: Argentina
Geonames ID: 3860259
Year established: 1687
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Long-standing secondary education institute and child of https://ror.org/056tb7j80, identified in https://github.com/ror-community/ror-updates/issues/2350. Affiliation usage is solid, so we can add.

Publication affiliation usage: https://openalex.org/W3171523181; https://openalex.org/W1535055951; https://doi.org/10.19137/cuadex-2020-04-04; https://openalex.org/W3035398101

ORCID affiliation usage: https://orcid.org/0000-0001-7242-4417 ; https://orcid.org/0000-0002-3189-5551 ; https://orcid.org/0000-0001-8641-3284

**Comment by mariagould** [comment]
I agree this is in scope as an education institution and given evidence of research activity and affiliation usage.
