### ISSUE TITLE
Add a new organization to ROR: Manuel Belgrano Higher School of Commerce

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2355]
Summary of request: Add a new organization to ROR

Name of organization: Escuela Superior de Comercio Manuel Belgrano
Website: https://mb.unc.edu.ar
Link to publications: 
Organization type: Education
Wikipedia page: https://es.wikipedia.org/wiki/Escuela_Superior_de_Comercio_Manuel_Belgrano
Wikidata ID: Q17630946
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Manuel Belgrano Higher School of Commerce
Acronym/abbreviation:
Related organizations: https://ror.org/056tb7j80 (parent)
City: Córdoba
Country: Argentina
Geonames ID: 3860259
Year established: 1938
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Long-standing secondary education institute and child of https://ror.org/056tb7j80, identified in https://github.com/ror-community/ror-updates/issues/2350. Affiliation usage is solid, so we can add.

Publication affiliation usage: https://api.openalex.org/W1535055951; https://api.openalex.org/W1503280662

ORCID affiliation usage: https://orcid.org/0000-0001-9434-7344 ; https://orcid.org/0000-0002-6174-2775

**Comment by mariagould** [comment]
I agree this is in scope as an educational institution and given evidence of research activity and affiliation usage. 

I added Wikipedia link and Wikidata ID. Also adjusted capitalization in primary name following convention used on organization's website.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05yfjjn56 in release v1.20.
