### ISSUE TITLE
Add a new organization to ROR: 
 
The Cancer Imaging Archive

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#236]
Summary of request: Add a new organization to ROR

Name of organization: The Cancer Imaging Archive
Website: https://www.cancerimagingarchive.net
Link to publications: Yes
Organization type: Archive (An organization involved in stewarding research and cultural heritage materials. Includes libraries, museums, and zoos)
Wikipedia page: https://en.wikipedia.org/wiki/The_Cancer_Imaging_Archive_(TCIA)
Wikidata ID: https://www.wikidata.org/wiki/Q25339822
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: n/a
Acronym/abbreviation: TCIA
Related organizations: University of Arkansas for Medical Sciences https://ror.org/00xcryt71 (related), National Cancer Institute https://ror.org/040gcmg81 (related), Frederick National Laboratory for Cancer Research https://ror.org/03v6m3209 
(related)
City: Little Rock
Country: United States
Year established: 2010
How will a ROR ID for this organization be used? To identify affiliations for datasets
Other information about this request: The Cancer Imaging Archive (TCIA) is a data publisher of cancer related images and supporting data that is funded by NIH/NCI, managed by the Frederick National Laboratory for Cancer Research and hosted and operated by the University of Arkansas for Medical Sciences. TCIA has an advisory board that approves TCIA hosted imaging collections. TCIA is a trusted repository for Nature Scientific Data, Medical Physics and other journals. As such, TCIA needs its own ROR.

**Comment by nlundvick** [comment]
In scope. No affiliation use found, but organization is involved in research by hosting and curating cancer imaging data. There are many publications that include TCIA images/data: https://www.cancerimagingarchive.net/publications/. ROR includes many similar archives and repositories. Recommend adding to ROR.

**Comment by arthurpsmith** [comment]
I agree with Nick this should have a ROR. As the request notes, it can be considered to have multiple "parent" organizations so it qualifies on those grounds also.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02qyzaf42 in release v1.0.
