### ISSUE TITLE
Add a new organization to ROR: 
 
Centro de Investigación Biomédica en Red de Enfermedades Respiratorias

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#237]
Summary of request: Add a new organization to ROR

Name of organization: Centro de Investigación Biomédica en Red de Enfermedades Respiratorias
Website: https://ciberes.org
Link to publications: https://doi.org/10.3389/fmicb.2021.660403 ; https://doi.org/10.1038/s41467-021-24383-3 ; 10.1080/21505594.2021.1937883 ; https://doi.org/10.1128/JVI.00321-21 ; 
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: https://isni.org/isni/0000000478633182
GRID ID: 
Crossref Funder ID: 
Other names for the organization: CIBER de Enfermedades Respiratorias; Biomedical Research Networking Center on Respiratory Diseases
Acronym/abbreviation: CIBERES
Related organizations: Related institutions: https://ror.org/00zca7903 ; https://ror.org/01ygm5w19 ;  https://ror.org/03cn6tr16 ; https://ror.org/00dwgct76 ; https://ror.org/009byq155 ; https://ror.org/01gm5f004 ; https://ror.org/050q0kv47 ; https://ror.org/02s65tk16
City: Madrid
Country: Spain
Year established: 
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets
Other information about this request:

**Comment by nlundvick** [comment]
In scope, multiple instances of affiliation use. Sibling organizations already in ROR. Recommend adding to ROR.

**Comment by arthurpsmith** [comment]
I added the ISNI for this research institute; they have a slightly different English version of the name - "Biomedical Research Network Centre in Respiratory Diseases", maybe that should be another alias?

Also note that the type for the sibling organizations is listed as "Facility"; that may be more appropriate than "government" here, I think we generally use "Facility" for research institutes like this one.

**Comment by mariagould** [comment]
https://ror.org/0119pby33
