### ISSUE TITLE
Modify the information in an existing ROR record: 
University of Applied Sciences Würzburg-Schweinfurt https://ror.org/01k5h5v15


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#239]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Applied Sciences Würzburg-Schweinfurt
ROR ID: https://ror.org/01k5h5v15
Which part of the record needs to be changed? Other names or name versions listed in the record
Description of change: The german aliases lack the addition of "Würzburg-Schweinfurt". They should be "Fachhochschule Würzburg-Schweinfurt" and "Hochschule für angewandte Wissenschaften Würzburg-Schweinfurt".
Other information about this request:

**Comment by MSpenger** [comment]
The requested change should be added to the aliases. There are many "Fachhochschule" and "Hochschule für angewandte Wissenschaften" and the addition of a city is necessary to distinguish between them.

**Comment by arthurpsmith** [comment]
Oh, yes definitely the German names on this are very ambiguous right now! Let's get this fixed!
