### ISSUE TITLE
Project: Lille University Research Units

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2399]
Lille University has compared the HAL research units against ROR and submitted a set of their research units they would like added. These should be reviewed for metadata accuracy and scope.

https://docs.google.com/spreadsheets/d/1KdOaLKzx03kHD8sVXvBgLLCoa9_jltbC/edit?usp=sharing&ouid=109915645277784756470&rtpof=true&sd=true

**Comment by adambuttrick** [comment]
Limiting first set of new records to those with multiple parents, determined to be active, as listed in the multiple parents tab.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/053ppfe96 in release v1.20.

**Comment by maximecaz** [comment]
Hi,
I am the person who sent you the spreadsheet. Could you please give me some information about the integration into the ROR?
Maxime from University of Lille.

**Comment by adambuttrick** [comment]
@maximecaz Thank you for checking in on this. We've recently received a large volume of requests for French research units and are currently doing an assessment on what level of hierarchy is appropriate for these organizations in ROR. Traditionally, only multi-parent research units at a single level of hierarchy would be in scope for the registry, so in release v1.20 we added the units that met this criteria. I've listed the names and ROR IDs for these records below. 

ROR ID | Organization name
-- | --
https://ror.org/053ppfe96 | Systèmes avancés de délivrance de principes actifs
https://ror.org/032v67m28 | UMR Transfrontalière BioEcoAgro
https://ror.org/05x9zmx47 | CANTHER - Hétérogénéité, Plasticité et Résistance aux Thérapies des Cancers
https://ror.org/00g32ep81 | Centre d'Histoire Judiciaire
https://ror.org/04p4jgt68 | Centre d'Investigation Clinique - Innovation Technologique de Lille
https://ror.org/05vrs3189 | Centre de Recherche en Informatique, Signal et Automatique de Lille
https://ror.org/04k5h2q42 | Génomique fonctionnelle métabolique (epi) et mécanismes moléculaires impliqués dans le diabète de type 2 et les maladies apparentées
https://ror.org/02dvx0516 | Groupe de Recherche sur les formes Injectables et les Technologies Associées
https://ror.org/01ja5aj48 | Histoire, Archéologie et Littérature des Mondes Anciens
https://ror.org/013z99a51 | AERIS/ICARE Data and Services Center
https://ror.org/0455vgw31 | IMPact de l'Environnement Chimique sur la Santé humaine
https://ror.org/03qy9z186 | Institute for Translational Research in Inflammation
https://ror.org/010nk4c68 | Institut de Recherche sur les Composants logiciels et matériels pour l'Information et la Communication Avancée
https://ror.org/04f5rw142 | Laboratoire de Mécanique, Multiphysique, Multiéchelle
https://ror.org/00fh1dw28 | Laboratoire de Génie Civil et Géo Environnement
https://ror.org/04p94ax69 | Lille Neurosciences & Cognition
https://ror.org/0086epd30 | Médicaments et Molécules pour Agir sur les Systèmes Vivants
https://ror.org/00hz02a80 | Marrow Adiposity & Bone Lab
https://ror.org/01qygwc68 | Evaluation des technologies de santé et des pratiques médicales
https://ror.org/04q29nn62 | OncoThAI
https://ror.org/05fjffm04 | Laboratoire de Physiologie Cellulaire 
https://ror.org/056hav897 | Plateformes Lilloises en Biologie et Santé
https://ror.org/03rvrjk28 | Facteurs de risque et déterminants moléculaires des maladies liées au vieillissement
https://ror.org/03pbmtd68 | Recherche translationnelle sur le diabète
https://ror.org/00tt79z10 | Unité de Mécanique de Lille - Joseph Boussinesq

I've likewise separated out the outstanding requested units into [a separate sheet in the submitted file](https://docs.google.com/spreadsheets/d/1KdOaLKzx03kHD8sVXvBgLLCoa9_jltbC/edit?usp=sharing&ouid=109915645277784756470&rtpof=true&sd=true).

Once our assessment is complete, we will update the issue and publish records for any additional units. Apologies for the delay. Because these kinds of decisions can have wide-ranging impacts for how we curate the registry, we have to be somewhat cautious in how we proceed.

**Comment by adambuttrick** [comment]
In scope, per discussion with Ministère de l'enseignement supérieur de la recherche and larger project to include all level two research French units.

**Comment by adambuttrick** [comment]
@maximecaz The remainder of these research units will be published in our next release, v1.22, which is currently scheduled for next week.

**Comment by adambuttrick** [comment]
Added in release v1.22.

ROR ID | Organization name
-- | --
https://ror.org/05q5m4q74 | Analyses Littéraires et Histoire de la Langue
https://ror.org/00bwykg15 | Centre d'Etude des Arts Contemporains
https://ror.org/016w4zy25 | Centre de Recherche "Individus, Epreuves, Sociétés"
https://ror.org/00ccaam24 | Centre Interuniversitaire de Recherche en Education de Lille
https://ror.org/047y28a09 | Centre de Recherche Droits et Perspectives du droit
https://ror.org/02tznxc41 | Groupe d'Etudes et de Recherche Interdisciplinaire en Information et Communication
https://ror.org/006vqpx82 | Laboratoire de Virologie - Pathogenèse virale
https://ror.org/0409gk363 | LACTH - Laboratoire d'Architecture Conception Territoire Histoire Matérialité
https://ror.org/00jsgkx16 | Lille School of Management Research Center
https://ror.org/02hkbys70 | Lille University Management
https://ror.org/044xe8e90 | Psychologie : Interactions, Temps, Emotions, Cognition
https://ror.org/03ya3d516 | Unité de Taphonomie Médico-Légale
