### ISSUE TITLE
Add a new organization to ROR: Universitätsbibliothek der LMU München

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#24]
Summary of request: Add a new organization to ROR

Name of organization: Universitätsbibliothek der LMU München
Website: https://www.ub.uni-muenchen.de
Link to publications: DOI Prefix 10.5282
Organization type: Archive
Wikipedia page:
Wikidata ID: https://www.wikidata.org/wiki/Q2496326
ISNI ID:
GRID ID:
Crossref Funder ID:
Acronyms: ITG
Aliases:
Labels: University Library of the LMU München*English
Acronym/abbreviation:
Related organizations: https://ror.org/05591te55 (parent)
City: Munich
Country: Germany
Geonames ID: 2867714
Year established:
How will a ROR ID for this organization be used?
Other information about this request: The institution is also taking the role of a publisher and the institution name is prominently featured in our DataCite metadata. And as we plan to assign around 17.000 retro entries (mainly thesis and texts) with DOIs this year, we also wanted to make the best use of ORCID and ROR as well.

**Comment by mariagould** [comment]
This is a legacy issue from early days of the curation pilot in 2020 and we were not able to make a clear determination on scope at the time. I am reinstating it for review now. @MSpenger I believe you initially created this request, so can you confirm whether the request is still valid, and if so, how we would evaluate it given our current criteria and workflows?

I will note that we have up to this point determined that university libraries are not in scope, so my recommendation is that this should not have a ROR ID, but I am flagging it for group discussion so we can close the loop.

**Comment by MSpenger** [comment]
Regarding our recent recommendations, I would also not include this entry in ROR.

One thing that might come up for further discussion is the role of university libraries as publishers. The "Universitätsbibliothek der LMU München" is publishing born digital content as well as hybrid formats in an own imprint, e.g. https://www.en.ub.uni-muenchen.de/writing/open_publishing_lmu/oph/index.html
