### ISSUE TITLE
Add a new organization to ROR: Divine Mercy University

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2406]
Summary of request: Add a new organization to ROR

Name of organization: Divine Mercy University
Website: https://www.divinemercy.edu
Link to publications: 
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Divine_Mercy_University
Wikidata ID: Q28230919
ISNI ID: 0000 0004 5345 4575
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City: Sterling
Country: United States
Geonames ID: 4787534
Year established: 2015
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Private Catholic university in the United States. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1002/cvj.12156; https://doi.org/10.1007/s10943-018-0574-6; https://doi.org/10.1080/13674676.2018.1458083; https://openalex.org/W2787840195; https://doi.org/10.1007/s11896-020-09413-y; https://doi.org/10.1080/17439760.2016.1228005; https://doi.org/10.1177/0953946816658720; https://doi.org/10.1177/0024363919856810; https://doi.org/10.1016/j.lmot.2019.01.002

ORCID affiliation usage: https://orcid.org/0000-0002-7375-3770 ; https://orcid.org/0000-0001-6376-0662 ; https://orcid.org/0000-0003-1662-2296

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0308crw96 in release v1.20.
