### ISSUE TITLE
Add a new organization to ROR: Kinneret College on the Sea of Galilee

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2407]
Summary of request: Add a new organization to ROR

Name of organization: Kinneret College on the Sea of Galilee
Website: https://www.kinneret.ac.il
Link to publications: 
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Kinneret_College
Wikidata ID: Q6414075
ISNI ID: 0000 0004 0604 9067
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Kinneret College; Kinneret Academic College; Kinneret Academic College in the Jordan Valley; 
Labels: המכללה האקדמית כנרת בעמק הירדן*Hebrew;  كلية كينيريت الأكاديمية*Arabic
Acronym/abbreviation:
Related organizations: 
City: Galilee
Country: Israel
Geonames ID: 294932
Year established: 1965
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
College in Israel. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1007/s10956-007-9057-3; https://doi.org/10.1016/j.chb.2015.02.057; https://doi.org/10.1080/13032917.2008.9687080; https://doi.org/10.1016/j.jhtm.2016.02.003; https://doi.org/10.1111/j.1651-2227.2010.01821.x; https://doi.org/10.1007/s12144-016-9496-1; https://doi.org/10.1016/j.invent.2018.05.002; https://doi.org/10.1016/j.annals.2010.06.002; https://doi.org/10.1007/s10984-015-9174-5

ORCID affiliation usage: https://orcid.org/0000-0001-9097-3786 ; https://orcid.org/0000-0003-1557-1810 ; https://orcid.org/0000-0003-1248-8712

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05402ng93 in release v1.20.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01ja5aj48 in release v1.20.
