### ISSUE TITLE
Add a new organization to ROR: Fundacion Universitaria San Pablo CEU

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2408]
Summary of request: Add a new organization to ROR

Name of organization: Fundacion Universitaria San Pablo CEU
Website: https://www.ceu.es/
Link to publications: 
Organization type: 
Wikipedia page: https://en.wikipedia.org/wiki/Centro_de_Estudios_Universitarios
Wikidata ID:
ISNI ID: 0000 0001 1193 582X
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Centro de Estudios Universitarios
Labels:
Acronym/abbreviation:
Related organizations: 
City: Madrid
Country: Spain
Geonames ID: 
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Already exists in ROR under its former name - https://ror.org/04a0dbe36 - although looks it looks like GRID had the location wrong. Will create request to update.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/013z99a51 in release v1.20.
