### ISSUE TITLE
Add a new organization to ROR: 
 
Unichem Laboratories Ltd

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#241]
Summary of request: Add a new organization to ROR

Name of organization: Unichem Laboratories Ltd
Website: https://www.unichemlabs.com/
Link to publications: https://scholar.google.com/scholar?hl=en&as_sdt=0,5&qsp=1&q=unichem+laboratories&qst=bb
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: https://en.wikipedia.org/wiki/Unichem_Laboratories
Wikidata ID: https://www.wikidata.org/wiki/Q7884723
ISNI ID: https://isni.org/isni/0000000405029777
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Acasia, Unichem Europe, Unichem USA
Acronym/abbreviation: n/a
Related organizations: none
City: Mumbai
Country: India
Year established: 1944
How will a ROR ID for this organization be used? To acknowledge a research facility
Other information about this request:

**Comment by arthurpsmith** [comment]
I added Wikidata and ISNI id's.

The organization is definitely engaged in research and used as an affiliation, and is not part of some larger entity as far as I can see. It should have a ROR id.

**Comment by carlyrobinson** [comment]
Agreed, it should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03ddvws43 in release v1.0.
