### ISSUE TITLE
Add a new organization to ROR: Institut Regional du Cancer de Montpellier

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2419]
Summary of request: Add a new organization to ROR

Name of organization: Institut Regional du Cancer de Montpellier
Website: https://www.icm.unicancer.fr
Link to publications: 
Organization type: Healthcare
Wikipedia page:
Wikidata ID: Q16643770
ISNI ID: 0000 0000 9452 8287
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: ICM
Related organizations: https://ror.org/04vhgtv41 (parent)
City: Montpellier
Country: France
Geonames ID:  2992166
Year established: 1923
How will a ROR ID for this organization be used? 
Other information about this request: Description of research areas can be found here: https://www.icm.unicancer.fr/fr/linstitut-du-cancer-de-montpellier/la-recherche

**Comment by adambuttrick** [comment]
Cancer treatment and research facility in France. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1101/344465; https://doi.org/10.1200/jco.2021.39.15_suppl.5548; https://doi.org/10.1158/1078-0432.ccr-20-3416; https://doi.org/10.1111/jir.12336; https://doi.org/10.1016/j.ejca.2021.11.012; https://doi.org/10.1101/2022.06.29.497942; https://doi.org/10.1093/annonc/mdt042.29

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02693j602 in release v1.20.
