### ISSUE TITLE
Add a new organization to ROR: Centre Henri Becquerel

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2420]
Summary of request: Add a new organization to ROR

Name of organization: Centre Henri Becquerel
Website: https://www.becquerel.fr
Link to publications: 
Organization type: Facility
Wikipedia page: https://fr.wikipedia.org/wiki/Centre_Henri-Becquerel
Wikidata ID: Q2944818
ISNI ID: 0000 0000 9653 5464
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/04vhgtv41 (parent)
City: Rouen
Country: France
Geonames ID: 2982652
Year established: 1967
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Cancer treatment and research facility in France. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1016/0167-8140(92)90242-m; https://doi.org/10.1038/76006; https://doi.org/10.1093/annonc/mdv304; https://doi.org/10.1038/sj.leu.2403202; https://doi.org/10.1016/j.ccr.2011.06.003; https://doi.org/10.1016/s0140-6736(07)61537-2; https://doi.org/10.1182/blood-2010-03-276246; https://doi.org/10.1016/s0140-6736(12)60485-1; https://doi.org/10.1016/s0140-6736(10)62175-7

ORCID affiliation usage: https://orcid.org/0000-0002-1630-6421 ; https://orcid.org/0000-0002-1989-453X ; https://orcid.org/0000-0001-8269-2140

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00whhby07 in release v1.20.
