### ISSUE TITLE
Project: SLAC Bulk Submission

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2430]
As part of a new ROR integration, https://ror.org/05gzmn429 has submitted a list of 37 organizations to be added to the registry. These should be reviewed for scope and added where appropriate.

https://docs.google.com/spreadsheets/d/1LELg-T9nkv7ozV3xoi0G4ALwAkMxpVc6/edit#gid=1878538060

**Comment by carlyrobinson** [comment]
The Advanced Photon Source (APS) and the National  Synchrotron Light Source II (NSLS II) are both DOE user facilities that perform and produce research. 
https://science.osti.gov/bes/suf/User-Facilities/X-Ray-Light-Sources/NSLS-II
https://science.osti.gov/bes/suf/User-Facilities/X-Ray-Light-Sources/APS

They have staff that are authors of papers that would use the facility as their affiliation. Some of the DOE facilities (more in the future) are assigning award DOIs and need ROR ID to included in the DOI metadata as the "funding organization" awarding time to use those facilities.

As with other DOE facilities that have been included in ROR, I think APS and NSLS II should be included and meet the requirements for adding.

**Comment by adambuttrick** [comment]
@arthurpsmith @carlyrobinson Thanks so much! Very helpful!

**Comment by nlundvick** [comment]
Advanced hCMOS Systems is a private facility and sufficiently independent from Sandia Lab. I found three instances of affiliation use in scholarly publications:

- https://meetings.aps.org/Meeting/DPP22/Session/GO06.1
- https://doi.org/10.1364/OE.472275
- https://doi.org/10.1063/5.0107542

Additional affiliation use:

- https://www.researchgate.net/profile/Liam-Claus

The facility is fairly new (established 2021) so limited affiliation use to be expected. I consider this organization to be in scope. Add to ROR.

**Comment by nlundvick** [comment]
@adambuttrick @arthurpsmith 

Weighing in on the Swiss Light Source question - I consider this to be a very similar facility to the Advanced Photon Source at Argonne. Similar to APS and other synchrotron light sources, it provides access to external users: https://www.psi.ch/en/sls/users. Affiliation use is almost always associated with PSI, but I would consider this it to be in scope under the facility use case.

**Comment by adambuttrick** [comment]
@nlundvick thanks so much for reviewing!

**Comment by adambuttrick** [comment]
Added all new records in release v1.21.
