### ISSUE TITLE
Add a new organization to ROR: 
 
Punta Culebra Nature Center

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#244]
Summary of request: Add a new organization to ROR

Name of organization: Punta Culebra Nature Center
Website: https://stri.si.edu/facility/punta-culebra
Link to publications: https://doi.org/10.1371/journal.pone.0247551
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: None
Acronym/abbreviation: NONE
Related organizations: Smithsonian Institution (https://ror.org/01pp8nd67), Smithsonian Tropical Research Institute (https://ror.org/035jbxr46)
City: Punta Culebra
Country: Panama
Year established: 1964
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility
Other information about this request:

**Comment by mariagould** [comment]
Part of a cluster of requests along with #245 and #243 (as well as #246 which was already processed in the latest GRID release)

**Comment by nlundvick** [comment]
This is a Smithsonian Tropical Research Institute facility. All affiliation uses for this organization, and related requests, are at the parent level. URL is a subdomain of STRI. Not in scope. Recommend requestor use ROR for STRI (https://ror.org/035jbxr46)

**Comment by nlundvick** [comment]
Per ROR curation team meeting 2021-09-07, this should be added to ROR with Smithsonian Tropical Research Institute (https://ror.org/035jbxr46) as the parent organization

**Comment by arthurpsmith** [comment]
I think this one does have a Wikipedia entry and Wikidata id:
https://en.wikipedia.org/wiki/Marine_Exhibition_Center_of_Punta_Culebra
https://www.wikidata.org/wiki/Q6764140

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01ge7v435 in release v1.0.
