### ISSUE TITLE
Add a new organization to ROR: 
 
Fortuna Field Station

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#245]
Summary of request: Add a new organization to ROR

Name of organization: Fortuna Field Station
Website: https://stri.si.edu/facility/fortuna 
Link to publications: https://doi.org/10.5479/si.14315990.v1
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Jorge L. Araúz Research Center, Fortuna Station, Green House, Vivero
Acronym/abbreviation: None
Related organizations: Smithsonian Institution (https://ror.org/01pp8nd67), Smithsonian Tropical Research Institute (https://ror.org/035jbxr46)
City: Chiriquí Province, 8.45°, -82.15° 
Country: Panama
Year established: 1976
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility
Other information about this request:

**Comment by mariagould** [comment]
Part of a cluster of requests along with #244 and #243 (as well as #246 which was already processed in the latest GRID release)

**Comment by nlundvick** [comment]
This is a Smithsonian Tropical Research Institute field station. All affiliation uses for this organization, and related requests, are at the parent level. URL is a subdomain of STRI. Not in scope. Recommend requestor use ROR for STRI (https://ror.org/035jbxr46)

**Comment by nlundvick** [comment]
Per ROR curation team meeting 2021-09-07, this should be added to ROR with Smithsonian Tropical Research Institute (https://ror.org/035jbxr46) as the parent organization

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05s45j557 in release v1.0.
