### ISSUE TITLE
Add a new organization to ROR: Instituto de Investigaciones Forestales de la Amazonía

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2452]
Summary of request: Add a new organization to ROR

Name of organization: Instituto de Investigaciones Forestales de la Amazonía
Website: https://facultad.uabjb.edu.bo/fcf/index.php/institutos-de-investigaciones/iifa
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: IIFA
Related organizations: https://ror.org/03ztnr397 (parent)
City: Riberalta
Country: Bolivia
Geonames ID: 3906466
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Amazon rain forest monitoring and research institute, identified in https://github.com/ror-community/ror-updates/issues/2445. I'm seeing a fair amount of secondary references to this. Affiliation usage is more limited, but is typically leading for https://ror.org/03ztnr397. Since the request is identifying a specific difficulty with identifying their publication outputs and is located separate from the university parent, I suppose we can add. Seems to serve a similar regional function as the various LTER entities.

Publication affiliation_usage: https://doi.org/10.1111/geb.13531; https://cipca.org.bo/docs/publications/es/228_mundos-rurales-15-web.pdf#page=25

**Comment by arthurpsmith** [comment]
I'm not seeing a lot of research output from this institute; also it looks like it is always identified as part of UABJB. The website is very minimal, listing only one publication which doesn't even have this as an affiliation. I think this is out of scope for ROR, at least for now.

**Comment by arthurpsmith** [comment]
However, maybe somebody more familiar with South American research should take a look?

**Comment by adambuttrick** [comment]
I'll see if anyone we work with in the region has any insights.

**Comment by adambuttrick** [comment]
Unable to confirm any additional details about this organization, so declining as out of scope.
