### ISSUE TITLE
Modify the information in an existing ROR record: Istituto Nazionale di Riposo e Cura per Anziani - https://ror.org/057aq1y25

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2457]
Summary of request: Modify the information in an existing ROR record

Name of organization: Istituto Nazionale di Riposo e Cura per Anziani
ROR ID: https://ror.org/057aq1y25
Which part of the record needs to be changed? Name
Description of change: The name seems to have changed to INRCA-IRCCS, although an expert in the Italian system is best placed to judge. The URL of INRCA-IRCCS is the same as the URL on https://ror.org/057aq1y25, i.e. https://www.inrca.it/inrca/

Update: add.aliases==Istituto di Ricerca a Carattere Scientifico - Istituto Nazionale di Riposo e Cura per Anziani; replace.links==https://www.inrca.it/inrca/; add.acronyms==IRCCS-INRCA;$

Related organizations: https://ror.org/04tfzc498 (parent)

**Comment by adambuttrick** [comment]
Adding this as an alias and additional acronym for now as the most commonly referenced forms are still those currently on the record.

**Comment by adambuttrick** [comment]
Record updated in release v1.21.
