### ISSUE TITLE
Add a new organization to ROR: 
 
Bocas Del Toro Research Station

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#246]
Summary of request: Add a new organization to ROR

Name of organization: Bocas Del Toro Research Station
Website: https://stri.si.edu/facility/bocas-del-toro
Link to publications: https://doi.org/10.5479/si.01960768.38.73
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: https://en.wikipedia.org/wiki/Bocas_del_Toro_Research_Station
Wikidata ID: https://www.wikidata.org/wiki/Q4936149
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: None
Acronym/abbreviation: None
Related organizations: Smithsonian Institution (https://ror.org/01pp8nd67), Smithsonian Tropical Research Institute (https://ror.org/035jbxr46)
City: Colón Island, 9.352, -82.256 
Country: Panama
Year established: 1998
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility
Other information about this request:

**Comment by mariagould** [comment]
Part of a cluster of requests from the Smithsonian. This one has already been processed in the latest GRID release.

Related requests: 
- #244
- #245
- #250 
- #251 
- #252

**Comment by nlundvick** [comment]
This is a Smithsonian Tropical Research Institute research station. All affiliation uses for this organization, and related requests, are at the parent level. URL is a subdomain of STRI. Not in scope. Recommend requestor use ROR for STRI (https://ror.org/035jbxr46)

**Comment by nlundvick** [comment]
Per ROR curation team meeting 2021-09-07, this should be added to ROR with Smithsonian Tropical Research Institute (https://ror.org/035jbxr46) as the parent organization

**Comment by mariagould** [comment]
https://ror.org/02ftc8763
