### ISSUE TITLE
Add a new organization to ROR: Fundación Instituto de Empresa

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2461]
Summary of request: Add a new organization to ROR

Name of organization: Fundación IE
Website:  https://www.ie.edu/es/fundacion-ie/
Link to publications: 
Organization type: Other
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0000 9355 8812
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Fundación Instituto de Empresa
Labels: IE Foundation*English
Acronym/abbreviation:
Related organizations: https://ror.org/02jjdwm75 (parent)
City:  Madrid
Country: Spain
Geonames ID: 3117735
Year established: 1997
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Nonprofit funding and development arm of https://ror.org/02jjdwm75. Affiliation usage exists at this level, so this is fine to add.

Publication affiliation usage: https://doi.org/10.2139/ssrn.1134491; https://doi.org/10.1111/j.1540-6520.2012.00529.x; https://doi.org/10.2139/ssrn.1015883; https://doi.org/10.5465/amp.24.1.62; https://doi.org/10.2139/ssrn.1015363; https://doi.org/10.2139/ssrn.1134489; https://doi.org/10.2139/ssrn.1134505; https://openalex.org/W3122202648

ORCID affiliation usage: https://orcid.org/0000-0003-4157-2956 ; https://orcid.org/0000-0002-2800-7437 ; https://orcid.org/0000-0002-8767-8556

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00c5kmy11 in release v1.21.
