### ISSUE TITLE
Add a new organization to ROR: Child Neurology Society

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2462]
Summary of request: Add a new organization to ROR

Name of organization: Child Neurology Society
Website:  https://www.childneurologysociety.org
Link to publications: 
Organization type: Other
Wikipedia page:
Wikidata ID: Q85340929
ISNI ID: 0000 0004 0566 843X
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City:  Saint Paul
Country: USA
Geonames ID: 5045360
Year established:
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Academic society and research funder. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1016/j.jpeds.2008.10.021; https://doi.org/10.1017/s0317167100046801; https://doi.org/10.1111/j.1469-8749.2011.04075.x; https://doi.org/10.1016/j.clnesp.2017.09.010; https://doi.org/10.1177/0883073809359936; https://doi.org/10.1016/j.yebeh.2017.12.009; https://doi.org/10.1111/epi.16625

ORCID affiliation usage: https://orcid.org/0000-0002-9812-1083 ; https://orcid.org/0000-0002-3792-9898 ; https://orcid.org/0000-0003-2253-8955

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05aqazf41 in release v1.21.
