### ISSUE TITLE
Add a new organization to ROR: International Society of Bipolar Disorders

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2463]
Summary of request: Add a new organization to ROR

Name of organization: International Society of Bipolar Disorders
Website:  https://www.isbd.org
Link to publications: 
Organization type: Other
Wikipedia page:
Wikidata ID: Q6053330
ISNI ID: 0000 0004 6464 8308
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City:  Monroeville
Country: USA
Geonames ID: 5201734
Year established: 1999
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Academic society and research funder. Publishes journal, "Bipolar Disorders," and thus would be in scope for our publisher use case.

Publication affiliation usage: https://doi.org/10.2217/ebo.11.273

ORCID affiliation usage: https://orcid.org/0000-0001-5450-1300 ; https://orcid.org/0000-0003-1145-8669 ; https://orcid.org/0000-0001-9016-2414

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04q6sm464 in release v1.21.
