### ISSUE TITLE
Add a new organization to ROR: Central European University - Budapest Campus

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2464]
Summary of request: Add a new organization to ROR

Name of organization: Central European University - Budapest Campus
Website:  https://www.ceu.edu/campus
Link to publications: 
Organization type: Education
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 9333 8464
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/02zx40v98 (parent)
City:  Budapest
Country: Hungary
Geonames ID: 3054643
Year established:
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Request here is to distinguish the Budapest campus from the Austrian one for https://ror.org/02zx40v98. Affiliation usage seems to bear out this distinction and they do exist in separate countries. If created, we would perhaps instantiate as a child organization, as [self-description](https://www.ceu.edu/about) and indicated accreditation is emphasized as being in Austria.

Publication affiliation usage: https://doi.org/10.1098/rstb.2010.0319; https://doi.org/10.1177/1354066100006002001; https://doi.org/10.1016/j.physrep.2020.05.004; https://doi.org/10.1016/s0140-6736(16)00619-x; https://doi.org/10.1080/13501760410001694291; https://doi.org/10.1126/science.aao0185; https://doi.org/10.1038/nn.4171; https://doi.org/10.1016/s0927-5371(00)00014-2

ORCID affiliation usage: https://orcid.org/0000-0001-5356-6022 ; https://orcid.org/0000-0002-1914-7374 ; https://orcid.org/0000-0001-7452-2862

**Comment by arthurpsmith** [comment]
We don't ordinarily add records for separate campuses, but since this is in a different country I think it's fine to do so here. The affiliation usage seems clear. Yes, should be in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02s3xwp33 in release v1.21.
