### ISSUE TITLE
Add a new organization to ROR: Fondazione SDN per la Ricerca e l’Alta Formazione in Diagnostica Nucleare

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2465]
Summary of request: Add a new organization to ROR

Name of organization: Fondazione SDN per la Ricerca e l’Alta Formazione in Diagnostica Nucleare
Website:  https://sdn.synlab.it/fondazione/
Link to publications: 
Organization type: 
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 1763 136X
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City:  Napoli
Country: Italy
Geonames ID: 
Year established:
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Research foundation associated with https://ror.org/01e8d4510. Relationship to https://ror.org/01e8d4510 is ambiguous, as the self-description would seem to apply equally to https://ror.org/01e8d4510 as the foundation. I can likewise find no funding or affiliation references for this, so my suspicion is that this should just be treated as equivalent to https://ror.org/01e8d4510.

@icraig-afk How is this used in the Wiley context? Is there affiliation usage that is not being surfaced here?
