### ISSUE TITLE
Add a new organization to ROR: Bibliosan

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2466]
Summary of request: Add a new organization to ROR

Name of organization: Bibliosan
Website:  http://www.bibliosan.it
Link to publications:
Organization type:  Consortium
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 0447 1547
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City:  Segrate
Country: Italy
Geonames ID: 3166808
Year established: 2003
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Italian library consortia providing shared resources access. No affiliation usage I can find, but we have similar records in ROR that have the same shared access function (e.g. https://ror.org/04zp06k22 and https://ror.org/021gxf250), so I think this is OK to add.


ORCID affiliation usage: https://orcid.org/0000-0001-5402-2510 ; https://orcid.org/0000-0002-5010-6562

**Comment by arthurpsmith** [comment]
I removed the Wikidata ID from the proposal - that ID is for an article about the project, not for this consortium itself.

Also I don't think the ORCID usages are really "affiliations" - they are indicating membership of this person as a "representative" or some other function within Bibliosan. Not employed there presumably, and not using it as their affiliation for publications I would guess.

However library consortia are useful to track as organizations that represent many other research organizations so I agree this belongs in ROR, let's add it.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/020hx9j68 in release v1.21.
