### ISSUE TITLE
Add a new organization to ROR:  Instituto Nazionale Tumori Regina Elena

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2467]
Summary of request: Add a new organization to ROR

Name of organization: Instituto Nazionale Tumori Regina Elena
Website:
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 1760 5073
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations:  https://ror.org/04tfzc498 (parent)
City:  Rome
Country: Italy
Geonames ID: 3169070
Year established:
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Cancer research institute in Italy. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1097/jto.0b013e3181c06980; https://doi.org/10.1117/12.2306424; https://doi.org/10.1117/12.2623466

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04mgfev69 in release v1.21.
