### ISSUE TITLE
Add a new organization to ROR:  Istituto di Ricovero e Cura a Carattere Scientifico San Raffaele, Pisana

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2468]
Summary of request: Add a new organization to ROR

Name of organization: Istituto di Ricovero e Cura a Carattere Scientifico San Raffaele
Website:  https://www.sanraffaele.it/assistenza/strutture-sanitarie/1/irccs-san-raffaele-pisana
Link to publications: 
Organization type: Healthcare
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 1784 8390
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Aliases: IRCCS San Raffaele
Labels: 
Related organizations:  https://ror.org/04tfzc498 (parent)
City:  Rome
Country: Italy
Geonames ID: 3169070
Year established:
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Healthcare and rehabilitation facility in Italy. Funds and employs researchers. Solid affiliation usage. Should be added.'

Publication affiliation usage: https://doi.org/10.1016/j.jacc.2010.03.090; https://doi.org/10.1038/nm1582; https://doi.org/10.1182/blood-2014-03-561381

ORCID affiliation usage: https://orcid.org/0000-0002-9311-8600 ; https://orcid.org/0000-0002-2658-2243 ; https://orcid.org/0000-0002-8453-0353

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/006x48140 in release v1.21.
