### ISSUE TITLE
Add a new organization to ROR: Instituto Portugues do Sangue e da Transplantacao, IP

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2469]
Summary of request: Add a new organization to ROR

Name of organization: Instituto Portugues do Sangue e da Transplantacao, IP
Website:  https://ipst.pt
Link to publications: 
Organization type: Healthcare
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 4909 9291
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: IPST; IPST, IP
Aliases: Instituto Portugues do Sangue e da Transplantacao; Portuguese Institute of Blood and Transplantation
Related organizations: 
City:  Lisbon
Country: Portugal
Geonames ID: 2267057
Year established: 1958
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Biomedical research center in Portugal. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1177/14604582211009918; https://doi.org/10.1016/j.tracli.2022.03.005

ORCID affiliation usage: https://orcid.org/0000-0003-0355-5944

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02r8brs23 in release v1.21.
