### ISSUE TITLE
Add a new organization to ROR: Infarmed - Autoridade Nacional do Medicamento e Produtos de Saúde, I.P

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2471]
Summary of request: Add a new organization to ROR

Name of organization: Infarmed
Website:  https://www.infarmed.pt
Link to publications: 
Organization type: Government
Wikipedia page: https://pt.wikipedia.org/wiki/Infarmed
Wikidata ID: Q10302096
ISNI ID: 0000 0000 9104 7218
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:  Infarmed - Autoridade Nacional do Medicamento e Produtos de Saúde, I.P.; Infarmed - National Authority of Medicines and Health Products I.P.; Instituto Nacional da Farmácia e do Medicamento, I.P.
Labels: 
Acronym/abbreviation:
Related organizations: 
City:  Lisbon
Country: Portugal
Geonames ID: 2267057
Year established: 1983
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Stage pharmaceutical monitoring agency in Portugal. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1016/s0003-2670(02)01020-6; https://doi.org/10.1016/s0731-7085(03)00073-6; https://doi.org/10.3389/fphar.2016.00305; https://doi.org/10.3389/fphar.2017.00497; https://doi.org/10.1016/j.cyto.2010.04.008; https://doi.org/10.1089/humc.2016.193; https://doi.org/10.3389/fphar.2013.00039; https://doi.org/10.1128/jcm.00234-07; https://doi.org/10.2217/rme.14.65

ORCID affiliation usage: https://orcid.org/0000-0003-4085-875X ; https://orcid.org/0000-0002-2132-2178 ; https://orcid.org/0000-0002-6071-4211

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05pczjj75 in release v1.21.
