### ISSUE TITLE
Add a new organization to ROR: Mathias Corvinus Collegium

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2472]
Summary of request: Add a new organization to ROR

Name of organization: Mathias Corvinus Collegium
Website:  https://mcc.hu
Link to publications: 
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Mathias_Corvinus_Collegium
Wikidata ID: Q1166681
ISNI ID: 0000 0005 0489 765X
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: MCC
Related organizations: 
City:  Budapest
Country: Hungary
Geonames ID: 3054643
Year established: 1996
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
College in Hungary. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1556/2052.2022.00349; https://doi.org/10.1080/10438599.2020.1849968; https://doi.org/10.1080/21599165.2022.2126834; https://doi.org/10.19044/esj.2022.v18n39p128; https://doi.org/10.1007/978-3-658-33677-6_11; https://doi.org/10.5281/zenodo.6977088; https://doi.org/10.2478/pce-2022-0004; https://doi.org/10.1007/978-3-658-33677-6_19; https://doi.org/10.2139/ssrn.4353670; https://doi.org/10.19044/esipreprint.12.2022.p193

ORCID affiliation usage: https://orcid.org/0000-0002-6218-0639 ; https://orcid.org/0000-0002-7088-0280 ; https://orcid.org/0000-0001-8291-6415

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01vk3ab38 in release v1.21.
