### ISSUE TITLE
Add a new organization to ROR: Euroopan kemikaalivirasto

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2473]
Summary of request: Add a new organization to ROR

Name of organization: European Chemicals Agency
Website:  https://echa.europa.eu
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/European_Chemicals_Agency
Wikidata ID: Q48798
ISNI ID: 0000 0004 0433 5924
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: ECHA
Aliases: 
Labels: Euroopan kemikaalivirasto*Finnish
Related organizations: https://ror.org/019w4f821 (parent)
City:  Helsinki
Country: Finland
Geonames ID: 658225
Year established: 2007
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
EU regulatory body for chemicals legislation. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1016/j.bios.2010.07.033; https://doi.org/10.1093/toxsci/kfz201; https://doi.org/10.1021/acs.est.5b02412; https://doi.org/10.1002/jat.2949; https://doi.org/10.1021/acs.est.6b00608; https://doi.org/10.3109/10408444.2013.835786

ORCID affiliation usage: https://orcid.org/0000-0002-3493-7358 ; https://orcid.org/0000-0002-5184-1403 ; https://orcid.org/0000-0002-1453-9387

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01ayrdf49 in release v1.21.
