### ISSUE TITLE
Add a new organization to ROR: Maanmittauslaitos

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2474]
Summary of request: Add a new organization to ROR

Name of organization: Maanmittauslaitos
Website:  https://www.maanmittauslaitos.fi
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/National_Land_Survey_of_Finland
Wikidata ID: Q979330
ISNI ID: 0000 0004 0494 894X
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: MML
Aliases: National Land Survey of Finland
Labels:
Related organizations: 
City:  Helsinki
Country: Finland
Geonames ID: 658225
Year established: 1812
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Goverment surveying agency in Finland. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.3390/rs1030577; https://openalex.org/W3203698804; https://doi.org/10.2218/ijdc.v11i2.388;  https://doi.org/10.1109/ursi-emts.2016.7571366; https://doi.org/10.1515/jogs-2016-0008; https://doi.org/10.1515/jogs-2016-0001; https://doi.org/10.1371/journal.pone.0225773; https://doi.org/10.5194/epsc2021-642; https://doi.org/10.5194/epsc2021-658; https://doi.org/10.1016/j.jqsrt.2017.09.033; https:/

ORCID affiliation usage: https://orcid.org/0000-0002-4129-5381 ; https://orcid.org/0000-0003-0985-4443 ; https://orcid.org/0000-0002-6817-8628

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05tkycb73 in release v1.21.
