### ISSUE TITLE
Add a new organization to ROR: Puolustusvoimien tutkimuslaitos

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2475]
Summary of request: Add a new organization to ROR

Name of organization: Puolustusvoimien tutkimuslaitos
Website:  https://puolustusvoimat.fi/tutkimuslaitos
Link to publications:
Organization type: Government
Wikipedia page:
Wikidata ID: Q23870426
ISNI ID: 0000 0004 0647 694X
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Aliases: Finnish Defence Research Agency; Finnish Defense Research Agency
Labels: 
Related organizations: https://ror.org/04avm2781 (parent)
City:  Lakiala
Country: Finland
Geonames ID: 11978501
Year established:
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Research institute under the Finnish Defense Forces. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1109/mcom.2017.1700220; https://doi.org/10.1186/s40649-018-0060-z; https://doi.org/10.3390/ijerph17239064; https://doi.org/10.1080/00140139.2015.1136699; https://doi.org/10.1016/j.jsams.2017.11.019; https://doi.org/10.1016/j.jsams.2020.02.006; https://doi.org/10.1093/milmed/usx049; https://doi.org/10.14814/phy2.13850; https://doi.org/10.1016/j.chb.2019.03.022; https://doi.org/10.3389/fphys.2019.01600

ORCID affiliation usage: https://orcid.org/0000-0002-9000-4659 ; https://orcid.org/0000-0002-2873-5418 ; https://orcid.org/0000-0002-7261-6408

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02kpw7e71 in release v1.21.
