### ISSUE TITLE
Add a new organization to ROR: Sege Yeonguso Kimchi

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2476]
Summary of request: Add a new organization to ROR

Name of organization: World Institute of Kimchi
Website: https://www.wikim.re.kr
Link to publications: 
Organization type: Facility
Wikipedia page: https://en.wikipedia.org/wiki/World_Institute_of_Kimchi
Wikidata ID: Q12602186
ISNI ID: 0000 0004 1786 4331
GRID ID:
Crossref Funder ID: 501100003722
Other names for the organization: 
Acronym/abbreviation:
Aliases: WiKim
Labels: 세계김치연구소*Korean
Related organizations: https://ror.org/01wpjm123 (parent)
City:  Gwangju
Country: South Korea
Geonames ID: 1841811
Year established:
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Food science research institute in Korea. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1016/j.fm.2011.10.011; https://doi.org/10.4014/jmb.1501.01019; https://doi.org/10.1007/s12275-018-8032-4; https://doi.org/10.1016/j.ijfoodmicro.2012.10.015; https://doi.org/10.1016/j.ijfoodmicro.2011.11.030

ORCID affiliation usage: https://orcid.org/0000-0001-5253-7190 ; https://orcid.org/0000-0002-3167-5241 ; https://orcid.org/0000-0003-1646-4726

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01dcefd69 in release v1.21.
