### ISSUE TITLE
Add a new organization to ROR: National Security Research Institute

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2477]
Summary of request: Add a new organization to ROR

Name of organization: National Security Research Institute
Website: https://www.nst.re.kr/eng/contents.do?key=163
Link to publications: 
Organization type: Government
Wikipedia page:
Wikidata ID: Q12585599
ISNI ID: 0000 0004 5312 9385
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: NSRI
Aliases:
Labels: 국가보안기술연구소*Korean
Related organizations: https://ror.org/058rymf81 (parent)
City:  Daejeon
Country: South Korea
Geonames ID: 1835235
Year established:
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request: At this URL you can find mention of this institute, https://www.nst.re.kr/eng/contents.do?key=163, note that contact information is partial and "Recent achievements omitted for security reasons"

**Comment by adambuttrick** [comment]
National security research institute in Korea. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1007/978-3-540-24624-4_40; https://doi.org/10.1109/cloudcom.2016.0054; https://doi.org/10.1007/978-3-540-39887-5_19; https://doi.org/10.4218/etrij.04.0103.0073; https://doi.org/10.1007/3-540-45450-0_31; https://doi.org/10.3390/app5041503; https://doi.org/10.1093/ietfec/e90-a.1.303

ORCID affiliation usage: https://orcid.org/0000-0002-9235-9824

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01rg5mm74 in release v1.21.
