### ISSUE TITLE
Add a new organization to ROR: Medicinrådet

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2478]
Summary of request: Add a new organization to ROR

Name of organization: Medicinrådet
Website:  https://medicinraadet.dk
Link to publications: 
Organization type: Other
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 6003 8385
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: 
City:  Copenhagen
Country: Denmark
Geonames ID: 2618425
Year established: 2017
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
Danish pharmaceutical review body. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1002/14651858.cd003200.pub8; https://doi.org/10.1002/14651858.cd011040.pub2; https://doi.org/10.1002/14651858.cd011040; https://doi.org/10.17896/ucn.perspektiv.n6.353

ORCID affiliation usage: https://orcid.org/0000-0002-1491-3586 ; https://orcid.org/0000-0002-8895-6394 ; https://orcid.org/0000-0001-6916-2604

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03az8b907 in release v1.21.
