### ISSUE TITLE
Add a new organization to ROR: Foroya Landsbokasavn;

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2479]
Summary of request: Add a new organization to ROR

Name of organization: Landsbókasavnið
Website:  https://landsbokasavnid.fo
Link to publications: 
Organization type: Archive
Wikipedia page: https://en.wikipedia.org/wiki/National_Library_of_the_Faroe_Islands
Wikidata ID: Q144515
ISNI ID: 0000 0004 0519 3964
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Landsbókasavnið - National Library of the Faroe Islands
Labels: National Library of the Faroe Islands*English
Acronym/abbreviation:
Related organizations: 
City:  Tórshavn
Country: Faroe Islands
Geonames ID: 2611396
Year established: 2002
How will a ROR ID for this organization be used?  To be used for Wiley OA management
Other information about this request:

**Comment by adambuttrick** [comment]
State library of the Faroe Islands. No affiliation usage I can find, but all other national libraries are in scope for ROR (e.g. https://ror.org/04v1bf639 and https://ror.org/01n7gem85), so this would be as well, especially given the context of a ROR integration.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03k6sff92 in release v1.21.
