### ISSUE TITLE
Add a new organization to ROR: Instituto Dom Luiz

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2482]
Summary of request: Add a new organization to ROR

Name of organization: Instituto Dom Luiz
Website: http://idl.campus.ciencias.ulisboa.pt
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID: Q105169349
ISNI ID: 0000 0004 0475 6243
GRID ID:
Crossref Funder ID: 501100011656
Other names for the organization: 
Acronym/abbreviation:
Related organizations:  https://ror.org/01c27hj86 (parent) https://github.com/ror-community/ror-updates/issues/2470
City: Lisbon
Country: Portugal
Geonames ID: 2267057
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Geophysical research facility, first identified in https://github.com/ror-community/ror-updates/issues/2470. Funds and employs researchers. Solid affiliation usage, although looks to be exclusively leading for https://ror.org/01c27hj86, but #2470 [self-describes](https://www.arditi.pt/pt/sobre.html) as additional parent.

Publication affiliation usage: https://doi.org/10.1126/science.1201224; https://doi.org/10.1175/2011jhm1369.1; https://doi.org/10.1016/j.rse.2012.12.008; https://doi.org/10.1002/2014wr015638; https://doi.org/10.1073/pnas.1207068110; https://doi.org/10.1175/bams-d-11-00154.1

ORCID affiliation usage: https://orcid.org/0000-0003-0410-2971 ; https://orcid.org/0000-0002-9155-5874 ; https://orcid.org/0000-0002-7526-1841

**Comment by arthurpsmith** [comment]
A little ambiguous - but it has it's own Crossref funder id! And I did find one case of affiliation usage where the University was not mentioned (one of the ORCID usages). So yes, it should be in ROR.
