### ISSUE TITLE
Merge duplicate records for The Nature Conservancy

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#249]
Summary of request: Merge two or more ROR records

Description of change: 
There are two records in ROR for The Nature Conservancy. These are duplicates and should be merged so there is only one record. 

Primary record: https://ror.org/0563w1497 (US location)
Record to be merged: https://ror.org/00gcd8h55 (branch in Colombia)

Name of organization: The Nature Conservancy
ROR ID: https://ror.org/00gcd8h55
Related organizations: https://ror.org/0563w1497 (successor-np)
Update: change.status==withdrawn;$

**Comment by adambuttrick** [comment]
Updated in release v1.15.
