### ISSUE TITLE
Project: Universitat Pompeu Fabra Research Units

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2499]
Universitat Pompeu Fabra - https://ror.org/04n0g0b29 has submitted a set of research units they would like added to the registry. These should be reviewed for scope and added, where appropriate.

Institut de Política Econòmica i Governança (IPEG)
Escola Superior de Comerç Internacional (ESCI)
Escola Superior d'Infermeria del Mar (ESIM)
BIST Dolors Aleu Graduate Centre
Barcelonaβeta  Brain Research Center
UPF Barcelona School of Management
Tecnocampus

**Comment by adambuttrick** [comment]
- UPF Barcelona School of Management: 
- Curator: This appears to be a department of UPF and thus would be out of scope for ROR (affiliations should reference the parent organization, i.e. UPF). Is this correct?
- No, it isn't a department of UPF. It's a center attached to UPF. It belongs to the Fundación Instituto de Educación Continua from Universidad Pompeu Fabra (UPF). Has a separate funding sources and leadership: https://www.bsm.upf.edu/en/about-us#Aboutus
- 
- Escola Superior de Comerç Internacional (ESCI) 
- Curator: How is this organization distinct from/related to UPF? Does it have separate funding sources, leadership, etc?  UPF: It's a center attached to UPF.  Has a separate funding sources and leadership.
- https://www.esci.upf.edu/en/about-us/introduction
- 
- Escola Superior d'Infermeria del Mar (ESIM)
- Curator: How is this organization distinct from/related to UPF? Does it have separate funding sources, leadership, etc?   UPF: It's a center attached to UPF.  Has a separate funding sources and leadership.
- https://www.esimar.edu.es/en/about-the-school/qui-som/
- Curator: Tecnocampus: What is this organization's relationship to UPF? I see reference to it being managed by the Tecnocampus Mataró-Maresme Foundation, but it is also listed as a center attached to UPF . 
- UPF: Yes, It's a center attached to UPF.  Has a separate funding sources and leadership.
- https://www.tecnocampus.cat/en/sobre-el-parc-tecnocampus/sobre-el-tecnocampus
- BIST Dolors Aleu Graduate Centre: 
- Curator: This appears to be a post-graduate facility affiliated to but in someway distinct from UPF - could you provide additional details? 
- UPF: It's a center attached to UPF.  Has a separate funding sources and leadership. https://mmres.bist.eu/dolors-aleu-gc/

**Comment by mariagould** [comment]
I think these research units can all be considered within scope for ROR given their independent status and distinct funding/governance circumstances.

**Comment by adambuttrick** [comment]
Added in release v1.22.

ROR ID | Organization name
-- | --
https://ror.org/03wbt1f24 | Institut de Política Econòmica i Governança
https://ror.org/033m8p353 | Escola Superior de Comerç Internacional
https://ror.org/04jp88086 | Escola Superior d'Infermeria del Mar
https://ror.org/037tawy03 | BIST Dolors Aleu Graduate Centre
https://ror.org/023hj4e57 | Barcelonaβeta Brain Research Center
https://ror.org/04m3cqq68 | UPF Barcelona School of Management
https://ror.org/05193xx52 | TecnoCampus
