### ISSUE TITLE
Add a new organization to ROR: Joint Fire Science Program

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#25]
Summary of request: Add a new organization to ROR

Name of organization: Joint Fire Science Program
Website: https://www.firescience.gov
Link to publications: https://www.firescience.gov/JFSP_publications.cfm, https://search.crossref.org/funding?q=100015231
Organization type: Government
Wikipedia page:
Wikidata ID: Q30297389
ISNI ID: 0000 0004 8339 055X
GRID ID:
Crossref Funder ID: 100015231
Other names for the organization: 
Acronym/abbreviation: JFSP
Related organizations: https://ror.org/03zmjc935 (parent) https://ror.org/03v0pmy70 (parent)
City: Boise, Idaho
Country: United States
Geonames ID: 5586437
Year established: 1998

How will a ROR ID for this organization be used? This is a funding organization that is represented in the DMPTool, which integrates with ROR. A ROR ID for JFSP will identify research projects funded by the organization. 

Other information about this request: This ID has been requested by the DMPTool. In the course of reviewing the request we realized that this organization was previously assigned an ID in GRID (grid.454813.f) and then redirected to the record for the Department of the Interior (grid.239134.e, https://ror.org/03v0pmy70). This happened prior to ROR's existence so we never registered a ROR ID.

**Comment by mariagould** [comment]
This is a legacy request that ROR received from DMPTool in 2020. DMPTool requested the ROR ID in order to be able to connect JFSP to the research projects that it funds. We were not able to process the request at that time because the record had previously been deprecated by GRID and was not likely to be reinstated. I am re-opening the request so that we can review it for a future ROR release. I recommend adding to ROR because it is an identified funder associated with published research. It is distinct from the Department of the Interior (the record that GRID redirected it to) because it is jointly operated by both DOI and the US Forest Service.

**Comment by carlyrobinson** [comment]
I agree with the assessment. Recommend adding to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03ccbtk93 in release v1.1.
