### ISSUE TITLE
Add a new organization to ROR: 
 
Naos Marine and Molecular Laboratories

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#252]
Summary of request: Add a new organization to ROR

Name of organization: Naos Marine and Molecular Laboratories
Website: https://stri.si.edu/facility/naos
Link to publications: https://doi.org/10.1016/j.biocon.2020.108858 
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Laboratorios de isla Naos, Naos Island Laboratories, Naos Laboratories
Acronym/abbreviation: None
Related organizations: Smithsonian Institution https://ror.org/01pp8nd67 (related), Smithsonian Tropical Research Institute https://ror.org/035jbxr46 (related)
City: Naos Island, 8.91°, -79.53° 
Country: Panama
Year established: 1963
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility
Other information about this request:

**Comment by mariagould** [comment]
Part of a cluster of requests from the Smithsonian. 

Related requests: 
- #243 
- #244 
- #245  
- #246 (already processed in the latest GRID release)
- #250 
- #251

**Comment by nlundvick** [comment]
This is a Smithsonian Tropical Research Institute facility. Unlike related requests, for which I recommended not in scope, I found an instance of affiliation use for this organization (https://doi.org/10.1046/j.1471-8286.2003.00454.x). Moving this and related requests to needs discussion so that ROR Curation team can discuss how to process these requests in a consistent manner.

**Comment by nlundvick** [comment]
A couple more examples of Naos affiliation use: https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-294X.2004.02397.x; https://onlinelibrary.wiley.com/doi/full/10.1046/j.1365-294X.2003.01946.x

**Comment by nlundvick** [comment]
Per ROR curation team meeting 2021-09-07, this should be added to ROR with Smithsonian Tropical Research Institute (https://ror.org/035jbxr46) as the parent organization

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/007yfgf06 in release v1.0.
