### ISSUE TITLE
Modify the information in an existing ROR record: Eastern Shore Community College - https://ror.org/05tg3y165

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#2524]
Summary of request: Modify the information in an existing ROR record

Name of organization: Eastern Shore Community College
ROR ID: https://ror.org/05tg3y165
Which part of the record needs to be changed? Address
Description of change:  This is located in Melfa,  not Accomac. See foot of this page for full details: https://es.vccs.edu/

Update: change.Geonames==4772630;$

**Comment by adambuttrick** [comment]
Confirmed address change via organization's website.

**Comment by adambuttrick** [comment]
Record updated in release v1.21.
