### ISSUE TITLE
Add a new organization to ROR: 
 
Coral Publications, Coral Research and Education Systems

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#254]
Summary of request: Add a new organization to ROR

Name of organization: Coral Publications, Coral Research and Education Systems
Website: www.coralpublications.org
Link to publications: https://coralpublications.org/index.php/jemi/,https://coralpublications.org/index.php/jms/, https://doi.org/10.52633/jms.v3i2 
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/Q108107720
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Coral Publications. Coral Research and Education Systems
Acronym/abbreviation: CORAL
Related organizations: 
City: Karachi
Country: Pakistan
Year established: 2019
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by arthurpsmith** [comment]
The Wikidata ID is no longer valid - it was deleted for lack of supporting information. This is a very small publisher from Pakistan, with 2 journals focused on business management questions. I guess this may count as research publications but it seems out of scope relative to our main focus. Unless we really want to have a complete database of scholarly publishers I don't think this needs to be included in ROR. Willing to listen to a second opinion on this though.

**Comment by KellyStathis** [comment]
I think we need more clarity in our policies to decide this. Do publishers need to be a certain size for inclusion?Generally, I think publishers and journals are better covered by other databases (like Sherpa Romeo). That said, per our our [Guidance for Evaluating Common Organization Types](https://github.com/ror-community/ror-updates/wiki/Curator-Evaluation-Workflow:-New-Records#guidance-for-evaluating-common-organization-types), publishers are generally in scope for ROR: "Add to ROR if: **publishing/hosting research**, and/or if members publish research using this affiliation." Moving to "Needs discussion".

**Comment by arthurpsmith** [comment]
From curation meeting we decided to go ahead with this one.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03q3ecb97 in release v1.0.
