### ISSUE TITLE
Add a new organization to ROR: Hospital Universitário Regional de Maringá

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2544]
Summary of request: Add a new organization to ROR

Name of organization: Hospital Universitário Regional de Maringá
Website: https://www.hum.uem.br
Link to publications: 
Organization type: Healthcare
Wikipedia page:
Wikidata ID: Q10298499
ISNI ID: 0000 0004 0553 4730
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/04bqqa360 (parent)
City: Maringa
Country: Brazil
Geonames ID: 3457671
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University hospital, first identified in https://github.com/ror-community/ror-updates/issues/2541. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.1590/s0037-86822008000500004; https://doi.org/10.1590/s1414-81452013000100005; https://doi.org/10.1590/s1983-14472012000200010; https://doi.org/10.1590/s0104-07072007000300015; https://doi.org/10.5216/ree.v11.47109; https://doi.org/10.1590/s0104-11692001000200011; https://doi.org/10.1590/s0037-86822007000300004; https://doi.org/10.1590/s0104-07072013000300012; https://doi.org/10.1016/j.jhin.2004.06.033

ORCID affiliation usage: https://orcid.org/0000-0001-9639-1402 ; https://orcid.org/0000-0001-9774-7458 ; https://orcid.org/0000-0001-9711-2962

**Comment by mariagould** [comment]
I agree this is in scope as a university hospital and given evidence of affiliation usage.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03vadg117 in release v1.21.
