### ISSUE TITLE
Modify the information in an existing ROR record: 
HTW Berlin - University of Applied Sciences https://ror.org/01xzwj424


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#256]
Summary of request: Modify the information in an existing ROR record

Name of organization: HTW Berlin - University of Applied Sciences
ROR ID: https://ror.org/01xzwj424
Which part of the record needs to be changed? Other names or name versions listed in the record, Organization website
Description of change: Please change the link to the website. It links to an error. Use this link for the english website: https://www.htw-berlin.de/en/ or the following one for german: https://www.htw-berlin.de/ If possible, please add both links.
Also the name in the subtitle in German should be: "Hochschule für Technik und Wirtschaft Berlin". The town is part of the name.

MG Note:
Replace links: https://www.htw-berlin.de/
Replace label: Hochschule für Technik und Wirtschaft Berlin (de)

Update: replace.links==https://www.htw-berlin.de/; replace.labels==Hochschule für Technik und Wirtschaft Berlin*de;

**Comment by arthurpsmith** [comment]
Yes, the website needs to be changed - I recommend just listing the main site https://www.htw-berlin.de/ (but if we can add the English one also that's fine too).
And yes the German version of the name needs Berlin added, otherwise it has the same name as many other such institutions in Germany!

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
