### ISSUE TITLE
Modify Netherlands Cancer Institute https://ror.org/03xqtf034

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#257]
Summary of request: Split an existing ROR record into two or more records

Name of organization: 
Antoni van Leeuwenhoek Hospital NETHERLANDS CANCER INSTITUTE, NKI-AVL, ANTONI VAN LEEUWENHOEKZIEKENHUIS, Nederlands Kanker Instituut

ROR ID: https://ror.org/03xqtf034

Describe what change needs to be made to the ROR record(s). Provide a reason for the change (e.g., the organization no longer exists, or the organization has merged with another one)
We had a reviewer complain that her institution was not in the ROR list. Netherlands Cancer Institute (https://www.nki.nl/ ) is part of the ROR record for Antoni van Leeuwenhoek Hospital, but as you can see, they have distinct websites. Also note that Nederlands Kanker Instituut does not produce the record in question as a top result.

MG Note:
Change name: Netherlands Cancer Institute-Antoni van Leeuwenhoek Hospital
Add label: Nederlands Kanker Instituut (nl)

Update: change.name==Netherlands Cancer Institute-Antoni van Leeuwenhoek Hospital; add.labels==Nederlands Kanker Instituut*nl;

**Comment by mariagould** [comment]
This one is a little confusing. From the about section of the websites, it appears as though they are the same organization, even though there are two different websites:

https://www.nki.nl/about-us/organization/
https://www.avl.nl/en/about-the-organization/about-the-nki/#jaarverslagen

My proposal would be to keep it as a single record, determine which URL should be used, and update the name fields so that we have all versions represented for better discoverability and identification.

**Comment by arthurpsmith** [comment]
Reading the Dutch pages (with Google Translate) it seems clear the Netherlands Cancer Institute is a research institute while Antoni van Leeuwenhoekziekenhuis is a hospital, so they are (somewhat) distinct. They both have wikipedia pages: https://en.wikipedia.org/wiki/Antoni_van_Leeuwenhoekziekenhuis and https://en.wikipedia.org/wiki/Netherlands_Cancer_Institute - and both together make up the "NKI-AVL" which could  have yet another separate organization identifier if we were to split them. Unfortunately there doesn't seem to be a main website for the combined organization. I think it might be best to change the main label here to "Netherlands Cancer Institute-Antoni van Leeuwenhoek Hospital" representing that joint organization. It would be nice if we could link to both websites, but if not I don't think it matters which one we pick. So basically yes I agree with Maria's recommendation here.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
