### ISSUE TITLE
Add a new organization to ROR: Universitas Labuhanbatu

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2599]
Summary of request: Add a new organization to ROR

Name of organization: Universitas Labuhanbatu
Website: http://ulb.ac.id
Link to publications: 
Organization type: Education
Wikipedia page: https://id.wikipedia.org/wiki/Universitas_Labuhanbatu
Wikidata ID: Q105626563
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Labuhanbatu University
Labels:
Acronym/abbreviation: ULB
Related organizations: 
City:  Rantauprapat
Country: Indonesia
Geonames ID: 1214073
Year established: 2019
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
University in Indonesia. Funds and employs researchers. Solid affiliation usage. Should be added.

Publication affiliation usage: https://doi.org/10.46729/ijstm.v1i1.5; https://doi.org/10.33258/birci.v4i2.1940; https://doi.org/10.1088/1757-899x/1088/1/012045; https://doi.org/10.15294/jpii.v8i4.19433; https://doi.org/10.35335/mantik.vol4.2021.1171.pp2411-2415; https://doi.org/10.29103/ijevs.v1i4.1464; https://doi.org/10.33258/birci.v3i1.804

ORCID affiliation usage: https://orcid.org/0000-0002-3856-9353 ; https://orcid.org/0000-0003-3028-3622 ; https://orcid.org/0000-0001-6579-580X

**Comment by mariagould** [comment]
I agree this is in scope as an educational institution and given evidence of affiliation usage. 

NB: I added Wikipedia link above.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04apdjp43 in release v1.21.
