### ISSUE TITLE
Add a new organization to ROR: Helmholtz Open Science Office

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#26]
Summary of request: Add a new organization to ROR

Name of organization: Helmholtz Open Science Office
Website: https://os.helmholtz.de/
Link to publications: https://doi.org/10.5281/zenodo.2575346; https://doi.org/10.1177/0963662516678514; https://doi.org/10.1515/9783110494068; https://doi.org/10.5282/o-bib/2017H2S35-55; https://doi.org/10.2312/lis.17.01; https://doi.org/10.5282/o-bib/2017H1S151-169
Organization type: Other
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/0281dp749 (parent)
City: Potsdam
Country: Germany
Year established: 2005
How will a ROR ID for this organization be used? 
Other information about this request: The Helmholtz Open Science Office is an independent department of the Helmholtz Assoziation to raise awareness for open science topics in the whole Helmholtz community and to promote open scholarly communication and publishing practices for all researchers.

**Comment by mariagould** [comment]
This is a legacy request submitted by the organization in 2020. The organization decided to hold the request until ROR had the ability to link related organizations. I am reinstating the request so that we can review it for inclusion in a future release. 

This is an independent entity that is also part of the Helmholtz Association (https://ror.org/0281dp749). It is involved in publishing research and supporting researchers. As far as I can tell, publications associated with the office tend to use the main affiliation for the Helmholtz Association, and related IDs are at the association level as well. 

We should consider whether the current representation at the association level is sufficient, or whether a new record should be created to identify the open science office.

**Comment by arthurpsmith** [comment]
This is not listed as one of the 18 Hemlholtz centers - https://www.helmholtz.de/ueber-uns/helmholtz-zentren/ - rather it is mentioned under their "values" - https://www.helmholtz.de/ueber-uns/unsere-werte/open-science/ - I think at the least this office is not really considered independent of the central association as are the research centers. I did find one use of the office explicitly as an affiliation, but generally their staff seem to be happy to just list "Helmholtz Association" as the affiliation. My recommendation is not to create a new ROR id for this office, at least until/unless we are ready to add university departments etc which I would consider comparable or more justified than this.

**Comment by adambuttrick** [comment]
Agree with Arthur's assessment. Declining as out-of-scope.
