### ISSUE TITLE
Add a new organization to ROR: 
 
De Bastei (former Natuurmuseum Nijmegen)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#260]
Summary of request: Add a new organization to ROR

Name of organization: De Bastei (former Natuurmuseum Nijmegen)
Website: www.debastei.nl
Link to publications: DOI10.15468/kqlhek ; DOI10.15468/tjvemo
Organization type: Archive (An organization involved in stewarding research and cultural heritage materials. Includes libraries, museums, and zoos)
Wikipedia page: https://nl.wikipedia.org/wiki/De_Bastei
Wikidata ID: https://www.wikidata.org/wiki/Q55108539
ISNI ID: https://isni.org/isni/0000000087729208
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Former : Natuurmuseum Nijmegen
Acronym/abbreviation: Does not apply
Related organizations: none
City:  Nijmegen
Country: Netherlands
Year established: 2015
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets
Other information about this request:

**Comment by arthurpsmith** [comment]
Seems clear this should have a ROR id. "Natuurmuseum Nijmegen" was definitely used as an affiliation for research  publications, and the DOI links they provide are to significant datasets. I'm a little surprised we didn't already have this in ROR but I guess there are a lot of museums out there!

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04y2aw426 in release v1.0.
