### ISSUE TITLE
Modify the information in an existing ROR record: 
HZG https://ror.org/03qjp1d79


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#261]
Summary of request: Modify the information in an existing ROR record

Name of organization: HZG
ROR ID: https://ror.org/03qjp1d79
Which part of the record needs to be changed? Primary name, Organization website
Description of change: Article about the primary name change : https://www.presseportal.de/pm/149279/4878983
New website address : https://www.hereon.de/

MG Note:
Add acronyms: HZG
Add Wikidata: Q1290544
Add Wikipedia: https://de.wikipedia.org/wiki/Helmholtz-Zentrum_Hereon

Update: add.acronyms==HZG; add.Wikidata==Q1290544; add.wikipedia_url==https://de.wikipedia.org/wiki/Helmholtz-Zentrum_Hereon;

**Comment by arthurpsmith** [comment]
Primary name should now be: Helmholtz-Zentrum Hereon
Current primary name could be preserved as an alias.
Maybe should also add alias "Helmholtz-Zentrum hereon GmbH" (mentioned in the press release)?
The current website we have listed redirects to the new one, so https://www.hereon.de/ should indeed be the new URL.

**Comment by mariagould** [comment]
I don't think we need an alias that includes the GmbH since the first part of the name would be the same.

**Comment by mariagould** [comment]
The requested changes were incorporated in the September GRID/ROR release. However, HZG is missing as an acronym. This should be added so I am keeping the issue open (marking it as lower priority).

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
