### ISSUE TITLE
Modify the information in an existing ROR record: 
Technische Universität Ilmenau https://ror.org/01weqhp73


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#262]
Summary of request: Modify the information in an existing ROR record

Name of organization: Technische Universität Ilmenau
ROR ID: https://ror.org/01weqhp73
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website
Description of change: 
NAME: Technische Universität Ilmenau; 
ALIAS: TU Ilmenau; 
Website: https://www.tu-ilmenau.de/   
There is no translation of the name allowed.

Begründung:
https://www.tu-ilmenau.de/universitaet/quicklinks/universitaetsbibliothek/forschen-publizieren/hinweise-zum-publizieren/empfehlungen-zur-sichtbarkeit
Entsprechend der „Verzeichnung wissenschaftlicher Publikationen in fachlichen und fachübergreifenden Informationsquellen: gemeinsame Empfehlungen des Rektorats und der Universitätsbibliothek der TU Ilmenau“
https://www.tu-ilmenau.de/fileadmin/Bereiche/UB/Dokumente/Forschen_Publizieren/OpenAccess/TU-Ilmenau_Sichtbarkeit-Hinweise_Empfehlungen.pdf
 
„Die institutionelle Zugehörigkeit („Affiliation“) ist bei jeder Publikation in einheitlicher und vollständiger Form anzugeben.
Bei allen Veröffentlichungen, die ganz oder teilweise auf Forschungstätigkeit an der TU Ilmenau zurückgehen, ist die institutionelle Zugehörigkeit in folgender Form anzugeben:
„Technische Universität Ilmenau“ oder „TU Ilmenau“.
Für ergänzende Angaben zu Fachgebieten oder Instituten sind die jeweils offiziellen Bezeichnungen zu verwenden, wahlweise in deutscher oder englischer Fassung.“

Other information about this request: If the German correct name ist not allowed, please use the shortname" TU Ilmenau"

MG Note:
Change name: Technische Universität Ilmenau
Replace aliases: TU Ilmenau
Replace links: https://www.tu-ilmenau.de/ 

Update: change.name==Technische Universität Ilmenau; replace.aliases==TU Ilmenau; replace.links==https://www.tu-ilmenau.de/;

**Comment by arthurpsmith** [comment]
Their English web pages uniformly use "TU Ilmenau" as the name, so I'd be in favor of putting that as the principle name for ROR. The official German name would be ok too, with "TU Ilmenau" as an alias.
Note the request to also change the website link to the main page - we should do that also.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
