### ISSUE TITLE
Add a new organization to ROR: 
 
International Institute of Innovation and Technology

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#264]
Summary of request: Add a new organization to ROR

Name of organization: International Institute of Innovation and Technology
Website: https://i3tk.org
Link to publications: 10.47857/irjms.2020.v01i02.008
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 0000 0004 7977 6986
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation: I3T
Related organizations:
City: Kolkata
Country: India
Geonames ID: 1275004
Year established: 2018
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by arthurpsmith** [comment]
I added the ISNI id.
I'm not sure about this one. Searching Goolge scholar I found only a handful of publications from this institute, with 3 different authors, only two of whom actually used the institute as an affiliation; the others were all published in "IRJMS" (https://www.irjms.com) which is a very new journal and seems a little sketchy. The website for the institute seems to be mostly talking about the founder, with great plans for the future and some recent donations etc. but not much that I can see of current status (I don't see any lists of actual researchers anywhere?) I guess it's still a new organization. I'd be inclined to hold this one for later? Willing to defer to a second opinion on this though.

**Comment by nlundvick** [comment]
I concur with @arthurpsmith - moving to Hold for Later

**Comment by arthurpsmith** [comment]
@adambuttrick While it does seem to be rather small it looks to me like their continuing research activity level does qualify them for a ROR id; I think we should approve this one now.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/011619g15 in release v1.1.
