### ISSUE TITLE
Add a new organization to ROR: 
 
Tetiaroa Society

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#266]
Summary of request: Add a new organization to ROR

Name of organization: Tetiaroa Society
Website: https://www.tetiaroasociety.org/
Link to publications: https://www.tetiaroasociety.org/document-library
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: https://isni.org/isni/0000000502676108
GRID ID: 
Crossref Funder ID: https://doi.org/10.13039/100016851
Other names for the organization: None
Acronym/abbreviation: TS
Related organizations: Tetiaroa Society French Polynesia
City: Tetiaroa Atoll
Country: French Polynesia
Year established: 2010
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by arthurpsmith** [comment]
Added ISNI and Crossref Funder ID's.
It does not appear to be used as an affiliation, but there are many papers on Google Scholar acknowledging it for support, so as a research funder I do think it belongs in ROR.

**Comment by carlyrobinson** [comment]
Agree that it should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04p8xrf95 in release v1.0.
