### ISSUE TITLE
Add a new organization to ROR: 
 
Universitätsbibliothek Heidelberg

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#268]
Summary of request: Add a new organization to ROR

Name of organization: Universitätsbibliothek Heidelberg
Website: https://www.ub.uni-heidelberg.de/
Link to publications: Catalogue entry: https://katalog.ub.uni-heidelberg.de/titel/66605093   Publication: https://doi.org/10.11588/diglit.2667
Organization type: Archive (An organization involved in stewarding research and cultural heritage materials. Includes libraries, museums, and zoos)
Wikipedia page: https://de.wikipedia.org/wiki/Universit%C3%A4tsbibliothek_Heidelberg ; ENG: https://en.wikipedia.org/wiki/Heidelberg_University_Library
Wikidata ID: https://www.wikidata.org/wiki/Q880794
ISNI ID: https://isni.org/isni/0000000122480429
GRID ID: https://www.grid.ac/institutes-PENDING_!!!!!!!
Crossref Funder ID: 
Other names for the organization: see here: http://d-nb.info/gnd/2002498-8
Acronym/abbreviation: UB Heidelberg
Related organizations: Heidelberg University: https://ror.org/038t36y30
City: Heidelberg
Country: Germany
Year established: 1386
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility, To be integrated in a scholarly publishing system, DOI Metadata, OJS metadata if possible OMP metadata
Other information about this request: Please note the URL for GRID, ie. application is pending as it just went out today. Please find here the link to ISNI (https://isni.org/isni/0000000122480429) with further titles/publications related to Heidelberg University Library. Please let me know should any information be missing. Many thanks and best regards.

**Comment by arthurpsmith** [comment]
Note - seems clearly part of the university. If added to GRID then I guess we will also add, but it wouldn't normally qualify as needing its own ROR id.

**Comment by mariagould** [comment]
It appears that GRID did not end up creating a separate record for the university library. The ROR ID that should be used for this is the ID for the university: https://ror.org/00g30e956.
