### ISSUE TITLE
Modify the information in an existing ROR record: 
Ansgar Bibelskole https://ror.org/05y8hw592


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#269]
Summary of request: Modify the information in an existing ROR record

Name of organization: Ansgar Bibelskole
ROR ID: https://ror.org/05y8hw592
Which part of the record needs to be changed? Primary name, Organization website
Description of change: Change Ansgar Bibelskole to Ansgar University College https://ansgarhoyskole.no/

Update: change.name==Ansgar University College; add.aliases==Ansgar Bible School; add.labels==Ansgar høyskole*no; add.acronyms==AS;

**Comment by arthurpsmith** [comment]
I do not think these are the same organization, although they are clearly related:
https://ansgarhoyskole.no/om-skolen/skolens-organisering
The existing "Bibelskole" website does not redirect to the "ansgarhoyskole.no" site, it seems to be continuing under that name.
It may be they want to create a new ROR id for the "University College". Or maybe all "Ansgar" should be replaced by a top-level organization, but I'm not sure what. Here's the Google translate English version of the central portion of the "organisering" page, which I am having trouble making sense of:

"From 1 January 2006, Ansgar University College is registered as a subsidiary of Ansgar Høgskole AS under the limited liability group Ansgarskolen AS, which is also registered in the Brønnøysund registers from the same date. The limited liability group consists of the four companies Ansgar høyskole AS, Ansgar Drift og Eiendom AS, Ansgar bibelskole AS and Ansgar Sommerhotell AS. All shares in the group are owned by Misjonskirken Norge."

Is the relevant top-level organization "Ansgar Høgskole AS", "Ansgarskolen AS" or perhaps just "Misjonskirken Norge" (the sponsoring church)?

Anyway, it seems clear that "Ansgar Høgskole AS", of which "Ansgar University College" is part, is different from "Ansgar Bibelskole AS", so  the substance of this request should not proceed as requested in my view, and something different needs to be done here. Just not sure what. Maybe go back to the requester for more detail on what the relationships are and what we should list?

**Comment by mariagould** [comment]
I'm seeing Ansgar University College used as an affiliation (e.g., https://www.ingentaconnect.com/content/intellect/ijcm/2017/00000010/00000001/art00006). From what I can tell, the Bible school is a subsidiary and/or predecessor. Although the bible school website doesn't redirect to the university college site, the website footer does list https://ansgarhoyskole.no/ as the main contact. So I would recommend that we:

1. Update the primary name in the record to "Ansgar University College"
2. Add "Ansgar Bible School" as an alias
3.  Add the Norwegian name "Ansgar høyskole"
4. Add "AS" as an acronym

**Comment by carlyrobinson** [comment]
I agree with @mariagould suggestion. It would be great to confirm with someone familiar (whether the requestor or someone in ROR community.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
