### ISSUE TITLE
Add a new organization to ROR: Human Computation Institute

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#27]
Summary of request: Add a new organization to ROR

Name of organization: Human Computation Institute
Website: http://humancomputation.org
Link to publications: https://doi.org/10.1126/science.aad6499, https://doi.org/10.1007/978-3-319-07052-0_35
Organization type: Nonprofit
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: HCI
Related organizations: 
City: Ithaca, New York
Country: United States
Geonames ID: 5122432
Year established: 2018
How will a ROR ID for this organization be used? 
Other information about this request: This was encouraged by Proposal Central (Altum).

**Comment by mariagould** [comment]
This was previously approved by ROR curation but was not approved for inclusion in GRID at the time, so we were unable to create the record in ROR until now. I am reinstating this request so that we can process the request. This is an independent nonprofit that is associated with published research, supports research collaborations, and publishes a research journal.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01c1qvn60 in release v1.1.
