### ISSUE TITLE
Modify the information in an existing ROR record: 
University of Tromsø - The Arctic University of Norway https://ror.org/00wge5k78


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#271]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Tromsø - The Arctic University of Norway
ROR ID: https://ror.org/00wge5k78
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: Current primary (english) name for institution is: UiT The Arctic University of Norway.
Keep "University of Tromsø - The Arctic University of Norway" as a name version (this is an older name for the university). 
Add the following as a name version: UiT Norgga árktalaš universitehta
An overview of the current name forms for the university can be found here: https://uit.no/organisasjon/enhetsnavn

**Comment by arthurpsmith** [comment]
Yes, let's make these changes exactly as requested.
