### ISSUE TITLE
Merge records: Black Country Partnership NHS Foundation Trust (https://ror.org/04kk6v249) and Dudley and Walsall Mental Health Partnership NHS Trust (https://ror.org/0013ks972)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#272]
Summary of request: Modify the information in an existing ROR record

Name of organization: Black Country Partnership NHS Foundation Trust
ROR ID: https://ror.org/04kk6v249
Which part of the record needs to be changed? Primary name, Organization website
Description of change: From the linked Url in the above record: 
"Black Country Partnership NHS Foundation Trust merged with Dudley and Walsall Mental Health Partnership NHS Trust on 1 April 2020.

We are now known as Black Country Healthcare NHS Foundation Trust and you can visit our new website at www.blackcountryhealthcare.nhs.uk."

Related organizations: https://ror.org/02f5a3t64 (successor-np)
Update: change.status==inactive;$

**Comment by mariagould** [comment]
Records to be merged:
1. Dudley and Walsall Mental Health Partnership NHS Trust: https://ror.org/0013ks972
2. Black Country Partnership NHS Foundation Trust: https://ror.org/04kk6v249

Records 1 and 2 should be redirected to a new record for Black Country Healthcare NHS Foundation Trust. This will be done when ROR has functionality in place to merge and redirect records.

**Comment by adambuttrick** [comment]
Will process updates once #1723 has been added.

**Comment by adambuttrick** [comment]
Record updated in release v1.17.
