### ISSUE TITLE
Modify the information in an existing ROR record: 
Wirral Community NHS Trust https://ror.org/0257nzs56


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#273]
Summary of request: Modify the information in an existing ROR record

Name of organization: Wirral Community NHS Trust
ROR ID: https://ror.org/0257nzs56
Which part of the record needs to be changed? Primary name, Organization website
Description of change: The website address on this record redirects to https://www.wchc.nhs.uk, the website of Wirral Community Health and Care NHS Foundations Trust. This follows a major NHS reorganisation in 2020.

MG Note:
Change name: Wirral Community Health and Care NHS Foundations Trust
Add aliases: Wirral Community NHS Trust
Replace links: https://www.wchc.nhs.uk

Update: change.name==Wirral Community Health and Care NHS Foundations Trust; add.aliases==Wirral Community NHS Trust; replace.links== https://www.wchc.nhs.uk;

**Comment by arthurpsmith** [comment]
Yes, new primary name should be "Wirral Community Health and Care NHS Foundations Trust" - current name can be made an alias for historical purposes.
And website should be changed to https://www.wchc.nhs.uk as requested.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
