### ISSUE TITLE
Modify the information in an existing ROR record: 
National Aeronautics and Space Administration (NASA) https://ror.org/027ka1x80


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#275]
Summary of request: Modify the information in an existing ROR record

Name of organization: National Aeronautics and Space Administration (NASA)
ROR ID: https://ror.org/027ka1x80
Which part of the record needs to be changed? Other IDs for the organization
Description of change: The ISNI number (ISNI 0000000114567559) dereferences to a Danish Rock Group called "N.A.S.A), NOT the National Aeronautics and Space Administration of the United States government. As far as I can determine, the US NASA does not have an ISNI number.

Other information about this request: I discovered this while looking up organizational PIDs to be recorded in metadata for (US) NASA funded data sets. I've worked on a NASA grant for nearly 30 years. In my personal experience, NASA may rock - but it is not Danish.

MG Note:
Replace ISNI: 0000 0004 4907 1619

Update: replace.ISNI==0000 0004 4907 1619;

**Comment by mariagould** [comment]
I believe the ISNI is https://isni.org/isni/0000000449071619. It was difficult to get it via ISNI search. I finally retrieved it with the query "national aeronautics"

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
