### ISSUE TITLE
Add a new organization to ROR: 
 
CatalystNeuro

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#277]
Summary of request: Add a new organization to ROR

Name of organization: CatalystNeuro
Website: https://www.catalystneuro.com/
Link to publications: https://doi.org/10.1101/2021.03.13.435173, https://dandiarchive.org/dandiset/000055/draft
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: not applicable
Acronym/abbreviation: not applicable
Related organizations: 
City: Benicia, CA
Country: United States
Year established: 2017
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets
Other information about this request:

**Comment by arthurpsmith** [comment]
While they list a number of people as staff at the company, the only person I've found using this affiliation is the founder, Ben Dichter, and then only on a handful of papers/preprints/datasets (via google scholar at least). I think this should probably wait for a ROR id until they have a more substantive need for it.

**Comment by carlyrobinson** [comment]
CatalystNeuro is being used as an affiliation and I've found a couple others listed on their team as having the organization listed in their LinkedIn (links below). I'm guessing this is a dual role for most of the team. I'd recommend adding. 

https://www.linkedin.com/in/cesar-echavarria/
https://www.linkedin.com/in/alessio-buccino-770abbb6/?originalSubdomain=ch

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01d74sk53 in release v1.0.
