### ISSUE TITLE
Add a new organization to ROR: 
 
Fundación Trópico Alto

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#278]
Summary of request: Add a new organization to ROR

Name of organization: Fundación Trópico Alto
Website: http://www.tropicoalto.ong/
Link to publications: 10.15472/o6xlel, 10.13140/RG.2.2.32120.19206, 10.13140/RG.2.2.10519.52643, http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=256354
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: High Tropics Foundation
Acronym/abbreviation: FTA
Related organizations: Corporación Geoambiental TERRAE
City: Bogota
Country: Colombia
Year established: 2018
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility
Other information about this request: FTA hosts the J.J. Triana Herbarium (HJJT) and the Maria Sibylla Merian Entomological Collection (CEMS), both of them registered under the colombian Unique National Registry of Biological Collections (http://rnc.humboldt.org.co/admin/index.php/registros/detail/1359, http://rnc.humboldt.org.co/admin/index.php/registros/detail/1360). We are currently working on botanical, entomological and conservation issues in northern South America.

**Comment by nlundvick** [comment]
In scope, recommending adding to ROR

**Comment by carlyrobinson** [comment]
Producing data and multiple people involved. Agreed, should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03s4kfm57 in release v1.0.
