### ISSUE TITLE
Add a new organization to ROR: 
 
Pandawa Institute

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#280]
Summary of request: Add a new organization to ROR

Name of organization: Pandawa Institute
Website: https://pandawainstitute.com
Link to publications: https://doi.org/10.47352/jmans
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation:
Related organizations: 
City: Metro
Country: Indonesia
Geonames ID: 1635283
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for research publications, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by nlundvick** [comment]
Relatively new (2020) scholarly publisher. Publishes two journals, one of which has no published volumes and the other only has two issues from 2021 and 2022. No publications listed under books or conferences. Recommend placing request on hold and revisiting at a later time

**Comment by carlyrobinson** [comment]
Agree that it would be good to revisit after they've had a bit more time to become established.

**Comment by adambuttrick** [comment]
Situation is unchanged. Need to make a determination.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02eb9xn27 in release v1.3.
