### ISSUE TITLE
Modify the information in an existing ROR record: 
Keldysh Institute of Applied Mathematics https://ror.org/01dv3hq14


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#281]
Summary of request: Modify the information in an existing ROR record

Name of organization: Keldysh Institute of Applied Mathematics
ROR ID: https://ror.org/01dv3hq14
Which part of the record needs to be changed? Other names or name versions listed in the record
Description of change: Please replace the all part of the record "Other names or name versions listed in the record" with the following data in accordance with the Statute of the Institute,  pages 6-7, https://keldysh.ru/doc/ustav.pdf .
Keldysh Institute of Applied Mathematics of Russian Academy of Sciences, KIAM RAS, Федеральное государственное учреждение "Федеральный исследовательский центр Институт прикладной математики им. М.В. Келдыша Российской академии наук", ИПМ им. М.В. Келдыша РАН

MG Note:
Replace label: Федеральное государственное учреждение "Федеральный исследовательский центр Институт прикладной математики им. М.В. Келдыша Российской академии наук" (ru)
Add aliases: ИПМ им. М.В. Келдыша РАН

Update: replace.labels==Федеральное государственное учреждение "Федеральный исследовательский центр Институт прикладной математики им. М.В. Келдыша Российской академии наук"*ru; add.aliases==ИПМ им. М.В. Келдыша РАН;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
