### ISSUE TITLE
Add a new organization to ROR: 
 
Municipal Higher Education Institution "Kherson Academy of Continuing Education" of the Kherson Regional Council

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#283]
Summary of request: Add a new organization to ROR

Name of organization: Municipal Higher Education Institution "Kherson Academy of Continuing Education" of the Kherson Regional Council
Website: http://academy.ks.ua/
Link to publications: https://doi.org/10.37915/pa.vi48
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Комунальний вищий навчальний заклад "Херсонська академія неперервної освіти" Херсонської обласної ради
Acronym/abbreviation: MHEI "Kherson academy of continuing education"
Related organizations: 
City: Kherson
Country: Ukraine
Year established: 1944
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by mariagould** [comment]
I added the established date to the metadata list above.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01zqrkn57 in release v1.0.
