### ISSUE TITLE
Modify the information in an existing ROR record: EDF https://ror.org/04pq5sx96

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#2832]
Summary of request: Modify the information in an existing ROR record

Name of organization: EDF
ROR ID: https://ror.org/04pq5sx96
Which part of the record needs to be changed? Name, labels
Description of change: (1) Remove label "Electricité de France". This name references a completely different organization. (2) Change name to "EDF Renewables" 

Update: change.name==EDF Energy North America; add.aliases==EDF Energy NA; replace.links==https://edfenergyna.com;$

Related organizations: https://ror.org/03wb8xz10 (parent)

**Comment by mariagould** [comment]
Encountered this while researching the ROR record for Electricité de France as part of Funder Registry reconciliation. The metadata in the present record should be updated to reflect the current state of the organization's name and to avoid confusion with the Electricité de France record (https://ror.org/03wb8xz10).

**Comment by adambuttrick** [comment]
GRID conflated two records here by using the incorrect link: EDF Energy NA and EDF Renewables. Updating this to reflect EDF Energy NA and will create a new record for EDF Renewables.

**Comment by adambuttrick** [comment]
Record updated in release v1.23.
