### ISSUE TITLE
Modify the information in an existing ROR record: Russian Foundation for Basic Research https://ror.org/02mh1ke95

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#2836]
Summary of request: Modify the information in an existing ROR record

Name of organization: Russian Foundation for Basic Research
ROR ID: https://ror.org/02mh1ke95
Which part of the record needs to be changed? Label, External IDs
Description of change: (1) Add Russian name Российский фонд фундаментальных исследований (2) Add Funder ID [100012555](http://dx.doi.org/10.13039/100012555)

Update: add.labels==Российский фонд фундаментальных исследований*Russian; add.FundRef==100012555;$

**Comment by mariagould** [comment]
Identified as part of ongoing Funder Registry reconciliation work

**Comment by adambuttrick** [comment]
Record updated in release v1.23.
