### ISSUE TITLE
Add a new organization to ROR: 
 
Udako Euskal Unibertsitatea (UEU)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#284]
Summary of request: Add a new organization to ROR

Name of organization: Udako Euskal Unibertsitatea (UEU)
Website: http://www.ueu.eus/
Link to publications: https://dx.doi.org/10.26876
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://eu.wikipedia.org/wiki/Udako_Euskal_Unibertsitatea
Wikidata ID: https://www.wikidata.org/wiki/Q12268488
ISNI ID: https://isni.org/isni/0000000119564955
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Universidad Vasca de Verano (ES); Université basque d'été (FR); Basque Summer University (EN)
Acronym/abbreviation: UEU
Related organizations: 
City: Bilbao
Country: Spain
Year established: 1973
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by arthurpsmith** [comment]
I added the ISNI id to the request. Otherwise this is clearly a university conducting research (Google Scholar lists many articles, and they are themselves a significant publisher in the Basque language) that should have a ROR id.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/005k57c98 in release v1.0.
