### ISSUE TITLE
Cleanup: Duplicated GRID IDs in Restored Records

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#2845]
When the deleted GRID records were restored in 2022, a handful of GRID IDs were duplicated in withdrawn and inactive records because of inconsistencies in the historic GRID data files. These values should be removed, such that they're only referenced in the active records. IDs with duplicated values:

ROR ID | Duplicate GRID ID
-- | --
https://ror.org/04jv0aa72 | grid.425688.5
https://ror.org/057sq8156 | grid.425210.0
https://ror.org/00ks26d70 | grid.413626.4
https://ror.org/023zp7889 | grid.443308.8
https://ror.org/044hkny52 | grid.426089.1
https://ror.org/045kz4b81 | grid.459613.c
https://ror.org/02qvmee20 | grid.466671.4
https://ror.org/03drevg53 | grid.483305.9
https://ror.org/04qfm3385 | grid.449846.3
https://ror.org/02q34ka72 | grid.419367.e
https://ror.org/021pnpq62 | grid.435928.1
https://ror.org/00se3yr70 | grid.503724.7
https://ror.org/055503602 | grid.488233.6

**Comment by amandafrench** [comment]
I just want to make sure I understand this! For example, there are currently two ROR records with GRID ID 'grid.413626.4': https://ror.org/01h8zk368 (Hamilton Psychiatric Hospital, active) and https://ror.org/00ks26d70 (Hamilton Psychiatric Hospital, withdrawn). The withdrawn record is succeeded by https://ror.org/02cwjh447, the Juravinski Cancer Centre. Why isn't the active record also succeeded by https://ror.org/02cwjh447, the Juravinski Cancer Centre?

**Comment by amandafrench** [comment]
Got it, thanks for explaining

**Comment by adambuttrick** [comment]
Updated in release v1.23.
