### ISSUE TITLE
Add a new organization to ROR: 
 
The Latino Medical Student Association

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#285]
Summary of request: Add a new organization to ROR

Name of organization: Latino Medical Student Association
Website: https://national.lmsa.net
Link to publications: Residency Match in the Virtual World
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID:
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Aliases: National Network of Latin American Medical Students
Acronym/abbreviation: LMSA
Labels:
Related organizations:
City: Chicago, IL
Country: USA
Geonames ID: 4887398
Year established: 1998
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request: At least two manuscripts with survey data of LMSA members are currently in preparation. Research articles will focus on needs, challenges, and assets of underrepresented minority (URM) trainees in medicine in the United States, as well as the impact of the organization on URM trainee advancement.

**Comment by nlundvick** [comment]
I agree with Arthur. However, ROR has a similar organization with an ID, the American Medical Student Association https://ror.org/03x6bc282. Moving to needs discussion

**Comment by arthurpsmith** [comment]
Per curation meeting, moving to Hold for Later

**Comment by adambuttrick** [comment]
Situation is largely unchanged, although I see their survey data being referenced in recent publication, e.g.: https://link.springer.com/article/10.1007/s11606-021-06786-6

Need to make a determination about whether this is in scope.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04dqm5e84 in release v1.3.
