### ISSUE TITLE
Add a new organization to ROR: 
 
Gen-info Ltd 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#286]
Summary of request: Add a new organization to ROR

Name of organization: Gen-info Ltd 
Website: www.gen-info.hr
Link to publications: 10.1038/s41586-021-03779-7
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Gen-info d.o.o.
Acronym/abbreviation: GNFO
Related organizations: 
City: Zagreb
Country: Croatia
Year established: 2008
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by carlyrobinson** [comment]
Agree this is within scope. I did find a link to their old website - http://www.gen-info.hr/english.html - that provides a bit of information about the company.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/057gst528 in release v1.0.
