### ISSUE TITLE
Modify the information in an existing ROR record: 
Cooley (United States) https://ror.org/05w8njj13


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#287]
Summary of request: Modify the information in an existing ROR record

Name of organization: Cooley (United States)
ROR ID: https://ror.org/05w8njj13
Which part of the record needs to be changed? Other IDs for the organization
Description of change: You have the wikidata id presented as a Crossref Funder ID

MG Note:
Change FundRef ID to Wikidata

Update: add.Wikidata==Q5167436; delete.FundRef==Q5167436;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
