### ISSUE TITLE
Modify the information in an existing ROR record: Hamilton Psychiatric Hospital https://ror.org/01h8zk368 

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#2876]
Summary of request: Modify the information in an existing ROR record

Name of organization: Hamilton Psychiatric Hospital
ROR ID: https://ror.org/01h8zk368 
Which part of the record needs to be changed? Status
Description of change: The Hamilton Psychiatric Hospital in Ontario, Canada apparently no longer exists by that name and should be marked inactive. At least one source suggests that it has been folded into St. Joseph's Healthcare Services https://ror.org/009z39p97 

* https://www.hospitalsdata.com/usa/hamilton-psychiatric-hospital-hamilton.html 

Update: change.status==inactive;$
Related organizations: https://ror.org/009z39p97 (successor-np)

**Comment by adambuttrick** [comment]
Following on https://github.com/ror-community/ror-updates/issues/2845

**Comment by adambuttrick** [comment]
Record updated in release v1.24.
