### ISSUE TITLE
Modify the information in an existing ROR record: Atypon https://ror.org/03z1mhq06

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#2885]
Summary of request: Modify the information in an existing ROR record

Name of organization: Atypon
ROR ID: https://ror.org/03z1mhq06 
Which part of the record needs to be changed? Relationships type parent
Description of change: Atypon was acquired by John Wiley and Sons https://ror.org/02xe89706 in 2016. https://ror.org/02xe89706 should be added as relationship type=parent. 

Sources: 
- https://www.atypon.com/about-us/atypon-ownership/ 

- https://www.businesswire.com/news/home/20160818005927/en/Wiley-Signs-Definitive-Agreement-to-Acquire-Atypon 

Related organizations: https://ror.org/02xe89706 (parent)

**Comment by adambuttrick** [comment]
Updated in release v1.24
