### ISSUE TITLE
Modify the information in an existing ROR record: 
Swiss Federal University for Vocational Education and Training https://ror.org/00zg4za48


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#289]
Summary of request: Modify the information in an existing ROR record

Name of organization: Swiss Federal University for Vocational Education and Training
ROR ID: https://ror.org/00zg4za48
Which part of the record needs to be changed? Primary name, Organization website, Organization type
Description of change: In your database is a link to our institution which is not correct anymore. We changed our legal status and name by August 1st 2021 to:

Eidgenössische Hochschule für Berufsbildung EHB.
Haute école fédérale en formation professionnelle HEFP.
Scuola universitaria federale per la formazione professionale SUFFP.
Swiss Federal University for Vocational Education and Training SFUVET

Could you please change that on your websites 
The refence to our webpage: Swiss Federal University for Vocational Education and Training https://www.sfuvet.swiss/ (available in four languages)

Update: change.name==Swiss Federal University for Vocational Education and Training SFUVET; delete.labels==Scuola Universitaria Federale per la Formazione Professionale; delete.labels==Eidgenössische Hochschule für Berufsbildung; delete.labels==Haute École Fédérale en Formation Professionnelle; add.labels==Eidgenössische Hochschule für Berufsbildung EHB*German; add.labels==Haute école fédérale en formation professionnelle HEFP*French; add.labels==Scuola universitaria federale per la formazione professionale SUFFP*Italian;

**Comment by nlundvick** [comment]
ROR website needs to be updated to https://www.sfuvet.swiss/. I believe the existing ROR primary name, French/German/Italian aliases, and initialisms are correct, but moving to second review for verification

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
