### ISSUE TITLE
Modify the information in an existing ROR record: 
Universidad de Cantabria  https://ror.org/046ffzj20


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#290]
Summary of request: Modify the information in an existing ROR record

Name of organization: Universidad de Cantabria
ROR ID:  https://ror.org/046ffzj20
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: - Primary must be in Spanish: Universidad de Cantabria. 
- Scondary name must be in English: University of Cantabria. 
- No other languages or acronyms should be used as name versions.

Other information about this request: Nothing else, thanks a lot, kind regards.

MG Note:
Remove acronyms: UC
Remove labels: Universitat de Cantàbria; Kantabriako Unibertsitatea

Update: delete.acronyms==UC; delete.labels==Universitat de Cantàbria; delete.labels==Kantabriako Unibertsitatea;

**Comment by arthurpsmith** [comment]
In the ROR API, 'KANTABRIAKO UNIBERTSITATEA' is listed as a Basque (eu) version of the name, and 'UNIVERSITAT DE CANTÀBRIA' as a Catalan (ca) version. I'm assuming from this message that these are unofficial or unapproved versions of the name. I don't think they add much to discoverability, though they are used on Basque and Catalan websites referring to the university. Anyway, I think it's fine to remove them here. We do have a policy of using the English name (if there is an official one) as the main label in ROR so I think we should leave that. And "UC" is probably not much use as an acronym so fine to remove that also.

So - just remove all the aliases and other-language labels except for Spanish, and leave the rest alone. Make sense?

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
