### ISSUE TITLE
Add a new organization to ROR: 
 
Bannari Amman Institute of Technology

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#292]
Summary of request: Add a new organization to ROR

Name of organization: Bannari Amman Institute of Technology
Website: www.bitsathy.ac.in
Link to publications: 10.1520/JTE20210113
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://en.wikipedia.org/wiki/Bannari_Amman_Institute_of_Technology
Wikidata ID: https://www.wikidata.org/wiki/Q4835740
ISNI ID: https://isni.org/isni/0000000417651192
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Bannariamman Institute of Technology
Acronym/abbreviation: BIT SATHY
Related organizations: 
City: Sathyamangalam
Country: India
Year established: 1996
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge a research facility
Other information about this request:

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01qkd1z70 in release v1.0.
