### ISSUE TITLE
Add a new organization to ROR: 
 
Associação Brasileira de Psiquiatria

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#293]
Summary of request: Add a new organization to ROR

Name of organization: Associação Brasileira de Psiquiatria
Website: https://www.abp.org.br/
Link to publications: https://revistardp.org.br/
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: https://pt.wikipedia.org/wiki/Associa%C3%A7%C3%A3o_Brasileira_de_Psiquiatria
Wikidata ID: https://www.wikidata.org/wiki/Q9633893
ISNI ID: https://isni.org/isni/0000000485145187
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Brazilian Association of Psychiatry
Acronym/abbreviation: ABP
Related organizations: https://ror.org/03w7hce19 (related)
City: Rio de Janeiro, RJ
Country: Brasil
Year established: 1966
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request: Validar filiações de autores científicos que publicam em revistas científicas e outros documentos

**Comment by carlyrobinson** [comment]
Agreed, should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02jn8gs50 in release v1.0.
