### ISSUE TITLE
Modify the information in an existing ROR record:  Instytut Historii Nauki im. Ludwika i Aleksandra Birkenmajerów Polskiej Akademii Nauk - https://ror.org/00nx96f80

### ISSUE THREAD

**Issue by mikoko1** [ror-community/ror-updates#2931]
Summary of request: Modify the information in an existing ROR record

Name of organization: 
ROR ID: https://ror.org/00nx96f80
Which part of the record needs to be changed?
Description of change:

1.
If a comma "," is a logical sign separating separate names in ROR, then two names:
“Ludwik and Aleksander Birkenmajer Institute for the History of Science, Polish Academy of Sciences”,
“L & A. Birkenmajer Institute for the History of Science, Polish Academy of Sciences”
may cause that the achievements of other institutes of the Polish Academy of Sciences may be confused with the achievements of the institute with ID: [00nx96f80](https://ror.org/00nx96f80)

2.
There are two options to avoid this problem:

a) a simple solution: deletion of the term "Polish Academy of Sciences" in two names:

Ludwik and Aleksander Birkenmajer Institute for the History of Science, Polish Academy of Sciences,  L. & A. Birkenmajer Institute for the History of Science, Polish Academy of Sciences, …

b) a more radical solution: introducing an additional character ";" to separate separate all name fields:
Ludwik and Aleksander Birkenmajer Institute for the History of Science, Polish Academy of Sciences; L. & A. Birkenmajer Institute for the History of Science, Polish Academy of Sciences; …

3.
on the list of "Other Names" please delate the first name:

Instytut Historii Nauki, ...

4.
The first name on the list of "Other Names" should be:

Instytut Historii Nauki PAN, ...

(In other words, please move this name from the fifth - sixth position to the first).

Kind regards
prof. Michal Kokowski, Ph, DSc
Instytut Historii Nauki PAN [00nx96f80](https://ror.org/00nx96f80)

Update: delete.aliases==Instytut Historii Nauki;$

**Comment by mikoko1** [comment]
Name of organization: Instytut Historii Nauki im. Ludwika i Aleksandra Birkenmajerów Polskiej Akademii Nauk
ROR ID: [00nx96f80](https://ror.org/00nx96f80)
Which part of the record needs to be changed? "Other Names"

**Description of change:**

**1.**
If a comma "," is a logical sign separating separate names in ROR, then two names:
“Ludwik and Aleksander Birkenmajer Institute for the History of Science, Polish Academy of Sciences”,
“L & A. Birkenmajer Institute for the History of Science, Polish Academy of Sciences”
may cause that the achievements of other institutes of the Polish Academy of Sciences may be confused with the achievements of the institute with ID: [00nx96f80](https://ror.org/00nx96f80)

**2.**
There are two options to avoid this problem:

a) a simple solution: deletion of the term "Polish Academy of Sciences" in two names:

Ludwik and Aleksander Birkenmajer Institute for the History of Science, Polish Academy of Sciences, L. & A. Birkenmajer Institute for the History of Science, Polish Academy of Sciences, …

b) a more radical solution: introducing an additional character ";" to separate separate all name fields:
Ludwik and Aleksander Birkenmajer Institute for the History of Science, Polish Academy of Sciences; L. & A. Birkenmajer Institute for the History of Science, Polish Academy of Sciences; …

**3.**
On the list of "Other Names" please delate the first name:

Instytut Historii Nauki, ...

**4.**
The first name on the list of "Other Names" should be:

Instytut Historii Nauki PAN, ...

(In other words, please move this name from the fifth - sixth position to the first).

Kind regards
prof. Michal Kokowski, Ph, DSc
Instytut Historii Nauki PAN [00nx96f80](https://ror.org/00nx96f80)

**Comment by adambuttrick** [comment]
Hi @mikoko1  - points number 1 and 2 seem to conflict with what was previously requested in https://github.com/ror-community/ror-updates/issues/2799. There is not much risk of falsely matching to broader Polish Academy of Sciences outputs, as the affiliation matching logic would find these name forms too incongruent.  3 we can process without issue. For 4, variant names in ROR are an unordered list, so the display on the ROR site should not be taken as in anyway weighted or canonical.

**Comment by mikoko1** [comment]
Dear @adambuttrick,

Thank you for the clarification and that "3 we can process without issue". 

Kind regards,
Michal

**Comment by adambuttrick** [comment]
Record updated in release v1.24.
