### ISSUE TITLE
Add a new organization to ROR: 
 
Bundesinstitut für Bau-, Stadt- und Raumforschung

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#294]
Summary of request: Add a new organization to ROR

Name of organization: Bundesinstitut für Bau-, Stadt- und Raumforschung
Website: https://www.bbsr.bund.de/
Link to publications: https://doi.org/10.11129/9783955534936-011 ("Final report of the research project funded by BBSR as part of the research initiative Zukunft Bau")
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://doesnotexist.butIhavetofillthisfield
Wikidata ID: https://doesnotexist.butIhavetofillthisfield
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Federal Institute for Research on Building, Urban Affairs and Spatial Development
Acronym/abbreviation: BBSR
Related organizations: https://ror.org/04hqtn844 (parent)
City: Bonn
Country: Germany
Year established: 2009
How will a ROR ID for this organization be used? To acknowledge research funders
Other information about this request:

**Comment by MSpenger** [comment]
"Bundesinstitut für Bau-, Stadt- und Raumforschung" is part of "Bundesamt für Bauwesen und Raumordnung" (https://ror.org/04hqtn844 would be parent organisation).
As an federal agency, the "Bundesinstitut für Bau-, Stadt- und Raumforschung" is responsible for research output and has listed more than 1.400 publications on its website. 
This is a subdomain, but most other criteria for new organizations apply.
This link could be added as Wikipedia page: https://de.wikipedia.org/wiki/Bundesamt_f%C3%BCr_Bauwesen_und_Raumordnung#Bundesinstitut_f%C3%BCr_Bau-,_Stadt-_und_Raumforschung

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01zy7yh11 in release v1.0.
