### ISSUE TITLE
Add a new organization to ROR: 
 
Kansas City National Security Campus

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#296]
Summary of request: Add a new organization to ROR

Name of organization: Kansas City National Security Campus
Website: https://kcnsc.doe.gov/
Link to publications: https://doi.org/10.1038/s41467-019-12432-x
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: https://en.wikipedia.org/wiki/Kansas_City_Plant
Wikidata ID: https://www.wikidata.org/wiki/Q6364819
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Kansas City Plant
Acronym/abbreviation: KCNSC
Related organizations: https://ror.org/01bj3aw27 (parent), https://ror.org/03sk1we31 (related), https://ror.org/02t71h845 (related)
City: Kansas City, MO
Country: United States
Year established: 1949
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by nlundvick** [comment]
In scope, recommend adding to ROR

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03e7mhc87 in release v1.0.
