### ISSUE TITLE
Add a new organization to ROR: 
 
ProRelix Education

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#297]
Summary of request: Add a new organization to ROR

Name of organization: ProRelix Education
Website: https://www.prorelix.com/
Link to publications: https://www.prorelix.com/certificates-awards/
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: ProRelix Services LLP
Acronym/abbreviation: ProRelix Education
Related organizations: 
City: Pune
Country: India
Year established: 2014
How will a ROR ID for this organization be used? To identify affiliations for datasets, To acknowledge a research facility
Other information about this request:

**Comment by nlundvick** [comment]
This is a private (for-profit?) training/educational institute. Link to publications does not include a list of publications. Rather, it includes one award and one certificate that were awarded to the institution. No publications found when searching Google Scholar and Web of Science. I concur with @arthurpsmith - this institution does not appear to be involved in research and therefore does not match criteria [2] for inclusion in ROR (https://github.com/ror-community/ror-updates).
