### ISSUE TITLE
Add a new organization to ROR: 
 
Institute for Research in Biomedicine (IRB)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#299]
Summary of request: Add a new organization to ROR

Name of organization: Institute for Research in Biomedicine (IRB)
Website: https://www.irb.usi.ch/
Link to publications: 10.1021/acs.jmedchem.1c00852
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: https://isni.org/isni/0000000405092792
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Istituto di Ricerca in Biomedicina
Acronym/abbreviation: IRB
Related organizations: Parent: https://ror.org/03c4atk17
City: Bellinzona
Country: Switzerland
Year established: 2000
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by nlundvick** [comment]
Scholarly research is conducted at the institute and published using the institute as an affiliation (jointly with the  the Università della Svizzera italiana (USI), as noted by first curator). Copyright to the website is owned by institute, not USI. The institute has multiple research groups and facilities, and the "People" page seems to indicates that it is somewhat autonomous from USI, having it's own support and administrative staff. Add to ROR with USI as parent organization.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05gfswd81 in release v1.0.
