### ISSUE TITLE
Modify the information in an existing ROR record: 
Botanischer Garten und Botanisches Museum Berlin https://ror.org/00bv4cx53


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#300]
Summary of request: Modify the information in an existing ROR record

Name of organization: Botanischer Garten und Botanisches Museum Berlin
ROR ID: https://ror.org/00bv4cx53
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: We need the official english institution name as the primary name and would like the german version as "other" name.
The primary name would be: Botanic Garden and Botanical Museum Berlin
Other name: Botanischer Garten und Botanisches Museum Berlin

Update: change.name==Botanic Garden and Botanical Museum Berlin; add.labels==Botanischer Garten und Botanisches Museum Berlin*German;

**Comment by MSpenger** [comment]
Looks good. English name also appears in this form in Imprint of website. German name for the institution could be added as first alias

**Comment by nlundvick** [comment]
Concur, update Primary Name to "Botanical Garden and Botanical Museum Berlin" and use "Botanischer Garten und Botanisches Museum Berlin" and "BGBM" as aliases.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
