### ISSUE TITLE
Modify the information in an existing ROR record: Escuela Superior de Administración y Dirección de Empresas https://ror.org/02d9gec76

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#3006]
Summary of request: Modify the information in an existing ROR record

Name of organization: Escuela Superior de Administración y Dirección de Empresas
ROR ID: https://ror.org/02d9gec76
Which part of the record needs to be changed? Status
Description of change: As part of #2679, Science Media Center Germany has asked that we requested that we reactive this as a child of https://ror.org/04p9k2z50.

Update: change.name==Esade; add.aliases==Esade Ramon Llull University; add.aliases==Escuela Superior de Administración y Dirección de Empresas; replace.links==https://www.esade.edu; change.status==active;$

**Comment by adambuttrick** [comment]
Was formerly independent and than integrated into  https://ror.org/04p9k2z50 in 1995, per the organization's history page. I'm likewise seeing affiliation usage that does not reference the https://ror.org/04p9k2z50 and it appears to have its own research institutes (e.g. https://doi.org/10.1007/s13132-012-0084-9 https://doi.org/10.1007/s10551-008-9812-2). Likewise, has an ISNI. One of those edge-cases where you could go either way, so would appreciate a Second Review.

**Comment by ssmulyan** [comment]
https://ror.org/04y3yya25 seems to have the same relationship to https://ror.org/04p9k2z50 that Esade does

https://ror.org/05fc8gj45 is also possibly related, just through their social work department

**Comment by ssmulyan** [comment]
I can see how it could go either way, but my sense is that https://ror.org/02d9gec76 should be reactivated.  

Esade has distinct campuses and distinct branding, indicating something like a parent-child relationship with Ramon Llull University. 

Some of the affiliation usage is specifically "ESADE business school" 

10.1080/10967494.2018.1495672
10.5465/ambpp.2022.14989abstract
10.4018/jbe.321556
10.22215/timreview/603
10.1080/03069400.2016.1272041
10.5465/ambpp.2020.157

**Comment by adambuttrick** [comment]
Record updated in release v1.25.
