### ISSUE TITLE
Modify the information in an existing ROR record: 
Instituto Tecnológico Vale https://ror.org/05wnasr61


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#301]
Summary of request: Modify the information in an existing ROR record

Name of organization: Instituto Tecnológico Vale
ROR ID: https://ror.org/05wnasr61
Which part of the record needs to be changed? Something else
Description of change: Location is wrong - this is in Belem, Brazil. It is currently shown as "Belen, United States". The geographic coordinates are also wrong.

MG Note:
Change location to Belém, Brazil (Geonames ID 3405870)
Replace links: https://www.itv.org/

Update: replace.Geonames==3405870; replace.links==https://www.itv.org/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
