### ISSUE TITLE
Modify the information in an existing ROR record: 
Grenoble School of Management https://ror.org/01h4fxd96


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#302]
Summary of request: Modify the information in an existing ROR record

Name of organization: Grenoble School of Management
ROR ID: https://ror.org/01h4fxd96
Which part of the record needs to be changed? Primary name
Description of change: We need to change the primary name with "Grenoble Ecole de Management" it is the official name of the school. please see the institutionnal website https://en.grenoble-em.com. We ask to all our researchers to use the exact affiliation Grenoble Ecole de Management

Other information about this request: For some rankings we have to be very rigorous to write the affiliation, to ensure the attribution of the publications to GEM. It is especially important to our the shanghai ranking which is based on Web Of Science database. So it is essential to use Grenoble Ecole de Management in ROR registry

MG Note:
Change name: Grenoble Ecole de Management
Replace aliases: Grenoble School of Management
Delete label: Grenoble École de Management

Update: change.name==Grenoble Ecole de Management; replace.aliases==Grenoble School of Management; delete.labels==Grenoble École de Management;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
