### ISSUE TITLE
Add a new organization to ROR: 
 
Niedersächsischer Landesbetrieb für Wasserwirtschaft, Küsten- und Naturschutz -Forschungsstelle Küste-

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#304]
Summary of request: Add a new organization to ROR

Name of organization: Niedersächsischer Landesbetrieb für Wasserwirtschaft, Küsten- und Naturschutz -Forschungsstelle Küste-
Website: http://www.nlwkn.de/FSK/
Link to publications: https://bmbf-plastik.de/de/verbundprojekt/plawes
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://de.wikipedia.org/wiki/Niedersächsischer_Landesbetrieb_für_Wasserwirtschaft,_Küsten-_und_Naturschutz
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Lower Saxony State Agency for Water Management, Coastal Protection and Nature Conservation
Acronym/abbreviation: NLWKN
Related organizations: 
City: Norden
Country: Deutschland
Year established: 2005
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets
Other information about this request:

**Comment by carlyrobinson** [comment]
Agreed that Lower Saxony State Office for Water Management, Coastal and Nature Conservation should be added. It's within scope - they are a number of people working there and they are collecting data. ROR already includes a few Lower Saxony State Offices.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/002e7ss22 in release v1.0.
