### ISSUE TITLE
Add a new organization to ROR: 
 
Natural History Museum of the Lesvos Petrified Forest

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#307]
Summary of request: Add a new organization to ROR

Name of organization: Natural History Museum of the Lesvos Petrified Forest
Website: www.lesvosmuseum.gr
Link to publications: N/A
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: https://el.wikipedia.org/wiki/%CE%9C%CE%BF%CF%85%CF%83%CE%B5%CE%AF%CE%BF_%CE%A6%CF%85%CF%83%CE%B9%CE%BA%CE%AE%CF%82_%CE%99%CF%83%CF%84%CE%BF%CF%81%CE%AF%CE%B1%CF%82_%CE%91%CF%80%CE%BF%CE%BB%CE%B9%CE%B8%CF%89%CE%BC%CE%AD%CE%BD%CE%BF%CF%85_%CE%94%CE%AC%CF%83%CE%BF%CF%85%CF%82_%CE%9B%CE%AD%CF%83%CE%B2%CE%BF%CF%85 (Greek)
https://en.wikipedia.org/wiki/Natural_History_Museum_of_the_Lesvos_Petrified_Forest (English)
Wikidata ID: https://www.wikidata.org/wiki/Q6980528
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Μουσείο Φυσικής Ιστορίας Απολιθωμένου Δάσους Λέσβου
Acronym/abbreviation: NHMLPF
Related organizations: 
City: Western Lesvos
Country: Greece
Year established: 1994
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by KellyStathis** [comment]
I agree that this should be in ROR, even though it is not used as an affiliation.

I would also add UNESCO (https://ror.org/04h4z8k05) and the Greek Ministry of Culture and Sports (https://ror.org/02g13cw94) as related organizations in the metadata.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04gcece27 in release v1.0.
