### ISSUE TITLE
Modify the information in an existing ROR record: 
State Flight Academy of Ukraine https://ror.org/03cfeg204


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#308]
Summary of request: Modify the information in an existing ROR record

Name of organization: State Flight Academy of Ukraine
ROR ID: https://ror.org/03cfeg204
Which part of the record needs to be changed? Primary name, Organization website
Description of change: Flight Academy of the National Aviation University, web-site http://sfa.org.ua/

Update: change.name==Flight Academy of the National Aviation University; replace.links==http://sfa.org.ua/; add.aliases==State Flight Academy of Ukraine; replace.Wikidata==Q3010496;

**Comment by KellyStathis** [comment]
This change looks good to me based on the updated website.

- Update primary name: Flight Academy of the National Aviation University
- Update website: http://sfa.org.ua/
- Add alias for previous name: State Flight Academy of Ukraine

**Comment by arthurpsmith** [comment]
It looks like the proposed new name is the English translation of the current Ukrainian name we have, so definitely we should use this as they suggest it.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
