### ISSUE TITLE
Modify the information in an existing ROR record: 
University of Bremen https://ror.org/04ers2y35


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#309]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Bremen
ROR ID: https://ror.org/04ers2y35
Which part of the record needs to be changed? Organization website
Description of change: link isn't correct anymore (better https://www.uni-bremen.de/ or https://www.uni-bremen.de/en/ if you have to link the english version, but the first one is more stable)

Other information about this request: This correction request was also sended to grid

MG Note:
Replace links: https://www.uni-bremen.de/

Update: replace.links==https://www.uni-bremen.de/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
