### ISSUE TITLE
Modify the information in an existing ROR record: 
Research Library in Olomouc https://ror.org/02jh2mm49


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#310]
Summary of request: Modify the information in an existing ROR record

Name of organization: Research Library in Olomouc
ROR ID: https://ror.org/02jh2mm49
Which part of the record needs to be changed? Primary name
Description of change: There is a soft hyphen character in the name, encoded as \u00ad in the data dump. The character is normally invisible, but is there nonetheless and can disturb matching.

Update: change.name==Research Library in Olomouc;

**Comment by arthurpsmith** [comment]
Yes indeed - it doesn't show up when you look at the HTML page for the ID, but it's there when you fetch via API - looks like "Res|B|-earch Library in Olomouc" in my viewer. I wonder how many other id's have this problem. Anyway, the "soft hyphen" character definitely should be removed - just rewriting the word "Research" maybe would solve this if it's hard to see the problem in the editing UI.

**Comment by arthurpsmith** [comment]
Also if you cut and paste the word "Research" from the main ROR page for that id, it does bring the soft hyphen with it.

**Comment by arthurpsmith** [comment]
And if you paste that copy of "Research" (with the soft hyphen) into the ROR search box, only this one ID shows up. So maybe it's not a widespread problem?

**Comment by mariagould** [comment]
Very strange! We'll definitely fix this. We should do a larger cleanup effort to catch other cases like this (extra spaces, etc.)

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
