### ISSUE TITLE
Add a new organization to ROR: 
 
KAGRA

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#311]
Summary of request: Add a new organization to ROR

Name of organization: KAGRA
Website: https://gwcenter.icrr.u-tokyo.ac.jp/en/
Link to publications: 10.1103/PhysRevD.91.022005; 
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: https://en.wikipedia.org/wiki/KAGRA
Wikidata ID: https://www.wikidata.org/wiki/Q725081
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Kamioka Gravitational Wave Detector
Acronym/abbreviation:
Aliases: Kamioka Gravitational Wave Detector; KAGRA 大型低温重力波望遠鏡; Large Scale Cryogenic Gravitational Wave Telescope;
Related organizations: https://ror.org/04djymq25 (child) https://ror.org/008td3p62 (parent)
City: Hida, Gifu Prefecture
Country: Japan
Geonames ID: 11611937
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for datasets
Other information about this request:

**Comment by KellyStathis** [comment]
KAGRA appears to be associated with the Gravitational Wave Group at the Institute for Cosmic Ray Research, which is based at the University of Tokyo. There is a list of related publications here: https://www.icrr.u-tokyo.ac.jp/gr/GWPOHPe/reports-e.html. 

The ICRR is based at the University of Tokyo, but it is referred to as an "inter-university research institute" (https://www.icrr.u-tokyo.ac.jp/en/about-icrr-2/directors-greetings/). I think it's sufficiently independent that we could add the ICRR to ROR, but I'm not sure if KAGRA is in scope. Do we have other examples of facilities like this in ROR?

If we do add KAGRA, we might want to add some of the other ICRR facilities listed here: https://www.icrr.u-tokyo.ac.jp/en/facility/.

Moving to "needs discussion".

**Comment by arthurpsmith** [comment]
Ah, good to point that out. The KAGRA website is under ICRR's domain, but as it notes: "KAGRA is hosted by the Institute for Cosmic Ray Research (ICRR), the University of Tokyo, and co-hosted by the High Energy Accelerator Research Organization (KEK) and National Astronomical Observatory of Japan (NAOJ)" so it's not purely part of University of Tokyo.
Among the "ICRR facilities", I believe CTA does have a ROR id already (and is also not just a U Tokyo facility): https://ror.org/020jy7109
Kamioka Observatory I think also deserves one, it's a major physics research facility that's been operating for decades. Not sure about the others.
That said, ICRR is a pretty major institute in its own right and maybe should have a ROR even though it is indeed part of U Tokyo. It does seem to have its own Crossref Funder ID: https://doi.org/10.13039/501100013260

**Comment by adambuttrick** [comment]
Adding for context that this would likely fall under the tracking research outputs and funding acknowledgment use cases of #49 and #386.

**Comment by adambuttrick** [comment]
Adding affiliation usage for context. Affiliation pattern almost everywhere is, "Kamioka Observatory, ICRR, University of Tokyo":

Google Scholar affiliation usage: https://scholar.google.com/citations?user=lgYtLGsAAAAJ; https://scholar.google.com/citations?user=MrYQwRUAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0002-4665-2210
