### ISSUE TITLE
Add a new organization to ROR: 
 
Nosivska Breeding And Research Station

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#312]
Summary of request: Add a new organization to ROR

Name of organization: Nosivska Breeding And Research Station
Website: http://nosivkasds.at.ua
Link to publications: 10.31073/mvis201909-01
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: https://uk.wikipedia.org/wiki/%D0%9D%D0%BE%D1%81%D1%96%D0%B2%D1%81%D1%8C%D0%BA%D0%B0_%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%86%D1%96%D0%B9%D0%BD%D0%BE-%D0%B4%D0%BE%D1%81%D0%BB%D1%96%D0%B4%D0%BD%D0%B0_%D1%81%D1%82%D0%B0%D0%BD%D1%86%D1%96%D1%8F
Wikidata ID: https://www.wikidata.org/wiki/Q12134455
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Носівська селекційно-дослідна станція
Acronym/abbreviation: NSDS
Related organizations: 
City: Doslidne
Country: Ukraine
Year established: 1911
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by nlundvick** [comment]
Concur - add to ROR

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02e4h5817 in release v1.0.
