### ISSUE TITLE
Modify the information in an existing ROR record: 
Bocas del Toro https://ror.org/02ftc8763


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#313]
Summary of request: Modify the information in an existing ROR record

Name of organization: Bocas del Toro
ROR ID: https://ror.org/02ftc8763
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Other IDs for the organization
Description of change: Please change the primary name to: Bocas del Toro Research Station.  Please change the other name to: Bocas del Toro Estación de Investigación.  Please change the Wikidata ID to Q4936149 (it is currently associated with Q888971 - the island, not the research facility). Thank you!

Update: change.name==Bocas del Toro Research Station; add.acronyms==BRS; add.labels==Bocas del Toro Estación de Investigación*es; replace.Wikidata==Q4936149; delete.aliases==Bocas del Toro Research Station;

**Comment by nlundvick** [comment]
Update Primary Name to "Bocas del Toro Research Station" (confirmed at website, Wikidata, Wikipedia). Add Aliases "BRS" (Wikipedia) and "Bocas del Toro Estación de Investigación" (https://stri.si.edu/es/estacion/bocas-del-toro). Update Wikidata ID to Q4936149.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
