### ISSUE TITLE
Modify the information in an existing ROR record: 
Main Astronomical Observatory https://ror.org/02xp2c270


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#315]
Summary of request: Modify the information in an existing ROR record

Name of organization: Main Astronomical Observatory
ROR ID: https://ror.org/02xp2c270
Which part of the record needs to be changed? Other IDs for the organization
Description of change: Wikidata Q1589563 (https://www.wikidata.org/wiki/Q1589563)

Update: add.Wikidata==Q1589563; add.wikipedia_url==https://uk.wikipedia.org/wiki/Головна_астрономічна_обсерваторія_НАН_України;

**Comment by arthurpsmith** [comment]
Adding the Wikidata id is a good idea here. Also there's a Ukrainian wikipedia page:
https://uk.wikipedia.org/wiki/Головна_астрономічна_обсерваторія_НАН_України

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
