### ISSUE TITLE
Modify the information in an existing ROR record: Natural History Museum https://ror.org/0166x0j30

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#316]
Summary of request: Modify the information in an existing ROR record

Name of organization: Natural History Museum (https://ror.org/0166x0j30)
ROR ID: https://ror.org/0166x0j30
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: The museum is only listed as 'Natural History Museum' in English (Primary name) and 'Naturhistorisk Museum' in Danish. We would like these to be changed to 'Natural History Museum Aarhus' and 'Naturhistorisk Museum Aarhus' respectively.

**Comment by nlundvick** [comment]
Update Primary Name to "Natural History Museum Aarhus" (per request and confirmed at Wikidata) and Alias to "Naturhistorisk Museum Aarhus" (per museum website)

**Comment by mariagould** [comment]
Closing because this is is duplicated and now superseded by #385
