### ISSUE TITLE
Add a new organization to ROR: 
 
Fundación Grupo para la Investigación Formación y Edición Transdisciplinar

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#317]
Summary of request: Add a new organization to ROR

Name of organization: Fundación Grupo para la Investigación Formación y Edición Transdisciplinar
Website: https://fundaciongifet.wordpress.com/
Link to publications: https://petroglifosrevistacritica.org.ve/
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation: GIFET
Aliases: Fundación GIFET
Related organizations: 
City: Maracay
Country: Venezuela
Geonames ID: 3632998
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by carlyrobinson** [comment]
A research organization, with a number of people, publishing a magazine - I'd recommend adding.

**Comment by adambuttrick** [comment]
Adding as additional context this ORCID affiliation usage: https://orcid.org/0000-0003-2467-5961 ; https://orcid.org/0000-0003-2035-4116 ; https://orcid.org/0000-0003-0749-726X

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00d9nf164 in release v1.0.
