### ISSUE TITLE
Add a new organization to ROR: 
 
UMR Géographie-cités

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#319]
Summary of request: Add a new organization to ROR

Name of organization: UMR Géographie-cités
Website: https://geographie-cites.cnrs.fr/
Link to publications: https://hal.archives-ouvertes.fr/GEOGRAPHIE-CITE
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/Q51781143
ISNI ID: https://isni.org/isni/0000000406236436
GRID ID: 
Crossref Funder ID: 
Other names for the organization: UMR 8504
Acronym/abbreviation: GC
Related organizations: CNRS https://ror.org/02feahw73 (related)
City: Aubervilliers
Country: France
Year established: 1987
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request: The national number (France) of this organization is: 99812840V

**Comment by arthurpsmith** [comment]
I added Wikidata and ISNI id's. Also fixed the website link (original link was to an English page that has moved). Clearly a significant research organization and it's been around for over 30 years. An example recent affiliation use is here: https://doi.org/10.1111/tesg.12460 - several authors list affiliation with "Géographie-cités" while also mentioning either University of Paris or CNRS. It's multi-parented and we already have ROR id's for similar French UMR laboratories (like https://ror.org/033ebya06, https://ror.org/026tc4g97 etc.). This should have a ROR  id.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05yqfzf35 in release v1.0.
