### ISSUE TITLE
Add a new organization to ROR: Rockefeller University Press

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#3204]
Summary of request: Add a new organization to ROR

Name of organization: Rockefeller University Press
Website: https://rupress.org/
Link to publications: https://api.crossref.org/works?query.publisher-name=Rockefeller&filter=has-ror-id:t
Organization type: Other
Wikipedia page: https://en.wikipedia.org/wiki/Rockefeller_University_Press
Wikidata ID: Q1524082 
ISNI ID: 0000 0004 0619 781X
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: RUP
Related organizations:  https://ror.org/0420db125 (parent)
City: New York
Country: United States 
Geonames ID: 5128581
Year established: 1910
How will a ROR ID for this organization be used? In the OA Switchboard and in publisher metadata
Other information about this request: Since the curation board has determined that university presses are in scope for ROR, we should add ROR adopter Rockefeller University Press.

**Comment by adambuttrick** [comment]
In scope for ROR by virtue of our publisher use case. Affiliation usage looks fine as well.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04er32z07 in release v1.25.
