### ISSUE TITLE
Modify the information in an existing ROR record: 
French National Centre for Scientific Research https://ror.org/02feahw73


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#321]
Summary of request: Modify the information in an existing ROR record

Name of organization: French National Centre for Scientific Research
ROR ID: https://ror.org/02feahw73
Which part of the record needs to be changed? Other IDs for the organization
Description of change: ISNI is 0000000122597504 , the actual value is not correct

https://aurehal.archives-ouvertes.fr/structure/read/id/441569

Other information about this request: It seems that this was migrated from Grid, thank you in advance

Update: replace.ISNI==0000 0001 2259 7504;

**Comment by arthurpsmith** [comment]
Yes, ISNI should be replaced with:

https://isni.org/isni/0000000122597504

as they request. The existing ISNI seems to be for a subsection of CNRS, not the top-level organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
