### ISSUE TITLE
Modify the information in an existing ROR record: 
Shupyk National Medical Academy of Postgraduate Education https://ror.org/02cyra061


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#322]
Summary of request: Modify the information in an existing ROR record

Name of organization: Shupyk National Medical Academy of Postgraduate Education
ROR ID: https://ror.org/02cyra061
Which part of the record needs to be changed? Primary name
Description of change: We would like to inform you that by the order of the Ministry of Health of Ukraine of February 10, 2021 № 225 "On changing the type, renaming and approval of the Charter of the National University of Health of Ukraine named after PL Shupyk (new edition)" National Medical Academy of Postgraduate Education named after PL Shupyk was renamed the PL Shupyk National University of Health of Ukraine (abbreviated name: PL Shupyk National Health Insurance Institute of Ukraine). PL Shupyk National University of Health of Ukraine is the legal successor of all rights and responsibilities of the PL Shupyk National Medical Academy of Postgraduate Education. Relevant documents can be found on the official website of the university: www.nuozu.edu.ua; e-mail address: office@nuozu.edu.ua

Update: change.name==Shupyk National Healthcare University of Ukraine; replace.links==https://nuozu.edu.ua; replace.labels==Національний університет охорони здоров'я України імені П. Л. Шупика*Ukrainian; delete.aliases==Kiev Institute of Advanced Training of Physicians; delete.acronyms==NMAPE;$

**Comment by arthurpsmith** [comment]
The old website (which we currently list) redirects to the new one:
https://nuozu.edu.ua/
The name listed on the English version of the new website is:
"Shupyk National Healthcare University of Ukraine"

The name in Ukrainian from the website is:
"Національний університет охорони здоров'я України імені П. Л. Шупика"

so I think we should change the primary name and the Ukrainian label as above, and also the website link.

Then add as alias the name they ask for "PL Shupyk National University of Health of Ukraine" (this doesn't appear on the website - I think they must have Google translated the Ukrainian name?)

**Comment by carlyrobinson** [comment]
I agree with @arthurpsmith assessment and changes. One strange thing - in the About information and in the Education - Global Programs, it still uses the old name Shupyk National Medical Academy of Postgraduate Education. Not sure if that should be considered?

**Comment by mariagould** [comment]
It looks like the name has also been updated in Wikidata: https://www.wikidata.org/wiki/Q2083440.

However, I'm also confused because the Ministry of Health website still refers to it by the old name: https://en.moz.gov.ua/educational-institutions. 

Let's check back on this later to confirm.

**Comment by adambuttrick** [comment]
English language references appear not to have been updated, but Ukrainian form is as described, including on the Ministry of Health site, so we should proceed with the update:

https://moz.gov.ua/en/navchalni-zakladi

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
