### ISSUE TITLE
Modify the information in an existing ROR record: 
Phoenix Hospital Chelmsford https://ror.org/03jasrp23


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#323]
Summary of request: Modify the information in an existing ROR record

Name of organization: Phoenix Hospital Chelmsford
ROR ID: https://ror.org/03jasrp23
Which part of the record needs to be changed? Organization website
Description of change: Website merge. Updated URL - https://www.phoenixhospitalgroup.com/our-locations/phoenix-hospital-chelmsford/
We also need the 'other name' changed from 'Baddow Hospital' To Phoenix Hospital Group

MG Note:
Replace links: https://www.phoenixhospitalgroup.com/our-locations/phoenix-hospital-chelmsford/
Add Wikidata ID: Q88222461 (preferred)

Update: replace.links==https://www.phoenixhospitalgroup.com/our-locations/phoenix-hospital-chelmsford/; add.Wikidata==Q88222461;

**Comment by arthurpsmith** [comment]
So the question to me here is whether we should make this ROR the id for the top-level organization (which seems relatively new) - "Phoenix Hospital Group". This top-level org has Phoenix Hospital Chelmsford as a subsidiary, but also Weymouth Street Hospital and a couple of additional clinics (based on their website). We don't have a ROR for any of these right now, only this one for the Chelmsford location.

The website we currently have redirects to the main "phoenixhospitalgroup.com" page now. There is also a new Wikidata ID for the Chelmsford hospital: Q88222461, and Q88222468 for "Phoenix Hospital Group", also Q20714162 for Weymouth Street Hospital.

If we keep this as just the id for the Chelmsford hospital then I think we should also keep the name "Baddow Hospital" as an alias for historical purposes as we do in other cases where a name has changed. We can add "Phoenix Hospital Group" also as an alias and adjust the website as requested, assuming we don't create a new id for "Phoenix Hospital Group" separately. Not sure on this - I guess the minimal change is to go ahead as requested without creating new id's or changing to top level rght now.

**Comment by KellyStathis** [comment]
I agree we should keep this record specific to the Chelmsford location. However, if we do that, I'm not sure about adding "Phoenix Hospital Group" as an alias when it's really the parent org. I would propose creating a new ROR ID for the parent instead.

Side question on our process - do we update Wikidata when we update/add new ROR IDs? I noticed that the Baddow Hospital Wikidata page (Q30292854) references this ROR ID, but it isn't on the Chelmsford hospital Wikidata page (Q88222461) - we could add it there too.

Moving to "Needs discussion".

**Comment by mariagould** [comment]
I agree with Kelly that we should keep this record specific to the Chelmsford location. We should also add the Wikidata ID for Chelmsford hospital (Q88222461), and keep Baddow as an alias.

I'm a little wary of creating new records for corporate parent entities like hospital groups without documented use cases for ROR IDs. I'll add this as a discussion topic for a future meeting.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
