### ISSUE TITLE
Modify the information in an existing ROR record: 
Pyatigorsk State Pharmaceutical Academy https://ror.org/0364tzz24


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#325]
Summary of request: Modify the information in an existing ROR record

Name of organization: Pyatigorsk State Pharmaceutical Academy
ROR ID: https://ror.org/0364tzz24
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website, Other IDs for the organization, Organization type, Something else
Description of change: According to the Order of the Ministry of Health and Social Development of the Russian Federation No.434 dated 28.04.2012, the Pyatigorsk State Pharmaceutical Academy is attached to the Volgograd State Medical University as a separate subdivision (branch).
Its label was changed to Pyatigorsk Medical and Pharmaceutical Institute - branch of Volgograd State Medical University.
The institute has recently received a new ISNI - https://isni.org/isni/0000000503828740
Wikipedia - https://ru.wikipedia.org/wiki/%D0%9F%D1%8F%D1%82%D0%B8%D0%B3%D0%BE%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B5%D0%B4%D0%B8%D0%BA%D0%BE-%D1%84%D0%B0%D1%80%D0%BC%D0%B0%D1%86%D0%B5%D0%B2%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B8%D0%BD%D1%81%D1%82%D0%B8%D1%82%D1%83%D1%82
Wikidata - https://www.wikidata.org/wiki/Q52637580
New official website - http://www.pmedpharm.ru/

Related organizations: https://ror.org/04q6a0352 (parent)

Update: change.name==Pyatigorsk Medical and Pharmaceutical Institute - branch of Volgograd State Medical University; add.labels==Пятигорский медико-фармацевтический институт – филиал Волгоградского государственного медицинского университет*Russian; delete.labels==Пятигорская государственная фармацевтическая академия; add.aliases==Пятигорская государственная фармацевтическая академия; add.aliases==Pyatigorsk State Pharmaceutical Academy; replace.ISNI==0000 0005 0382 8740; replace.links==http://www.pmedpharm.ru/; add.Wikidata==Q4385790;

**Comment by arthurpsmith** [comment]
We definitely had an out of date name for this - it changed in 2013 or maybe 2016 at latest. The website link we had is dead (the new website they propose is fine). The change in ISNI seems ok; the new Wikidata ID they propose isn't the right one - I've corrected it in the notes below.

When we can we should link this ROR id to its parent: https://ror.org/04q6a0352

So changes needed here are (I think this is straightforward):
* Primary label: Pyatigorsk Medical and Pharmaceutical Institute - branch of Volgograd State Medical University
* Label in Russian: Пятигорский медико-фармацевтический институт – филиал Волгоградского государственного медицинского университета
* Move current English and Russian labels to alternate labels
* Change ISNI to https://isni.org/isni/0000000503828740
* Change website to http://www.pmedpharm.ru/
* Add Wikidata ID https://www.wikidata.org/wiki/Q4385790
* When possible link to parent ROR: https://ror.org/04q6a0352

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
