### ISSUE TITLE
Modify the information in an existing ROR record: 
 École Normale Supérieure - PSL https://ror.org/05a0dhs15


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#326]
Summary of request: Modify the information in an existing ROR record

Name of organization:  École Normale Supérieure - PSL
ROR ID: https://ror.org/05a0dhs15
Which part of the record needs to be changed? Organization website, Other IDs for the organization
Description of change: ISNI is not the good one (it connect to ENS Paris Cachan) the good one is 0000000123532622. It could be better to give the website with the psl domain (https://www.ens.psl.eu/)

Update: replace.ISNI==0000 0001 2353 2622; replace.links==https://www.ens.psl.eu/;

**Comment by arthurpsmith** [comment]
Yes, best to change website and ISNI as requested. Our current website URL redirects to the one they  request.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
