### ISSUE TITLE
Modify the information in an existing ROR record: 
Leibniz Institute for Research and Information in Education https://ror.org/0327sr118


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#328]
Summary of request: Modify the information in an existing ROR record

Name of organization: Leibniz Institute for Research and Information in Education
ROR ID: https://ror.org/0327sr118
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: New name, german and english: DIPF | Leibniz-Institut für Bildungsforschung und Bildungsinformation; DIPF | Leibniz Institute for Research and Information in Education

Update: change.name==DIPF | Leibniz Institute for Research and Information in Education; add.labels==Leibniz-Institut für Bildungsforschung und Bildungsinformation*German; add.Wikidata==Q1205728; change.wikipedia_url==https://de.wikipedia.org/wiki/DIPF_Leibniz-Institut_für_Bildungsforschung_und_Bildungsinformation;

**Comment by arthurpsmith** [comment]
Note the current name we have is "German Institute for International Educational Research". Their website (from the link we have already) agrees with their proposed new names. So we should change:
* Primary name: Leibniz Institute for Research and Information in Education
* German label:  Leibniz-Institut für Bildungsforschung und Bildungsinformation

We already have the acronym DIPF. The current primary name and German label should probably be kept as aliases.

**Comment by mariagould** [comment]
The acronym DIPF appears to be used as part of the primary affiliation string, e.g.: see
https://doi.org/10.1111/jcal.12626 and https://doi.org/10.1007/s11218-021-09656-5

This is in accordance with the request so the primary name and German name should be adjusted accordingly.

**Comment by mariagould** [comment]
Also add Wikidata https://www.wikidata.org/wiki/Q1205728 and Wikipedia https://de.wikipedia.org/wiki/DIPF_Leibniz-Institut_f%C3%BCr_Bildungsforschung_und_Bildungsinformation

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
