### ISSUE TITLE
Add a new organization to ROR: 
 
Institut Scientifique de Rabat

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#332]
Summary of request: Add a new organization to ROR

Name of organization: Institut Scientifique de Rabat
Website: http://www.israbat.ac.ma
Link to publications: https://www.scopus.com/source/eval.uri
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://fr.wikipedia.org/wiki/Institut_scientifique_de_Rabat
Wikidata ID: https://www.wikidata.org/wiki/Q3152518
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: المعهد العلمي الرباط
Acronym/abbreviation: ISR
Related organizations: 
City: Rabat
Country: Morocco
Year established: 1920
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by arthurpsmith** [comment]
Long-established, and definitely used as an affiliation in research publications - example from 1980 here: https://repository.naturalis.nl/pub/504413
The wikipedia page mentions that it is affiliated with a university, but the university doesn't seem to be mentioned in the affiliation use nor is the website URL related to the university. This seems to me to qualify for its own ROR id.

**Comment by nlundvick** [comment]
Concur - add to ROR

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03ckf5b20 in release v1.0.
