### ISSUE TITLE
Modify the information in an existing ROR record: 
Museum of Natural Sciences of Barcelona ror.org/015hz7p22


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#334]
Summary of request: Modify the information in an existing ROR record

Name of organization: Museum of Natural Sciences of Barcelona
ROR ID: https://ror.org/015hz7p22
Which part of the record needs to be changed? Primary name
Description of change: Primary name should be Natural Science Museum of Barcelona (it already appears in the record). This is the one used in publications and the one that appears in the website. 

Update: change.name==Natural Science Museum of Barcelona; add.aliases==Museum of Natural Sciences of Barcelona; delete.aliases==Natural Science Museum of Barcelona;

**Comment by mariagould** [comment]
Records in Google Scholar show the English version of the affiliation as Natural Science Museum of Barcelona. We can accept this change to the record by switching the current alias and primary name fields:

Primary name: Natural Science Museum of Barcelona 
Alias: Museum of Natural Sciences of Barcelona

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
