### ISSUE TITLE
Modify the information in an existing ROR record: 
Institute of the Czech Language https://ror.org/01912nj27 


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#335]
Summary of request: Modify the information in an existing ROR record

Name of organization: Institute of the Czech Language
ROR ID: https://ror.org/01912nj27 
Which part of the record needs to be changed? Primary name
Description of change: Our name of the Institute has been changed and right name is "Czech Language Institute of the Czech Academy of Sciences"
https://ujc.avcr.cz/index.html
Update: change.name==Czech Language Institute of the Czech Academy of Sciences; add.aliases==Institute of the Czech Language; delete.aliases==Ústav pro Jazyk AV ČR; delete.links==http://www.ujc.cas.cz/; add.links==https://ujc.avcr.cz/; add.labels==Ústav pro jazyk český AV ČR*Czech; add.wikipedia_url==https://en.wikipedia.org/wiki/Institute_of_the_Czech_Language; add.Wikidata==Q1661875;

**Comment by arthurpsmith** [comment]
Yes, the name should be changed; it appears the Czech name is also slightly different. Also the website we have redirects to the one they mention so we should fix that too.
Changes needed:
Primary name: Czech Language Institute of the Czech Academy of Sciences
Czech label: Ústav pro jazyk český AV ČR
Website: https://ujc.avcr.cz/
The current primary name should probably be kept as an alias.

**Comment by mariagould** [comment]
Also add Wikidata ID: https://www.wikidata.org/wiki/Q1661875

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
