### ISSUE TITLE
Modify the information in an existing ROR record: 
Golisano Children's Hospital ror.org/02rcfy15


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#337]
Summary of request: Modify the information in an existing ROR record

Name of organization: Golisano Children's Hospital
ROR ID: https://ror.org/02rcfyf15
Which part of the record needs to be changed? Other IDs for the organization
Description of change: GCH is part of University of Rochester Medical Center ror.org/00trqv719

Other information about this request: Rockefeller Univ Press is using ROR ID for Read & Publish subscriptions. We want to make sure all UR and URMC departments are under/affiliated so our instiutional authors are recognized as UR(MC) affiliated.

Curator comments (MG):
Per conversation with requestor, the desired change is to add Golisano Children's Hospital (https://ror.org/02rcfyf15) as a child to University of Rochester (https://ror.org/022kthw22). 

Related organizations: https://ror.org/022kthw22 (parent)

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
