### ISSUE TITLE
Modify the information in an existing ROR record: 
CVUA Stuttgart https://ror.org/049waqj15


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#339]
Summary of request: Modify the information in an existing ROR record

Name of organization: CVUA Stuttgart
ROR ID: https://ror.org/049waqj15
Which part of the record needs to be changed? Primary name
Description of change: The "official" Name of CVUA Stuttgart in English is 
"Chemical and Veterinary Investigations Office Stuttgart“.

The one currently given under https://ror.org/049waqj15 (Chemical and Veterinary Testing Agency Stuttgart) is not correct!

Other information about this request: Please see the screenshot from our intranet-page indicating the correct translation of CVUA Stuttgart in English: https://cloud.landbw.de/index.php/s/nnFFZsGW4ysLkrd

Update: change.name==Chemical and Veterinary Investigations Office Stuttgart; add.Wikidata==Q104481400;

**Comment by arthurpsmith** [comment]
The share seems to be broken now (I guess somebody should have  looked sooner?!) Anyway, the translation of "Veterinäruntersuchungsamt" as "Veterinary Investigations Office"  seems closer to accurate than "Veterinary Testing Agency" so this request makes sense to me. They don't use an English version of their name on their website as far as I can see, so we could also just go with the official German name as the primary label.

Anyway, for now I think just doing as requested here makes the most sense. So change is:
Primary name: Chemical and Veterinary Investigations Office Stuttgart

**Comment by mariagould** [comment]
Also add Wikidata ID: https://www.wikidata.org/wiki/Q104481400

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
