### ISSUE TITLE
Modify the information in an existing ROR record: 
i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto  https://ror.org/04wjk1035


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#340]
Summary of request: Modify the information in an existing ROR record

Name of organization: i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto
ROR ID:  https://ror.org/04wjk1035
Which part of the record needs to be changed? Primary name
Description of change: I would like the institution's name to be changed to:  i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto.

Update: change.name==i3S - Institute for Research and Innovation in Health, University of Porto; add.labels== i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto*Portuguese; delete.labels==Instituto de Investigação e Inovação em Saúde;

**Comment by arthurpsmith** [comment]
Hmm, the request is to replace  the current English primary label with the official name in Portuguese. I think instead we should replace the Portuguese label with what they propose. However, most of their  website is in English  and they do use an English name there  for the  institute - "Institute for Research and Innovation in Health".

So I  recommend:
* Primary name: i3S -  Institute for Research and Innovation in Health, University of Porto
* Portuguese label:  i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
