### ISSUE TITLE
Modify the information in an existing ROR record: 
Bell Resources Limited https://ror.org/002dxp647


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#341]
Summary of request: Modify the information in an existing ROR record

Name of organization: Bell Resources Limited
ROR ID: https://ror.org/002dxp647
Which part of the record needs to be changed? Other IDs for the organization
Description of change: add wikipedia to the records.
https://en.wikipedia.org/wiki/Bell_Resources

Update: add.wikipedia_url==https://en.wikipedia.org/wiki/Bell_Resources;

**Comment by arthurpsmith** [comment]
Looks like a wikipedia page was created last year for this. Yes,  let's make this change; simple enough!

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
