### ISSUE TITLE
Modify the information in an existing ROR record: 
Public Health England (PHE) https://ror.org/00vbvha87


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#342]
Summary of request: Modify the information in an existing ROR record

Name of organization: Public Health England (PHE)
ROR ID: https://ror.org/00vbvha87
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website, Other IDs for the organization
Description of change: Public Health England has been replaced by the UK Health Security Agency. Please see information related to this here
https://www.gov.uk/government/organisations/public-health-england (information about replacement at the top of the page)
https://www.gov.uk/government/publications/transforming-the-public-health-system/transforming-the-public-health-system-reforming-the-public-health-system-for-the-challenges-of-our-times (detailed information about the changes) 
https://en.wikipedia.org/wiki/UK_Health_Security_Agency
I am thinking it would be best to update/modify the existing PHE record because the majority of PHE functions are now part of UKHSA and the site locations of the main PHE sites are the same as previously.

Other information about this request: Please let me know if you need any further information we have recently for example updated the previous Ringgold ID for publishing with the new organisation name UK Health Security Agency ID 371011.

**Comment by arthurpsmith** [comment]
There is a new wikidata ID also: https://www.wikidata.org/wiki/Q104336949
It is still part of the Department of Health and Social Care.
There does NOT seem to be an ISNI for the new agency. I think it would be confusing to re-use this ROR id for the new one. I believe we should create a new ID for this since there are so many differences, and the previous organization was not entirely folded into the new one:
* Primary name: UK Health Security Agency
* Acronym: UKHSA
* Type: Government
* Established: 2020
* Country: United Kingdom
* Website: https://www.gov.uk/government/organisations/uk-health-security-agency
* Wikipedia link: https://en.wikipedia.org/wiki/UK_Health_Security_Agency
* Wikidata ID: https://www.wikidata.org/wiki/Q104336949
* Parent organization: https://ror.org/03sbpja79

**Comment by mariagould** [comment]
I received some additional information from the requesting organization that might help us come to a decision. The comments came from 3 different colleagues. The questions about handling deprecated/redirected IDs is something we don't have a solution for yet, but will be exploring this year. 

```
In relation to your question on whether or not to update the existing record or create a new record for UKHSA please see comments below from staff here:
 
**Comment 1**
I can’t see any disadvantages with a new entry for UKHSA. Obviously the PHE entry would need to indicate that PHE no longer exists. Would the PHE entry stay visible? If yes, then a suitable contact, presumably at UKHSA, should be supplied.
 
**Comment 2**
Creating a new record for UKHSA should not be a disadvantage, but if a new record for UKHSA is created will it show that it was previously linked to PHE or are all the records on the ROR standalone records where no relationship/predecessor organisations are shown?
 
**Comment 3**
I think the reason we were thinking to initially update/modify the existing record rather than create a new record was because we know of at least one current service that is using the ROR to identify organisations, and this is a journal checker tool: https://journalcheckertool.org/. Currently this journal checker tool is using PHE’s ROR ID, so if a new record is created for UKHSA it will mean we will have to contact this service to get them to change the organisation name/ROR ID to UKHSA. We are also unsure of any other services that are currently using PHE’s ROR ID that may need to be contacted if there is a new record created on the ROR for UKHSA. Although admittedly services currently using the PHE ROR ID might not be dynamically updating anyway, so even if the existing PHE ROR record was only updated/modified to show details of the new organisation these services may still need to be contacted to get them to manually update their information.
```

**Comment by KellyStathis** [comment]
Weighing in here - to me, it's significant that the website says PHE has been replaced by UKHSA **and** the Office for Health Improvement and Disparities. If we modify PHE to UKHSA, we aren't representing the change accurately - and in cases where the previous ROR ID was used as an affiliation, staff who are now part of the OHID will be mislabeled as affiliated with UKHSA.

I support creating a new ROR ID for _both_ the new organizations - UKHSA and OHID - and relating these organizations back to PHE. This does mean that services that use the PHE ROR, like the journal checker tool, will need to make changes. 

Unfortunately, I think this is part of the messiness of government departments... we have similar cases in Canada that I have noticed in ROR (both federal and provincial level), which I haven't submitted yet. Ultimately, I would be interested to see ROR add predecessor/successor relationship types, for cases that are not a straightforward name change.

**Comment by adambuttrick** [comment]
I agree with Kelly's assessment. We should create two records for the successor organizations, although we would have to determine what proper redirect for this case would be. I will flag this as an example in our development discussions, as well as the predecessor/successor relationship types as a change to the data model.

**Comment by adambuttrick** [comment]
Closing as this has been separated into three corresponding issues.
