### ISSUE TITLE
Add a new organization to ROR: 
 
Trabzon University 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#346]
Summary of request: Add a new organization to ROR

Name of organization: Trabzon University 
Website: http://www.trabzon.edu.tr
Link to publications: http://www.trabzon.edu.tr
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://en.wikipedia.org/wiki/Trabzon_University
Wikidata ID: https://www.wikidata.org/wiki/Q52162277
ISNI ID: https://isni.org/isni/000000047889928X
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Trabzon Üniversitesi (Turkish)
Acronym/abbreviation: TRU
Related organizations: 
City: Trabzon
Country: Turkey
Year established: 2018
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by arthurpsmith** [comment]
I added WIkidata and ISNI id's. This is a new university (established 2018) but it does already appear as an affiliation  in research publications (from Google Scholar). From the WIkipedia page and their "history" page (https://trabzon.edu.tr/Website/Contents.aspx?PageID=2429&LangID=1) they seem to have been partly split off from Karadeniz Technical University (https://ror.org/03z8fyr40) but it doesn't seem like they are still affiliated with that institution. So yes, this should have it's own ROR id.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04mmwq306 in release v1.0.
