### ISSUE TITLE
Add a new organization to ROR: 
 
California Geological Survey

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#347]
Summary of request: Add a new organization to ROR

Name of organization: California Geological Survey
Website: https://www.conservation.ca.gov/cgs
Link to publications: https://www.conservation.ca.gov/cgs/library
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://en.wikipedia.org/wiki/California_Geological_Survey
Wikidata ID: https://www.wikidata.org/wiki/Q5020505
ISNI ID: https://isni.org/isni/000000010807116X
GRID ID: 
Crossref Funder ID: 
Other names for the organization: California Division of Mines and Geology
Acronym/abbreviation: CGS
Related organizations: https://ror.org/00vmaka31 (parent)
City: Sacramento
Country: United States
Year established: 1853
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by arthurpsmith** [comment]
We've been adding other state geological surveys, so we should definitely have California's! Information provided looks complete and accurate, I think this is straightforward, it should have a ROR id.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01xfrxk65 in release v1.0.
