### ISSUE TITLE
Add a new organization to ROR - Kasturba Medical College, Mangalore

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#3478]
Summary of request: Add a new organization to ROR

Name of organization: Kasturba Medical College, Mangalore
Website: https://manipal.edu/kmc-mangalore.html
Link to publications:
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Kasturba_Medical_College,_Mangalore
Wikidata ID: Q6374846
ISNI ID: 0000 0004 1802 780X
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: KMC Mangalore
Labels:
Acronym/abbreviation: 
Related organizations: https://ror.org/02xzytt36 (parent)
City: Mangalore
Country: India
Geonames ID: 1263780
Year established: 1953
Other information about this request: Part of #3475

**Comment by adambuttrick** [comment]
With existing inclusion of https://ror.org/05hg48t65 and its hospital, https://ror.org/00kkxv282, in ROR, I can see the case for adding this. Affiliation usage appears to be at this level, without reference to parent organization Manipal University.

**Comment by nlundvick** [comment]
Medical college that is associated with research activities and publications. Affiliation use: https://api.crossref.org/works/?query.affiliation=Kasturba+Medical+College+Mangalore. Related medical college is in the registry (https://ror.org/05hg48t65). In scope, add to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/048vk1h54 in release v1.27.
