### ISSUE TITLE
Add a new organization to ROR - Manipal-Tata Medical College, Jamshedpur

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#3479]
Summary of request: Add a new organization to ROR

Name of organization: Manipal-Tata Medical College, Jamshedpur
Website: https://manipal.edu/mtmc-jamshedpur.html
Link to publications:
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Manipal-Tata_Medical_College,_Jamshedpur
Wikidata ID: Q113561011
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: MTMC Jamshedpur; Tata Medical College, Jamshedpur
Labels:
Acronym/abbreviation: 
Related organizations: https://ror.org/02xzytt36 (parent)
City: Jamshedpur
Country: India
Geonames ID: 1269300
Year established: 
Other information about this request: Part of #3475

**Comment by adambuttrick** [comment]
With existing inclusion of https://ror.org/05hg48t65 and its hospital, https://ror.org/00kkxv282, in ROR, I can see the case for adding this. Affiliation usage appears to be at this level, without reference to parent organization Manipal University

**Comment by mariagould** [comment]
I could see a case for adding this given that it has a secondary parent in Tata Steel. However, I'd like to flag this for group discussion so we can make sure we're staying in alignment with regard to handling university-affiliated medical schools in general.

**Comment by adambuttrick** [comment]
Corresponds to existing pattern of adding affiliated colleges in India.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04qkb5e79 in release v1.32.
