### ISSUE TITLE
Add a new organization to ROR: Biological Museum, Lund University 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#349]
Summary of request: Add a new organization to ROR

Name of organization: Biological Museum, Lund University 
Website: https://www.biology.lu.se/biological-museum
Organization type: Archive
Link to publications: 
Wikipedia page:
Wikidata ID: Q105086168
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: Biologiska Museet, Lunds universitet
Acronym/abbreviation: LD, MZLU
Labels: Biologiska Museet, Lunds universitet*Swedish;
Related organizations: https://ror.org/012a77v79 (parent)
City: Lund
Country: Sweden
Geonames ID: 2693678
Other information about this request: Second largest natural history museum in Sweden

**Comment by arthurpsmith** [comment]
This is entirely part of the university, within the Department of Biology, as the website indicates. As not a top-level unit (and not clearly used anywhere as an affiliation) I don't believe this is in scope for ROR at this time.

**Comment by KellyStathis** [comment]
Looking at the [guidance for common organization types](https://github.com/ror-community/ror-updates/wiki/Curator-Evaluation-Workflow:-New-Records#guidance-for-evaluating-common-organization-types), we specify that for a museum within a university, "Add to ROR if: they are producing research and the museum is used as an affiliation." I agree that the  museum by itself is not used as an affiliation - for example, the museum director uses his university affiliation on his ORCID: https://orcid.org/0000-0002-1259-3363 

However, this feels like a fine line that we're drawing here. The example in the guidance is the UC Berkeley Museum of Vertebrate Zoology (https://ror.org/01rdg4502) - I'm not sure if the difference between these two examples is significant:
- The [UCMVZ website](https://mvz.berkeley.edu/) is also hosted within the UC Berkeley domain, and although it doesn't mention a department, it is a [research unit within the university](https://vcresearch.berkeley.edu/research-units?for=All&search=&rut=All&page=4).
- Both museums are listed in GBIF: [UCMVZ](https://www.gbif.org/grscicoll/institution/59175240-4500-42b9-9e98-42ae299a5e9b/metrics), [Lund University Biological Museum](https://www.gbif.org/grscicoll/institution/13edc77b-7023-4ddd-89c7-d883a480b294)

I do agree that this is not a top-level organization; however, I want to make sure we are consistent. Moving to "needs discussion".

**Comment by adambuttrick** [comment]
The publication affiliation usage pattern for the UC Berkeley Museum of Vertebrate Zoology and the Biological Museum, Lund University are more or less identical :

Biological Museum, Lund University:
https://lucris.lub.lu.se/ws/files/24186691/Kondratyuk_et_al.pdf
https://lucris.lub.lu.se/ws/files/46184553/GS_30_94.pdf
https://www.mapress.com/zt/article/view/zootaxa.5047.3.8

UC Berkeley Museum of Vertebrate Zoology and Biological Museum:
https://onlinelibrary.wiley.com/doi/full/10.1111/mec.13529
https://onlinelibrary.wiley.com/doi/abs/10.1111/zsc.12368
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.580.9635&rep=rep1&type=pdf

If we take UC Berkeley Museum of Vertebrate Zoology and Biological Museum as our guidance/precedent, I'm not sure how we could justify excluding Biological Museum, Lund University. Agree with Kelly that we need to firm this up for the sake of consistency.

**Comment by arthurpsmith** [comment]
I stand corrected, Adam has found some cases where the museum is used directly as an affiliation. So given our criteria I think it does qualify for a ROR after all.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/048555y32 in release v1.0.
