### ISSUE TITLE
Add a new organization to ROR: Natural History Museum Maastricht 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#350]
Summary of request: Add a new organization to ROR

Name of organization: Natural History Museum Maastricht 
Website: http://nhmmaastricht.nl
Link to publications: 
Organization type: Archive
Wikipedia page: https://en.wikipedia.org/wiki/Maastricht_Natural_History_Museum
Wikidata ID: https://www.wikidata.org/wiki/Q2412016
ISNI ID: https://isni.org/isni/0000000084997610
GRID ID:
Crossref Funder ID:
Other names for the organization: Natuurhistorisch Museum Maastricht
Acronym/abbreviation: NHMM, NHME, MAA
Labels: Natuurhistorisch Museum Maastricht (Dutch)
Related organizations: 
City: Maastricht
Country: Netherlands
Geonames ID: 2751282
Year established: 1912
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by arthurpsmith** [comment]
They didn't provide a link to publications or a "How will a ROR ID for this organization be used?" !!  Nevertheless this appears to be a significant well-established museum that is widely referred to in research publications, though I couldn't find a lot of cases where it was actually an affiliation (there were a few though). I've added ISNI and  Wikipedia ID's. I think this should have a ROR id.

**Comment by carlyrobinson** [comment]
Agree that is should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0488nj033 in release v1.0.
