### ISSUE TITLE
Add a new organization to ROR: Gothenburg Natural History Museum

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#351]
Summary of request: Add a new organization to ROR

Name of organization: Gothenburg Natural History Museum
Website: https://www.gnm.se/
Link to publications: 
Organization type: Archive
Wikipedia page: https://sv.wikipedia.org/wiki/Göteborgs_Naturhistoriska_museum
Wikidata ID: https://www.wikidata.org/wiki/Q848411
ISNI ID: https://isni.org/isni/0000000100593334
GRID ID:
Crossref Funder ID:
Other names for the organization: Göteborgs Naturhistoriska Museum
Acronym/abbreviation: GNM
Labels: Göteborgs Naturhistoriska Museum (Swedish)
Related organizations: 
City: Gothenburg
Country: Sweden
Geonames ID: 2711533
Year established: 1833
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by arthurpsmith** [comment]
Again, widely referenced in research publications, I think this should have a ROR  id.

I added the Wikipedia and ISNI links, and year established from what I  could find.

**Comment by carlyrobinson** [comment]
Agree that it should have a ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01yhex183 in release v1.0.
