### ISSUE TITLE
Modify the information in an existing ROR record: 
Reiner Lemoine Institute https://ror.org/03xvdbr49


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#353]
Summary of request: Modify the information in an existing ROR record

Name of organization: Reiner Lemoine Institute
ROR ID: https://ror.org/03xvdbr49
Which part of the record needs to be changed? Other IDs for the organization
Description of change: Add link to Wikidata: https://www.wikidata.org/wiki/Q77077223

Update: add.labels==Reiner Lemoine Institut*German; add.Wikidata==Q77077223;

**Comment by nlundvick** [comment]
Add Wikidata information. Also add German label "Reiner Lemoine Institut"

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
