### ISSUE TITLE
Modify the information in an existing ROR record: 
Botanical Garden – Centre for Biological Diversity Conservation in Powsin https://ror.org/020vrnw42


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#354]
Summary of request: Modify the information in an existing ROR record

Name of organization: Botanical Garden – Centre for Biological Diversity Conservation in Powsin
ROR ID: https://ror.org/020vrnw42
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: Dear Sir/Madam,
there is an error in the database regarding the name of our institution in both English and Polish. Instead of "Botanical Garden - Center for Biological Diversity Conservation in Powsin" Warsaw, PL should be: "Polish Academy of Sciences Botanical Garden – Center for Biological Diversity Conservation in Powsin" Warsaw, PL. Please correct the name of the institution. The correct name of the institution in Polish should be: "Polska Akademia Nauk Ogród Botaniczny – Centrum Zachowania Różnorodności Biologicznej w Powsinie" Warszawa, PL.

webpage pl: https://ogrod-powsin.pl/
webpage eng: https://ogrod-powsin.pl/en/

Update: change.name==Polish Academy of Sciences Botanical Garden – Center for Biological Diversity Conservation in Powsin; replace.labels==Polska Akademia Nauk Ogród Botaniczny – Centrum Zachowania Różnorodności Biologicznej w Powsinie*Polish; replace.links==https://ogrod-powsin.pl/;

**Comment by nlundvick** [comment]
Per website (EN and PL) update names to "Polish Academy of Sciences Botanical Garden – Center for Biological Diversity Conservation in Powsin" and "Polska Akademia Nauk Ogród Botaniczny – Centrum Zachowania Różnorodności Biologicznej w Powsinie"

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
