### ISSUE TITLE
Add a new organization to ROR: 
 
International Scientific Network (ISNet)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#355]
Summary of request: Add a new organization to ROR

Name of organization: International Scientific Network
Website: https://isnet.ir
Link to publications: https://ijie.ir
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID:
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation:
Aliases: ISNet
Related organizations: 
City: Tehran
Country: Iran
Geonames ID: 112931
Year established: 2021
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by arthurpsmith** [comment]
This is a new publisher based in Tehran (website says it started up in 2021). It has at least one journal that has published some articles, which is what they link. I believe this probably doesn't qualify given that we are not planning to create ROR id's for all small publishers. However we could wait and see on this. Note the Wikidata ID mentioned has been deleted due to insufficient information.

**Comment by nlundvick** [comment]
I concur with @arthurpsmith - given the newness and and small size of this publishing organization, recommend placing the request on hold

**Comment by adambuttrick** [comment]
Situation is unchanged, although they appear to have published a few more articles. Need to make a determination about whether they are in scope.

**Comment by adambuttrick** [comment]
In scope, per the small publisher use case discussed in the curation team meeting on 2022/06/07.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/032ct1x19 in release v1.3.
