### ISSUE TITLE
Modify the information in an existing ROR record: 
Angelus Silesius University of Applied Sciences in Wałbrzych https://ror.org/04qw9bn98


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#356]
Summary of request: Modify the information in an existing ROR record

Name of organization: Angelus Silesius University of Applied Sciences in Wałbrzych
ROR ID: https://ror.org/04qw9bn98
Which part of the record needs to be changed? Primary name, Organization website
Description of change: Dear Sir/ Madame
On 1 October my university changed its name. The old name is Angelus Silesius University of Applied Sciences in Wałbrzych (Państwowa Wyższa Szkoła Zawodowa im. Angelusa Silesiusa w Wałbrzychu), the new name is Angelus Silesius State University (Państwowa Uczelnia Angelusa Silesiusa). 

We also changed our website https://puas.pl/.

Can you change it in your base?

Update: change.name==Angelus Silesius State University; replace.labels==Państwowa Uczelnia Angelusa Silesiusa*Polish; replace.acronyms==PUAS; add.links==https://puas.pl/; add.wikipedia_url==https://pl.wikipedia.org/wiki/Państwowa_Uczelnia_Angelusa_Silesiusa; add.Wikidata==Q11815224;

**Comment by arthurpsmith** [comment]
I confirm the old website redirects to the new one, and the name has been changed to the name they state here (English and Polish).

Also there is a wikipedia page (Polish) which we should add:
https://pl.wikipedia.org/wiki/Państwowa_Uczelnia_Angelusa_Silesiusa
and Wikidata ID:
https://www.wikidata.org/wiki/Q11815224

So changes that should be made are:
Primary label: Angelus Silesius State University
Label in Polish: Państwowa Uczelnia Angelusa Silesiusa
Also acronym should be changed to PUAS
Current primary and Polish names should be moved to alternate names.
Website: https://puas.pl/
Wikipedia and Wikidata links as above.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
