### ISSUE TITLE
Add a new organization to ROR: 
 
Azimuth Labs

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#357]
Summary of request: Add a new organization to ROR

Name of organization: Azimuth Labs
Website: https://azimuthlabs.io
Link to publications: https://doi.org/10.1177/1757913919897943
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: NA
Acronym/abbreviation: NA
Related organizations: NA
City: Jersey City
Country: United States
Year established: 2018
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets
Other information about this request:

**Comment by nlundvick** [comment]
This is a relatively new consulting firm (2018) with one related publication. Website does not provide much information, there is no link to organizational structure, "About Us", history, etc. Propose moving to "Hold for later" to see if there ends up being more affiliation use.

**Comment by arthurpsmith** [comment]
I've never heard of an anthropology  consultant  before, that's interesting! But it appears  from a search for publications  there is just one person using this affiliation -  "Matt Artz". There do seem  to be maybe a half-dozen papers by him with this affiliation (from Google Scholar) but I agree this isn't sufficient to justify a ROR id. Let's revisit a year or two down the road to  see if there's more info that can be found or it's clearly more than just one person.

**Comment by adambuttrick** [comment]
Continues to be a one-person org, so declining as out of scope.
