### ISSUE TITLE
Add a new organization to ROR: 
 
Saudi Arabia Ministry of Sports

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#358]
Summary of request: Add a new organization to ROR

Name of organization: Ministry of Sports
Website: https://www.mos.gov.sa/
Link to publications: Internal NIHR/Health Research Authority application documents
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://en.wikipedia.org/wiki/Ministry_of_Sports_(Saudi_Arabia)
Wikidata ID: https://www.wikidata.org/wiki/Q10966946
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: not known
Acronym/abbreviation: not known
Related organizations: 
City: Riyadh
Country: Saudi Arabia
Year established:  1974
Geonames ID: 108410
How will a ROR ID for this organization be used? To acknowledge research funders
Other information about this request:

**Comment by arthurpsmith** [comment]
Does not appear to be used as an affiliation, but it is referenced in a number of research articles (via Google Scholar). They mention relevance as a funder but they don't seem to have a Crossref Funder entry. We do have a number of other national sports-related ministries in ROR though, so maybe this should have an ID; I guess given all of the above I'd lean toward yes it should have an ID.

**Comment by nlundvick** [comment]
Concur with @arthurpsmith - This is an edge case considering no affiliation use and no evidence of funding scholarly research (I found no publications identifying this organization as a funding agency in the Web of Science). However, considering this organization would like a ROR ID to be acknowledged as a research funder and similar government organizations exist in ROR we can assign a ROR ID.

**Comment by adambuttrick** [comment]
Approving per the comments here. Updated name to "Ministry of Sports," as is used in the site's branding and copyright statement.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/036dczj04 in release v1.0.
