### ISSUE TITLE
Modify the information in an existing ROR record: Leibniz Institute of European History https://ror.org/059dyrr28

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#360]
Summary of request: Modify the information in an existing ROR record

Name of organization: Leibniz Institute of European History
ROR ID: https://ror.org/059dyrr28
Which part of the record needs to be changed? Other IDs for the organization
Description of change: please add isni https://isni.org/isni/0000000405618205 : this is the same institute, founded in 1950, became a member of the leibniz-gemeinschaft in 2012, and since then uses the prefix leibniz- with its name

Other information about this request: https://isni.org/isni/0000000405618205 and https://isni.org/isni/0000000494574274 describe one institute and only reflect an addition the the institutional name 

Update: replace.ISNI==0000 0004 9457 4274; add.ISNI==0000 0004 0561 8205;

**Comment by MSpenger** [comment]
Additional ISNI should be added:

`external_ids":{"ISNI":{"preferred":null,"all":["0000 0004 0561 8205"]},`

**Comment by arthurpsmith** [comment]
Actually, the current ISNI we have for this - http://isni.org/isni/0000000119314040 - already redirects to the one they request (https://isni.org/isni/0000000405618205). The other ID mentioned - https://isni.org/isni/0000000494574274 -has the new name so I think it should be preferred. So the change should be:
*  Remove ISNI  http://isni.org/isni/0000000119314040
* Add https://isni.org/isni/0000000494574274 as preferred ISNI id
* Add https://isni.org/isni/0000000405618205 as an additional ISNI (historical).

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
