### ISSUE TITLE
Modify the information in an existing ROR record: 
University of Salzburg https://ror.org/05gs8cd61


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#361]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Salzburg
ROR ID: https://ror.org/05gs8cd61
Which part of the record needs to be changed? Organization website
Description of change: Please update the organization website address to: www.plus.ac.at/

Update: replace.links==https://www.plus.ac.at/;

**Comment by MSpenger** [comment]
Link to website needs to be updated as current link is not working:

`"links":["www.plus.ac.at/"]`

**Comment by arthurpsmith** [comment]
Or  https://www.plus.ac.at -  yes, we should  change this.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
