### ISSUE TITLE
Modify the information in an existing ROR record: 
Tula Foundation https://ror.org/0029jxk29


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#362]
Summary of request: Modify the information in an existing ROR record

Name of organization: Tula Foundation
ROR ID: https://ror.org/0029jxk29
Which part of the record needs to be changed? Other IDs for the organization
Description of change: I would like to have the CrossRef Funder ID for the Tula Foundation added to the Tula Foundation ROR. The CrossRef Funder ID is https://doi.org/10.13039/100014446

Update:Delete.Wikidata==Q5640294; replace.FundRef==100014446;

**Comment by arthurpsmith** [comment]
Yes, this is the CrossRef Funder ID for this foundation, this change should be made.

One other change we ought to make is to remove Wikidata ID Q5640294 from this record; that is the ID for Hakai Institute, not Tula Foundation. Unless we want this ROR id to represent both organizations. The other Wikidata ID on this one is correct.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
