### ISSUE TITLE
Modify the information in an existing ROR record: 
German Institute for International and Security Affairs SWP, Stiftung Wissenschaft und Politik  https://ror.org/05frkc804


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#363]
Summary of request: Modify the information in an existing ROR record

Name of organization: German Institute for International and Security Affairs SWP, Stiftung Wissenschaft und Politik 
ROR ID: https://ror.org/05frkc804
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: Please change the present record to the following: Stiftung Wissenschaft und Politik (SWP), German Institute for International and Security Affairs (primary name in German); organization website: https://www.swp-berlin.org/

Update: change.name==Stiftung Wissenschaft und Politik, German Institute for International and Security Affairs; replace.labels==Stiftung Wissenschaft und Politik, Deutsches Institut für Internationale Politik und Sicherheit*German;

**Comment by MSpenger** [comment]
New name seems to be the corporate wording for the institute and needs to be changed:

`"name":"Stiftung Wissenschaft und Politik (SWP), German Institute for International and Security Affairs"`

Old name could be added as alias:

`"aliases":["German Institute for International and Security Affairs"]`

Link is not working anymore. Suggested change:

`"links":["https://www.swp-berlin.org/"]`

**Comment by arthurpsmith** [comment]
Yes the website link  should be trimmed as suggested.

However, I don't understand quite what is being proposed regarding labels. From their website, the German name of this institute appears now to be:
"Stiftung Wissenschaft und Politik
Deutsches Institut für Internationale Politik und Sicherheit"
(from their Contact page, and also the header on every page)

However the *English* page lists the name they seem to  be requesting, so perhaps this is the official English name?:
"Stiftung Wissenschaft und Politik
German Institute for International and Security Affairs"
SWP is an acronym so  I don't think should be part of the main label at all.

Therefore I believe we should change:
* Primary label: "Stiftung Wissenschaft und Politik, German Institute for International and Security Affairs"
* Label  in German: "Stiftung Wissenschaft und Politik, Deutsches Institut für Internationale Politik und Sicherheit"
and leave the acronym as it is.

@MSpenger do you agree?

**Comment by adambuttrick** [comment]
Giving this a second review: I concur with Arthur's analysis. English and German name forms appear as such on their site, contact information, and copyright statements, so we should use this form.

**Comment by MSpenger** [comment]
I also agree with @arthurpsmith and @adambuttrick .

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
