### ISSUE TITLE
Modify the information in an existing ROR record: 
Universität der Bundeswehr München https://ror.org/05kkv3f82


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#364]
Summary of request: Modify the information in an existing ROR record

Name of organization: Universität der Bundeswehr München
ROR ID: https://ror.org/05kkv3f82
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: The primary and official name is the german form "Universität der Bundeswehr München" . The English translation is "University of the Bundeswehr Munich"

**Final decision per curator discussion (MG):**
- Change primary name to `Universität der Bundeswehr München`
- Add English `en` name: `University of the Bundeswehr Munich`
- Add acronym `UniBw M`

Update: change.name==Universität der Bundeswehr München; replace.labels==University of the Bundeswehr Munich*English; add.acronyms==UniBw M;

**Comment by MSpenger** [comment]
Looks correct. Name change according to corporate wording:
```

"name":"Universität der Bundeswehr München"

"labels":[{"label":"University of the Bundeswehr Munich","iso639":"en"}]
```

**Comment by arthurpsmith** [comment]
I'm ok with this but I'm wondering, don't we have a policy to  prefer the English version of a name if there is an official one? Anyway, we have  plenty  of  German primary names on other organizations  so this is fine.

**Comment by mariagould** [comment]
If the organization has a policy against using the English version of the name as an official name, we would default to the original language. I'm not sure of the situation in this case. I'm also wondering about the English version of the name itself: would it be "University of the Bundeswehr Munich" or "University of the Federal Armed Forces Munich"?

**Comment by arthurpsmith** [comment]
The English web page of the university - https://www.unibw.de/home-en - uses the German name - "Universität der Bundeswehr München" everywhere. Although they also have an acronym version they use too: "UniBw M" which it would probably be good for ROR to add. So maybe we should just drop this English label altogether? It's not clear from the request that the university was actually asking us to use their "translation" rather than just telling us a translation??

**Comment by mariagould** [comment]
I agree we should add the German acronym. As to dropping the English entirely, I would err on the side of including an English version. @MSpenger do you have any insights as to which English version of the name should be used ( "University of the Bundeswehr Munich" or "University of the Federal Armed Forces Munich") or whether it would be best to omit an English version altogether?

**Comment by MSpenger** [comment]
Also +1 for the acronym.  If an English name should be added, I would stick to "Bundeswehr University Munich" as it seems to be the most used English version and is also used in Wikidata: https://www.wikidata.org/wiki/Q283099

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
