### ISSUE TITLE
Add a new organization to ROR: Fluor Marine Propulsion

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#3663]
Summary of request: Add a new organization to ROR

Name of organization: Fluor Marine Propulsion (United States)
Website: 
Link to publications: 
Organization type: Company
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: Fluor Marine Propulsion
Labels: 
Acronym/abbreviation: 
Related organizations: https://ror.org/02885vs25 (parent)  
City: Arlington, VA
Country: United States
Geonames ID: 4744709
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: Part of #3616

**Comment by adambuttrick** [comment]
Subsidiary of https://ror.org/02885vs25. Has leading affiliation usage for labs that warrant demarcation from parent. In addition, work with US government likely requires this distinction. Affiliation usage is fine, so this can be added.

**Comment by arthurpsmith** [comment]
It's based in a distinct location (the main Fluor hq is in Texas) and seems to be listed specifically as an affiliation on its own, not as part of Fluor.
However it seems odd that it doesn't have its own website. Also the "year established" claim of 1912 disagrees with what I've seen elsewhere where it seems to be just a few years old.
So the case here is not strong. However given the affiliation usage and contract work I guess this is ok to add to ROR. I think the website and "year established" metadata in the request should not be used; if better values can be found use those.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/036x93b86 in release v1.28.
