### ISSUE TITLE
Add a new organization to ROR: 
 
Laboratoire d’Informatique Signal et Image de la Côte d’Opale

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#367]
Summary of request: Add a new organization to ROR

Name of organization: Opal Coast Signal and Image Computer Laboratory
Website: https://www-lisic.univ-littoral.fr/
Link to publications: https://hal-ulco.archives-ouvertes.fr/LISIC
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/Q51783321
ISNI ID: https://isni.org/isni/0000000461084463
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation: LISIC
Labels: Laboratoire d’Informatique Signal et Image de la Côte d’Opale*French
Related organizations: University of the Littoral Opal Coast https://ror.org/02gdcg342 (parent)
City: Calais
Country: France
Geonames ID: 3029162
Year established: 2010
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders
Other information about this request:

**Comment by arthurpsmith** [comment]
I added the WIkidata ID. Definitely widely used as an affiliation, but again it seems to be uniformly part of the university - affiliations also include "Université du Littoral Côte d’Opale" as far as I can see. Given that we've added ROR ids for other similar French labs, this probably should be included also, but willing to hear other opinions here.

**Comment by adambuttrick** [comment]
Concur with Arthur that this is in scope for ROR. Used as an independent affiliation and the facility produces research with scholars outside the university. Use case follows that of #49 and #386, tracking research outputs from a given facility.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00tm1qp20 in release v1.0.
