### ISSUE TITLE
Add a new organization to ROR: 
 
Shandong Institute of Advanced Technology

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#369]
Summary of request: Add a new organization to ROR

Name of organization: Shandong Institute of Advanced Technology
Website: http://www.sdiat.cn/en/
Link to publications: https://doi.org/10.1103/PhysRevLett.127.021101
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/Q110140441
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 山东高等技术研究院
Acronym/abbreviation: SDIAT
Related organizations: 
City: Jinan
Country: China
Year established: 2019
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by arthurpsmith** [comment]
New Chinese university, heavily involved in research, definitely should be in ROR!

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02n7p8p77 in release v1.0.
