### ISSUE TITLE
Restore ID for Natural History Museum of Denmark 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#370]
From requestor: Error: https://ror.org/040ck2b86 serves a blank page, but should show our institution according to e.g. GBIF (https://registry.gbif.org/institution/68fcaba0-61fe-4e78-a460-4f37654d025d/identifier)

MG notes (sent to requestor for clarification):
It looks as though the ROR ID https://ror.org/040ck2b86 previously referenced the Natural History Museum of Denmark. We have another record in ROR that also refers to a Natural History Museum of Denmark: https://ror.org/0166x0j30. 

Since ROR has previously been synced to GRID, I imagine that what happened is that GRID merged the two records. ROR does not currently support redirected IDs, but this is functionality that we will implement in future. 

I am not sure, however, if it was correct to merge the two IDs referenced above. As far as I can tell, there is a Natural History Museum of Denmark in Aarhus (https://www.naturhistoriskmuseum.dk/, Wikidata Q12328428), and a Natural History Museum of Denmark in Copenhagen (https://snm.ku.dk/, Wikidata Q978464). Are these the same institution, or are they distinct?

**Comment by mariagould** [comment]
Response from organization rep:

`The Natural History Museum in Aarhus and the one in Copenhagen are distinct institutions. The latter is referred to as “Natural History Museum of Denmark” (institution code NHMD), in Danish: “Statens Naturhistoriske Museum” (literally NHM of the State, also reflected in our url: snm.ku.dk), the other simply as “Natural History Museum Aarhus” (institution code NHMA). So the ROR ID https://ror.org/0166x0j30 refers to an entirely different entity (NHMA) leaving us in want of an entry for our own museum (NHMD), previously at: https://ror.org/040ck2b86. The latter ROR ID is what is referred to in the GBIF registry at https://registry.gbif.org/institution/68fcaba0-61fe-4e78-a460-4f37654d025d/identifier`

**Comment by mariagould** [comment]
We will need to restore the old ROR ID https://ror.org/040ck2b86 for Natural History Museum of Denmark. Putting this on hold until we have the functionality in place. We should make a new issue to update the name for https://ror.org/0166x0j30.

**Comment by FedorSteeman** [comment]
Thanks for looking into this. I will be following this thread.

**Comment by adambuttrick** [comment]
https://ror.org/040ck2b86  is part of the GRID removed records set that will soon be restored. Need clarification about current status of the organization, as well as correct names, aliases, and labels.

**Comment by mariagould** [comment]
This is the metadata we used to have in ROR before GRID accidentally merged it to the other museum's record. @FedorSteeman we are finally ready to reinstate this record in ROR so could you please take a look at the last version of the metadata and suggest any updates if anything has changed? Thank you!

`    {
        "id": "https://ror.org/040ck2b86",
        "acronyms": [
            "NHMD"
        ],
        "aliases": [],
        "status": "active",
        "links": [
            "https://snm.ku.dk/"
        ],
        "types": [
            "Archive"
        ],
        "name": "Natural History Museum of Denmark",
        "wikipedia_url": "https://en.wikipedia.org/wiki/Natural_History_Museum_of_Denmark",
        "country": {
            "country_name": "Denmark",
            "country_code": "DK"
        },
        "external_ids": {
            "ISNI": {
                "all": [
                    "0000 0004 0607 1678"
                ],
                "preferred": null
            },
            "GRID": {
                "all": "grid.507616.3",
                "preferred": "grid.507616.3"
            },
            "Wikidata": {
                "all": [
                    "Q978464"
                ],
                "preferred": null
            }
        },
        "labels": [
            {
                "label": "Statens Naturhistoriske Museum",
                "iso639": "da"
            }
        ]
    },`

**Comment by FedorSteeman** [comment]
Thank you, @mariagould 
I'd say that "Statens Naturhistoriske Museum" may be considered an alias, since it's the Danish language name for your institute. 

Otherwise, everything looks as it should. 

Our official website is: https://snm.ku.dk/ 
English version: https://snm.ku.dk/english/

The Natural History Museum of Denmark was established on 1 January 2004 by the merging of four long-standing institutions: the Botanical Garden, the Botanical Museum & Central Library, the Geological Museum, and the Zoological Museum. 

I hope this is sufficient.

**Comment by FedorSteeman** [comment]
Thank you, @mariagould
I'd say that "Statens Naturhistoriske Museum" may be considered an alias, since it's the Danish language name for our institute.

Otherwise, everything looks as it should.

The Natural History Museum of Denmark was established on 1 January 2004 by the merging of four long-standing institutions located in Copenhagen: the Botanical Garden, the Botanical Museum & Central Library, the Geological Museum, and the Zoological Museum.

I hope this is sufficient.

**Comment by mariagould** [comment]
Thank you @FedorSteeman !
