### ISSUE TITLE
Add a new organization to ROR: 
 
National MS Center Melsbroek

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#371]
Summary of request: Add a new organization to ROR

Name of organization: National MS Center Melsbroek
Website: https://mscenter.be/nl
Link to publications: https://nl.wikipedia.org/wiki/Nationaal_Multiple_Sclerose_Centrum
Organization type: Healthcare (A medical care facility such as hospital or clinic. Excludes medical schools, which should be categorized as “Education”)
Wikipedia page: https://nl.wikipedia.org/wiki/Nationaal_Multiple_Sclerose_Centrum
Wikidata ID: https://www.wikidata.org/wiki/Q2356005
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: MS-Kliniek, Nationaal Multiple Sclerose Centrum (Dutch)
Acronym/abbreviation: MS Center
Related organizations: 
City: Steenokkerzeel
Country: Belgium
Year established: 1957
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by arthurpsmith** [comment]
Independent institution conducting research and used in affiliations. Not sure why they linked to wikipedia for their publications, that doesn't say much. I fixed the Wikidata id. An example paper with this affiliation on two authors is: https://doi.org/10.1111/j.1468-1331.2011.03596.x . Anyway, it seems clear this should have a ROR id.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03dgx1q54 in release v1.0.
