### ISSUE TITLE
Modify the information in an existing ROR record: 
Medical University of Silesia https://ror.org/005k7hp45


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#374]
Summary of request: Modify the information in an existing ROR record

Name of organization: Medical University of Silesia
ROR ID: https://ror.org/005k7hp45
Which part of the record needs to be changed? Organization website
Description of change: The organization's website is incorrect. It should be: 
http://www.sum.edu.pl/

Update: replace.links==http://www.sum.edu.pl/;

**Comment by arthurpsmith** [comment]
Our current website link is to a particular faculty within the medical university, so yes we should fix this URL.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
