### ISSUE TITLE
Add a new organization to ROR: 
 
Lakeland University Japan

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#378]
Summary of request: Add a new organization to ROR

Name of organization: Lakeland University Japan
Website: http://luj.lakeland.edu/
Link to publications: https://punctumbooks.com/titles/a-buddha-land-in-this-world-philosophy-utopia-and-radical-buddhism/
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://en.wikipedia.org/wiki/Lakeland_University_Japan_and_VWU_Global
Wikidata ID: https://www.wikidata.org/wiki/Q6478785
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: -
Acronym/abbreviation: LUJ
Related organizations: 
City: Tokyo
Country: Japan
Year established: 1991
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by KellyStathis** [comment]
This is an international campus of Virginia Wesleyan University. We have similar instances already, e.g. NYU Florence: https://ror.org/02pthyn77. Therefore, I think this is in scope for ROR, even though it is not a top-level organization.

The Punctum Books website is down currently but they are a legitimate publisher.

The parent organization, Virginia Wesleyan University, is in ROR under its previous name, Virginia Wesleyan College: https://ror.org/03ken7w58. This record will need to be modified to reflect the name change and new ISNI ID: https://isni.org/isni/0000000494940043.

**Comment by arthurpsmith** [comment]
I added the Wikidata ID also. Yes this seems to be active in research.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03294c124 in release v1.0.
