### ISSUE TITLE
Add a new organization to ROR: 
 
Open Data Commons for Spinal Cord Injury

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#379]
Summary of request: Add a new organization to ROR

Name of organization: Open Data Commons for Spinal Cord Injury
Website: https://odc-sci.org
Link to publications: Some datasets published by the ODC-SCI - DOI:10.34945/F5D01P , DOI:10.34945/F5MG68 , DOI:10.34945/F5R59J , DOI:10.34945/F5NC7X , DOI:10.34945/F5HP4N , DOI:10.34945/F5XW2P , DOI:10.34945/F5S59V , DOI:10.34945/F56C7W , DOI:10.34945/F5B59T ; Some publications referring to the Open Data Commons - DOI:10.1089/neu.2019.6674 , DOI:10.1016/j.expneurol.2017.05.012 , DOI:10.1007/s12021-021-09533-8 , DOI:10.1007/s12021-020-09498-0
Organization type: Other (Use this category for any organization that does not fit the categories above)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: N/A
Acronym/abbreviation: ODC-SCI
Related organizations: https://ror.org/0168r3w48 (related), https://ror.org/043mz5j54 (related), https://ror.org/0160cpw27 (related)
City: ODC-SCI is hosted through UCSD (La Jolla, CA)
Country: United States
Year established: 2017
How will a ROR ID for this organization be used? To identify affiliations for datasets, To be integrated in a scholarly publishing system, ROR ID for integration with DataCite
Other information about this request: Description of Repository: The spinal cord injury (SCI) community created the ODC-SCI to mitigate dark data in SCI research. The ODC-SCI also aims to increase transparency with individual-level data, enhance collaboration, facilitate advanced analytics, and conform to increasing mandates by funders and publishers to make data accessible. Members of the ODC-SCI have access to a private digital lab space managed by the PI or multi-PIs for dataset storage and sharing. The PIs can share their labs’ datasets with the registered members of the ODC-SCI community and make their datasets public and citable. The ODC-SCI implements stewardship principles that scientific data be made FAIR (Findable, Accessible, Interoperable and Reusable) and has been widely adopted by the international SCI research community.

**Comment by KellyStathis** [comment]
This is a data repository for spinal cord injury research. Data repositories are in scope for ROR if they are actively publishing/disseminating research, which is the case for ODC-SCI. It is a collaborative effort between UC San Francisco and the University of Alberta: https://www.ualberta.ca/rehabilitation/news-and-events/news/2019/august/first-global-open-data-commons-for-preclinical-spinal-cord-injury-research-will-be-a-game-changer.html. The submission also indicates it is hosted at UCSD. However, I think it is sufficiently standalone that it is in scope for ROR on its own, with these universities as related organizations.

**Comment by arthurpsmith** [comment]
Yes, this one makes sense to me, let's add it to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/027790w81 in release v1.0.
