### ISSUE TITLE
Add a new organization to ROR:  Pacific Centre for Isotopic and Geochemical Research

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#38]
Summary of request: Add a new organization to ROR

Name of organization to be added | Pacific Centre for Isotopic and Geochemical Research

Organization website | https://pcigr.eos.ubc.ca/

Briefly explain why you are requesting a ROR ID for this organization and how the ROR ID will be used. | I see having a ROR as an excellent means of highlighting all research output including data sets, journal articles, and dissertations. Currently research data sets are scattered across a number of research data repositories including Pangaea, Zenodo, EarthChem/IEDA and Dataverse.

Provide DOI(s) or links for research associated with this organization, such as published articles that include the organization's name as an affiliation. If DOIs or links are not available, describe the research-related activities of this organization. | isotopic geochemistry

Other relevant metadata about the organization (e.g., name variants in other languages, related records in ROR, links to external records such as Wikidata) | pcigr

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01nzphv03 in release v1.0.
