### ISSUE TITLE
Add a new organization to ROR: 
 
Institute of Social Sciences and Humanities – Skopje

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#380]
Summary of request: Add a new organization to ROR

Name of organization: Institute of Social Sciences and Humanities – Skopje
Website: https://www.isshs.edu.mk/
Link to publications: https://punctumbooks.com/titles/after-the-speculative-turn-realism-philosophy-and-feminism/
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: Q74435207
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Институтот за општествени и хуманистички науки – Скопје
Acronym/abbreviation: ISSHS
Related organizations: 
City: Skopje
Country: North Macedonia
Year established: 
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by nlundvick** [comment]
Added Wikidata ID

**Comment by nlundvick** [comment]
Established research institution that produces scholarly publications, funds research, and is used as an affiliation. Recommend adding to ROR.

**Comment by arthurpsmith** [comment]
Yes, this seems legitimate to me also. Let's add to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03fktew82 in release v1.0.
