### ISSUE TITLE
Add a new organization to ROR: 
 
Universidad Villanueva

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#382]
Summary of request: Add a new organization to ROR

Name of organization: Universidad Villanueva
Website: https://www.villanueva.edu/
Link to publications: 10.30828/real/2021.1.8
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://es.wikipedia.org/wiki/Universidad_Villanueva
Wikidata ID: https://www.wikidata.org/wiki/Q63226588
ISNI ID: https://isni.org/0000000505070582
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Universidad Internacional Villanueva / Centro Universitario Villanueva / Villanueva University
Acronym/abbreviation: UV
Related organizations: Centro Universitario Villanueva
City: Madrid
Country: España
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by cfuentemo** [comment]
Buenos días, 

Solo quería saber cuándo se revisará el registro que he solicitado para la Universidad Villanueva y también comentar que tenemos ya el identificador ISNI que es: 0000 0005 0507 0582, por si se puede añadir al registro solicitado. 

Muchas gracias
Carmen

**Comment by mariagould** [comment]
Hola @cfuentemo gracias por avisarnos del identificador ISNI. Lo voy a incluir en los metadatos que salen arriba en el ticket. 

Su solicitud todavía está por revisar. El equipo va a revisarla en las semanas que vienen. Gracias por su paciencia.

**Comment by cfuentemo** [comment]
Muchas gracias, espero que me avisen cuando esté ya disponible en la plataforma. 

Un cordial saludo 
Carmen

**Comment by cfuentemo** [comment]
Hola de nuevo, 

Si es posible me gustaría que también se añadiera en nuestro perfil el Ringgold ID que es: 38807 y añadir otro nombre de la Universidad, como nombre alternativo: Villanueva University. 

Muchas gracias y un cordial saludo
Carmen

**Comment by arthurpsmith** [comment]
Responding to @cfuentemo - I don't think we can add Ringgold ID's in ROR, but it could be linked perhaps by adding that to the Wikidata record. I did add the English name you suggest to the list of "other names".

In general - this is a newly established independent private university in Spain, but it developed over a number of years previously through a link with the Complutense University of Madrid. It has some level of research activity and use as an affiliation (Google Scholar finds many papers with this). So it certainly seems to me to qualify for inclusion in ROR.

**Comment by cfuentemo** [comment]
Muchas gracias por la respuesta y por añadir el nombre en inglés, tenemos en cuanta lo que comenta. 

Un cordial saludo

Carmen

**Comment by cfuentemo** [comment]
Buenos días, 

Me gustaría saber cuándo se incluirá nuestra universidad en ROR. 

Muchas gracias
Carmen

**Comment by mariagould** [comment]
Hola @cfuentemo no se sabe todavía. El estado del ticket cambiará cuando se haya preparado la actualización. Gracias por su paciencia.

**Comment by cfuentemo** [comment]
Buenos días, 

Me gustaría saber si será posible incluir la Universidad Villanueva en ROR y cuándo estará disponible.

Muchas gracias
Carmen

**Comment by mariagould** [comment]
Hola @cfuentemo la actualización del registro sigue en curso. El estado de este ticket cambiará y se notará el ROR ID cuando todo esté finalizado. Gracias.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02fn69884 in release v1.0.

**Comment by cfuentemo** [comment]
Muchas gracias,

Disculpen las molestias, solo quería que se eliminara en el registro el nombre abreviado de la universidad: UV, 

Muchas gracias
Carmen

**Comment by mariagould** [comment]
Hola @cfuentemo el nombre abreviado se quitará en la próxima actualización del registro.

**Comment by cfuentemo** [comment]
Muchas gracias y disculpa las molestias
Carmen
