### ISSUE TITLE
Modify the information in an existing ROR record: Ministerium für Innovation, Wissenschaft und Forschung d. Landes Nordrhein-Westfalen https://ror.org/04n00c532

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3828]
Summary of request: Modify the information in an existing ROR record

Name of organization: Ministerium für Innovation, Wissenschaft und Forschung d. Landes Nordrhein-Westfalen
ROR ID: https://ror.org/04n00c532
Which part of the record needs to be changed? Name, Aliases, External IDs
Description of change: (1) Update name to Ministerium für Kultur und Wissenschaft des Landes Nordrhein-Westfalen; (2) Add alias Ministerium für Innovation, Wissenschaft und Forschung des Landes Nordrhein-Westfalen; (3) Add two Funder IDs: [501100014690](https://doi.org/10.13039/501100014690) and [501100009591](http://doi.org/10.13039/501100009591)

Note: Identified as part of ongoing Funder Registry reconciliation work

Update: change.name==Ministerium für Kultur und Wissenschaft des Landes Nordrhein-Westfalen; add.aliases==Ministerium für Innovation, Wissenschaft und Forschung d. Landes Nordrhein-Westfalen; add.FundRef==501100014690; add.FundRef==501100009591;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
