### ISSUE TITLE
Add a new organization to ROR: 
 
Sektion Medienpädagogik der Deutschen Gesellschaft für Erziehungswissenschaft (DGfE)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#383]
Summary of request: Add a new organization to ROR

Name of organization: Sektion Medienpädagogik der Deutschen Gesellschaft für Erziehungswissenschaft (DGfE)
Website: https://www.dgfe.de/sektionen-kommissionen-ag/sektion-12-medienpaedagogik
Link to publications: https://doi.org/10.21240/mpaed/00/2021.11.29.X, https://doi.org/10.21240/mpaed/00/2021.10.27.X, https://doi.org/10.21240/mpaed/00/2020.07.16.X
Organization type: Other (Use this category for any organization that does not fit the categories above)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Sektion Medienpädagogik
Acronym/abbreviation:
Aliases: Sektion Medienpädagogik
Related organizations: Parent - Deutsche Gesellschaft für Erziehungswissenschaf #453 
City: Not applicable
Country: Germany, Austria, Switzerland
Year established: 1999
How will a ROR ID for this organization be used? To identify affiliations for research publications, To be integrated in a scholarly publishing system
Other information about this request: This affiliation can best described as scientific society (learned society)

**Comment by MSpenger** [comment]
A new entry for ROR is suggested. The umbrella organisation does not have a ROR yet: Deutsche Gesellschaft für Erziehungswissenschaft [DGfE] (https://www.wikidata.org/wiki/Q1202838, https://isni.oclc.org/xslt/DB=1.2/CMD?ACT=SRCH&IKT=8006&TRM=ISN%3A0000%200001%201092%207326).

Some other sections are already linked to the ISNI above. Here is an overview of the organisation of the DGfE Divisions: https://www.dgfe.de/en/divisions-subdivisions

It would make sense to add a ROR entry for the DGfE first and then assess this request again.

**Comment by carlyrobinson** [comment]
Agree with @MSpenger that the higher level organization should be added to ROR. It is being used as an affiliation.

**Comment by adambuttrick** [comment]
Created and approved record for parent organization in #453, per these comments. Moving back to needs discussion for further consideration.

**Comment by adambuttrick** [comment]
Out of scope per curator discussion on 04/05/2022.
