### ISSUE TITLE
Add a new organization to ROR: Training Centre in Communication

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3831]
Summary of request: Add a new organization to ROR

Name of organization: Training Centre in Communication
Website: https://www.tcc-africa.org
Link to publications: https://hal.science/hal-03480952, https://doi.org/10.5281/zenodo.3732274
Organization type: Nonprofit
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: TCC Africa
Acronym/abbreviation:
Related organizations: 
City: Nairobi
Country: Kenya
Geonames ID: 184745
Year established: 2006
How will a ROR ID for this organization be used? 
Other information about this request: TCC Africa is the first African-based training centre to teach effective communication skills to scientists. TCC Africa is an [award winning ](https://www.tcc-africa.org/ten-hot-topics-around-scholarly-publishing/) Trust, established as a non-profit entity in 2006 and is registered in Kenya. TCC Africa provides  capacity support in improving researchers  output and visibility through training in [scholarly](https://www.tcc-africa.org/courses/) and [science communication](https://www.tcc-africa.org/course/science-communication-and-communicating-to-non-scientist/).

**Comment by mariagould** [comment]
I'm suggesting we add TCC Africa as they are heavily involved in supporting various research activities across the African continent.

**Comment by adambuttrick** [comment]
Solid affiliation usage. Should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00dzfmv17 in release v1.27.
