### ISSUE TITLE
Modify the information in an existing ROR record: 
Landesamt für Bergbau, Energie und Geologie https://ror.org/0291s1e82


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#384]
Summary of request: Modify the information in an existing ROR record

Name of organization: Landesamt für Bergbau, Energie und Geologie
ROR ID: https://ror.org/0291s1e82
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Other IDs for the organization
Description of change: The german name is "Landesamt für Bergbau, Energie und Geologie", and the english name is "State authority for Mining, Energy and Geology", see https://www.lbeg.niedersachsen.de/download/1070/The_LBEG_presents_itself.pdf . Wikidata object is Q1448021.

Update: change.name==Landesamt für Bergbau, Energie und Geologie; add.aliases==State authority for Mining, Energy and Geology; add.Wikidata==Q1448021;

**Comment by MSpenger** [comment]
Name should be adjusted (comma is missing) and English Version can be added:

```
"name":"Landesamt für Bergbau, Energie und Geologie"

"aliases":["State authority for Mining, Energy and Geology"]
```

**Comment by arthurpsmith** [comment]
Agreed.

**Comment by tilmanb** [comment]
What about the wikidata ID?

**Comment by arthurpsmith** [comment]
Good point - here's a wikipedia page and wikidata id for this:
Wikipedia: https://de.wikipedia.org/wiki/Landesamt_für_Bergbau,_Energie_und_Geologie
Wikidata: Q1448021

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
