### ISSUE TITLE
Modify the information in an existing ROR record: Natural History Museum

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#385]
Summary of request: Modify the information in an existing ROR record

Name of organization: Natural History Museum
ROR ID: https://ror.org/0166x0j30
Which part of the record needs to be changed? Name, label
Description of change: GRID mistakenly merged two records for two different museums with similar names. See full description in #370. For the present record https://ror.org/0166x0j30 we should update the names for clarity and to help differentiate the two. 

Primary name: Natural History Museum Aarhus
Label (`dk`): Naturhistorisk Museum Aarhus

Update: change.name==Natural History Museum Aarhus; delete.labels==Naturhistorisk Museum; add.labels==Naturhistorisk Museum Aarhus*Danish;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
