### ISSUE TITLE
Add a new organization to ROR: 
 
CSIRO BioFoundry

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#386]
Summary of request: Add a new organization to ROR
Name of organization: CSIRO BioFoundry
Website: http://www.csiro.au/BioFoundry
Link to publications: None yet
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation:
Related organizations: CSIRO https://ror.org/03qn8fb07 (parent)
City: Brisbane
Country: Australia
Geonames ID: 2174003
Year established: 
How will a ROR ID for this organization be used? To acknowledge a research facility
Other information about this request:

**Comment by arthurpsmith** [comment]
This appears to be new; it is one of 84 CSIRO "labs and facilities" listed here: https://www.csiro.au/en/work-with-us/use-our-labs-facilities

I don't think we want to add all 84 to ROR. I spot-checked a handful of them and could find none currently in ROR, though we may have some of them. I think this one is technically a subsidiary of "CSIRO Land & Water" - https://ror.org/057xz1h85 - but I don't know if that would be included in any affiliation for a researcher at this facility. Anyway, given they have no publications as yet I recommend we either put this on hold until there's more research output associated with it, or probably better to just say no as it is not a top-level research org which ROR is focused on right now.

**Comment by adambuttrick** [comment]
Spoke with CSIRO staff on a community call and they need this approved to begin a process of acknowledging funding and research outputs.

**Comment by KellyStathis** [comment]
I agree that keeping the CSIRO entries in ROR at the level of the [business units](https://www.csiro.au/en/about/people/business-units) like Land and Water makes sense, rather than adding all 84 labs.

Leaving this in second review as I'm not sure about making the final call to decline.

**Comment by alslib** [comment]
Hi folks, I would appreciate a reconsideration of this submission please.
The use case is the acknowledgement of the use of a facility. Facilities in CSIRO are "managed" by a specific business unit, but may be used by anyone in the organisation, or researchers external to CSIRO.
We note the inclusion of a ROR in the Acknowledgements section of this journal article, https://doi.org/10.1093/mnras/stab1823, to acknowledge the use of National Energy Research Scientific Computing Center; this is a use case for facilities, "research resources" in ORCID's language, with the potential to push metadata of successful proposals to a researcher's ORCID record, and to support the tracking of publications that acknowledge the use of such facilities.
Regards
Anne Stevenson, CSIRO Research Data Services

**Comment by mpfl** [comment]
Hello! I'm not on the review team but the Australian Research Data Commons is watching this thread with great interest. I'm not sure if Australia has a strange model, but we have quite a few "national facilities" that are administered as sub-units or sub-sub-units of other organisations. These national facilities are often funded at a national and/or state level, but are administered through existing organisations.

Despite the way they are administered, they have their own identity and can be used by any researcher. Reiterating @alslib's point, the particular use case here is around tracking the acknowledgements/citations of those facilities and all of the instruments/services belonging to that facility.

An example is the John de Laeter Centre (JdLC) here Perth, Western Australia. The JdLC reports through Curtin University's Faculty of Science and Engineering, but the JdLC itself is a national-scale facility that attracts state and national funding to house instruments and provide services to all researchers, not just those at Curtin University. It does some of its own original research, but most research undertaken using its instruments is undertaken by researchers _not_ based there.

Reiterating @alslib's point, the use case for ROR in this situation is for acknowledgement and citation of the use of the facilities. Directors of these facilities would love to know much research is published as a result of the use of those facilities, especially when applying for future funding.

**Comment by adambuttrick** [comment]
@mpfl Your insights are always appreciated here! Including here for additional context that we have precedents in ROR for similar organizations, such as the Australian National Imaging Facility (https://ror.org/01kdbsa35) and AuScope (https://ror.org/04s1m4564). See also the discussion on Microscopy Australia in issue #49.

**Comment by adambuttrick** [comment]
Discussed this further with @mariagould: we are recommending inclusion in ROR, given the additional context provided by CSIRO and ARDC, as well as following the prior decision-making process for similar use cases, (e.g. #49). We will discuss this use case more generally in our next curator meeting, and continue working with groups in Australia to make sure they have adequate representation. Thank you once again, @mpfl and @alslib, for your feedback and concern for these issues!

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02jfhsn35 in release v1.0.
