### ISSUE TITLE
Modify the information in an existing ROR record:

### ISSUE THREAD

**Issue by julesteindel** [ror-community/ror-updates#3867]
Summary of request: Modify the information in an existing ROR record

Name of organization: Leibniz Institute of Freshwater Ecology and Inland Fisheries
ROR ID: https://ror.org/01nftxb06
Which part of the record needs to be changed? Add Wikidata and coordinate location
Description of change:
Wikidata: Q1813732
See Wikidata: [52°26'58.783"N, 13°38'51.187"E](https://geohack.toolforge.org/geohack.php?params=52.449662_N_13.647552_E_globe:earth&language=en)

**Comment by adambuttrick** [comment]
Latitude and longitude values are derived from the Geonames location record and cannot be set manually.
