### ISSUE TITLE
Modify the information in an existing ROR record: 
University of the French west indies  https://ror.org/02ryfmr77


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#387]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of the French west indies
ROR ID:  https://ror.org/02ryfmr77
Which part of the record needs to be changed? Something else
Description of change: The ISNI code recorded is no longer used (0000000121973053). The right one is : 0000000405935227 (https://isni.ringgold.com/search/)

Update: change.name==University of the French Antilles; add.aliases==University of the French West Indies; add.aliases==University of the French West Indies and Guiana; add.Wikidata==Q16682075; add.ISNI==0000 0004 0593 5227; add.ISNI==0000 0004 9471 2972;

**Comment by adambuttrick** [comment]
ISNI change is correct. Primary name needs to be changed as well. Should be, "University of the French West Indies and Guiana," per the ISNI(https://isni.org/isni/0000000405935227) and Wikidata records

**Comment by adambuttrick** [comment]
Unfortunately, this request isn't as simple as an ISNI change. The current URL in the ROR record points to the University of the French Antilles. The Wikidata ID (https://www.wikidata.org/wiki/Q829169) points at the University of the French West Indies and Guiana, which appears to have been split into to different entities in 2015 (https://en.wikipedia.org/wiki/University_of_the_French_Antilles). 

So, we need to make a determination if this record represents the historic form of the organization before it split, deprecate it, and create a new record to reflect the University of the French Antilles entry (with the updated ISNI), or pursue some other kind of representation in ROR.

**Comment by adambuttrick** [comment]
Example of predecessor/successor relationship

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
