### ISSUE TITLE
Add a new organization to ROR: 
 
Associação Brasileira de Editores Científicos - ABEC Brasil

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#388]
Summary of request: Add a new organization to ROR

Name of organization: Brazilian Association of Scientific Editors
Website: https://www.abecbrasil.org.br
Link to publications: Yes
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation: 
Labels: Associação Brasileira de Editores Científicos*Portuguese
Aliases: ABEC Brasil
Related organizations: 
City: Botucatu
Country: Brazil
Year established: 1985
Geonames ID: 3469136
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by KellyStathis** [comment]
This organization is a Brazilian association that "brings together individuals and legal entities interested in developing and improving scientific journals; improve communication and dissemination of information; keep the exchange of ideas, the debate of problems and the defense of the common interests of the community" (https://www.abecbrasil.org.br/novo/estatuto/, translation by Google). ABEC Brasil is also a Crossref member/facilitates Crossref membership: https://www.abecbrasil.org.br/novo/2015/09/estabelecido-o-acordo-abeccrossrefibict-para-facilitar-a-atribuicao-de-dois/

I'm not sure which category this falls under within the [Guidance for evaluating common organization types](https://github.com/ror-community/ror-updates/wiki/Curator-Evaluation-Workflow:-New-Records#guidance-for-evaluating-common-organization-types). 

However, there are similar non-profit organizations in ROR, for example the [Council of Science Editors](https://ror.org/007cr8911), which has [partnered with ABEC Brasil](https://www.councilscienceeditors.org/resource-library/cse-publication-certificate-program/cse-publication-certificate-program-for-abec-members/). Based on this, I think ABEC Brasil is in scope for ROR. They are an established organization and closely related to research activities.

**Comment by adambuttrick** [comment]
Agree that this in scope for ROR. Adding ORCID affiliations for additional reference and sticking with it being a non-profit, as that is how the [Council of Science Editors](https://ror.org/007cr8911) is classed.

ORCID affiliation usage: https://orcid.org/0000-0002-0745-5716 ; https://orcid.org/0000-0002-9157-6114 ; https://orcid.org/0000-0002-0951-9189

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02yhdfk86 in release v1.0.
