### ISSUE TITLE
Modify the information in an existing ROR record: 
Herder Institute for Historical Research on East Central Europe https://ror.org/00sngv739


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#389]
Summary of request: Modify the information in an existing ROR record

Name of organization: Herder Institute for Historical Research on East Central Europe
ROR ID: https://ror.org/00sngv739
Which part of the record needs to be changed? Other IDs for the organization
Description of change: ISNI reference is incorrect. It refers to another institute with a similar name. The correct ISNI is this: https://isni.org/isni/0000000121510454

MG Note:
Replace ISNI ID: 0000 0001 2151 0454
Add Wikidata ID: Q870192

Update: replace.ISNI==0000 0001 2151 0454; add.Wikidata==Q870192;

**Comment by MSpenger** [comment]
the ISNI in ROR is incorrect. I agree with the request to change the ISNI to: https://isni.org/isni/0000000121510454

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
