### ISSUE TITLE
Add a new organization to ROR: Poltekkes Kemenkes Kendari

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#39]
Summary of request: Add a new organization to ROR

Name of organization to be added | Poltekkes Kemenkes Kendari

Organization website | https://www.poltekkeskendari.ac.id/

Briefly explain why you are requesting a ROR ID for this organization and how the ROR ID will be used. | We will use the ID to link author affiliation on the published article

Provide DOI(s) or links for research associated with this organization, such as published articles that include the organization's name as an affiliation. If DOIs or links are not available, describe the research-related activities of this organization. | https://doi.org/10.36990/hijp.vi.149

**Comment by carlyrobinson** [comment]
Agree with @arthurpsmith recommendation. Should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02sjhqg84 in release v1.0.
