### ISSUE TITLE
Add a new organization to ROR: 
 
Albanian Academy of Sciences

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#390]
Summary of request: Add a new organization to ROR

Name of organization: Albanian Academy of Sciences
Website: http://akad.gov.al/ash/
Link to publications: https://punctumbooks.com/titles/broken-narrative-the-politics-of-contemporary-art-in-albania/
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://sq.wikipedia.org/wiki/Akademia_e_Shkencave_e_Shqip%C3%ABris%C3%AB
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Akademia e Shkencave e Shqipërisë
Acronym/abbreviation: -
Related organizations: 
City: Tirana
Country: Albania
Year established: 1972
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by adambuttrick** [comment]
This organization is already represented in ROR (https://ror.org/016sx0y50) under the English used on its site, "Academy of Sciences of Albania."

The URL in our metadata no longer resolves, while the supplied does, so I will create an update request to reflect.

**Comment by arthurpsmith** [comment]
Ok! I don't think this needs further discussion - moving to "declined".
