### ISSUE TITLE
Modify the information in an existing ROR record: Ministerio de Ciencia e Innovación https://ror.org/05r0vyz12

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3929]
Summary of request: Modify the information in an existing ROR record

Name of organization: Ministerio de Ciencia e Innovación
ROR ID: https://ror.org/05r0vyz12
Which part of the record needs to be changed? External IDs
Description of change: Funder ID 100014440 is for an older instance of the ministry. It should be added to the record as an additional Funder ID to support reconciliation between the Funder Registry and ROR. 

Update: add.FundRef==100014440;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
