### ISSUE TITLE
Add a new organization to ROR: 
 
Seven Past Nine

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#393]
Summary of request: Add a new organization to ROR

Name of organization: Seven Past Nine
Website: https://sevenpastnine.com
Link to publications: 10.1016/j.tiv.2021.105229
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation: 7P9
Related organizations: 
City: Cerknica
Country: Slovenia
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
Aside from the article provided, I can find no other affiliation usage. The company only lists two members (both as CEOs) on its site. The site features two additional publications, for which "[Seven Past Nine] contributed as main authors," but both of which were authored by one of the CEOs and use a different affiliation (Edelweiss Connect).

**Comment by arthurpsmith** [comment]
Agreed - looks like it will be involved with research, but very minimal so far. On hold sounds good.

**Comment by adambuttrick** [comment]
I'm seeing one new instance of affiliation usage for this:

https://www.sciencedirect.com/science/article/pii/S0887233321001545

This appears to be a two-person organization, so we need to determine whether those should be in scope.

**Comment by adambuttrick** [comment]
In scope per discussion on 2022/07/05. EU Horizon funding and potential third staff member.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/023dg6y22 in release v1.3.
