### ISSUE TITLE
Modify the information in an existing ROR record: The Eric and Wendy Schmidt Fund for Strategic Innovation https://ror.org/014bj2y47

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3930]
Summary of request: Modify the information in an existing ROR record

Name of organization: The Eric and Wendy Schmidt Fund for Strategic Innovation
ROR ID: https://ror.org/014bj2y47
Which part of the record needs to be changed? Name, External IDs, Aliases, Links
Description of change: The following metadata should be updated to support discoverability and Funder Registry reconciliation:

- Change name to "Schmidt Family Foundation"
- Move current name to Aliases
- Add website https://tsffoundation.org/
- Add Funder ID 100016382

Update: change.name==Schmidt Family Foundation; add.aliases==The Eric and Wendy Schmidt Fund for Strategic Innovation; replace.links==https://tsffoundation.org; add.FundRef==100016382;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
