### ISSUE TITLE
Modify the information in an existing ROR record: Florida Museum of Natural History https://ror.org/02pjdv450

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3931]
Summary of request: Modify the information in an existing ROR record

Name of organization: Florida Museum of Natural History
ROR ID: https://ror.org/02pjdv450
Which part of the record needs to be changed? External ID
Description of change: The current Funder ID is for a biodiversity institute associated with the museum. I recommend adding the main Funder ID for the museum to the ROR record and making it the preferred ID. The ID to be added and marked as preferred is 100012310. This will support Funder Registry reconciliation. 

Update: add.FundRef==100012310;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
