### ISSUE TITLE
Modify the information in an existing ROR record: Maryland Department of Natural Resources https://ror.org/01fem2359

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3932]
Summary of request: Modify the information in an existing ROR record

Name of organization: Maryland Department of Natural Resources
ROR ID: https://ror.org/01fem2359
Which part of the record needs to be changed? External ID
Description of change: This record currently has the Funder ID 100004946 which is for "Department of Natural Resources." Looking at the works in Crossref with this Funder ID asserted, it's not clear to me that this ID actually corresponds to the Maryland Department of Natural Resources. I found a different Funder ID that _is_ associated with the Maryland instance: 100015849. I recommend replacing the existing Funder ID with this one. 

Update: replace.FundRef==100015849;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
