### ISSUE TITLE
Modify the information in an existing ROR record: Society for Integrative and Comparative Biology https://ror.org/006qmn341

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3933]
Summary of request: Modify the information in an existing ROR record

Name of organization: Society for Integrative and Comparative Biology
ROR ID: https://ror.org/006qmn341
Which part of the record needs to be changed? Acronyms, External IDs
Description of change:
- Add acronym SICB
- Add Funder ID 100014548 as preferred

Note: This was identified as part of Funder Registry reconciliation. The current Funder ID in the record references an older instance of the org. 

Update: add.acronyms==SICB; add.FundRef==100014548*preferred;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
