### ISSUE TITLE
Modify the information in an existing ROR record: University of Tennessee at Knoxville https://ror.org/020f3ap87

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3934]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Tennessee at Knoxville
ROR ID: https://ror.org/020f3ap87
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 100014455 and mark as preferred. Current Funder ID in record (100008526) is for a subsidiary institute. This was identified as part of Funder Registry reconciliation. 

Update: add.FundRef==100014455*preferred;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
