### ISSUE TITLE
Modify the information in an existing ROR record: Yale Peabody Museum https://ror.org/03db5ay71

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3935]
Summary of request: Modify the information in an existing ROR record

Name of organization: Yale Peabody Museum
ROR ID: https://ror.org/03db5ay71
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 100020596

Update: add.FundRef==100020596;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
