### ISSUE TITLE
Modify the information in an existing ROR record: Association Neurofibromatoses et Recklinghausen https://ror.org/014wjf777

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3937]
Summary of request: Modify the information in an existing ROR record

Name of organization: Association Neurofibromatoses et Recklinghausen
ROR ID: https://ror.org/014wjf777
Which part of the record needs to be changed? External IDs, Links
Description of change: (1) Add Funder ID 501100016394 (2) Update Links to https://www.anrfrance.fr/
Note: Identified as part of Funder Registry reconciliation

Update: add.FundRef==501100016394; replace.links==https://www.anrfrance.fr;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
