### ISSUE TITLE
Modify the information in an existing ROR record: Ministry of the Environment https://ror.org/03rtq6c48

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3938]
Summary of request: Modify the information in an existing ROR record

Name of organization: Ministry of the Environment
ROR ID: https://ror.org/03rtq6c48
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 501100013872

Update: add.FundRef==501100013872;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
