### ISSUE TITLE
Modify the information in an existing ROR record: Delta Waterfowl Foundation https://ror.org/01ezjqh37

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3939]
Summary of request: Modify the information in an existing ROR record

Name of organization: Delta Waterfowl Foundation
ROR ID: https://ror.org/01ezjqh37
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 501100020073

Update: add.FundRef==501100020073;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
