### ISSUE TITLE
Modify the information in an existing ROR record: International Association for Plant Taxonomy https://ror.org/03mz8ps81

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3940]
Summary of request: Modify the information in an existing ROR record

Name of organization: International Association for Plant Taxonomy
ROR ID: https://ror.org/03mz8ps81
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 501100020652

Update: add.FundRef==501100020652;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
