### ISSUE TITLE
Modify the information in an existing ROR record: Université Libre de Bruxelles https://ror.org/01r9htc13

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3941]
Summary of request: Modify the information in an existing ROR record

Name of organization: Université Libre de Bruxelles
ROR ID: https://ror.org/01r9htc13
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 501100010527. ROR record already has Funder ID 501100008367 which appears to be a duplicate. 

Update: add.FundRef==501100010527*preferred;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
