### ISSUE TITLE
Modify the information in an existing ROR record: Dutch Research Council https://ror.org/04jsz6e67

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3942]
Summary of request: Modify the information in an existing ROR record

Name of organization: Dutch Research Council
ROR ID: https://ror.org/04jsz6e67
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 501100013956. This is the earth and life sciences branch of the Dutch Research Council. ROR record already has Funder ID 501100003246 for the parent entity. 

Update: add.FundRef==501100013956;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
