### ISSUE TITLE
Modify the information in an existing ROR record: Allen Institute https://ror.org/03cpe7c52

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3948]
Summary of request: Modify the information in an existing ROR record

Name of organization: Allen Institute
ROR ID: https://ror.org/03cpe7c52
Which part of the record needs to be changed? External IDs
Description of change: Add additional Funder ID 100017023 (Paul G. Allen Frontiers Group) to support Funder Registry reconciliation. ROR record already has Funder ID 100017008 for the main org. 

Update: add.FundRef==100017023;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
