### ISSUE TITLE
Modify the information in an existing ROR record: 
Research Institute for Farm Animal Biology (FBN) https://ror.org/02n5r1g44


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#395]
Summary of request: Modify the information in an existing ROR record

Name of organization: Research Institute for Farm Animal Biology (FBN)
ROR ID: https://ror.org/02n5r1g44
Which part of the record needs to be changed? Primary name, Other IDs for the organization
Description of change: I would like to inform you that the FBN has changed its name:

English
Old: Leibniz Institute for Farm Animal Biology (FBN).
New: Research Institute for Farm Animal Biology (FBN)

German
Old: Leibniz-Institut für Nutztierbiologie (FBN)
New: Forschungsinstitut für Nutztierbiologie (FBN)

Source:
https://www.fbn-dummerstorf.de/service/impressum/
https://www.fbn-dummerstorf.de/en/service/impressum/

Other IDs:
GND (Gemeinsame Normdatei): 16072459-4
Ringgold Organization Identifier: 28415

Update: change.name==Research Institute for Farm Animal Biology (FBN); replace.labels==Forschungsinstitut für Nutztierbiologie (FBN)*German; replace.links==https://www.fbn-dummerstorf.de/;

**Comment by adambuttrick** [comment]
Name changes correspond to those on organization's website and copyright statement.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
