### ISSUE TITLE
Modify the information in an existing ROR record: Department of Education https://ror.org/03a2pqz96

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3951]
Summary of request: Modify the information in an existing ROR record

Name of organization: Department of Education
ROR ID: https://ror.org/03a2pqz96
Which part of the record needs to be changed? Labels, External IDs, Links
Description of change: Update the following metadata:
- Add label Hezkuntza Saila*eu
- Replace link: https://www.euskadi.eus/eusko-jaurlaritza/hezkuntza-saila/
- Add Funder ID 100015866

Update: add.labels==Hezkuntza Saila*eu; replace.links==https://www.euskadi.eus/eusko-jaurlaritza/hezkuntza-saila/; add.FundRef==100015866;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
