### ISSUE TITLE
Modify the information in an existing ROR record: German Center for Integrative Biodiversity Research https://ror.org/01jty7g66

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3952]
Summary of request: Modify the information in an existing ROR record

Name of organization: German Center for Integrative Biodiversity Research
ROR ID: https://ror.org/01jty7g66
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 501100020056

Update: add.FundRef==501100020056;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
