### ISSUE TITLE
Modify the information in an existing ROR record: Universidad de las Americas https://ror.org/0198j4566

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3953]
Summary of request: Modify the information in an existing ROR record

Name of organization: Universidad de las Americas
ROR ID: https://ror.org/0198j4566
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 100021068

Update: add.FundRef==100021068;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
