### ISSUE TITLE
Modify the information in an existing ROR record: Bavarian State Ministry of Education Science and the Arts https://ror.org/01a44gd51

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3954]
Summary of request: Modify the information in an existing ROR record

Name of organization: Bavarian State Ministry of Education Science and the Arts
ROR ID: https://ror.org/01a44gd51
Which part of the record needs to be changed? Name, Labels, Aliases, External IDs, Links
Description of change: Update the following metadata:
- Replace name: Bavarian State Ministry for Science and Art
- Replace label: Bayerisches Staatsministerium für Wissenschaft und Kunst
- Add alias Bayerisches Staatsministerium für Bildung und Kultus, Wissenschaft und Kunst
- Add Funder ID 501100021711
- Replace links: https://www.stmwk.bayern.de/
- 
Update: change.name==Bavarian State Ministry for Science and Art; replace.labels==Bayerisches Staatsministerium für Wissenschaft und Kunst*German; add.aliases==Bayerisches Staatsministerium für Bildung und Kultus, Wissenschaft und Kunst; add.FundRef==501100021711; replace.links==https://www.stmwk.bayern.de;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
