### ISSUE TITLE
Modify the information in an existing ROR record: 
Bundesanstalt für Wasserbau https://ror.org/03z6hnk02


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#396]
Summary of request: Modify the information in an existing ROR record

Name of organization: Bundesanstalt für Wasserbau
ROR ID: https://ror.org/03z6hnk02
Which part of the record needs to be changed? Something else
Description of change: Please add link to Wikipedia: 
https://de.wikipedia.org/wiki/Bundesanstalt_für_Wasserbau

Update: change.wikipedia_url==https://de.wikipedia.org/wiki/Bundesanstalt_für_Wasserbau;

**Comment by adambuttrick** [comment]
Wikipedia entry corresponds to that for the organization and no English-language Wikipedia entry exists.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
