### ISSUE TITLE
Modify the information in an existing ROR record: 
Institut für Zeitgeschichte München-Berlin https://ror.org/008pp7a77


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#397]
Summary of request: Modify the information in an existing ROR record

Name of organization: Institut für Zeitgeschichte München-Berlin
ROR ID: https://ror.org/008pp7a77
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website
Description of change: Please change the primary name from "Institut für Zeitgeschichte" to "Institut für Zeitgeschichte München–Berlin".

Please add the following other names:
- "Leibniz Institute for Contemporary History (IfZ)",
- "Institute for Contemporary History München–Berlin",
- "Institut für Zeitgeschichte (München)",
- "Stiftung zur wissenschaftlichen Erforschung der Zeitgeschichte".

Please change the URL to "https://www.ifz-muenchen.de/".

You may compare the changes with the GND-entry https://d-nb.info/gnd/2014524-X.
We will successively initiate the same changes in GRID, Wikidata and ISNI.

Update: change.name==Institut für Zeitgeschichte München–Berlin; add.labels==Leibniz Institute for Contemporary History (IfZ)*English; add.labels==Institute for Contemporary History München–Berlin*English; add.aliases==Institut für Zeitgeschichte (München); add.aliases==Stiftung zur wissenschaftlichen Erforschung der Zeitgeschichte; replace.links==https://www.ifz-muenchen.de/;

**Comment by adambuttrick** [comment]
Supplied names do correspond to those in the German National Library authority file entry for the organization, so those seem fine as labels. Change to "https" vs "http" makes sense from a privacy/security standpoint and the "http" form redirects there anyway. Copyright statement only uses short form ("Institut für Zeitgeschichte") of name, but "München-Berlin" does appear in their branding and as part of the org URL.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
