### ISSUE TITLE
Modify the information in an existing ROR record: International Medical University https://ror.org/04d4wjw61

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3982]
Summary of request: Modify the information in an existing ROR record

Name of organization: International Medical University
ROR ID: https://ror.org/04d4wjw61
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 501100009381

Update: add.FundRef==501100009381;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
