### ISSUE TITLE
Modify the information in an existing ROR record: 
Northwest German Forest Research Institute https://ror.org/03hpxd290


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#399]
Summary of request: Modify the information in an existing ROR record

Name of organization: Northwest German Forest Research Institute
ROR ID: https://ror.org/03hpxd290
Which part of the record needs to be changed? Primary name
Description of change: it's a german  instiution with a primary german name. Please use "Nordwestdeutsche Forstliche Versuchsanstalt" as primary name and the other names as alternate names.

Other information about this request: We have problems with mixed up names and therefore we would like to emphasize our proper name. Thanks a ton.
Update: change.name==Nordwestdeutsche Forstliche Versuchsanstalt; delete.labels==Nordwestdeutsche Forstliche Versuchsanstalt; add.labels==Northwest German Forest Research Institute*English;

**Comment by MSpenger** [comment]
I agree with the suggested name change. The name "Nordwestdeutsche Forstliche Versuchsanstalt" (already listed under labels) should be used.

**Comment by arthurpsmith** [comment]
This seems fine to me, just swap the primary name and the German label. I guess we're going to run into this a lot with German institutes of this sort.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
