### ISSUE TITLE
Modify the information in an existing ROR record: Ministry of Science and Technology https://ror.org/02kv4zf79

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#3993]
Summary of request: Modify the information in an existing ROR record

Name of organization: Ministry of Science and Technology
ROR ID: https://ror.org/02kv4zf79
Which part of the record needs to be changed? Name, External IDs, Links, Aliases, Labels
Description of change: This Taiwanese ministry is now operating under the name "National Science and Technology Council." The name needs to be updated accordingly, and the website needs to be updated as well. Also need to add another Funder ID to support discoverability and reconciliation between the Funder Registry and ROR. These are the changes that need to be made:
- Replace name: National Science and Technology Council
- Replace links: https://www.nstc.gov.tw/
- Add Funder ID: 100020595
- Add aliases: Ministry of Science and Technology
- Add label: 國科會 

Update: change.name==National Science and Technology Council; replace.links==https://www.nstc.gov.tw; add.FundRef==100020595; add.aliases==Ministry of Science and Technology; add.labels==國科會*Chinese;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
