### ISSUE TITLE
Add a new organization to ROR: 
 
Postdoctoral Institute for Computational Studies

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#400]
Summary of request: Add a new organization to ROR

Name of organization: Postdoctoral Institute for Computational Studies
Website: https://picomps.org/
Link to publications: https://doi.org/10.1016/j.etap.2021.103665
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: PICompS
Acronym/abbreviation: PICompS
Related organizations: 
City: Enfield, New Hampshire
Country: USA
Geonames ID: 5085900
Year established: 
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
Similar to https://ror.org/04awze035, which they cite on their webpage. Essentially, they seem to provide an affiliation for use by researchers working outside of traditional and academic roles. Not certain how involved they are with our "conducting," "producing," or "managing" research use cases. More an example of "touches" research, but precedent does exist with cited Ronin Institute.

publication affiliation usage:

https://www.mdpi.com/1420-3049/26/1/8/pdf

https://dlc.dlib.indiana.edu/dlc/bitstream/handle/10535/10767/Cebo_2020.pdf?sequence=1&isAllowed=y

https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/60c74f99842e651900db387b/original/predicted-3d-models-of-the-sars-co-v-2-spike-protein-membrane-proximal-external-region-and-transmembrane-domain.pdf

orcid_affiliation_usage: https://orcid.org/0000-0002-5365-6332 ; https://orcid.org/0000-0002-4376-1366

**Comment by arthurpsmith** [comment]
I'm not very impressed with their website - most of the things you click on do not seem to provide any information (the FAQ, the lists of members, in particular - tried Safari and Chrome). However, it does appear to have been used as an affiliation in publications by more than one or two distinct researchers. Is it really a research organization in the sense that we define it? I guess we do have a precedent as mentioned. So while this might be a borderline case, I do think it should have a ROR id.

**Comment by adambuttrick** [comment]
Removing from release as the website has been suspended and that was the primary source for verifying metadata.

**Comment by adambuttrick** [comment]
Website is still offline, so declining as out of scope.
