### ISSUE TITLE
Modify the information in an existing ROR record: 
Lynchburg College https://ror.org/03grk0f38


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#401]
Summary of request: Modify the information in an existing ROR record

Name of organization: Lynchburg College
ROR ID: https://ror.org/03grk0f38
Which part of the record needs to be changed? Primary name
Description of change: Name Change: University of Lynchburg

Other information about this request: Lynchburg College changed its name to University of Lynchburg back in 2018
Update: change.name==University of Lynchburg;

**Comment by adambuttrick** [comment]
Name change corresponds to branding and copyright statement on org's website. Wikidata has already been reflected to update this change as well.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
