### ISSUE TITLE
Modify the information in an existing ROR record: Alberta Environment and Sustainable Resource Development https://ror.org/0202cv241

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4012]
Summary of request: Modify the information in an existing ROR record

Name of organization: Alberta Environment and Sustainable Resource Development
ROR ID: https://ror.org/0202cv241
Which part of the record needs to be changed? Name, Aliases, Links, Wikipedia ID, External IDs
Description of change: This Canadian state ministry is now operating under a new name (see https://en.wikipedia.org/wiki/Alberta_Environment_and_Protected_Areas). The record is also missing a URL, and we should add relevant Funder ID(s) for Funder Registry reconciliation. Summary of changes to be made:
- Replace name: Alberta Environment and Protected Areas
- Add aliases: Alberta Environment and Sustainable Resource Development, Alberta Environment and Parks
- Add links: https://www.alberta.ca/environment-and-protected-areas.aspx
- Replace Wikipedia ID: https://en.wikipedia.org/wiki/Alberta_Environment_and_Protected_Areas
- Add ISNI ID: 000000011276660X
- Add Funder ID: 100012165

Update: change.name==Alberta Environment and Protected Areas; add.aliases==Alberta Environment and Sustainable Resource Development; add.aliases==Alberta Environment and Parks; add.links==https://www.alberta.ca/environment-and-protected-areas.aspx; change.wikipedia_url==https://en.wikipedia.org/wiki/Alberta_Environment_and_Protected_Areas; add.ISNI==0000 0001 1276 660X; add.FundRef==100012165;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
