### ISSUE TITLE
Modify the information in an existing ROR record: Ministry for Primary Industries https://ror.org/055y4y749

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4013]
Summary of request: Modify the information in an existing ROR record

Name of organization: Ministry for Primary Industries
ROR ID: https://ror.org/055y4y749
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 100013420

Update: add.FundRef==100013420;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
