### ISSUE TITLE
Modify the information in an existing ROR record: Universitas Katolik Widya Mandala Surabaya https://ror.org/00efxp054

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4015]
Summary of request: Modify the information in an existing ROR record

Name of organization: Universitas Katolik Widya Mandala Surabaya
ROR ID: https://ror.org/00efxp054
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 100020445

Update: add.FundRef==100020445;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
