### ISSUE TITLE
Modify the information in an existing ROR record: Innovation and Technology Commission https://ror.org/04vf9tr09

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4034]
Summary of request: Modify the information in an existing ROR record

Name of organization: Innovation and Technology Commission
ROR ID: https://ror.org/04vf9tr09
Which part of the record needs to be changed? External IDs, Links
Description of change:
- Add Funder ID 501100010428
- Replace links: https://www.itc.gov.hk

Update: add.FundRef==501100010428; replace.links==https://www.itc.gov.hk;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
