### ISSUE TITLE
Add a new organization to ROR: 
 
Lviv Medical Institute LLC

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#404]
Summary of request: Add a new organization to ROR

Name of organization: Lviv Medical Institute
Website: https://medinstytut.lviv.ua/
Link to publications: https://doi.org/10.53933/sspmpm.v1i2.32
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: 
ISNI ID: https://isni.org/isni/000000040517646X
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Львівський Медичний Інститут*Ukrainian;
Acronym/abbreviation: LMI
Related organizations: 
City: Lviv
Country: Ukraine
Year established: 2004
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge a research facility
Other information about this request:

**Comment by adambuttrick** [comment]
Used as an affiliation on the linked publications:

https://eesa-journal.com/wp-content/uploads/EESA_31_2.pdf#page=30

https://pdfs.semanticscholar.org/efa5/179d84a45e51cebb8792231217106403a973.pdf

https://doi.org/10.15587/2519-4852.2021.238320

Organization also appears to publish two journals, "Actual Problems of Medicine and Pharmacy" (Актуальні проблеми медицини та фармації) and "Journal of Higher Medical Education" (Вісник Вищої медичної освіти)
 
https://medinstytut.lviv.ua/vydavnycha_diyalnist/

**Comment by arthurpsmith** [comment]
So this organization could easily be confused with https://ror.org/0027cag10 which was previously known as the "Lviv State Medical Institute"; I think we need to create a ROR for this new institute just to avoid potential confusion here. But yes it should qualify on other grounds also. I added the ISNI id.

**Comment by arthurpsmith** [comment]
Oh - we generally remove corporate type appendages like "LLC" from primary names, I believe, right?

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/014kkjk75 in release v1.0.
