### ISSUE TITLE
Merge two or more ROR records: Tata Trusts https://ror.org/057kjcb31 and Tata Trusts https://ror.org/03x55yk94

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4044]
Merge/split/deprecate records:
Organizations affected by this change: Tata Trusts 
ROR ID(s) of organization(s) affected by this change: https://ror.org/057kjcb31 and https://ror.org/03x55yk94
How should the record(s) be changed? It appears as though GRID created duplicate records for Tata Trusts. I'm not sure which one should be primary. Perhaps the one with more external IDs? In any case, my recommendation would be:

1. Mark https://ror.org/03x55yk94 as withdrawn
2. Incorporate the relevant metadata from https://ror.org/03x55yk94 into the primary record (alternate names, additional funder ID)

**Comment by adambuttrick** [comment]
@mariagould Addressed in https://github.com/ror-community/ror-updates and /issues/3567
https://github.com/ror-community/ror-updates/issues/3572. Closing as duplicate.
