### ISSUE TITLE
Modify the information in an existing ROR record: Rio Tinto (Canada) https://ror.org/00mv4xe50

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4045]
Summary of request: Modify the information in an existing ROR record

Name of organization: Rio Tinto (Canada)
ROR ID: https://ror.org/00mv4xe50
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 501100018865

Update: add.FundRef==501100018865;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
