### ISSUE TITLE
Modify the information in an existing ROR record: University of Freiburg https://ror.org/0245cg223

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4046]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of Freiburg
ROR ID: https://ror.org/0245cg223
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 501100021729. This is the ID for the university's medical school and should be part of the main record for the university to support Funder Registry reconciliation. 

Update: add.FundRef==501100021729;$

**Comment by adambuttrick** [comment]
Record updated in release v1.27.
