### ISSUE TITLE
Modify the information in an existing ROR record: Westlake University https://ror.org/05hfa4n20

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4048]
Summary of request: Modify the information in an existing ROR record

Name of organization: Westlake University
ROR ID: https://ror.org/05hfa4n20
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 100018928 and set to preferred. Existing preferred Funder ID in record (501100015495) is for a university institute.

Update: add.FundRef==100018928;$

**Comment by adambuttrick** [comment]
Record updated in release v1.28.
