### ISSUE TITLE
Add a new organization to ROR: 
 
Rogante Engineering Office

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#405]
Summary of request: Add a new organization to ROR

Name of organization: Rogante Engineering Office
Website: www.roganteengineering.it
Link to publications: http://dx.doi.org/10.29228/JCHAR.52780
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Studio d'Ingegneria Rogante
Acronym/abbreviation: REO; SIR
Related organizations: 
City: Civitanova Marche
Country: Italy
Year established: 1997
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To be integrated in a scholarly publishing system
Other information about this request: The full list of research publications that use the organization as an affiliation is in the web page http://www.roganteengineering.it/pubblicazioni.asp

**Comment by nlundvick** [comment]
Added acronym/abbreviation "SIR." This organization is involved in materials science research using neutron techniques. The organization is well-established, founded in 1997. I found multiple affiliation use cases - see http://www.roganteengineering.it/pubblicazioni.asp. I can see a case being made for adding this organization to ROR. My one concern is that there appears to only be a single individual (Dr. Massimo Rogante) associated with the organization.

**Comment by arthurpsmith** [comment]
Yes, I cannot find any other person associated with this organization, nor does the website have any indication of other staff, and certainly nobody else seems to use this affiliation for publication. The "organization" seems to be just the one researcher, and our policy on this is clear - it is out of scope for ROR.
