### ISSUE TITLE
Modify the information in an existing ROR record: Adlerbertska Foundations https://ror.org/0494fs390

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4055]
Summary of request: Modify the information in an existing ROR record

Name of organization: Adlerbertska Foundations
ROR ID: https://ror.org/0494fs390
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 501100014552 to support Funder Registry reconciliation. The current Funder ID in the record appears to be a duplicate. 

Update: add.FundRef==501100014552*preferred;$

**Comment by adambuttrick** [comment]
Record updated in release v1.28.
