### ISSUE TITLE
Modify the information in an existing ROR record: 
University of St.Gallen https://ror.org/0561a3s31


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#406]
Summary of request: Modify the information in an existing ROR record

Name of organization: University of St.Gallen
ROR ID: https://ror.org/0561a3s31
Which part of the record needs to be changed? Organization website
Description of change: https://www.unisg.ch

MG Note:
Replace links: https://www.unisg.ch/

Update: replace.links==https://www.unisg.ch/;

**Comment by mariagould** [comment]
The website currently appearing in the record is http://www.es.unisg.ch/en/. This appears to be the website for the University of St. Gallen executive school (hence the "es" in the URL). The primary website for the university is https://www.unisg.ch/. This change should therefore proceed as suggested.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
