### ISSUE TITLE
Modify the information in an existing ROR record: Arizona Game and Fish Department https://ror.org/05r11v294

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4067]
Summary of request: Modify the information in an existing ROR record

Name of organization: Arizona Game and Fish Department
ROR ID: https://ror.org/05r11v294
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 100020504

Update: add.FundRef==100020504;$

**Comment by adambuttrick** [comment]
Record updated in release v1.28.
