### ISSUE TITLE
Modify the information in an existing ROR record: 
Universitätsklinik Balgrist https://ror.org/02yzaka98


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#408]
Summary of request: Modify the information in an existing ROR record

Name of organization: Universitätsklinik Balgrist
ROR ID: https://ror.org/02yzaka98
Which part of the record needs to be changed? Organization website
Description of change: Correction of URL: https://www.balgrist.ch/en/
Update: delete.links==http://www.balgrist.ch/en/Home.aspx; add.links==https://www.balgrist.ch/;

**Comment by adambuttrick** [comment]
Current URL in ROR does not resolve, while this one does. We will strip out the English page reference, however, as the website resolves fine without it.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
