### ISSUE TITLE
Modify the information in an existing ROR record: Western Illinois University https://ror.org/02sshz518

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4082]
Summary of request: Modify the information in an existing ROR record

Name of organization: Western Illinois University
ROR ID: https://ror.org/02sshz518
Which part of the record needs to be changed? External IDs
Description of change: This record is missing a Funder ID. The ID should be added to support Funder Registry reconciliation. Add Funder ID: 100018100

Update: add.FundRef==100018100;$

**Comment by adambuttrick** [comment]
Record updated in release v1.28.
