### ISSUE TITLE
Modify the information in an existing ROR record: Agencia Nacional de Promoción Científica y Tecnológica https://ror.org/03stxzb56

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4084]
Summary of request: Modify the information in an existing ROR record

Name of organization: Agencia Nacional de Promoción Científica y Tecnológica
ROR ID: https://ror.org/03stxzb56
Which part of the record needs to be changed? Name, Aliases, Links, External ID
Description of change: The agency is operating under a new name and URL and this should be reflected in the record. There are multiple entries in the Funder Registry and these IDs should be part of the ROR record to support Funder Registry reconciliation. 
(1) Change name: Agencia Nacional de Promoción de la Investigación, el Desarrollo Tecnológico y la Innovación
(2) Add former name as alias: Agencia Nacional de Promoción Científica y Tecnológica
(3) Replace links: https://www.argentina.gob.ar/ciencia/agencia
(4) Add Funder ID: 501100021778

Update: change.name==Agencia Nacional de Promoción de la Investigación, el Desarrollo Tecnológico y la Innovación; add.aliases==Agencia Nacional de Promoción Científica y Tecnológica; replace.links==https://www.argentina.gob.ar/ciencia/agencia; add.FundRef==501100021778;$

**Comment by adambuttrick** [comment]
Record updated in release v1.28.
