### ISSUE TITLE
Modify the information in an existing ROR record: Auckland Council https://ror.org/03xedy893

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4088]
Summary of request: Modify the information in an existing ROR record

Name of organization: Auckland Council
ROR ID: https://ror.org/03xedy893
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 100011256

Update: add.FundRef==100011256;$

**Comment by adambuttrick** [comment]
Record updated in release v1.28.
