### ISSUE TITLE
Add a new organization to ROR: 
 
SeaLevel.info

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#409]
Summary of request: Add a new organization to ROR

Name of organization: SeaLevel.info
Website: https://sealevel.info/
Link to publications: 10.1007/s11069-012-0159-8
Organization type: Other (Use this category for any organization that does not fit the categories above)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: n/a
Acronym/abbreviation: n/a
Related organizations: 
City: Cary, NC
Country: USA
Year established: 2012
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by nlundvick** [comment]
SeaLevel.Info is a website that analyzes sea level and includes data accumulated from various sources. There is only contact information for a single individual. The publication provided in the request is a "Comment on" a published paper. It was authored by SeaLevel's contact, who claims affiliation with "Burton Systems Software" in the comment, not SeaLevel. Searching Google Scholar I am not finding any affiliation use for "SeaLevel." The website includes a "Papers" link, but these are documents authored by researchers affiliated with various other organizations, not SeaLevel. Determination: Not in scope

**Comment by adambuttrick** [comment]
Agree, this is out of scope for ROR.
