### ISSUE TITLE
Add a new organization to ROR: 
 
Community of Physics

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#410]
Summary of request: Add a new organization to ROR

Name of organization: Community of Physics
Website: https://www.cpbd.ac/
Link to publications: https://arxiv.org/abs/2112.05206
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/Q51077272
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation: CP
Related organizations: 
City: Dhaka
Country: Bangladesh
Geonames ID: 1185241
Year established: 2013
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
Limited publication affiliation usage, but organization does appear to provide instruction in domain. Organization staff are well-credentialed and involved with similar organizations internationally (e.g. Institute of Physics, London, American Physical Society).

Publication affiliation usage: https://www.sciencepublishinggroup.com/journal/paperinfo?journalid=197&doi=10.11648/j.sjedu.20170501.13

Google Scholar affiliation_usage: https://scholar.google.com/citations?user=8HLUACMAAAAJ; https://scholar.google.com/citations?user=D34NJnsAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0002-1702-2615 ; https://orcid.org/0000-0002-7452-0012 ; https://orcid.org/0000-0003-3976-6161 ; https://orcid.org/0000-0003-0165-9360 ; https://orcid.org/0000-0002-6170-5296 ; https://orcid.org/0000-0003-3434-5691 ; https://orcid.org/0000-0001-9315-6538 ; https://orcid.org/0000-0001-8103-7670 ; https://orcid.org/0000-0003-2693-2765 ; https://orcid.org/0000-0001-5207-486X ; https://orcid.org/0000-0002-5703-6827 ; https://orcid.org/0000-0002-2111-4846

**Comment by nlundvick** [comment]
Established top-level organization involved in scholarly research. As noted by previous curator, limited affiliation use but similar to other physics organizations in ROR. Organization is in scope and should be assigned a ROR ID.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/041anjn10 in release v1.0.
