### ISSUE TITLE
Add a new organization to ROR: 
 
Station de Radioastronomie de Nançay

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#411]
Summary of request: Add a new organization to ROR

Name of organization: Nançay Radio Observatory
Website: https://www.obs-nancay.fr
Link to publications: https://doi.org/10.1093/mnras/stab2496, https://doi.org/10.1051/0004-6361/201937201,  https://doi.org/10.3847/1538-4357/ac1acd
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: https://en.wikipedia.org/wiki/Nançay_Radio_Observatory
Wikidata ID: https://www.wikidata.org/wiki/Q60643512
ISNI ID: https://isni.org/isni/0000000404717041
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Unité Scientifique de Nançay
Labels: Station de Radioastronomie de Nançay (French); Unité Scientifique de Nançay (French)
Acronym/abbreviation: USN
Related organizations: https://ror.org/029nkcm90 (parent) https://ror.org/02feahw73 (parent) https://ror.org/014zrew76 (parent)
City: Nançay
Country: France
Geonames ID: 2991013
Year established: 1956
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility
Other information about this request:

**Comment by adambuttrick** [comment]
Radio astronomy facility associated with Paris Observatory and University of Orleans. Data outputs and related research appear to use Paris Observatory affiliation (e.g., https://archives-decametriques.obspm.fr/?lang=en ;  https://www.researchgate.net/publication/224263728_Solar_physics_at_Nancay_radio_observatory_Recent_developments/link/02bfe510a23f96bbb9000000/download), but we have lots of other observatories in ROR.

ORCID affiliation usage: https://orcid.org/0000-0002-8191-3885
Similar records in ROR: https://ror.org/00vnwz606 ; https://ror.org/00w894124

**Comment by nlundvick** [comment]
Concur with @adambuttrick - add to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01vqrde47 in release v1.0.
