### ISSUE TITLE
Project: Add European Reference Networks 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#412]
This is a bulk request to review the proposed addition of all European Reference Network entities. The proposed additions are in this spreadsheet:

https://docs.google.com/spreadsheets/d/1edwGR1NO2AivGgfkoZ4DCyfltuifEEjs/edit?usp=sharing&ouid=109671855708944259476&rtpof=true&sd=true
 
Background information received: 

> "The European Reference Networks fall within the scope of ROR. I found a record for one of the ERNs (ERN Guard Heart; https://ror.org/055s7a943), but there are 23 ERNs that are not yet available [...] [T]hese are fairly new research networks (within the last 5 years) so publication data may not be available. Additional information about the networks can be found on the European Commission's website: https://ec.europa.eu/health/ern/networks_en."

The linked spreadsheet includes the proposed additions, with the following notes:

> "ERN parent organization: The first row contains the information for the parent organization (The Board of the Member States for the ERNs). If this entry is accepted, then the ROR ID of the parent organization should be applied to all of the ERNS."
> "Update Request: For the ERN that already exists in ROR (ERN GUARD-HEART, https://ror.org/055s7a943), I have an update. I have added the related ROR organization and location information."

**Comment by adambuttrick** [comment]
Records created as part of release v1.1.

| ROR ID | Name |
| https://ror.org/05s4nk876 | Endo-ERN |
| https://ror.org/04x2ddb07 | ERKNet |
| https://ror.org/00r7apq26 | ERN Board of Member States |
| https://ror.org/04crk2m06 | ERN BOND |
| https://ror.org/032gggv33 | ERN CRANIO |
| https://ror.org/0214h3370 | ERN EpiCARE |
| https://ror.org/01rq5e797 | ERN EURACAN |
| https://ror.org/04x3ta798 | ERN EURO-NMD |
| https://ror.org/04dng8q18 | ERN EuroBloodNet |
| https://ror.org/00y7tet25 | ERN eUROGEN |
| https://ror.org/029nm1m14 | ERN EYE |
| https://ror.org/03pbpa834 | ERN GENTURIS |
| https://ror.org/03va0yq34 | ERN ITHACA |
| https://ror.org/0279ntc65 | ERN LUNG |
| https://ror.org/02dk8t214 | ERN PaedCan |
| https://ror.org/036e61f39 | ERN RARE-LIVER |
| https://ror.org/04069k268 | ERN ReCONNET |
| https://ror.org/0208ges23 | ERN RITA |
| https://ror.org/0446wcg70 | ERN Skin |
| https://ror.org/04rr75245 | ERN TRANSPLANT-CHILD |
| https://ror.org/05a27za87 | ERN-RND |
| https://ror.org/02h9n4675 | ERNICA |
| https://ror.org/00xdsr520 | MetabERN |
| https://ror.org/005pygq66 | VASCERN |
