### ISSUE TITLE
Add a new organization to ROR: Garfield Weston Foundation

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4121]
Summary of request: Add a new organization to ROR

Name of organization: Garfield Weston Foundation
Website: https://garfieldweston.org
Link to publications: 
Organization type: Nonprofit
Wikipedia page: 
Wikidata ID: Q5523127
ISNI ID: 0000 0004 1781 1758
GRID ID: 
Crossref Funder ID: 100013999
Other names for the organization: 
Aliases: 
Labels: 
Acronym/abbreviation: GWF
Related organizations: https://ror.org/0512g3q82 (related)
City: London
Country: United Kingdom
Geonames ID: 2643743
Year established: 1958
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of Funder Registry reconciliation.

**Comment by adambuttrick** [comment]
Part of Funder Registry reconciliation.

**Comment by mariagould** [comment]
I just found a duplicate Funder ID for this organization: 501100000243. The ID is currently incorrectly assigned to https://ror.org/0512g3q82. The ID should be moved to this new record instead. There is a separate Funder ID associated with https://ror.org/0512g3q82 which will be addressed in a separate issue as part of Funder Registry reconciliation.

**Comment by adambuttrick** [comment]
Incorporated separately and maintain separate web presences, so we would probably need both. Have separate Wikidata, Wikipedia, and funder registry entries. Will tag as related.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00rm5fa18 in release v1.28.
