### ISSUE TITLE
Add a new organization to ROR: 
 
 Société des historiens médiévistes de l'enseignement supérieur public

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#413]
Summary of request: Add a new organization to ROR

Name of organization:  Société des historiens médiévistes de l'enseignement supérieur public
Website: https://www.shmesp.fr/
Link to publications: http://isni.org/isni/0000000114636737, https://catalogue.bnf.fr/ark:/12148/cb120734837, https://books.openedition.org/psorbonne/55167, https://books.openedition.org/psorbonne/16331, https://books.openedition.org/author?name=societe%C2%A0des%C2%A0historiens%C2%A0medievistes%C2%A0de+l%E2%80%99enseignement%C2%A0superieur%C2%A0public, 
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: Q50823978
ISNI ID: http://isni.org/isni/0000000114636737
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation: SHMESP, SHMS
Related organizations: 
City: Paris
Country: France
Geonames ID: 2988507
Year established: 1969
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders, To be integrated in a scholarly publishing system
Other information about this request: The << Société des historiens médiévistes de l'enseignement supérieur public >> is a scholarly association. Created in 1969 by the medievalist Édouard Perroy, the Société des historiens médiévistes de l'enseignement supérieur public gathers almost all French scholars in the field of medieval history and organizes since 1970 a yearly scholarly conference on a specific topic that illustrates the ongoing research. The volumes are also edited online since 1993: https://books.openedition.org/author?name=societe%C2%A0des%C2%A0historiens%C2%A0medievistes%C2%A0de+l%E2%80%99enseignement%C2%A0superieur%C2%A0public
website: https://www.shmesp.fr/
some identifiers:
http://isni.org/isni/0000000114636737
https://catalogue.bnf.fr/ark:/12148/cb120734837
https://viaf.org/viaf/133310488/

**Comment by adambuttrick** [comment]
We have examples of independent Medieval research societies (see similar IDs linked below) in ROR. Produces scholarly publications and is used as an affiliation in ORCID.

ORCID affiliation usage: https://orcid.org/0000-0001-8887-1000 ; https://orcid.org/0000-0003-0478-5071 ; https://orcid.org/0000-0003-3059-245X ; https://orcid.org/0000-0001-9969-3334 ; https://orcid.org/0000-0003-4751-9152

Similar IDs in ROR: https://ror.org/04g3e3p90 ; https://ror.org/02pjxh370 ; https://ror.org/04g3e3p90

**Comment by nlundvick** [comment]
Concur - Established top-level organization with multiple instances of affiliation use in scholarly outputs. Add to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/002vpkf64 in release v1.0.
