### ISSUE TITLE
Merge records: Athlone Institute of Technology & Limerick Institute of Technology

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#414]
Summary of request: Merge two or more ROR records

**Name(s) of organization(s) associated with record(s):**
Athlone Institute of Technology
Limerick Institute of Technology

**ROR ID(s) affected by this proposed change:** 
https://ror.org/02dyxwz31
https://ror.org/0269ncv24

**Describe what change needs to be made to the ROR record(s). Provide a reason for the change (e.g., the organization no longer exists, or the organization has merged with another one):**
Merge of Athlone Institute of Technology & Limerick Institute of Technology

**Other information about this request:** 
New university name: Technological University of the Shannon: Midlands Midwest (TUS).  
Primary address for profile: Moylish Campus, Moylish Park, Limerick, V94 EC5T

**Comment by adambuttrick** [comment]
Addressed with #1725 and #1726.
