### ISSUE TITLE
Add a new organization to ROR: 
 
Institute for Social and Political Psychology

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#416]
Summary of request: Add a new organization to ROR

Name of organization: Institute of Social and Political Psychology
Website: https://ispp.org.ua/
Link to publications: https://doi.org/10.33120
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://uk.wikipedia.org/wiki/Інститут_соціальної_та_політичної_психології_НАПН_України
Wikidata ID: Q15088248
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Institute for Social and Political Psychology of the National Academy of Educational Sciences of Ukraine 
Acronym/abbreviation: ISPP NAES
Aliases: ISPP NAES of Ukraine
Labels: Інститут соціальної та політичної психології НАПН України*Ukrainian
Related organizations: https://ror.org/05h1pdj54 (parent)
City: Kyiv
Country: Ukraine
Geonames ID: 703448
Year established: 1994
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
Research institute under the National Academy of Educational Sciences of Ukraine. Primary name form corresponds to that on the English version of their site.

Publication affiliation usage: https://lib.iitta.gov.ua/725841/1/зб 2020 -ст Гриценок-Юрченко_removed.pdf

Google Scholar affiliation usage: https://scholar.google.com/citations?hl=en&user=kbPyXRcAAAAJ&view_op=list_works&sortby=pubdate

ORCID Affiliation Usage: https://orcid.org/0000-0003-4378-9841 ; https://orcid.org/0000-0001-6141-9786 ; https://orcid.org/0000-0002-0055-2185

**Comment by nlundvick** [comment]
In scope with multiple instances of affiliation use found at Google Scholar, add to ROR. Edited primary name from "Institute for Social and Political Psychology" to "Institute of Social and Political Psychology" to match the name listed in English version of the organization's website (using website's language dropdown option). @adambuttrick - Less clear on how to handle the label. I think it should be changed to "Інститут соціальної та політичної психології" with the "НАПН України" removed as that portion translates to "of the National Academy of Educational Sciences of Ukraine".

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/049z73212 in release v1.1.
