### ISSUE TITLE
Modify the information in an existing ROR record: 
WHU – Otto Beisheim School of Management  https://ror.org/01yhahq71


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#417]
Summary of request: Modify the information in an existing ROR record

Name of organization: WHU – Otto Beisheim School of Management
ROR ID:  https://ror.org/01yhahq71
Which part of the record needs to be changed? Primary name
Description of change: incorrect spelling (see https://www.whu.edu/en/)

Update: change.name==WHU – Otto Beisheim School of Management;

**Comment by mariagould** [comment]
The request notes an issue with the spelling of the primary name but unless I am missing something, I am not able to identify the error. The only thing I notice is different spacing around the hyphen that comes after "WHU."

Name in the ROR record: WHU-Otto Beisheim School of Management
Name on WHU website: WHU – Otto Beisheim School of Management

@MSpenger do you have any insights?

**Comment by MSpenger** [comment]
I also think that this is the intended correction. "WHU – Otto Beisheim School of Management" should be the primary name and the entry "WHU-Otto Beisheim School of Management" can be omitted from the entry.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
