### ISSUE TITLE
Add a new organization to ROR: 
 
SPL L'Eau des Collines

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#418]
Summary of request: Add a new organization to ROR

Name of organization: SPL L'Eau des Collines
Website: http://www.eaudescollines.fr/
Link to publications: http://www.eaudescollines.fr/publications-spl-eau-des-collines/partage-de-nos-connaissances/
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: L'Eau des Collines
Aliases: L'Eau des Collines
Acronym/abbreviation: SPL EDC
Related organizations: 
City: Aubagne
Country: France
Geonames ID: 3036433
Year established: 2012
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request: SPL L'Eau des Collines was driving field work and was providing data for supporting academic research work in the fied of the subsurface hydrology. Recent publication in international peer-reviewed journal aknowledged our contribution as data provider  https://link.springer.com/article/10.1007%2Fs10040-021-02426-9#Ack1 . The present request to be indexed in ROR.org is for supporting open-access of all our scientific data and  reports  with a systematic registration of our numeric ressources in Datacite (each of our data will be indexed with a DOI through OPIDOR service provided by CNRS). We need to be recorded in ROR.org in order to be able to affiliate our DOIs ressources.

**Comment by adambuttrick** [comment]
Public water company in charge of water management and related services in the Pays d'Aubagne et de l'Étoile territory of France. Provides datasets and produces reports on the related to the resources under their charge (https://doi.org/10.48799). I can't them yet on Datacite, I believe the request for a ROR ID may be part of their move to the platform.

Not certain whether to use the form provided for the primary name. Mailing address on their site simply list "L’eau des collines." SPL is an abbreviation for "Société publique locale du pays d'Aubagne et de l'Etoile."

**Comment by arthurpsmith** [comment]
Ok, it's about 10 years old, and it does seem to be somewhat involved in research. Given that we've added a few similar organizations previously I think this is fine. While SPL is a type-of-organization abbreviation it appears to be a relatively limited and new one (the website mentions it's from a law dated May 2010) so I think it's ok in this case to leave it as part of the name as they requested.
