### ISSUE TITLE
Add a new organization to ROR - Institut d'administration des entreprises de Paris

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4183]
Summary of request: Add a new organization to ROR

Name of organization: IAE Paris
Website: http://www.iae-paris.com
Link to publications:
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/IAE_Paris
Wikidata ID: Q3151899
ISNI ID: 0000 0001 0941 5948
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: Institut d'administration des entreprises de Paris; Sorbonne Business School
Labels:
Acronym/abbreviation: 
Related organizations:
City: Paris
Country: France
Geonames ID: 2968815
Year established: 1956
Other information about this request:

**Comment by adambuttrick** [comment]
Identified as a parent organization in RNSR reconciliation. Affiliation usage has this leading for https://ror.org/002t25c44, but [HAL authority record](https://aurehal.archives-ouvertes.fr/structure/read/id/300334) (and RNSR references) have this as its own institution. Listed as associated to https://ror.org/002t25c44 for its degree granting status. My thinking is that references to this should roll up to https://ror.org/002t25c44, but I would appreciate a second review to verify.

Publication affiliation usage: https://doi.org/10.3390/smartcities4010006; https://doi.org/10.3406/rei.2000.1048; https://doi.org/10.1016/j.chb.2018.05.042; https://doi.org/10.1080/00207543.2018.1427900; https://doi.org/10.1016/j.ijhm.2018.07.013; https://doi.org/10.1509/jm.15.0291

**Comment by arthurpsmith** [comment]
Yes, it does appear to be always associated with the parent university in affiliation usage and on their website. I'm wondering if we will need to create a separate record for this in a few years when France reorganizes their universities again, but for now I think it's fine to recommend use of https://ror.org/002t25c44 for this institution.
