### ISSUE TITLE
Add a new organization to ROR: 
 
Netherlands Haemophilia Society

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#419]
Summary of request: Add a new organization to ROR

Name of organization: Netherlands Haemophilia Society
Website: http://www.nvhp.nl
Link to publications: 10.1111/hae.14475, 10.1159/000215786, 10.1111/j.1365-2516.1995.tb00061.x, 10.1111/hae.14396, 10.1182/bloodadvances.2020002740
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Nederlandse Vereniging van Hemofilie-Patiënten
Acronym/abbreviation: NVHP
Aliases: Dutch Haemophilia Society
Labels: Nederlandse Vereniging van Hemofilie-Patiënten*Dutch
Related organizations: 
City: Nijkerk
Country: The Netherlands
Geonames ID: 2750065
Year established: 1971
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
Publication/researcher affiliations are solid and list Netherlands Haemophilia Society exclusively. Public Benefit Organization entry includes, "to promote scientific research with respect to hemophilia and related hereditary coagulation factor deficiencies and hereditary platelet disorders, and with respect to all that is related thereto."

https://www.nvhp.nl/over-de-nvhp.html

ORCID affiliation usage: https://orcid.org/0000-0003-4118-4670

Similar records in ROR: https://ror.org/013h8cr97

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00wk22n41 in release v1.0.
