### ISSUE TITLE
Add a new organization to ROR - Institut supérieur de l'automobile et des transports

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4192]
Summary of request: Add a new organization to ROR

Name of organization: Institut supérieur de l'automobile et des transports
Website: http://www.isat.fr
Link to publications:
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Institut_sup%C3%A9rieur_de_l%27automobile_et_des_transports
Wikidata ID: Q3152566
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases:
Labels:
Acronym/abbreviation: ISAT
Related organizations:
City: Nevers
Country: France
Geonames ID: 2990474
Year established: 1991
Other information about this request:

**Comment by adambuttrick** [comment]
Identified as part of RNSR reconciliation. Hierarchy/independence here is somewhat confusing, as its located at https://ror.org/03k1bsr36 but appears to operate with some degree of autonomy. That said affiliation usage is all leading for https://ror.org/03k1bsr36.

https://doi.org/10.1109/itec.2012.6243425; https://doi.org/10.1109/itec.2013.6574503
orcid_affiliation_usage: https://orcid.org/0000-0001-5279-5579 ; https://orcid.org/0000-0002-0006-6419

**Comment by arthurpsmith** [comment]
Hmm, the ORCID affiliation listings don't mention the university. And here's an old OSTI entry that lists this institute without mentioning the University of Burgundy - https://www.osti.gov/etdeweb/biblio/145892 - I think given the separate website domain also (though the website is framed in a University of Burgundy context) this would be fine to have as a separate ROR id. Do we need another opinion on this?

**Comment by adambuttrick** [comment]
@arthurpsmith Nope! For this project, we're leaning toward being inclusive, so yours will suffice. Thank you for reviewing!

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/020120f86 in release v1.29.
