### ISSUE TITLE
Add a new organization to ROR - Telecom SudParis

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4196]
Summary of request: Add a new organization to ROR

Name of organization: Telecom SudParis
Website: https://www.telecom-sudparis.eu
Link to publications:
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Telecom_SudParis
Wikidata ID: Q43305
ISNI ID: 0000 0004 0640 6351
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases:
Labels:
Acronym/abbreviation: 
Related organizations:  https://ror.org/042tfbd02 (parent) https://ror.org/025vp2923 (parent)
City: Évry
Country: France
Geonames ID: 6454878
Year established: 1979
Other information about this request:

**Comment by adambuttrick** [comment]
Identified as part of RNSR reconciliation. Grande école in France. [HAL authority record](https://aurehal.archives-ouvertes.fr/structure/read/id/352124) has this as an independent organization, but affiliation usage and other references have parent as https://ror.org/025vp2923. Would appreciate Second Review.

Publication affiliation usage: https://doi.org/10.1109/access.2019.2913984; https://doi.org/10.1145/2030112.2030127; https://doi.org/10.1109/jiot.2014.2318835

**Comment by arthurpsmith** [comment]
As usual with French institutions I am a little confused. However, it looks like from the wikipedia page and their own website that Telecom SudParis is a part of BOTH https://ror.org/025vp2923 and https://ror.org/042tfbd02 - it lists itself as a "school" of the first, and a founding member of the second. Somehow in ROR it looks like we have https://ror.org/025vp2923 as a child of  https://ror.org/042tfbd02 but I don't think that's correct; from their wikipedia page it looks like IMT is a founding member of Paris-Saclay University - https://ror.org/03xjwb503. In any case I am pretty sure this qualifies as a two-parent case. Also there's the independent website for Telecom SudParis, and that IMT is not mentioned in some of the affiliation usage, only Telecom SudParis itself. So I think this qualifies for its own ROR id.

**Comment by arthurpsmith** [comment]
PS I added their ISNI

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05xvk4r52 in release v1.30.
