### ISSUE TITLE
Add a new organization to ROR: Center for Scientific Collaboration and Community Engagement

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#42]
Summary of request: Add a new organization to ROR

Name of organization to be added | Center for Scientific Collaboration and Community Engagement (CSCCE)

Organization website | https://www.cscce.org/

Briefly explain why you are requesting a ROR ID for this organization and how the ROR ID will be used. | CSCCE publishes various outputs to support scientific community building

Provide DOI(s) or links for research associated with this organization, such as published articles that include the organization's name as an affiliation. If DOIs or links are not available, describe the research-related activities of this organization. | See resources published on the CSCCE Zenodo page: https://zenodo.org/communities/cscce/ for example: https://zenodo.org/record/3997802

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03xaryf14 in release v1.0.
