### ISSUE TITLE
Add a new organization to ROR: 
 
GO FAIR FOUNDATION

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#420]
Summary of request: Add a new organization to ROR

Name of organization: GO FAIR FOUNDATION
Website: https://www.gofairfoundation.org
Link to publications: https://www.scidatacon.org/virtual-2021/sessions/375/
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation: GFF
Labels: STICHTING GO FAIR*Dutch
Related organizations: 
City: LEIDEN
Country: NETHERLANDS 
Geonames ID: 2751773
Year established: 2018
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility
Other information about this request: GFF supports the FAIR Principles and the GO FAIR movement, by preparing the implementing of a coherent certification program and by coordinating international missionary and kickstart activities for FAIR related projects worldwide.

**Comment by mariagould** [comment]
This request still needs to proceed through the review process. This is an independent organization involved in supporting and certifying activities around FAIR data. 

Per follow-up email, the intended use case for a ROR ID is to identify the foundation as the certifying entity for FAIR Implementation Profiles: 

> It is a project with the ENVRI-FAIR consortium (https://envri.eu/home-envri-fair/) that has increased the urgency for the ROR ID. The GFF has been commissioned, along with the Environmental Agency Austria to upgrade a tool call FAIR Implementation Profile Wizard, which helps communities to create machine-readable FAIR Implementation Profiles. The ENVRI-FAIR consortium, in close collaboration with GO FAIR, have been leading the development of the FAIR Implementation Profile method, and the FIP Wizard tool. [...] A key function, namely the GFF “qualification” or endorsement of FAIR Enabling Resources, will require a globally unique and persistent identifier for the GO FAIR Foundation. Hence, our request. 

The foundation does appear as an affiliation in extant publications (e.g., https://doi.org/10.1162/dint_a_00050).

The foundation is related the GO FAIR initiative (https://www.go-fair.org/) as well as to the GO FAIR International Support and Coordination Office (GFISCO) (https://www.go-fair.org/go-fair-initiative/go-fair-offices/). 

I think it is in scope for ROR to represent GO FAIR as an organization that is involved in certifying and producing research, but I think we need to review whether the ROR record should reflect the foundation, the International Support and Coordination Office (GFISCO), or the overall initiative. 

Additional review from curators is needed in order to make a determination about how we should proceed.

**Comment by arthurpsmith** [comment]
The initiative has a Wikidata id (Q49984485); GFISCO's website is under the initiative website. Both GFISCO and the GFF are used as affiliations. The GFF website claims they support GFISCO (among other things) and points to the initiative website for that.

I think from all the above that GFF acts like a top-level organization here, and given that the request specifically asked for the foundation to be recognized and it is actually an organization (as opposed to a project or initiative) I think that does make the most sense. So yes let's create a ROR id for the GO FAIR Foundation as requested here.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/056j50v04 in release v1.0.
