### ISSUE TITLE
Add a new organization to ROR: 
 
Oregon Water Resources Department

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#421]
Summary of request: Add a new organization to ROR

Name of organization: Oregon Water Resources Department
Website: https://www.oregon.gov/owrd/pages/index.aspx
Link to publications: https://www.oregon.gov/owrd/wrdreports/Groundwater_Simulation_and_Management_%20Models.pdf
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://en.wikipedia.org/wiki/Oregon_Water_Resources_Department
Wikidata ID: https://www.wikidata.org/wiki/Q7101419
ISNI ID: https://isni.org/isni/0000000106841300
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Oregon State Water Resources Department
Aliases: Oregon State Water Resources Department
Acronym/abbreviation: OWRD
Related organizations: 
City: Salem, Oregon
Geonames ID: 5750162
Country: United States of America
Year established: 1975
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge a research facility
Other information about this request:

**Comment by adambuttrick** [comment]
Produces research and datasets, especially in coordination with USGS.

Publication involvement: https://pubs.er.usgs.gov/publication/sir20175097
Data source for USGS report: https://pubs.usgs.gov/of/2020/1138/ofr20201138.pdf

ORCID affiliation_usage: https://orcid.org/0000-0002-6684-6426 ; https://orcid.org/0000-0002-9562-9340 ; https://orcid.org/0000-0001-5289-1210 ; https://orcid.org/0000-0002-8930-6967

Similar records in ROR: https://ror.org/03v275937 ; https://ror.org/056y4tg97

**Comment by arthurpsmith** [comment]
Seems clear it should be in ROR. Metadata looks good. Moving to ready.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02xbecd21 in release v1.0.
