### ISSUE TITLE
Modify the information in an existing ROR record: CGIAR https://ror.org/04c4bm785

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4219]
Summary of request: Modify the information in an existing ROR record

Name of organization: CGIAR
ROR ID: https://ror.org/04c4bm785
Which part of the record needs to be changed? Aliases, External IDs
Description of change: (1) Add alias Consortium of International Agricultural Research Centers; (2) Add Funder ID 501100015815

Update: add.aliases==Consortium of International Agricultural Research Centers; add.FundRef==501100015815;$

**Comment by adambuttrick** [comment]
Record updated in release v1.28.
