### ISSUE TITLE
Add a new organization to ROR: 
 
Vishwakarma University

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#422]
Summary of request: Add a new organization to ROR

Name of organization: Vishwakarma University
Website: www.vupune.ac.in
Link to publications: https://research.vupune.ac.in/index, https://doi.org/10.3390/electronics10111289 , https://doi.org/10.1016/j.matpr.2020.10.130 ,  
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://en.wikipedia.org/wiki/Vishwakarma_University
Wikidata ID: 
ISNI ID: 0000 0005 0599 7193
GRID ID: 
Crossref Funder ID: 
Other names for the organization: विश्वकर्मा युनिव्हर्सिटी / विश्वकर्मा विद्यापीठ 
Labels: विश्वकर्मा युनिव्हर्सिटी / विश्वकर्मा विद्यापीठ (Marathi)
Acronym/abbreviation: VU
Related organizations: 
City: Pune
Country: India
Geonames ID: 1259229
Year established: 2017
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets
Other information about this request: Dear Sir/Madam
Vishwakarma University, Pune (VU) is a natural offshoot of the Vishwakarma Group of Institutions’ educational legacy spanning more than 35 years. The University has been established as a State Private University through Maharashtra Government Act in the year 2017. Being UGC approved, VU is authorized to design and implement its curriculum, conduct examinations, award degrees. Vishwakarma University is Member of Association of Indian Universities (AIU, New Delhi). It is requested to please add Vishwakarma University name in ROR.
Thanking You.

**Comment by adambuttrick** [comment]
ROR metadata extracted from Wikidata:

wikidata_id: Q48731017
established: 2017
admin_terr_name: Pune
admin_terr_geonames_id: 1259229
country: India
wikipedia_url: https://en.wikipedia.org/wiki/Vishwakarma_University
links: http://www.vupune.ac.in
lat_lng: 18.460266666666666, 73.88363611111112

Sample affiliation usage from Google Scholar with links to publications:
https://scholar.google.com/citations?user=Li4av4UAAAAJ
https://scholar.google.com/citations?user=C7Xb1xIAAAAJ
https://scholar.google.com/citations?user=Z600OfoAAAAJ

All lines up with submission and ROR criteria. Looks good to me!

**Comment by arthurpsmith** [comment]
Very thorough, I agree with everything Adam said above. One additional detail, it seems to be in ISNI also:
0000 0005 0599 7193 - https://isni.org/isni/0000000505997193

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/016zwj547 in release v1.0.
