### ISSUE TITLE
Modify the information in an existing ROR record: Vlaamse Interuniversitaire Raad https://ror.org/00q3h2974

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4225]
Summary of request: Modify the information in an existing ROR record

Name of organization: Vlaamse Interuniversitaire Raad
ROR ID: https://ror.org/00q3h2974
Which part of the record needs to be changed? Links, External IDs
Description of change: (1) Replace links: https://vlir.be/ ; (2) Add Funder ID 501100022083

Update: replace.links==https://vlir.be; add.FundRef==501100022083;$

**Comment by adambuttrick** [comment]
Record updated in release v1.28.
