### ISSUE TITLE
Modify the information in an existing ROR record: Department of Environment, Forestry and Fisheries https://ror.org/01vm69c87

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4226]
Summary of request: Modify the information in an existing ROR record

Name of organization: Department of Environment, Forestry and Fisheries
ROR ID: https://ror.org/01vm69c87
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 501100022252 and mark as preferred. Current preferred Funder ID 501100006296 appears to be referencing a funding program, not the organization.

Update: add.FundRef==501100022252*preferred;$

**Comment by adambuttrick** [comment]
Record updated in release v1.28.
