### ISSUE TITLE
Add a new organization to ROR: 
 
Max Planck Institute for Multidisciplinary Sciences

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#423]
Name of organization: Max Planck Institute for Multidisciplinary Sciences
Website: https://www.mpinat.mpg.de/
Link to publications: not yet available (institution was officially started 2022-01-01, merge of two former Max-Planck institutes))
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://en.wikipedia.org/wiki/Max_Planck_Institute_for_Biophysical_Chemistry
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Max Planck Institut für Multidisziplinäre Naturwissenschaften
Acronym/abbreviation: MPINAT
Related organizations: 
City: Göttingen
Country: Germany
Year established: 2022
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request: The institute was formed by merging two other Max-Planck-Institutes (Max Planck Institute for Biophysical Chemistry (https://ror.org/03e76ya46), Max Planck Institute of Experimental Medicine (https://ror.org/04a7f6w43), see separate ROR Request)

**Comment by adambuttrick** [comment]
Links on ROR records fo Max Planck Institute for Biophysical Chemistry( https://ror.org/03e76ya46) and Max Planck Institute of Experimental Medicine (https://ror.org/04a7f6w43),  now redirect to the Max Planck Institute for Multidisciplinary Sciences. Merger is described there as well.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03av75f26 in release v1.0.
