### ISSUE TITLE
Modify the information in an existing ROR record: Shenzhen Municipal People's Government https://ror.org/05rcfc739

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4236]
Summary of request: Modify the information in an existing ROR record

Name of organization: Shenzhen Municipal People's Government
ROR ID: https://ror.org/05rcfc739
Which part of the record needs to be changed? External IDs
Description of change: Add Funder ID 100017127

Update: add.FundRef==100017127;$

**Comment by adambuttrick** [comment]
Record updated in release v1.28.
