### ISSUE TITLE
Merge two or more ROR records: Max Planck Institute for Biophysical Chemistry, Max Planck Institute of Experimental Medicine

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#424]
Summary of request: Merge two or more ROR records

Name of organizations: Max Planck Institute for Biophysical Chemistry, Max Planck Institute of Experimental Medicine
ROR IDs: https://ror.org/04a7f6w43  https://ror.org/03e76ya46
Which part of the record needs to be changed? 
Description of change: Merge and deprecate records for Max Planck Institute for Biophysical Chemistry and the Max Planck Institute of Experimental Medicine, following their merger into a single institution. See [Issue #423](https://github.com/ror-community/ror-updates/issues/423) for details of the merger.

**Comment by adambuttrick** [comment]
Require we have the ability to deprecate records in Leo.

**Comment by adambuttrick** [comment]
Addressed with #1727 and #1728.
