### ISSUE TITLE
Add a new organization to ROR: 
 
Universitätsverlag Kiel | Kiel University Publishing

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#425]
Summary of request: Add a new organization to ROR

Name of organization: 
ROR ID: 
Which part of the record needs to be changed? 
Description of change: 

Name of organization: Universitätsverlag Kiel | Kiel University Publishing
Website: https://www.universitaetsverlag.uni-kiel.de/de
Link to publications:  10.38072/2748-3150/v1
Organization type: Archive (An organization involved in stewarding research and cultural heritage materials. Includes libraries, museums, and zoos)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Universitätsverlag Kiel | Kiel University Publishing
Acronym/abbreviation: Universitätsverlag Kiel | Kiel University Publishing
Related organizations: https://ror.org/04v76ef78
City: Kiel
Country: Germany
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for research publications, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
Not certain whether this sufficiently constitutes an independent, top-level entity. From the org's "Publishing" page:

"The services of Kiel University Publishing are available to all members and affiliates of Kiel University, as described in the constitution (basic rules, PDF, § 4). This means that researchers from Kiel University must be involved in all publications, whether as authors or editors. Within the publication projects, they are therefore the main contact persons of the publishing team."

I can likewise find no affiliation usage for the press itself, which corresponds with the above (authors and editors would likely identify with Kiel University instead). In addition, Kiel University is already represented in ROR (https://ror.org/04v76ef78).

**Comment by OAIWetz** [comment]
Dear ror team,
just added new record to wikidata
https://www.wikidata.org/wiki/Q110621719

best regards, Thorsten Wetzenstein

**Comment by arthurpsmith** [comment]
Note their contact page says they are "c/o Universitätsbibliothek Kiel" - and the about page also mentions the publishing service is provided by the library. So not only is this clearly not an independent "top-level" organization, there's another layer between it and the university which we don't have in ROR either (German Wikipedia has an entry for the library at least: https://de.wikipedia.org/wiki/Universitätsbibliothek_Kiel). So I'm afraid this is definitely out of ROR's current scope. If and when we support subunits of research organizations then this is a likely useful addition, but not right now.
