### ISSUE TITLE
Add a new organization to ROR: 
 
Institute of Radio and Information Systems (IRIS)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#426]
Summary of request: Add a new organization to ROR

Name of organization: Institute of Radio and Information Systems (IRIS)
Website: http://media-publisher.eu/
Link to publications: 10.1109/EMCTECH53459.2021.9619166
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/Q110584472
ISNI ID: https://isni.org/isni/0000000505937764
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Institut für Radio- und Informationssysteme – IRIS
Acronym/abbreviation: IRIS
Labels: Institut für Radio- und Informationssysteme – IRIS (German)
Related organizations: 
City: Vienna
Country: Austria
Geonames ID: 2761369
Year established: 2019
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by arthurpsmith** [comment]
I added Wikidata and ISNI id's for this. The related organization "Media Publisher LLC" seems to be based in Russia - see https://www.wikidata.org/wiki/Q110586198 for example - I assume that was where the journal started, before IRIS was organized. Maybe the organizers moved from Moscow to Vienna in or before 2019?

All that might put me in favor of waiting on this one, but they are publishing in IEEE journals, so in the end I think we should proceed with adding this to ROR now.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04yy4tq26 in release v1.0.
