### ISSUE TITLE
Modify the information in an existing ROR record: 
Okinawa Institute of Science and Technology https://ror.org/02qg15b79


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#427]
Summary of request: Modify the information in an existing ROR record

Name of organization: Okinawa Institute of Science and Technology
ROR ID: https://ror.org/02qg15b79
Which part of the record needs to be changed? Primary name
Description of change: Changing the primary name from "Okinawa Institute of Science and Technology" to "Okinawa Institute of Science and Technology Graduate University"

Update: change.name==Okinawa Institute of Science and Technology Graduate University; delete.aliases==Okinawa Institute of Science and Technology Graduate University; add.aliases==Okinawa Institute of Science and Technology;

**Comment by adambuttrick** [comment]
Name change corresponds to English display form on the org site's header and footer:

https://www.oist.jp/

Japanese form also includes "Graduate University" :

沖縄科学技術**大学院大学**

Likewise, this form already exists as a label on the record itself:

https://ror.org/02qg15b79

**Comment by arthurpsmith** [comment]
Agreed. We don't need to keep the current label at all I think as it's just a substring of the correct full name.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
