### ISSUE TITLE
Modify the information in an existing ROR record: 
Royal Botanic Gardens https://ror.org/00ynnr806


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#428]
Summary of request: Modify the information in an existing ROR record

Name of organization: Royal Botanic Gardens
ROR ID: https://ror.org/00ynnr806
Which part of the record needs to be changed? Primary name
Description of change: The name needs to change to 'Royal Botanic Gardens, Kew' as per their official website.
Other information about this request: This has been raised to us by colleagues at Royal Botanic Gardens, Kew and as we use ROR in our organisation database it would be good to fix at source.

Update: change.name==Royal Botanic Gardens, Kew;

**Comment by adambuttrick** [comment]
"Royal Botanic Gardens, Kew" is used in Crossref funder record, Wikidata, as well as in the copyright statement on the org's site (https://www.kew.org/). I see no reason why not to update.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
