### ISSUE TITLE
Add a new organization to ROR: Australian Plant Phenomics Facility

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#43]
Summary of request: Add a new organization to ROR

Name of organization: Australian Plant Phenomics Facility
Website: https://www.plantphenomics.org.au/
Link to publications: https://www.plantphenomics.org.au/resources/#research-publications
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: APPF
Related organizations: 
City: Adelaide
Country: Australia
Other information about this request:

**Comment by carlyrobinson** [comment]
Agree with @arthurpsmith. Should be added to ROR - using as affiliation, separate website domain, separate branding.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02zj7b759 in release v1.0.
