### ISSUE TITLE
Add a new organization to ROR: 
 
Axiom Data Science

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#430]
Summary of request: Add a new organization to ROR

Name of organization: Axiom Data Science
Website: www.axiomdatascience.com
Link to publications: https://spillanddrift.srv.axds.co/
Organization type: Other (Use this category for any organization that does not fit the categories above)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: none
Acronym/abbreviation: AXDS
Related organizations: 
City: Anchorage
Country: United States
Year established: 2007
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility
Other information about this request: I can send a bunch more links or URLs if necessary. The one include in the form is for a research and analysis product, but we're also the metadata contact in a few hundred records in the DataONE network (most of which are in the Research Workspace DataONE Member Node). Let me know what other information I can provide.

**Comment by adambuttrick** [comment]
This appears to be an organization that is involved with providing data services and dataset hosting for a variety of federal, private, academic and non-governmental organizations. It is not already in ROR. It is in scope for ROR because it:

    -is an established organization
    -is a top-level organization and not a subsidiary unit
    -is associated with research publications and/or other activities (https://scholar.google.com/citations?user=l2E5TFMAAAAJ ; https://scholar.google.com/citations?user=HZDH3hIAAAAJ) Similar records in ROR: Mountain Data Group (https://ror.org/01sah3s84), Dragonfly Data Science (https://ror.org/00jsnkt88)

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02f4ks689 in release v1.0.
