### ISSUE TITLE
Add a new organization to ROR: 
 
Institute of Slavonic Studies

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#431]
Summary of request: Add a new organization to ROR

Name of organization: 
ROR ID: 
Which part of the record needs to be changed? 
Description of change: 

Name of organization: Institute of Slavonic Studies
Website: http://www.slu.cas.cz/
Link to publications: https://doi.org/10.31577/slovlit.2021.68.6.510.31577/slovlit.2021.68.6.5
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://cs.wikipedia.org/wiki/Slovansk%C3%BD_%C3%BAstav_Akademie_v%C4%9Bd_%C4%8Cesk%C3%A9_republiky
Wikidata ID: 
ISNI ID: https://isni.org/isni/0000000404287272
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Slovanský ústav Akademie věd České republiky
Acronym/abbreviation: SLÚ AV ČR
Related organizations: Czech Academy of Sciences
City: Prague
Country: Czech Republic
Year established: 1922
How will a ROR ID for this organization be used? to help put the contents of the Czech national CRIS in an international context, see https://github.com/jdvorak001/isvavai-orgs-ror-mapping
Other information about this request: The institute's English production is rather scarce, which is probably why it hasn't been included yet. However, it is one of the institutes of the Czech Academy of Sciences, https://www.avcr.cz/en/about-us/cas-structure/research-institutes/, and actually the only one missing a ROR id. See https://github.com/jdvorak001/isvavai-orgs-ror-mapping

**Comment by adambuttrick** [comment]
This record already exists in ROR under the name, "Slovanský Ústav" (https://ror.org/03qq0n189). At the minimum, we should probably update the record to reflect the full English name and its Czech form (Slovanský ústav Akademie věd České republiky), but it would be good to purse a consistent relationship across all records for the Czech Academy of Sciences.

**Comment by jdvorak001** [comment]
Oh, how could I have failed to find that if it has a Czech name! Thank you very much.
