### ISSUE TITLE
Add a new organization to ROR - Academia Joven de España

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4318]
Summary of request: Add a new organization to ROR

Name of organization: Academia Joven de España
Website: https://academiajoven.es
Link to publications:
Organization type: Other
Wikipedia page: https://es.wikipedia.org/wiki/Academia_Joven_de_Espa%C3%B1a
Wikidata ID: Q104380044
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: Young Academy of Spain
Labels:
Acronym/abbreviation: 
Related organizations: 
City: Madrid
Country: Spain
Geonames ID: 3117735
Year established: 2019
Other information about this request:

**Comment by adambuttrick** [comment]
Scientific advocacy organization in Spain formed by the Spanish government in response to their involvement with https://github.com/ror-community/ror-updates/issues/4319. No affiliation usage I can find, but believe this is fine to add by virtue of its ties to Spain's Ministry of Education.

**Comment by mariagould** [comment]
I think this is fine to add given evidence of research-oriented activities.
