### ISSUE TITLE
Add a new organization to ROR: 
 
DevScope

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#432]
Summary of request: Add a new organization to ROR

Name of organization: 
ROR ID: 
Which part of the record needs to be changed? 
Description of change: 

Name of organization: DevScope
Website: https://www.devscope.net
Link to publications: https://www.jpathinformatics.org/text.asp?2020/11/1/30/295359
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: DevScope
Acronym/abbreviation: DevScope
Related organizations: 
City: Porto
Country: Portugal
Year established: 2003
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders
Other information about this request:

**Comment by adambuttrick** [comment]
Aside from the link provided, I can find no other affiliation usage. There is nothing in ORCID and only a single Google Scholar profile, for which all the linked articles use the author's university affiliation, not DevScope:

https://scholar.google.com/citations?user=XZ9Mon8AAAAJ

If they are sponsoring research, we would need additional examples.

**Comment by arthurpsmith** [comment]
Searching Google Scholar for this name is a little confusing because there seems to be also some sort of device called "DevScope" used in research, which appears to be completely unrelated. Anyway, yes the only research articles I could find with this affiliation were by the same person. I agree out of scope for now.
