### ISSUE TITLE
Project: Standardize representation of records for the Czech Academy of Sciences 

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#433]
The records for the Czech Academy of Sciences have inconsistent representations, impeding discovery in ROR. See [Issue #431](https://github.com/ror-community/ror-updates/issues/431) for an example.

A ROR user has created a full mapping of our data with these institutions (https://github.com/jdvorak001/isvavai-orgs-ror-mapping/blob/main/organizations.csv), whose work and expertise we should consider consulting. What appears to be official English names are also linked here: https://www.avcr.cz/en/about-us/cas-structure/research-institutes/

**Comment by jdvorak001** [comment]
I agree this would be useful.
Adding the "... of the CAS" suffixes would help, otherwise the names are sometimes rather generic.

I will be happy to assist.

**Comment by adambuttrick** [comment]
Records updated as part of release v1.1.
