### ISSUE TITLE
Add a new organization to ROR: Center for Psychotherapy Research

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4354]
Summary of request: Add a new organization to ROR

Name of organization: Forschungsstelle für Psychotherapie
Website: https://www.klinikum.uni-heidelberg.de/zentrum-fuer-psychosoziale-medizin-zpm/institut-fuer-psychosoziale-praevention/forschung/forschungsstelle-fuer-psychotherapie-fost/wir-ueber-uns
Link to publications: https://www.klinikum.uni-heidelberg.de/zentrum-fuer-psychosoziale-medizin-zpm/institut-fuer-psychosoziale-praevention/forschung/forschungsstelle-fuer-psychotherapie-fost/publikationen
Organization type: Facility
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: Center for Psychotherapy Research
Labels: 
Acronym/abbreviation: FOST
Related organizations: https://ror.org/013czdx64 (parent)  
City: Heidelberg
Country: Germany
Geonames ID: 2907911
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: Part of https://github.com/ror-community/ror-updates/issues/4083.

**Comment by adambuttrick** [comment]
From all appearances, a research group at the Center for Psychosocial Medicine (not in ROR) at https://ror.org/013czdx64. Although this appears to have operated more autonomously in the past, I think its now to far down the hierarchy to add to ROR. There's a better argument for adding the Center for Psychosocial Medicine, as https://ror.org/013czdx64 various facilities are already disambiguated from the parent.

**Comment by arthurpsmith** [comment]
Agreed this is not in scope; affiliation usage always appears to include the university hospital (and doesn't seem to mention the "Center for Psychosocial Medicine" so I don't think that is an issue here).
