### ISSUE TITLE
Add a new organization to ROR: 
 
Invest in Open Infrastructure

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#437]
Summary of request: Add a new organization to ROR

Name of organization: Invest in Open Infrastructure
Website: https://investinopen.org
Link to publications: https://doi.org/10.5281/zenodo.4056882 ; https://doi.org/10.5281/zenodo.4056901
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page:
Wikidata ID: https://www.wikidata.org/wiki/Q75736561
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Acronym/abbreviation: IOI
Related organizations: Code for Science & Society https://ror.org/01dmavx46 (related)
City: New York, New York
Country: USA
Geonames ID: 5128581
Year established: 2019
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders
Other information about this request:

**Comment by adambuttrick** [comment]
Funds and publishes research (e.g. https://zenodo.org/record/4159838) advocating for the adoption of open source technology and standards, including a recommended catalog of data sources that includes ROR stakeholders (Crossref and DataCite). Seems a pretty straightforward case for inclusion in ROR.

**Comment by KellyStathis** [comment]
Agree this is a straightforward case for inclusion, and metadata looks good!

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0588n4k65 in release v1.0.
