### ISSUE TITLE
Add a new organization to ROR: Institute for Legal Policy

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4370]
Summary of request: Add a new organization to ROR

Name of organization: Institut für Rechtspolitik an der Universität Trier 
Website: https://www.uni-trier.de/universitaet/fachbereiche-faecher/fachbereich-v/forschung/irp
Link to publications: https://www.uni-trier.de/universitaet/fachbereiche-faecher/fachbereich-v/forschung/irp/publikationen
Organization type: Facility
Wikipedia page: 
Wikidata ID: Q17486138
ISNI ID: 0000 0001 2369 498X
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases:Institut für Rechtspolitik; Institute for Legal Policy
Labels: 
Acronym/abbreviation: IRP
Related organizations: https://ror.org/02778hg05 (parent)
City: Trier
Country: Germany
Geonames ID: 2821164
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: Part of https://github.com/ror-community/ror-updates/issues/4083.

**Comment by adambuttrick** [comment]
Legal research institute in Germany. Funds and employs researchers. Solid affiliation usage. Not certain what degree of separation this has (if any) from its parent organization. Some of the description appears to suggest a degree of autonomy, but not certain. @MSpenger Could you take a look at this one?

**Comment by MSpenger** [comment]
It looks like this request qualifies for a ROR entry. It is an institute linked to Uni Trier (https://www.uni-trier.de/universitaet/fachbereiche-faecher/fachbereich-v/forschung) through a cooperation agreement. They also have a cooperation agreement with the Gesellschaft für Rechtspolitik.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01z5ygt35 in release v1.29.
