### ISSUE TITLE
Add a new organization to ROR: Juris GmbH

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4377]
Summary of request: Add a new organization to ROR

Name of organization: Juris (Germany)
Website: https://www.juris.de
Link to publications: 
Organization type: Company
Wikipedia page: 
Wikidata ID: 
ISNI ID: 0000 0001 0944 7691
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: Juris; Juris GmbH; Juris GmbH  – Juristisches Informationssystem für die Bundesrepublik Deutschland, Saarbrücken
Labels: 
Acronym/abbreviation: 
Related organizations:   
City: Saarbrücken
Country: Germany
Geonames ID: 2842647
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: Part of https://github.com/ror-community/ror-updates/issues/4083.

**Comment by adambuttrick** [comment]
Legal information system for the Federal Republic of Germany. No affiliation usage I can find. Seems similar to LexisNexis in the US context. Not certain how appropriate this is for ROR. @MSpenger could you weigh in on this one?

**Comment by MSpenger** [comment]
Also couldn't find an affiliation usage and I would put this request on hold for now.

Wikidata is available: https://www.wikidata.org/wiki/Q1703172

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/015dvgv60 in release v1.29.
