### ISSUE TITLE
Add a new organization to ROR: University of Church Music of the Evangelical Church of Westphalia

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4379]
Summary of request: Add a new organization to ROR

Name of organization: Hochschule für Kirchenmusik der Evangelischen Kirche von Westfalen
Website: https://www.hochschule-kirchenmusik.de
Link to publications: 
Organization type: Education
Wikipedia page: 
Wikidata ID: Q1622191
ISNI ID: 0000 0004 7470 8933
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: Landeskirchenmusikschule; Hochschule für Kirchenmusik Herford; Hochschule für Kirchenmusik Herford-Witten
Labels: University of Church Music of the Evangelical Church of Westphalia*English
Acronym/abbreviation: 
Related organizations: https://ror.org/03d0tpz61 (parent)
City: Hereford
Country: Germany
Geonames ID: 6557621
Year established: 1948
How will a ROR ID for this organization be used? 
Other information about this request: Part of https://github.com/ror-community/ror-updates/issues/4083.

**Comment by adambuttrick** [comment]
Music school in Germany. Seems long-standing and well-established, but no research outputs I can find. Given its practical focus, I suppose that may be unsurprising, but would still appreciate a second review to confirm this is in scope. @MSpenger Apologies for leaning on you for all of these requests from Germany, but could you take a look?

**Comment by MSpenger** [comment]
Publication affiliation usage: https://ixtheo.de/Record/1646908759 or https://d-nb.info/356149803

Apparently it was renamed twice in the past: Landeskirchenmusikschule (1948), Hochschule für Kirchenmusik Herford (1991), Hochschule für Kirchenmusik Herford-Witten (2016)

In this case, the parent organization would be: https://ror.org/03d0tpz61 
And City and Geonames should also be adjusted:
City: Hereford
Geonames ID: 6557621

Would recommend creating a ROR entry for this organization and for #4381 .

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0446hjy70 in release v1.29.
