### ISSUE TITLE
Modify the information in an existing ROR record: 
Swiss Federal University for Vocational Education and Training https://ror.org/00zg4za48


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#438]
Summary of request: Modify the information in an existing ROR record

Name of organization: Swiss Federal University for Vocational Education and Training
ROR ID: https://ror.org/00zg4za48
Which part of the record needs to be changed? Organization website
Description of change: please use https://www.sfuvet.swiss/ instead of http://www.ehb-schweiz.ch/en/
Update: delete.links==http://www.ehb-schweiz.ch/en/; add.links==https://www.sfuvet.swiss/;

**Comment by adambuttrick** [comment]
Link in ROR resolves to a 404, while the one provided by requestor does to an English-language page for the university.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
