### ISSUE TITLE
Add a new organization to ROR: University of Church Music of the Diocese of Rottenburg-Stuttgart

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4381]
Summary of request: Add a new organization to ROR

Name of organization: Hochschule für Kirchenmusik der Diözese Rottenburg-Stuttgart
Website: https://www.kirchenmusik-hochschule.org
Link to publications: 
Organization type: Education
Wikipedia page: 
Wikidata ID: Q1736343
ISNI ID: 0000 0004 7470 8925
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: 
Labels: University of Church Music of the Diocese of Rottenburg-Stuttgart*English
Acronym/abbreviation: 
Related organizations:   
City: Rottenburg-Stuttgart
Country: Germany
Geonames ID: 2843729
Year established: 1949
How will a ROR ID for this organization be used? 
Other information about this request: Part of https://github.com/ror-community/ror-updates/issues/4083.

**Comment by adambuttrick** [comment]
Music school in Germany. Seems long-standing and well-established, but has a single instance of affiliation usage. Given its practical focus, this may be fine, but will process in tandem with determination on https://github.com/ror-community/ror-updates/issues/4379.

**Comment by MSpenger** [comment]
This request is also in scope as it is a similar organization as #4379 .

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04e7egx43 in release v1.29.
