### ISSUE TITLE
Add a new organization to ROR: Brandon Capital Partners 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#44]
Summary of request: Add a new organization to ROR

Name of organization: Brandon Capital Partners 
Website: https://www.brandoncapital.com.au/
Link to publications: https://www.brandoncapital.com.au/investment-portfolio/
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: 
Country: 
Other information about this request:

**Comment by carlyrobinson** [comment]
Agree that this is not within scope. I could find no evidence of the organization's involvement in scholarly research.
