### ISSUE TITLE
Modify the information in an existing ROR record: 
German Climate Computing Centre https://ror.org/03ztgj037


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#440]
Summary of request: Modify the information in an existing ROR record

Name of organization: German Climate Computing Centre
ROR ID: https://ror.org/03ztgj037
Which part of the record needs to be changed? Organization website
Description of change: The correct web address would be https://www.dkrz.de

Update: delete.links==http://www.dkrz.de/dkrz-en?set_language=en; add.links==https://www.dkrz.de;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
