### ISSUE TITLE
Add a new organization to ROR: 
 
BAHAMAS ADVANCED INSTITUTE AND CONFERENCES

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#441]
Summary of request: Add a new organization to ROR

Name of organization: 
ROR ID: 
Which part of the record needs to be changed? 
Description of change: 

Name of organization: Bahamas Advanced Institute and Conferences
Website: https://cgc.physics.miami.edu/BASIC.html
Link to publications: https://www.natureindex.com/country-outputs/Bahamas  ,    https://www.natureindex.com/institution-outputs/bahamas/bahamas-advanced-study-institute-and-conferences-basic/5dca705895f5851de32e4942  ,     https://www.natureindex.com/article/10.1140/epjc/s10052-021-09646-z
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Bahamas Advanced Study and College
Acronym/abbreviation: BASIC
Related organizations: 
City: Stella Maris, Long Island
Country: Bahamas
Year established: 2016
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by adambuttrick** [comment]
Not certain whether this is a sufficiently established organization. It appears to be a yearly conference held in the Bahamas with the intent of establishing a research institute there. From the organization's description of itself on the website: "This is a proposal to create a center for theoretical research and training of advanced students and postdoctoral scientists at a location on Long Island, Bahamas.  Funding for the center will come from international foundations and other private sources." Very limited publication usage as well, generally as a secondary affiliation, e.g.: https://link.springer.com/article/10.1140%2Fepjc%2Fs10052-021-09646-z

**Comment by arthurpsmith** [comment]
I've heard of this before, it's been around for a while as a conference series (since 2016). But I think it's a one-person project - Guendelman is the one who's been using it as an affiliation, and from Google Scholar it's on 4 or 5 papers at most. If it really does create an institute as proposed then we can add to ROR then; we can move it to "on hold" for now, but I think it's likely to remain out of scope for at least a few more years.

**Comment by adambuttrick** [comment]
Declining this as out of scope, as it is both a one-person organization and has no new affiliation usage. Should the institute ever be built, they can resubmit.
