### ISSUE TITLE
Project: Long Term Ecological Research Network Members

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#442]
The request for US-based Long Term Ecological Research Network Members (#197) indicates several other members that are not currently represented in ROR. A request to add Beaufort Lagoon Ecosystem (#32) has already been approved, but we would need to investigate whether the remainder are in scope, along with gathering their corresponding metadata. All would likewise need to be represented as children of #197. Organzations as listed in the original request are provided below.

Andrews Forest
Arctic LTER
Baltimore Ecosystem Study
Beaufort Lagoon Ecosystem
Bonanza Creek LTER
Central Arizona - Phoenix
Central Plains Experimental Range
California Current Ecosystem
Cedar Creek Ecosystem Science Reserve
Coweeta LTER
Florida Coastal Everglades
Georgia Coastal Ecosystems
Harvard Forest
Hubbard Brook Experimental Forest LTER
Jornada Basin LTER
Kellogg Biological Station
Konza Prairie
Luquillo Experimental Forest
McMurdo Dry Valleys
Minneapolis St. Paul LTER
Mo'orea Coral Reef
Niwot Ridge LTER
North Temperate Lakes
Northeast U.S. Shelf LTER
Northern Gulf of Alaska LTER
Palmer Station Antarctica
Plum Island Ecosystem
Santa Barbara Coastal
Sevilleta National Wildlife Refuge
Shortgrass Steppe LTER
Virginia Coast Reserve Long-Term Ecological Research

**Comment by adambuttrick** [comment]
Records created as part of release v1.1.

ROR ID | Organization name
-- | --

https://ror.org/026jqvs13 | Andrews Forest Long Term Ecological Research
https://ror.org/04pk7zz41 | Arctic Long Term Ecological Research
https://ror.org/01nysf027 | Bonanza Creek Long Term Ecological Research
https://ror.org/010dcp921 | California Current Ecosystem Long Term Ecological Research
https://ror.org/03a976s92 | Cedar Creek Long Term Ecological Research
https://ror.org/020zjmd13 | Central Arizona–Phoenix Long Term Ecological Research
https://ror.org/03davk141 | Florida Coastal Everglades Long Term Ecological Research
https://ror.org/017bfx208 | Georgia Coastal Ecosystems Long Term Ecological Research
https://ror.org/059cpzx98 | Harvard Forest Long Term Ecological Research
https://ror.org/00mkh7345 | Hubbard Brook Long Term Ecological Research
https://ror.org/05976ta47 | Jornada Basin Long Term Ecological Research
https://ror.org/02vkce854 | Kellogg Biological Station Long Term Ecological Research
https://ror.org/02wavzm11 | Konza Prairie Long Term Ecological Research
https://ror.org/00krzbm55 | Luquillo Long Term Ecological Research
https://ror.org/04r3s7465 | McMurdo Dry Valleys Long Term Ecological Research
https://ror.org/04sqxdt31 | Minneapolis-St. Paul Long Term Ecological Research
https://ror.org/017vyhs10 | Moorea Coral Reef Long Term Ecological Research
https://ror.org/02ep77d74 | Niwot Ridge Long Term Ecological Research
https://ror.org/04gq8q482 | North Temperate Lakes Long Term Ecological Research
https://ror.org/04sj20m66 | Northeast U.S. Shelf Long Term Ecological Research
https://ror.org/01csn4944 | Northern Gulf of Alaska Long Term Ecological Research
https://ror.org/0139hn422 | Palmer Long Term Ecological Research
https://ror.org/052tfzs89 | Plum Island Ecosystems Long Term Ecological Research
https://ror.org/05hnkta08 | Santa Barbara Coastal Long Term Ecological Research
https://ror.org/01qcacz92 | Sevilleta Long Term Ecological Research
https://ror.org/013zder45 | Virginia Coast Reserve Long Term Ecological Research

**Comment by marty-downs** [comment]
Awesome! Thanks.
Thanks,
Marty
---
Marty Downs (she/her)
617-833-7930 (m)
