### ISSUE TITLE
Modify the information in an existing ROR record: Department of Education, Skills and Employment https://ror.org/02wa0fq92

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#4421]
Summary of request: Modify the information in an existing ROR record

Name of organization: Department of Education, Skills and Employment
ROR ID: https://ror.org/02wa0fq92
Which part of the record needs to be changed? Name, External IDs, website
Description of change: Per order of the Australian government, this department was reconfigured in 2022 and the following metadata needs to be updated:
(1) Update name: Department of Employment and Workplace Relations
(2) Replace links: https://www.dewr.gov.au/
(3) Add Funder ID 501100000937

Update: change.name==Department of Employment and Workplace Relations; replace.links==https://www.dewr.gov.au; add.FundRef==501100000937;$

**Comment by adambuttrick** [comment]
Record updated in release v1.29.
