### ISSUE TITLE
Add a new organization to ROR: 
 
Centre for Environmental Data Analysis (CEDA) 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#443]
Summary of request: Add a new organization to ROR

Name of organization: Centre for Environmental Data Analysis
Website: https://www.ceda.ac.uk/
Link to publications: 10.5281/zenodo.5592466
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://en.wikipedia.org/wiki/Centre_for_Environmental_Data_Analysis
Wikidata ID: Q48815787
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: CEDA
Acronym/abbreviation: CEDA
Related organizations: https://ror.org/02b5d8509 (related)
City: Harwell
Country: UK
Geonames ID: 2647384
Year established: 2005
How will a ROR ID for this organization be used? To identify affiliations for datasets, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
Hosts datasets and provides technical research support for the UK's Natural Environment Research Council (https://ror.org/02b5d8509 ), so seems clearly in scope. 

google scholar affiliation usage: https://scholar.google.com/citations?user=nSTeJ2YAAAAJ
publication usage: https://centaur.reading.ac.uk/90006/1/1137-7373-1-PB.pdf ; https://academic.oup.com/rev/article/30/2/169/6048418?login=true

**Comment by arthurpsmith** [comment]
Yes, agreed it should be in ROR.
I think the established date should be 2005; however it was formed by joining two previously existing data centres - BADC and NEODC, with BADC having a long history (and an ISNI id:  ISNI 0000 0004 5900 5324). Also their history page goes back to 1984: https://www.ceda.ac.uk/about/history/ But 2005 seems to be when the current name was taken on (or close to the current name) so maybe that's the best date to set here. If we need one.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04j4kad11 in release v1.0.
