### ISSUE TITLE
Modify the information in an existing ROR record: York College https://ror.org/022jz8688

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#4450]
Summary of request: Modify the information in an existing ROR record

Name of organization: York College
ROR ID: https://ror.org/022jz8688
Which part of the record needs to be changed? Name
Description of change: In late 2021 York College in York, Nebraska in the United States changed its name to York University. The name York College should be stored as a previous name in aliases. See https://www.york.edu/about/our-history.php 

Update: change.name==York University; add.aliases==York College;$

**Comment by adambuttrick** [comment]
Record updated in release v1.29.
