### ISSUE TITLE
Add a new organization to ROR: 
 
Academician F. H. Burchak Scientific-Research Institute of Private Law and Entrepreneurship

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#446]
Summary of request: Add a new organization to ROR

Name of organization: Academician F. H. Burchak Scientific-Research Institute of Private Law and Entrepreneurship
Website: https://ndippp.gov.ua/
Link to publications: https://scholar.google.com.ua/citations?hl=ru&user=fILKwgBRKckC; https://www.scopus.com/affil/profile.uri?afid=60212803
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://uk.wikipedia.org/wiki/Науково-дослідний_інститут_приватного_права_і_підприємництва_імені_академіка_Ф._Г._Бурчака
Wikidata ID: Q16708724
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Науково-дослідниq інститут приватного права і підприємництва імені академіка Ф. Г. Бурчака
Labels: Науково-дослідниq інститут приватного права і підприємництва імені академіка Ф. Г. Бурчака (Ukrainian)
Acronym/abbreviation: NDIPPP
Aliases: Academician F. H. Burchak Scientific-Research Institute of Private Law and Entrepreneurship of National Academy of Law Sciences of Ukraine
Related organizations:
City: Kyiv
Country: Ukraine
Geonames ID: 703448
Year established: 1996
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge a research facility
Other information about this request:

**Comment by adambuttrick** [comment]
State scientific and research institution focused on Ukrainian law, and also part of the National Academy of Legal Sciences of Ukraine. Seems in scope. My only question would be on the primary name, as there is varying English representation. Should this be what the requestor has provided, or the full form that appears on publications, "The Academician F. H. Burchak Scientific-Research Institute of Private Law and Entrepreneurship of National Academy of Law Sciences of Ukraine"?

Publication affiliation usage: https://iusprivatumjournal.online/en-editorial-board ; https://pubmed.ncbi.nlm.nih.gov/35029582/

Google Scholar affiliation usage: https://scholar.google.com/citations?user=19EvCn-VR6UC; https://scholar.google.com/citations?user=gI41qtcAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0003-3973-715X ; https://orcid.org/0000-0002-3239-1216 ; https://orcid.org/0000-0001-6578-1491 ;

**Comment by arthurpsmith** [comment]
Hi Adam - other than in the request form, where did you see that this was part of the "National Academy of Sciences of Ukraine" (for which we have a ROR id)? Everywhere I look on this, including in the full affiliation names, it seems to be just part of the "National Academy of Legal Sciences of Ukraine". I agree that should be in ROR, and I think this should be also, given how we handle other institutes of national academies. Also I think we generally don't use those "full form" names as main labels, but it could be an alternate label.

Anyway, other than the relationship to https://ror.org/00je4t102 as a parent organization, I think this is ready to be added here.

**Comment by adambuttrick** [comment]
@arthurpsmith I was extrapolating from the National Academy of Legal Sciences being hosted on the National Academy of Sciences site (https://www.nas.gov.ua/EN/Org/Pages/default.aspx?OrgID=0000661), but now agree tgat you're correct that the appropriate parent would be the National Academy of Legal Sciences (for which we would need to create a record). Moving to approved and will create an issue for National Academy of Legal Sciences.

**Comment by adambuttrick** [comment]
Created #450 for the parent record.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02hhf2525 in release v1.0.
