### ISSUE TITLE
Add a new organization to ROR: Lexical Computing

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#448]
Summary of request: Add a new organization to ROR

Name of organization: Lexical Computing CZ

Website: https://www.lexicalcomputing.com
Link to publications: See articles written by key personnel:
https://scholar.google.com/citations?user=O6_44PwAAAAJ
https://scholar.google.com/citations?user=mF_yu7wAAAAJ
https://scholar.google.com/citations?user=AQJK5pMAAAAJ
https://scholar.google.com/citations?user=P1R68loAAAAJ

Wikipedia page:
Wikidata ID:  https://www.wikidata.org/wiki/Q45027067
ISNI ID: https://isni.org/isni/0000000473882649
GRID ID:
Crossref Funder ID:
Ringgold ID:
Other names for the organization:
Acronym/abbreviation:
Related organizations: https://ror.org/issue59 (parent)
City: Brno
Country: Czech Republic
Geonames ID: 3078610
Other information about this request: Lexical Computing is small research company founded in 2003 by a UK university professor Adam Kilgarriff. Over the almost 20 years, it has been carrying out research and development in the area of computer lexicography, corpus linguistics and natural language processing.

**Comment by mariagould** [comment]
Per discussion in #59 we plan to create a separate record for the Czech branch of this company. The UK record will be the parent.

**Comment by mariagould** [comment]
This request should be for the Czech branch (child), under the name Lexical Computing CZ. The related record (parent) is captured in #59

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01adbad76 in release v1.0.
