### ISSUE TITLE
Add a new organization to ROR: 
 
Health and Wellbeing Queensland

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#449]
Summary of request: Add a new organization to ROR

Name of organization: Health and Wellbeing Queensland
Website: https://hw.qld.gov.au/
Link to publications: DOI:10.1111/obr.13373     DOI:10.1016/j.appet.2021.105811  
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://en.wikipedia.org/wiki/Health_and_Wellbeing_Queensland
Wikidata ID: Q97474541
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Health + Wellbeing Queensland
Aliases: Health + Wellbeing Queensland
Acronym/abbreviation: HWQld
Related organizations: https://ror.org/00c1dt378 (parent)
City: Brisbane, Queensland
Country: Australia
Geonames ID: 2174003
Year established: 2019
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system, Used in Altmetrics 
Other information about this request:

**Comment by adambuttrick** [comment]
New agency founded in 2019. Funding is provided by Queensland Health (https://ror.org/00c1dt378), which I've listed as parent. Publication affiliation looks solid. Funds and employs researchers.

Google Scholar affiliation usage: https://scholar.google.com/citations?user=7HdW3RAAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0001-5371-4777 ; https://orcid.org/0000-0003-2010-3640

Similar records in ROR: https://ror.org/01cdys993

**Comment by arthurpsmith** [comment]
Fully agree this should be in ROR. Can't find any missing ID's, looks ready to go.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/004edqb24 in release v1.0.
