### ISSUE TITLE
Add a new organization to ROR: 
 
University Museum Utrecht

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#451]
Summary of request: Add a new organization to ROR

Name of organization: University Museum Utrecht
Website: https://umu.nl/
Link to publications: https://www.gbif.org/dataset/39b4ca7a-27f7-4489-8b49-c539144ccdc8
Organization type: Archive (An organization involved in stewarding research and cultural heritage materials. Includes libraries, museums, and zoos)
Wikipedia page: https://nl.wikipedia.org/wiki/Universiteitsmuseum_(Utrecht)
Wikidata ID: https://www.wikidata.org/wiki/Q14510918
ISNI ID: 0000 0001 2110 5571
GRID ID: 
Crossref Funder ID: 
Other names for the organization: Universiteitsmuseum Utrecht
Acronym/abbreviation: UMU
Labels: Universiteitsmuseum Utrecht*Dutch
Related organizations: Utrecht University https://ror.org/04pp8hn57 (parent)
City: Utrecht
Country: The Netherlands
Geonames ID: 2745911
Year established: 1928
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
Publication affiliation:

https://peerj.com/articles/7675/#aff-6

http://yadda.icm.edu.pl/yadda/element/bwmeta1.element.agro-e968e821-7eb8-4081-888a-df10ff94dd33/c/Re-evaluation_of_pachycormid.pdf

https://triggered.edina.clockss.org/ServeContent?url=http://www.gewina-studium.nl%2Farticles%2F10.18352%2Fstudium.10121%2Fprint%2F

Google Scholar Affiliation: https://scholar.google.com/citations?hl=en&user=KQlvSeQAAAAJ

**Comment by nielsraes** [comment]
_How will a ROR ID for this organization be used?_ UMU is one of the [DiSSCo-NL partners](https://www.dissco.eu/nl/) that wants to mobilize their geological data to both GBIF and [GeoCASe](https://www.dissco.eu/nl/). At the level of DiSSCo ROR IDs are identified as institutional IDs, hence the request.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/058kzes98 in release v1.1.
