### ISSUE TITLE
Modify the information in an existing ROR record: 
Akvaplan-niva https://ror.org/03nrps502


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#456]
Summary of request: Modify the information in an existing ROR record

Name of organization: Akvaplan-niva
ROR ID: https://ror.org/03nrps502
Which part of the record needs to be changed? Primary name
Description of change: The name in ROR currently has the suffix " (Norway)" ie "Akvaplan-niva (Norway)", it shoule be just "Akvaplan-niva" as in wikidata: https://www.wikidata.org/wiki/Q11957195

Update: change.name==Akvaplan-niva; delete.links==https://www.akvaplan.niva.no/en; add.links==https://www.akvaplan.niva.no/

**Comment by adambuttrick** [comment]
Name change corresponds to branding on organization's site as well as the copyright statement. I see no instances of foreign subsidiaries in ROR or for the organization itself, so this should be fine to approve. We should also remove the English page reference from the URL.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
