### ISSUE TITLE
Modify the information in an existing ROR record: 
Herder-Institut für Historische Ostmitteleuropaforschung – Institut der Leibniz-Gemeinschaft https://ror.org/00sngv739


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#457]
Summary of request: Modify the information in an existing ROR record

Name of organization: Herder-Institut für Historische Ostmitteleuropaforschung – Institut der Leibniz-Gemeinschaft
ROR ID: https://ror.org/00sngv739
Which part of the record needs to be changed? Other IDs for the organization
Description of change: Please change the ISNI-Number on page https://ror.org/00sngv739
into https://isni.org/isni/0000000121510454
That is the right one for Herder-Institut für Historische Ostmitteleuropaforschung – Institut der Leibniz-Gemeinschaft
Update: delete.ISNI==0000 0001 2296 4132;add.ISNI==0000 0001 2151 0454;delete.links==http://www.herder-institut.de/en/home.html;add.links==http://www.herder-institut.de/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
