### ISSUE TITLE
Add a new organization to ROR: Digital Health Cooperative Research Centre

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#46]
Summary of request: Add a new organization to ROR

Name of organization:  Digital Health Cooperative Research Centre
Website: https://www.digitalhealthcrc.com
Link to publications: https://www.digitalhealthcrc.com/hms-data-sets/
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: Digital Health, Digital Health CRC
Acronym/abbreviation: 
Related organizations: parent org is Australian Dept of Industry, Science, Energy and Resources, which is grid.495818.9 - also should be https://ror.org/056naxb15 
City: Sydney
Country: Australia
Other information about this request:

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02n8xct56 in release v1.0.
