### ISSUE TITLE
Modify the information in an existing ROR record: 
Etymotic Research (United States) https://ror.org/01n2k7643


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#460]
Summary of request: Modify the information in an existing ROR record

Name of organization: Etymotic Research (United States)
ROR ID: https://ror.org/01n2k7643
Which part of the record needs to be changed? Other IDs for the organization
Description of change: currently have these ids:
ISNI Q30256598
Wikidata 0000 0004 0369 3287
should be changed to:
ISNI 0000 0004 0369 3287
Wikidata Q30256598
Other information about this request: I have seen several things to modify in ror. They tell me if they want me to contribute more.

Update: change.Wikidata==Q30256598; change.ISNI==0000 0004 0369 3287;

**Comment by adambuttrick** [comment]
ISNI and Wikidata values are inverted, as the request describes.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
