### ISSUE TITLE
Modify the information in an existing ROR record: 
Federal Maritime and Hydrographic Agency of Germany https://ror.org/03ycvrj88


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#461]
Summary of request: Modify the information in an existing ROR record

Name of organization: Federal Maritime and Hydrographic Agency of Germany
ROR ID: https://ror.org/03ycvrj88
Which part of the record needs to be changed? Organization website
Description of change: The website currently named leads into a 404 error, i.e. the website does not exist (anymore). Please replace by: https://www.bsh.de/EN

Update: delete.links==http://www.bsh.de/en/index.jsp; add.links==https://www.bsh.de/;

**Comment by adambuttrick** [comment]
Current URL in ROR does not resolve. Updating to https://www.bsh.de/ , per our policy of using the top-level domain vs. English language page.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
