### ISSUE TITLE
Modify the information in an existing ROR record: 
Institute for Scientific Research on Economic Reforms https://ror.org/05037p730


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#462]
Summary of request: Modify the information in an existing ROR record

Name of organization: Institute for Scientific Research on Economic Reforms
ROR ID: https://ror.org/05037p730
Which part of the record needs to be changed? Primary name, Organization website, Something else
Description of change: The name and address of the Institute registered under the name "Institute for Scientific Research on Economic Reforms" (ID: grid.501766.3) have been changed. Please help us to update the new information about the institute. The new name and address of the institute are as follows:  
Name: Ministry of Economy of the Republic of Azerbaijan  Economic Scientific Research        İnstitute (ESRI)
Street: 196, Hasan Bey Zardabi Avenue, AZ1122

**Comment by adambuttrick** [comment]
Tagging this as hold for later. I can find no instance of usage of this new form and the requester indicates that the new website is in progress. Current website in ROR still resolves and uses the name form on the record. We can review later on for redirects or public use of this form.

**Comment by adambuttrick** [comment]
Website is offline, so unable to verify whether this change should be made. Keeping on hold.

**Comment by adambuttrick** [comment]
Website is still offline, so declining this request. Can resubmit when name change is publicly verifiable.
