### ISSUE TITLE
Modify the information in an existing ROR record: 
Prague University of Economics and Business (formerly University of Economics, Prague) https://ror.org/029ecwj92


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#463]
Summary of request: Modify the information in an existing ROR record

Name of organization: Prague University of Economics and Business (formerly University of Economics, Prague)
ROR ID: https://ror.org/029ecwj92
Which part of the record needs to be changed? Primary name
Description of change: Please change the primary name in English, see https://www.vse.cz/english/press-releases/university-of-economics-prague-changes-name/ and keep the old one in the Other Names section. Thank you.

Update: change.name==Prague University of Economics and Business; add.aliases==University of Economics Prague; delete.aliases==Vysoká škola ekonomická v Praze;

**Comment by adambuttrick** [comment]
Press release for name change appears on same domain as the site in ROR and the name change is on the English page for the organization,

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
