### ISSUE TITLE
Merge two or more ROR records: 
 


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#465]
Summary of request: Merge two or more ROR records 

Name of organization: Kangdong Sacred Heart Hospital
ROR ID: https://ror.org/00hr1eg19
Description of change: 
Per the website in the record (http://eng.hallym.or.kr/ptp201e.asp), it is actually Hallym University Kangdong Sacred Heart Hospital and thus duplicates https://ror.org/05mx1gf76. The archived version of the website (https://web.archive.org/web/20171026182310/http://kangdong.hallym.or.kr:80/) gives the same address as the website in https://ror.org/00njt2653. There is an extant ROR for the incorrect name of https://ror.org/00njt2653, i.e. Kangnam Sacred Heart Hospital (https://ror.org/00hr1eg19). I believe merging https://ror.org/00njt2653 and https://ror.org/05mx1gf76 would resolve the issue."
Related organizations: https://ror.org/00njt2653 (successor-np)
Update: change.status==withdrawn;$

**Comment by adambuttrick** [comment]
Requestor is correct that these are duplicates of one another. Moving to Hold for Later until we have merge functionality.

**Comment by adambuttrick** [comment]
Updated in release v1.15.
