### ISSUE TITLE
Modify the information in an existing ROR record: 
Zygo Corporation  https://ror.org/051fsan18


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#466]
Summary of request: Modify the information in an existing ROR record

Name of organization: Zygo Corporation
ROR ID:  https://ror.org/051fsan18
Which part of the record needs to be changed? Organization website
Description of change: Please convert URL to https, i.e. https://www.zygo.com
Update: delete.links==http://www.zygo.com/; add.links==https://www.zygo.com/;

**Comment by adambuttrick** [comment]
HTTP form redirects to HTTPS.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
