### ISSUE TITLE
Modify the information in an existing ROR record: 
Tango Therapeutics (United States) https://ror.org/003x6t567


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#467]
Summary of request: Modify the information in an existing ROR record

Name of organization: Tango Therapeutics (United States)
ROR ID: https://ror.org/003x6t567
Which part of the record needs to be changed? Other IDs for the organization
Description of change: currently have these ids:
Crossref Funder ID https://doi.org/10.1021/cen-09514-buscon007

delete said id since it is wrong
Update: delete.FundRef==https://doi.org/10.1021/cen-09514-buscon007;

**Comment by adambuttrick** [comment]
Current ID is a DOI for a journal article and nothing appears in the CrossRef API for this funder, so this is good to delete.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
