### ISSUE TITLE
Add a new organization to ROR: Office for Science and Technology of the Embassy of France in the United States

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4679]
Summary of request: Add a new organization to ROR

Name of organization: Office for Science and Technology of the Embassy of France in the United States
Website: 
Link to publications: 
Organization type:
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 100015488
Other names for the organization: 
Aliases: Office for Science and Technology, Embassy of France in the USA; OST; Mission pour la Science et la Technologie in FRENCH; Office for Science and Technology; Office for Science and Technology of the French Embassy in the United States; Mission pour la Science et la Technologie de l’Ambassade de France aux Etats-Unis in FRENCH; Office for Science & Technology of the Embassy of France in the United States; Office for Science and Technology Embassy of France in the USA; MS&T
Labels: 
Acronym/abbreviation: 
Related organizations: 
City: 
Country: United States
Geonames ID: 
Year established: 
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of Dryad Funder Registry reconciliation - https://github.com/ror-community/ror-updates/issues/4590.

**Comment by mariagould** [comment]
I would recommend creating the ROR record at the higher level - Embassy of France in the United States, which aligns with other representations of foreign embassies in ROR, e.g., https://ror.org/04enpqf37 and https://ror.org/03594dm11. 

There does not appear to be a corresponding Funder ID for the embassy, so the ID for the Office of Science and Technology will be the primary Funder ID associated with the ROR record.
