### ISSUE TITLE
Add a new organization to ROR: Stiftung Begabtenförderung Cusanuswerk

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4687]
Summary of request: Add a new organization to ROR

Name of organization: Stiftung Begabtenförderung Cusanuswerk
Website: https://stiftung.cusanuswerk.de
Link to publications: 
Organization type:
Wikipedia page: 
Wikidata ID: 
ISNI ID:  0000 0004 8308 2717
GRID ID: 
Crossref Funder ID: 501100014401
Other names for the organization: 
Aliases: Die Stiftung Begabtenförderung Cusanuswerk; Foundation for Gifted Cusanuswerk
Labels: 
Acronym/abbreviation: 
Related organizations: 
City: Bonn
Country: Germany
Geonames ID: 2946447
Year established: 
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of Dryad Funder Registry reconciliation - https://github.com/ror-community/ror-updates/issues/4590.

**Comment by mariagould** [comment]
I would recommend creating the ROR ID at the parent level, e.g., for Cusanuswerk (https://www.cusanuswerk.de/), as opposed to the foundation level. There does not appear to be a corresponding Funder ID for the parent entity, so the existing Funder ID for the foundation will be the primary one associated with the ROR record.
