### ISSUE TITLE
Add a new organization to ROR: Virginia's Academic Library Consortium

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#469]
Summary of request: Add a new organization to ROR

Name of organization: Virginia's Academic Library Consortium
Website: https://vivalib.org/
Link to publications: 
Organization type: Other
Wikipedia page: https://en.wikipedia.org/wiki/Virtual_Library_of_Virginia
Wikidata ID: Q7934991
ISNI ID: https://isni.org/isni/0000000404965192
GRID ID:
Crossref Funder ID:
Other names for the organization: Virtual Library of Virginia
Acronym/abbreviation: VIVA
Related organizations: 
City: Fairfax, VA
Country: United States
Geonames ID: 4758023
Year established: 1994
How will a ROR ID for this organization be used? 
Other information about this request: Request via Rockefeller University Press to use ROR ID for Read & Publish agreements

**Comment by mariagould** [comment]
This is needed to facilitate eligibility tracking for authors affiliated with institutions participating in read & publish agreements. 

We have similar library consortia already represented in ROR, i.e., https://ror.org/02m6s1q30 and https://ror.org/01vvcdt37. 

I recommend that we create a new ROR ID for VIVA.

**Comment by adambuttrick** [comment]
Adding ORCID affiliation usage:
https://orcid.org/0000-0002-7679-9846
https://orcid.org/0000-0002-6018-6906
https://orcid.org/0000-0001-8043-7701

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/021gxf250 in release v1.0.
