### ISSUE TITLE
Add a new organization to ROR: European Plate Observing System  

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#47]
Summary of request: Add a new organization to ROR

Name of organization: European Plate Observing System  
Website: https://www.epos-eu.org
Link to publications: https://www.epos-eu.org/data-services/data-products
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: 
Country: Italy (host country - consortium is pan-European)
Other information about this request:

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00qxqkw78 in release v1.0.
