### ISSUE TITLE
Add a new organization to ROR: 
 
Instituto Peruano de Orientación Psicológica

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#471]
Summary of request: Add a new organization to ROR

Name of organization: Instituto Peruano de Orientación Psicológica - IPOPS
Website: https://ipops.pe/
Link to publications: https://doi.org/10.1186/s12888-021-03456-z; https://doi.org/10.3389/fpsyg.2021.673945; https://doi.org/10.12688/f1000research.27150.2; http://dx.doi.org/10.1136/bmjopen-2020-036777
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page:
Wikidata ID: https://www.wikidata.org/wiki/Q52662516
ISNI ID: https://isni.org/isni/0000000495136890
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels:
Acronym/abbreviation: IPOPS
Related organizations: 
City: Lima
Country: Peru
Year established: 1986
Geonames ID: 3936456
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
Private institution focused on research in psychology and psychological treatment. Conducts training, seminars, and organizes conferences. Publication affiliation usage looks solid.

Google Scholar affiliation usage: https://scholar.google.com/citations?user=UhIQliwAAAAJ; https://scholar.google.com/citations?user=Vjdy9pQAAAAJ; https://scholar.google.com/citations?user=QHRUnMQAAAAJ
ORCID affiliation usage: https://orcid.org/0000-0003-0972-4534 ; https://orcid.org/0000-0002-7345-878X ; https://orcid.org/0000-0003-4989-4538 ; https://orcid.org/0000-0001-9267-1618 ; https://orcid.org/0000-0001-7333-6574 ;


Similar records in ROR: https://ror.org/056ezyb19 ; https://ror.org/0165gz615

**Comment by arthurpsmith** [comment]
Looks good to me, my only thought was it might be something we already have but I can't find it so I think good to go!

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/046ghm278 in release v1.1.
