### ISSUE TITLE
Add a new organization to ROR: 
 
Megjunaroden Slavjanski Univerzitet Gavrilo Romanovich Derzhavin

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#472]
Summary of request: Add a new organization to ROR

Name of organization: International Slavic University Gavrilo Romanovich Derzhavin
Website: https://msu.edu.mk/
Link to publications: https://konferencii.msu.edu.mk/mdiz/spisanija/spisanija/
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://mk.wikipedia.org/wiki/Меѓународен_славјански_универзитет_„Гаврило_Романович_Державин“
Wikidata ID: Q12909391
ISNI ID: https://isni.org/isni/0000000506038664
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels: Меѓународен Славјански Универзитет Гаврило Романович Державин*Macedonian; Международный славянский университет (МСУ) “Гаврило Романович Державин”*Russian;
Acronym/abbreviation: MSU; ISU; МСУ
Related organizations: 
City: Sveti Nikole
Country: North Macedonia
Geonames ID: 863905
Year established: 2004
How will a ROR ID for this organization be used? To identify affiliations for research publications, To be integrated in a scholarly publishing system
Other information about this request:

**Comment by adambuttrick** [comment]
North Macedonian university. I can only find limited affiliation usage by searching the Macedonian name, seemingly from scholarly outputs of the university itself (e.g. https://eprints.ugd.edu.mk/14078/1/ZBORNIK_6_PSIHOLOGIJA_i_web.pdf), but does otherwise seem legitimate. 

ORCID affiliation usage: https://orcid.org/0000-0001-9357-019X

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02qtq4y04 in release v1.1.
