### ISSUE TITLE
Merge two or more ROR records: Limerick Institute of Technology and 

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#473]
Summary of request: Merge two or more ROR records

Name of organizations: Limerick Institute of Technology and Athlone Institute of Technology
ROR IDs: https://ror.org/0269ncv24 ; https://ror.org/02dyxwz31
Description of change: Limerick Institute of Technology (https://ror.org/0269ncv24) and the Athlone Institute of Technology (https://ror.org/02dyxwz31) have been merged into one institution (Technological University of the Shannon: Midlands Midwest), as described in #470. These records need to be deprecated and merged.

**Comment by sckott** [comment]
Thanks for creating this issue from the one I opened in #470 - I've never requested a change or addition to ROR - about how long does it take generally to get in to the ROR database? Weeks? Months? Longer?

**Comment by adambuttrick** [comment]
Closing this issue, as it is a dupe of #414.

**Comment by sckott** [comment]
Thanks very much!

**Comment by tyoungmarsh** [comment]
Hi Both,  can I ask why this request was declined?  I got no notification of any issues with the request and only discovered the updated status now.  I can see other tickets #470 #414.  Re address for new or merged university, Moylish, Limerick is to be used as HQ for research.  Please contact me if you have any questions regarding TUS.  Can I ask how long this process will take and which ticket number should I follow?

**Comment by tyoungmarsh** [comment]
Hi @adambuttrick excellent, thank you so much.  I wrongly assumed work on creating/merging a new ROR would not commence without a request from an organisation, therefore I never checked to see if any tickets were already created.  Thanks again, and looking forward to seeing our new TUS ROR.
