### ISSUE TITLE
Modify the information in an existing ROR record: Bear Fight Institute

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#4745]
Summary of request: Modify the information in an existing ROR record

Name of organization: Bear Fight Institute
ROR ID: https://ror.org/04pfac868 
Which part of the record needs to be changed?
Description of change: Make inactive. Sadly, the Bear Fight Institute, which I thought might be a good candidate for a Favorite ROR, closed its research facility in 2021: https://methowvalleynews.com/2021/01/27/bear-fight-institute-closes-research-facility/ The listed website at http://bearfightinstitute.com/ is also defunct. 

Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
Record updated in release v1.29.
