### ISSUE TITLE
Add a new organization to ROR: 
 
State Institution  “Institute for Economics and Forecasting, National Academy of Sciences of Ukraine”

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#475]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Institute for Economics and Forecasting of the National Academy of Sciences of Ukraine
Website: http://ief.org.ua/
Link to publications: Yes
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://en.wikipedia.org/wiki/NASU_Institute_for_Economics_and_Forecasting
Wikidata ID: https://www.wikidata.org/wiki/Q12074603
ISNI ID: https://isni.org/isni/0000000460235442
GRID ID: 
Crossref Funder ID: 
Aliases: NASU Institute for Economics and Forecasting, SI “Institute for Economics and Forecasting, NAS of Ukraine”
Labels: Державна установа “Інститут економіки та прогнозування НАН України”*Ukrainian; Государс твенное учреждение “Институт экономики и прогнозирования НАН Украины”*Russian
Acronym/abbreviation: 
Related organizations: National Academy of Sciences of Ukraine https://ror.org/00je4t102 (parent)
City: Kyiv
Country: Ukraine
Year established: 1997
Geonames ID: 703448
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request: State Institution “Institute for  Economics and Forecasting,  National Academy of Sciences of Ukraine”, in accordance with Decree by Presidium of NAS of Ukraine of 06.07.2005 No 139 “On the renaming Institute for Economic Forecasting, of NAS of Ukraine” is successor Institute for Economic Forecasting, of NAS of Ukraine which was created in accordance with Decree by Ukraine’s Cabinet of Ministers of 19.07.1997. No772 “On the creation of the Institute for Economic Forecasting, Ukrainian National Academy of Sciences” and the corresponding Decree by the Presidium of Ukrainian National Academy of Sciences of 05.09.1997 No 298 in order to provide the elaboration of strategic forecasts and programs of Ukraine’s socio-economic development.
The Head of the Institute Is Academician of NAS of Ukraine Valeriy Mykhailovych HEYETS.
The Institute’s main objective is conducting fundamental and applied researches on the following guidelines: economic theory; modeling and forecasting economic development; monetary relations; public finances; finances of the real sector; economic growth and economic restructuring; economics and organization of high technologies; development of production infrastructure; industrial policy; technological forecasting and innovation policy; sectoral forecasting and market conjuncture; economics and policy of agrarian transformations; forma and methods of economic management in the agro-industrial complex; monitoring-based research on socio-economic transformations of the Ukrainian society; economic history; socio-economic problems of labor; economics management; spatial economic development and local government. On that basis, the Institute is developing the guidelines and methods of the development of the economic system, strategic forecasts and programs of the development of Ukraine’s economy.

**Comment by adambuttrick** [comment]
This is another instance of a Ukrainian National Academy of Sciences institute, of which we have many (e.g. https://ror.org/05x75zf33 , https://ror.org/059fvd392). Should be added.

ORCID affiliation usage: https://orcid.org/0000-0002-3986-5613 ; https://orcid.org/0000-0003-2265-4614 ; https://orcid.org/0000-0002-8542-3904 ; https://orcid.org/0000-0003-0540-5413

**Comment by arthurpsmith** [comment]
Looks fine to me. I added the ISNI id.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0244nkc36 in release v1.1.
