### ISSUE TITLE
Modify the information in an existing ROR record: Southampton City College https://ror.org/005c9q773

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#4773]
Summary of request: Modify the information in an existing ROR record

Name of organization: Southampton City College
ROR ID: https://ror.org/005c9q773
Which part of the record needs to be changed? Name
Description of change: Change the name to "City College Southampton", as this appears to be the primary way this organization represents itself according to its website at https://www.southampton-city.ac.uk/. Add the alias "Southampton City College" to aliases, since according to the Wikipedia page at https://en.wikipedia.org/wiki/Southampton_City_College and the document at https://www.peridotpartners.co.uk/wp-content/uploads/2022/03/Southampton-City-College-Governor-Financial-Statements-2020-21.pdf it is an alternate name for the organization. 

Update: change.name==City College Southampton; add.aliases==Southampton City College;$

**Comment by adambuttrick** [comment]
Name change corresponds to organization's website and branding.

**Comment by adambuttrick** [comment]
Record updated in release v1.30.
