### ISSUE TITLE
Add a new organization to ROR: 
 
French Statistical Society (SFdS)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#479]
Name of organization: French Statistical Society
Website: https://www.sfds.asso.fr
Link to publications: "https://computo.sfds.asso.fr/", "http://statistique-et-societe.fr/" 
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: https://en.wikipedia.org/wiki/French_Statistical_Society
Wikidata ID: Q3488327
ISNI ID: 0000 0001 2152 0652
GRID ID: 
Crossref Funder ID: 
Aliases: 
Labels: Société Française de Statistique*French
Acronym/abbreviation: SFdS
Related organizations: 
City: Paris
Country: France
Geonames ID: 2988507
Year established: 1997
How will a ROR ID for this organization be used? To identify affiliations for research publications
Other information about this request:

**Comment by adambuttrick** [comment]
Independent academic society in Paris, with roots dating back to the 1800s. Publishes four journals on statistical topics (http://journal-sfds.fr ; http://statistique-et-enseignement.fr ; http://statistique-et-societe.fr/ ; http://csbigs.fr/). Clearly involved with research and should be added to ROR

ORCID affiliation usage: https://orcid.org/0000-0003-4297-1334 ; https://orcid.org/0000-0001-6275-5888 ; https://orcid.org/0000-0002-3406-5887

**Comment by arthurpsmith** [comment]
We have many similar societies in ROR already, this seems fine to me. Well-established.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00jp4qe04 in release v1.0.
