### ISSUE TITLE
Add a new organization to ROR: InterGrain Pty Ltd  

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#48]
Summary of request: Add a new organization to ROR

Name of organization: InterGrain Pty Ltd  
Website:https://www.intergrain.com
Link to publications:  https://www.intergrain.com/variety-id-testing/
Wikipedia page: 
Wikidata ID: 
ISNI ID: https://isni.org/isni/0000000502336218
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: Bibra Lake
Country: Australia
Other information about this request:

**Comment by carlyrobinson** [comment]
Agreed, should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00nw4tw41 in release v1.0.
