### ISSUE TITLE
Add a new organization to ROR: 
 
Pacific Northwest National Laboratory DataHub: Scientific Data Repository (PNNL2)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#480]
Name of organization: Pacific Northwest National Laboratory DataHub: Scientific Data Repository (PNNL2)
Website: https://data.pnnl.gov/
Link to publications: https://doi.org/10.25584/PNNL.DataHub/1812943
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: https://www.osti.gov/servlets/purl/1812943
Aliases: PNNL DataHub
Labels:
Acronym/abbreviation: PNNL2
Related organizations: https://ror.org/05h992307
City: Richland
Country: United States of America
Year established: 2017
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request: This is a PNNL data project repository in development at FAIRSharing.org under the record URL: https://fairsharing.org/3692. Data provided at this project repository is intended for long-term preservation, project data source linking, and shares data with the EMSL user facility (https://ror.org/04rc0xn13) as part of the DOE/BER program (https://ror.org/0114b2m14), in addition to many NIH (https://ror.org/01cwqze88) related sponsored grants/contracts.

**Comment by adambuttrick** [comment]
Not certain this repository is sufficiently independent organization, as it is clearly under the Pacific Northwest National Laboratory (https://ror.org/05h992307). I see very few similar records in ROR. The two that we do include (https://ror.org/00x6h5n95 ; https://ror.org/014trz974) are more distinctly independent entities. They would most likely use the Pacific Northwest National Laboratory ID for their own data deposits and other contributors could likewise use their own IDs.
