### ISSUE TITLE
Modify the information in an existing ROR record: Almaty Technological University - https://ror.org/01xeb1c73

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#4802]
Summary of request: Modify the information in an existing ROR record

Name of organization: Almaty Technological University
ROR ID: https://ror.org/01xeb1c73
Which part of the record needs to be changed? Links, Wikidata ID, Labels
Description of change: Replace links with https://atu.edu.kz. Add Wikidata ID Q2399553. Add alias Алматы технологиялық университеті*Kazakh.

Update: replace.links==https://atu.edu.kz; add.Wikidata==Q2399553; add.labels==Алматы технологиялық университеті*Kazakh;$

**Comment by Alex-Almaty** [comment]
Adam, hi.

What is the deadline for the task?

**Comment by adambuttrick** [comment]
@Alex-Almaty We will publish this change in our next release, which is currently scheduled for the end of next week. More generally, ROR publishes updates approximately once per month. Please continue to follow this issue to be notified when the change has been published.

**Comment by adambuttrick** [comment]
Record updated in release v1.30.
