### ISSUE TITLE
Redirect Laboratory of Hydrology and Geochemistry (https://ror.org/03y81da23)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#481]
Summary of request: Redirect Laboratory of Hydrology and Geochemistry (https://ror.org/03y81da23)

Name of organization: Laboratory of Hydrology and Geochemistry 
ROR ID: https://ror.org/03y81da23
Description of change: Per https://ites.unistra.fr/linstitut/historique-anciennes-umrs, this laboratory has now (along with another entity) become part of the newly formed Earth and Environment Institute of Strasbourg.

We are creating a new ROR ID for the Earth and Environment Institute of Strasbourg (see #365). When we have redirecting functionality in place, we should redirect https://ror.org/03y81da23 to the new ROR ID.

Update: change.status==inactive;$
Related organizations: https://ror.org/0530qwm02 (successor)

**Comment by adambuttrick** [comment]
Record updated in release v1.15.
