### ISSUE TITLE
Modify the information in an existing ROR record: 
Catholic University of the West https://ror.org/00jzv1t04


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#483]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Catholic University of the West
ROR ID: https://ror.org/00jzv1t04
Which part of the record needs to be changed? Other IDs for the organization, Something else
Description of change: The ISNI  : the right is : https://isni.org/isni/0000000119403502
The current identifier corresponds to that of a research team
The url : https://www.uco.fr

Update: replace.ISNI==0000 0001 1940 3502; replace.links==https://www.uco.fr;

**Comment by adambuttrick** [comment]
URL change is to the top-level domain for the organization, while the one in ROR is not. ISNI change checks out as well.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
