### ISSUE TITLE
Modify the information in an existing ROR record: 
JDSU (United States) https://ror.org/01a5v8x09


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#485]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: JDSU (United States)
ROR ID: https://ror.org/01a5v8x09
Which part of the record needs to be changed? Primary name, Organization website
Description of change: This corporate has change names. It and its children need to be updated to VIAVI, www.viavisolutions.com

**Comment by adambuttrick** [comment]
Not certain we should process this as a simple name change. According to Wikipedia, the company was split into two different entities in 2015:

"In August 2015, JDSU split into two different companies: [Viavi Solutions](https://en.wikipedia.org/wiki/Viavi_Solutions) and [Lumentum Holdings](https://en.wikipedia.org/w/index.php?title=Lumentum_Holdings&action=edit&redlink=1)[](https://en.wikipedia.org/wiki/JDSU#cite_note-3)."

**Comment by adambuttrick** [comment]
I'm going to say this is addressed solely by the deprecation.
