### ISSUE TITLE
Add a new organization to ROR: Politeknik Negeri Banjarmasin

### ISSUE THREAD

**Issue by wanvysaputra** [ror-community/ror-updates#4855]
Summary of request: Add a new organization to ROR

Name of organization: Politeknik Negeri Banjarmasin
Website: https://poliban.ac.id
Link to publications: https://ejurnal.poliban.ac.id/
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://id.wikipedia.org/wiki/Politeknik_Negeri_Banjarmasin
Wikidata ID: Q6684388
ISNI ID: 0000 0004 0375 2304
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Banjarmasin State Polytechnic; State Polytechnic of Banjarmasin
Labels:
Acronym/abbreviation: POLIBAN
Related organizations: 
City: Banjarmasin
Country: Indonesia
Geonames ID: 1650213
Year established: 1987
How will a ROR ID for this organization be used? To identify affiliations for research publications and webometrics
Other information about this request:

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02ffcdy84 in release v1.30.
