### ISSUE TITLE
Add a new organization to ROR: 
 
Computable Publishing LLC

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#486]
Summary of request: Add a new organization to ROR

Name of organization: Computable Publishing
Website: https://computablepublishing.com
Link to publications: doi: 10.1002/lrh2.10271, doi: 10.1111/hex.13244, doi: 10.1016/j.jbi.2021.103685
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: CompPub
Labels:
Acronym/abbreviation: CP
Related organizations: 
City: Ipswich
Country: United States
Geonames ID: 4940625
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To be integrated in a scholarly publishing system, demonstration of ROR IDs in a citation repository

Other information about this request: Computable Publishing LLC maintains the Fast Evidence Interoperability Resources (FEvIR) Platform (https://fevir.net) which could be a repository for integrating ROR IDs

**Comment by adambuttrick** [comment]
Private company looking to integrate ROR as part of their medical project and research tracking platform. Company is and independent, top-level entity with multiple employees and is used as affiliation on publications in this domain. Appears in scope for ROR.

publication affiliation usage: https://www.sciencedirect.com/science/article/pii/S1532046421000149#; https://onlinelibrary.wiley.com/doi/full/10.1002/lrh2.10271
Google Scholar affiliation usage: https://scholar.google.com/citations?user=lqriLpkAAAAJ
ORCID affiliation usage: https://orcid.org/0000-0002-9896-9842 ; https://orcid.org/0000-0002-3526-7667 ; https://orcid.org/0000-0003-4300-4928

**Comment by arthurpsmith** [comment]
Rather new, but it does seem active and valid as far as our usual criteria go. Yes, let's add this one.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/034eyya14 in release v1.0.
