### ISSUE TITLE
Modify the information in an existing ROR record: 
Institut fuer Integrierte Produktion Hannover (Germany) https://ror.org/03w8k6t95


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#487]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Institut fuer Integrierte Produktion Hannover (Germany)
ROR ID: https://ror.org/03w8k6t95
Which part of the record needs to be changed? Organization website
Description of change: The old Website does not exist anymore. The Website needs to be: https://www.iph-hannover.de/de/ 

Update: change.links==https://www.iph-hannover.de/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
