### ISSUE TITLE
Modify the information in an existing ROR record: 
Kunsthistorisches Museum https://ror.org/03h82yz49


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#488]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Kunsthistorisches Museum
ROR ID: https://ror.org/03h82yz49
Which part of the record needs to be changed? Primary name
Description of change: The Primary name has to be changed from "Kunsthistorisches Museum" into "KHM-Museumsverband" (as presented in https://www.khm.at/fileadmin/user_upload/KHM-Geschaeftsbericht_2020.pdf)

Update: change.name==KHM-Museumsverband; add.aliases==Kunsthistorisches Museum;$

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
