### ISSUE TITLE
Add a new organization to ROR: 
 
Oku Okut Derneği

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#489]
Summary of request: Add a new organization to ROR

Name of organization: Oku Okut Derneği
Website: https://www.okuokut.org/
Link to publications: https://yayin.okuokut.org/okuokut
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID:
ISNI ID: 0000 0005 0627 6072
GRID ID: 
Crossref Funder ID: 
Aliases: Oku Okut Association
Labels:
Acronym/abbreviation: OKU OKUT
Related organizations: Oku Okut Yayınları, Oku Okut Akademi
City: Ankara
Country: Turkey
Geonames ID: 323786
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request: Oku Okut Association Annual Report-2021, https://yayin.okuokut.org/okuokut/catalog/view/ekitap/978-605-71294-1-3/67

**Comment by adambuttrick** [comment]
Appears to be a relatively new, open access publishing imprint focused on the humanities and social sciences. Does publish work by researchers at universities in Turkey (e.g. https://yayin.okuokut.org/okuokut/catalog/book/978-605-74416-1-4), so appears in scope for ROR.

Google scholar affiliation usage: https://scholar.google.com/citations?user=Cxnd6TcAAAAJ

**Comment by drademir** [comment]
Oku Okut Derneği Wikidata ID: Q110946274, https://www.wikidata.org/wiki/Q110946274
Organisation ID (OID): E10291891, https://webgate.ec.europa.eu/erasmus-esc/index/organisations/search-for-an-organisation
About: https://www.okuokut.org/hakkimizda/

**Comment by drademir** [comment]
Oku Okut Derneği | Oku Okut Association:
Oku Okut Yayinlari DOI prefix: 10.55709
[](https://www.crossref.org/members/prep/34564)

**Comment by arthurpsmith** [comment]
I removed the Wikidata ID from the metadata fields as the item has been deleted there (no external references).

It's only a bit over a year old and they've published only a few items so far. Also there seem to be 3 related organizations here (mentioned on the "related organizations" line):
Oku Okut Yayınları - the publishing arm
Oku Okut Akademi - an educational arm I guess

I think this is marginal - is this really related to research as we understand it? For example here's one of their books: https://www.ceeol.com/search/book-detail?id=1031808

As always these marginal ones take the most time to figure out. I guess we can be generous here and let it have an identifier, at least that will give some way of linking together what they do.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03zs8ga83 in release v1.1.
