### ISSUE TITLE
Add a new organization to ROR: Microscopy Australia

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#49]
Summary of request: Add a new organization to ROR

Name of organization: Microscopy Australia
Website: https://micro.org.au/
Link to publications: 
Wikipedia page: 
Type: Facility
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: MicroAU
Related organizations: 
City: Sydney
Country: Australia
Other information about this request:

**Comment by carlyrobinson** [comment]
Interesting case where this is a network on microscope facilities that can be used by Australian researchers. The microscopes seem to be at university that would already have ROR IDs. Since it is being acknowledged in publications, it may make sense to assign a ROR since it fits other criteria - more than one parent organization (network of universities), independent domain, run by more than one person, established/stable.

**Comment by mariagould** [comment]
Further information from the organization. Note that I have added MicroAU to the acronym in the summary data above.

> Microscopy Australia is a network of microscopy facilities that are hosted at universities. We provide funding for infrastructure and personnel. As a result, researchers acknowledge Microscopy Australia for support in their publications but there is no researcher affiliated with Microscopy Australia per se. In the Australian research environment, Microscopy Australia is the same type of research facility as the Australian National Imaging Facility (NIF, https://ror.org/01kdbsa35) and AuScope (https://ror.org/04s1m4564).
> 
> Acronym/abbreviation: in the application, I wrote “n/a”. In the GitHub board, it is “MA”. If an acronym were to be used, I would prefer “MicroAU” instead of “MA”. Microscopy Australia has recommended that researchers and partners (in Australia and overseas) do not use “MA” when referring to Microscopy Australia. If anything, in Australia, “MA” is “Metabolomics Australia”.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/042mm0k03 in release v1.0.
