### ISSUE TITLE
Add a new organization to ROR: 
 
Zurich Heart House - Foundation for Cardiovascular Research

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#490]
Summary of request: Add a new organization to ROR

Update record:
Name of organization: 
ROR ID: 
Which part of the record needs to be changed? 
Description of change: 

Merge/split/deprecate records:
Organizations affected by this change:
ROR ID(s) of organization(s) affected by this change: 
How should the record(s) be changed? 

Add record:
Name of organization: Zurich Heart House - Foundation for Cardiovascular Research
Website: www.zhh.ch
Link to publications: https://www.cmc.uzh.ch/en.html
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: www.zhh.ch
Wikidata ID: Q50037365
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: Stiftung für Herz- und Kreislaufforschung
Labels:
Acronym/abbreviation: ZHH
Related organizations: 
City: Zurich
Country: Switzerland
Geonames ID: 7287650
Year established: 1996
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Zurich Heart House already exists in ROR: https://ror.org/01agg0039. Closing.
