### ISSUE TITLE
Modify the information in an existing ROR record: 
Leibniz Institute for the History and Culture of Eastern Europe (GWZO) https://ror.org/04tjfqn96


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#491]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Leibniz Institute for the History and Culture of Eastern Europe (GWZO)
ROR ID: https://ror.org/04tjfqn96
Which part of the record needs to be changed? Primary name
Description of change: The official legal name of the research institute in English is "Leibniz Institute for the History and Culture of Eastern Europe (GWZO)". The official legal German name is "Leibniz-Institut für Geschichte und Kultur des östlichen Europa (GWZO)". Both names include the abbrevation "GWZO" in brackets at the end, which are missing in the record. Verification: https://leibniz-gwzo.de/en/imprint

Update: change.name==Leibniz Institute for the History and Culture of Eastern Europe (GWZO); replace.labels==Leibniz-Institut für Geschichte und Kultur des östlichen Europa (GWZO)*German;

**Comment by adambuttrick** [comment]
Use of "GWZO" is present on the legal notice section of the organization's website.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
