### ISSUE TITLE
Modify the information in an existing ROR record: 
Japan Science and Technology Agency https://ror.org/00097mb19


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#492]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Japan Science and Technology Agency
ROR ID: https://ror.org/00097mb19
Which part of the record needs to be changed? Other names or name versions listed in the record
Description of change: I would like to add Japanese name "科学技術振興機構" as well as other Japanese institutions, for they are useful for displaying on Japanese websites. https://www.jst.go.jp/

Update: add.labels==科学技術振興機構*Japanese; replace.links==https://www.jst.go.jp/; add.Wikidata==Q11595927; add.ISNI==0000 0001 2285 0987;

**Comment by adambuttrick** [comment]
Correct Japanese form of the name. Updating link to remove English page reference and adding Wikidata and additional ISNI value.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
