### ISSUE TITLE
Add a new organization to ROR: 
 
Southern Urals biophysics institute

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#493]
Summary of request: Add a new organization to ROR

Name of organization: Southern Urals Biophysics Institute
Website: http://ib.subi.su
Link to publications: 10.1007/s00411-017-0688-3
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: 
Wikidata ID: Q110975438
ISNI ID: 0000 0004 0620 1495
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels: Ûžno-Ural'skij institut biofiziki*Slovenian;  Южно-Уральский институт биофизики*Russian;
Acronym/abbreviation: SUBI
Related organizations: https://ror.org/052ay8m85 (parent)
City: Ozersk
Country: Russia
Geonames ID: 1538634
Year established: 1953
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets

Other information about this request: Please don`t support the name "FGUP Uzno-Ural'skij institut biofiziki Federal'nogo mediko-biologiceskogo agentstva Rossii" like ISNI. We need use only "Southern Urals Biophysics Institute" name.

**Comment by adambuttrick** [comment]
Federal-level biophysics research institute in the Russian Federation with solid publication affiliation usage. Top-level entity. Should be added to ROR.

ORCID affiliation usage: https://orcid.org/0000-0001-8807-9494; https://orcid.org/0000-0002-2113-429X ; https://orcid.org/0000-0001-9177-4666 ; https://orcid.org/0000-0003-4757-7969

Publication affiliation usage: https://www.researchgate.net/institution/Southern-Ural-Biophysics-Institute

**Comment by cvetkov321** [comment]
Hello! Please tell me I should do something to add my institution (Southern Urals Biophysics Institute) to ROR or should I just wait? Best regards, Nikolay Tsvetkov.

**Comment by arthurpsmith** [comment]
I added the Wikidata ID and parent ROR id. Yes, this should be in ROR.

**Comment by cvetkov321** [comment]
Thank you, friends!!!

**Comment by cvetkov321** [comment]
> I added the Wikidata ID and parent ROR id. Yes, this should be in ROR.

Hallo! Please help me, where can I find my institution? I fill the search field on https://ror.org/ with "Southern Urals biophysics institute" and bekam nothing. What I do uncorrect?
![2022-04-25_09-19-03](https://user-images.githubusercontent.com/99870438/165020293-f5af611d-f6a3-47cf-9696-81be38f3a96e.png)

**Comment by arthurpsmith** [comment]
Hi @cvetkov321   - there are a few more steps before it will be available online, but it should happen by the end of June if not sooner.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03bw8s353 in release v1.1.
