### ISSUE TITLE
Add a new organization to ROR: 
 
Institut für Axiologische Forschungen

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#495]
Summary of request: Add a new organization to ROR

Name of organization: Institute of Axiological Research
Website: https://www.iaf.ac.at
Link to publications: http://dx.doi.org/10.25180/lj
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: Q74547450
ISNI ID: 0000 0001 2168 3806
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels: Institut für Axiologische Forschungen*German
Acronym/abbreviation: IAF
Related organizations: 
City: Vienna
Country: Austria
Year established: 1999
Geonames ID: 2761369
How will a ROR ID for this organization be used? To identify affiliations for research publications, To be integrated in a scholarly publishing system

Other information about this request: The field of scientific activity of the Institite is "philosophical and interdisciplinary value research" and the institute is registret in Austria with number ZVR: 818 739 280

**Comment by arthurpsmith** [comment]
Looks good to me, nothing to add.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01dvbrt74 in release v1.1.
