### ISSUE TITLE
Deprecate an existing ROR record: 
 
Oxford Medical Diagnosticshttps://ror.org/013zcv680

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#496]
Summary of request: Deprecate an existing ROR record

Name of organization: Oxford Medical Diagnostics
ROR ID: https://ror.org/013zcv680
How should the record(s) be changed? This company was dissolved in July 2018, see  https://find-and-update.company-information.service.gov.uk/company/06611677

Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
Company does appear to have been dissolved. Moving to hold for later until we have the ability to tombstone records.

**Comment by icraig-afk** [comment]
@mariagould . Re this ability to tombstone records. Could you let me know where that is in the development plan? Thanks

**Comment by mariagould** [comment]
Hi @icraig-afk we are still scoping how this will be implemented so we don't have a specific timeframe in place just yet.

**Comment by adambuttrick** [comment]
Record updated in release v1.15.
