### ISSUE TITLE
Modify the information in an existing ROR record: 
Institute of Methodologies for Environmental Analysis https://ror.org/024ye7w89


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#497]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Institute of Methodologies for Environmental Analysis
ROR ID: https://ror.org/024ye7w89
Which part of the record needs to be changed? Other names or name versions listed in the record
Description of change: Acronym should be IMAA instead of IMAAA. This is either a typo or based on a preceding organization called Institute of Advanced Methodologies for Environmental Analysis / l’Istituto di Metodologie Avanzate di Analisi Ambientale (IMAAA), see https://www.imaa.cnr.it/en/about-us

Update: replace.acronyms==IMAA;

**Comment by adambuttrick** [comment]
Italian label ""L’Istituto di Metodologie per l’Analisi Ambientale" corresponds to the acronym change.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
