### ISSUE TITLE
Add a new organization to ROR: 
 
Data Observatory Foundation

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#499]
Name of organization: Data Observatory Foundation
Website: https://www.dataobservatory.net
Link to publications: https://www.dataobservatory.net
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: Data Observatory; Observatorio de Datos;
Labels: Fundación Observatorio de Datos*Spanish;
Acronym/abbreviation: DO
Related organizations: https://ror.org/0326knt82 (parent) https://ror.org/00as45r68 (parent)
City: Santiago
Country: Chile
Geonames ID: 3871336
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility

Other information about this request: We've recently been added as a DataCite Consortium and we want to register as a suggestion from them (we wasn't fully aware about the existence of this kind of register)

**Comment by adambuttrick** [comment]
Data hosting service, similar to ROR parent Datacite, created as a project between Spain's Ministry of Science, Technology, Knowledge and Innovationm, Ministry of Economy, and Universidad Adolfo Ibáñez (UAI). Hosts state-level COVID-19 datasets, earth and marine satellite data monitoring data, and astronomical research classifiers. Should be added to ROR.

**Comment by adambuttrick** [comment]
#502 would be the parent.

**Comment by arthurpsmith** [comment]
Very new though it's been in the works for several years before it started it looks like. Anyway, yes looks good to me, should be in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/027nn6b17 in release v1.0.
