### ISSUE TITLE
Add a new organization to ROR: NESP - Threatened Species Recovery Hub  

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#50]
Summary of request: Add a new organization to ROR

Name of organization: NESP - Threatened Species Recovery Hub  
Website: https://www.nespthreatenedspecies.edu.au
Link to publications: https://www.nespthreatenedspecies.edu.au/publications-and-tools
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: St Lucia
Country: Australia
Other information about this request:

**Comment by KellyStathis** [comment]
This one is tricky. I think it is used as an affiliation (for example, in https://www.publish.csiro.au/pc/Fulltext/PC19036?subscribe=false), but it is listed alongside Charles Darwin University in this publication, one of the Hub's partner universities (https://www.environment.gov.au/science/nesp/hub-threatened-species-recovery). It appears that all researchers affiliated with the Hub have another research organization as their primary appointment.

I am not sure if adding NESP addresses the issue; to me, it seems less accurate to say that these researchers are affiliated with NESP broadly, than to say they are affiliated with their specific research Hub. The six Hubs seem to function independently from each other (separate websites, etc), although each is accountable to NESP.

Another factor is that this project does not appear to be premised on long-term stability. According to this page, this Hub will not continue to exist past 2021 - it is part of Phase 1 of the NESP: http://www.environment.gov.au/science/nesp/phase-1. There are different Hubs for Phase 2: http://www.environment.gov.au/science/nesp/about.

**Comment by adambuttrick** [comment]
Phase one hubs would be out of scope, as they ceased in 2021.
