### ISSUE TITLE
Add a new organization to ROR: 
 
 H2020 ERA-net 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#500]
Name of organization: ERA-Net Cofund
Website: https://ec.europa.eu/programmes/horizon2020/en/h2020-section/era-net
Link to publications:
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:  
Labels:
Acronym/abbreviation:
Related organizations:  
City: Brussels
Country: Belgium
Geonames ID: 2800866
Year established: 9999
How will a ROR ID for this organization be used? To acknowledge research funding

Other information about this request:

**Comment by adambuttrick** [comment]
Under the Horizon 2020 scheme, the ERA-NET funding program has been merged into a single instrument, with the goal of "topping up" research funding across various domains. Full description of the instrument [here] (https://ec.europa.eu/research/participants/docs/h2020-funding-guide/cross-cutting-issues/era-net_en.htm).

**Comment by adambuttrick** [comment]
@MSpenger Can you provide any insight on whether you believe this funding scheme is in scope for ROR?

**Comment by MSpenger** [comment]
@adambuttrick 

I think this item might need some extra discussion. Looking at the [Checklist for evaluating new organizations](https://github.com/ror-community/ror-updates/wiki/Curator-Evaluation-Workflow:-New-Records#checklist-for-evaluating-new-organizations), most criteria are not met. Also the type "funding scheme" does not exist as a type of organization in the [Guidance for evaluating common organization types](https://github.com/ror-community/ror-updates/wiki/Curator-Evaluation-Workflow:-New-Records#guidance-for-evaluating-common-organization-types). Technically, the ERC Research Council (https://ror.org/0472cxd90) is the organization behind the funding scheme ERA-Net Cofund.

"The main and compulsory activity of the ERA-NET Cofund under Horizon 2020 is the implementation of the co-funded joint call for proposals that leads to the funding of trans-national research and/or innovation projects (one co-funded call per Grant Agreement)." https://www.era-learn.eu/support-for-partnerships/cofunded-p2p/era-net-cofund 

A use case, where a funder ID might be needed, is the funding reference in the DataCite metadata schema:
```
<fundingReference>
<funderName>European Commission</funderName>
<funderIdentifier funderIdentifierType="Crossref Funder ID">https://doi.org/10.13039/501100000780</funderIdentifier>
<awardNumber awardURI="https://cordis.europa.eu/project/rcn/100603_en.html">284382</awardNumber>
<awardTitle>
Institutionalizing global genetic-resource commons. Global Strategies for accessing and using essential public knowledge assets in the life sciences
</awardTitle>
</fundingReference>
```

However, "ERA-Net Cofund" cannot befound in either ISNI or Crossref Funder Registry.

And regarding the entry mentioned in the initial post, the "Year established" shows 9999. Is this used as a placeholder?

**Comment by adambuttrick** [comment]
Out of scope per discussion on 2022/05/03. Should use ERC ID for referencing this funding.
