### ISSUE TITLE
Add a new organization to ROR: 
 
Fundación Universitaria Horizonte 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#501]
Name of organization: Fundación Universitaria Horizonte 
Website: https://unihorizonte.edu.co
Link to publications: https://unihorizonte.edu.co/programas/facultades/facultad-ciencias-basicas/investigacion/
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 0000 0004 7717 0016 
GRID ID: 
Crossref Funder ID: 
Aliases: UniHorizonte
Labels:
Acronym/abbreviation:
Related organizations: 
City: BOGOTÁ, D.C.
Country: Colombia
Geonames ID: 3688689
Year established: 1977
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Colombian university. No current representation in ROR. Limited, but solid-looking publication affiliation usage. Should be added.

Publication affiliation usage: https://acofipapers.org/index.php/eiei/article/download/631/636 ; https://dialnet.unirioja.es/servlet/articulo?codigo=7368100

Google Scholar affiliation usage: https://scholar.google.com/citations?user=ZOpLewoAAAAJ
ORCID affiliation usage: https://orcid.org/0000-0001-9614-177X ; https://orcid.org/0000-0002-3537-9861 ; https://orcid.org/0000-0002-8004-1325

**Comment by arthurpsmith** [comment]
Yes, I believe our Latin American coverage is a serious weak spot (with GRID, and now in ROR). Let's add this!
