### ISSUE TITLE
Add a new organization to ROR: 
 
MIRCORE

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#503]
Name of organization: MIRCORE
Website: https://www.mircore.org
Link to publications: https://doi.org/10.1083/jcb.201103097, DOI: 10.1126/scisignal.2001744, DOI: 10.3233/JAD-200917, etc
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 0000 0005 0630 8601
GRID ID: 
Crossref Funder ID: 
Aliases: miRcore
Labels:
Acronym/abbreviation: MIRCORE
Related organizations: 
City: Ann Arbor
Country: United States
Geonames ID: 4984247
Year established: 2009
How will a ROR ID for this organization be used? To identify affiliations for research publications, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Nonprofit that provides microgrants for genetics research, primarily in the areas of disease treatment and resolution. Independent entity with solid publication affiliation usage. Should be added to ROR.

Publication affiliation usage: https://www.mircore.org/publications/
Google Scholar affiliation usage: https://scholar.google.com/citations?user=nUYpAKUAAAAJ
ORCID affiliation usage: https://orcid.org/0000-0001-5840-3900

**Comment by arthurpsmith** [comment]
Is there anybody with this affiliation aside from Inhan Lee? It looks like a very small outfit. On the other hand it does have an ISNI (added above).

**Comment by arthurpsmith** [comment]
Moving to "needs discussion" but if we see the affiliation used by more than the one person then I'm ok with it, that's my only concern here.

**Comment by adambuttrick** [comment]
@arthurpsmith Instances of affiliation usage by other people beside Inhan Lee: https://pubmed.ncbi.nlm.nih.gov/30845713/ ; https://pubmed.ncbi.nlm.nih.gov/27896996/ ; https://pubmed.ncbi.nlm.nih.gov/26156244/

Approving since this was the only concern.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01v1hv534 in release v1.1.
