### ISSUE TITLE
Project: ENEA Research Centers

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#506]
Merge/split/deprecate records:
Organizations affected by this change:ENEA-TALIAN NATIONAL AGENCY FOR NEW TECHNOLOGIES, ENERGY AND SUSTAINABLE ECONOMIC DEVELOPMENT
ROR ID(s) of organization(s) affected by this change: https://ror.org/02an8es95
How should the record(s) be changed? Please add the folowing insitutions:
1- ENEA Frascati Research Centre, Via E. Fermi 45 I-00044 Frascati (Roma) Italy
2- ENEA- Casaccia Research Centre via Anguillarese 301 I-00123 Roma, Italy
3- ENEA- Brasimone Research Centre Località Brasimone, I-40032 Camugnano (Bologna, Italy 
4- ENEA- Italian Natiional Institute of Ionizing Radiation Metrology, via Anguillarese 301 I-00123 Roma, Italy

---
Per curatorial discussion: expanding as project to include all ENEA research centers:

- ENEA Bologna Research Centre
- ENEA Brasimone Research Centre
- ENEA Brindisi Research Centre
- ENEA Casaccia Research Centre
- ENEA Frascati Research Centre
- ENEA Portici Research Centre
- ENEA Saluggia Research Centre
- ENEA Santa Teresa Research Centre
- ENEA Trisaia Research Centre
- National Institute of Ionizing Radiation Metrology

**Comment by adambuttrick** [comment]
This should not be processed as a split, but a request to add four new children for Italy's National Agency for New Technologies, Energy and Sustainable Economic Development. Assuming approval, I'll create separate record requests for each of these.

As to their scope, these do appear to be independent, national-level research facilities. Each has its own publication affiliation usage:

ENEA Casaccia Research Centre
https://ieeexplore.ieee.org/author/37085367280

ENEA Frascati Research Centre
https://ieeexplore.ieee.org/author/37314209000

ENEA Brasimone
https://ieeexplore.ieee.org/author/37086187013

ENEA Italian Natiional Institute of Ionizing Radiation Metrology
https://ieeexplore.ieee.org/author/37529688700

**Comment by arthurpsmith** [comment]
I've found the Italian research institute organizations generally quite confusing - for CNR or INFN they seem to have multiple differing hierarchical breakdowns, with the bottom level being what seem to be quite small university-level institutes of (sometimes) just a handful of people. But I agree with the main point of Adam's comment above that we should keep https://ror.org/02an8es95 as the main organization with headquarters in Rome, and add subsidiary orgs as needed. Note the wikipedia page for ENEA lists 11 research centers in addition to the Rome headquarters, so more than just these 4 requested, and that list does not seem to include the "Italian National Institute of Ionizing Radiation Metrology" so as usual, confusing.

By the way, what is https://ror.org/01sfh2b07 ?  A branch of this Italian agency in London? Or a mistake?

ENEA Frascati has a Wikidata entry: https://www.wikidata.org/wiki/Q40211354
and ISNI: https://isni.org/isni/0000000406480033
Also the Brasimone (Bologna) center I think: https://www.wikidata.org/wiki/Q54856965
although the latter doesn't seem to mention Brasimone at all so not sure?

Anyway, in general consider this "approved" - I'll move it to the "ready for signoff" column but what we really want is a number of new requests to add these specific research centers.

**Comment by adambuttrick** [comment]
@arthurpsmith Thank you for reviewing! I will attempt to consolidate all the ENEA research institute metadata for the 11(?) institutions into a single project issue/spreadsheet and we can take things from there.

**Comment by adambuttrick** [comment]
@arthurpsmith Metadata in the attached. I confirmed publication affiliation usage for all as well
[ENEA_research_centers.xlsx](https://github.com/ror-community/ror-updates/files/8543404/ENEA_research_centers.xlsx)
.

**Comment by arthurpsmith** [comment]
Looks good - I also found a Wikidata ID for INMRI - Q3803641.

**Comment by adambuttrick** [comment]
Records created as part of release v1.1.

ROR ID | Organization name
-- | --
https://ror.org/0496k0e74 | ENEA Bologna Research Centre
https://ror.org/03zjaj674 | ENEA Brasimone Research Centre
https://ror.org/05k1m9s26 | ENEA Brindisi Research Centre
https://ror.org/02khqd465 | ENEA Casaccia Research Centre
https://ror.org/01026pq66 | ENEA Frascati Research Centre
https://ror.org/00x69dn41 | ENEA Portici Research Centre
https://ror.org/05nczym02 | ENEA Saluggia Research Centre
https://ror.org/018j1ye79 | ENEA Santa Teresa Research Centre
https://ror.org/023q8n217 | ENEA Trisaia Research Centre
https://ror.org/01m7aex78 | National Institute of Ionizing Radiation Metrology
