### ISSUE TITLE
Modify the information in an existing ROR record: John Marshall Law School

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#5083]
Summary of request: Modify the information in an existing ROR record

Name of organization: John Marshall Law School
ROR ID: https://ror.org/059bgk218 
Which part of the record needs to be changed? Name, Website, possibly status, possibly relationships
Description of change: The John Marshall Law School in Chicago merged with the University of Illinois in 2019 and changed its name to the University of Illinois Chicago John Marshall Law School. In 2021 it changed its name again to University of Illinois Chicago School of Law. The website at http://www.jmls.edu/ no longer works. See https://www.wikidata.org/wiki/Q6246903 and https://en.wikipedia.org/wiki/University_of_Illinois_Chicago_School_of_Law 

Update: change.status==inactive;$

Related organizations: https://ror.org/02mpq6x41 (successor-np)

**Comment by adambuttrick** [comment]
Changing to inactive and identifying successor, since this has been merged into https://ror.org/02mpq6x41.

**Comment by adambuttrick** [comment]
Record updated in release v1.31.
