### ISSUE TITLE
Add a new organization to ROR: 
 
Fundació I-CERCA - Centres de Recerca de Catalunya

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#511]
Name of organization: CERCA Institution
Website: http://www.cerca.cat/
Link to publications: https://portalrecerca.csuc.cat/
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://en.wikipedia.org/wiki/CERCA_Institute
Wikidata ID: Q30100395
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: Research Centers of Catalonia
Labels: Institució CERCA - Centres de Recerca de Catalunya*Catalan; Fundació Institució dels Centres de Recerca de Catalunya*Catalan;
Acronym/abbreviation: CERCA; I-CERCA;
Related organizations: https://ror.org/02dm87055 (child); https://ror.org/03ej8a714 (child); https://ror.org/04tz2h245 (child); https://ror.org/03abrgd14 (child); https://ror.org/0241avf06 (child); https://ror.org/03wyzt892 (child); https://ror.org/020s51w82 (child); https://ror.org/02tt2zf29 (child); https://ror.org/001cwea56 (child); https://ror.org/02rkks755 (child); https://ror.org/038c0gc18 (child); https://ror.org/056h71x09 (child); https://ror.org/05rke5d69 (child); https://ror.org/04nwrc387 (child); https://ror.org/03g5ew477 (child); https://ror.org/013j2zh96 (child); https://ror.org/00k1qja49 (child); https://ror.org/04qeh2h86 (child); https://ror.org/04zfaj906 (child); https://ror.org/054vayn55 (child); https://ror.org/0008xqs48 (child); https://ror.org/020yb3m85 (child); https://ror.org/00k6njn28 (child); https://ror.org/01sdrjx85 (child); https://ror.org/03bzdww12 (child); https://ror.org/01av3a615 (child); https://ror.org/042nkmz09 (child); https://ror.org/02zbs8663 (child); https://ror.org/01z1gye03 (child); https://ror.org/03mfyme49 (child); https://ror.org/03b6f4629 (child); https://ror.org/00btzwk36 (child); https://ror.org/001synm23 (child); https://ror.org/03g7nb016 (child); https://ror.org/012zh9h13 (child); https://ror.org/03hjgt059 (child); https://ror.org/01d5vx451 (child); https://ror.org/03q0p7c86 (child); https://ror.org/012zh9h13 (child); https://ror.org/03mw46n78 (child); https://ror.org/018ndmv91;
City: Barcelona
Country: Catalunya (Spain)
Geonames ID: 3128760
Year established: 2010
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system, International Evaluation of our research institutes

Other information about this request: CERCA is a group of 42 research institutes funded by Generalitat de Catalunya. The organization has requested CERCA Institution be their primary name.

**Comment by arthurpsmith** [comment]
Yes, definitely, similar I guess to https://ror.org/01hhn8329 (Max Planck Society) we should have the parent organization as well as all these children institutes.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01bkbaq61 in release v1.0.
