### ISSUE TITLE
Modify the information in an existing ROR record: Freie Universität Berlin - https://ror.org/046ak2485

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#5115]
Summary of request: Modify the information in an existing ROR record

Name of organization: Freie Universität Berlin
ROR ID: https://ror.org/046ak2485
Which part of the record needs to be changed? Links, ISNI
Description of change: Replace links with https://www.fu-berlin.de. Add ISNI ID 0000 0001 2185 5786 as preferred.

Update: replace.links==https://www.fu-berlin.de; add.ISNI==0000 0001 2185 5786;$

**Comment by MSpenger** [comment]
ISNI should be changed to 0000 0001 2185 5786 . The link can also be updated (https://github.com/ror-community/ror-updates/wiki/ROR-Metadata-Policies#links)

**Comment by adambuttrick** [comment]
Record updated in release v1.32.
