### ISSUE TITLE
Project: Add 11 new child organizations to ROR

### ISSUE THREAD

**Issue by MarioLocati** [ror-community/ror-updates#5117]
Summary of request: Add 11 child organizations to an existing main ROR record

At the Data Management Office of INGV we require to identify each physical branch in which is subdivided our Public Research Organisation, an organisation that already exists in ROR and it is identified with the following record
> Istituto Nazionale di Geofisica e Vulcanologia
> https://ror.org/00qps9a02

The main organisation is currently classified with the type "Facility".
I request the type it is changed into "Government".

Below the description of the 11 child organisations that should be created and associated with the main organization https://ror.org/00qps9a02

Name of organization: INGV Amministrazione Centrale
Website: https://istituto.ingv.it/
Organization Type: Facility
Acronym/abbreviation: INGV-AC
City: Rome
Country: Italy
Geonames ID: 3169070

Name of organization: INGV Sezione di Roma 1
Website: http://roma1.ingv.it/
Organization Type: Facility
Acronym/abbreviation: INGV-Roma1
City: Rome
Country: Italy
Geonames ID: 3169070

Name of organization: INGV Sezione di Roma 2
Website: https://roma2.ingv.it/
Organization Type: Facility
Acronym/abbreviation: INGV-Roma2
City: Rome
Country: Italy
Geonames ID: 3169070

Name of organization: INGV Osservatorio Nazionale Terremoti
Website: https://www.ont.ingv.it/
Organization Type: Facility
Acronym/abbreviation: INGV-ONT
City: Rome
Country: Italy
Geonames ID: 3169070

Name of organization: INGV Osservatorio Vesuviano
Website: https://www.ov.ingv.it/
Organization Type: Facility
Acronym/abbreviation: INGV-OV
City: Napoli
Country: Italy
Geonames ID: 3172391

Name of organization: INGV Osservatorio Etneo
Website: https://www.ct.ingv.it/
Organization Type: Facility
Acronym/abbreviation: INGV-OE
Wikidata Q112972503
City: Catania
Country: Italy
Geonames ID: 2525068

Name of organization: INGV Sezione di Milano
Website: https://www.mi.ingv.it/
Organization Type: Facility
Acronym/abbreviation: INGV-MI
City: Milan
Country: Italy
Geonames ID: 3173435

Name of organization: INGV Sezione di Bologna
Website: https://www.bo.ingv.it/
Organization Type: Facility
Acronym/abbreviation: INGV-BO
City: Bologna
Country: Italy
Geonames ID: 3181928

Name of organization: INGV Sezione di Pisa
Website: https://www.pi.ingv.it/
Organization Type: Facility
Acronym/abbreviation: INGV-PI
City: Pisa
Country: Italy
Geonames ID: 3170647

Name of organization: INGV Sezione di Palermo
Website: https://www.pa.ingv.it/
Organization Type: Facility
Acronym/abbreviation: INGV-PA
City: Palermo
Country: Italy
Geonames ID: 2523920

Name of organization: INGV Sezione Irpinia
Website: http://www.gm.ingv.it/
Organization Type: Facility
Acronym/abbreviation: INGV-IRP
City: Grottaminarda
Country: Italy
Geonames ID: 3175772

This request tries to adopt an approach adopted by another similarly structured Italian Research institution, the INFN https://ror.org/005ta0471. Just to be clear, consider this a simple remark, I am not requesting to establish any relation between INFN and INGV.

**Comment by adambuttrick** [comment]
Treating as project issue, as there are new records involved with this requests. Affiliation usage follows the pattern provided, so these are otherwise fine to add.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05ezvck41 in release v1.32.

**Comment by MarioLocati** [comment]
@adambuttrick Thank you, I can confirm that all the suggested new entries are available
https://ror.org/search?query=ingv

Sadly, I think something wen wront and there is now a duplicated entry called "INGV Amministrazione Centrale":
1) https://ror.org/029rr4k19
2) https://ror.org/05ezvck41

Please, remove the second entry.

**Comment by adambuttrick** [comment]
@MarioLocati Thank you for reporting. I've created the issue to correct.

**Comment by MarioLocati** [comment]
@adambuttrick I'm sorry, one last thing just discovered: as I don't see "INGV Amministrazione Centrale" among the child organisations of the main INGV organisation (https://ror.org/00qps9a02), I think the relationship "child" is missing in https://ror.org/029rr4k19
