### ISSUE TITLE
Add a new organization to ROR: 
 
Japan Geoscience Union

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#514]
Add record:
Name of organization: Japan Geoscience Union
Website: https://www.jpgu.org
Link to publications: progearthplanetsci.org
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: Q11507752
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels: 日本地球惑星科学連合*Japanese;
Acronym/abbreviation: JpGU
Related organizations: 
City: Tokyo
Country: Japan
Geonames ID: 1850147
Year established: 1990
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Japanese geosciences advocacy group. Itself publishes journal "Progress in Earth and Planetary Sciences" and partners on other English-language geoscience journals (https://www.jpgu.org/en/publications/#gakujutsu). Used as a membership affiliation by researchers. Should be added to ROR.

ORCID affiliation usage: https://orcid.org/0000-0002-0681-4932 ; https://orcid.org/0000-0003-1817-057X ; https://orcid.org/0000-0003-1014-7172

**Comment by mariagould** [comment]
I agree that this is in scope as an independent organization that publishes research and is used as an affiliation by researchers.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/044r01e44 in release v1.0.
