### ISSUE TITLE
Add a new organization to ROR: 
 
ESCIRE S.A.

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#517]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: eScire
Website: https://www.escire.lat
Link to publications: https://www.youtube.com/channel/UCA9Z8UrIbuhycRkEniug19w
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: escire
Labels:
Acronym/abbreviation:
Related organizations: 
City: Panama City
Country: Panamá
Geonames ID: 3703443
Year established: 2012
How will a ROR ID for this organization be used? To be integrated in a scholarly publishing system, To promote the good practices for the FAIR principles within the community.

Other information about this request: We are a company that promote the good practices for the open access and the open science culture. We work with differnt academic, gubernamental and research institutions with their research publications, libraries and other areas with projects related to open science and open access practices.

**Comment by adambuttrick** [comment]
Library and open access technology consulting firm working with institutions across Latin America on adopting these platforms. Helps institutions implement the Open Journal System (https://pkp.sfu.ca/ojs/) in this region and is referenced as a service provider for similar software implementations on DataCite website (https://support.datacite.org/docs/service-provider-software-integrations). Believe they are in scope for ROR.

**Comment by nlundvick** [comment]
Bit of an outlier as this organization does not seem to be involved in research nor used as an affiliation. However, I do agree with previous reviewer's comments. Also, similar organization is in ROR - 4Science (https://ror.org/03vb2cr34). Concur that a ROR ID should be assigned to eScire.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02thjp576 in release v1.0.
