### ISSUE TITLE
Add a new organization to ROR: 
 
ISMO Bio-Photonics Private Limited 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#518]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: ISMO Bio-Photonics
Website: www.ismobiophotonics.com
Link to publications: https://doi.org/10.1063/5.0041027
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: ISMO Bio-Photonics
Labels:
Acronym/abbreviation:
Related organizations: 
City: Chennai
Country: India
Geonames ID: 1264527
Year established: 2020
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders

Other information about this request:

**Comment by adambuttrick** [comment]
Bioreactor startup company with MIT affiliations. Appears relatively new without affiliation usage (linked publication uses university affiliations). Press references to the company on their site, including, again MIT (https://picower.mit.edu/news/tiny-brains-grown-3d-printed-bioreactor). Clearly involved with biotechnology R&D, but also may be a one or two person entity (contact email is principal developer of the bioreactor). Leaning toward Hold for Later versus denying outright.

**Comment by nlundvick** [comment]
This looks like a small startup that is attempting to sell a single piece of medical equipment (a 3D-printed bioreactor). While the bioreactor may be used in medical research, I am not seeing anything to indicate the company itself will be involved in scholarly research. Moving to Hold for Later per previous curator's comments.

**Comment by adambuttrick** [comment]
Still no research outputs using this affiliation, so declining for lack of supporting evidence.
