### ISSUE TITLE
Add a new organization to ROR: 
 
NBIS -- National Bioinformatics Infrastructure Sweden

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#519]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: National Bioinformatics Infrastructure Sweden
Website: https://nbis.se
Link to publications: doi: 10.1371/journal.pone.0215077. eCollection 2019.
Organization type: Other
Wikipedia page: 
Wikidata ID: Q109518478
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels:
Acronym/abbreviation: NBIS
Related organizations: ELIXIR (parent) https://ror.org/03zttf063 (related) https://ror.org/04ev03g22 (related) https://ror.org/05ynxx418 (related) https://ror.org/040wg7k59 (related) https://ror.org/01tm6cn81 (related) https://ror.org/056d84691 (related) https://ror.org/026vcq606 (related) https://ror.org/012a77v79 (related) https://ror.org/05k323c76 (related) https://ror.org/02yy8x990 (related) https://ror.org/05f0yaq80 (related) https://ror.org/05kb8h459 (related) https://ror.org/004hzzk67 (related)
City: Uppsala
Country: Sweden
Year established: 2008
Geonames ID: 2666199
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility

Other information about this request:

**Comment by adambuttrick** [comment]
Distributed national bioinformatics research infrastructure supported by the Swedish Research Council, Science for Life Laboratory, and several major Swedish universities. Clearly in scope for ROR.

Google Scholar affiliation_usage: https://scholar.google.com/citations?user=A3i-TV4AAAAJ; https://scholar.google.com/citations?user=lqZKmqIAAAAJ; https://scholar.google.com/citations?user=TNHVVA4AAAAJ

ORCID affiliation usage: https://orcid.org/0000-0003-0502-1401 ; https://orcid.org/0000-0003-1984-8522 ; https://orcid.org/0000-0002-2122-536X

**Comment by arthurpsmith** [comment]
Seems fine to me. I suspect there are similar organizations in other European countries that are their respective contact-points for ELIXIR, which we'll also be asked to add. But this one has been around for a while, and certainly seems to qualify on its own.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00enajs79 in release v1.1.
