### ISSUE TITLE
Add a new organization to ROR: 
 
TU Delft Open Publishing

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#520]
Summary of request: Add a new organization to ROR

Name of organization: TU Delft Open Publishing
Website: https://www.tudelft.nl/library/open-publishing
Link to publications: https://journals.open.tudelft.nl/, https://doi.org/10.34641/mg.14 DOI; https://doi.org/10.5074/T.2022.001; 
Organization type: Other (Use this category for any organization that does not fit the categories above)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: TU Delft OPEN Publishing
Labels:
Acronym/abbreviation: TU Delft OPEN
Related organizations: 
City: Delft
Country: The Netherlands
Geonames ID: 2757345
Year established: 2019
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request: Welcome to TU Delft OPEN, the open access publisher of Delft University of Technology (TU Delft). We publish high-standard, peer-reviewed content authored or edited by academics of TU Delft, often in collaboration. TU Delft OPEN predominantly publishes books, journals, and textbooks, but, as an open access publisher, we seek to expand and include other types of scholarly content. We also provide support, consultancy and services to TU Delft scholars in their journey towards academic and societal visibility, and impact.

**Comment by adambuttrick** [comment]
TU Delft's university press. Publishes numerous open access books and journals, including co-publications with other universities and research institutes (e.g. [International Journal of Water Governance](https://journals.open.tudelft.nl/ijwg)). More examples [here](https://www.tudelft.nl/en/library/current-topics/open-publishing). While university presses normally require independent affiliation usage, the scope of their activities and editorial involvement from outside researchers puts them closer to the precedents like https://ror.org/03jsdjx34 and https://ror.org/006v7bf86. Believe they are in scope for ROR.

**Comment by arthurpsmith** [comment]
It seems to me this is too closely tied to TU Delft to qualify for a separate ROR id. Cambridge University Press has its own website, has been around almost 500 years, has a major presence in many areas of publishing, has thousands of employees around the world - and has a pretty substantive wikipedia page about itself. I don't think this university press is anywhere close to comparable.

**Comment by adambuttrick** [comment]
Out of scope, per discussion on June 7th, 2022. Should use broader university affiliation.

**Comment by fredbelliard** [comment]
Hello, 
What is the status of our application? I am a bit confused by the correspondence. On top, it says closed and below open. Do you need more information? Thanks.

**Comment by adambuttrick** [comment]
@fredbelliard Apologies, the curation team is still trying to assess this kind of publisher use case. Traditionally, TU Delft Open Publishing would be out of scope and we would instead advise to use the university's ROR ID instead. We are meeting to discuss next week and I will follow up with up with you.  #4211 is the open issue to track.
