### ISSUE TITLE
Add a new organization to ROR: 
 
Institute for Geometry and Physics

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#524]
Summary of request: Add a new organization to ROR

Name of organization: Institute for Geometry and Physics
Website: https://www.igap-ts.it
Link to publications: -- 
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: 
Labels:
Acronym/abbreviation: IGaP-TS; IGaP
Related organizations: https://ror.org/004fze387 (parent) https://ror.org/009gyvm78 (parent)
City: Trieste
Country: Italy
Geonames ID: 3165185
Year established: 2018
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility

Other information about this request: IGaP is a recent joint institute shared by SISSA and ICTP in Trieste - Italy. We need to get the status of recognized affiliation in publications records, like INSPIRE-HEP or arXiv to increase the visibility of the institute and accounting to promote us while asking future funding.

**Comment by adambuttrick** [comment]
Relatively new, joint institute between  https://ror.org/004fze387 and  https://ror.org/009gyvm78, intended to bridge research between the domains of mathematics and physics. Conducts seminars. Used as part of a compound affiliation usage. 

Publication affiliation: https://link.springer.com/article/10.1007/s40879-021-00461-0 ; https://link.springer.com/article/10.1007/s40863-020-00199-9 ; https://arxiv.org/pdf/2112.09698.pdf ; https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.126.231602

**Comment by nlundvick** [comment]
Concur - In scope with scholarly affiliation use. Add to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04ys00n93 in release v1.1.
