### ISSUE TITLE
Add a new organization to ROR: 
 
Hochschullehrerbund

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#525]
Summary of request: Add a new organization to ROR

Name of organization: Hochschullehrerbund
Website: https://www.hlb.de
Link to publications: https://www.hlb.de/die-neue-hochschule
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: https://de.wikipedia.org/wiki/Hochschullehrerbund
Wikidata ID: Q1622266
ISNI ID: 0000 0001 0431 9412
GRID ID: 
Crossref Funder ID: 
Aliases: 
Labels: German Association of Professors of Universities of Applied Sciences*English
Acronym/abbreviation: HLB
Related organizations: 
City: Bonn
Country: Germany
Geonames ID: 3247450
Year established: 1972
How will a ROR ID for this organization be used? To identify affiliations for research publications, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Professional association for university lecturers in Germany. Produces a bi-monthly publication, "Die Neue Hochschule" (https://www.hlb.de/die-neue-hochschule), which features research on university-related pedagogical, occupational and management subjects. Only membership affiliation usage as far as I can tell. This looks to be an example of "publishes research."

ORCID affiliation usage: https://orcid.org/0000-0002-1120-977X ; https://orcid.org/0000-0003-4664-4963 ; https://orcid.org/0000-0002-5291-4301

**Comment by arthurpsmith** [comment]
I added the ISNI id for this. Is that an official English translation of the name of this organization? I couldn't find any English version of their website so it doesn't look like it came from there?
It does clearly have members involved in research, and publishes some things that also qualify. We do have a number of professional associations like this in ROR so I think it's fine to add this one.

**Comment by adambuttrick** [comment]
@arthurpsmith This was the English name included in the request by the CEO of the organization. Apologies for not tagging org-requested. That being said, I can also find no reference to this form of the name anywhere, so I think its best to keep the German as the primary. Thank you for catching.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01kk9d604 in release v1.1.
