### ISSUE TITLE
Modify the information in an existing ROR record: 
Parks and Wildlife Commission of the Northern Territory https://ror.org/05fyd4h04


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#526]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Parks and Wildlife Commission of the Northern Territory
ROR ID: https://ror.org/05fyd4h04
Which part of the record needs to be changed? Something else
Description of change: hello, the URL of this record is Australian, but the address details are in New Zealand. One of these must be wrong, please can you resolve? Thanks! Iain

Update: change.Geonames==2073124; add.Wikidata==Q21538549; add.ISNI==0000 0001 0845 6238;$

**Comment by adambuttrick** [comment]
Address details should be for Australia, not New Zealand. Updating to capital city of the Northern Territory and adding some external IDs from Wikidata.
