### ISSUE TITLE
Add a new organization to ROR: 
 
Millennium Institute SAPHIR, Santiago

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#527]
Summary of request: Add a new organization to ROR

Name of organization: Millennium Institute for Subatomic Physics at High-Energy Frontier, Saphir
Website: https://www.institutosaphir.cl
Link to publications: https://www.institutosaphir.cl/
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: SAPHIR Millennium Institute
Labels: Instituto Milenio de Física Subatómica en la Frontera de Altas Energías, Saphir*Spanish; 
Acronym/abbreviation: SAPHIR
Related organizations: https://ror.org/05510vn56 (parent) https://ror.org/01qq57711 (parent) https://ror.org/04teye511 (parent) https://ror.org/04xe01d27 (parent) https://ror.org/01ht74751 (parent) https://ror.org/01c080z51 (parent)
City: Santiago
Country: Chile
Geonames ID: 3871336
Year established: 
How will a ROR ID for this organization be used? To identify affiliations for research publications

Other information about this request:

**Comment by adambuttrick** [comment]
Subatomic scientific research center facility, similar to CERN, funded by the Millennium Science Initiative (MSI) and hosted by the Universidad Técnica Federico Santa María, Universidad Andrés Bello, Pontificia Universidad Católica de Chile, Universidad de La Serena and Universidad de Tarapacá. Funds and employs researchers (https://www.institutosaphir.cl/investigadores/). In scope for ROR.

**Comment by arthurpsmith** [comment]
If we add this, I assume the official full Spanish name (Adam mentioned above) should be among the labels? SAPHIR seems an unfortunate acronym as it has been used previously for a (unrelated I think) particle detector and is also a surname and real word in some languages, so difficult to narrow down this as an affiliation by searching for this.

I did find some English-language papers using the name "Millennium Institute for Subatomic Physics at High-Energy Frontier - SAPHIR" as an affiliation - https://arxiv.org/pdf/2204.03256.pdf and https://doi.org/10.1140/epjc/s10052-021-09535-5

So yes this should be in ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00rbe2516 in release v1.1.
