### ISSUE TITLE
Modify the information in an existing ROR record: Kansas State University Salina https://ror.org/02mrpaq42 

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#528]
Summary of request: Modify the information in an existing ROR record

Name of organization: Kansas State University Salina
ROR ID: https://ror.org/02mrpaq42 
Which part of the record needs to be changed? Name + URL
Description of change: 
The name can be made clearer: Kansas State University Salina Aerospace and Technology Campus, and the URL updated: https://www.salina.k-state.edu/

Update: change.name==Kansas State University Salina Aerospace and Technology Campus; replace.links==https://www.salina.k-state.edu/; replace.wikipedia_url==https://en.wikipedia.org/wiki/Kansas_State_University_Salina_Aerospace_and_Technology_Campus; replace.Wikidata==Q6365093;$

**Comment by mariagould** [comment]
Hi @icraig-afk thanks for submitting this. I'm assigning it to curation lead @adambuttrick so this can go through our standard review workflow.

**Comment by adambuttrick** [comment]
@icraig-afk Adam Buttrick, here. I'm ROR's new Metadata Curation Lead. Yes, you may submit record requests using the new and update issue templates. It's not currently our preferred method for all requests, as we have issues with data completeness in requests that the form helps mitigate. But for those that are active within ROR community and know our ins and outs better than most, submitting via Github is fine as well. Please let me know if you have any questions about using the issue templates themselves.

**Comment by adambuttrick** [comment]
Changes correspond to organizations website.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
