### ISSUE TITLE
Add a new organization to ROR: Mataram College of Health Sciences / Sekolah Tinggi Ilmu Kesehatan (STIKES) Mataram

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#53]
Summary of request: Add a new organization to ROR

Name of organization: Mataram College of Health Sciences
Website: http://id.stikes-mataram.ac.id/
Link to publications: https://doi.org/10.2174/1573399816666200802183738
Wikipedia page: 
Wikidata ID: 
ISNI ID: 0000 0004 0406 3711
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: Sekolah Tinggi Ilmu Kesehatan (STIKES) Mataram
Acronym/abbreviation: STIKES
Related organizations: 
City: Lombok
Country: Indonesia
Other information about this request: Will be used for the author affiliation at HIJP https://myjurnal.poltekkes-kdi.ac.id/index.php/HIJP

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02684yk50 in release v1.0.
