### ISSUE TITLE
Modify the information in an existing ROR record: Orot Israel College https://ror.org/01rnt9r23

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#530]
Summary of request: Modify the information in an existing ROR record

Name of organization: Orot Israel College
ROR ID: https://ror.org/01rnt9r23
Which part of the record needs to be changed? Name and city change
Description of change: As per their website the name is: Orot Israel College of Education. There are two campus, Elkana and Rehovot. On the contact us page: https://english.orot.ac.il/contact-us it is Elkana that is listed. In ROR It is currently listed as Rosh HaAyin, which is ca 22km away according to Google Maps. Recommend to change to Elkana.

Update: change.Geonames==283986;$

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
