### ISSUE TITLE
Modify the information in an existing ROR record: Botanic Gardens Conservation International https://ror.org/014x7mf51

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#531]
Summary of request: Modify the information in an existing ROR record

Name of organization: Botanic Gardens Conservation International 
ROR ID:  https://ror.org/014x7mf51
Which part of the record needs to be changed? Address
Description of change: As per https://www.bgci.org/contact/, this organisation has several offices, one of which is the China office listed in ROR. The HQ however is in the UK, in London: https://www.bgci.org/legal-and-policies/. If a single node is to represent this org rather than a parent and multiple children, it would make sense to have this as the UK entry.

Update: change.Geonames==2643743;$

**Comment by adambuttrick** [comment]
Change to London as primary address makes sense based on the delineation of offices on the organization's site. I don't think the branch offices sufficiently constitute top-level entities, such that they should have their own ROR IDs, but moving to Second Review for additional consideration by others on the curation team.

**Comment by nlundvick** [comment]
I agree - Address should be updated to London, UK; branch offices are not sufficiently independent to require their own ROR IDs

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
