### ISSUE TITLE
Modify the information in an existing ROR record: UCL Australia https://ror.org/024atcf19

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#532]
Summary of request: Modify the information in an existing ROR record

Name of organization: UCL Australia
ROR ID: https://ror.org/024atcf19
Which part of the record needs to be changed? This location is permanently closed
Description of change: As per https://en.wikipedia.org/wiki/UCL_Australia this campus is now closed. I appreciate you can't easily mark as inactive just now, but I'm flagging so it can looked at at the appropriate time

@adambuttrick perhaps a new template could be created for the merge/split/deprecate issues?

Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
@icraig-afk I will look at adding this template.

**Comment by adambuttrick** [comment]
Campus was closed in 2017. Moving to Hold for Later until we have the ability to tombstone records.

**Comment by adambuttrick** [comment]
Record updated in release v1.15.
