### ISSUE TITLE
Modify the information in an existing ROR record: Central European Institute of Technology https://ror.org/01nvdnb36

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#533]
Summary of request: Modify the information in an existing ROR record

Name of organization: Central European Institute of Technology
ROR ID: https://ror.org/01nvdnb36
Which part of the record needs to be changed? Now closed
Description of change: This org in Austria has been closed since 2014, see notice at URL. http://www2.ceit.at/
Note that an org of very similar name exits in the Czech Republic: https://www.ceitec.eu/

Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
Closed, per the organization's site. Organization with a similar name is already represented in ROR - https://ror.org/01p7k1986. Moving to Hold for Later until we have the ability to tombstone records.

**Comment by adambuttrick** [comment]
Record updated in release v1.15.
