### ISSUE TITLE
Modify the information in an existing ROR record: Daniel Webster College https://ror.org/002c7gt96

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#534]
Summary of request: Modify the information in an existing ROR record

Name of organization: Daniel Webster College
ROR ID: https://ror.org/002c7gt96
Which part of the record needs to be changed? This org is now closed
Description of change: This org has been closed since 2017, see https://en.wikipedia.org/wiki/Daniel_Webster_College

Update: change.status==inactive;$

**Comment by adambuttrick** [comment]
Organization closed, per Wikipedia. Moving to Hold for Later until we have the ability to tombstone records.

**Comment by adambuttrick** [comment]
Record updated in release v1.15.
