### ISSUE TITLE
Add a new organization to ROR: 
 
Mental Health and Yoga Pvt Ltd

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#536]
Summary of request: Add a new organization to ROR

Name of organization: Mental Health and Yoga Pvt Ltd
Website: www.mhy.org.np
Link to publications: https://doi.org/10.31234/osf.io/2kfsu
Organization type: Healthcare (A medical care facility such as hospital or clinic. Excludes medical schools, which should be categorized as “Education”)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: मेन्टल हेल्थ एण्ड योगा प्रा लि
Labels:
Acronym/abbreviation: MHY
Related organizations: 
City: Pokhara
Country: Nepal
Year established: 2021
How will a ROR ID for this organization be used? To identify affiliations for research publications

Other information about this request:

**Comment by adambuttrick** [comment]
Appears to be a one-person organization. Copyright statement on the website is for Dhirendra Paudel, who is the only person who appears to use this affiliation. Publication provided is a preprint and uses this org as a secondary affiliation. All the authors previous articles use the primary affiliation (Department of Psychiatry, Dhaulagiri Hospital). Believe this is out of scope.

**Comment by nlundvick** [comment]
Concur - does not meet [criteria for inclusion](https://github.com/ror-community/ror-updates#criteria-for-inclusion-in-ror) and is out of scope
