### ISSUE TITLE
Modify the information in an existing ROR record: 
Bydgoszcz University of Science and Technology https://ror.org/049eq0c58


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#539]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Bydgoszcz University of Science and Technology
ROR ID: https://ror.org/049eq0c58
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website
Description of change: We would like to change the name of our university from University of Technology and Life Sciences in Bydgoszcz  to Bydgoszcz University of Science and Technology https://pbs.edu.pl/pl/
https://www.wikidata.org/wiki/Q677503

Update: change.name==Bydgoszcz University of Science and Technology; replace.links==https://pbs.edu.pl/pl/; replace.Wikidata==Q677503; replace.ISNI==0000 0001 1943 1810;$

**Comment by adambuttrick** [comment]
Name change corresponds to English-language Wikipedia entry (https://en.wikipedia.org/wiki/Bydgoszcz_University_of_Science_and_Technology) and is org requested. Updating the link as well.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
