### ISSUE TITLE
Modify the information in an existing ROR record: Partners Healthcare (https://ror.org/04py2rh25)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#54]
Summary of request: Modify the information in an existing ROR record

Name of organization: Partners Healthcare
ROR ID: https://ror.org/04py2rh25

Description of change: Organization changed names in early 2020 from Partners Healthcare to Mass General Brigham (following the link on the current listed URL will confirm name change)

New name: Mass General Brigham 
New URL: https://www.massgeneralbrigham.org/

Update: change.name==Mass General Brigham; delete.links==http://www.partners.org/; add.links==https://www.massgeneralbrigham.org/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
