### ISSUE TITLE
Add a new organization to ROR: ELIXIR

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#541]
Summary of request: Add a new organization to ROR

Name of organization: ELIXIR
Website: https://elixir-europe.org
Link to publications: 
Organization type: Other
Wikipedia page: https://en.wikipedia.org/wiki/ELIXIR
Wikidata ID: Q12269561
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Acronym/abbreviation:
Aliases: European Life-Sciences Infrastructure for Biological Information
Related organizations: https://ror.org/02catss52 (related) https://ror.org/00enajs79 (child)
City: Hinxton
Country: UK
Geonames ID: 2646840
Year established: 2013
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
European life sciences data infrastructure project with ties to life science organizations in most EU member states. Provides research funding to life science research organizations (https://elixir-europe.org/news/29-new-projects-funded-elixir). In scope for ROR.

**Comment by arthurpsmith** [comment]
I added a Wikidata id. ELIXIR Hub is used as an affiliation in some publications - https://doi.org/10.1093/bioinformatics/btz959 for example. Clearly involved in research and should be included.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/044rwnt51 in release v1.0.
