### ISSUE TITLE
Add new records for ENEA: 
 


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#543]
Summary of request: Add new records for ENEA

Add record:
Name of organization: 
Website: 
Link to publications: 
Organization type: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: 
Labels:
Acronym/abbreviation: 
Related organizations: 
City: 
Country: 
Year established: 
How will a ROR ID for this organization be used? 

Other information about this request: I would like to ask the possibility to add the following affiliation records for ENEA (Italian National Agency for New Technologies, Energy and Sustainable Economic Development):

1- ENEA- Department of Fusion and Technologies for Nuclear Safety and Security, Italy
2- ENEA - Management of Infrastructures and Services, Rome, Italy
3- ENEA - Department Energy Technologies and Renewable Sources, Rome, Italy
4- ENEA  - Italian National Institute of Ionizing Radiation Metrology, Italy
5 - ENEA - Institute of Radiation Protection, Italy;
6 - ENEA - Department for Sustainability, Italy
This request is because we have a project and in sumbitting papers related ti his project the different authors should be affiliated to the correct department.
Thank you for your attention
Regards
Antonino Pietropaolo

**Comment by adambuttrick** [comment]
Moving this to hold for later as this should be separate requests and I've reached out to the requester to provided better metadata/details. Also relates to #506, so tagging that here.

**Comment by adambuttrick** [comment]
Declining as requestor never responded with further details or metadata for the organization.
