### ISSUE TITLE
Add a new organization to ROR: 
 
Agence de Conseil et de Recherche Océanographiques

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#544]
Summary of request: Add a new organization to ROR

Name of organization: Agency for Consultation and Research in Oceanography
Website: https://acro.pagespro-orange.fr
Link to publications: https://doi.org/10.1093/plankt/fbab067; https://doi.org/10.1016/j.rsma.2020.101461; https://doi.org/10.1515/corrrev-2019-0111; https://doi.org/10.1016/j.envres.2020.109764; https://doi.org/10.1007/s10126-020-09971-6; http://www.eurekaselect.com/173578/article; doi: 10.1016/j.watres.2019.114883; doi:  10.1016/j.csr.2018.04.009; 
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels: Agence de Conseil et de Recherche Océanographiques*French; 海洋学咨询与研究所*Chinese
Acronym/abbreviation: ACRO
Related organizations: 
City: La Roche Canillac
Country: France
Geonames ID: 3006802
Year established: 1995
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Extensive publication history in peer-reviewed journals, but appears to only be being used by one person, Ian R. Jenkinson. Site lists some people working in administrative roles, but none whom appear to use the affiliation. By the one-person org rule, would be out of scope. 

ORCID affiliation usage: https://orcid.org/0000-0001-5488-8189

**Comment by arthurpsmith** [comment]
Agreed this seems to be at best a 3-person operation, only one of whom seems involved in research.
