### ISSUE TITLE
Add a new organization to ROR: 
 
The Library Code GmbH

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#545]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: The Library Code
Website: https://www.the-library-code.de
Link to publications: https://doi.org/10.3390/publications8020031
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels:
Acronym/abbreviation: TLC
Related organizations: 
City: Berlin
Country: Germany
Year established: 2017
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
German software company ran by a primary DSpace developer that helps libraries set up, manage, and develop DSpace instances. Limited affiliation usage, but does have relationship with ROR backer DataCite as a service provider.

**Comment by adambuttrick** [comment]
Spoke with DataCite and they have no requirement that service providers have ROR IDs. Leaning toward this being out of scope by being a one-person org.

**Comment by MSpenger** [comment]
With regard to DataCite's statement and the available information I would also vote for this entry as out of scope.
