### ISSUE TITLE
Add a new organization to ROR: 
 
Almayzab Digital Library

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#547]
Summary of request: Add a new organization to ROR

Name of organization: Almayzab Digital Library
Website: https://mdl.edu.sd
Link to publications: Ebsco
Organization type: Archive (An organization involved in stewarding research and cultural heritage materials. Includes libraries, museums, and zoos)
Wikipedia page:
Wikidata ID: 
ISNI ID: 0000 0005 0382 9428
GRID ID: 
Crossref Funder ID: 
Aliases: 
Labels:  مكتبة الميزاب الرقمية*Arabic
Acronym/abbreviation: MDL
Related organizations: 
City: Khartoum
Country: Sudan
Geonames ID: 379252
Year established: 2019
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Non-profit initiative in Sudan to provide electronic resource access to various journals and eBooks. Can find no affiliation usage, but ISNI suggests they're established. More an example of "touches research," but we have precedent for another Digital Library initiatives in ROR (e.g. https://ror.org/00p0gp915 ; https://ror.org/03rrpvb29).

**Comment by almayzab** [comment]
Hello im manger direct of almayzab digital library

**Comment by adambuttrick** [comment]
Hello, @almayzab! This request is waiting for review by our curation board. Please stay subscribed to it for updates. We will reach out if we need clarification with anything about the request.

**Comment by almayzab** [comment]
Hello, @adambuttrick  any news  
You can search for our find my  institution in ebsco by link 
https://www.ebsco.com/find-my-organization
Almayzab Digital Library or by location sudan
![Screenshot_٢٠٢٢٠٤٠٤-٠٦١٢٢٦_Samsung Internet](https://user-images.githubusercontent.com/101909818/161467820-b7ef75e7-a47b-45ad-8361-367d66e0967b.jpg)

**Comment by adambuttrick** [comment]
@almayzab This request is awaiting additional review by our curation team. The ROR registry is updated quarterly at the moment, which means that the soonest the record for your organization would be included is June of this year. Thank you for your patience as this request works its way through the curation process.

**Comment by arthurpsmith** [comment]
Unfortunately the WIkidata ID was deleted for lack of notability/supporting references - and also because an Arabic Wikipedia page for this organization had also been deleted. I've removed the ID (https://www.wikidata.org/wiki/Q111270132) from the metadata above.

Their website seems awfully slow from here, it's a little hard to find out much more about them. I couldn't find any third-party references to them either. Nevertheless, given the location and stated purpose in support of education and research I think this deserves benefit of the doubt here for now, we can add it.

**Comment by almayzab** [comment]
Any  new update about almayzab Digital Library

**Comment by adambuttrick** [comment]
@almayzab Your request has been approved and this record will be included in our next release. The release is currently slated for later this month. Please continue to follow this issue, as the ROR ID will be provided once the record has been released to production.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05gwnz115 in release v1.0.
