### ISSUE TITLE
Modify the information in an existing ROR record: 
Museum De Bastei https://ror.org/04y2aw426


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#548]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Museum De Bastei
ROR ID: https://ror.org/04y2aw426
Which part of the record needs to be changed? Other names or name versions listed in the record
Description of change: The organisation is currently listed with alias: Natuurmuseum Nijmegen. This is not correct and should be removed (on their request).
Museum De Bastei is the result of a merger between ‘Natuurmuseum Nijmegen’ and museum ‘De Stratemakerstoren’.

Other information about this request: technical contact for organisation De Bastei for questions about this request: Daphne Niehoff, Daphne.Niehoff@debastei.nl

Update: delete.aliases==Natuurmuseum Nijmegen;$

**Comment by adambuttrick** [comment]
Approving, as this change is org requested.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
