### ISSUE TITLE
Add a new organization to ROR: National Coordination Office

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#5485]
Summary of request: Add a new organization to ROR

Name of organization: National Coordination Office*English
Website: 
Link to publications: 
Organization type: Government
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 100014072
Other names for the organization: 
Aliases: NSF National Coordination Office*English; National Science Foundation National Coordination Office*English
Labels: 
Acronym/abbreviation: NCO; NSF NCO
Related organizations: https://ror.org/021nxhr62 (parent)
City: Washington D.C.
Country: United States
Geonames ID: 4140963
Year established: 
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of Funder Registry reconciliation. Inactive record.

**Comment by adambuttrick** [comment]
Need to determine appropriate relationships and hiearchy.

**Comment by adambuttrick** [comment]
Appears to possibly be defunct. All links on the NSF site that reference this appear to be dead ends. We should otherwise add as inactive as this has a fairly extensive funding history. @carlyrobinson is there any kind of internal US government registry for these kinds of orgs such that its status could be verified?

**Comment by carlyrobinson** [comment]
@adambuttrick there isn't any kind of registry. I wish it were as easy as that. :) I looked at the current NSF org chart and don't see the office (though it could be a sub office, it looks like an old directorate - https://www.nsf.gov/funding/programs.jsp?org=NCO#) - https://nsf-gov-resources.nsf.gov/2023-08/NSF_Org_Chart.pdf. I'm happy to reach out to NSF if that would be helpful.

**Comment by adambuttrick** [comment]
@carlyrobinson That would be great! If NSF could just whether its defunct or a sub-office, we can then handle.

**Comment by adambuttrick** [comment]
Requested advice from NSF.

**Comment by adambuttrick** [comment]
Barring availability of further counsel on this, adding as inactive child of NSF.

**Comment by carlyrobinson** [comment]
Thanks @adambuttrick. I just followed back up with NSF, but I think that makes sense.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03wmx8367 in release v1.45.
