### ISSUE TITLE
Add a new organization to ROR: 
 
Castor

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#549]
Summary of request: Add a new organization to ROR

Name of organization: Castor
Website: https://www.castoredc.com
Link to publications: https://scholar.google.com/citations?view_op=view_citation&hl=nl&user=Ak4DHewAAAAJ&citation_for_view=Ak4DHewAAAAJ:Tyk-4Ss8FVUC  https://link.springer.com/article/10.1186/s13326-020-00231-z;   https://www.sciencedirect.com/science/article/pii/S1532046421002264
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels:
Acronym/abbreviation:
Related organizations: 
City: Amsterdam
Country: The Netherlands
Geonames ID: 2759794
Year established: 2012
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets

Other information about this request:

**Comment by adambuttrick** [comment]
Provides a clinical research data platform and related medical technologies. Limited article affiliation usage (one person), but the company has multiple employees. Referenced in research as well (e.g. https://www.researchprotocols.org/2019/6/e13464/). Believe they are in scope for ROR.

Google Scholar affiliation usage: https://scholar.google.com/citations?user=Ak4DHewAAAAJ; 
ORCID affiliation usage: https://orcid.org/0000-0002-2475-6254 ; https://orcid.org/0000-0001-5702-5856

**Comment by arthurpsmith** [comment]
I've seen both Arts and Kersloot use this affiliation, and possibly some of their coauthors, so it's more than just one person. And it is clearly directly involved in research activities through their product offering. So yes let's add this.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0448sav47 in release v1.0.
