### ISSUE TITLE
Modify the information in an existing ROR record: Tokyo Institute of Technology (https://ror.org/0112mx960)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#55]
Summary of request: Modify the information in an existing ROR record

Name of organization: Tokyo Institute of Technology
ROR ID: https://ror.org/0112mx960

Description of change: Please add "東工大" as abbreviation of the official name "東京工業大学” and delete "TIT" from the list of names because we don't like to use it.

Update: add.acronyms==東工大; delete.acronyms==TIT;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
