### ISSUE TITLE
Modify the information in an existing ROR record: 
Ohio University Southern https://ror.org/039eaqm23


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#552]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Ohio University Southern
ROR ID: https://ror.org/039eaqm23
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website, Other IDs for the organization
Description of change: 1. The primary name needs to be changed to "Ohio University Southern". 
2. The name "Ohio Southern" needs to be removed completely. 
3. The website needs to be updated to: https://www.ohio.edu/southern 

Update: delete.aliases==OHIO Southern; replace.links==https://www.ohio.edu/southern;$

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
