### ISSUE TITLE
Add a new organization to ROR: 
 
Ohio University Eastern

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#554]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Ohio University Eastern
Website: https://www.ohio.edu/eastern
Link to publications: DOI 10.1007/s10440-012-9682-6.   DOI: 10.1103/PhysRevA.82.044301
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://en.wikipedia.org/wiki/Ohio_University_Eastern_Campus
Wikidata ID: Q16975104
ISNI ID: 0000 0004 0609 460X
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels:
Acronym/abbreviation: OUE
Related organizations: https://ror.org/01jr3y717 (parent)
City: St. Clairsville, Ohio
Country: United States of America
Geonames ID: 5169130
Year established: 1957
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders

Other information about this request:

**Comment by nlundvick** [comment]
Concur with first reviewer - assign ROR ID

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/006hbbw23 in release v1.1.
