### ISSUE TITLE
Add a new organization to ROR: Health & Hospital Corporation of Marion County

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#5557]
Summary of request: Add a new organization to ROR

Name of organization: Health & Hospital Corporation of Marion County
Website: https://hhcorp.org
Link to publications: 
Organization type: Other
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: Health and Hospital Corporation of Marion County
Labels: 
Acronym/abbreviation: HHC
Related organizations: https://ror.org/00zskr649 (child) https://ror.org/0046t1019 (child)
City: Indianapolis, IN
Country: United States
Geonames ID: 4259418
Year established: 1951
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by andtheWings** [comment]
Regarding related organizations, I think there should be a new entity inserted between this new record and the existing, proposed child record (https://ror.org/02fj1x097). It might be easiest just to outline the whole hierarchy:

- Health & Hospital Corporation of Marion County (the government operator, a new record, this Github issue)
    - Marion County Public Health Department (the public health entity, new record, https://github.com/ror-community/ror-updates/issues/5544)
    - Eskenazi Health (the healthcare system, would be a new record, no issue created yet)
        - Sidney and Lois Eskenazi Hospital (the hospital facility, an existing record, https://ror.org/02fj1x097, but the label should be switched to "Sidney and Lois...", the old name is "Wishard Memorial Hospital" from before rebranding, no issue created yet).
        - Various community clinics (no significant research output, don't need their own ROR records, but could use the healthcare system record when wanting to name an affiliation)

You would also remove Eskenazi Health Foundation (non-profit funding and development entity, https://ror.org/0391w8d97) as a parent to the hospital (https://ror.org/02fj1x097) and add it as a parent to the healthcare system instead.

Sorry to mash all this together in one issue, but they're all so interrelated, it seems like it would be more confusing to split up all the information between separate Github issues.

**Comment by adambuttrick** [comment]
@andtheWings Thank you for this context. I will assess and create the corresponding issues, as needed.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02yjy0144 in release v1.34.
