### ISSUE TITLE
Modify the information in an existing ROR record: 
Ohio University Lancaster https://ror.org/03kf4rc21


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#556]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Ohio University Lancaster
ROR ID: https://ror.org/03kf4rc21
Which part of the record needs to be changed? Primary name
Description of change: Please remove the hyphens in the name. It should read: Ohio University Lancaster

Update: change.name==Ohio University Lancaster;$

**Comment by adambuttrick** [comment]
Change corresponds to org's branding on website.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
