### ISSUE TITLE
Modify the information in an existing ROR record: 
Ohio University  https://ror.org/01jr3y717


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#557]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Ohio University 
ROR ID: https://ror.org/01jr3y717
Which part of the record needs to be changed? Primary name
Description of change: Please change the name to: Ohio University Athens

**Comment by adambuttrick** [comment]
I don't believe we should change this entry to being the Athens campus, as that is not how it is used as an affiliation (https://orcid.org/0000-0003-2354-1523 ; https://orcid.org/0000-0003-3431-5513 ; https://orcid.org/0000-0003-0461-5638 ; https://orcid.org/0000-0003-3623-3925), nor in their copyright and branding. Those working on other campuses use a qualifier (e.g. https://orcid.org/0000-0002-1700-6797), but every affiliation usage instance I've found for the Athens location does not.
