### ISSUE TITLE
Modify the information in an existing ROR record: KBase - https://ror.org/01znn6x10

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#5594]
Summary of request: Modify the information in an existing ROR record

Name of organization: KBase
ROR ID: https://ror.org/01znn6x10
Which part of the record needs to be changed? Alias; Parent organization; Related organization
Description of change: Aliases: add United States Department of Energy Office of Science Lawrence Berkeley National Laboratory KBase. Parent organization: remove United States Department of Energy, add Lawrence Berkeley National Laboratory. Related organization: add Joint Genome Institute and Environmental Molecular Sciences Laboratory. Part of #5576

Update: add.aliases==United States Department of Energy Office of Science Lawrence Berkeley National Laboratory KBase; add.aliases==U.S. Department of Energy Office of Science Lawrence Berkeley National Laboratory KBase;   add.aliases==United States Department of Energy KBase; add.aliases==U.S. Department of Energy KBase;$

Related organizations: https://ror.org/04xm1d337 (related) https://ror.org/04rc0xn13 (related)

**Comment by adambuttrick** [comment]
Record updated in release v1.34.

**Comment by elishawc** [comment]
Thank you for the updates! 
Re: "Parent organization: remove United States Department of Energy, add Lawrence Berkeley National Laboratory" - LBNL is the lead lab, but we also have team members at Oak Ridge NL, Argonne NL, and Brookhave NL. Would be be appropriate to list all 4 under "parent"? 

The other names is super confusing... and probably should only have the "Department of Energy" and "Office of Science" components, and not LBNL in this section.
Department of Energy Systems Biology Knowledgebase, United States Department of Energy Office of Science Lawrence Berkeley National Laboratory KBase, U.S. Department of Energy Office of Science Lawrence Berkeley National Laboratory KBase, United States Department of Energy KBase, U.S. Department of Energy KBase

e.g., our funding statement: The DOE Systems Biology Knowledgebase (KBase) is funded by the [U.S. Department of Energy, Office of Science, Office of Biological and Environmental Research](http://science.energy.gov/ber/) under Award Numbers DE-AC02-05CH11231, DE-AC02-06CH11357, DE-AC05-00OR22725, and DE-AC02-98CH10886. (w/ the award numbers associated w/ the 4 NLs)

**Comment by adambuttrick** [comment]
@elishawc Thanks for your feedback! This was updated as part of a bulk DOE OSTI submission, but we're happy to correct. From what you outlined, it appears the aliases should be limited to the below:

- Department of Energy Systems Biology Knowledgebase
- DOE Systems Biology Knowledgebase
- United States Department of Energy Office of Science KBase
- United States Department of Energy KBase
- U.S. Department of Energy KBase

And the correct parent organization is either the DOE Office of Science - https://ror.org/00mmn6b08 or 
DOE Office of Science, Office of Biological and Environmental Research - https://ror.org/0114b2m14.

Could you please confirm? We will update then accordingly in our next release

**Comment by elishawc** [comment]
Aliases - yes! For the first one, let's add "US", so it would be:
US Department of Energy Systems Biology Knowledgebase

For parent, please use - https://ror.org/0114b2m14

Thank you!
