### ISSUE TITLE
Add a new organization to ROR: Centro de diseño, cine y televisión

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#56]
Summary of request: Add a new organization to ROR

Name of organization: Centro de diseño, cine y televisión
Website: http://www3.centro.edu.mx/
Link to publications: We are working with DOIs for ours papers
Wikipedia page: 
Wikidata ID: Q52660807
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: CENTRO
Related organizations: 
City: Mexico City
Country: Mexico
Other information about this request:

**Comment by carlyrobinson** [comment]
Agree, should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04qzdz471 in release v1.0.
