### ISSUE TITLE
Modify the information in an existing ROR record:  Swedish Institute for Children's Books https://ror.org/04a6wa396

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#5667]
Summary of request: Modify the information in an existing ROR record

Name of organization: Swedish Institute for Children's Books
ROR ID: https://ror.org/04a6wa396
Which part of the record needs to be changed? links
Description of change: The correct website for the SBI is https://www.barnboksinstitutet.se

Update: replace.links==https://www.barnboksinstitutet.se; add.Wikidata==Q10684945;$

**Comment by adambuttrick** [comment]
Link provided is that for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.34.
