### ISSUE TITLE
Modify the information in an existing ROR record: Vermont Center for the Book https://ror.org/01m1c9z98

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#5668]
Summary of request: Modify the information in an existing ROR record

Name of organization: Vermont Center for the Book 
ROR ID: https://ror.org/01m1c9z98
Which part of the record needs to be changed? Website, location, aliases, possibly types and status
Description of change: The website for the Vermont Center for the Book is currently https://www.vermonthumanities.org/about-vermont-humanities/the-humanities/center-for-the-book/ and that site says it is located in Montpelier. Also from their site: "Vermont Humanities became the Vermont Center for the Book in 2021, merging longstanding early childhood programs at the previously independent center with our own programs. The Vermont Center for the Book had been established as the Vermont Reading Project in 1985 and became the Vermont Center for the Book in 1994." It seems to have been that "previously independent center" whose website was www.mothergooseprograms.org -- see https://web.archive.org/web/20160327121418/http://www.mothergooseprograms.org/

Update: change.status==inactive;$

Related organizations: https://ror.org/05c602238 (successor-np)

**Comment by adambuttrick** [comment]
While the website has the description of the merger inverted, https://ror.org/01m1c9z98 became a sub-entity of https://ror.org/05c602238 in 2021. Changing status to inactive and identifying https://ror.org/05c602238 as its successor.

**Comment by adambuttrick** [comment]
Record updated in release v1.34.
