### ISSUE TITLE
Add a new organization to ROR:  Max Planck Institute for Neurobiology of Behavior – caesar

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#568]
Summary of request: Add a new organization to ROR

Name of organization: Max Planck Institute for Neurobiology of Behavior – caesar
Website: https://mpinb.mpg.de/
Link to publications: https://www.biorxiv.org/content/10.1101/2022.02.03.478949v1 ; there are no publications yet which use the new institute affiliation
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: https://de.wikipedia.org/wiki/Max-Planck-Institut_f%C3%BCr_Neurobiologie_des_Verhaltens_-_caesar
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID: 
Aliases: Max-Planck-Institut für Neurobiologie des Verhaltens – caesar*German
Labels:
Acronym/abbreviation: MPINB
Related organizations: Max Planck Society: https://ror.org/01hhn8329 (parent)
City: Bonn
Country: Germany
Geonames ID: 2946447
Year established: 2022
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility

Other information about this request: This new institute is a follow institution (same location) to Stiftung caesar =  https://ror.org/05350h943 in ROR, but the legal organization and structure changed completely, so I guess a new entry should be done ; I know that there are a lot of other identifiers and links (wikipedia) which should be either updated or a a complete new entry should be created. It would be great if you could give us a recommendation which variant would fulfill the aims best. Thanks!

**Comment by adambuttrick** [comment]
The Center of Advanced European Studies and Research has been dissolved and reconstituted as a new legal entity. As the prior org was in scope, I see no reason why this should not be, despite it being relatively young and the lack of affiliation usage. Will create separate request for the deprecation/redirect.

**Comment by adambuttrick** [comment]
@arthurpsmith Any comments on best practices for Wikidata and ISNI IDs in this instance? Should they obtain new? The Wikidata entry for the old org lists the current org's Wikipedia URL, which I expect is not best practice.

**Comment by arthurpsmith** [comment]
I see. Yes, I think in these cases it's safest to create a new ID - for ROR and ISNI and Wikidata should do so also. Presumably it hasn't happened there yet because the change was made only in the German language Wikipedia, and they just moved the article to a new name rather than creating a new one.

Have you come to any conclusions on what to do about redirects etc. on the ROR side for a case like this?

**Comment by adambuttrick** [comment]
@arthurpsmith Thank you for this! We still have to build the ability to redirect before we can make any policy decisions around them. I believe that is scheduled for this year, but not sure where it will fit in just yet. We will be discussing with the curation team once the application logic has been sorted out.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02yjyfs84 in release v1.1.
