### ISSUE TITLE
Add a new organization to ROR: Bureau of Justice Statistics

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#57]
Summary of request: Add a new organization to ROR

Name of organization: Bureau of Justice Statistics
Website: https://www.bjs.gov/
Link to publications: Produces statistics on  crime, criminal offenders, victims of crime, and the operation of justice systems at all levels of government.
Wikipedia page: https://en.wikipedia.org/wiki/Bureau_of_Justice_Statistics
Wikidata ID: Q3791513
ISNI ID: 0000 0004 7754 4970
GRID ID: 
Crossref Funder ID: doi.org/10.13039/100013173
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: BJS
Related organizations: https://ror.org/02916qm60 (parent)
City: Washington, DC
Country: USA
Other information about this request: This is a major US statistical agency that seem to be missing from your registry

**Comment by mariagould** [comment]
Relationships:

https://ror.org/02916qm60, parent

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0006s4z66 in release v1.0.
