### ISSUE TITLE
Modify the information in an existing ROR record: https://ror.org/00cqv5s75 - the URL redirects to offensive content

### ISSUE THREAD

**Issue by icraig-afk** [ror-community/ror-updates#576]
Summary of request: Modify the information in an existing ROR record

Name of organization: Sri Venkateswara Medical College and Ruia Hospital
ROR ID: https://ror.org/00cqv5s75
Which part of the record needs to be changed? The URL redirects to offensive content
Description of change: Supress URL

Update: replace.links==https://svmctpt.edu.in/;$

**Comment by adambuttrick** [comment]
Verified report. Updating to new link found via Wikidata.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
