### ISSUE TITLE
Add a new organization to ROR: Virginia Tech Transportation Institute

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#5771]
Summary of request: Add a new organization to ROR

Name of organization: Virginia Tech Transportation Institute
Website: https://www.vtti.vt.edu
Link to publications: https://www.vtti.vt.edu/research/publications.php
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0001 2226 3571 
GRID ID:
Crossref Funder ID: 100019835
Other names for the organization: 
Aliases: Center for Transportation Research
Labels:
Acronym/abbreviation: VTTI
Related organizations: https://ror.org/02smfhw86 (parent) https://ror.org/04n8zmx34 (related)
City: Blacksburg
Country: United States
Geonames ID: 4747845
Year established: 1988
How will a ROR ID for this organization be used? To enable tracking of institute researcher outputs in ROR-enabled systems
Other information about this request:

**Comment by adambuttrick** [comment]
Research facility in the United States. Would generally be out of scope by virtue of being a single-parent university research institute, but works closely with https://ror.org/04n8zmx34 (which I've added as related) on state and federal-level transportation initiatives. So this is fine to add.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05953j253 in release v1.34.
