### ISSUE TITLE
Modify the information in an existing ROR record: 
Masaryk Institute and Archive of the Czech Academy of Sciences https://ror.org/03nvfe914


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#578]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Masaryk Institute and Archive of the Czech Academy of Sciences
ROR ID: https://ror.org/03nvfe914
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: Change primary name: Masaryk Institute and Archive of the Czech Academy of Sciences. Change name versions: Masarykův ústav a Archiv AV ČR, MÚA AV ČR, MIA CAS. See https://www.mua.cas.cz/en

Update: change.name==Masaryk Institute and Archives of the Czech Academy of Sciences; delete.acronyms==MIA; add.acronyms==MIA CAS; add.acronyms==MÚA AV ČR; delete.aliases==Masarykův Ústav a Archiv AV ČR; add.labels==Masarykův ústav a Archiv AV ČR*Czech; replace.links==https://www.mua.cas.cz/;$

**Comment by adambuttrick** [comment]
Name changes correspond to website branding and are consistent with other Czech Academy of Sciences records.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
