### ISSUE TITLE
Merge records: https://ror.org/042pgcv68 and https://ror.org/02drdmm93

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#5783]
Summary of request: Merge records

Name of organization: China Academy of Chinese Medical Sciences; Chinese Academy of Medical Sciences & Peking Union Medical College
ROR ID: https://ror.org/042pgcv68; https://ror.org/02drdmm93
Description of change: I suspect that https://ror.org/042pgcv68 (China Academy of Chinese Medical Sciences) may have been created in error by GRID, or reflects a prior historical entity. Chinese Academy of Medical Sciences & Peking Union Medical College merged in 1957 and have been operating as a single entity since then, which is reflected in ROR as https://ror.org/02drdmm93. Unless I am overlooking something significant, I cannot find evidence or active usage of the name China Academy of Chinese Medical Sciences, except in the Funder Registry (501100005892) and in some publications that I believe may be using GRID for affiliation metadata. My recommendation would be to mark https://ror.org/042pgcv68 as inactive or withdrawn.

**Comment by adambuttrick** [comment]
I believe these are actually discrete organizations, one focused on traditional Chinese medicine and the other a state medical research body. This is perhaps more evident in the Chinese labels, where https://ror.org/02drdmm93 uses the characters for the study of medicine (医学科), which differ from that for traditional Chinese medicine (中医科), used on https://ror.org/042pgcv68. See also the Baidu Wiki entry [here](https://baike.baidu.com/item/%E4%B8%AD%E5%9B%BD%E4%B8%AD%E5%8C%BB%E7%A7%91%E5%AD%A6%E9%99%A2/913458), where the details and chronology do not correspond with that for the Chinese Academy of Medical Sciences & Peking Union Medical College.
