### ISSUE TITLE
Split an existing ROR record into two or more records: 
 
Okinawa Institute of Science and Technology Graduate Universityhttps://ror.org/02qg15b79

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#579]
Summary of request: Split an existing ROR record into two or more records

Merge/split/deprecate records:
Organizations affected by this change: Okinawa Institute of Science and Technology Graduate University
ROR ID(s) of organization(s) affected by this change: https://ror.org/02qg15b79
How should the record(s) be changed? From 2005 to 2011, the name of this organization was "Okinawa Institute of Science and Technology Promotion Corporation". In 2011, this organization was reformed to become the current "Okinawa Institute of Science and Technology Graduate University."

**Comment by adambuttrick** [comment]
According to the Japanese wikipedia entry, the Okinawa Institute of Science and Technology Promotion Corporation was created to further the establishment of the organization before it was a fully constituted university. I can reach out to the user about the use case, but generally speaking, I don't think we would create a ROR ID for a now defunct organization.

**Comment by adambuttrick** [comment]
Out of scope as we would not create a record for a defunct organization, nor one uninvolved with producing research outputs at that time in its existence.
