### ISSUE TITLE
Add a new organization to ROR: IPR MEDIA

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#58]
Summary of request: Add a new organization to ROR

Name of organization: IPR MEDIA LLC
Website: http://www.iprbookshop.ru/

Link to publications: 
https://doi.org/10.23682/98494 
https://doi.org/10.23682/98498 
https://doi.org/10.23682/98502  
https://doi.org/10.23682/94212  
https://doi.org/10.23682/93562 

Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: Saratov
Country: Russia
Other information about this request:

**Comment by carlyrobinson** [comment]
I agree with @arthurpsmith assessment. It was difficult to find information about the organization and what I could translate didn't provide much insight. Would be helpful if they provided more information about why a ROR ID would be helpful.
