### ISSUE TITLE
Add a new organization to ROR: 
 
Centro Ricerche Musicali

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#581]
Summary of request: Add a new organization to ROR

Name of organization: Centro Ricerche Musicali
Website: http://www.crm-music.it
Link to publications: http://dx.doi.org/10.1162/comj_a_00570 http://hdl.handle.net/10773/14893 http://dx.doi.org/10.1201/9781315216751
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels:
Acronym/abbreviation: CRM
Related organizations: 
City: Rome
Country: Italy
Geonames ID: 3169070
Year established: 1988
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request: CRM promotes musical research in its aesthetic, analytical, musicological and scientific aspects. In 1990, CRM was officially recognized by the Ministry of University and Scientific and Technological Research as a 'Research Center in the Music sector'

**Comment by adambuttrick** [comment]
Google Scholar affiliation usage: https://scholar.google.com/citations?user=beg9utQAAAAJ
ORCID affiliation usage: https://orcid.org/0000-0001-6993-2445 ; https://orcid.org/0000-0002-3671-9020 ; https://orcid.org/0000-0001-7953-9508

**Comment by arthurpsmith** [comment]
Seems a bit of an idiosyncratic entity, there's a rather comprehensive review of their activities here: https://muse.jhu.edu/article/801771 - but yes I think this is fine to include in ROR.
