### ISSUE TITLE
Modify the information in an existing ROR record:  St. Joseph Mercy Hospital - https://ror.org/01g0b5g28

### ISSUE THREAD

**Issue by DennisBirkholz** [ror-community/ror-updates#5825]
Summary of request: Modify the information in an existing ROR record

Name of organization:  St. Joseph Mercy Hospital
ROR ID: https://ror.org/01g0b5g28
Which part of the record needs to be changed: aliases/acronyms
Description of change:
"St. Joseph Mercy Oakland Hospital" should be an alias, not an acronym

**Comment by adambuttrick** [comment]
Transposition error is correctly identified. Hospital has been merged into the Trinity Health network and changed its name and site as described [here](https://www.trinityhealthmichigan.org/location/trinity-health-oakland-hospital). Updating accordingly.

**Comment by adambuttrick** [comment]
Updated in release v1.34.
