### ISSUE TITLE
Add a new organization to ROR: 
 
AL-IHYA ISLAMIC UNIVERSITY, KUNINGAN, INDONESIA

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#583]
Summary of request: Add a new organization to ROR

Name of organization: Al-Ihya Islamic University of Kuningan
Website: https://unisa.ac.id
Link to publications: https://www.scopus.com/record/display.uri?eid=2-s2.0-85087545013&origin=resultslist&sort=plf-f&src=s&st1=universitas+islam+al-ihya+kuningan&sid=a9b8a7f3d12d0fd7d7d7fa68857608ce&sot=b&sdt=b&sl=41&s=AFFIL%28universitas+islam+al-ihya+kuningan%29&relpos=0&citeCnt=0&searchTerm=&featureToggles=FEATURE_NEW_DOC_DETAILS_EXPORT:1
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: Q109913522
ISNI ID:
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels: Universitas Islam Al-Ihya Kuningan*Indonesian
Acronym/abbreviation: UNISA
Related organizations: 
City: KUNINGAN
Country: INDONESIA
Geonames ID: 1639093
Year established: 2014
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders

Other information about this request:

**Comment by adambuttrick** [comment]
Indonesian university with solid publication affiliation usage. Independent, top-level entity. Should be added to ROR.

Google Scholar Affiliation Usage: https://scholar.google.com/citations?user=OcuFC0MAAAAJ; https://scholar.google.com/citations?user=umY13bUAAAAJ; https://scholar.google.com/citations?user=BeOgdBYAAAAJ
ORCID affiliation usage: https://orcid.org/0000-0001-5339-1445 ; https://orcid.org/0000-0003-2437-6048 ; https://orcid.org/0000-0001-5968-357X

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05914mm11 in release v1.0.
