### ISSUE TITLE
Modify the information in an existing ROR record: Leibniz Institute for Applied Geophysics

### ISSUE THREAD

**Issue by nuest** [ror-community/ror-updates#5833]
Summary of request: Modify the information in an existing ROR record and add the Wikidata ID

Name of organization: Leibniz Institute for Applied Geophysics
ROR ID: https://ror.org/05txczf44
Which part of the record needs to be changed? Wikidata
Description of change:

The Wikidata ID is missing, it is https://www.wikidata.org/wiki/Q1813721

Update: add.Wikidata==Q1813721;$

**Comment by adambuttrick** [comment]
Wikidata ID is that for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.35.
