### ISSUE TITLE
Modify the information in an existing ROR record:  Leibniz Institute of Ecological Urban and Regional Development

### ISSUE THREAD

**Issue by nuest** [ror-community/ror-updates#5835]
Summary of request: Modify the information in an existing ROR record

Name of organization: Leibniz Institute of Ecological Urban and Regional Development
ROR ID: https://ror.org/02t26g637
Which part of the record needs to be changed?
Description of change: Add the missing Wikidata ID `Q1813774`, see https://www.wikidata.org/wiki/Q1813774

Update: add.Wikidata==Q1813774; replace.links==https://www.ioer.de;$

**Comment by adambuttrick** [comment]
Wikidata ID provided is that for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.35.
