### ISSUE TITLE
Modify the information in an existing ROR record:  Leibniz Institute of Freshwater Ecology and Inland Fisheries

### ISSUE THREAD

**Issue by nuest** [ror-community/ror-updates#5837]
Summary of request: Modify the information in an existing ROR record

Name of organization: Leibniz Institute of Freshwater Ecology and Inland Fisheries
ROR ID: https://ror.org/01nftxb06
Which part of the record needs to be changed?
Description of change: Add missing Wikidata ID https://www.wikidata.org/wiki/Q1813732

Update: add.Wikidata==Q1813732; replace.links==https://www.igb-berlin.de;$

**Comment by adambuttrick** [comment]
Wikidata ID provided is that for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.35.
