### ISSUE TITLE
Modify the information in an existing ROR record: Bavarian State Archives

### ISSUE THREAD

**Issue by nuest** [ror-community/ror-updates#5839]
Summary of request: Modify the information in an existing ROR record

Name of organization: Bavarian State Archives
ROR ID: https://ror.org/01hq2jk95
Which part of the record needs to be changed?
Description of change: Add missing Wikidata ID https://www.wikidata.org/wiki/Q2324301

Update: add.Wikidata==Q2324301; replace.links==https://www.gda.bayern.de;$

**Comment by adambuttrick** [comment]
Wikidata ID provided is that for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.35.
