### ISSUE TITLE
Modify the information in an existing ROR record: Bochum University of Applied Sciences

### ISSUE THREAD

**Issue by nuest** [ror-community/ror-updates#5840]
Summary of request: Modify the information in an existing ROR record

Name of organization: Bochum University of Applied Sciences
ROR ID: https://ror.org/04x02q560
Which part of the record needs to be changed?
Description of change: Add missing Wikidata ID https://www.wikidata.org/wiki/Q1622078

Update: add.Wikidata==Q1622078; replace.links==https://www.hochschule-bochum.de;$

**Comment by adambuttrick** [comment]
Wikidata ID provided is that for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.35.
