### ISSUE TITLE
Modify the information in an existing ROR record: 
University of Derby  https://ror.org/02yhrrk59


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#585]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: University of Derby
ROR ID:  https://ror.org/02yhrrk59
Which part of the record needs to be changed? Something else
Description of change: Information on Institutional Repository

**Comment by adambuttrick** [comment]
Intent of request is unclear. Reaching out to requester.

**Comment by adambuttrick** [comment]
No response from requestor.
