### ISSUE TITLE
Add a new organization to ROR: 
 
DataKind

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#586]
Summary of request: Add a new organization to ROR

Name of organization: DataKind
Website: https://www.datakind.org
Link to publications: https://chance.amstat.org/2021/09/pathways/
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: 
Wikidata ID: Q97135421
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels:
Acronym/abbreviation:
Related organizations:
City: Global, but headquartered in Brooklyn, NY
Country: United States
Geonames ID: 5110302
Year established: 2012
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility

Other information about this request:

**Comment by adambuttrick** [comment]
Non-profit that connects data scientists with social change organizations to leverage the former's skills in pursuit of the organizations goals. Limited publication affiliation usage, but their projects page (https://www.datakind.org/projects) documents extensive collaboration with established organizations. Quite similar to https://ror.org/02hdt9m26, so I believe they should be added to ROR.

Google Scholar affiliation usage: https://scholar.google.com/citations?user=Glueh8AAAAAJ
ORCID affiliation usage: https://orcid.org/0000-0001-7980-4658

**Comment by arthurpsmith** [comment]
Seems fine to me also. There is a Wikidata ID for them, which I added.
