### ISSUE TITLE
Modify the information in an existing ROR record: Dutch Research Council https://ror.org/04jsz6e67

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#5863]
Summary of request: Modify the information in an existing ROR record

Name of organization: Dutch Research Council
ROR ID: https://ror.org/04jsz6e67 
Which part of the record needs to be changed? aliases
Description of change: Add additional aliases from Open Funder Registry: Dutch Research Council, Netherlands; Dutch National Scientific Foundation; Dutch National Science Foundation

See also https://twitter.com/hldejonge/status/1712895263256306040?s=61&t=E3--3h7JhOIQVTL7SbSJUA 

Update: add.aliases==Dutch National Scientific Foundation; add.aliases==Dutch National Science Foundation;$

**Comment by adambuttrick** [comment]
We would not add “Dutch Research Council, Netherlands” as an alias as the country is already in our record metadata and thus accessible in our matching. The other two aliases are fine to add.

**Comment by adambuttrick** [comment]
Record updated in release v1.35.
