### ISSUE TITLE
Modify the information in an existing ROR record: 
Philipp University of Marburg https://ror.org/01rdrb571


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#587]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Philipp University of Marburg
ROR ID: https://ror.org/01rdrb571
Which part of the record needs to be changed? Primary name
Description of change: Philipps University of Marburg' or 'Philipps-Universität Marburg' => https://www.uni-marburg.de

Update: replace.links==https://www.uni-marburg.de/; change.name==Philipps University of Marburg;$

**Comment by adambuttrick** [comment]
Change corresponds to copyright statement and branding on organization's website. Updating link to strip out English-language page reference.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
