### ISSUE TITLE
Add a new organization to ROR: 
 
Instituto Politécnico da Lunda Sul

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#588]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Instituto Politécnico da Lunda Sul
Website: https://www.ipls.ao
Link to publications: https://revistas.ipls.ao
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels: Polytechnic Institute of Lunda Sul*English
Acronym/abbreviation: IPLS
Related organizations: Universidade Lueji A'nkonde
City: Saurimo
Country: Angola
Geonames ID: 145531
Year established: 2003
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
ORCID affiliation usage: https://orcid.org/0000-0001-8493-0392 ; https://orcid.org/0000-0002-6209-4319

**Comment by arthurpsmith** [comment]
Yes definitely we should have an entry for Universidade Lueji A'Nkonde. 

From the "about" page here: https://www.ipls.ao/?page_id=835 (if I'm reading the Google translation correctly) it appears this institute was originally created and "attached" to a different university - "Universidade Agostinho Neto" - https://ror.org/0057ag334 - so I think given that it has had in some sense two parents (?) it qualifies as sufficiently independent to be listed separately. Also some of the affiliation usage does not mention the Lueji A'Nkonde connection, and the website differs. So yes I think both that university and this institute should have ROR ids.
