### ISSUE TITLE
Add a new organization to ROR: Lexical Computing

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#59]
Summary of request: Add a new organization to ROR

Name of organization: Lexical Computing

Website: https://www.lexicalcomputing.com
Link to publications: See articles written by key personnel:
https://scholar.google.com/citations?user=O6_44PwAAAAJ
https://scholar.google.com/citations?user=mF_yu7wAAAAJ
https://scholar.google.com/citations?user=AQJK5pMAAAAJ
https://scholar.google.com/citations?user=P1R68loAAAAJ

Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/Q45025716
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: https://ror.org/issue448 (child)
City: Brighton
Country: United Kingdom
Geonames ID: 2654710
Other information about this request: Lexical Computing is small research company founded in 2003 by a UK university professor Adam Kilgarriff. Over the almost 20 years, it has been carrying out research and development in the area of computer lexicography, corpus linguistics and natural language processing.

Represents UK branch

**Comment by carlyrobinson** [comment]
Agree, should be added to ROR. Isn't Lexical Computing Limited the parent (in the UK), with Lexical Computing CZ as a child (if needed)?

**Comment by mariagould** [comment]
Decision: Create two records with UK entity as parent

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05jj7mn84 in release v1.0.
