### ISSUE TITLE
Modify the information in an existing ROR record: 
University of Sopron https://ror.org/05nj7my03


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#592]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: University of Sopron
ROR ID: https://ror.org/05nj7my03
Which part of the record needs to be changed? Organization website
Description of change: University of Sopron has a new international website and would like to ask you to update it as follows: http://international.uni-sopron.hu/home
Update: replace.links==http://international.uni-sopron.hu/home;$

**Comment by adambuttrick** [comment]
While the old site still exists, this is org requested and the new link is now the top Google hit for the University of Sopron.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
