### ISSUE TITLE
Add a new organization to ROR: 
 
Knowledge Motifs LLC

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#594]
Summary of request: Add a new organization to ROR

Name of organization: Knowledge Motifs
Website: http://kmotifs.com
Link to publications: https://doi.org/10.1016/j.patter.2021.100324; https://doi.org/10.1162/dint_a_00036; https://doi.org/10.5334/dsj-2019-058; https://doi.org/10.5281/zenodo.1451996; 
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: KMotifs
Labels:
Acronym/abbreviation:
Related organizations: 
City: San Mateo
Country: United States
Geonames ID: 5392423
Year established: 2009
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders

Other information about this request:

**Comment by adambuttrick** [comment]
Data consultancy for libraries and digital archives. While their site lists two principals, I can only find publication affiliation usage for one (Nancy Hoebelheinrich). While publication history is solid, it appears a one-person organization in terms of its research outputs and thus would be out of scope.

**Comment by arthurpsmith** [comment]
I did find one reference to Jerry Persons with this affiliation as a conference speaker, but otherwise it does seem to be exclusively used by Hoebelheinrich. Could perhaps be considered later if the company grows and there's more research output but for now I agree this seems out of scope for ROR.
