### ISSUE TITLE
Modify the information in an existing ROR record: Ministry of Science, Technology and Productive Innovation https://ror.org/02h503d38

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#5993]
Summary of request: Modify the information in an existing ROR record

Name of organization: Ministry of Science, Technology and Productive Innovation
ROR ID: https://ror.org/02h503d38
Which part of the record needs to be changed? Name, Acronym, Website, Wikipedia URL
Description of change: The word "productive" has been removed from the name of this agency. The current website is https://www.argentina.gob.ar/ciencia In Spanish the name of the agency is Ministerio de Ciencia, Tecnología e Innovación and the acronym MINCYT is often used. The Wikipedia page is https://en.wikipedia.org/wiki/Ministry_of_Science,_Technology_and_Innovation_(Argentina) 

Update: change.name==Ministerio de Ciencia, Tecnología e Innovación; add.aliases==Ministry of Science, Technology and Productive Innovation; add.aliases==Ministerio de Ciencia Tecnología e Innovación Productiva; add.aliases==Ministry of Science, Technology and Innovation; delete.labels==Ministerio de Ciencia Tecnología e Innovación Productiva; add.acronyms==MINCYT; add.Wikidata==Q6017195; change.wikipedia_url==https://es.wikipedia.org/wiki/Ministerio_de_Ciencia,_Tecnología_e_Innovación_(Argentina); replace.links==https://www.argentina.gob.ar/ciencia;$

**Comment by adambuttrick** [comment]
Name change corresponds to organization's site and branding.

**Comment by adambuttrick** [comment]
Record updated in release v1.35.
