### ISSUE TITLE
Batch QA: Malformed ISNI

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#6]
[ROR_table_ISNI_format_fixes.xlsx](https://github.com/ror-community/test-curation-workflow/files/5682292/ROR_table_ISNI_format_fixes.xlsx)

**Comment by adambuttrick** [comment]
Updated corrections/metadata for malformed ISNIs.

[20220808_isni_fixes.xlsx](https://github.com/ror-community/ror-updates/files/9293179/20220808_isni_fixes.xlsx)

**Comment by adambuttrick** [comment]
All records updated in release v1.4.
