### ISSUE TITLE
Modify the information in an existing ROR record: Lisbon University Institute (https://ror.org/014837179)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#60]
Summary of request: Modify the information in an existing ROR record

Name of organization: Lisbon University Institute
ROR ID: https://ror.org/014837179
Which part of the record needs to be changed? Name, alias

Description of change: 
Official designation: Iscte - Instituto Universitário de Lisboa
Short name: Iscte
The official name is in Portuguese, and it is: Iscte-Instituto Universitário de Lisboa
I suggest to change the primary name to: Iscte-Instituto Universitário de Lisboa
Please change at least the big title according the official name. Include in the list the short name as well. Thank you.

Update: change.name==University Institute of Lisbon; add.aliases== Iscte; delete.labels==Instituto Universitário de Lisboa; add.labels==Iscte-Instituto Universitário de Lisboa*Portuguese; delete.labels==Higher Institute of Business and Labour Sciences; add.labels==Iscte-University Institute of Lisbon*English;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
