### ISSUE TITLE
Add a new organization to ROR: 
 
Quantitative Genomics Medicine Laboratories (qGenomics)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#601]
Summary of request: Add a new organization to ROR

Name of organization: Quantitative Genomics Medicine Laboratories (qGenomics)
Website: https://qgenomics.com
Link to publications: doi: 10.1093/hmg/ddac073; doi: 10.7554/eLife.65310; doi: 10.1093/nar/gkac076; doi: 10.1002/humu.24278
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: qGenomics
Labels:
Acronym/abbreviation:
Related organizations: Center for Genomics Regulation https://ror.org/03wyzt892 (related)  Pompeu Fabra University https://ror.org/04n0g0b29 (related)
City: Esplugues de Llobregat, Barcelona
Country: Spain
Geonames ID: 3122826
Year established: 2008
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request: qGenomics was founded on the principles of excellence in service and research that govern the institutions that watched us hatch (CRG y UPF). For this reason, we consider basic and applied research fundamental pieces of our daily work, and we are committed to continue being a leading provider of genomic tools for clinical use

**Comment by adambuttrick** [comment]
Conducts genomic research and provides clinical services in the same domain. Independent, top-level entity. Solid publication history and affiliation usage. Should be added to ROR.

Google Scholar affiliation usage: https://scholar.google.com/citations?user=QZAAHYkAAAAJ; https://scholar.google.com/citations?user=HsZrogcAAAAJ; https://scholar.google.com/citations?user=OcKhRjQAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0002-6103-9852 ; https://orcid.org/0000-0002-8601-706X ; https://orcid.org/0000-0002-6844-974X
