### ISSUE TITLE
Modify the information in an existing ROR record: 
University of Natural Resources and Life Sciences https://ror.org/057ff4y42


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#602]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: University of Natural Resources and Life Sciences
ROR ID: https://ror.org/057ff4y42
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: lease change the offical University names in english and german to
"University of Natural Resources and Life Sciences, Vienna" and "Universität für Bodenkultur Wien" and the official abbreviation BOKU. See more information in our "Affiliation Policy"
https://boku.ac.at/fileadmin/data/H01000/mitteilungsblatt/MB_2020_21/MB27/RLAffiliation-Ver1-0eng.pdf

Update: change.name==University of Natural Resources and Life Sciences, Vienna; delete.aliases==Hochschule für Bodenkultur;$

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
