### ISSUE TITLE
Add a new organization to ROR: Queensland Climate Change Centre of Excellence

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#6021]
Summary of request: Add a new organization to ROR

Name of organization: Queensland Climate Change Centre of Excellence
Website: https://www.climatechange.qld.gov.au
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: Queensland Climate Change Centre for Excellence
Labels: 
Acronym/abbreviation: QCCCE
Related organizations: 
City: Brisbane
Country: Australia
Geonames ID: 2174003
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: Follows from #5998

**Comment by adambuttrick** [comment]
Inactive research facility with extensive affiliation usage and publication history. Can be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01sxj8p89 in release v1.35.

**Comment by durack1** [comment]
@adambuttrick thanks for adding this. Did you guys intend to mark institutions/entries that are no longer operating? This is a little difficult to ascertain in some instances, but in others it's easy.

**Comment by adambuttrick** [comment]
@durack1 Yes, we add new inactive organizations where there are demonstrated research outputs and a stated need by an integrator. These records have the status inactive vs. active for all other new records.

**Comment by durack1** [comment]
@adambuttrick nice, ok, I hadn't clicked the link and noted the "inactive" tag, this makes complete sense - thanks
