### ISSUE TITLE
Add a new organization to ROR: 
 
St. Petersburg Research Center of the Russian Academy of Sciences

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#603]
Summary of request: Add a new organization to ROR

Name of organization: St. Petersburg Research Center of the Russian Academy of Sciences
Website: http://www.spbrc.nw.ru
Link to publications: 10.7868/S2073667321040109
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3%D1%81%D0%BA%D0%B8%D0%B9_%D0%BD%D0%B0%D1%83%D1%87%D0%BD%D1%8B%D0%B9_%D1%86%D0%B5%D0%BD%D1%82%D1%80_%D0%A0%D0%90%D0%9D 
Wikidata ID: Q4407733
ISNI ID: 0000 0001 2225 2258
GRID ID: 
Crossref Funder ID: 
Aliases: St. Petersburg Research Center RAS
Labels: Санкт-Петербургский научный центр РАН*Russian
Acronym/abbreviation: SPbRC RAS
Related organizations: https://ror.org/05qrfxd25 (parent)
City: Saint Petersburg
Country: Россия
Geonames ID: 498817
Year established: 1983
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Long-standing Russian Academy of Sciences research center. Other RAS organizations are already included in ROR (e.g. https://ror.org/04ef8pm25 ; https://ror.org/02bc50c05), so they're clearly in scope.

**Comment by arthurpsmith** [comment]
Surprised we don't already have this. Yes it should be in ROR. I added the ISNI link in the metadata section.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0028hwj42 in release v1.1.
