### ISSUE TITLE
Add a new organization to ROR: 
 
Inuvialuit Regional Corporation

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#604]
Summary of request: Add a new organization to ROR

Name of organization: Inuvialuit Regional Corporation
Website: https://irc.inuvialuit.com
Link to publications: https://irc.inuvialuit.com/sites/default/files/HFT_carbon_report.pdf
Organization type: Other (Use this category for any organization that does not fit the categories above)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 0000 0004 5930 1414
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels:
Acronym/abbreviation: IRC
Related organizations: https://ror.org/05k87xn20 (related)
City: Inuvik
Country: Canada
Geonames ID: 5983607
Year established: 1986
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders

Other information about this request:

**Comment by adambuttrick** [comment]
Entity established to represents the collective interests of the Inuvialuit. Independent, top-level entity with solid-publication affiliation usage. Should be added to ROR.

Publication affiliation usage: https://www.osti.gov/etdeweb/biblio/20141998 ; https://www.osti.gov/etdeweb/biblio/20818672 ; 
Google Scholar affiliation usage: https://scholar.google.com/citations?user=9qU9b2gAAAAJ

**Comment by arthurpsmith** [comment]
Looks good to me. I added the ISNI identifier.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0549rra43 in release v1.1.
