### ISSUE TITLE
Modify the information in an existing ROR record: 
Institute of Information Technologies and Learning Tools of the NAES of Ukraine https://ror.org/02qqjk369


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#606]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Institute of Information Technologies and Learning Tools of the NAES of Ukraine
ROR ID: https://ror.org/02qqjk369
Which part of the record needs to be changed? Primary name
Description of change: Dear Editorial team! Would you be so kind to make changes in the profile https://ror.org/02qqjk369.  Our "Institute of Information Technologies and Learning Tools of the NAES of Ukraine" was renamed to "Institute for Digitalisation of Education of the NAES of Ukraine". See press release here: https://iitlt.gov.ua/eng/info/news/naradi/renaming-of-the-institute-of-informational-technologies-and-learning-tools-of-naes-of-ukraine/
Update: change.name==Institute for Digitalisation of Education of the NAES of Ukraine; replace.aliases==IDE NAES of Ukraine; replace.labels==Інститут цифровізації освіти НАПН України*Ukrainian;$

**Comment by adambuttrick** [comment]
Name change corresponds to branding, copyright, and statement on the organization's site.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
