### ISSUE TITLE
Modify the information in an existing ROR record: 
University of Auckland https://ror.org/03b94tp07


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#610]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: University of Auckland
ROR ID: https://ror.org/03b94tp07
Which part of the record needs to be changed? Something else
Description of change: The acronym for the University of Auckland should be: UoA
Update: add.acronyms==UoA;$

**Comment by adambuttrick** [comment]
Org-requested, so approving.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
