### ISSUE TITLE
Modify the information in an existing ROR record: 
Kryvyi Rih State Pedagogical University https://ror.org/01wx1q736


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#611]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Kryvyi Rih State Pedagogical University
ROR ID: https://ror.org/01wx1q736
Which part of the record needs to be changed? Primary name
Description of change: "Krivoy Rog State Pedagogical Institute" is an outdated name of Kryvyi Rih State Pedagogical University which used before 2000 (see https://kdpu.edu.ua/en/university/history-of-kspu.html for details). Moreover, "Krivoy Rog" is the Russian transliteration of the Kryvyi Rih city (see https://en.wikipedia.org/wiki/Kryvyi_Rih) which we don't use a lot of time. Kryvyi Rih State Pedagogical University is the only official name for our institution (https://en.wikipedia.org/wiki/Kryvyi_Rih_State_Pedagogical_University).

Update: change.name==Kryvyi Rih State Pedagogical University;$

**Comment by adambuttrick** [comment]
Name change corresponds to organization website and is the form used in Wikidata.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
