### ISSUE TITLE
Modify the information in an existing ROR record: Aichi Kidney Foundation https://ror.org/05a86es26

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#6117]
Summary of request: Modify the information in an existing ROR record

Name of organization: Aichi Kidney Foundation
ROR ID: https://ror.org/05a86es26
Which part of the record needs to be changed? Website 
Description of change: Current website link is a Google Translate link. Correct website appears to be https://www.ai-jinzou.or.jp/ 

Update: replace.labels==愛知腎臓財団*Japanese; add.aliases==公益財団法人愛知腎臓財団; add.aliases==愛知県腎臓創建; add.aliases==Aichi Jinzou Zaidan; add.aliases==あいちじんぞうかいだん; add.aliases==アイチジンゾウカイダン; replace.links==https://www.ai-jinzou.or.jp;$

**Comment by adambuttrick** [comment]
Link provided is that for the organization. Correcting Japanese label and adding aliases.

**Comment by adambuttrick** [comment]
Record updated in release v1.36.
