### ISSUE TITLE
Add a new organization to ROR: 
 
International Water Association Publishing

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#612]
Summary of request: Add a new organization to ROR

Name of organization: International Water Association Publishing
Website: https://www.iwapublishing.com
Link to publications: 10.2166/aqua. 10.2166/bgs. 10.2166/h2oj 10.2166/nh. 10.2166/hydro. 10.2166/wcc. 10.2166/wh. 10.2166/washdev. 10.2166/wp. 10.2166/wpt. 10.2166/wqrj. 10.2166/wrd. 10.2166/wst. 10.2166/ws.
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 0000 0004 0458 3514
GRID ID: 
Crossref Funder ID: 
Aliases: IWA Publishing
Labels:
Acronym/abbreviation: IWAP
Related organizations:  https://ror.org/027xkck76 (parent)
City: London
Country: United Kingdom
Geonames ID: 2643743
Year established: 1998
How will a ROR ID for this organization be used? Journal Comparison Service

Other information about this request:

**Comment by adambuttrick** [comment]
Publishing arm of https://ror.org/027xkck76. Publishes many open access journals and eBooks in this domain. In scope for ROR.

**Comment by arthurpsmith** [comment]
Ok, this seems to qualify on most counts though I don't see it used as an affiliation. Can be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/029kfxt47 in release v1.1.
