### ISSUE TITLE
Add a new organization to ROR: 
 
Leibniz Institute for Immunotherapy

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#615]
Summary of request: Add a new organization to ROR

Name of organization: Leibniz Institute for Immunotherapy
Website: https://www.rcii.de
Link to publications: https://www.science.org/doi/full/10.1126/sciadv.abh4050, https://www.nature.com/articles/s41467-021-21297-y
Organization type: Facility (A specialized facility where research takes place, such as a laboratory or telescope or dedicated research area)
Wikipedia page: https://de.wikipedia.org/wiki/Leibniz-Institut_f%C3%BCr_Immuntherapie
Wikidata ID: Q110516280
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: Regensburger Centrum für Interventionelle Immunologie
Labels: Leibniz-Institut für Immuntherapie*German
Acronym/abbreviation: LIT
Related organizations: https://ror.org/01n6r0e97 (parent) 
City: Regensburg
Country: Germany
Geonames ID: 2849483
Year established: 2022
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility

Other information about this request: The LIT is the former Regensburger Centrum for Interventional Immunotherapy (rcii) and became member of the Leibniz Association 01/01/2022

**Comment by adambuttrick** [comment]
Cancer treatment research facility spun off from the University of Regensburg. While the change in name and association is new, the former institute has long-standing publication affiliation usage. Other Leibniz Institute members are already included in ROR, so this is in scope.

Google scholar affiliation usage: https://scholar.google.com/citations?user=qL6ESpUAAAAJ; https://scholar.google.com/citations?user=eFJKGe4AAAAJ; https://scholar.google.com/citations?user=Eztmr40AAAAJ
ORCID affiliatio _usage: https://orcid.org/0000-0003-2239-3282

**Comment by MSpenger** [comment]
I agree with Adam. This new entry is in scope.
The Wikidata-ID can also be added to the entry: https://www.wikidata.org/wiki/Q110516280

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00xn1pr13 in release v1.1.
