### ISSUE TITLE
Modify the information in an existing ROR record: 
Institute for Foreign and International Criminal Law https://ror.org/04a8rd767


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#616]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Institute for Foreign and International Criminal Law
ROR ID: https://ror.org/04a8rd767
Which part of the record needs to be changed? Primary name
Description of change: New name for the MPI for Foreign and International Criminal Law since March 2020. The name of the institute has changed to "Max Planck Institute for the Study of Crime, Security and Law". 

Update: change.name==Max Planck Institute for the Study of Crime, Security and Law; replace.links==https://www.csl.mpg.de/;$

**Comment by adambuttrick** [comment]
Confirmed via organization's site. Updating link as well.
