### ISSUE TITLE
Add a new organization to ROR: World Glacier Monitoring Service (WGMS)

### ISSUE THREAD

**Issue by ezwelty** [ror-community/ror-updates#6161]
Summary of request: Add a new organization to ROR

Name of organization: World Glacier Monitoring Service
Website: https://wgms.ch
Link to publications: https://commons.datacite.org/doi.org?query=client.uid:ethz.wgms
Organization type: Other
Wikipedia page: https://en.wikipedia.org/wiki/World_Glacier_Monitoring_Service
Wikidata ID: Q656311
ISNI ID: 0000 0001 0942 1088
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels:
Acronym/abbreviation: WGMS
Related organizations: https://ror.org/02crff812 (related) https://ror.org/01jachm79 (related) https://ror.org/034s44556 (related) https://ror.org/015z29x25 (related) https://ror.org/04h4z8k05 (related) https://ror.org/011pjwf87 (related)
City: Zürich
Country: Switzerland
Geonames ID: 2657896
Year established: 1986
How will a ROR ID for this organization be used? Added to metadata records of DOIs published by the organization.
Other information about this request:

**Comment by adambuttrick** [comment]
Environmental monitoring organization in Switzerland. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01jtrvx49 in release v1.36.
