### ISSUE TITLE
Project: NCI-designated Cancer Centers

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#6174]
https://ror.org/05pyq8e17 has flagged that we have limited coverage of the [NCI-designated Cancer Centers](https://www.cancer.gov/research/infrastructure/cancer-centers/find). Existing records include:

- https://ror.org/05m5b8x20 - Sidney Kimmel Comprehensive Cancer Center
- https://ror.org/03qrhd488 - Edwards Comprehensive Cancer Center
- https://ror.org/0552r4b12 - Sylvester Comprehensive Cancer Center
- https://ror.org/05yndxy10 - UCSF Helen Diller Family Comprehensive Cancer Center
- https://ror.org/0512csj88 - Wake Forest Baptist Comprehensive Cancer Center

We should review all and complete this coverage, where in scope/appropriate.

**Comment by leonardcj** [comment]
Before tackling, ping me for status of the bulk submission I am working up (albeit slowly).  leonardcj

**Comment by adambuttrick** [comment]
@leonardcj Understood! We will wait for your submission to review.

**Comment by adambuttrick** [comment]
New and updated records provided by https://ror.org/05pyq8e17 are linked below:

https://docs.google.com/spreadsheets/d/1TB_Nqm1PovoE9V5VF0lXlIl8670aAHgYhsXFMpmsEq0/edit?usp=sharing

**Comment by adambuttrick** [comment]
All records added and updated in release v1.39.
