### ISSUE TITLE
Add a new organization to ROR: Open Citations

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#62]
Summary of request: Add a new organization to ROR

Name of organization to be added | OpenCitations

Organization website | http://opencitations.net/

Briefly explain why you are requesting a ROR ID for this organization and how the ROR ID will be used. | Scholarly infrastructures such as CDL, Crossref and DataCite all have RORs. Inspired by PIDapalooza 2021, and following these examples, I request a ROR for OpenCitations ("an independent infrastructure organization for open scholarship").
Provide DOI(s) or links for research associated with this organization, such as published articles that include the organization's name as an affiliation. If DOIs or links are not available, describe the research-related activities of this organization. | https://doi.org/10.1162/qss_a_00023

Other relevant metadata about the organization (e.g., name variants in other languages, related records in ROR, links to external records such as Wikidata) | https://en.wikipedia.org/wiki/OpenCitations, https://www.wikidata.org/wiki/Q29279836, https://www.wikidata.org/wiki/Q76434478

Summary of request: Add a new organization to ROR

--

**Curator Recommendation MC**

Name of organization: OpenCitations
Website: http://opencitations.net
Link to publications: Silvio Peroni, David Shotton (2020). OpenCitations, an infrastructure organization for open scholarship. Quantitative Science Studies, 1(1): 428-444. https://doi.org/10.1162/qss_a_00023
Wikipedia page: https://en.wikipedia.org/wiki/OpenCitations
Wikidata ID: https://www.wikidata.org/wiki/Q29279836
ISNI ID: Not found
GRID ID: Not found
Crossref Funder ID: Not found
Ringgold ID: Not found
Other names for the organization: None
Acronym/abbreviation: OC
Related organizations: None
City: Oxford (see comment below regarding city and country)
Country: United Kingdom

**Comment by mariagould** [comment]
This is related to the request in #63. Additional information from the requestor about the relationship between the two entities and the interest in having ROR IDs for both:

> OpenCitations is distinct from and pre-existed the Research Centre, having grown to become a valuable independent infrastructure from a small beginning as a research project in my lab.

The Research Centre was created specifically for two purposes: (a) to provide an institutional affiliation, a legal financial centre, and a formal administrative 'home' for OpenCitations, and (b) to permit academic activities affiliated with OpenCitations, such as being the academic home for graduate students of the University of Bologna working on projects involving open citations.  The Research Centre is formally a part of the University of Bologna in a way that OpenCitations is not.

In the medium-term future, OpenCitations may 'spin out' to become a non-profit foundation /association/Stiftung under direct governance by the wider academic community and other stakeholders, that is administratively and financially independent from the University of Bologna.  In that case, OpenCitations will continue with its stated mission of providing open bibliographic metadata and citations, and the Research Centre will continue as an integral part of the University of Bologna in its academic roles with respect to OpenCitations, and will probably by then also have expanded its activities to include other types of metadata-oriented research work, but it will no longer be administratively and financially responsible for OpenCitations.

**Comment by mariagould** [comment]
Determination via group discussion: This should be added to ROR so the ROR ID can be used to identify the initiative's contributions to scholarly infrastructure. This sets a precedent for similar initiatives that could be added to ROR in the future, such as VIVO and FORCE11.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00wb4mk85 in release v1.0.
