### ISSUE TITLE
Add a new organization to ROR: Polar Knowledge Canada

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#625]
Summary of request: Add a new organization to ROR

Name of organization: Polar Knowledge Canada
Website: https://www.canada.ca/en/polar-knowledge.html
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Polar_Knowledge_Canada
Wikidata ID: Q5030480
ISNI ID: 0000 0001 2106 4693
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: POLAIRE; POLAR
Related organizations: 
City: Ottawa, Ontario
Country: Canada
Geonames ID: 6094817
Year established: 1991
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Successor organization , as identified in #622.

**Comment by arthurpsmith** [comment]
The website in the metadata section goes to the old Canadian Polar Commission site. I assume we should use the new site but not sure what it should be (https://www.canada.ca/en/polar-knowledge.html ??)

Otherwise yes this makes sense to create as a new record, deprecating the old entry.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00rfash91 in release v1.1.
