### ISSUE TITLE
Add a new organization to ROR: Crown-Indigenous Relations and Northern Affairs Canada

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#626]
Summary of request: Add a new organization to ROR

Name of organization: Crown-Indigenous Relations and Northern Affairs Canada
Website: https://www.rcaanc-cirnac.gc.ca
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Crown%E2%80%93Indigenous_Relations_and_Northern_Affairs_Canada
Wikidata ID: Q86685295
ISNI ID: 0000 0004 8308 3517
GRID ID:
Crossref Funder ID: 501100014009
Other names for the organization: 
Acronym/abbreviation: CIRNAC
Labels: Relations Couronne-Autochtones et des Affaires du Nord Canada*French;
Related organizations: 
City: Gatineau, Quebec
Country: Canada
Geonames ID: 5959974
Year established: 2019
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Successor organization to Aboriginal Affairs Northern Dev Canada (https://ror.org/05pgxdd43), which ceased operation in 2017, as identified in #623. As the prior organization was in scope, this should be as well.

ORCID affiliation usage: https://orcid.org/0000-0002-0729-6890

**Comment by arthurpsmith** [comment]
Seems fine to me.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05xmf1h49 in release v1.0.
