### ISSUE TITLE
Add a new organization to ROR: Indigenous Services Canada

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#627]
Summary of request: Add a new organization to ROR

Name of organization: Indigenous Services Canada
Website: https://www.sac-isc.gc.ca
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Indigenous_Services_Canada
Wikidata ID: Q85846156
ISNI ID:
GRID ID:
Crossref Funder ID: 501100013971
Other names for the organization: 
Acronym/abbreviation: ISC
Labels: Services aux Autochtones Canada*French;
Related organizations: 
City: Gatineau, Quebec
Country: Canada
Geonames ID: 5959974
Year established: 2019
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Successor organization to Aboriginal Affairs Northern Dev Canada (https://ror.org/05pgxdd43), which ceased operation in 2017, as identified in https://github.com/ror-community/ror-updates/issues/623. As the prior organization was in scope, this should be as well.

Google scholar affiliation usage: https://scholar.google.com/citations?user=Czm-jrEAAAAJ; https://scholar.google.com/citations?user=HuX-vIMAAAAJ; https://scholar.google.com/citations?user=QsrbPOgAAAAJ
ORCID affiliation usage: https://orcid.org/0000-0002-5786-7209 ; https://orcid.org/0000-0001-8040-1004 ; https://orcid.org/0000-0002-0729-6890

**Comment by arthurpsmith** [comment]
Yup, this is fine too.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04babsy72 in release v1.1.
