### ISSUE TITLE
Modify the information in an existing ROR record: 
National Center For Global Health and Medicine https://ror.org/00r9w3j27


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#629]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: National Center For Global Health and Medicine
ROR ID: https://ror.org/00r9w3j27
Which part of the record needs to be changed? Organization website
Description of change: Please change the URL to "https://www.ncgm.go.jp/en/index.html" as the official website URL has been updated.

Update: replace.links==https://www.ncgm.go.jp/;$

**Comment by adambuttrick** [comment]
Current link does not resolve, but we should remove the English language reference entirely. A button to switch the page to English appears prominently on the main site.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
