### ISSUE TITLE
Modify the information in an existing ROR record: 
Bonn-Rhein-Sieg University of Applied Sciences  https://ror.org/04m2anh63


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#630]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Bonn-Rhein-Sieg University of Applied Sciences
ROR ID:  https://ror.org/04m2anh63
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record
Description of change: As stated on the website the primary name is "Hochschule Bonn-Rhein-Sieg". Please switch the primary and secondary name. 
Please also change the abbreviation, "BRSU"  is no longer used, the official abbreviation is "H-BRS". 
website: https://www.h-brs.de/en/portrait
Update: change.name==Hochschule Bonn-Rhein-Sieg; replace.labels==Bonn-Rhein-Sieg University of Applied Sciences*English; replace.acronyms==H-BRS; replace.links==https://www.h-brs.de/;$

**Comment by adambuttrick** [comment]
Org-requested. Change corresponds to organization's website branding and copyright statement. Updating URL to remove all language preferences, per our policies around this. Top-level domain has a prominent English-language option button as well.
