### ISSUE TITLE
Add a new organization to ROR: 
 
Società Romana di Scienze Naturali

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#631]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Società Romana di Scienze Naturali
Website: http://www.srsn.it
Link to publications:
Organization type: Nonprofit (A non-profit and non-governmental organization involved in conducting or funding research)
Wikipedia page: https://it.wikipedia.org/wiki/Societ%C3%A0_Romana_di_Scienze_Naturali
Wikidata ID: Q48837331
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels: Roman Society of Natural Science*English;
Acronym/abbreviation: SRSN
Related organizations: 
City: Roma
Country: Italia
Geonames ID: 3169070
Year established: 1967
How will a ROR ID for this organization be used? To identify affiliations for research publications

Other information about this request:

**Comment by adambuttrick** [comment]
Animal biology research society and one of the 36 institutes participating Fauna Europaea (https://fauna-eu.org/) biodiversity project, led by the Museum für Naturkunde. Independent, top-level organization with solid publication affiliation usage. Should be added to ROR.

Publication affiliation usage: https://anms.it/upload/rivistefiles/dab21e1adb2767e331adbe937c60eac1.pdf https://www.museostorianaturaletrieste.it/wp-content/uploads/2012/12/volume-57.pdf#page=113 ; http://www.anisn.it/nuovosito/wp-content/uploads/2014/07/Collezione-vertebratologica-BL.pdf

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/011ywze69 in release v1.1.
