### ISSUE TITLE
Modify the information in an existing ROR record: CEDIA https://ror.org/05xczn782

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#6316]
Summary of request: Modify the information in an existing ROR record

Name of organization: CEDIA
ROR ID: https://ror.org/05xczn782
Which part of the record needs to be changed? Website
Description of change: Correct website is https://cedia.edu.ec/

Update: replace.links==https://cedia.edu.ec;$

**Comment by adambuttrick** [comment]
Record updated in release v1.36.
