### ISSUE TITLE
Modify the information in an existing ROR record: 
Institute of Science and Technology Austria https://ror.org/03gnh5541


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#633]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Institute of Science and Technology Austria
ROR ID: https://ror.org/03gnh5541
Which part of the record needs to be changed? Other names or name versions listed in the record, Organization website
Description of change: Since 01.03.2022 the logo is changed and as a new short form ISTA is used. (see also https://ista.ac.at/en/institute/at-a-glance/)  the new link for the homepage reflect that (https://ista.ac.at)

Update: replace.links==https://ista.ac.at/; add.acronyms==ISTA;$

**Comment by adambuttrick** [comment]
New acronym is used on organization's site, so I think this is fine to add. There are still multiple references to the alias "IST Austria," (e.g. https://ist.ac.at/en/news/ista-sells-logo-as-nft/) so I think we should leave that in place for discoverability.
