### ISSUE TITLE
Add a new organization to ROR: Dong A University

### ISSUE THREAD

**Issue by phucquan95** [ror-community/ror-updates#6364]
Summary of request: Add a new organization to ROR

Name of organization: Dong A University
Website: https://donga.edu.vn
Link to publications: https://www.sciencedirect.com/science/article/abs/pii/S026840122031481X
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/%C4%90%C3%B4ng_%C3%81_University
Wikidata ID: Q10829180
ISNI ID: 0000 0005 0369 8202
GRID ID:
Crossref Funder ID: 
Other names for the organization: 
Aliases: Đại học Đông Á; Đông Á University
Acronym/abbreviation: UAD
Related organizations: 
City: Danang
Country: Vietnam
Geonames ID: 1583992
Year established: 2009
How will a ROR ID for this organization be used? Validate webometrics ranking information
Other information about this request: This is Dong A University in Da Nang city, Vietnam (Vietnamese name is Đại học Đông Á), please do not confuse it with Dong-a University in Korea.

**Comment by adambuttrick** [comment]
University in Vietnam. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by phucquan95** [comment]
Dong A University (Đại học Đông Á) is a university in Vietnam. Please refer to the scientific publications of the faculty members here, all clearly stating the address of Dong A University, Da Nang, Vietnam
[https://scholar.google.com/citations?view_op=search_authors&hl=en&mauthors=donga.edu.vn&btnG=](url)
Please do not confuse it with Dong-A University in South Korea.
