### ISSUE TITLE
Add a new organization to ROR: Virginia Division of Geology and Mineral Resources

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#64]
Summary of request: Add a new organization to ROR

Name of organization to be added | Virginia Division of Geology and Mineral Resources

Organization website | https://www.dmme.virginia.gov/dgmr/divisiongeologymineralresources.shtml

Briefly explain why you are requesting a ROR ID for this organization and how the ROR ID will be used. | We are a state geological survey in the USA. We conduct geoscience studies and host a large repository of physical samples of rocks, minerals, and fossils.

Provide DOI(s) or links for research associated with this organization, such as published articles that include the organization's name as an affiliation. If DOIs or links are not available, describe the research-related activities of this organization. | We conduct applied geoscience studies in the Commonwealth of Virginia and publish the results of those studies in maps, reports, and databases. Our focus is on geologic mapping, economic geology, and geologic hazards. Our publications can be searched and downloaded through our website: https://www.dmme.virginia.gov/commerce/

Other relevant metadata about the organization (e.g., name variants in other languages, related records in ROR, links to external records such as Wikidata) | None.

Please add any other information about this request if needed | I am requesting this registration because we have been asked to enter metadata about our physical collections into a database of geological materials repositories. The very first thing they request is our ROR, and we don't have one.

**Comment by KellyStathis** [comment]
Thanks for sharing this background information! I also found another ISNI for the "Division of Mineral Resources Virginia", which was the name from 1957-2008: https://isni.org/isni/0000000106698815.

I'm leaning in the same direction--that we should consider the history in full, along with the fact that it is a state Geological Survey (and therefore we have other similar organizations in ROR).

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03vtv7935 in release v1.0.
