### ISSUE TITLE
Add a new organization to ROR: Fundação Lemann

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#6401]
Summary of request: Add a new organization to ROR

Name of organization: Fundação Lemann
Website: https://fundacaolemann.org.br
Link to publications: 
Organization type: Nonprofit
Wikipedia page: https://pt.wikipedia.org/wiki/Funda%C3%A7%C3%A3o_Lemann
Wikidata ID: Q25419108
ISNI ID: 0000 0005 0382 7668
GRID ID: 
Crossref Funder ID: 501100020431
Other names for the organization: 
Aliases: Lemann Foundation-Brazil; Lemann Foundation
Labels: The Lemann Foundation*English
Acronym/abbreviation: 
Related organizations: 
City: São Paulo
Country: Brazil
Geonames ID: 3448439
Year established: 2001
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of Dryad funder reconciliation on #5938

**Comment by hnew1** [comment]
@adambuttrick is the *English descriptor needed for the Label?

**Comment by adambuttrick** [comment]
@hnew1 Yes! All labels require a language indicator.
