### ISSUE TITLE
Modify the information in an existing ROR record: 
Technological University Dublin https://ror.org/04t0qbt32


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#641]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Technological University Dublin
ROR ID: https://ror.org/04t0qbt32
Which part of the record needs to be changed? Other IDs for the organization
Description of change: Adding a ISNI Identifier - https://isni.org/isni/0000000495240153

Update: add.ISNI==0000 0004 9524 0153;$

**Comment by adambuttrick** [comment]
ISNI corresponds to organization.
