### ISSUE TITLE
Add a new organization to ROR: Canadian Statistical Sciences Institute

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#6419]
Summary of request: Add a new organization to ROR

Name of organization: Canadian Statistical Sciences Institute
Website: https://canssi.ca
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: 
ISNI ID: 0000 0005 1231 5867
GRID ID: 
Crossref Funder ID: 100022210
Other names for the organization: 
Aliases:
Labels: Institut Canadien des Sciences Statistiques*French
Acronym/abbreviation: CANSSI; INCASS
Related organizations: https://ror.org/0213rcc28 (parent)
City: Burnaby
Country: Canada
Geonames ID: 5911606
Year established: 
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of Dryad funder reconciliation on #5938

**Comment by hnew1** [comment]
https://ror.org/0213rcc28 is the host organisation.
