### ISSUE TITLE
Add a new organization to ROR: 
 
Rovereto Civic Museum Foundation

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#642]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Rovereto Civic Museum Foundation
Website: https://www.fondazionemcr.it
Link to publications: http://www.museocivico.rovereto.tn.it/annali
Organization type: Archive (An organization involved in stewarding research and cultural heritage materials. Includes libraries, museums, and zoos)
Wikipedia page: https://it.wikipedia.org/wiki/Museo_civico_di_Rovereto
Wikidata ID: Q3867769
ISNI ID: 0000 0001 2248 6425
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels: Fondazione Museo Civico di Rovereto*Italian
Acronym/abbreviation: FMCR
Related organizations: 
City: Rovereto
Country: Italy
Geonames ID: 3168854
Year established: 1851
How will a ROR ID for this organization be used? To identify affiliations for research publications

Other information about this request:

**Comment by adambuttrick** [comment]
Italian Museum with solid publication affiliation usage. Independent top-level entity. Should be added to ROR.

Publication affiliation usage: https://www.researchgate.net/institution/Fondazione_Museo_Civico_di_Rovereto ; https://www.researchgate.net/profile/Alessio-Bertolli

**Comment by carlyrobinson** [comment]
I agree with the assessment. Recommend adding to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04se57789 in release v1.1.
