### ISSUE TITLE
Add a new organization to ROR: Ministerio de Ciencia, Tecnología e Innovación

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#6429]
Summary of request: Add a new organization to ROR

Name of organization: Ministerio de Ciencia, Tecnología e Innovación
Website: https://minciencias.gov.co
Link to publications: 
Organization type: Government
Wikipedia page: 
Wikidata ID: Q77701552
ISNI ID: 
GRID ID: 
Crossref Funder ID: 100022965
Other names for the organization: 
Aliases: Ministra da Ciência, Tecnologia e Inovação; Ministre des Sciences, de la Technologie et de l'Innovation; MinCiencias; Ministry of Science, Technology and Innovation
Labels: 
Acronym/abbreviation: 
Related organizations: https://ror.org/048jthh02 (predecessor)
City: Bogotá
Country: Colombia
Geonames ID: 3688689
Year established: 
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of Dryad funder reconciliation on #5938

**Comment by hnew1** [comment]
@adambuttrick I am putting portmanteau names under aliases, eg "MinCiencias".  Let me know if portmanteau names should go under acronym/abbreviation instead.

**Comment by adambuttrick** [comment]
@hnew1 Your intuition was correct! Aliases is the correct place for them.
