### ISSUE TITLE
Add a new organization to ROR: 
 
Cherkasy Medical Academy  

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#643]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Cherkasy Medical Academy  
Website: http://medacademy.ck.ua
Link to publications: https://lumenpublishing.com/journals/index.php/rrem/article/view/3255
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://uk.wikipedia.org/wiki/%D0%A7%D0%B5%D1%80%D0%BA%D0%B0%D1%81%D1%8C%D0%BA%D0%B0_%D0%BC%D0%B5%D0%B4%D0%B8%D1%87%D0%BD%D0%B0_%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D1%96%D1%8F
Wikidata ID: Q12169819
ISNI ID: 0000 0005 0683 883X
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels: Черкаська медична академія*Ukrainian
Acronym/abbreviation: ChMA
Related organizations: 
City: Cherkasy
Country: Ukraine
Geonames ID: 710791
Year established: 1930
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Long-standing Ukrainian college with various medical, nursing, and pharmacy programs. Established as an independent, top-level entity in 1993. Should be added to ROR.

Publication affiliation usage: https://rsglobal.pl/index.php/ws/article/view/2140 ; http://nzp.tnpu.edu.ua/article/view/102698

ORCID affiliation usage: https://orcid.org/0000-0002-1181-841X ; https://orcid.org/0000-0003-2476-0963 ; https://orcid.org/0000-0002-2320-5530

**Comment by carlyrobinson** [comment]
I agree with the assessment. Recommend adding to ROR.
