### ISSUE TITLE
Add a new organization to ROR: Recherches Avancées sur la Biologie de l’Arbre et les Ecosystèmes Forestiers

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#6439]
Summary of request: Add a new organization to ROR

Name of organization: Recherches Avancées sur la Biologie de l’Arbre et les Ecosystèmes Forestiers
Website: https://mycor.nancy.inra.fr/ARBRE/
Link to publications: 
Organization type:
Wikipedia page: 
Wikidata ID: Q30267170
ISNI ID: 0000 0004 1794 7268
GRID ID: 
Crossref Funder ID: 100015818
Other names for the organization: 
Aliases: Labex ARBRE; Laboratory of Excellence for Advanced Research on the Biology of TRee and Forest Ecosystems;
Labels: 
Acronym/abbreviation: ARBRE
Related organizations: 
City: 
Country: France
Geonames ID: 
Year established: 
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of Dryad funder reconciliation on #5938

**Comment by hnew1** [comment]
Organisation already exists in ROR: https://ror.org/00gyb4719 but is missing Wikidata ID and Funder ID. 
@adambuttrick Not sure of workflow in this case?

**Comment by adambuttrick** [comment]
@hnew1 Just tag me and the existing ROR ID and I will correct. Thanks for flagging!
