### ISSUE TITLE
Modify the information in an existing ROR record: 
Geological Survey Ljubljana https://ror.org/05aw7p057


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#644]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Geological Survey Ljubljana
ROR ID: https://ror.org/05aw7p057
Which part of the record needs to be changed? Primary name, Organization website
Description of change: Primary name needs to be changed to: Geological Survey of Slovenia
Website needs to changed to: https://www.geo-zs.si
Update: change.name==Geological Survey of Slovenia; replace.links==https://www.geo-zs.si; add.labels==Geološki zavod Slovenije*Slovenian;$

**Comment by adambuttrick** [comment]
Name corresponds to English website branding. Parent domain of current link in ROR (which does not resolve).
