### ISSUE TITLE
Add a new organization to ROR:  Horlivka Institute for Foreign Languages

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#647]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Horlivka Institute for Foreign Languages
Website: http://forlan.org.ua/
Link to publications:
Organization type: Education (A university or similar institution involved in providing education and educating/employing researchers)
Wikipedia page: https://en.wikipedia.org/wiki/Horlivka_Institute_for_Foreign_Languages
Wikidata ID: Q4144467
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: 
Labels: Горлівський інститут іноземних мов*Ukrainian
Acronym/abbreviation:
Related organizations: 
City: Bakhmut
Country: Ukraine
Geonames ID: 713174
Year established: 1949
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets

Other information about this request: There are ROR for our separate division https://ror.org/059mp4e63 but this is a different organization.

**Comment by adambuttrick** [comment]
Already exists in ROR under variant name, "Donbass State Pedagogical University." Will update record to correspond to request.

**Comment by adambuttrick** [comment]
Current link in ROR redirects to link provided by user and is located in the same city, so I'm not sure how these organizations are supposed to differ. Will reach out to requester.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05mqfgg03 in release v1.1.
