### ISSUE TITLE
Add a new organization to ROR: 
 
CNR ISPAAM Istituto per il sistema produzione animale in ambiente Mediterraneo 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#648]
Summary of request: Add a new organization to ROR

Update record:
Name of organization: 
ROR ID: 
Which part of the record needs to be changed? 
Description of change: 

Merge/split/deprecate records:
Organizations affected by this change:
ROR ID(s) of organization(s) affected by this change: 
How should the record(s) be changed? 

Add record:
Name of organization: CNR ISPAAM Istituto per il sistema produzione animale in ambiente Mediterraneo 
Website: http://www.ispaam.cnr.it/home_it.htm
Link to publications: https://publications.cnr.it/institutes/083/2
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: 
Wikidata ID: https://www.wikidata.org/wiki/Q30282022
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: Institute for animal production system in mediterranean environment (ISPAAM)
Labels:
Acronym/abbreviation: ISPAAM-CNR
Related organizations: CNR
City: Portici (NA) 
Country: Italy
Geonames ID:
Year established: 2002
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment]
Already exists in ROR - https://ror.org/01wqae691
