### ISSUE TITLE
Add a new organization to ROR: Orient-Institut Istanbul

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#654]
Summary of request: Add a new organization to ROR

Name of organization: Orient-Institut Istanbul
Website: https://www.oiist.org
Link to publications: 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Orient-Institut_Istanbul
Wikidata ID: Q15837722
ISNI ID: 0000 0000 8190 0334
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: OI Istanbul
Labels: Orient Enstitüsü İstanbul*Turkish; Orient-Institute Istanbul*English
Acronym/abbreviation: OII
Related organizations: https://ror.org/02esxtn62 (parent)
City: Istanbul
Country: Turkey
Geonames ID: 745044
Year established: 2009
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Child of the German government organization the Max Weber Foundation - German Humanities Institutes Abroad (https://ror.org/02esxtn62). Its sibling, the Orient-Institut Beruit (https://ror.org/03wd03705) is already included in ROR, so this should be added as well. 

Google Scholar affiliation usage: https://scholar.google.com/citations?user=0R9hRMAAAAAJ
ORCID affiliation usage: https://orcid.org/0000-0002-7911-5649 ; https://orcid.org/0000-0003-1907-9946 ; https://orcid.org/0000-0003-0362-134X

**Comment by arthurpsmith** [comment]
This all makes sense to me, yes it should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05jm6kj71 in release v1.1.
