### ISSUE TITLE
Add a new organization to ROR: Max Weber Forum für Südasienstudien Delhi

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#655]
Summary of request: Add a new organization to ROR

Name of organization: Max Weber Forum für Südasienstudien Delhi
Website: https://mwfdelhi.hypotheses.org/
Link to publications: 
Organization type: Government
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: MWF Delhi
Labels: Max Weber Forum for South Asian Studies in Delhi*English
Acronym/abbreviation:
Related organizations: https://ror.org/02esxtn62 (parent)
City: New Delhi
Country: India
Geonames ID: 1261481
Year established: 2021
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Child of the German government organization the Max Weber Foundation - German Humanities Institutes Abroad (https://ror.org/02esxtn62). Relatively new, but since its sibling, the Orient-Institut Beruit (https://ror.org/03wd03705) is already included in ROR, so this should be added as well.

**Comment by arthurpsmith** [comment]
Their "other publications" seem to mostly predate the formation of the institute! However at least one publication there lists this as the affiliation, and clearly they have plans for growth. Since we have (most of?) the other Max Weber Foundation institutes in ROR, we should add this one too.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03pe74b89 in release v1.1.
