### ISSUE TITLE
Add a new organization to ROR: Atlantic Technological University

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#656]
Summary of request: Add a new organization to ROR

Name of organization: Atlantic Technological University
Website: https://www.atu.ie/
Link to publications: 
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Atlantic_Technological_University
Wikidata ID: Q58310020
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: ATU
Aliases: Atlantic TU
Labels: Ollscoil Teicheolaíochta an Atlantaigh*Irish
Related organizations: 
City: Sligo
Country: Ireland
Geonames ID: 2961423
Year established: 2021
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Successor organization for rhe Galway-Mayo Institute of Technology (https://ror.org/024j9sx72), Letterkenny Institute of Technology (https://ror.org/04s2yen12) and Institute of Technology, Sligo (https://ror.org/032fvf508), which have merged, as described in #652. Since the former orgs were all in scope, this obviously would be as well.

**Comment by nlundvick** [comment]
Concur with first reviewer - assign a ROR ID to this organization.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0458dap48 in release v1.0.
