### ISSUE TITLE
Modify the information in an existing ROR record: 
Oslo Metropolitan University https://ror.org/04q12yn84


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#657]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Oslo Metropolitan University
ROR ID: https://ror.org/04q12yn84
Which part of the record needs to be changed? Organization website
Description of change: https://www.oslomet.no/en

Update: replace.links==https://www.oslomet.no;$

**Comment by adambuttrick** [comment]
Current link in record does not resolve, while this does.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
