### ISSUE TITLE
Merge two or more ROR records: 
 
Osaka City University, Osaka Prefecture Universityhttps://ror.org/02skfsw40 and https://ror.org/02cf1je33

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#658]
Summary of request: Merge two or more ROR records

Merge/split/deprecate records:
Organizations affected by this change:Osaka City University, Osaka Prefecture University
ROR ID(s) of organization(s) affected by this change: https://ror.org/02skfsw40 and https://ror.org/02cf1je33
How should the record(s) be changed? These have merged to form "Osaka Metropolitan University" - see https://www.upc-osaka.ac.jp/new-univ/en-research/about/

Other information about this request: Wikidata ID for merged university: https://www.wikidata.org/wiki/Q101579967

**Comment by adambuttrick** [comment]
Merger corresponds to description on organization's site. Moving to "Hold for Later" until we have deprecation functionality.

**Comment by adambuttrick** [comment]
Individual updates cover this deprecation, thus closing.
