### ISSUE TITLE
Add a new organization to ROR: Good Clinical Practice Alliance - Europe

### ISSUE THREAD

**Issue by FrancisPC** [ror-community/ror-updates#6588]
Summary of request: Add a new organization to ROR

Name of organization: Good Clinical Practice Alliance - Europe
Website: https://gcpalliance.org
Link to publications: 
Organization type: Nonprofit
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Good Clinical Practice Alliance
Labels
Acronym/abbreviation: GCPA
Related organizations: 
City: Leuven
Country: Belgium
Geonames ID: 2792482
Year established: 2005
How will a ROR ID for this organization be used? For identifying research projects and publications
Other information about this request:

**Comment by adambuttrick** [comment]
NPO in Belgium. All affiliation usage is for a single author, the organization's principal. ROR requires evidence of affiliation usage by more than one person to be added to the registry, so declining as out of scope until this can be demonstrated.
