### ISSUE TITLE
Add a new organization to ROR: Osaka Metropolitan University

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#659]
Summary of request: Add a new organization to ROR

Name of organization: Osaka Metropolitan University
Website: https://www.omu.ac.jp
Link to publications: 
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Osaka_Metropolitan_University
Wikidata ID: Q101579967
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases:
Labels: 大阪公立大学*Japanese
Acronym/abbreviation:
Related organizations: 
City: Osaka
Country: Japan
Geonames ID: 1853909
Year established: 2022
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Per #658, Osaka City University and Osaka Prefecture University (https://ror.org/02skfsw40 and https://ror.org/02cf1je33) have merged into a single institution. While this change is very new (April 2022), since both prior orgs were in scope, this would be as well. Should be added.

Google Scholar affiliation usage: https://scholar.google.com/citations?user=fDMvqTAAAAAJ; https://scholar.google.com/citations?user=RvO1LXYAAAAJ; https://scholar.google.com/citations?user=Yfq0HloAAAAJ
ORCID affiliation usage: https://orcid.org/0000-0003-2850-5409 ; https://orcid.org/0000-0001-6787-3728 ; https://orcid.org/0000-0002-7983-554X
issue_references: None

**Comment by arthurpsmith** [comment]
Since I'm the one who requested this I won't act as second approval, but just to note that I do support this!

**Comment by adambuttrick** [comment]
I'll vouch for this as the second approval, per my original comment.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01hvx5h04 in release v1.1.
