### ISSUE TITLE
Add a new organization to ROR: North Carolina Geological Survey

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#66]
Summary of request: Add a new organization to ROR

Name of organization to be added | North Carolina Geological Survey

Organization website | https://deq.nc.gov/about/divisions/energy-mineral-land-resources/north-carolina-geological-survey

Briefly explain why you are requesting a ROR ID for this organization and how the ROR ID will be used. | The ROR ID will be used to track the NCGS Coastal Plain Office and Core Repository and its holdings.

Provide DOI(s) or links for research associated with this organization, such as published articles that include the organization's name as an affiliation. If DOIs or links are not available, describe the research-related activities of this organization. | Applied research in mapping, stratigraphy, hydrostratigraphy, sedimentology, geomorphology, geologic hazards, Quaternary, bedrock geology.https://deq.nc.gov/about/divisions/energy-mineral-land-resources/north-carolina-geological-survey/ncgs-publications

Other relevant metadata about the organization (e.g., name variants in other languages, related records in ROR, links to external records such as Wikidata) | North Carolina Geological Survey Coastal Plain Office and Core Repository

Related organizations: https://ror.org/01ftg8r37 (parent)

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03qhydd02 in release v1.0.
