### ISSUE TITLE
Add a new organization to ROR: HELIN Library Consortium

### ISSUE THREAD

**Issue by sckott** [ror-community/ror-updates#660]
Summary of request: Add a new organization to ROR

Name of organization: HELIN Library Consortium
Website: https://helininc.org
Link to publications: 
Organization type: Other
Wikipedia page: 
Wikidata ID:
ISNI ID: 0000 0004 0622 8698
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: The Higher Education Library Information Network
Acronym/abbreviation: HELIN
Related organizations: https://ror.org/0104cy831 (related) https://ror.org/03w2cyv53 (related) https://ror.org/00rxpqe74 (related) https://ror.org/01k5gt570 (related) https://ror.org/017nweb49 (related) https://ror.org/004qfsw40 (related) https://ror.org/055ja0v85 (related)
City: Warwick, Rhode Island
Country: United States
Geonames ID: 5225507
Year established: 2005
How will a ROR ID for this organization be used? We use ROR IDs in Unsub (https://unsub.org/) to link institutions to other types of data
Other information about this request:
- In ICOLC: https://www.icolc.net/participating-consortia/helin-higher-education-library-information-network
- Consortium members:  Community College of Rhode Island, the Johnson & Wales University, Providence College, Rhode Island College, Roger Williams University, Salve Regina University, Wheaton College

**Comment by adambuttrick** [comment]
This is needed to identify the organization in ROR intergrator OurResearch's product Unsub.

We have similar consortium already represented in ROR, e.g., https://ror.org/02m6s1q30 and https://ror.org/01vvcdt37, so this is in scope and should be added.

**Comment by carlyrobinson** [comment]
Agree with the assessment; recommend adding to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03b4ffc11 in release v1.1.

**Comment by sckott** [comment]
great, thanks
