### ISSUE TITLE
Project: Norwegian research institutions

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#661]
Sikt - Norwegian Agency for Shared Services in Education and Research is undertaking a project to develop a national knowledge archive for Norway. Many of the organizations in their registry are already in ROR but some are not. The linked spreadsheet includes 5 that they wish to add. It looks like one is already in ROR but I am waiting on the requestor to verify.

https://docs.google.com/spreadsheets/d/1ubvpTLbBfZSRCEjMQO3atZ-EaPvtAjWDSwhK6fLbggM/edit#gid=0

Per Sikt, these are "non-education institutions that do research equal to universities, with more or less governmental funding and mandate. Some of them are located to a facility, but most are not."

**Comment by mariagould** [comment]
@arthurpsmith sorry about that! The access issue should be resolved now.

**Comment by arthurpsmith** [comment]
Ok, I've reviewed these and added my assessments.
One of the 4 remaining ones is also already in ROR - https://ror.org/01vmqaq17 has changed its name to NORSUS.
Of the other 3, two had clear uses as affiliations and do seem actively engaged in research. The last is the new one and doesn't seem to have been used as an affiliation itself yet - I'm not sure why as it's not so very new but even very recent (2022) publications by the listed author seem to use a different affiliation, and google scholar found nothing. Nevertheless I suppose for completeness it would be useful to add this one also.

**Comment by adambuttrick** [comment]
Records created as part of release v1.1.

ROR ID | Organization name
-- | --
https://ror.org/05tas6715 | The Norwegian Center for Child Behavioral Development
https://ror.org/03s2agk53 | The Norwegian Institute for Children’s Books
https://ror.org/04r8kt465 | University College of Vocational Education
