### ISSUE TITLE
Modify the information in multiple existing ROR records:  University of Puerto Rico

### ISSUE THREAD

**Issue by leonardcj** [ror-community/ror-updates#6614]
Summary of request: Modify the information in an existing ROR record

https://ror.org/04w7hre37	
University of Puerto Rico at Aguadilla		
https://en.wikipedia.org/wiki/University_of_Puerto_Rico_at_Aguadilla

Should properly be

PR	Puerto Rico
instead of 
US	United States

Same issue for:
https://ror.org/038z2eg27	University of Puerto Rico at Arecibo
https://ror.org/058hjkk82	University of Puerto Rico at Bayamón
https://ror.org/05phyf558	University of Puerto Rico at Carolina
https://ror.org/00yxqn620	University of Puerto Rico at Cayey
https://ror.org/020wm8g88	University of Puerto Rico at Humacao
https://ror.org/04vs2n780	University of Puerto Rico at Ponce
https://ror.org/05s2fqz02	University of Puerto Rico at Utuado
https://ror.org/00h25w961	University of Puerto Rico, Medical Sciences Campus
https://ror.org/00wek6x04	University of Puerto Rico-Mayaguez

These appear correct:
https://ror.org/0453v4r20	University of Puerto Rico at Río Piedras
https://ror.org/02yg0nm07	University of Puerto Rico System

**Comment by adambuttrick** [comment]
Geonames switched from US to PR at some point in the past, but the listed records have not had an address refresh since that time. I've refreshed.

**Comment by adambuttrick** [comment]
Updated in release v1.37.
