### ISSUE TITLE
Modify the information in an existing ROR record: Brandon Roberts + Associates (United States) https://ror.org/04hm1bb33

### ISSUE THREAD

**Issue by leonardcj** [ror-community/ror-updates#6615]
Summary of request: Modify the information in an existing ROR record

Name of organization: Brandon Roberts + Associates (United States)
ROR ID: https://ror.org/04hm1bb33
Which part of the record needs to be changed? ...geonames_admin1..., ...geonames_admin2...

Description of change:

Chevy Chase	4138011	
Washington, D.C.	4138106	
Washington, D.C.	4138106

Should be

Chevy Chase	4138011	
Maryland	4361885
Maryland	4361885

addresses[0].geonames_city.name	addresses[0].geonames_city.id
addresses[0].geonames_city.geonames_admin1.name	addresses[0].geonames_city.geonames_admin1.code
addresses[0].geonames_city.geonames_admin2.name	addresses[0].geonames_city.geonames_admin2.code

**Comment by adambuttrick** [comment]
Updated in release v1.37.
