### ISSUE TITLE
Modify the information in an existing ROR record: 
Deutsche Forschungsgemeinschaft https://ror.org/018mejw64


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#662]
Summary of request: Modify the information in an existing ROR record

Update record:
Name of organization: Deutsche Forschungsgemeinschaft
ROR ID: https://ror.org/018mejw64
Which part of the record needs to be changed? Other IDs for the organization
Description of change: The ISNI-ID "0000000119579997" for "Deutsche Forschungsgemeinschaft" doesn't seem to be the right one. It seems to be the ISNI-ID for "Deutsche Forschungsgemeinschaft Südosteuropa-Arbeitskreis". I guess more appropriate would be:

Deutsche Forschungsgemeinschaft: ISNI "0000 0001 2096 9829"

Also Wikidata and GRID use the ISNI-ID "0000000119579997" (Deutsche Forschungsgemeinschaft Südosteuropa-Arbeitskreis)  instead of "0000 0001 2096 9829" (Deutsche Forschungsgemeinschaft). Might be some kind of consequential error?

Update: replace.ISNI==0000 0001 2096 9829;$

**Comment by adambuttrick** [comment]
Suggested ISNI corresponds to ROR record.

**Comment by adambuttrick** [comment]
Record updated in release v1.1.
