### ISSUE TITLE
Add a new organization to ROR: Continental Scientific Drilling Facility

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#67]
Summary of request: Add a new organization to ROR

Name of organization: Continental Scientific Drilling Facility
Website: https://cse.umn.edu/csd
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Acronym/abbreviation: CSD
Related organizations: https://ror.org/017zqws13 (parent)
City: Minneapolis, Minnesota
Country: USA
Geonames ID: 5037649
Year established: 2021
How will a ROR ID for this organization be used? 
Other information about this request:

Briefly explain why you are requesting a ROR ID for this organization and how the ROR ID will be used. | The Continental Scientific Drilling Facility is a national facility funded by NSF for support of scientific research involving drilling and coring on land and in lakes, core analysis, and curation. The ROR ID will allow unique linkages between the facility and the researchers it supports, and the outputs from this research.

Provide DOI(s) or links for research associated with this organization, such as published articles that include the organization's name as an affiliation. If DOIs or links are not available, describe the research-related activities of this organization. | https://experts.umn.edu/en/organisations/continental-scientific-drilling-facility

Other relevant metadata about the organization (e.g., name variants in other languages, related records in ROR, links to external records such as Wikidata) | Name variants include CSD Facility, CSDF, and the former facilities that merged to form the current facility in mid-2020: LacCore and CSDCO (Continental Scientific Drilling Coordination Office). Earlier variants include the Limnological Research Center or LRC, which sometimes still appear in publications.

Please add any other information about this request if needed | We are rebuilding our website and will soon have a new URL, which we will update with ROR when the website launches.

**Comment by adambuttrick** [comment]
New site is live, so this should be processed:

https://cse.umn.edu/csd

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02amckb22 in release v1.0.
