### ISSUE TITLE
Add a new organization to ROR: Pandian Educational Trust

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#68]
Summary of request: Add a new organization to ROR

Name of organization: Pandian Educational Trust
Website: https://sites.google.com/view/pandianeducationaltrust
Link to publications: 
Wikipedia page: 
Wikidata ID: nil
ISNI ID: https://isni.org/isni/0000000493432717
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: Virudhunagar, Tamil Nadu
Country: India
Other information about this request: Pandian Educational Trust is a public trust that has emerged  from the foresight of Mrs.D.Maheswari to foster educational services for the society. It destinies to foster the academic activities for the needed people. It runs academic journals to for Tamil "தமிழ்மொழி மற்றும் இலக்கிய பன்னாட்டு ஆய்விதழ்" ( International Journal of Tamil Language and Literary Studies (ijtlls) ) CARE LISTED JOURNAL ijtlls.com/ and English "Literary Druid"  literarydruid.com/ and கோயில் கலைகள்  தமிழ் ஆய்விதழ் (Tamil Journal of Temple Studies) tamiljournaloftemplestudies.wordpress.com/  to encourage research in the domain areas. It also provide paid plagiarism services to Tamil and other department academicians.

**Comment by carlyrobinson** [comment]
I agree with @arthurpsmith that if we add, we should add the publishing organization. It seems like this might be a one person organization. I wasn't able to find links the the 3 journals they publish.

**Comment by adambuttrick** [comment]
Situation is unchanged, so declining this as out of scope.
