### ISSUE TITLE
Add a new organization to ROR: GW4

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#686]
Summary of request: Add a new organization to ROR

Name of organization: GW4
Website: https://gw4.ac.uk
Link to publications: 
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/GW4
Wikidata ID: Q28402688
ISNI ID: 0000 0004 7478 045X
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: GW4 Alliance; Great Western 4
Acronym/abbreviation:
Related organizations: https://ror.org/0524sp257 (related) https://ror.org/03yghzc09 (related) https://ror.org/002h8g185 (related) https://ror.org/03kk7td41 (related) https://ror.org/022p86748 (child)
City: Bristol
Country: United Kingdom
Geonames ID: 2654675
Year established: 2013
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Joint research and instructional initiative by the universities of Bath, Bristol, Cardiff and Exeter. Came to our attention by way of #685, which demonstrates their funding of research facilities. In addition, they have a joint pool of funds for sponsoring cross-collaborative research between the organizations. Similar to https://ror.org/006e48x19. Should be added to ROR.

**Comment by carlyrobinson** [comment]
Agree with the assessment; recommend adding to ROR.
