### ISSUE TITLE
Add a new organization to ROR: Muzeum Archeologiczne w Poznaniu

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#69]
Summary of request: Add a new organization to ROR

Name of organization: Muzeum Archeologiczne w Poznaniu
Website: https://www.muzarp.poznan.pl/
Link to publications: An example of DOI of "Fontes Archaeologici Posnanienses": 10.34868/fap.55
Wikipedia page: https://pl.wikipedia.org/wiki/Muzeum_Archeologiczne_w_Poznaniu
Wikidata ID: Q11786905
ISNI ID: https://isni.org/isni/0000000119313910
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 154685
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: Poznan
Country: Poland
Other information about this request: publishes a scientific yearbook ("Fontes Archaeologici Posnanienses" ISSN 0071-6863) and publishes scientific monographs in two series: "Bibliotheca Fontes Archaeologici Posnanienses" (ISSN 0208-4988) and "Studies in African Archaeology" (ISSN 0866-9244). The use of ROR ID is recommended in Poland by the National Science Center for all research organizations.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05qzrbt52 in release v1.0.
