### ISSUE TITLE
Investigate record: https://ror.org/01br3aa17

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#7]
ROR ID: https://ror.org/01br3aa17
Name of organization: Biophysics Center of Armenian
User feedback re: Biophysics Center of Armenian (https://ror.org/01br3aa17)     

> This "Biophysics" entity is not shown in the diagram of the current structure of the Armenian Academy of Sciences (the domain sci.am/)

We should investigate whether this organization is still active. If not, the record should be deprecated.

Update: change.status==inactive;$
Relationships: https://ror.org/02yqgb753 (successor)

**Comment by adambuttrick** [comment]
According to this description, the organization has been inactive since 1996, when it was restructured into a new entity:

>"In 1996 the Biophysics Center of Armenian NAS was awarded the status of UNESCO Chair in Life Sciences by UNESCO Director General Mr. Federico Mayor and was reorganized into Life Sciences International Postgraduate Educational Center (LSIPEC). LSIPEC is specialized in Biophysics, Biotechnology, Environmental Health, Neuroscience, Biomedical Engineering."
http://www.biophys.am/pages/index/About/

**Comment by adambuttrick** [comment]
Record updated in release v1.15.
