### ISSUE TITLE
Add a new organization to ROR: KBASE

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#70]
Summary of request: Add a new organization to ROR

Name of organization: KBase
Website: https://www.kbase.us/
Link to publications: Platform publication: 10.1038/nbt.4163
Updates to features, databases, data sets: 0.1109/CANOPIE-HPC49598.2019.00009; 10.1038/s41587-020-0718-6; doi.org/10.1093/nar/gkaa746E
Examples of user research: 10.25982/59912.37/1635154; 10.25982/51077.6/1637903; 10.25982/54100.27/1635639
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: https://ror.org/01bj3aw27 (parent)
City: 
Country: 
Other information about this request: 
KBase is a free, open source data analysis and sharing platform funded by the Department of Energy to support research and education in systems biology and bioinformatics. KBase supports the movement towards FAIR data principles. For example, data sets and reproducible analysis workflows can received DOIs that can be included in publications.

KBase is a data analysis platform that allows users to combine data from many sources to do sophisticated analysis thru a free, open source, graphical user interface. I believe that unique research discoveries are enabled by our platform, and we are now able to produce static snap-shots of analysis workflows, which get a DOI and can be submitted in a publication, for example in a data availability statement. So, yes - included in publication metadata associated w the DOI for the data workflow. We would include the ROR ID directly into the DOI metadata, which would sync automatically with DataCite.

For several of us on the project that are still active researchers, we would also include the ROR ID in our ORCID accounts, for example. We are hoping, in a few years, to start enabling a post-doc program and possibly community grants to work with us, which could also utilize the affiliation ID.

**Comment by mariagould** [comment]
Relationships:

https://ror.org/01bj3aw27, parent

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01znn6x10 in release v1.0.
