### ISSUE TITLE
Modify Oita National College of Technology (https://ror.org/05983b311)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#71]
Summary of request: Modify an existing organization in ROR

Name of organization: Oita National College of Technology
ROR ID: https://ror.org/05983b311
Which part of the record needs to be changed? 
The English name in the record is currently Oita National College of Technology. This should be changed National Institute of Technology, Oita College. This change aligns with the name convention used in similar records (https://ror.org/03pngf508 and https://ror.org/040mta007)

Additional links for verification:
http://www.oita-ct.ac.jp/
https://www.wikidata.org/wiki/Q11432687
Update: change.name==National Institute of Technology, Oita College; add.Wikidata==Q11432687;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
