### ISSUE TITLE
Modify the information in an existing ROR record: https://ror.org/03q2cf306  Achaogen (United States)

### ISSUE THREAD

**Issue by leonardcj** [ror-community/ror-updates#7194]
Summary of request: Modify the information in an existing ROR record

Name of organization: Achaogen (United States)
ROR ID: https://ror.org/03q2cf306
Which part of the record needs to be changed? Add ISNI
Description of change:
Add ISNI
https://isni.org/isni/0000000403956868

Update: add.ISNI==0000 0004 0395 6868;$

**Comment by adambuttrick** [comment]
ISNI ID is that for the organization.

**Comment by adambuttrick** [comment]
Updated in release v1.38.
