### ISSUE TITLE
Modify the information in an existing ROR record: Allegheny-Singer Research Institute https://ror.org/004315x41

### ISSUE THREAD

**Issue by leonardcj** [ror-community/ror-updates#7196]
Summary of request: Modify the information in an existing ROR record

Name of organization: Allegheny-Singer Research Institute 
ROR ID: https://ror.org/004315x41
Which part of the record needs to be changed? Add ISNI
Description of change:
Add ISNI
https://isni.org/isni/0000000459301844

Update: add.ISNI==0000 0004 5930 1844;$

**Comment by adambuttrick** [comment]
ISNI ID is that for the organization.
