### ISSUE TITLE
Modify the information in an existing ROR record: Air Force Institute of Technology (Poland/US) DISAMBIGUATION

### ISSUE THREAD

**Issue by leonardcj** [ror-community/ror-updates#7198]
Summary of request: Modify the information in an existing ROR record

Name of organization: Air Force Institute of Technology
ROR ID: https://ror.org/0410xnr11 AND https://ror.org/03f9f1d95
Which part of the record needs to be changed? Name
Description of change:

Disambiguation of name

https://ror.org/0410xnr11	Air Force Institute of Technology
https://ror.org/03f9f1d95	Air Force Institute of Technology
to
https://ror.org/0410xnr11	Air Force Institute of Technology (Poland)
https://ror.org/03f9f1d95	Air Force Institute of Technology (United States)

**Comment by adambuttrick** [comment]
We can disambiguate by switching the Polish record to use its Polish label as primary and addition of the some aliases on the US record. Both unfortunately do use the same exact same name in English.

**Comment by adambuttrick** [comment]
Updated in release v1.38.
