### ISSUE TITLE
Add a new organization to ROR: ResearchGate

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#73]
Summary of request: Add a new organization to ROR

Name of organization: ResearchGate
Website: https://www.researchgate.net
Link to publications: 
Wikipedia page: https://en.wikipedia.org/wiki/ResearchGate
Wikidata ID: Q754454
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: Berlin
Country: Germany
Other information about this request: ResearchGate’s mission is to connect the world of science. ResearchGate is working with various stakeholders in the scientific ecosystem and the scholarly communication supply chain. We hope that ROR IDs can facilitate technical integration work.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/008f3q107 in release v1.0.
