### ISSUE TITLE
Use the English names of 5 organizations in Czechia

### ISSUE THREAD

**Issue by jdvorak001** [ror-community/ror-updates#739]
Summary of request: Modify the information in an existing ROR record

Description of change: Most other organizations in the Czech Republic are presented with their English names, but I found these five are using their (correct) Czech forms. I'd suggest to unify these records, i.e.
* move the current names into aliases;
* use the following English names:

https://ror.org/04z6gwv56: Národní muzeum -> National Museum
https://ror.org/00jk0vn85: Revmatologický Ústav -> Institute of Rheumatology
https://ror.org/04hyq8434: Thomayerova nemocnice -> Thomayer University Hospital
https://ror.org/04sg4ka71: Fakultní nemocnice Královské Vinohrady -> University Hospital Kralovske Vinohrady
https://ror.org/02c1tfz23: Fakultní Nemocnice Plzeň -> University Hospital Plzen

Examples of similar Czech institutions:
https://ror.org/00a6yph09: University Hospital Ostrava
https://ror.org/04yg23125: General University Hospital in Prague
https://ror.org/019k25552: National Heritage Institute

I'm basing this request on a [mapping table](https://github.com/jdvorak001/isvavai-orgs-ror-mapping) I have compiled.

**Comment by adambuttrick** [comment]
@jdvorak001 Thank you for your mapping table! We have already used it to make these changes in #433. These changes are slated be included in our next release:

https://github.com/ror-community/ror-updates/commit/b1d0339a74551b262a9286948940e57c32a32596

**Comment by adambuttrick** [comment]
Closing, as request has already been addressed in a previous issue.

**Comment by jdvorak001** [comment]
Excellent, thank you!
