### ISSUE TITLE
Modify the information in an existing ROR record: Consortium of European Social Science Data Archives (https://ror.org/02wg9xc72)

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#74]
Summary of request: Modify the information in an existing ROR record

Name of organization: Consortium of European Social Science Data Archives
ROR ID: https://ror.org/02wg9xc72
Which part of the record needs to be changed? Website
Description of change: Change Website from http://cessda.net to https://www.cessda.eu
Update: delete.links==http://cessda.net/; add.links==https://www.cessda.eu;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
