### ISSUE TITLE
Add a new organization to ROR: Moinhos de Vento Agroecology Research Centre

### ISSUE THREAD

**Issue by palmajoao** [ror-community/ror-updates#7511]
Summary of request: Add a new organization to ROR -> MVARC

Name of organization: Moinhos de Vento Agroecology Research Centre 
Website: https://www.mvarc.eu
Link to publications: https://mvarc.eu/publications
Organization type: Facility
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Moinhos de Vento Agroecological Research Centre; MV Agroecological Research Centre; MV Agroecology Research Centre; MV Agroecology
Labels:
Acronym/abbreviation: MVARC
Related organizations: 
City:  Moinhos de Vento de Baixo, 7750-217 Espírito Santo
Country: Portugal
Geonames ID: 2266324
Year established: 2018
How will a ROR ID for this organization be used? Initially, to allow staff to edit their profiles in ORCID having MARC listed as Institution
Other information about this request:

**Comment by adambuttrick** [comment]
Research center in Portugal. Funds and employs researchers. Solid affiliation usage. Should be added.
