### ISSUE TITLE
Add a new organization to ROR: Kélonia

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#754]
Summary of request: Add a new organization to ROR

Name of organization: Kélonia
Website: https://museesreunion.fr/kelonia
Link to publications: https://doi.org/10.7589/2018-04-103; https://doi.org/10.1002/vrc2.22
Organization type: Archive
Wikipedia page: https://fr.wikipedia.org/wiki/K%C3%A9lonia
Wikidata ID: Q259897
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Kélonia, l'Observatoire des Tortues Marines
Acronym/abbreviation:
Related organizations: #752 (related)
City: Saint Leu, La Reunion
Country: France
Geonames ID: 935225
Year established: 2006
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by carlyrobinson** [comment]
Agree, should be added to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/04181p105 in release v1.3.
