### ISSUE TITLE
Modify the information in an existing ROR record: https://ror.org/search?query=Dong+A+University+/+T

### ISSUE THREAD

**Issue by phucquan95** [ror-community/ror-updates#7551]
Summary of request: Modify the information in an existing ROR record

Name of organization: Dong A University / Trường Đại Học Đông Á
ROR ID: 
Which part of the record needs to be changed? https://ror.org/search?query=Dong+A+University+/+T
Description of change: link Dong A University / Trường Đại Học Đông Á, World Rank 8385 with ROR  https://ror.org/0164qgj37

**Comment by adambuttrick** [comment]
ROR has no affiliation with or connection to Webometrics. Please follow up with their staff about use of ROR IDs in their service.
