### ISSUE TITLE
Modify the information in an existing ROR record: Congressionally Directed Medical Research Programs https://ror.org/03g2zjp07

### ISSUE THREAD

**Issue by leonardcj** [ror-community/ror-updates#7652]
Summary of request: Modify the information in an existing ROR record

Name of organization: Congressionally Directed Medical Research Programs
ROR ID: https://ror.org/03g2zjp07
Which part of the record needs to be changed? update URL
Description of change:
URL used to be
http://cdmrp.army.mil/
now is
https://cdmrp.health.mil/

Update: replace.links==https://cdmrp.health.mil; delete.relationships==https://ror.org/0447fe631;$

Related organizations: https://ror.org/03cd02q50 (parent)

**Comment by adambuttrick** [comment]
Confirmed link for the organization.

**Comment by leonardcj** [comment]
Strictly speaking there was some sort of organizational change and CDMRP is now a child of 

https://ror.org/03df8gj37
Defense Health Agency

thus the change in web URL and e-mail addresses.

It is also still described as being a subordinate command of 
https://ror.org/03cd02q50
United States Army Medical Research and Development Command

**Comment by adambuttrick** [comment]
@leonardcj I've listed both as parents for now, but can follow up with our DOD contact to clarify as well.

**Comment by adambuttrick** [comment]
Per DOD contact, U.S. Army Medical Research and Development Command (USAMRDC), is the correct parent, with Defense Health Agency acting as an oversight body for USAMRDC's work on the program.

**Comment by adambuttrick** [comment]
Record updated in release v1.40.
