### ISSUE TITLE
Modify the information in an existing ROR record: Albany College of Pharmacy and Health Sciences https://ror.org/014hfaw95

### ISSUE THREAD

**Issue by leonardcj** [ror-community/ror-updates#7653]
Summary of request: Modify the information in an existing ROR record

Name of organization: Albany College of Pharmacy and Health Sciences
ROR ID: https://ror.org/014hfaw95
Which part of the record needs to be changed? ISNI number
Description of change:
ROR is using 
https://isni.org/isni/000000008718587X
when they should be using
https://isni.org/isni/0000000403675521

First link is to precursor organization ACP (1800's), second link is to current organization ACPHS

Update: replace.ISNI==0000 0004 0367 5521;$

**Comment by adambuttrick** [comment]
Confirmed correct ISNI.

**Comment by adambuttrick** [comment]
Record updated in release v1.40.
