### ISSUE TITLE
Modify the information in an existing ROR record: Anderson University - South Carolina https://ror.org/01gmrmd93

### ISSUE THREAD

**Issue by leonardcj** [ror-community/ror-updates#7656]
Summary of request: Modify the information in an existing ROR record

Name of organization: Anderson University - South Carolina
ROR ID: https://ror.org/01gmrmd93
Which part of the record needs to be changed? ISNI
Description of change:

https://ror.org/03cebjr81
Anderson University - Indiana
https://isni.org/isni/0000000403699160
is unambiguosly
https://en.wikipedia.org/wiki/Anderson_University_(Indiana)

Whereas:
https://ror.org/01gmrmd93
Anderson University - South Carolina
https://en.wikipedia.org/wiki/Anderson_University_(South_Carolina)

has two potential ISNI records, both of which are cross-contaminated by references to Indiana
https://isni.org/isni/0000000404445162 (recorded in ROR)
https://isni.org/isni/0000000405839235 (add to ROR?)

It is unclear what the best path forward might be.  1) Eliminate the confusing ISNI while simultaneously pursuing a clarification via ISNI of the two confused records OR 2) add the second, also confused ISNI to the first OR C) do nothing and wait for ISNI to sort it out. 

There are no really attractive choices until ISNI sorts it out, so this message was submitted against all three ISNI numbers in hopes of eventual clarification.

Update: add.ISNI==0000 0004 0583 9235;$

**Comment by adambuttrick** [comment]
We'll add for now, despite the errant references to Indiana on both of these records. Many services use ISNI as a bridge identifier for ROR (e.g. ORCID), so its best to err on the side of including in these and similar cases.

**Comment by adambuttrick** [comment]
Record updated in release v1.40.
