### ISSUE TITLE
Add a new organization to ROR: Institut de Chimie Moléculaire de l'Université de Bourgogne

### ISSUE THREAD

**Issue by vrameau** [ror-community/ror-updates#7660]
Summary of request: Add a new organization to ROR

Name of organization: Institut de Chimie Moléculaire de l'Université de Bourgogne
Website: http://www.icmub.com
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID:
ISNI ID: 0000 0004 0383 1547
GRID ID:
Crossref Funder ID :
Other names for the organization:
Aliases: Molecular Chemistry Institute of the University of Burgundy
Labels: Institute of Molecular Chemistry of the University of Burgundy*English
Acronym/abbreviation: ICMUB
Related organizations: https://ror.org/03k1bsr36 (parent) https://ror.org/02feahw73 (parent)
City: Dijon
Country: France
Geonames ID: 3021372
Year established: 
How will a ROR ID for this organization be used? The ROR ID will be integrating in the IDREF notice : https://www.idref.fr/159770688
and in the HAL structure notice : https://aurehal.archives-ouvertes.fr/structure/read/id/24496
Other information about this request:

**Comment by adambuttrick** [comment]
Research unit at https://ror.org/03k1bsr36 and part of RNSR reconciliation. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/011ygpb73 in release v1.40.
