### ISSUE TITLE
Add a new organization to ROR: Archéologie, Terre, Histoire, Sociétés

### ISSUE THREAD

**Issue by vrameau** [ror-community/ror-updates#7662]
Summary of request: Add a new organization to ROR

Name of organization: Archéologie, Terre, Histoire, Sociétés
Website: https://artehis.u-bourgogne.fr
Link to publications: 
Organization type: Facility
Wikipedia page:
Wikidata ID: Q51780478
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: ARTéHIS
Aliases: Laboratoire Archéologie, Terre, Histoire, Sociétés; Laboratoire ARTéHIS
Related organizations: https://ror.org/02feahw73 (parent) https://ror.org/03k1bsr36 (parent) https://ror.org/017rnyz40 (parent)
City: Dijon
Country: France
Geonames ID: 3021372
Year established: 
How will a ROR ID for this organization be used? The id ROR will be integrated in the following registers : https://www.idref.fr/078998417; https://aurehal.archives-ouvertes.fr/structure/read/id/184759
Other information about this request: 
Relationships > Parent organizations : [French National Centre for Scientific Research](https://ror.org/02feahw73); [University of Burgundy](https://ror.org/03k1bsr36)

**Comment by adambuttrick** [comment]
Research unit at https://ror.org/03k1bsr36 and part of RNSR reconciliation. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/011hdpx94 in release v1.40.
