### ISSUE TITLE
Modify the information in an existing ROR record: Cold Spring Harbor Laboratory https://ror.org/02qz8b764

### ISSUE THREAD

**Issue by leonardcj** [ror-community/ror-updates#7666]
Summary of request: Modify the information in an existing ROR record

Name of organization: Cold Spring Harbor Laboratory
ROR ID: https://ror.org/02qz8b764
Which part of the record needs to be changed? ISNI
Description of change:
replace
https://isni.org/isni/0000000403873667
appears to be a subordinate unit of
https://isni.org/isni/0000000110881567

Update: replace.ISNI==0000 0001 1088 1567; replace.links==https://www.cshl.edu;$

**Comment by adambuttrick** [comment]
Top-level ISNI correctly identified.

**Comment by adambuttrick** [comment]
Record updated in release v1.40.
