### ISSUE TITLE
Add a new organization to ROR: École des mines d'Alès

### ISSUE THREAD

**Issue by ericjeangirard** [ror-community/ror-updates#7668]
Summary of request: Add a new organization to ROR

Name of organization: École des mines d'Alès
Website: https://www.imt-mines-ales.fr/
Link to publications: https://doi.org/10.1016/j.cej.2020.127399
Organization type: 
Wikipedia page:
Wikidata ID: Q3577938
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: IMT Alès
Labels:
Acronym/abbreviation:
Related organizations: 
City: Alès
Country: France
Geonames ID: 
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Already exists in ROR - https://ror.org/03e8rf594. Will update link and aliases from this request
