### ISSUE TITLE
Add a new organization to ROR: WIN Consortium

### ISSUE THREAD

**Issue by ericjeangirard** [ror-community/ror-updates#7671]
Summary of request: Add a new organization to ROR

Name of organization: WIN Consortium
Website: https://winconsortium.org
Link to publications: 10.1038/s41568-022-00529-3 and others
Organization type: Nonprofit
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 1780 1891
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Worldwide Innovative Networking in Personalized Cancer Medicine
Labels:
Acronym/abbreviation:
Related organizations: 
City: Chevilly-Larue
Country: France
Geonames ID: 3025314
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Cancer research consortium in France. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03r6bpj37 in release v1.40.
