### ISSUE TITLE
Add a new organization to ROR: The Intergovernmental Committee on Surveying (ICSM)and Mapping

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#77]
Summary of request: Add a new organization to ROR

Name of organization: The Intergovernmental Committee on Surveying (ICSM) and Mapping
Website: https://www.icsm.gov.au
Link to publications:  10.1007/s001900050096; 10.13140/RG.2.2.28678.40001; 10.13140/RG.2.2.36706.27843; 10.1080/08120099.2018.1412353; 10.1080/00277738.2020.1731243;
Wikipedia page: https://en.wikipedia.org/wiki/ANZLIC; https://en.wikipedia.org/wiki/Surveying_in_Australia
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: 
Country: 
Other information about this request: Obtaining a ROR ID is very important to assist  the Modernisation of the Foundation Spatial Data Framework program (https://www.anzlic.gov.au/anzlic-council/anzlic-strategic-plan-2020-24)

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/03pep4w33 in release v1.0.
