### ISSUE TITLE
Project: Euro-Bioimaging Nodes

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#778]
#777 exposed several imaging facilities as part of its research infrastructure that are likely in scope for ROR. We should evaluate to what extent they are already represented and determine whether those absent are in scope for the registry:

https://www.eurobioimaging.eu/about-us/eurobioimaging-nodes

**Comment by 44sth4** [comment]
Hello @adambuttrick, 
I am the data services coordinator at Euro-BioImaging and the one who put in the request for the ROR-ID. I find your discussion about including Euro-BioImaging Nodes, pretty spot on as this is a common problem our facilities face. Is this a use-case you are looking to work on? I am happy to support you in the process, provide information and mediate communication to our facilities, etc.

**Comment by adambuttrick** [comment]
@44sth4 Thanks for your offer of assistance! In the past few months, we have expanded our scope to be more inclusive of facility output tracking. We still do enforce some qualifiers that would likely not affect  Euro-Bioimaging (e.g. university facilities are generally not included, but joint facility ventures between various research organizations would be in scope). We're currently in the process of prepping our next release, but I can reach out to coordinate further next week.

**Comment by adambuttrick** [comment]
@44sth4 I have completed my initial review. Please see here for details and feel free to provide additional comments/context:

https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing


The amount of variation from node to node in terms of their status as organizations (in ROR's sense of the term) would make it difficult to add all of these nodes to the registry. Some appear to be sub-units of existing records (e.g. Austrian BioImaging CMI looks to be a sub-entity of the Vienna BioCenter Core Facilities - https://ror.org/01w64ht88), others already exist in the registry under their primary names (e.g. Sofia BioImaging Node I believe is the Institute of Molecular Biology - https://ror.org/00t7c6f62). Some of these nodes do need to be added because they qualify for the registry, independent of their involvement with Euro-Bioimaging. Others, however, seem to lack the solidity/structure to qualify, or are effectively projects (e.g. Grand Challenges) and are thus out of scope for ROR.

My recommendation for now would be to add those organizations that are clearly in scope, create relationships between their records and that for Euro-Bioimaging, as well as potentially add aliases corresponding to how these organizations are referenced in the context of Euro-Bioimaging.

I'm also going to ask a few of my curation team colleagues to review and provide their thoughts. @MSpenger @arthurpsmith @nlundvick Could you take a look?

**Comment by nlundvick** [comment]
Hi @adambuttrick - I was able to review some of these today and I added comments to the spreadsheet. Will continue to review as time allows.

**Comment by nlundvick** [comment]
Hi @adambuttrick - I completed my first pass through. Would like to do a quick run through these again to make sure my logic is consistent throughout (had to do some jumping back and forth between the nodes). Will do that early next week. Hope you have an awesome holiday weekend!

**Comment by adambuttrick** [comment]
Thanks so much @nlundvick! Really appreciate all your work on this!

**Comment by 44sth4** [comment]
Hi @adambuttrick and @nlundvick . Thanks so much for this wonderful work. 
I had a question about the nomenclature of the "relation" you would use between Euro-BioImaging and their Nodes. As I understand three relations currently implemented (Parent, Child, Related). I guess "related" would be relation of choice?
And as a way to support the process, we can have a look at it with our team comment on the cases that are unclear.
For the clear cases, can they simply be added or one needs to contact a potential submitter or owner of a ROR request?

**Comment by adambuttrick** [comment]
@44sth4 We can defer to what you think is appropriate for the relationships between Euro-BioImaging and its nodes, based on the organization's internal structure. Generally speaking, parent-child relationships are used where some hierarchy exists between organizations, e.g. the parent governs over its children in some fashion, whereas related is for non-hierarchical/cooperative efforts.

We can add the clear cases, no need for any additional submission. If there are questions about metadata for any of the individual organizations, I will reach out to you accordingly.

**Comment by nlundvick** [comment]
Hi @adambuttrick - I completed my review of the nodes. In the spreadsheet I added a column with my recommendation and another column with my review comment.

[https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1dn7oSsNPil86_dCLa6xoKL6huUtCAIVZf-ibFqV9ndc/edit?usp=sharing)

Please let me know if you have any questions.

**Comment by adambuttrick** [comment]
Thanks @nlundvick! Will review!

**Comment by adambuttrick** [comment]
All records created except for one hold for later request, so closing this out.
