### ISSUE TITLE
Project: New Records from Long Tail Funder Registry Reconciliation

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#7784]
As part of https://github.com/ror-community/ror-updates/issues/2620, @hnew1 has identified a set of new records that should be added to the registry. These should be reviewed and improved for completeness of metadata.
[20240103_funder_registry_new_records.xlsx](https://github.com/ror-community/ror-updates/files/13822747/20240103_funder_registry_new_records.xlsx)

**Comment by hnew1** [comment]
All child issues checked/edited and added to metadata QA/sign off column.

**Comment by adambuttrick** [comment]
All records added in release v1.41.
