### ISSUE TITLE
Add a new organization to ROR: NIHR Biomedical Research Centre, Royal Marsden NHS Foundation Trust/Institute of Cancer Research

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#7794]
Summary of request: Add a new organization to ROR

Name of organization:  NIHR Biomedical Research Centre at The Royal Marsden and the ICR
Website: https://www.cancerbrc.org
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 100014461
Other names for the organization: 
Aliases: BRC; NIHR Royal Marsden Biomedical Research Centre; National Institute for Health Research Biomedical Research Centre; NIHR Biomedical Research Centre at The Royal Marsden NHS Foundation Trust and The Institute of Cancer Research; NIHR BRC at The Royal Marsden and the ICR; Biomedical Research Centre for Cancer; NIHR Biomedical Research Centre at The Royal Marsden and The Institute of Cancer Research; NIHR Biomedical Research Centre, Royal Marsden NHS Foundation Trust/Institute of Cancer Research; Royal Marsden BRC
Labels: 
Acronym/abbreviation: NIHR BRC 
Related organizations: https://ror.org/0187kwz08 (parent) https://ror.org/043jzw605 (parent)
City: London
Country: United Kingdom
Geonames ID: 2643743
Year established: 
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of long tail funder reconciliation on #7784.

**Comment by hnew1** [comment]
Needs review - possibly more than one organisation.

**Comment by adambuttrick** [comment]
@hnew1 This appears to be one institute that is a joint research facility between the The Royal Marsden Foundation and the Institute for Cancer Research London. Site is here: https://www.cancerbrc.org/. You can just update to reflect the details of the site. Name should be NIHR Biomedical Research Centre at The Royal Marsden and the ICR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/014ktry78 in release v1.41.
