### ISSUE TITLE
Add a new organization to ROR: Chemical Sciences, Geosciences, and Biosciences Division

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#7800]
Summary of request: Add a new organization to ROR

Name of organization: Chemical Sciences, Geosciences, & Biosciences Division
Website: https://science.osti.gov/bes/csgb
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 100013145
Other names for the organization: 
Aliases: Chemical Sciences, Geosciences, and Energy Biosciences; CSGB Division; Chemical Sciences, Geosciences, & Biosciences (CSGB) Division; Chemical Sciences, Geosciences, and Biosciences Division
Labels: 
Acronym/abbreviation: CSGB
Related organizations: https://ror.org/00mmn6b08 (parent)
City: Washington D.C.
Country: United States
Geonames ID: 4140963
Year established: 
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of long tail funder reconciliation on #7784.

**Comment by adambuttrick** [comment]
DOE is separately correcting all the records related to their funding offices, so flagging for their review before adding. @carlyrobinson Can you weigh in on whether this should be added?

**Comment by carlyrobinson** [comment]
At this point, we're not planning to go to this level of granularity with the DOE hierarchy. We are currently stopping at the level above this division (stopping at DOE, Office of Science, Office of Basic Energy Sciences).

**Comment by adambuttrick** [comment]
@carlyrobinson Great! Thank you for reviewing!
