### ISSUE TITLE
Add a new organization to ROR: Bioenergy Technologies Office

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#7814]
Summary of request: Add a new organization to ROR

Name of organization: Bioenergy Technologies Office
Website: 
Link to publications: 
Organization type:
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 100011735
Other names for the organization: 
Aliases: U.S. Department of Energy Bioenergy Technologies Office; DOE Bioenergy Technologies Office; BETO
Labels: 
Acronym/abbreviation: 
Related organizations: https://ror.org/02ssawd58 (parent)
City: 
Country: United States
Geonames ID: 
Year established: 
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of long tail funder reconciliation on #7784. Bioenergy Technologies Office. Should be added. Parent org https://ror.org/02xznz413

**Comment by hnew1** [comment]
@adambuttrick Correction: rather than new record creation, Funder ID (http://dx.doi.org/10.13039/100011735) should be added to existing record (https://ror.org/01qrpsa36 - missing Funder ID)
