### ISSUE TITLE
Add a new organization to ROR: Wind Energy Technologies Office

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#7842]
Summary of request: Add a new organization to ROR

Name of organization: Wind Energy Technologies Office
Website: 
Link to publications: 
Organization type:
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 100011030
Other names for the organization: 
Aliases: EERE/WETO; WETO; Office of Energy Efficiency and Renewable Energy Wind Energy Technologies Office; EERE Wind Energy Technologies Office
Labels: 
Acronym/abbreviation: 
Related organizations: https://ror.org/00p6app11 (parent)
City: 
Country: United States
Geonames ID: 
Year established: 
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of long tail funder reconciliation on #7784. Wind Energy Technologies Office. Should be added.  Parent record https://ror.org/02xznz413

**Comment by hnew1** [comment]
@adambuttrick Correction - ROR record already exists (https://ror.org/01qvmna33)

**Comment by adambuttrick** [comment]
@hnew1 Thanks for catching. For any duplicates like this you find, you can just comment as much, remove the triage label, close the issue, and then move to the "Declined Requests" project column.
