### ISSUE TITLE
Add a new organization to ROR: NERC Environmental Bioinformatics Centre

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#7859]
Summary of request: Add a new organization to ROR

Name of organization: NERC Environmental Bioinformatics Centre
Website: http://bioinfo-core.org/index.php/NERC_Environmental_Bioinformatics_Centre
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: Q30264588
ISNI ID: 
GRID ID: 
Crossref Funder ID: 100008668
Other names for the organization: 
Aliases: Environmental Bioinformatics Centre; 
Labels: NEBC
Acronym/abbreviation: 
Related organizations:  https://ror.org/00pggkr55
City: Wallingford
Country: United Kingdom
Geonames ID: 2634869
Year established: 2005
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of long tail funder reconciliation on #7784. NERC Environmental Bioinformatics Centre

**Comment by hnew1** [comment]
Organisation record already exists: https://ror.org/03rjhjc18

**Comment by hnew1** [comment]
Organisation record already exists: https://ror.org/03rjhjc18
