### ISSUE TITLE
Add a new organization to ROR: Building Technologies Office

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#7868]
Summary of request: Add a new organization to ROR

Name of organization: Building Technologies Office
Website: https://www.energy.gov/eere/buildings/building-technologies-office
Link to publications: 
Organization type: Government
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 100011682
Other names for the organization: 
Aliases: The Building Technologies Office; U.S. Department of Energy's Building Technologies Office; BTO; EERE Building Technologies Office; DOE Building Technologies Office;
Labels: BTO
Acronym/abbreviation: 
Related organizations: https://ror.org/02xznz413 (parent)
City: Washington, DC
Country: United States
Geonames ID: 4140963
Year established: 
How will a ROR ID for this organization be used? To identify research funders.
Other information about this request: Part of long tail funder reconciliation on #7784. Building Technologies Office. Should be added.  Parent organisation https://ror.org/02xznz413

**Comment by hnew1** [comment]
Already exists in ROR: https://ror.org/01wqtde93
Add Funder ID to record

**Comment by adambuttrick** [comment]
Already assigned to record, so fine to close.
