### ISSUE TITLE
Modify the information in an existing ROR record: University Institute of Lisbon https://ror.org/014837179

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#789]
Summary of request: Modify the information in an existing ROR record

Name of organization: University Institute of Lisbon
ROR ID: https://ror.org/014837179
Which part of the record needs to be changed? primary name, website
Description of change:  (1) Move `pt` label `Iscte – Instituto Universitário de Lisboa` to primary name; (2) Update website to https://www.iscte-iul.pt/

Update: change.name==Iscte – Instituto Universitário de Lisboa; delete.label==Iscte – Instituto Universitário de Lisboa; replace.links==https://www.iscte-iul.pt;$

**Comment by mariagould** [comment]
We made some adjustments to the organization name in v1.0 (see #60) but we did not accurately represent the official name of the organization, which needs to be in Portuguese per guidance from the organization.

**Comment by adambuttrick** [comment]
Waiting on organization to identify proper capitalization for "Iscte" prefix.
