### ISSUE TITLE
Add a new organization to ROR: USGS Woods Hole Coastal and Marine Science Center Samples Repository

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#79]
Summary of request: Add a new organization to ROR

Name of organization: USGS Woods Hole Coastal and Marine Science Center Samples Repository
Website: https://www.usgs.gov/centers/whcmsc/labs/samples-repository
Link to publications: https://doi.org/10.5066/F7319TT0, https://doi.org/10.3133/ofr20181100 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: https://ror.org/035a68863 (parent)
City: 
Country: 
Other information about this request: I was asked to include our repository in a directory of public repositories of geoscience samples and data. Entries in the directory are asked to include an ROR for their facilities.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02pv64t29 in release v1.0.
