### ISSUE TITLE
Add record: Arnold Arboretum

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#8]
Description: Add Arnold Arboretum

This request came from Dryad. ROR forwarded to GRID but it was not in scope for inclusion in GRID. Therefore it has been held in the ROR backlog until ROR can make independent updates.

Because this is a legacy issue, there is no form data for this request and therefore all of the metadata for the new record needs to be generated from scratch.

Related organizations: https://ror.org/03vek6s52 (parent)

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05xsxgs79 in release v1.0.
