### ISSUE TITLE
Modify the information in an existing ROR record: Indian Institute for Research in Numismatic Studies https://ror.org/0455mxm38

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#8017]
Summary of request: Modify the information in an existing ROR record

Name of organization: Indian Institute for Research in Numismatic Studies
ROR ID: https://ror.org/0455mxm38
Which part of the record needs to be changed? Name, aliases, website
Description of change: The website http://www.inhcrf.org/Public/Include/Home.aspx is inactive and should be changed, but in general it also looks to me as though the record might need to be renamed "Indian Numismatic, Historical and Cultural Research Foundation" whose website is http://www.inhcrf.org/. The INHCRF runs the Money Museum with aliases "Nane Sangrahalaya (Coin Museum)" and "Shanti-Krishna Museum of Money & History" according to the INHCRF website. Depending on what affiliation usage is like, the record might need to be split into a parent record and a separate record for the Money Museum.

Update: change.name==Indian Numismatic, Historical and Cultural Research Foundation; add.aliases==Indian Institute for Research in Numismatic Studies; replace.links==http://www.inhcrf.org; add.aliases==Nane Sangrahalaya (Coin Museum); add.aliases==Shanti-Krishna Museum of Money & History; add.aliases==Shanti-Krishna Museum of Money and History;$

**Comment by adambuttrick** [comment]
Name change corresponds to organization's site and branding. Link provided is the top-level domain of the existing. The museum does not appear to operate as an independent entity from the broader association, so adding as aliases.

**Comment by adambuttrick** [comment]
Record updated in release v1.40.
