### ISSUE TITLE
Modify the information in an existing ROR record: Arctic Sciences https://ror.org/02trddg58

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#8020]
Summary of request: Modify the information in an existing ROR record

Name of organization: Arctic Sciences
ROR ID: https://ror.org/02trddg58
Which part of the record needs to be changed? Website
Description of change: Website in record 404s: current website is https://www.nsf.gov/geo/opp/arctic/index.jsp 

Update: replace.links==https://www.nsf.gov/geo/opp/arctic/; add.aliases==Office of Polar Programs Arctic Sciences; add.aliases==OPP Arctic Sciences; add.Wikidata==Q30299866;$

**Comment by adambuttrick** [comment]
Link provided is that for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.40.
