### ISSUE TITLE
Modify the information in an existing ROR record: Antarctic Sciences https://ror.org/05fnzca26

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#8021]
Summary of request: Modify the information in an existing ROR record

Name of organization: Antarctic Sciences 
ROR ID: https://ror.org/05fnzca26
Which part of the record needs to be changed? Website
Description of change: Website in record 404s: current website is https://www.nsf.gov/geo/opp/ant/index.jsp 

Update: replace.links==https://www.nsf.gov/geo/opp/ant/; add.aliases==OPP Antarctic Sciences; add.aliases==Office of Polar Programs Antarctic Sciences Section; add.aliases==Office of Polar Programs Antarctic Sciences; add.Wikidata==Q30299863;$

**Comment by adambuttrick** [comment]
Record updated in release v1.40.
