### ISSUE TITLE
Modify the information in an existing ROR record: Arctic Athabaskan Council https://ror.org/020cbcj98

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#8022]
Summary of request: Modify the information in an existing ROR record

Name of organization: Arctic Athabaskan Council
ROR ID: https://ror.org/020cbcj98
Which part of the record needs to be changed? Website
Description of change: Website in record 404s: current website is https://arcticathabaskancouncil.com

Update: replace.links==https://arcticathabaskancouncil.com; add.Wikidata==Q30263298;$

**Comment by adambuttrick** [comment]
Link provided is that for the organization.

**Comment by adambuttrick** [comment]
Record updated in release v1.40.
