### ISSUE TITLE
Modify the information in an existing ROR record: Arctic Submarine Laboratory https://ror.org/01dwp8348

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#8023]
Summary of request: Modify the information in an existing ROR record

Name of organization: Arctic Submarine Laboratory
ROR ID: https://ror.org/01dwp8348
Which part of the record needs to be changed? Website
Description of change: Website in record 404s; current website appears to be https://www.sublant.usff.navy.mil/ASL/ 

Update: replace.links==https://www.sublant.usff.navy.mil/ASL/; add.aliases==United States Navy Arctic Submarine Laboratory; add.aliases==U.S. Navy Arctic Submarine Laboratory;$

**Comment by adambuttrick** [comment]
Record updated in release v1.40.
