### ISSUE TITLE
Modify the information in an existing ROR record: Valentine https://ror.org/0262sec15

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#8024]
Summary of request: Modify the information in an existing ROR record

Name of organization: Valentine
ROR ID: https://ror.org/0262sec15
Which part of the record needs to be changed? Name
Description of change: The organization's website makes it clear that the museum is generally referred to as "The Valentine." My grandmother and aunt volunteered here for years and they always called it "The Valentine" or "The Valentine Museum." See e.g. https://doi.org/10.1177/009614429502100302

Update: change.name==The Valentine; add.aliases==Valentine; add.aliases==The Valentine Museum; add.Wikidata==Q7911006; replace.links==https://thevalentine.org;$

**Comment by adambuttrick** [comment]
Name provided corresponds to organization's site and branding.

**Comment by adambuttrick** [comment]
Record updated in release v1.40.
