### ISSUE TITLE
Add a new organization to ROR: National Transportation Library

### ISSUE THREAD

**Issue by tvrdy-ctr** [ror-community/ror-updates#8037]
Summary of request: Add a new organization to ROR

Name of organization: National Transportation Library
Website: https://ntl.bts.gov
Link to publications: https://doi.org/10.21949/1398953
Organization type: Government; Archive
Wikipedia page: https://en.wikipedia.org/wiki/National_Transportation_Library
Wikidata ID: Q6979017
ISNI ID: 0000 0004 0639 4055
GRID ID: 
Crossref Funder ID: 
Other names for the organization:
Aliases: U.S. Department of Transportation National Transportation Library; United States Department of Transportation National Transportation Library
Labels:
Acronym/abbreviation: NTL
Related organizations: https://ror.org/05xfdey77 (parent)
City: Washington, D.C.
Country: United States of America
Geonames ID: 4140963
Year established: 1998
How will a ROR ID for this organization be used?: To connect group outputs of NTL as an official organization separate from the Department of Transportation and Bureau of Transportation Statistics. Further, the National Transportation Library operates the Repository & Open Science Access Portal (ROSA P), as the official repository for all US DOT created and funded scientific research. 
Other information about this request:

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00snbrd52 in release v1.40.
