### ISSUE TITLE
Add a new organization to ROR: Federal Motor Carrier Safety Administration

### ISSUE THREAD

**Issue by tvrdy-ctr** [ror-community/ror-updates#8038]
Name of organization: Federal Motor Carrier Safety Administration
Website: https://www.fmcsa.dot.gov
Link to publications: https://rosap.ntl.bts.gov/collection_fmcsa
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Federal_Motor_Carrier_Safety_Administration
Wikidata ID: Q5440305
ISNI ID: 0000 0001 2230 9621
GRID ID:
Crossref Funder ID: 100006286
Other names for the organization:
Acronym/abbreviation: FMCSA
Aliases:
Labels:
Related organizations: https://ror.org/02xfw2e90 (parent)
City: Washington, D.C.
Country: United States of America
Geonames ID: 4140963
Year established: 2000
How will a ROR ID for this organization be used?: To unambiguously identify FMCSA outputs from among other US DOT research and other Federal Agencies.
Other information about this request

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/01jt5mq34 in release v1.40.
