### ISSUE TITLE
Add a new organization to ROR: Pipeline and Hazardous Materials Safety Administration

### ISSUE THREAD

**Issue by tvrdy-ctr** [ror-community/ror-updates#8039]
Summary of request: Add a new organization to ROR

Name of organization: Pipeline and Hazardous Materials Safety Administration
Website: https://www.phmsa.dot.gov
Link to publications:  https://rosap.ntl.bts.gov/collection_phmsa
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Pipeline_and_Hazardous_Materials_Safety_Administration
Wikidata ID: Q7197274
ISNI ID: 0000 0000 9566 3376
GRID ID: 
Crossref Funder ID: 100006284
Other names for the organization: 
Acronym/abbreviation: PHMSA
Related organizations: United States Department of Transportation
City: Washington, D.C.
Country: United States of America
Geonames ID: 4140963
Year established: 2004
How will a ROR ID for this organization be used? To unambiguously identify PHMSA outputs from among other US DOT research and other Federal Agencies
Other information about this request:

**Comment by adambuttrick** [comment]
U.S. state agency. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00dqsq280 in release v1.40.
