### ISSUE TITLE
Add a new organization to ROR: Bureau of Transportation Statistics

### ISSUE THREAD

**Issue by tvrdy-ctr** [ror-community/ror-updates#8040]
Summary of request: Add a new organization to ROR

Name of organization: Bureau of Transportation Statistics
Website: https://www.bts.gov
Link to publications: https://rosap.ntl.bts.gov/collection_bts_products 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/Bureau_of_Transportation_Statistics
Wikidata ID: Q4998432
ISNI ID: 0000 0001 1090 3893
GRID ID: 
Crossref Funder ID: 100014820
Other names for the organization: 
Acronym/abbreviation: BTS
Related organizations: https://ror.org/02xfw2e90 (parent)
City: Washington, D.C.
Country: United States of America
Geonames ID: 4140963
Year established: 1992
How will a ROR ID for this organization be used? To unambiguously identify  BTS Products from among other US DOT research and other Federal Statistical Agencies 
Other information about this request:

**Comment by adambuttrick** [comment]
U.S. state agency. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05xfdey77 in release v1.40.
