### ISSUE TITLE
Add a new organization to ROR: University Transportation Centers Program

### ISSUE THREAD

**Issue by tvrdy-ctr** [ror-community/ror-updates#8041]
Summary of request: Add a new organization to ROR

Name of organization: University Transportation Centers Program
Website: https://www.transportation.gov/content/university-transportation-centers
Link to publications: https://rosap.ntl.bts.gov/collection_utcp 
Organization type: Government
Wikipedia page: https://en.wikipedia.org/wiki/University_Transportation_Centers_Program
Wikidata ID: Q7894968
ISNI ID: 0000 0004 8307 3191
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Acronym/abbreviation: UTC
Related organizations: https://ror.org/0150hkx05 (parent)
City: Washington, D.C.
Country: United States of America
Geonames ID: 4140963
Year established: 1987
How will a ROR ID for this organization be used? To unambiguously identify UTC funded research products and outputs from other USDOT research offices’ research outputs. The UTC program funds millions of dollars worth of university transportation research each year, much of which appears in peer-reviewed journals.  A ROR ID will also be vital for proper attribution and citation, as well as funder metrics tracking.
Other information about this request:

**Comment by adambuttrick** [comment]
Research program under the US DOT Office of the Assistant Secretary for Research and Technology. While we have some precedence for these U.S. government research programs (e.g. https://ror.org/03g2zjp07), it would be good to understand to what extent this operates separately from the Office of the Assistant Secretary for Research and Technology (e.g. does it have its own staff). There does appear to be a management component related to coordinating and creation of new centers, but this should be more broadly reviewed in the context of funding programs vs. funding organizations in context of the Funder Registry transition.

**Comment by tvrdy-ctr** [comment]
The University Transportation Center program is one of many offices currently organized under the US DOT Office of Assistant Secretary for Research and Technology. However, this is not necessarily a permanent location within the DOT hierarchy. In it's earliest iteration the program was part of the Federal Highway Administration at US DOT. The administrative management of the UTC program was later moved from FHWA to OST-R. However, the independent functions and the staff of the UTC program remained the same. The UTC program has its own staff, and its own chunk of the DOT research budget to award, through its own review process. The home office of the UTC program could change again in the future, in no way that would impact its function or its role in funding research. We feel strongly that in order to correctly attribute UTC-funded research to the correct office in DOT, that the UTC program should have a ROR ID separate from the OST-R office, as the UTC office has its own identity with US DOT research overall. Thank you!

**Comment by tvrdy-ctr** [comment]
If you have any questions, feel free to reach out to leighton.christiansen@dot.gov and myself (peyton.tvrdy.ctr@dot.gov)

**Comment by adambuttrick** [comment]
@tvrdy-ctr Thanks for these clarifications! This is very helpful. I'm going to have other of my curation team colleague's review, so that we have consensus and documentation around the appropriate threshold for creating records in such circumstances. As you might imagine, other programs under review have different circumstances, are of a more ephemeral or of a term-limited nature, such that we have to be somewhat cautious in how we integrate.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02jf59s11 in release v1.40.
