### ISSUE TITLE
Add a new organization to ROR: USDOT Intelligent Transportation Systems Joint Program Office (ITSJPO) Research Program

### ISSUE THREAD

**Issue by tvrdy-ctr** [ror-community/ror-updates#8042]
Summary of request: Add a new organization to ROR

Name of organization: Intelligent Transportation Systems Joint Program Office
Website: https://www.its.dot.gov
Link to publications: https://rosap.ntl.bts.gov/collection_itsjpo
Organization type: Government
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: ITSJPO
Aliases: USDOT Intelligent Transportation Systems Joint Program Office; ITS Joint Program Office
Labels:
Related organizations: https://ror.org/0150hkx05 (parent)
City: Washington D.C.
Country: United States
Geonames ID: 4140963
Year established: 1994
How will a ROR ID for this organization be used?:  To unambiguously identify ITSJPO outputs from among other US DOT research and other Federal Agencies. The ITSJPO is responsible for much of the most cutting-edge research conducted at US DOT, including automated vehicles and smart infrastructure.
Other information about this request:

**Comment by adambuttrick** [comment]
We would add at the level of the office vs. its programs. This also requires representation of an intermediary USDOT office, which I've added with https://github.com/ror-community/ror-updates/issues/8047. Otherwise, Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/012cshy85 in release v1.40.
