### ISSUE TITLE
Modify the information in an existing ROR record: Instituto Tecnológico de Oaxaca https://ror.org/03s3m8k31

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#8122]
Summary of request: Modify the information in an existing ROR record

Name of organization: Instituto Tecnológico de Oaxaca
ROR ID: https://ror.org/03s3m8k31
Which part of the record needs to be changed? Website
Description of change: The website http://www.itoaxaca.edu.mx/web/ 404s and should be changed to http://www.itoaxaca.edu.mx/ 

Update: replace.links==http://www.itoaxaca.edu.mx;$

**Comment by adambuttrick** [comment]
Record updated in release v1.41.
