### ISSUE TITLE
Modify the information in an existing ROR record: Leibniz University Hannover https://ror.org/0304hq317

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#8130]
Summary of request: Modify the information in an existing ROR record

Name of organization: Leibniz University Hannover 
ROR ID: https://ror.org/0304hq317
Which part of the record needs to be changed? Aliases and/or status
Description of change: Reportedly the current institution called Leibniz University Hannover https://ror.org/0304hq317 used to be called "Technische Universität Hannover". Depending on whether this is just a name change or something more substantive, the name Technische Universität Hannover should be added to aliases and/or a new Successor record created. 

Update: add.aliases==Technische Universität Hannover; add.aliases==Technische Hochschule Hannover; add.aliases==Universität Hannover; replace.links==https://www.uni-hannover.de;$

**Comment by adambuttrick** [comment]
From the [university's history page](https://www.uni-hannover.de/en/universitaet/profil/geschichte/stichworte), the primary former names are "Technische Universität Hannover" and "Technische Hochschule Hannover." 

The university also operated under the name  "Königliche Technische Hochschule," but the only affiliation usage for this is an unrelated university in Sweden (https://doi.org/10.1007/bf01948690), so I don't think it makes sense to add. Likewise, the historic name "Höhere Gewerbeschule zu Hannover" appears to have only been used before it was a college.

**Comment by adambuttrick** [comment]
Record updated in release v1.41.
