### ISSUE TITLE
Modify the information in an existing ROR record: CASRAI https://ror.org/01fhm2133

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#8131]
Summary of request: Modify the information in an existing ROR record

Name of organization: CASRAI
ROR ID: https://ror.org/01fhm2133
Which part of the record needs to be changed? Status
Description of change: The CASRAI record should be marked Inactive, because according to reports the organization closed in 2021 or so and the website casrai.org has been taken over by a domain squatter. Cf. https://eurocris.org/casrai-domain-handover and https://web.archive.org/web/20210813083158/https://casrai.org/ 

Update: change.status==inactive; delete.links== http://casrai.org/;$

**Comment by adambuttrick** [comment]
Record updated in release v1.41.
