### ISSUE TITLE
Add a new organization to ROR:  Digital Repository of Ireland

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#83]
Summary of request: Add a new organization to ROR

Name of organization: Digital Repository of Ireland
Website: https://www.dri.ie/

Link to publications: Wellcome Grant id 220151/Z/20/Z (https://wellcome.org/grant-funding/people-and-projects/grants-awarded/digital-preservation-reproductive-health-resources).
Reports from previous research projects: https://doi.org/10.7486/DRI.sx61t2042, https://doi.org/10.7486/DRI.pz50w9969, https://doi.org/10.7486/DRI.qz216736v, https://doi.org/10.7486/DRI.pr76tj28w-1.
Other reports: https://doi.org/10.7486/DRI.qj732p00f, https://doi.org/10.7486/DRI.qb990w327, https://doi.org/10.7486/DRI.5m614676f-1.
Oral History recordings and transcripts from the Atlantic Philanthropies project: https://doi.org/10.7486/DRI.0c48h625z
Academic publications - book chapters, conference papers, journal papers (note: these may not all have the Digital Repository of Ireland as an author affiliation, as the DRI is a consortium including several institutes): https://doi.org/10.4324/9781315575278, https://doi.org/10.1109/IWSG.2015.17, https://www.scopus.com/inward/record.uri?eid=2-s2.0-84959895938&partnerID=40&md5=87f7e82b3da457b51b374dec20dc6bc9, https://doi.org/10.1080/13614576.2015.1114838, https://doi.org/10.1080/13614576.2015.1110398, https://doi.org/10.1108/OIR-01-2015-0031

Wikipedia page: https://en.wikipedia.org/wiki/Digital_Repository_of_Ireland
Wikidata ID: https://www.wikidata.org/wiki/Q47461569
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: Taisclann Dhigiteach na hÉireann
Acronym/abbreviation: DRI
Related organizations: DRI consortium members: https://ror.org/02tyrky19, https://ror.org/048nfjm95, https://ror.org/019tbdj08
City: Royal Irish Academy, 19 Dawson Street, Dublin 2, Ireland
Country: 

Other information about this request: The Digital Repository of Ireland is a Trustworthy Digital Repository for Ireland's Humanities and Social Science data. In addition to offering long-term preservation of data from Irish researchers we also participate directly in research projects and infrastructures projects including a research component. Current projects include the Wellcome Trust funded "Digital Preservation of Reproductive Health Resources: Archiving the 8th" project and the upcoming CEF-funded EnrichEuropeana+ project due to start in April. We publish in journals and conference proceedings, as well as publishing a range of guidelines on best practice for research data management and other topics relating to Research Data and Digital Preservation.

**Comment by carlyrobinson** [comment]
Agree that the Digital Repository of Ireland fits the criteria and should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/034d7ma87 in release v1.0.
