### ISSUE TITLE
Add a new organization to ROR: State Key Laboratory of Automobile Simulation and Control

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#8329]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: State Key Laboratory of Automotive Simulation and Control
Website: http://www.ascl.jlu.edu.cn
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 501100011234
Other names for the organization: 
Aliases: State Key Lab of Automotive Simulation and Control; State Key Laboratory of Automobile Simulation and Control; State Key Lab of Automobile Simulation and Control; 汽车动态模拟国家重点实验室
Acronym/abbreviation: 
Labels: 汽车仿真与控制国家重点实验室*Chinese
Related organizations: https://ror.org/00js3aw79 (parent) 
City: Changchun
Country: China
Geonames ID: 2038180
Year established: 
Other information about this request: Part of #8123. Supporting units: Jilin University.

**Comment by adambuttrick** [comment]
@huangjqq This was submitted with #8392 as its inactive predecessor organization. Although they have different names in Chinese, I'm wondering if they were truly distinct from each other, given that they are in the same place, links, and have the same parent. Could you take a look?

**Comment by huangjqq** [comment]
They are the same org, different name -- official government notice here: https://www.most.gov.cn/xxgk/xinxifenlei/fdzdgknr/qtwj/qtwj2010before/201101/t20110107_84111.html

Government source also gives State Key Laboratory of Automotive Simulation and Control (not Automobile) as the official English  name, confirmed by English version of lab website.

**Comment by adambuttrick** [comment]
Closed https://github.com/ror-community/ror-updates/issues/8392 as a duplicate and moving to release queue.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00b67z867 in release v1.43.
