### ISSUE TITLE
Add a new organization to ROR: State Key Laboratory of Quantum Optics and Quantum Optics Devices

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#8393]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: State Key Laboratory of Quantum Optics and Quantum Optics Devices
Website: http://sklqo.sxu.edu.cn
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: State Key Lab of Quantum Optics and Quantum Optics Devices
Acronym/abbreviation: 
Labels: 量子光学与光量子器件国家重点实验室*Chinese
Related organizations: https://ror.org/03y3e3s17 (parent) 
City: Taiyuan
Country: China
Geonames ID: 1793511
Year established: 
Other information about this request: Part of #8123. Supporting units: Shanxi University.

**Comment by adambuttrick** [comment]
@huangjqq This was submitted with #8279 as its inactive predecessor organization. Although they have different names in Chinese, I'm wondering if they were truly distinct from each other, given that they are in the same place, links, and have the same parent. Could you take a look?

**Comment by huangjqq** [comment]
They just switched up the Chinese character used for "and" -- these are the same. I'm pretty sure 8279 has the correct current Chinese name form, though.

**Comment by adambuttrick** [comment]
Updating label and closing https://github.com/ror-community/ror-updates/issues/8279 as a duplicate, per curator review.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/035z18f46 in release v1.43.
