### ISSUE TITLE
Add a new organization to ROR: Minnesota Geological Survey

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#84]
Summary of request: Add a new organization to ROR

Name of organization: Minnesota Geological Survey
Website: https://cse.umn.edu/mgs
Link to publications: https://hdl.handle.net/11299/708
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: MGS
Related organizations: University of Minnesota https://ror.org/017zqws13 (parent)
City: 2609 Territorial Road, St. Paul MN 55114
Country: 
Other information about this request: We store and curate important geological samples and data for the State of Minnesota. This ID will be used in a directory of public repositories for geological samples that is currently being organized.

**Comment by mariagould** [comment]
Relationships:

https://ror.org/017zqws13, parent

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/034ebnm46 in release v1.0.
