### ISSUE TITLE
Add a new organization to ROR: Manipal University Jaipur

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#843]
Summary of request: Add a new organization to ROR

Name of organization: Manipal University Jaipur
Website: https://jaipur.manipal.edu
Link to publications: 
Organization type: Education
Wikipedia page: https://en.wikipedia.org/wiki/Manipal_University_Jaipur
Wikidata ID: Q17071873
ISNI ID: 0000 0004 4661 2475
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation: MUJ
Related organizations: https://ror.org/02xzytt36 (related)
City: Jaipur
Country: India
Geonames ID: 1269515
Year established: 2011
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by mariagould** [comment]
Concur this should be added to ROR based on publications and similar entries already in ROR.

**Comment by hcshipra** [comment]
Dear team, 
 My researcher ids for verification
These are my researcher  Id
Researcher Identified: 
    ResearcherID: http://www.researcherid.com/rid/H-4739-2014/E-5126-2011
   ORCID iD: http://orcid.org/0000-0002-1296-8970              
 Scopus Profile: http://www.scopus.com/authid/detail.url?authorId=54384313700
   Google Scholar Profile: https://scholar.google.com/citations?hl=en&user=YzhX3dMAAAAJ analytics code: (UA-56082180-2)
 ResearchGate Profile: http://www.researchgate.net/profile/Shiva_Prasad_H_C 
  LiveDNA is 91.12161
   http://econpapers.repec.org/RAS/ppr371.htm
   SSRN, Author ID: 2112353  
    https://www.manipal.pure.elsevier.com/admin/Id: 8823368   
  https://figshare.com/authors/SHIVA_PRASAD_H_C/4802184 
    https://profiles.impactstory.org/u/0000-0002-1296-8970 
  https://publons.com/a/721827 
     http://arxiv.org/a/prasad_s_1
 https://tinyurl.com/y99f9xca  
 	https://dblp.org/pers/hd/p/Prasad:Shiva_H=_C= 
    https://tinyurl.com/ycn4qppd
             https://tinyurl.com/y8fjstfe
http://researchid.co/hcshipra
http://researchid.co/rid13867

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/040h76494 in release v1.3.
