### ISSUE TITLE
Add a new organization to ROR: State Key Laboratory of Clean and Efficient Coal-Fired Power Generation and Pollution Control

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#8447]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: State Key Laboratory of Clean and Efficient Coal-Fired Power Generation and Pollution Control
Website: http://cestri.chnenergy.com.cn/kxjsyjyww/gjjyfpt/202107/faa343f050bc4c0f914c716b639a4483.shtml
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: State Key Lab of Clean and Efficient Coal-Fired Power Generation and Pollution Control
Acronym/abbreviation: 
Labels: 清洁高效燃煤发电与污染控制国家重点实验室*Chinese
Related organizations: https://ror.org/01s5v9a88 (parent)
City: Nanjing
Country: China
Geonames ID: 1799962
Year established: 
Other information about this request: Part of #8123. Supporting units: China Energy Science and Technology Research Institute Co., Ltd.

**Comment by adambuttrick** [comment]
Correct parent here is "China Energy Science and Technology Research Institute Co., Ltd.," but I'm having difficulty finding any further details about this. @huangjqq could you take a look?

**Comment by huangjqq** [comment]
For "China Energy Science and Technology Research Institute Co., Ltd.," 国家能源集团科学技术研究院有限公司 is the full Chinese name, http://cestri.chnenergy.com.cn/ is their website. Established in 2009, it's a subsidiary of China Guodian Corporation (https://ror.org/02zrmae98), based in Nanjing.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/056wcaa53 in release v1.41.
