### ISSUE TITLE
Add a new organization to ROR: State Key Laboratory of Virtual Reality Technology and Systems

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#8458]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: State Key Laboratory of Virtual Reality Technology and Systems
Website: https://vrlab.buaa.edu.cn
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 501100011160
Other names for the organization: 
Aliases: State Key Lab of Virtual Reality Technology and Systems; 虚拟现实技术国家重点实验室
Acronym/abbreviation: 
Labels: 虚拟现实技术与系统国家重点实验室*Chinese
Related organizations: https://ror.org/00wk2mp56 (parent) 
City: Beijing
Country: China
Geonames ID: 1816670
Year established: 
Other information about this request: Part of #8123. Supporting units: Beihang University.

**Comment by adambuttrick** [comment]
@huangjqq This was submitted with #8274 as two separate organizations. Although they have different names in Chinese, the supporting unit is actually the same for both, just under different aliases (Beihang University vs. Beijing University of Aeronautics and Astronautics). Could you take a look?

**Comment by huangjqq** [comment]
Yup, the supporting unit is definitely the same (Beihang is the short name for BUAA), and these are two different names for the same org -- the correct/current full form is on 8274

**Comment by adambuttrick** [comment]
Updated label and closed https://github.com/ror-community/ror-updates/issues/8274.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0009eea46 in release v1.43.
