### ISSUE TITLE
Add a new organization to ROR: State Key Laboratory of Power System and Generation Equipment

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#8478]
Summary of request: Add a new organization to ROR

Add record:
Name of organization: State Key Laboratory of Power System and Generation Equipment
Website: http://eesklab.tsinghua.edu.cn
Link to publications: 
Organization type: Facility
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 501100011284
Other names for the organization: 
Aliases: State Key Lab of Power System and Generation Equipment; State Key Laboratory of Safety Control and Simulation of Power System and Large-scale Power Generation Equipment; 电力系统及发电设备控制和仿真国家重点实验室
Acronym/abbreviation: 
Labels: 电力系统及大型发电设备安全控制和仿真国家重点实验室*Chinese
Related organizations: https://ror.org/03cve4549 (parent) 
City: Beijing
Country: China
Geonames ID: 1816670
Year established: 
Other information about this request: Part of #8123. Supporting units: Tsinghua University.

**Comment by adambuttrick** [comment]
https://github.com/ror-community/ror-updates/issues/8318 Appears to be the same lab as well.

**Comment by huangjqq** [comment]
8466 is the old/previous/original name -- same organization. 8318 has the same Chinese label as this entry, so these are definitely the same. Not sure about the official English name, but I'd just go by affiliation usage and list the other as an alias.

**Comment by adambuttrick** [comment]
Closed duplicates. Moving to release queue.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/043evzg22 in release v1.43.
