### ISSUE TITLE
All research outputs are from a single author. Single person organizations are out of scope for ROR.

### ISSUE THREAD

**Issue by gejoopur** [ror-community/ror-updates#8493]
The assessment was biased since it looked at just one volume (65): https://journal.geophysicsjournal.com/JofG/issue/view/26. However, vol. 65 only coincidentally contains works by one author. Importantly though, Geophysics Online has published the journal since vol. 63: https://journal.geophysicsjournal.com/JofG/issue/view/14, with various authors, and vol. 64: https://journal.geophysicsjournal.com/JofG/issue/view/25 also with different authors. The decision is unjustifiable. Please reconsider.

---
              All research outputs are from a single author. Single person organizations are out of scope for ROR.

_Originally posted by @adambuttrick in https://github.com/ror-community/ror-updates/issues/8096#issuecomment-1886013351_

**Comment by adambuttrick** [comment]
Address with comment on original issue, which has likewise been re-opened.
