### ISSUE TITLE
Add a new organization to ROR: STATE UNIVERSITY OF INFRASTRUCTURE AND TECHNOLOGIES

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#85]
Summary of request: Add a new organization to ROR

Name of organization: STATE UNIVERSITY OF INFRASTRUCTURE AND TECHNOLOGIES
Website: https://duit.edu.ua/
Link to publications: Https://doi.org/10.15587/1729-4061.2019.160456
Wikipedia page: https://uk.wikipedia.org/wiki/Державний_університет_інфраструктури_та_технологій
Wikidata ID: Q56368232
ISNI ID: https://isni.org/isni/0000000495295701
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: ДЕРЖАВНИЙ УНІВЕРСИТЕТ ІНФРАСТРУКТУРИ ТА ТЕХНОЛОГІЙ
Acronym/abbreviation: 
Related organizations: 
City: 9, KyrylivskaSt., Kyiv, Ukraine, 04071
Country: Ukraine
Other information about this request:

**Comment by carlyrobinson** [comment]
Agree, should be added to ROR.
