### ISSUE TITLE
Add a new organization to ROR: National Registry of Exonerations

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#86]
Summary of request: Add a new organization to ROR

Name of organization: National Registry of Exonerations
Website: http://www.law.umich.edu/special/exoneration/Pages/about.aspx
Link to publications: 
Wikipedia page: https://en.wikipedia.org/wiki/National_Registry_of_Exonerations
Wikidata ID: https://www.wikidata.org/wiki/Q6978009
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: UC Irvine, U. Michigan, Michigan State
City: 
Country: 
Other information about this request: We have 3 full-time employees (but they are all soft-money employees of UCI). We have 3 faculty editors who work for universities and work for the Registry without compensation. We have just created a non-profit organization, called the National Registry of Exonerations Foundation doing business as the National Registry of Exonerations, to raise money for the Registry. So I think we are an organization, but I guess the question is whether we are a "highest level" organization, as you put it, or we are a part of larger organizations (UCI, Michigan State, University of Michigan).

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/0553k7b06 in release v1.0.
