### ISSUE TITLE
Add a new organization to ROR: NBN Trust

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#87]
Summary of request: Add a new organization to ROR

Name of organization: NBN Trust
Website: We have begun a bibliography of research that cite the NBN Atlas: https://nbn.org.uk/tools-and-resources/nbn-atlas-citations/
Link to publications: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: 
Country: 
Other information about this request: "The National Biodiversity Network (NBN) is a collaborative partnership created to exchange biodiversity information.  The NBN Trust is the charity that oversees and facilitates the development of the NBN. We manage the NBN Atlas, which is the UK depository of biodiversity data and the UK GBIF node. 

We would like to encourage our data partners to use ROR identifiers when they share data with the NBN Atlas, and the first step is to have a ROR identifier for the NBN Atlas. We would ask people to use the ROR ID when they cite the NBN Atlas. 

I am not sure whether the ID should be for the NBN Atlas (which is the data portal) or for the NBN Trust (which manages the NBN Atlas)."

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00mcxye41 in release v1.0.
