### ISSUE TITLE
Add a new organization to ROR: Institute for the Study of Anthropic Impact and Sustainability in the Marine Environment

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#870]
Summary of request: Add a new organization to ROR

Name of organization: Institute for the Study of Anthropic Impact and Sustainability in the Marine Environment
Website: http://www.ricercamarina.cnr.it/en/ias.php
Link to publications: https://www.sciencedirect.com/science/article/pii/S0278434322001431; https://www.sciencedirect.com/science/article/pii/S1470160X22001285#!
Organization type: Other
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 8497 0708 
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Aliases: Institute for the Study of Anthropic Impact and Sustainability in the Marine Environment of the National Research Council
Labels: Istituto per lo studio degli impatti Antropici e Sostenibilità in ambiente marino*Italian
Acronym/abbreviation: IAS; IAS-CNR; CNR-IAS
Related organizations: https://ror.org/04zaypm56 (parent)
City: Rome
Country: Italy
Geonames ID: 3169070
Year established:
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
One of three organization's comprising https://ror.org/04zaypm56 's Institutes of Marine Science (http://www.ricercamarina.cnr.it/en/index.php). Independent, top-level entity, with solid affiliation usage. Funds and employs researchers. Should be added to ROR.

**Comment by mariagould** [comment]
Concur this should be added to ROR given independent status and publication activity.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/013fk0013 in release v1.3.
