### ISSUE TITLE
Add a new organization to ROR: Institute for Marine Biological Resources and Biotechnology

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#871]
Summary of request: Add a new organization to ROR

Name of organization: Institute for Marine Biological Resources and Biotechnology
Website: https://www.irbim.cnr.it
Link to publications: https://scholar.google.com/citations?hl=it&user=RZ3P1YYAAAAJ&view_op=list_works&sortby=pubdate ; https://www.sciencedirect.com/science/article/abs/pii/S0958166921001300#!
Organization type: Other
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 7693 4918
GRID ID:
Crossref Funder ID:
Other names for the organization:
Aliases: Institute for Marine Biological Resources and Biotechnology of the National Research Council
Labels: Istituto per le Risorse Biologiche e le Biotecnologie Marine*Italian
Acronym/abbreviation: IRBIM; IRBIM-CNR; CNR-IRBIM
Related organizations: https://ror.org/04zaypm56 (parent)
City: Messina
Country: Italy
Geonames ID: 2524170
Year established: 2018
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
One of three organization's comprising https://ror.org/04zaypm56 's Institutes of Marine Science (http://www.ricercamarina.cnr.it/en/index.php). Independent, top-level entity, with solid affiliation usage. Funds and employs researchers. Should be added to ROR.

Google Scholar affiliation usage: https://scholar.google.com/citations?user=Cld87qcAAAAJ; https://scholar.google.com/citations?user=Y4plvnMAAAAJ; https://scholar.google.com/citations?user=Foq3j_wAAAAJ; https://scholar.google.com/citations?user=Xoycj4cAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0002-0416-9634 ; https://orcid.org/0000-0002-8052-7544 ; https://orcid.org/0000-0003-4005-1278; https://orcid.org/0000-0001-5946-7877

**Comment by mariagould** [comment]
Concur this should be added to ROR given independent status and publication activity and per decision on #870.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00pb0ac76 in release v1.3.
