### ISSUE TITLE
Add a new organization to ROR:  Magnetics Information Consortium (MagIC) Data Repository

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#88]
Summary of request: Add a new organization to ROR

Name of organization: Magnetics Information Consortium (MagIC) Data Repository
Website: https://earthref.org/MagIC
Link to publications: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: 
Country: 
Other information about this request: We are a paleo and rock magnetic data repository supported by the NSF (https://www.earthref.org/MagIC). We would like to register with ROR in particular to use a ROR id in our data set schema.org headers and DataCite entries.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/00f89wy98 in release v1.0.
