### ISSUE TITLE
Modify the information in an existing ROR record: Instituto Portugues Da Qualidade https://ror.org/01pe22k85

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#9034]
Summary of request: Modify the information in an existing ROR record

Name of organization: Instituto Português da Qualidade
ROR ID: https://ror.org/01pe22k85
Which part of the record needs to be changed? Name, website
Description of change: Per IPQ-affiliated user email, the correct website for this organization is https://www.ipq.pt In addition, the name of the organization should be changed to include the correct accent marks and capitalization: Instituto Português Da Qualidade

Update: change.name==Instituto Português Da Qualidade; replace.links==https://www.ipq.pt;$

**Comment by adambuttrick** [comment]
Confirmed name correction via the organization's site.

**Comment by adambuttrick** [comment]
Record updated in release v1.41.
