### ISSUE TITLE
Add a new organization to ROR: International Society for the Advancement of Spine Surgery

### ISSUE THREAD

**Issue by parivalavanm** [ror-community/ror-updates#9072]
Summary of request: Add a new organization to ROR

Name of organization: International Society for the Advancement of Spine Surgery
Website: https://isass.org
Link to publications: https://www.ijssurgery.com/content/current
Organization type: Other 
Wikipedia page:
Wikidata ID:
ISNI ID: 0000 0004 7777 4063
GRID ID:
Crossref Funder ID: 100013744
Other names for the organization:
Aliases:
Labels
Acronym/abbreviation: ISASS
Related organizations: 
City: Wheaton
Country: USA
Geonames ID: 4916288
Year established: 2000
How will a ROR ID for this organization be used? 
Other information about this request: To be integrated in a scholarly publishing system

**Comment by adambuttrick** [comment]
Professional society in the US. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/02cjm2b20 in release v1.41.
