### ISSUE TITLE
Add a new organization to ROR: Accord University

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#9115]
Summary of request: Add a new organization to ROR

Name of organization: Accord University
Website: https://accord.edu.so
Link to publications: 
Organization type: Education
Wikipedia page: 
Wikidata ID: 
ISNI: 0000 0005 0817 0052
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: 
Labels: 
Acronym/abbreviation: 
Related organizations: 
City: Mogadishu
Country: Somalia
Geonames ID: 53654
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: Follows from https://github.com/ror-community/ror-updates/issues/9114.

**Comment by adambuttrick** [comment]
University in Somalia. Affiliation usage appears primarily to be works hosted in Zenodo. There are some secondary references [here](https://doi.org/10.1080/23311886.2022.2110199) and [here](https://www.google.com/books/edition/Media_and_Technology_in_21st_Century_Hig/9uPiEAAAQBAJ?hl=en&gbpv=1&bsq=%22Accord%20University%22), so this may be fine to add, but I would appreciate a second review.

**Comment by ssmulyan** [comment]
To try and uncover more affiliation usage, I started from their [faculty list](https://www.accord.edu.so/contacts-by-faculty) and looked for publication by those researchers.  That didn't turn up any additional Accord University affiliations, unfortunately.  Most of the listed faculty members seem to all be located outside Somalia, and have primary affiliations with other institutions.  Some of them listed their relationship with accord as "consultant" or "advisor" on their linkedin profiles or elsewhere. 

The affiliation for "Accord Institute" found by the bot is inaccurate.  The Zenodo records all seem to be situations where Accord University is the publisher, not author affiliation: Accord University Economic Journal, Accord University Health Journal, Accord University Humanity & Social Science Journal, etc.  But there are no records for any of those journals (or the named publisher "Wisdom Company Limited") outside of Zenodo either. 

I don't think these things rule them out, but it's hard to find something definitively to rule them in either.

**Comment by adambuttrick** [comment]
Given absence of evidence of research outputs and funding activities, declining for now. If the requestor can provide and we will reassess.
