### ISSUE TITLE
Project: Link corrections for https://ror.org/041qv0h25 children

### ISSUE THREAD

**Issue by marcelriedel** [ror-community/ror-updates#9169]
Summary of request: Modify the information in an existing ROR record

Name of organization: 
ROR ID: https://ror.org/041qv0h25

Which part of the record needs to be changed? 
Website (URL)

Description of change:
The DAI has launched it´s new homepage a couple of weeks before: https://www.dainst.org/
Since this launch the former sub-domains, representing the dai-departements (all childs of https://ror.org/041qv0h25), are broken. Unfortunately we cannot implement a good working redirect solution.

So we like to update the website url for all childs as follow:

https://ror.org/023md1f53 => https://www.dainst.org/rom
https://ror.org/05q9y3f51 => https://www.dainst.org/istanbul
https://ror.org/05wps8h17 => https://www.dainst.org/kairo
https://ror.org/03tg3dp70 => https://www.dainst.org/dai-standorte/orient-abteilung
https://ror.org/04e1nss61 => https://www.dainst.org/madrid
https://ror.org/0503gdw52 => https://www.dainst.org/eurasien
https://ror.org/05nqsnd28 => https://www.dainst.org/athen
https://ror.org/01fqayw81 => https://www.dainst.org/rgk
https://ror.org/02rspp784 => https://www.dainst.org/kaak

**Comment by adambuttrick** [comment]
Converting to project issue for bulk correction. I've tagged all as separate issues here.

**Comment by adambuttrick** [comment]
Updated in release v1.42.

**Comment by marcelriedel** [comment]
Thank you!
