### ISSUE TITLE
Add a new organization to ROR: e-teaching.org

### ISSUE THREAD

**Issue by Arkusm** [ror-community/ror-updates#9278]
Summary of request: Add a new organization to ROR

Name of organization: e-teaching.org
Website: https://www.e-teaching.org/
Link to publications: https://www.e-teaching.org/materialien/artikel
Organization type: Education, Nonprofit
Wikipedia page: https://de.wikipedia.org/wiki/E-teaching.org
Wikidata ID: https://www.wikidata.org/wiki/Q118148636
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/03hv28176
City: Tübingen
Country: Germany
Geonames ID: https://www.geonames.org/2820860/tuebingen.html
Year established: 2003
How will a ROR ID for this organization be used? To fill in the publisher attributes during DOI registration via DataCite Fabrica.
Other information about this request:
e-teaching.org is a non-commercial, freely accessible, German-language Internet portal on the use of digital media in higher education teaching. The portal was launched in 2003 and contains a wide range of academic and practice-oriented publications on the use of digital media in higher education.

**Comment by adambuttrick** [comment]
Online learning platform in Germany. Currently developed/housed at https://ror.org/03hv28176, but has had many other organizational contributors and financial backers. That being said, this is listed as a project of https://ror.org/03hv28176 vs. a discrete organization ('Das Portal ist ein Projekt des [Leibniz-Instituts für Wissensmedien), which would indicate using the parent-level ID is more appropriate here. Will confer with DataCite colleagues about the proper use of publisher as well.

**Comment by KellyStathis** [comment]
On DataCite's end, the DataCite Metadata Schema does not prescribe that a Publisher is an organization, nor that publisherIdentifier is a ROR ID. You can see other example values for publisherIdentifierScheme here: https://datacite-metadata-schema.readthedocs.io/en/4.5/properties/publisher/ - including Wikidata.

I see you're using Fabrica to create DOIs. The Fabrica form was implemented with a lookup for ROR IDs. If your publisher is not in ROR, you have two options with the Fabrica form:
- you can still provide "e-teaching.org" as the publisher name without a publisherIdentifier: https://support.datacite.org/docs/field-descriptions-for-form#publisher
- you can add a different publisherIdentifier using the file upload tool to edit the XML: https://support.datacite.org/docs/fabrica-create-doi-file-upload

Feel free to reach out to us at support@datacite.org if you have any questions about this.
