### ISSUE TITLE
Modify the information in an existing ROR record: Aragón Materials Science Institute (https://ror.org/031n2c920)

### ISSUE THREAD

**Issue by arthurpsmith** [ror-community/ror-updates#93]
Summary of request: Modify the information in an existing ROR record

Name of organization: Aragón Materials Science Institute
ROR ID: https://ror.org/031n2c920
Which part of the record needs to be changed? Primary name, other names, website
Description of change: Now 'Instituto de Nanociencia y Materiales de Aragón' (Spanish)/'Aragon Nanoscience and Materials Institute' (English) - acronym INMA, website https://inma.unizar-csic.es/ - see https://inma.unizar-csic.es/el-instituto/informacion-general/historia/ - this was after a merger with another university institute so maybe this should be a new ID?

MG Note:
Add aliases: Institute of Research in Nanoscience of Aragon; Aragón Materials Science Institute 

Update: add.aliases==Institute of Research in Nanoscience of Aragon; add.aliases==Aragón Materials Science Institute;

**Comment by mariagould** [comment]
Determination: We need to create a new ROR ID for INMA and redirect the existing two records to the new one.

**Comment by mariagould** [comment]
Update: 
Aragon Materials Science Institute (https://ror.org/031n2c920) maps to GRID ID grid.466773.7. The GRID record has been updated with a new name: Instituto de Nanociencia y Materiales de Aragón. Therefore, we may want to consider whether we should create a new record for the Institute of Nanoscience.

**Comment by mariagould** [comment]
Reviewing this one again with a final recommendation: We have an entry in ROR (https://ror.org/031n2c920) for Instituto de Nanociencia y Materiales de Aragón (INMA), an entity created in 2020 that fused the Institute of Research in Nanoscience of Aragon (INA) (no prior ROR ID) and Aragón Materials Science Institute (ICMA) (the name previously used in https://ror.org/031n2c920). The new institute name is being used as an affiliation in publications, e.g., https://doi.org/10.1016/j.cej.2020.126103.

My recommendation is that we add the prior names Institute of Research in Nanoscience of Aragon and Aragón Materials Science Institute as aliases to the existing record. 

Posting this comment in #195 as well.

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
