### ISSUE TITLE
Deprecate Institutes absorbed by the Biology Centre of the Czech Academy of Sciences

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#936]
Per #784, five institutes associated with the Czech Academy of Sciences have been absorbed into https://ror.org/05pq4yn02 as departments. These records should be deprecated/made inactive.

    https://ror.org/039nazg33 - Institute of Entomology
    https://ror.org/0436nxt45 - Institute of Hydrobiology (ASCR)
    https://ror.org/05rhyza23 - Institute of Parasitology
    https://ror.org/00jr65m43 - Institute of Plant Molecular Biology
    https://ror.org/02tz8r820 - Institute of Soil Biology

**Comment by adambuttrick** [comment]
Closing this issue now that separate ones for each institute have been created.

**Comment by janderova** [comment]
Hello Adam,

is it possible to add to the record https://ror.org/05pq4yn02 Biology Centre of the Czech Academy of Sciences
relationship - Predecessors - the five institutes?
https://ror.org/039nazg33 - Institute of Entomology
https://ror.org/0436nxt45 - Institute of Hydrobiology (ASCR)
https://ror.org/05rhyza23 - Institute of Parasitology
https://ror.org/00jr65m43 - Institute of Plant Molecular Biology
https://ror.org/02tz8r820 - Institute of Soil Biology
Thank you 
Katerina Janderova

**Comment by adambuttrick** [comment]
@janderova Certainly. We should be able to add these in our next release.

https://github.com/ror-community/ror-updates/issues/2068
