### ISSUE TITLE
Project: University of Belgrade - https://ror.org/02qsmb048 Faculties

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#9399]
Per curation team review and discussion of https://github.com/ror-community/ror-updates/issues/7057, https://github.com/ror-community/ror-updates/issues/7206, and https://github.com/ror-community/ror-updates/issues/8521, the University of Belgrade's faculties can be added as they are separately accredited, discrete legal entities. Instead of being added piecemeal, these should all be included in a single release, with consistent representation across all. Specific attention should be given to their naming, so as to avoid false positive matches with the sub-organizational units of other universities.

**Comment by lessormore4** [comment]
Can we (locals) help push this forward? By the way, the official naming convention is University of Belgrade - Faculty of ....

**Comment by adambuttrick** [comment]
@lessormore4 Apologies, we will include the three records tagged here in our next major release. We've received a high-volume of bulk submissions recently and prioritize on the basis of completeness.

**Comment by lessormore4** [comment]
No problem at all! Thanks! Can we make submissions for the remaining faculties?

**Comment by adambuttrick** [comment]
@lessormore4 Yes, if you could complete using the attached spreadsheet and add a comment with file here, we can process faster/all in the next major release. If possible, please use the same name format for the English and Serbian name forms, e.g. University of Belgrade - Faculty of Geography, Univerzitet u Beogradu - Geografski fakultet, and  Универзитет у Београду – Географски факултет. 
[ROR Bulk New Record Template.xlsx](https://github.com/ror-community/ror-updates/files/15278639/ROR.Bulk.New.Record.Template.xlsx)
an

**Comment by lessormore4** [comment]
Thanks and no problem! They all have the same name format (it was unified 10+ years ago) but people tend to use the old names. Do you want me to add https://github.com/ror-community/ror-updates/issues/7057, https://github.com/ror-community/ror-updates/issues/7206, and https://github.com/ror-community/ror-updates/issues/8521and https://github.com/ror-community/ror-updates/issues/6370 in the table?

**Comment by adambuttrick** [comment]
@lessormore4 No, you can leave the issue that have already been submitted out. The old or former names can also be added as additional aliases, where there is affiliation usage that makes use of those forms.

**Comment by lessormore4** [comment]
The spreadsheet with the remaining independent members of the University of Belgrade:
[ROR.Bulk.New.Record.University-of-Belgrade.xlsx](https://github.com/user-attachments/files/15688155/ROR.Bulk.New.Record.University-of-Belgrade.xlsx)
Tank you for your collaboration. If additional information is needed, I'll be happy to provide it.

**Comment by adambuttrick** [comment]
All records added in release v1.48.
