### ISSUE TITLE
Project: New Records from Long Tail Funder Registry Reconciliation pt. 2

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#9522]
As part of https://github.com/ror-community/ror-updates/issues/2620, @hnew1 has identified a set of new records that should be added to the registry. These should be reviewed and improved for completeness of metadata.
[20240222_long_tail_new_records.xlsx](https://github.com/ror-community/ror-updates/files/14381656/20240222_long_tail_new_records.xlsx)

**Comment by hnew1** [comment]
Child records now processed.

**Comment by adambuttrick** [comment]
Added in release v1.44.
