### ISSUE TITLE
Add a new organization to ROR: Astex Pharmaceuticals

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#957]
Summary of request: Add a new organization to ROR

Name of organization: Astex Pharmaceuticals
Website: https://astx.com
Link to publications: 
Organization type: Company
Wikipedia page: https://en.wikipedia.org/wiki/Astex_Pharmaceuticals
Wikidata ID: Q106995996
ISNI ID: 0000 0004 0411 1795
GRID ID:
Crossref Funder ID: 100013870
Other names for the organization: 
Acronym/abbreviation:
Related organizations: https://ror.org/013k5y296 (parent)
City: Pleasanton, CA
Country: USA
Geonames ID: 5383777
Year established: 2011
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment]
Successor organization to https://ror.org/049922318, as identified in #955. Pharmaceutical company with offices in the US and UK. Independent, top-level entity with solid affiliation usage. Funds and employs researchers. Should be added to ROR.

#955 suggests we should add both the US and UK branch, but I think we should move away from the practice of creating separate records for national-level corporate offices that we inherited of GRID. What I think is actually needed is for address to be a repeatable field.

Publication affiliation usage: https://europepmc.org/article/med/35512344 ; https://pubs.acs.org/doi/abs/10.1021/acs.jmedchem.2c00164 ; https://eprints.soton.ac.uk/448304/1/ParaMol_paper.pdf

Google Scholar affiliation usage: https://scholar.google.com/citations?user=RvCGvpoAAAAJ; https://scholar.google.com/citations?user=WKL574IAAAAJ; https://scholar.google.com/citations?user=f_pF6fQAAAAJ

ORCID affiliation usage: https://orcid.org/0000-0002-1143-7289 ; https://orcid.org/0000-0002-2688-5965 ; https://orcid.org/0000-0003-3839-9806

**Comment by mariagould** [comment]
I concur this is in scope, and I agree that we should only create one record for both branches.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05fx1fs38 in release rc-v1.5.
