### ISSUE TITLE
Modify the information in an existing ROR record: 
State Forestry and Grassland Administration (https://ror.org/03f2n3n81)


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#96]
Summary of request: Modify the information in an existing ROR record

Name of organization: State Forestry and Grassland Administration
ROR ID: https://ror.org/03f2n3n81
Description of change: As the Chinese native speaker, I found the Chinese affiliation name is wrong in the above ROR ID. The correct Chinese name of State Forestry and Grassland Administration is "国家林业和草原局" in stead of "国家林业局森林病虫害防治总站", for the existing name is just a station of the State Forestry and Grassland Administration, not itself. Please see here: http://www.forestry.gov.cn/main/6006/index.html

Update:delete.labels==国家林业局森林病虫害防治总站; add.labels==国家林业和草原局*Chinese; delete.links==http://english.forestry.gov.cn/; add.links==http://www.forestry.gov.cn/;

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
