### ISSUE TITLE
Update record for ROR https://ror.org/01wx1q736: Kryvyi Rih State Pedagogical University

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#97]
Summary of request: Update ROR record

Curator comments (MG):
The name in the record was updated in ROR's September release. The prior name should be added as an alias to aid in discovery. The Ukrainian acronym should also be added to the metadata. 

In summary:
1. Add alias `Krivoy Rog State Pedagogical Institute`
2. Add Ukrainian acronym `КДПУ`

----
**Prior metadata submitted originally to request a new record:**
Name of organization: Kryvyi Rih State Pedagogical University
ROR ID: https://ror.org/01wx1q736
Website: http://www.kdpu.edu.ua
Link to publications: https://www.scopus.com/authid/detail.uri?authorId=57216844651, https://www.scopus.com/authid/detail.uri?authorId=15081138900,
https://www.scopus.com/authid/detail.uri?authorId=36620754500,
https://www.scopus.com/authid/detail.uri?authorId=56375008500,
https://scholar.google.com.ua/citations?user=d-c3KWYAAAAJ&hl=en&oi=ao
Wikipedia page: 
Wikidata ID: DOI https://doi.org/10.31812
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: Криворізький державний педагогічний університет, КДПУ, KDPU
Acronym/abbreviation: 
Related organizations: 
City: 50086, Kryvyi Rih, Haharin av. 54
Country: 
Other information about this request: 

----
KS - Metadata:
Wikipedia page: **https://en.wikipedia.org/wiki/Kryvyi_Rih_State_Pedagogical_University**
Wikidata ID: **https://www.wikidata.org/wiki/Q12114710**
ISNI ID: n/a
GRID ID: n/a
Crossref Funder ID: n/a
Ringgold ID: n/a
Other names for the organization: Криворізький державний педагогічний університет, КДПУ, KDPU
Acronym/abbreviation: 
Related organizations: 
City: 50086, Kryvyi Rih, Haharin av. 54
Country: **Ukraine**
Other information about this request: 

Update: change.name==Krivoy Rog State Pedagogical Institute; add.acronyms==КДПУ;

**Comment by mariagould** [comment]
Cleaning up the details of this change (will paste a summary in the issue body as well):

The prior primary name in the record was "Krivoy Rog State Pedagogical Institute". The name was adjusted in GRID to be Kryvyi Rih State Pedagogical University. This change was synced to ROR in our final release. Per Wikipedia, Krivoy Rog is an alternate name for Kryvyi Rih (https://en.wikipedia.org/wiki/Kryvyi_Rih). 

The primary name in ROR is now up to date. There are two changes we should make to the existing record:

1. Add alias `Krivoy Rog State Pedagogical Institute`
2. Add Ukrainian acronym `КДПУ`

**Comment by adambuttrick** [comment]
Record updated in release v1.0.
