### ISSUE TITLE
Merge existing ROR records: 04ma29860 , 022rydv31 

### ISSUE THREAD

**Issue by VladimirAlexiev** [ror-community/ror-updates#9821]
Summary of request: merge existing ROR records

Name of organization: Fishing in Ireland
ROR ID: 04ma29860 , 022rydv31 
Which part of the record needs to be changed? Merge the two
Description of change: The two records have the same ISNI and nearly the same website:
- https://ror.org/04ma29860 : http://www.fishinginireland.info/
- https://ror.org/022rydv31 : https://www.fisheriesireland.ie/

**Comment by adambuttrick** [comment]
https://ror.org/04ma29860 appears to be a duplicate entry for https://ror.org/022rydv31, so I will process with.separate deprecation issue.

**Comment by adambuttrick** [comment]
Updated in release v1.43.
