### ISSUE TITLE
Modify the information in an existing ROR record: 02gmp5156 

### ISSUE THREAD

**Issue by VladimirAlexiev** [ror-community/ror-updates#9822]
Summary of request: Modify the information in an existing ROR record
Name of organization: National Research Foundation of **Ukraine**
ROR ID: https://ror.org/02gmp5156 
Which part of the record needs to be changed? The ISNI is wrong
Description of change:
* https://isni.org/isni/0000000458970237 is National Research Foundation of **Korea**
* 

Update: delete.ISNI==0000 0004 5897 0237;$

**Comment by adambuttrick** [comment]
Confirmed errant ISNI ID assignment.

**Comment by adambuttrick** [comment]
Record updated in release v1.43.
