### ISSUE TITLE
Add a new organization to ROR: Lviv University of Business and Law

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#99]
Summary of request: Add a new organization to ROR

Name of organization: Lviv University of Business and Law
Website: http://lubp.com.ua/
Link to publications: https://edirc.repec.org/data/lubplua.html
Wikipedia page: https://uk.wikipedia.org/wiki/Львівський_університет_бізнесу_та_права
Wikidata ID: Q16705458
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Ringgold ID: 
Other names for the organization: Львівський університет бізнесу та права
Acronym/abbreviation: 
Related organizations: 
City: 99 Kulparkіvska Street, Lviv, 79021, Ukraine
Country: Ukraine
Other information about this request:

**Comment by carlyrobinson** [comment]
I agree with @arthurpsmith assessment and would recommend adding to ROR.

**Comment by adambuttrick** [comment]
Assigned ROR ID https://ror.org/05x83ep82 in release v1.0.
