### ISSUE TITLE
Modify the information in an existing ROR record: Plymouth College of Art https://ror.org/00fpvte21

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-updates#9953]
Summary of request: Modify the information in an existing ROR record

Name of organization: Plymouth College of Art
ROR ID: https://ror.org/00fpvte21
Which part of the record needs to be changed? Name, Website
Description of change: Organisation is now called Arts University Plymouth as per email from org representative. Current website http://www.plymouthart.ac.uk/ also redirects to https://www.aup.ac.uk/ and uses the new name. 

Update: change.name==Arts University Plymouth; add.aliases==Plymouth College of Art; replace.links==https://www.aup.ac.uk;$

**Comment by adambuttrick** [comment]
Confirmed name change via the organization's site.

**Comment by adambuttrick** [comment]
Record updated in release v1.43.
